### ISSUE TITLE
Error on https://www.htfgames.com/games/after_amok.htm

### ISSUE THREAD

**Issue by marblyn** [ruffle-rs/ruffle#14181] opened 2023-11-26 18:59 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display3D/textures/atf_jpegxr.rs:26:55:
Failed to parse ATF texture: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display3D/textures/atf_jpegxr.rs:26:55:
Failed to parse ATF texture: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.8a79229e95b2762242c4.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h878d7563074f0d48 (wasm://wasm/03371cf6:wasm-function[9797]:0x9b1624)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/03371cf6:wasm-function[6282]:0x8a1d32)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/03371cf6:wasm-function[9604]:0x9ac59c)
    at core::result::unwrap_failed::hbe79a418fab461ff (wasm://wasm/03371cf6:wasm-function[7621]:0x911213)
    at ruffle_core::avm2::globals::flash::display3D::textures::atf_jpegxr::do_compressed_upload::h28c38f0665cf7f87 (wasm://wasm/03371cf6:wasm-function[716]:0x2116ed)
    at ruffle_core::avm2::globals::flash::display3D::textures::texture::upload_compressed_texture_from_byte_array_internal::hcc046e015034c88d (wasm://wasm/03371cf6:wasm-function[3668]:0x742deb)
    at ruffle_core::avm2::function::Executable::exec::h82c15fca8f46a2ab (wasm://wasm/03371cf6:wasm-function[865]:0x2f7a8d)
    at ruffle_core::avm2::object::TObject::call_property::hdd24804f71e6161f (wasm://wasm/03371cf6:wasm-function[1258]:0x414bac)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h18eb352805db57c4 (wasm://wasm/03371cf6:wasm-function[2817]:0x67aa68)
```
AVM2 stack:
```
    at flash.display3D.textures::Texture/flash::display3D::textures::Texture::uploadCompressedTextureFromByteArrayInternal()
    at MethodInfo-2322()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti (0x00001C82) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: aa2.swf
Param quality: high
Param wmode: direct
Param swfversion: 6.0.65.0
Param expressinstall: ../scripts/expressInstall.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.htfgames.com/games/after_amok.htm
SWF URL: https://www.htfgames.com/games/aa2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-26
Channel: nightly
Built: 2023-11-26T00:15:21.702Z
Commit: d3b9d8a4516a985a78d8a081a764aacabd8e3b6d
Is extension: false

# Metadata
width: 1140
height: 640
frameRate: 25
numFrames: 1
swfVersion: 31
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 8036149

**Comment by Lord-McSweeney** [comment] 2023-11-26 19:12
Duplicate of #13990 (already fixed)

**Closed by Lord-McSweeney** 2023-11-26 19:12 UTC
Labels: error-report
