### ISSUE TITLE
Error on http://www.officegamespot.com/freegames/electric-man-2.htm

### ISSUE THREAD

**Issue by fernandozh1234** [ruffle-rs/ruffle#6626] opened 2022-04-05 01:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.officegamespot.com/ruffle/ruffle.js:1:6906)
    at std::sync::once::Once::call_once::{{closure}}::h5c607ed08f988e53 (http://www.officegamespot.com/ruffle/1554e5eaeee087dcdfe9.wasm:wasm-function[999]:0x2e7fa5)
    at std::sync::once::Once::call_inner::hf1b92ab8c222362b (http://www.officegamespot.com/ruffle/1554e5eaeee087dcdfe9.wasm:wasm-function[1324]:0x35ad17)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3097032c631d0165 (http://www.officegamespot.com/ruffle/1554e5eaeee087dcdfe9.wasm:wasm-function[4549]:0x4e1373)
    at std::panicking::rust_panic_with_hook::ha223473efd20893e (http://www.officegamespot.com/ruffle/1554e5eaeee087dcdfe9.wasm:wasm-function[3244]:0x49d7c1)
    at rust_begin_unwind (http://www.officegamespot.com/ruffle/1554e5eaeee087dcdfe9.wasm:wasm-function[4610]:0x4e362d)
    at core::panicking::panic_fmt::hca0bee0b11468063 (http://www.officegamespot.com/ruffle/1554e5eaeee087dcdfe9.wasm:wasm-function[4810]:0x4edfef)
    at core::panicking::panic::hb05521048dcb55f3 (http://www.officegamespot.com/ruffle/1554e5eaeee087dcdfe9.wasm:wasm-function[4543]:0x4e0b20)
    at core::ops::function::FnOnce::call_once::he4935335e83056c8 (http://www.officegamespot.com/ruffle/1554e5eaeee087dcdfe9.wasm:wasm-function[1045]:0x304f96)
    at ruffle_core::avm1::function::Executable::exec::h7e21bfb6cef675c1 (http://www.officegamespot.com/ruffle/1554e5eaeee087dcdfe9.wasm:wasm-function[434]:0x15a5f5)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.officegamespot.com/freegames/electric-man-2.htm
SWF URL: http://www.officegamespot.com/freewebgames/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-29
Channel: nightly
Built: 2021-10-29T00:13:28.079Z
Commit: a1130b973fc1dd4bc08114121eb60dc2427f84cb
Is extension: false

**Comment by relrelb** [comment] 2022-04-05 05:49
Duplicate of #4932.

**Closed by relrelb** 2022-04-05 05:49 UTC
