### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by Goodart-Bit** [ruffle-rs/ruffle#15375] opened 2024-03-01 12:35 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.


    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3391:21)
    at js_sys::Error::new::h5edd0775a3c60fbf (wasm://wasm/038ef09a:wasm-function[13778]:0xafc08b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb886bdb533e9c413 (wasm://wasm/038ef09a:wasm-function[11393]:0xaa6d2a)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/038ef09a:wasm-function[6933]:0x964cf2)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/038ef09a:wasm-function[11099]:0xaa014e)
    at core::ops::function::Fn::call::hc897e573079af08a (wasm://wasm/038ef09a:wasm-function[7257]:0x97c50a)
    at wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::h57d2886041e33ed7 (wasm://wasm/038ef09a:wasm-function[5740]:0x8f515f)
    at <T as wgpu::context::DynContext>::device_create_buffer::h66fb375edefd330b (wasm://wasm/038ef09a:wasm-function[8004]:0x9c69b4)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hcf982c9be24df9cb (wasm://wasm/038ef09a:wasm-function[2020]:0x5732c6)
    at core::cell::once::OnceCell<T>::get_or_try_init::outlined_call::he4ff31f44e624520 (wasm://wasm/038ef09a:wasm-function[6532]:0x943c59)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 (0x00005917) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-02-29
Channel: nightly
Built: 2024-02-29T00:05:52.876Z
Commit: a03355458f25ce64fea37708ff63876db829b152
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 19988205

**Comment by Dinnerbone** [comment] 2024-07-12 22:01
Duplicate of #14913

**Closed by Dinnerbone** 2024-07-12 22:01 UTC
Labels: duplicate, error-report, wgpu-oom
