### ISSUE TITLE
Error on https://electricman2.club/

### ISSUE THREAD

**Issue by GarrenCox** [ruffle-rs/ruffle#6257] opened 2022-02-12 14:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (wasm://wasm/0186af7a:wasm-function[1032]:0x303aa1)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (wasm://wasm/0186af7a:wasm-function[1171]:0x3397a9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (wasm://wasm/0186af7a:wasm-function[4680]:0x4d6936)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (wasm://wasm/0186af7a:wasm-function[3195]:0x48c602)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (wasm://wasm/0186af7a:wasm-function[4954]:0x4e26c1)
    at core::panicking::panic::h35778e3c18266c93 (wasm://wasm/0186af7a:wasm-function[4677]:0x4d645d)
    at core::ops::function::FnOnce::call_once::h63635e87c343a6bd (wasm://wasm/0186af7a:wasm-function[1068]:0x319d58)
    at ruffle_core::avm1::function::Executable::exec::h2f4c44ab37d80dc0 (wasm://wasm/0186af7a:wasm-function[414]:0x157014)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hd2ac2ca7aecc5e6d (wasm://wasm/0186af7a:wasm-function[624]:0x223065)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://electricman2.club/electric-man-2.swf
Param game: https://electricman2.club/electric-man-2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://electricman2.club/
SWF URL: https://electricman2.club/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-21
Channel: nightly
Built: 2022-01-21T00:17:44.053Z
Commit: 4d8db1e64d36cc59c98c63b6883971cf01c5c9e3
Is extension: false

**Comment by relrelb** [comment] 2022-02-12 18:25
Duplicate of #4932.

**Closed by relrelb** 2022-02-12 18:25 UTC
Labels: error-report
