### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by jeanpierre117** [ruffle-rs/ruffle#3885] opened 2021-04-03 17:24 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1617202287:1:6915)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ea72e7bd92c6a211ab42071518cef232.wasm:wasm-function[1187]:0x2837d7)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ea72e7bd92c6a211ab42071518cef232.wasm:wasm-function[1773]:0x2fe79a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ea72e7bd92c6a211ab42071518cef232.wasm:wasm-function[5274]:0x40ae40)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://uploads.ungrounded.net/ruffle_wrapper/lib/ea72e7bd92c6a211ab42071518cef232.wasm:wasm-function[4049]:0x3dc94d)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (https://uploads.ungrounded.net/ruffle_wrapper/lib/ea72e7bd92c6a211ab42071518cef232.wasm:wasm-function[4752]:0x3fd57d)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (https://uploads.ungrounded.net/ruffle_wrapper/lib/ea72e7bd92c6a211ab42071518cef232.wasm:wasm-function[5647]:0x410b58)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/ea72e7bd92c6a211ab42071518cef232.wasm:wasm-function[5518]:0x40f19c)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ea72e7bd92c6a211ab42071518cef232.wasm:wasm-function[5649]:0x410bbc)
    at std::thread::local::LocalKey<T>::with::h6d81463357c6f29a (https://uploads.ungrounded.net/ruffle_wrapper/lib/ea72e7bd92c6a211ab42071518cef232.wasm:wasm-function[871]:0x220712)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1617202287%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F512000%2F512407_hank2009.swf%3F1605221180%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226068a23ee1b00%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A720%2C%22height%22%3A405%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F512000%2Fflash_512407_card.png%3Ff1605218420%22%7D
SWF URL: https://uploads.ungrounded.net/512000/512407_hank2009.swf?1605221180

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-31
Channel: nightly
Built: 2021-03-31T00:37:28.936Z
Commit: 5cefaa16d2c29dac0e573967477126f31bb69075

**Comment by relrelb** [comment] 2021-04-03 18:28
Duplicate of #3884.

**Closed by relrelb** 2021-04-03 18:28 UTC
