### ISSUE TITLE
Error on https://extrememath.net/swf.html

### ISSUE THREAD

**Issue by drakethebest** [ruffle-rs/ruffle#7921] opened 2022-09-08 20:34 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:812:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:812:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.a3e1b9cde9a38610e086.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::h00e9527065505d48 (wasm://wasm/01707642:wasm-function[939]:0x269559)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/01707642:wasm-function[1391]:0x2f25a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h962959d96d2b047f (wasm://wasm/01707642:wasm-function[4847]:0x44ec00)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/01707642:wasm-function[3618]:0x4188af)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/01707642:wasm-function[5030]:0x455202)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/01707642:wasm-function[4934]:0x450426)
    at core::ops::function::FnOnce::call_once::h3462a087907747a9 (wasm://wasm/01707642:wasm-function[1040]:0x28ad95)
    at ruffle_core::avm1::function::Executable::exec::hd250bd9376154bb0 (wasm://wasm/01707642:wasm-function[352]:0xd737d)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h2945afc5b30b046e (wasm://wasm/01707642:wasm-function[822]:0x2396c5)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://extrememath.net/swf.html?notebook=electricman2
SWF URL: https://extrememath.net/swffiles/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14909.132.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-08
Channel: nightly
Built: 2022-09-08T00:16:33.182Z
Commit: ece4b9a76dd825a1664f06c22622f1066cc69011
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3641749

**Comment by n0samu** [comment] 2022-09-08 21:09
Duplicate of #4932

**Closed by n0samu** 2022-09-08 21:09 UTC
Labels: duplicate, error-report
