### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Gamerwolf5958** [ruffle-rs/ruffle#6762] opened 2022-04-20 21:23 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/shape_utils.rs:186:38
Error stack:
```
@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.5fac0900d56c49d8cc28.js:1:7717
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h07d0245bef259c27]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h623ac32ff431b114]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h5118e89563022e7e]@[wasm code]
<?>.wasm-function[core::panicking::panic::he88f1b1582b09c8c]@[wasm code]
<?>.wasm-function[ruffle_core::shape_utils::ActivePath::flush_fill::h932e3cafc7a245af]@[wasm code]
<?>.wasm-function[ruffle_core::shape_utils::ShapeConverter::flush_layer::h66beb67534a7dd6e]@[wasm code]
<?>.wasm-function[<ruffle_core::shape_utils::DistilledShape as core::convert::From<&swf::types::Shape>>::from::h6e92fa6608141852]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::ha98dc4b982c17625]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::hbaf6f019c2eaff27]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h1a20254dba634c51]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h903ee168fc90b9ee]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h33ed72626bb34236]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::he8e3ce0ab6352214]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h40f6ecbecfe0d2cc]@[wasm code]
wasm-stub@[native code]
O@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.5fac0900d56c49d8cc28.js:1:3868
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.5fac0900d56c49d8cc28.js:1:2393
promiseReactionJob@[native code]
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1650293381%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F840000%2F840508_pdtd.swf%3F1650467843%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2245639879.98163bcb470626b630f14bef73727e18fa4e4bd2ec6abc%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22626078a652d70%22%2C%22NewgroundsAPI_SessionID%22%3A%22rb0igKxpOBT7C5I2jdoVdcd93117e349b5b339942eb3c858a51a28ae3907Odze%22%2C%22NewgroundsAPI_UserName%22%3A%22Gamerwolf5958%22%2C%22NewgroundsAPI_UserID%22%3A9632548%2C%22ng_username%22%3A%22Gamerwolf5958%22%7D%2C%22width%22%3A800%2C%22height%22%3A450%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F840000%2Fflash_840508_card.png%3Ff1650467849%22%7D
SWF URL: https://uploads.ungrounded.net/840000/840508_pdtd.swf?1650467843

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-18
Channel: nightly
Built: 2022-04-18T00:19:04.299Z
Commit: 3305ac69c456fe62c08d244b875775a5c9b7479e
Is extension: false

**Comment by n0samu** [comment] 2024-06-23 23:36
Likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:36 UTC
Labels: error-report
