### ISSUE TITLE
Error on http://mickski.labrute.fr/cellule

### ISSUE THREAD

**Issue by Mickski** [ruffle-rs/ruffle#2417] opened 2021-01-12 13:09 UTC
# Error Info
Error name: RuntimeError
Error message: unreachable executed
Error stack:
```
std::panicking::rust_panic_with_hook::h123718ba3bf480af@moz-extension://d696df22-2f8e-401f-8b58-d04654d9e8a7/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[3312]:0x340572
std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2@moz-extension://d696df22-2f8e-401f-8b58-d04654d9e8a7/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[3889]:0x35b821
std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925@moz-extension://d696df22-2f8e-401f-8b58-d04654d9e8a7/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4627]:0x36b02f
rust_begin_unwind@moz-extension://d696df22-2f8e-401f-8b58-d04654d9e8a7/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4500]:0x36966c
core::panicking::panic_fmt::h285dc015a87be5a4@moz-extension://d696df22-2f8e-401f-8b58-d04654d9e8a7/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[4629]:0x36b093
core::option::expect_none_failed::hb95d2b1dc5448c17@moz-extension://d696df22-2f8e-401f-8b58-d04654d9e8a7/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[3969]:0x35dfe0
instant::wasm::now::h73d54eb5f99f20e4@moz-extension://d696df22-2f8e-401f-8b58-d04654d9e8a7/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[3682]:0x3537d5
ruffle_core::player::Player::new::h2273c818300799f8@moz-extension://d696df22-2f8e-401f-8b58-d04654d9e8a7/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[348]:0xcda8d
ruffle_web::Ruffle::new::ha55206f91423035f@moz-extension://d696df22-2f8e-401f-8b58-d04654d9e8a7/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[426]:0x11c963
ruffle_new@moz-extension://d696df22-2f8e-401f-8b58-d04654d9e8a7/dist/b4716f96db7fd93a9458.module.wasm:wasm-function[3895]:0x35bb02
G@moz-extension://d696df22-2f8e-401f-8b58-d04654d9e8a7/dist/core.ruffle.js:1:20011
ensureFreshInstance/<@http://mickski.labrute.fr/cellule:3:18490
c@http://mickski.labrute.fr/cellule:3:14611
promise callback*a@http://mickski.labrute.fr/cellule:3:14776
p/<@http://mickski.labrute.fr/cellule:3:14787
p@http://mickski.labrute.fr/cellule:3:14554
ensureFreshInstance@http://mickski.labrute.fr/cellule:3:17204
load/<@http://mickski.labrute.fr/cellule:3:19771
p/<@http://mickski.labrute.fr/cellule:3:14809
p@http://mickski.labrute.fr/cellule:3:14554
load@http://mickski.labrute.fr/cellule:3:19390
connectedCallback@http://mickski.labrute.fr/cellule:3:26417
W@http://mickski.labrute.fr/cellule:3:32451
polyfill/<@http://mickski.labrute.fr/cellule:3:34030
polyfill@http://mickski.labrute.fr/cellule:3:34165
init@http://mickski.labrute.fr/cellule:3:4455
EventListener.handleEvent*o@http://mickski.labrute.fr/cellule:3:3848
negotiate@http://mickski.labrute.fr/cellule:3:5116
773@http://mickski.labrute.fr/cellule:3:33894
yi@http://mickski.labrute.fr/cellule:3:35054
@http://mickski.labrute.fr/cellule:3:67946
@http://mickski.labrute.fr/cellule:3:67955
@http://mickski.labrute.fr/cellule:3:67959

```

# Player Info
Allows script access: true

# Page Info
Page URL: http://mickski.labrute.fr/cellule

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by Txori** [comment] 2021-01-12 13:59
Duplicate of https://github.com/ruffle-rs/ruffle/issues/2406

**Closed** 2021-01-12 15:49 UTC
Labels: duplicate
