### ISSUE TITLE
Error on https://fotostrana.ru/fast/yammy/yammy_fs.php?v1=0&domain_url=fotostrana.ru&ajax_server=fotostrana.ru&static_server=st.fotocdn.net&logged_user_id=37009135&version=0&timestamp=1612715319&is_admin=0&g_t=0&s_n=0&g_m=0&s_m=0&reload_href=yammy&swf_path=https://st.fotocdn.net/app/yammy/swf/__v1602669678.yammy.swf&is_https=1&test_group=&yammy_mt=0&ticker=&is_newbie=&

### ISSUE THREAD

**Issue by erdgi** [ruffle-rs/ruffle#3142] opened 2021-02-07 16:29 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:11028)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (wasm-function[1265]:169)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (wasm-function[1528]:675)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (wasm-function[4309]:67)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (wasm-function[3299]:224)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (wasm-function[3916]:159)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (wasm-function[4655]:40)
    at rust_begin_unwind (wasm-function[4526]:89)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (wasm-function[4657]:48)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (wasm-function[3996]:123)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://st.fotocdn.net/app/yammy/swf/__v1602669678.yammy.swf?v0
Param menu: false
Param flashvars: [object Object]&v1=0&domain_url=fotostrana.ru&ajax_server=fotostrana.ru&static_server=st.fotocdn.net&logged_user_id=37009135&version=0&timestamp=1612715319&is_admin=0&g_t=0&s_n=0&g_m=0&s_m=0&reload_href=yammy&swf_path=https://st.fotocdn.net/app/yammy/swf/__v1602669678.yammy.swf&is_https=1&test_group=&yammy_mt=0&ticker=&is_newbie=
Param allowfullscreen: true
Param allownetworking: all
Param allowscriptaccess: always
Param bgcolor: #189db3
Param quality: high
Param useExpressInstall: true
Param type: application/x-shockwave-flash
Param wmode: window
Param hasPriority: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://fotostrana.ru/fast/yammy/yammy_fs.php?v1=0&domain_url=fotostrana.ru&ajax_server=fotostrana.ru&static_server=st.fotocdn.net&logged_user_id=37009135&version=0&timestamp=1612715319&is_admin=0&g_t=0&s_n=0&g_m=0&s_m=0&reload_href=yammy&swf_path=https://st.fotocdn.net/app/yammy/swf/__v1602669678.yammy.swf&is_https=1&test_group=&yammy_mt=0&ticker=&is_newbie=&
SWF URL: https://st.fotocdn.net/app/yammy/swf/__v1602669678.yammy.swf?v0

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.69 Freeu/61.0.3163.69 MRCHROME SOC Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by adrian17** [comment] 2021-03-03 20:11
Looks like a duplicate of https://github.com/ruffle-rs/ruffle/issues/3140 .

**Closed by adrian17** 2021-03-03 20:11 UTC
