### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by fushsuf** [ruffle-rs/ruffle#8568] opened 2022-11-18 00:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/collections/btree/navigate.rs:522:22
Error stack:
```
@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.e631855af83866180192.js:1:7331
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hade171d180e8c1b3]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h34aee843864daceb]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b5ff8f72074c3e7]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h70a0e195f4db2a29]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h751be80779d42b53]@[wasm code]
<?>.wasm-function[core::panicking::panic::h8af046397a2bf65d]@[wasm code]
<?>.wasm-function[<alloc::collections::btree::map::Iter<K,V> as core::iter::traits::iterator::Iterator>::next::h4d0d49b16fefc597]@[wasm code]
<?>.wasm-function[<core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::h1b5cdd54ca4432d4]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::run_goto::hacca3cd440c0729c]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::goto_frame::h23d8ab48caba9647]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::globals::movie_clip::goto_frame::hc78b1e007a404f27]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h45eca0b81352d31f]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::haa980951d8d738e5]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::h954ab84db9d5d27d]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h888878a53ecfea0c]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h4aa053802fae5111]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h78c8747089155c4a]@[wasm code]
wasm-stub@[native code]
F@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.e631855af83866180192.js:1:3057
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.e631855af83866180192.js:1:2509
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=mobile&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1668524747%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F758000%2F758094_creambee-btsv4.swf%3F1636039048%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226376d7d67654b%22%2C%22NewgroundsAPI_SessionID%22%3A%22GW9fd0qhpM3148s6zYWz4471c7d9a2562884b997eca130f6c5fd2a900bfbIHnI%22%2C%22NewgroundsAPI_UserName%22%3A%22fushsuf%22%2C%22NewgroundsAPI_UserID%22%3A9889002%2C%22ng_username%22%3A%22fushsuf%22%7D%2C%22width%22%3A536%2C%22height%22%3A670%2C%22icon%22%3A%22https%3A%2F%2Fimg.ngfiles.com%2Fdefaults%2Ficon-portal-xl-a.gif%3Ff1601395813%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/758000/758094_creambee-btsv4.swf?1636039048

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-15
Channel: nightly
Built: 2022-11-15T00:15:53.122Z
Commit: 99a4172e2b9672999595b8e3e7774a49e964288a
Is extension: false

# Metadata
width: 640
height: 800
frameRate: 31.25
numFrames: 23
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 10612235

**Comment by n0samu** [comment] 2022-11-18 00:57
Duplicate of #6608. Updating your device to the latest iOS version should fix the issue!

**Closed by n0samu** 2022-11-18 00:57 UTC
Labels: duplicate, error-report
