### ISSUE TITLE
Error on https://ruffle.rs/demo/ on Opera Android

### ISSUE THREAD

**Issue by Anthpect101** [ruffle-rs/ruffle#16605] opened 2024-06-05 14:14 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.0/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.0/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.


    at Q.n.wbg.__wbg_new_28c511d9baebfa89 (https://ruffle.rs/demo/assets/ruffle_web-wasm_extensions-Boz1EWk8.js:2:73035)
    at ruffle_web.wasm.js_sys::Error::new::ha59a397dfb01052a (wasm://wasm/ruffle_web.wasm-033a2ffe:wasm-function[12805]:0x9fe15c)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d553c011316b6be (wasm://wasm/ruffle_web.wasm-033a2ffe:wasm-function[10433]:0x9b83b5)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-033a2ffe:wasm-function[6530]:0x883941)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-033a2ffe:wasm-function[10175]:0x9b0f15)
    at ruffle_web.wasm.core::ops::function::Fn::call::ha4719dc1d08feb58 (wasm://wasm/ruffle_web.wasm-033a2ffe:wasm-function[7486]:0x8c90f0)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::hfbd96b34f8ce7194 (wasm://wasm/ruffle_web.wasm-033a2ffe:wasm-function[7657]:0x8dc66e)
    at ruffle_web.wasm.<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h7a3038e2c83626c2 (wasm://wasm/ruffle_web.wasm-033a2ffe:wasm-function[1931]:0x501e99)
    at ruffle_web.wasm.core::cell::once::OnceCell<T>::get_or_try_init::outlined_call::hcd97a6e97a2e4628 (wasm://wasm/ruffle_web.wasm-033a2ffe:wasm-function[6221]:0x86d15c)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::hae40dda678d8441e (wasm://wasm/ruffle_web.wasm-033a2ffe:wasm-function[2776]:0x640a96)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Adreno (TM) 504"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 11; SM-T295) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.149 Safari/537.36 OPR/81.5.4292.78980
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-06-05
Channel: nightly
Built: 2024-06-05T00:06:01.896Z
Commit: 488fc4ae9fb1d87cbdb494d452592a5298027255
Is extension: false

# Metadata
width: 960
height: 600
frameRate: 32
numFrames: 4
swfVersion: 19
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 5818568

**Comment by Dinnerbone** [comment] 2024-07-12 22:00
Duplicate of #16572

**Closed by Dinnerbone** 2024-07-12 22:00 UTC
Labels: duplicate, error-report, wgpu-oom
