### ISSUE TITLE
Error on https://www.albinoblacksheep.com/games/shanghai

### ISSUE THREAD

**Issue by mjncag** [ruffle-rs/ruffle#6753] opened 2022-04-19 12:34 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
@https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/ruffle.js:1:6358
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h02eac160d339afc2]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h123718ba3bf480af]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_fmt::h96153d9dc0e882ed]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hf37d5bbee844564e]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6b0d014216238f67]@[wasm code]
wasm-stub@[native code]
R@https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/ruffle.js:1:4006
a@https://www.albinoblacksheep.com/script/ruffle_nightly_2021_01_26_selfhosted/ruffle.js:1:2841
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /swf/games/shanghai(www.albinoblacksheep.com).swf
Param movie: /swf/games/shanghai(www.albinoblacksheep.com).swf
Param quality: high
Param menu: true
Param wmode: window
Param allowFullScreen: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.albinoblacksheep.com/games/shanghai
SWF URL: https://www.albinoblacksheep.com/swf/games/shanghai(www.albinoblacksheep.com).swf

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-26
Channel: nightly
Built: 2021-01-26T00:36:48.131Z
Commit: 7856cdd3d770e406ce546bf1745d8046d7b716f8

**Comment by n0samu** [comment] 2024-06-23 23:41
Duplicate of #6608

**Closed by n0samu** 2024-06-23 23:41 UTC
Labels: error-report
