### ISSUE TITLE
This game does not work

### ISSUE THREAD

**Issue by empressjariden** [ruffle-rs/ruffle#2141] opened 2020-12-28 22:43 UTC

**Comment by Herschel** [comment] 2020-12-28 23:26
Hi, please provide information about what the issue is or which game you are trying. Thank you!

**Comment by empressjariden** [comment] 2020-12-28 23:28
I was trying to play Strike Force Heroes 2 for nostalgia sake, and noticed the little ad that talked about this, once I clicked in it, it responded with a bug.

**Comment by Herschel** [comment] 2020-12-28 23:38
Thanks! Looks like Strike Force Heroes 2 is an AS3 game which is still WIP in Ruffle. Closing in favor of issue #1368.

**Closed by Herschel** 2020-12-28 23:38 UTC
