### ISSUE TITLE
Error on https://mississippitalks.com/index.php?/ipsproarcade/playgame/16382-%7B?%7D/

### ISSUE THREAD

**Issue by Mississippitalks-com** [ruffle-rs/ruffle#2762] opened 2021-01-22 18:35 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at Object.X (chrome-extension://emcendmbaffpddpefcpnledppadknhni/dist/core.ruffle.js:1:21341)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:38348)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://emcendmbaffpddpefcpnledppadknhni/dist/00bd127fe3b85845047c.module.wasm:wasm-function[1280]:0x264d71)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://emcendmbaffpddpefcpnledppadknhni/dist/00bd127fe3b85845047c.module.wasm:wasm-function[1548]:0x295c9c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://emcendmbaffpddpefcpnledppadknhni/dist/00bd127fe3b85845047c.module.wasm:wasm-function[4312]:0x369bc1)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://emcendmbaffpddpefcpnledppadknhni/dist/00bd127fe3b85845047c.module.wasm:wasm-function[3310]:0x342e79)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://emcendmbaffpddpefcpnledppadknhni/dist/00bd127fe3b85845047c.module.wasm:wasm-function[3919]:0x35f9e7)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://emcendmbaffpddpefcpnledppadknhni/dist/00bd127fe3b85845047c.module.wasm:wasm-function[4655]:0x36f25b)
    at rust_begin_unwind (chrome-extension://emcendmbaffpddpefcpnledppadknhni/dist/00bd127fe3b85845047c.module.wasm:wasm-function[4529]:0x36d8db)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://emcendmbaffpddpefcpnledppadknhni/dist/00bd127fe3b85845047c.module.wasm:wasm-function[4657]:0x36f2bf)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://mississippitalks.com/arcade/easterislandtdEasyv32Th.swf
Param movie: https://mississippitalks.com/arcade/easterislandtdEasyv32Th.swf
Param pluginspage: http://www.macromedia.com/go/getflashplayer/
Param bgcolor: #ffffff
Param quality: high
Param menu: true
Param wmode: direct
Param allowScriptAccess: always
Param play: true
Param loop: true
Param hasPriority: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://mississippitalks.com/index.php?/ipsproarcade/playgame/16382-%7B?%7D/
SWF URL: https://mississippitalks.com/arcade/easterislandtdEasyv32Th.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-16
Channel: nightly
Built: 2021-01-16T01:09:33.302Z
Commit: 9df7facdb8d37a5d007a13c25efcc176ed4675e0

**Comment by n0samu** [comment] 2022-10-23 21:54
Duplicate of #2763

**Closed by n0samu** 2022-10-23 21:54 UTC
Labels: duplicate, error-report
