### ISSUE TITLE
Text is shown in wrong size(width of column)

### ISSUE THREAD

**Issue by sidmike** [ruffle-rs/ruffle#13079] opened 2023-09-05 22:01 UTC
### Describe the bug

I'm trying to run old runes.swf game through Ruffle, but Ruffle is displaying text at the wrong size. The column of text looks very narrow and long. It should not look like that.
[runes.zip](https://github.com/ruffle-rs/ruffle/files/12528651/runes.zip)

### Expected behavior

The column of text looks very narrow and long. It should not look like that. It should be wider for sure.

### Affected platform

Online demo

### Operating system

MacOs Ventura 13.5

### Browser

Google Chrome 116

### Additional information

Its written on Action Script 3

**Comment by sidmike** [comment] 2023-09-05 22:19
Forgot to mention what @n0samu already told regarding this bug:

 _...It looks similar to some AS2 issues I saw before but I don’t think I’ve seen it in AS3. Unless it’s related to unsupported TextFormat stuff. It’s worth checking..._

**Comment by n0samu** [comment] 2023-09-05 22:58
Looks like a similar issue to #13026, but it's a simpler reproduction, which is appreciated

**Comment by sidmike** [comment] 2023-09-06 09:19
yea, exactly same problem! Any ideas on what can be done here from Ruffle side?

**Comment by Lord-McSweeney** [comment] 2023-11-10 02:03
Fixed by #13923.

**Closed by Lord-McSweeney** 2023-11-10 02:03 UTC
Labels: bug, text

**Comment by sidmike** [comment] 2023-11-10 08:38
works like hell! thanks!
