### ISSUE TITLE
Problem with an intranet site with Firefox and Chrome

### ISSUE THREAD

**Issue by enniobal** [ruffle-rs/ruffle#1830] opened 2020-12-03 15:39 UTC
![ruffle](https://user-images.githubusercontent.com/75437901/101051668-0b83aa00-3586-11eb-88f3-c4aed088837d.PNG)

**Comment by bbb651** [comment] 2020-12-03 15:49
Could you please provide more info?
See [the guidelines for submitting issues](https://github.com/ruffle-rs/ruffle/blob/master/CONTRIBUTING.md#reporting-bugs).

**Comment by Toad06** [comment] 2020-12-03 19:04
Likely a duplicate of #1507 and #1630.

**Comment by Toad06** [comment] 2020-12-21 12:52
This should be fixed by #2051, so you'd just need to update to [a newer version of the extension](https://github.com/ruffle-rs/ruffle/tags). Please let us know if the issue still happens on your side.

Thank you.

**Closed by Toad06** 2020-12-21 12:52 UTC
