### ISSUE TITLE
Error on http://sonic.sega.jp/riders/ShootingStarStory/

### ISSUE THREAD

**Issue by DemonKingOdio** [ruffle-rs/ruffle#14557] opened 2023-12-30 01:46 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/string.rs:551:34:
string indices out of bounds
Error stack:
```
339/__wbg_get_imports/imports.wbg.__wbg_new_a64e3f2afc2cf2f8@moz-extension://3c012d78-e5fb-41a9-8290-ee18e2ae92a5/dist/339.js:2624:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::h643031ddb85c668c@:wasm-function[9872]:0x9cd24a
std::panicking::rust_panic_with_hook::hbf46ef0245cc9589@:wasm-function[6317]:0x8bd358
core::panicking::panic_fmt::h14c85a61aa3d538e@:wasm-function[9663]:0x9c7e96
core::option::expect_failed::h2966ad4c676148ac@:wasm-function[8624]:0x977448
ruffle_core::avm2::globals::string::substr::h91484ca68281b94b@:wasm-function[1696]:0x525082
ruffle_core::avm2::function::Executable::exec::h256c0c4a1cfdb4cd@:wasm-function[872]:0x32b9c6
ruffle_core::avm2::object::TObject::call_property::hd5aa583285c6f31d@:wasm-function[1278]:0x452a0e
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h177e0ec68fabedc8@:wasm-function[2856]:0x69c00e
ruffle_core::avm2::activation::Activation::run_actions::h3cac844649cfafe8@:wasm-function[568]:0x40606
ruffle_core::avm2::function::Executable::exec::h256c0c4a1cfdb4cd@:wasm-function[872]:0x32b5b5
ruffle_core::avm2::object::TObject::call_property::hc92489d89c913e30@:wasm-function[1305]:0x45f27f
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h177e0ec68fabedc8@:wasm-function[2856]:0x69bfec
ruffle_core::avm2::activation::Activation::run_actions::h3cac844649cfafe8@:wasm-function[568]:0x40606
ruffle_core::avm2::function::Executable::exec::h256c0c4a1cfdb4cd@:wasm-function[872]:0x32b5b5
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h27ea6128607d5938@:wasm-function[1075]:0x3db6e6
ruffle_core::avm2::events::dispatch_event_to_target::hfac940010f8caa19@:wasm-function[1040]:0x3c4f35
ruffle_core::avm2::events::dispatch_event::h186a5e0381e7d422@:wasm-function[1234]:0x43b3a5
ruffle_core::avm2::Avm2::broadcast_event::h1a4d529b92b8115a@:wasm-function[754]:0x27f2cb
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::enter_frame::ha4f75c9291b87bc4@:wasm-function[4812]:0x800456
ruffle_web::Ruffle::tick::h2da1b612e3b878f6@:wasm-function[860]:0x30a449
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hec0758b02fc1da12@:wasm-function[12015]:0xa1c8f4
wasm_bindgen::convert::closures::invoke1_mut::hf8bc7edfc00877b9@:wasm-function[10576]:0x9e8958
__wbg_adapter_63@moz-extension://3c012d78-e5fb-41a9-8290-ee18e2ae92a5/dist/339.js:290:10
real@moz-extension://3c012d78-e5fb-41a9-8290-ee18e2ae92a5/dist/339.js:271:20

```
AVM2 stack:
```
    at String/substr()
    at myAS::textAnimation/randomTxtFnc()
    at myAS::textAnimation/textChange()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1920, height: 720, depth_or_array_layers: 1 }

# Page Info
Page URL: http://sonic.sega.jp/riders/ShootingStarStory/
SWF URL: http://sonic.sega.jp/riders/ShootingStarStory/swf/top.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-23
Channel: nightly
Built: 2023-12-23T00:15:31.142Z
Commit: 704bd7502e66ae26fe308250ef5065fa7989bf20
Is extension: true

# Metadata
width: 800
height: 720
frameRate: 26
numFrames: 177
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 415645

**Comment by n0samu** [comment] 2023-12-30 01:54
Duplicate of #8553 and #9968

**Closed by n0samu** 2023-12-30 01:54 UTC
Labels: duplicate, avm2, panic, error-report
