### ISSUE TITLE
Error on http://www.hackedonlinegames.com/game/2283/tequila-zombies-3

### ISSUE THREAD

**Issue by Teleskless** [ruffle-rs/ruffle#17234] opened 2024-07-23 09:45 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/f9e3de5/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/f9e3de5/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3681:21)
    at ruffle_web.wasm.js_sys::Error::new::hf03bfdfe20712a15 (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[12858]:0x9e40a8)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hc88c405174a9e2d2 (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[9885]:0x97a962)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[6537]:0x86d3a2)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[10287]:0x9a5642)
    at ruffle_web.wasm.core::panicking::panic_display::hbd841ae85eb3dff4 (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[9816]:0x9728f6)
    at ruffle_web.wasm.core::option::expect_failed::h637b3c5bf9792ea8 (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[10859]:0x9affdb)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::h92d304d2e60387ff (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[769]:0xde5df)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::h92d304d2e60387ff (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[769]:0xdb7ca)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_object_static::h95c08aab90cede59 (wasm://wasm/ruffle_web.wasm-033838de:wasm-function[4431]:0x788e2f)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at BinaryData$/getMovieClipManager()
    at Game/onLoadComplete()
    at Game()
    at Main/createGame()
    at Main/onRootCreated()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-2032()
```

# Player Info
Allows script access: always
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x0000A7A1) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: medium
Surface samples: 2
Surface size: (1000, 750, 1)

# Page Info
Page URL: http://www.hackedonlinegames.com/game/2283/tequila-zombies-3
SWF URL: http://cache.hackedonlinegames.com/uploads/games/files/846/WOSVWD3ETW1M.swf?version=1

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-23
Channel: nightly
Built: 2024-07-23T00:05:24.982Z
Commit: e9c610816b04d9cc8d21ebee2c6aab5e8995a8eb
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 1
swfVersion: 22
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 86316

**Comment by evilpie** [comment] 2024-07-23 10:08
Duplicate of #13748.

**Closed by evilpie** 2024-07-23 10:08 UTC
Labels: error-report

**Comment by Teleskless** [comment] 2024-07-24 10:41
I just don't understand why is it not working on the website
