### ISSUE TITLE
Ruffle won't launch for me.

### ISSUE THREAD

**Issue by JohnGalt2005** [ruffle-rs/ruffle#18807] opened 2024-11-29 19:15 UTC
### Describe what you were doing

I'm just trying to get ruffle to launch so I can play some old flash games, but I can't open ruffle at all. Do I need to put a game into it first? I have used flash before, but not ruffle.

### What does the crash message say?

panicked at desktop\src\app.rs:466:14:
GUI controller should be created: Parent device is lost

### Ruffle Version

0.1.0-nightly (4965d7ff710c8a94ec2dfac4584710e305602aa5 2024-11-28)

### Affected platform

Desktop app

### Operating system

Windows 10.0.19045 (Windows 10 Enterprise) [64-bit]

**Comment by evilpie** [comment] 2024-12-08 14:16
Duplicate of #18690

**Closed by evilpie** 2024-12-08 14:16 UTC
Labels: bug, panic, render-wgpu, windows
