### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by PateoXd** [ruffle-rs/ruffle#8089] opened 2022-09-25 16:20 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.53726dfbe9c975c894bb.js:1:6979)
    at std::sync::once::Once::call_once::{{closure}}::h73fc39b54ec29717 (wasm://wasm/017ff18e:wasm-function[1028]:0x2a07bf)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017ff18e:wasm-function[1481]:0x31ffb4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d648d6ec080e3d2 (wasm://wasm/017ff18e:wasm-function[4943]:0x486b53)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017ff18e:wasm-function[3635]:0x4436b1)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017ff18e:wasm-function[5093]:0x489eca)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/017ff18e:wasm-function[4236]:0x46d9ae)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::hdbb032e447c80bb0 (wasm://wasm/017ff18e:wasm-function[2552]:0x3dd0f2)
    at ruffle_core::display_object::render_base::he8fc78d5f43f2e1f (wasm://wasm/017ff18e:wasm-function[1207]:0x2dec50)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::ha49f4f1346598250 (wasm://wasm/017ff18e:wasm-function[3858]:0x45952c)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1664114392%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2263307e3bc1266%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-25
Channel: nightly
Built: 2022-09-25T00:16:10.952Z
Commit: 898ccfba5dc1d0d2a439c0a2f03435afe7a06ece
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by n0samu** [comment] 2022-09-25 20:03
Duplicate of #7978

**Closed by n0samu** 2022-09-25 20:03 UTC
Labels: error-report
