### ISSUE TITLE
Error on https://www.animaljam.com/en/game/play

### ISSUE THREAD

**Issue by bonniebearr** [ruffle-rs/ruffle#3415] opened 2021-02-25 15:57 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:11028)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1265]:0x24e3c9)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1528]:0x27e7a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4309]:0x3537a0)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3299]:0x32c417)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3916]:0x3495f5)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4655]:0x358eda)
    at rust_begin_unwind (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4526]:0x3574b8)
    at std::panicking::begin_panic_fmt::h96153d9dc0e882ed (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4624]:0x358955)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h0cef4789c921984e (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1432]:0x26e35f)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://ajcontent.akamaized.net/1613/preloader.swf?v=2
Param quality: high
Param bgcolor: #242833
Param allowscriptaccess: always
Param allowfullscreen: true
Param scale: noScale
Param wmode: window
Param warning: ******* WARNING - GIVING OUT THIS INFORMATION IS LIKE GIVING AWAY YOUR PASSWORD. KEEP IT SAFE! *******
Param flashvars: webRefPath=game/play&content=https://ajcontent.akamaized.net/&blueboxPort=443&smartfoxPort=443&website=http://www.animaljam.com/&build_version=2&mdUrl=https://jammercentral.animaljam.com/game/&deploy_version=1613&sbStatTrackerIp=stats.animaljam.com&sbStatModulator=16&smoke_version=1613&playerWallHost=https://prod-wall.animaljam.com/wall&smartfoxServer=iss02-classic.prod.animaljam.internal&blueboxServer=iss02-classic.prod.animaljam.internal&webSessionId=896db7fd20fa262014800ccd5fdca00e&currentTimestamp=1614268652&locale=en&country=DE&myExternalIp=10.102.155.64&redemptionCode=&auth_token=c3d82a2b7681e2601590bbaa2add0d1eb1bd8ddc&username=Blitzzø&clientURL=https://ajcontent.akamaized.net/1613/ajclient.swf?v=2
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute 7: undefined

# Page Info
Page URL: https://www.animaljam.com/en/game/play
SWF URL: https://ajcontent.akamaized.net/1613/preloader.swf?v=2

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS aarch64 13597.94.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.186 Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by adrian17** [comment] 2021-05-17 22:04
It's very likely this was already fixed in newer version of Ruffle.
In fact, it's possible that this was already fixed by the time you posted this report - the issue is that the extension you used didn't use an up to date version of Ruffle. In fact, not only that extension isn't endorsed by us, it was recently removed from Chrome for being malware. With that in mind, I'd recommend trying a newer official version of Ruffle instead.

**Closed by adrian17** 2021-05-17 22:04 UTC
