### ISSUE TITLE
Error on https://f.kbhgames.com/RS/game.php

### ISSUE THREAD

**Issue by nunosard** [ruffle-rs/ruffle#5009] opened 2021-08-06 04:18 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:945:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:945:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://f.kbhgames.com/RS/asset/ruffle.js:1:6915)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (<anonymous>:wasm-function[1196]:0x28eb16)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (<anonymous>:wasm-function[1782]:0x309bb5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (<anonymous>:wasm-function[5307]:0x418e9b)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (<anonymous>:wasm-function[4081]:0x3ea7fa)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (<anonymous>:wasm-function[4788]:0x40b737)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (<anonymous>:wasm-function[5680]:0x41ebb3)
    at rust_begin_unwind (<anonymous>:wasm-function[5551]:0x41d1f7)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (<anonymous>:wasm-function[5682]:0x41ec17)
    at core::panicking::panic::h5da66f104e83c46a (<anonymous>:wasm-function[5479]:0x41bf8f)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://f.kbhgames.com/RS/game.php?r=//f.kbhgames.com/2018/swf/chibi_knight.swf&w=640&h=480
SWF URL: https://f.kbhgames.com/2018/swf/chibi_knight.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-02
Channel: nightly
Built: 2021-04-02T00:48:56.172Z
Commit: bbded906971e98016cd104d47dcd2fa34fd001c2

**Comment by relrelb** [comment] 2021-08-13 13:57
Duplicate of #5008.

**Closed by relrelb** 2021-08-13 13:57 UTC
