### ISSUE TITLE
Error on https://flashthemes.net/character/browser/family

### ISSUE THREAD

**Issue by Lyrics777** [ruffle-rs/ruffle#15902] opened 2024-04-07 02:30 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys/pal/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys/pal/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3393:21)
    at js_sys::Error::new::h8e593d55ccfdbc76 (wasm://wasm/03a5971a:wasm-function[13929]:0xb227b7)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h95f45e9c34bf174e (wasm://wasm/03a5971a:wasm-function[11529]:0xacd408)
    at std::panicking::rust_panic_with_hook::h5ca5fd3b2064be1b (wasm://wasm/03a5971a:wasm-function[7104]:0x99b761)
    at core::panicking::panic_fmt::h2582bddf31c1c986 (wasm://wasm/03a5971a:wasm-function[11237]:0xac6d29)
    at core::panicking::assert_failed_inner::hf073d683243b665e (wasm://wasm/03a5971a:wasm-function[4925]:0x886f28)
    at core::panicking::assert_failed::ha3d8bcf705ea9fbe (wasm://wasm/03a5971a:wasm-function[11279]:0xac81e5)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h4d57a7f9f1ad92fc (wasm://wasm/03a5971a:wasm-function[1048]:0x30db3c)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h66ed79ae242950c1 (wasm://wasm/03a5971a:wasm-function[1447]:0x476880)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h17b5e40182c3d9de (wasm://wasm/03a5971a:wasm-function[4076]:0x806de8)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (ARM, Mali-G72, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16383, max_texture_dimension_2d: 16383, max_texture_dimension_3d: 16383, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/cc_browser.swf
Param align: middle
Param allowScriptAccess: always
Param allowFullScreen: true
Param wmode: transparent
Param flashvars: apiserver=https%3A%2F%2Fflashthemes.net%2F&userId=37377&isLogin=Y&m_mode=school&isEmbed=0&ctc=go&tlang=en_US&appCode=go&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E&ut=60&v=37377&nextUrl=https%3A%2F%2Fflashthemes.net%2Fcharacter%2Fbrowser&clientThemePath=%2Fstatic%2Fct%2F30%2F%3Cclient_theme%3E&themeId=family
Param movie: /static/animationnew/414827163ad4eb60/cc_browser.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/character/browser/family
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/cc_browser.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-04-04
Channel: nightly
Built: 2024-04-04T00:05:40.274Z
Commit: 51d91b2c1757b79662379f126d4561265890fd10
Is extension: true

# Metadata

**Comment by n0samu** [comment] 2024-05-12 21:35
Duplicate of #13974

**Closed by n0samu** 2024-05-12 21:35 UTC
Labels: duplicate, error-report
