### ISSUE TITLE
Error on https://play.cplegacy.com/

### ISSUE THREAD

**Issue by bunnybeep** [ruffle-rs/ruffle#8812] opened 2022-12-16 23:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:507:50

# Player Info
Allows script access: true

# Page Info
Page URL: https://play.cplegacy.com/
SWF URL: https://cpl-prod.b-cdn.net/assets/media/swf/games/boot.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 OPR/93.0.0.0 (Edition std-1)
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-10
Channel: nightly
Built: 2022-07-10T00:19:08.480Z
Commit: 78ebf06f55eff05db6939166973bbfa08641300b
Is extension: false

**Comment by n0samu** [comment] 2022-12-17 04:40
Duplicate of #8811

**Closed by n0samu** 2022-12-17 04:40 UTC
Labels: duplicate, error-report
