### ISSUE TITLE
Unexpected TypeError during assignment

### ISSUE THREAD

**Issue by tram98** [ruffle-rs/ruffle#18527] opened 2024-11-08 20:28 UTC
### Describe the bug

We patched an SWF File by using JPEXS Decompiler. Trying to instantiate the created class AuthForm and assigning it to a class variable of the same type causes a TypeError:
```
2024-11-08T20:12:14.550271Z ERROR ruffle_core::display_object::movie_clip: Got "TypeError: Error #1034: Type Coercion failed: cannot convert com.auth::AuthForm@00000000000 to com.auth.AuthForm.
	at LOGIN$/Login()
	at GAME/Data()
	at GAME()" when constructing AVM2 side of movie clip of type GAME
```

This is an excerpt of the `LOGIN` class where the error happens.

```as3
...
      public static var authForm:AuthForm; // <== The variable is declared as the same type, so it should be compatible.
...
      public static function Login() : void
      {
         if(GAME.token)
         {
            PLEASEWAIT.Show("Logging in...");
            GLOBAL.eventDispatcher.addEventListener(KEYS.LANGUAGE_FILE_LOADED,onLanguageLoaded);
            GLOBAL.LanguageSetup();
         }
         else
         {
            authForm = new AuthForm(); // <== THE ERROR HAPPENS HERE
            GLOBAL._layerTop.addChild(authForm);
         }
      }
...
```

### Expected behavior

The assignment should not cause a crash. Flash Player runs the movie just fine. The code looks fine to me.

### Content Location

You can grab the latest copy of the affected file here (use the stable version): 
https://github.com/bym-refitted/backyard-monsters-refitted/releases

### Affected platform

Desktop app

### Operating system

macOS Sonoma 14.6.1 (23G93)

### Additional information

The movie is an Adobe AIR Application.

**Comment by Lord-McSweeney** [comment] 2024-11-08 22:46
Duplicate of #16504

**Closed by Lord-McSweeney** 2024-11-08 22:46 UTC
Labels: bug, duplicate, A-avm2
