### ISSUE TITLE
Error on https://www.jeux-jouer.fr/Electric-Man,28165.html

### ISSUE THREAD

**Issue by leilamouette** [ruffle-rs/ruffle#7035] opened 2022-05-20 18:23 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.jeux-jouer.fr/ruffle/core.ruffle.42226413fcddb0ba52ab.js:1:7708)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (https://www.jeux-jouer.fr/ruffle/ae5cb174a07ba7100ab3.wasm:wasm-function[1008]:0x2a52de)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://www.jeux-jouer.fr/ruffle/ae5cb174a07ba7100ab3.wasm:wasm-function[1446]:0x31c029)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (https://www.jeux-jouer.fr/ruffle/ae5cb174a07ba7100ab3.wasm:wasm-function[4922]:0x4742a3)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://www.jeux-jouer.fr/ruffle/ae5cb174a07ba7100ab3.wasm:wasm-function[3242]:0x416be4)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://www.jeux-jouer.fr/ruffle/ae5cb174a07ba7100ab3.wasm:wasm-function[5007]:0x47822b)
    at core::panicking::panic::he88f1b1582b09c8c (https://www.jeux-jouer.fr/ruffle/ae5cb174a07ba7100ab3.wasm:wasm-function[4920]:0x473e36)
    at core::ops::function::FnOnce::call_once::hea116a8eeeb59311 (https://www.jeux-jouer.fr/ruffle/ae5cb174a07ba7100ab3.wasm:wasm-function[1089]:0x2be097)
    at ruffle_core::avm1::function::Executable::exec::h0a1a3c56ef393e7a (https://www.jeux-jouer.fr/ruffle/ae5cb174a07ba7100ab3.wasm:wasm-function[391]:0x12c992)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf21230a28d8729f3 (https://www.jeux-jouer.fr/ruffle/ae5cb174a07ba7100ab3.wasm:wasm-function[371]:0xe6836)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.jeux-jouer.fr/Electric-Man,28165.html
SWF URL: https://www.jeux-jouer.fr/swf/ElectricManv32Th.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36 OPR/85.0.4341.79
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-25
Channel: nightly
Built: 2022-04-25T00:17:25.499Z
Commit: 155672d4829e83802c8ee7e7513582ae2e7b1cca
Is extension: false

**Comment by relrelb** [comment] 2022-05-20 18:50
Duplicate of #4932.

**Comment by relrelb** [comment] 2022-05-20 18:50
Duplicate of #4932.

**Closed by relrelb** 2022-05-20 18:50 UTC
Labels: error-report
