### ISSUE TITLE
Error on https://inkbunny.net/submissionview.php?id=363859

### ISSUE THREAD

**Issue by jleung1283** [ruffle-rs/ruffle#2926] opened 2021-01-28 12:00 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32283
    at r (<anonymous>:3:32773)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://va.ib.metapix.net/files/full/467/467812_Aval0nX_bsc_build_05_feb_2013.swf
Param movie: https://va.ib.metapix.net/files/full/467/467812_Aval0nX_bsc_build_05_feb_2013.swf
Param allowScriptAccess: never
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined

# Page Info
Page URL: https://inkbunny.net/submissionview.php?id=363859

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-28
Channel: nightly
Built: 2021-01-28T00:36:59.079Z
Commit: 5e0527c59944d5888128c63f37d23880fdb0c6ff

**Comment by relrelb** [comment] 2021-01-28 14:44
Duplicate of #2201.

**Comment by GreenReaper** [comment] 2021-02-05 04:51
This should be resolved now that Inkbunny is self-hosting Ruffle nighties. (And has unsafe-eval - thanks, Chrome.)

I knew Babysitting Cream would be the first thing people wanted from IB. 🙄
The work is very much NSFW, though there's a clear warning if you can view it.
Thankfully it's old enough that it works, but roll on AS3/AVM2 for _[Monster Mind](https://inkbunny.net/s/1599328)_.

**Closed** 2021-02-12 23:51 UTC
