### ISSUE TITLE
Error on https://game58661.konggames.com/games/ArmorGames/frontier/frame/6a07608c-10b4-465f-96c0-00299920e50d/

### ISSUE THREAD

**Issue by NimishNandedkar** [ruffle-rs/ruffle#10539] opened 2023-04-03 16:07 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:865:22
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:865:22
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d0557de10628cbe98f62.js:1:47949)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h927501cce3fc7417 (wasm://wasm/02a79bda:wasm-function[8163]:0x7ef5ba)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a79bda:wasm-function[5431]:0x71d11b)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a79bda:wasm-function[8045]:0x7ea229)
    at core::panicking::panic::h54beb3f515dd3c6d (wasm://wasm/02a79bda:wasm-function[7446]:0x7b6c2c)
    at core::ops::function::FnOnce::call_once::hdf8298564975d768 (wasm://wasm/02a79bda:wasm-function[851]:0x2cef2c)
    at ruffle_core::avm1::function::Executable::exec::h4504ceb347e7fd28 (wasm://wasm/02a79bda:wasm-function[591]:0x1a212f)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h24252d26605522dc (wasm://wasm/02a79bda:wasm-function[1372]:0x3d9a7d)
    at ruffle_core::avm1::activation::Activation::run_actions::h74244169b0188f52 (wasm://wasm/02a79bda:wasm-function[481]:0x1234c)
    at ruffle_core::avm1::function::Executable::exec::h4504ceb347e7fd28 (wasm://wasm/02a79bda:wasm-function[591]:0x1a1f0c)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game58661.konggames.com/games/ArmorGames/frontier/frame/6a07608c-10b4-465f-96c0-00299920e50d/?kongregate_host=www.kongregate.com
SWF URL: https://game58661.konggames.com/gamez/0005/8661/live/frontier-kongedition.swf?kongregate_game_version=1256856408

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-03
Channel: nightly
Built: 2023-04-03T00:21:21.992Z
Commit: 9441182b7d70d334ea6a7921f9b5541246a5a447
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 40
swfVersion: 10
backgroundColor: #003300
isActionScript3: false
uncompressedLength: 6210605

**Comment by n0samu** [comment] 2023-04-05 02:44
Hi, can you tell us what led up to this error? Did it happen at a specific point in the game?

**Comment by n0samu** [comment] 2024-06-22 03:49
Duplicate of #13577

**Closed by n0samu** 2024-06-22 03:49 UTC
Labels: duplicate, avm1, error-report
