### ISSUE TITLE
Error on https://www.princesadosjogos.com/polly-pickup-party.html

### ISSUE THREAD

**Issue by samarozviq** [ruffle-rs/ruffle#16767] opened 2024-06-18 20:04 UTC
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Response body loading was aborted
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Response body loading was aborted
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.princesadosjogos.com/polly-pickup-party.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-03
Channel: nightly
Built: 2021-05-03T00:12:09.006Z
Commit: f2256a661be22fd12ae1ec3b40574d7cca670a27

**Comment by Lord-McSweeney** [comment] 2024-06-19 04:19
Closing since the Ruffle version is three years outdated and the issue is probably just a network error

**Closed by Lord-McSweeney** 2024-06-19 04:19 UTC
