### ISSUE TITLE
A cap opener man - Preloader fills up but doesn't advance

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#367] opened 2020-02-01 19:41 UTC
https://www.newgrounds.com/portal/view/420417

The preloader for this animation goes to 102% in Flash Player but in Ruffle it shows 102.0000000000003 (I guesstimated the zeroes) and does not progress to the animation. Note: The decimal value may be irrelevant to it not playing.

**Comment by adrian17** [comment] 2020-02-01 20:25
> The decimal value may be irrelevant to it not playing.

It actually turns out to be relevant, as the script checks the progress bar status to see if it can start playing.
The issue is that the value is stored in `_xscale`, which in Ruffle is internally stored divided by 100. This means that the script effectively turns from `value += 2.0` to `value = (value*100.0 + 2.0) / 100.0`, which after enough iterations casues floating point precision issues.

**Comment by Herschel** [comment] 2020-11-02 23:11
Fixed by #1219.

**Closed by Herschel** 2020-11-02 23:11 UTC
Labels: actionscript, avm1
