### ISSUE TITLE
Error on https://www.incredibots.com/if/game.php

### ISSUE THREAD

**Issue by MarioBG** [ruffle-rs/ruffle#13331] opened 2023-09-27 21:31 UTC
# Error Info
Error name: Error
Error message: panicked at 'Unable to get Object', /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:418:14
Error stack:
```
Error: panicked at 'Unable to get Object', /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:418:14
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2414:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd6a9dc3a3c36784e (wasm://wasm/030baad6:wasm-function[9335]:0x924a1b)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/030baad6:wasm-function[6109]:0x826933)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/030baad6:wasm-function[9171]:0x920032)
    at core::option::expect_failed::h87919cabea3832be (wasm://wasm/030baad6:wasm-function[8066]:0x8de739)
    at flash_lso::amf3::read::AMF3Decoder::parse_element_object::h4a1fb9970a1406df (wasm://wasm/030baad6:wasm-function[654]:0x1d7804)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h6f36470b53f350ed (wasm://wasm/030baad6:wasm-function[564]:0x1111c7)
    at flash_lso::amf3::read::AMF3Decoder::parse_object_static::h81e81c92ef2b4743 (wasm://wasm/030baad6:wasm-function[3915]:0x6fd41d)
    at flash_lso::amf3::read::AMF3Decoder::parse_element_object::h4a1fb9970a1406df (wasm://wasm/030baad6:wasm-function[654]:0x1d7673)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h6f36470b53f350ed (wasm://wasm/030baad6:wasm-function[564]:0x1111c7)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at General::Database$/ExtractPartsFromByteArray()
    at General::Database$/ExtractRobotFromByteArray()
    at Game::ControllerMainMenu()
    at Main/update()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.incredibots.com/if/game.php?v=ib2
SWF URL: https://www.incredibots.com/if/incredibots2.swf?1604326052

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-26
Channel: nightly
Built: 2023-09-26T00:20:19.266Z
Commit: 7e4e4d4c5b1f55614b98b33b7cc6f70567c52bab
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 104991

**Comment by n0samu** [comment] 2023-09-28 01:18
Duplicate of #10520

**Closed by n0samu** 2023-09-28 01:18 UTC
Labels: duplicate, error-report
