### ISSUE TITLE
Error on http://www.dan-dare.info/Games/SonicRush/SonicRush.htm

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#4123] opened 2021-04-25 16:30 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/display_object/movie_clip.rs:1662:5
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/display_object/movie_clip.rs:1662:5
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/ruffle.js?uniqueMessageSuffix=68757069466:1:7447)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/73d78e96b2eab18414cb.wasm:wasm-function[838]:0x228302)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/73d78e96b2eab18414cb.wasm:wasm-function[1230]:0x2aac4f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/73d78e96b2eab18414cb.wasm:wasm-function[3690]:0x4328c0)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/73d78e96b2eab18414cb.wasm:wasm-function[2689]:0x39a30c)
    at rust_begin_unwind (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/73d78e96b2eab18414cb.wasm:wasm-function[3892]:0x438005)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/73d78e96b2eab18414cb.wasm:wasm-function[4004]:0x43b8fa)
    at core::option::expect_none_failed::h203584ddbc785ca2 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/73d78e96b2eab18414cb.wasm:wasm-function[3321]:0x422e9d)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::set_matrix::h3c6d005f784148a6 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/73d78e96b2eab18414cb.wasm:wasm-function[885]:0x238651)
    at core::ops::function::FnOnce::call_once::h832ee6590b81ff51 (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/73d78e96b2eab18414cb.wasm:wasm-function[1823]:0x329a98)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.dan-dare.info/Games/SonicRush/SonicRush.htm
SWF URL: http://www.dan-dare.info/Games/SonicRush/pjinns_sonic_rush.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13729.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.130 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-25
Channel: nightly
Built: 2021-04-25T00:14:45.259Z
Commit: d43b033caa98ed201f37558c25f9ce5f2da189d0

**Comment by Poopooracoocoo** [comment] 2021-07-06 09:18
Duplicate of #4377

**Closed by Poopooracoocoo** 2021-07-06 09:18 UTC
