### ISSUE TITLE
Exporting videos using Ruffle

### ISSUE THREAD

**Issue by OmriSama** [ruffle-rs/ruffle#2352] opened 2021-01-09 20:37 UTC
Is it possible to export videos to MP4 using Ruffle? Using ffmpeg or something? If not, could this be added?

Thanks!

**Comment by Herschel** [comment] 2021-01-09 22:25
Duplicate of #790. Currently you can export a PNG sequence using the "exporter" tool. Thank you!

**Closed by Herschel** 2021-01-09 22:25 UTC
Labels: duplicate
