### ISSUE TITLE
Error on https://shsgames.github.io/g/6f2e0289/electric-man-2

### ISSUE THREAD

**Issue by Scoutducky** [ruffle-rs/ruffle#6992] opened 2022-05-16 13:02 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.623d280283884f514fa3.js:1:7487)
    at std::sync::once::Once::call_once::{{closure}}::hc3464e04dbb9beda (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.16/78622a1a32633d031974.wasm:wasm-function[978]:0x290404)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.16/78622a1a32633d031974.wasm:wasm-function[1431]:0x30c1c9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h44f701de063d4daa (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.16/78622a1a32633d031974.wasm:wasm-function[4913]:0x462ec6)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.16/78622a1a32633d031974.wasm:wasm-function[3250]:0x408a55)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.16/78622a1a32633d031974.wasm:wasm-function[4994]:0x466b24)
    at core::panicking::panic::he88f1b1582b09c8c (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.16/78622a1a32633d031974.wasm:wasm-function[4911]:0x462a5f)
    at core::ops::function::FnOnce::call_once::h0e85a184fa37f64b (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.16/78622a1a32633d031974.wasm:wasm-function[1069]:0x2aaf93)
    at ruffle_core::avm1::function::Executable::exec::h114e6421d0b212e0 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.16/78622a1a32633d031974.wasm:wasm-function[375]:0xfe9ba)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h35f20484d42b76a5 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.16/78622a1a32633d031974.wasm:wasm-function[549]:0x1ac13e)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://shsgames.github.io/g/6f2e0289/electric-man-2
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14588.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.59 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-16
Channel: nightly
Built: 2022-05-16T00:15:30.965Z
Commit: eb38b2fb00c7e590ed2ffdfe6f223461df10bcf8
Is extension: false

**Comment by relrelb** [comment] 2022-05-17 06:30
Duplicate of #4932.

**Closed by relrelb** 2022-05-17 06:30 UTC
Labels: error-report
