### ISSUE TITLE
Error on https://www.getgames.io/games/ruffle/

### ISSUE THREAD

**Issue by AVRodagi** [ruffle-rs/ruffle#10547] opened 2023-04-04 10:09 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmap_data.rs:262:46
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmap_data.rs:262:46
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://www.getgames.io/scripts/ruffle/core.ruffle.bbf92d6ba39c089443f3.js:1:47895)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb025c08ea6ea4a5 (wasm://wasm/02ac463e:wasm-function[8125]:0x800631)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02ac463e:wasm-function[5413]:0x735ad3)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02ac463e:wasm-function[8009]:0x7fb870)
    at core::result::unwrap_failed::hc92dbc81ca7d2f52 (wasm://wasm/02ac463e:wasm-function[6181]:0x773ae9)
    at gc_arena::gc_cell::GcCell<T>::read::h0423372c2205415c (wasm://wasm/02ac463e:wasm-function[7060]:0x7bb12c)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::copy_pixels::hdff7182988b62eb8 (wasm://wasm/02ac463e:wasm-function[666]:0x2278fe)
    at ruffle_core::avm2::function::Executable::exec::h2774ab58e122c725 (wasm://wasm/02ac463e:wasm-function[912]:0x30cec3)
    at ruffle_core::avm2::object::TObject::call_property::h201157b06688a3ce (wasm://wasm/02ac463e:wasm-function[1090]:0x3734c9)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h58b73a121c778a83 (wasm://wasm/02ac463e:wasm-function[2651]:0x5b5098)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at pastaGame.models::PastaOrder/drawIntoSlices()
    at pastaGame.models::PastaTopping/screenUpdate()
    at pastaGame.models::PastaOrder/updateBuildPasta()
    at pastaGame.models::FoodOrder/updateBuildPasta()
    at pastaGame.screens::BuildScreen/updateScreen()
    at pastaGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.getgames.io/games/ruffle/?swf=papaspastaria.swf&name=Papa%27s%20Pastaria&warn=false
SWF URL: https://www.getgames.io/games/swf/papaspastaria.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-29
Channel: nightly
Built: 2023-03-29T00:22:09.432Z
Commit: b0eb1057f1c084c054ea51aed5ab7d8e2d451db9
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 13955205

**Comment by n0samu** [comment] 2023-04-04 19:10
Duplicate of #9852. This problem has already been fixed by #10315. Please contact the website owner and ask them to update their copy of Ruffle.

**Closed by n0samu** 2023-04-04 19:10 UTC
Labels: duplicate, error-report
