### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by Kobe1987** [ruffle-rs/ruffle#12059] opened 2023-07-14 20:23 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1fb1bf8fc190c8e7 (wasm://wasm/02e582f2:wasm-function[9034]:0x8a07a6)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02e582f2:wasm-function[5991]:0x7ab2bb)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02e582f2:wasm-function[8879]:0x89bf97)
    at core::panicking::panic::h2f041bf6aa990dfd (wasm://wasm/02e582f2:wasm-function[8122]:0x8641a3)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hff0599a8a7fade47 (wasm://wasm/02e582f2:wasm-function[665]:0x20e867)
    at ruffle_core::loader::Loader::preload_tick::hcaa6e5876e9cdf3a (wasm://wasm/02e582f2:wasm-function[1752]:0x4af733)
    at ruffle_web::Ruffle::tick::hf62d561c35e58d51 (wasm://wasm/02e582f2:wasm-function[761]:0x289457)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h9b543391f42e4631 (wasm://wasm/02e582f2:wasm-function[10838]:0x8dffb7)
    at wasm_bindgen::convert::closures::invoke1_mut::h55a8b825f8333ccd (wasm://wasm/02e582f2:wasm-function[9676]:0x8bd0d2)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA Quadro P600 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=700&sp=0&questionSet=&r=8178658&&width=640&height=500&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-13
Channel: nightly
Built: 2023-07-13T00:20:50.346Z
Commit: e0886707c5b9637c3fb6d3064a6ffd2cb28117de
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by Lord-McSweeney** [comment] 2023-07-14 20:26
Duplicate of #9972

**Closed by Lord-McSweeney** 2023-07-14 20:26 UTC
Labels: error-report
