### ISSUE TITLE
Asteroids Revenge III - Asteroid that follows mouse never appears

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#5187] opened 2021-08-31 17:04 UTC
https://www.newgrounds.com/portal/view/393248/format/flash?emulate=flash

If you play Asteroids Revenge III in the Flash Player, there's a blue asteroid that follows your mouse around the screen and you want to collide it with the ship without getting hit by the red bullets.

In Ruffle, there are red bullets but the asteroid is missing and so is the ship.

**Comment by relrelb** [comment] 2021-09-07 22:04
From a quick look, this is most likely caused by `BitmapData.draw()`, which is currently unimplemented (#290).

**Comment by Lord-McSweeney** [comment] 2023-01-18 04:58
Fixed by #7254 and #9134.

**Closed by Lord-McSweeney** 2023-01-18 04:58 UTC
Labels: bug, sponsor
