### ISSUE TITLE
Error on https://www.officegamespot.com/freegames/electric-man-2.htm why are you don't fix???

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#5898] opened 2021-12-19 16:50 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.officegamespot.com/ruffle/ruffle.js:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h28627feee31e90eb (https://www.officegamespot.com/ruffle/d5304213a7d903541fbf.wasm:wasm-function[1040]:0x3171e1)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://www.officegamespot.com/ruffle/d5304213a7d903541fbf.wasm:wasm-function[1251]:0x370393)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha861918671b1460e (https://www.officegamespot.com/ruffle/d5304213a7d903541fbf.wasm:wasm-function[4754]:0x522631)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://www.officegamespot.com/ruffle/d5304213a7d903541fbf.wasm:wasm-function[3331]:0x4dbb6d)
    at rust_begin_unwind (https://www.officegamespot.com/ruffle/d5304213a7d903541fbf.wasm:wasm-function[4817]:0x524f05)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://www.officegamespot.com/ruffle/d5304213a7d903541fbf.wasm:wasm-function[5029]:0x52fac1)
    at core::panicking::panic::hec1fc057bd0baf0b (https://www.officegamespot.com/ruffle/d5304213a7d903541fbf.wasm:wasm-function[4751]:0x521e97)
    at core::ops::function::FnOnce::call_once::hc543e126b95bfc01 (https://www.officegamespot.com/ruffle/d5304213a7d903541fbf.wasm:wasm-function[1104]:0x347132)
    at ruffle_core::avm1::function::Executable::exec::h1eede69262aac50e (https://www.officegamespot.com/ruffle/d5304213a7d903541fbf.wasm:wasm-function[411]:0x16097c)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.officegamespot.com/freegames/electric-man-2.htm
SWF URL: https://www.officegamespot.com/freewebgames/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-07
Channel: nightly
Built: 2021-12-07T00:12:16.001Z
Commit: 7d5463f850f01b97513efc0b6cd8a7a59a0120ea
Is extension: false

**Comment by Poopooracoocoo** [comment] 2021-12-19 18:00
Duplicate of #4932.

**Closed by Poopooracoocoo** 2021-12-19 18:00 UTC
Labels: duplicate, error-report
