### ISSUE TITLE
Error on https://h-flash.com/touch-the-girl/

### ISSUE THREAD

**Issue by qing1883443** [ruffle-rs/ruffle#12158] opened 2023-07-19 06:57 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:640:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:640:18
    at n.wbg.__wbg_new_15d3966e9981a196 (https://h-flash.com/data/ruffle/core.ruffle.77b76ff8ebf10abc4963.js:1:48778)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h321a9078ff9936f2 (<anonymous>:wasm-function[7858]:0x80d60b)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (<anonymous>:wasm-function[5347]:0x74b7e0)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (<anonymous>:wasm-function[7750]:0x8088a8)
    at core::panicking::panic::ha3ebcac1438d9280 (<anonymous>:wasm-function[7157]:0x7cd7e3)
    at ruffle_core::display_object::container::ChildContainer::replace_at_depth::h2de1d6a0c6867e00 (<anonymous>:wasm-function[1601]:0x465d51)
    at ruffle_core::display_object::container::TDisplayObjectContainer::replace_at_depth::h21501d2f3172dfbe (<anonymous>:wasm-function[4820]:0x71fb46)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h195a33510c0b747d (<anonymous>:wasm-function[743]:0x2938ed)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::{{closure}}::h7bf1329a46718fc5 (<anonymous>:wasm-function[923]:0x32cf58)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::hff866e088751f047 (<anonymous>:wasm-function[686]:0x25ff65)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://h-flash.com/touch-the-girl/
SWF URL: https://h-flash.com/data/swf/2020/04/touchthegirl_sv.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 13; V2121A; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.141 Mobile Safari/537.36 VivoBrowser/15.2.30.0
Platform: Linux armv8l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-12
Channel: nightly
Built: 2023-03-12T00:19:04.440Z
Commit: 1deebc87e869387c962f97b665d26785d0a2b52f
Is extension: false

# Metadata
width: 960
height: 600
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 2192454

**Comment by n0samu** [comment] 2023-07-19 08:33
Duplicate of #11262

**Closed by n0samu** 2023-07-19 08:33 UTC
Labels: duplicate, nsfw, error-report
