### ISSUE TITLE
Error on https://ooooooooo.ooo/static/

### ISSUE THREAD

**Issue by DOFF6-YT** [ruffle-rs/ruffle#17268] opened 2024-07-27 04:27 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/f9e3de5/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/f9e3de5/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
    at n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.b183ccb31e9b9b70a645.js:1:79242)
    at ruffle_web.wasm.js_sys::Error::new::ha367eb220e837752 (wasm://wasm/ruffle_web.wasm-0337077e:wasm-function[12852]:0x9dfd21)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hf90e4a564c6c6ca6 (wasm://wasm/ruffle_web.wasm-0337077e:wasm-function[9915]:0x975bb0)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h844c7fdc9e749b51 (wasm://wasm/ruffle_web.wasm-0337077e:wasm-function[6535]:0x86a429)
    at ruffle_web.wasm.core::panicking::panic_fmt::h8d7e2d43cfcec163 (wasm://wasm/ruffle_web.wasm-0337077e:wasm-function[10315]:0x9a0a87)
    at ruffle_web.wasm.core::option::expect_failed::hd7479ca38c4d39b8 (wasm://wasm/ruffle_web.wasm-0337077e:wasm-function[9084]:0x9457e9)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::hc6cf2b758bc55ab2 (wasm://wasm/ruffle_web.wasm-0337077e:wasm-function[771]:0xf9cd5)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::hc6cf2b758bc55ab2 (wasm://wasm/ruffle_web.wasm-0337077e:wasm-function[771]:0xf6e44)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_object_static::h73c91b1d91eebf9c (wasm://wasm/ruffle_web.wasm-0337077e:wasm-function[4379]:0x77daf9)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::hc6cf2b758bc55ab2 (wasm://wasm/ruffle_web.wasm-0337077e:wasm-function[771]:0xf9b29)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at BinaryData$/getMovieClipManager()
    at Game/onLoadComplete()
    at Game()
    at Main/createGame()
    at Main/onRootCreated()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-2020()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 4600 (0x00000412) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://ooooooooo.ooo/static/?23857723-4ca8-4e73-b48d-c844501381a1
SWF URL: http://chat.kongregate.com/gamez/0021/9572/live/TequilaZombies3.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-27
Channel: nightly
Built: 2024-07-27T00:05:30.539Z
Commit: 3f85265bc7d8407005e20263777a622890e02a7f
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 21
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 38307363

**Comment by n0samu** [comment] 2024-07-27 07:02
Duplicate of #13748

**Closed by n0samu** 2024-07-27 07:02 UTC
Labels: duplicate, error-report
