### ISSUE TITLE
Error on https://game179258.konggames.com/games/randomnine/cardinal-quest-2/frame/57487512-b866-4f06-b560-3d77f4074913/

### ISSUE THREAD

**Issue by abcdnned** [ruffle-rs/ruffle#16638] opened 2024-06-08 14:44 UTC
# Error Info
Error name: Error
Error message: panicked at render/naga-pixelbender/src/lib.rs:1223:29:
Unimplemented opcode Step
Error stack:
```
Error: panicked at render/naga-pixelbender/src/lib.rs:1223:29:
Unimplemented opcode Step
    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.45317f6c7f2721859acd.js:1:75592)
    at ruffle_web.wasm.js_sys::Error::new::ha59a397dfb01052a (wasm://wasm/ruffle_web.wasm-0339ba0e:wasm-function[12822]:0x9fbda2)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d553c011316b6be (wasm://wasm/ruffle_web.wasm-0339ba0e:wasm-function[10455]:0x9b6312)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-0339ba0e:wasm-function[6533]:0x87fc11)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-0339ba0e:wasm-function[10198]:0x9af1b3)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h959bc0d2524aa696 (wasm://wasm/ruffle_web.wasm-0339ba0e:wasm-function[8476]:0x91a0f4)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::display::shader_data::init::h02bc530de09631f4 (wasm://wasm/ruffle_web.wasm-0339ba0e:wasm-function[1537]:0x44f8fb)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::hbc7d499c270a1b0e (wasm://wasm/ruffle_web.wasm-0339ba0e:wasm-function[1138]:0x334a48)
    at ruffle_web.wasm.ruffle_core::avm2::object::TObject::call_method::h00e270e37d71bc60 (wasm://wasm/ruffle_web.wasm-0339ba0e:wasm-function[2286]:0x5a301f)
    at ruffle_web.wasm.ruffle_core::avm2::activation::Activation::run_actions::ha8f0c8079bc12694 (wasm://wasm/ruffle_web.wasm-0339ba0e:wasm-function[742]:0x2f671)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at flixelcq.tile::FlxCqTilemap()
    at cq::CqLevel()
    at cq::CqWorld/executeGoToLevel()
    at cq.states::GameState/continueInitialisation()
    at cq.states::GameState/update()
    at flixel::FlxState/tryUpdate()
    at flixel::FlxGame/update()
    at cq::Main/update()
    at flixel::FlxGame/step()
    at flixel::FlxGame/onEnterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (ATI Technologies Inc., AMD Radeon Pro Vega 16 OpenGL Engine, OpenGL 4.1)"
Adapter Device Type: Other
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 16384, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 128, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game179258.konggames.com/games/randomnine/cardinal-quest-2/frame/57487512-b866-4f06-b560-3d77f4074913/?kongregate_host=www.kongregate.com
SWF URL: https://game179258.konggames.com/gamez/0017/9258/live/cq2.swf?kongregate_game_version=1465851167

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-06-08
Channel: nightly
Built: 2024-06-08T00:05:40.726Z
Commit: 6e53f980687cbc00ca5b505ff7a74df9a1a8c2a3
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 15
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 20519535

**Comment by evilpie** [comment] 2024-10-12 16:11
#Duplicate of #14068

**Closed by evilpie** 2024-10-12 16:11 UTC
Labels: bug, unimplemented, A-avm2, panic, error-report, pixelbender
