### ISSUE TITLE
Error on https://sexflashgame.org/wp-content/games/harleys-prison-break/index.php

### ISSUE THREAD

**Issue by FearXD0** [ruffle-rs/ruffle#9379] opened 2023-02-01 02:41 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://sexflashgame.org/wp-content/ruffle/core.ruffle.e040f6d42b8f321914a0.js:1:7632)
    at std::sync::once::Once::call_once::{{closure}}::he80a94c0f5d51ad9 (https://sexflashgame.org/wp-content/ruffle/d05150f3d04f28cdc285.wasm:wasm-function[964]:0x28b1c7)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://sexflashgame.org/wp-content/ruffle/d05150f3d04f28cdc285.wasm:wasm-function[1464]:0x31df95)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hfd41d197921787cc (https://sexflashgame.org/wp-content/ruffle/d05150f3d04f28cdc285.wasm:wasm-function[4834]:0x465e46)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://sexflashgame.org/wp-content/ruffle/d05150f3d04f28cdc285.wasm:wasm-function[3222]:0x40de9f)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://sexflashgame.org/wp-content/ruffle/d05150f3d04f28cdc285.wasm:wasm-function[4916]:0x46ac8a)
    at core::result::unwrap_failed::ha62420c192a556da (https://sexflashgame.org/wp-content/ruffle/d05150f3d04f28cdc285.wasm:wasm-function[4053]:0x44db14)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hc0c63944bfb28d77 (https://sexflashgame.org/wp-content/ruffle/d05150f3d04f28cdc285.wasm:wasm-function[660]:0x1fe848)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::hfd905a521eed9a8c (https://sexflashgame.org/wp-content/ruffle/d05150f3d04f28cdc285.wasm:wasm-function[2831]:0x3ee6cd)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::hf5a51b9aaa7a0969 (https://sexflashgame.org/wp-content/ruffle/d05150f3d04f28cdc285.wasm:wasm-function[2574]:0x3cd1ee)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://sexflashgame.org/wp-content/games/harleys-prison-break/index.php
SWF URL: https://sexflashgame.org/wp-content/games/harleys-prison-break/harleys-prison-break.swf.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) FlashBrowser/1.0.0 Chrome/83.0.4103.122 Electron/9.4.4 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-18
Channel: nightly
Built: 2022-05-18T00:14:23.914Z
Commit: 135833e4000168efe291bca926f718eedc0069bb
Is extension: false

**Comment by Lord-McSweeney** [comment] 2023-02-01 03:22
Duplicate of #8705.

**Closed by Lord-McSweeney** 2023-02-01 03:22 UTC
Labels: error-report
