### ISSUE TITLE
[question] sound sync with timeline

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#202] opened 2019-12-21 13:33 UTC
@Herschel,

I use SWFTools to generate presentations (such as these https://www.free-culture.tk/). These are slides (frames) synced with sound according to an array of transition times in milliseconds from the sound start.

The way to get them perfectly synced in Flash is to add 500 ms to each transition time (I read this somewhere long ago [I forgot the details]).

But that approach is problematic with other programs (Lightspark, Ruffle may be in the future [unimplemented yet]).

Since #10 mentions audio sync with timeline, which issues are to be considered to get perfect audio syncing with the timeline?

Many thanks for your help.

**Comment by Herschel** [comment] 2019-12-21 18:45
Hi @ousia,

Mostly #10 is concerned about "Stream" sounds, which is a flag you set on sounds in the Flash editor that causes the player to drop frames/stall in order to keep sync with a sound, used by animations. These use the SoundStreamBlock SWF tags.

I haven't looked too deeply at the presentations, but at least `free_culture.swf`  uses an Event sound, so it actually has no syncing guarantees at all (if your PC went under heavy load, the audio would get out of sync with the slides). These use the StartSound SWF tags, or the Sound object in AS. So if these are long-playing, out-of-sync there is not a bug.

The AS code stops/restarts the sound using a Sound object with the timing values when you use the arrow keys, and hopefully our timing here would match Flash's. So if the sounds don't start at the correct timing (500ms off?), this would be a bug. Of course, we don't have Sound implemented yet (#183), but this should be done soon and you can give it a test :-)

**Comment by ousia** [comment] 2019-12-21 20:45
@Herschel,

this is the relevant code for automatic frame advance:

``` js
var times=new Array();
var maxtimes;
var position;

snd = new Sound(this);
snd.attachSound("audio");
position = 0;

maxtimes=242;
times[0]=0;
times[1]=17326;
times[2]=29172;
times[3]=33994;
times[4]=39681;
times[5]=45132;
times[6]=49246;
times[7]=50582;
// and so on...

function check_time() { // stripped to essential
    if ((snd.position>=times[position])&&(snd.position<times[position+1])) {
            slides.gotoAndStop(position+1);
        }
}

setInterval(check_time, 10);
```

A minimal version of the code for arrow keys is:

``` js
function previous_slide() {
    if (position > 0) {
        snd.position = times[position-1];
    } else {
        snd.position = 0;
    }
    snd.start(sound_position/1000.0,0);
}

function next_slide() {
    snd.position = times[position+1];
    if (snd.position > snd.duration) {
        snd.position = snd.duration - 500;
    }
    snd.start(sound_position/1000.0,0);
}


key_listen.onKeyDown = function() {
    switch (Key.getCode()) {
        case 37:
            previous_slide();
        break;
        case 39:
            next_slide();
        break;
    }
};
```

Is this approach better or can it get out of sync under heavy computation load?

**Comment by Herschel** [comment] 2019-12-21 21:09
I see, so if it is using Sound.position, it should stay in sync. When we implement Sound, there will be too things to check:
 * Sound.position returns the correct number of milliseconds (when letting the slide play). If Flash has an offset of ~500ms, I guess we should try to match this.
 * Sound.start starts the sound at the proper offset (when moving slides with arrow keys)

**Comment by ousia** [comment] 2019-12-21 21:32
Many thanks for your reply, @Herschel.

**Comment by Herschel** [comment] 2019-12-22 20:42
Closing, feel free to ask further questions.

**Closed by Herschel** 2019-12-22 20:42 UTC
Labels: question
