### ISSUE TITLE
Error on https://www.sinapsi.org/wordpress/

### ISSUE THREAD

**Issue by passegua** [ruffle-rs/ruffle#9613] opened 2023-02-17 15:05 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create buffer object"', /home/runner/.cargo/git/checkouts/wgpu-e4487c3622394142/a154700/wgpu-hal/src/gles/device.rs:469:24
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create buffer object"', /home/runner/.cargo/git/checkouts/wgpu-e4487c3622394142/a154700/wgpu-hal/src/gles/device.rs:469:24
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://www.sinapsi.org/public/ruffle/core.ruffle.a49238dfca6067045ab9.js:1:5353)
    at std::sync::once::Once::call_once::{{closure}}::h5f93984c1300ca75 (wasm://wasm/0271628a:wasm-function[1568]:0x404863)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/0271628a:wasm-function[1975]:0x495c54)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he904c54109aabe24 (wasm://wasm/0271628a:wasm-function[7083]:0x7404ce)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/0271628a:wasm-function[5006]:0x6a1597)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/0271628a:wasm-function[7403]:0x74f232)
    at core::result::unwrap_failed::h5f2e1804ca266e0b (wasm://wasm/0271628a:wasm-function[5914]:0x6e5ce4)
    at wgpu_hal::gles::device::<impl wgpu_hal::Device<wgpu_hal::gles::Api> for wgpu_hal::gles::Device>::create_buffer::hf475e87f44e8a9c2 (wasm://wasm/0271628a:wasm-function[2012]:0x49e2da)
    at wgpu_core::device::Device<A>::create_buffer::hbdaffc815ef2db43 (wasm://wasm/0271628a:wasm-function[2138]:0x4bd7ac)
    at <T as wgpu::context::DynContext>::device_create_buffer::h166d05347403a944 (wasm://wasm/0271628a:wasm-function[5698]:0x6d560c)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: PUSH_CONSTANTS
Available features: TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | CLEAR_TEXTURE | MULTIVIEW
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, max_push_constant_size: 96, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_buffer_size: 268435456 }
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://www.sinapsi.org/public/cuore.swf
Param movie: https://www.sinapsi.org/public/cuore.swf
Attribute 0: undefined
Attribute 1: undefined

# Page Info
Page URL: https://www.sinapsi.org/wordpress/
SWF URL: https://www.sinapsi.org/public/cuore.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 OPR/95.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-18
Channel: nightly
Built: 2023-01-18T01:27:15.115Z
Commit: b5c6d5debe06922b40f47a72d1bf16c53f9db05c
Is extension: false

# Metadata

**Comment by n0samu** [comment] 2023-02-17 19:14
Duplicate of #9611

**Closed by n0samu** 2023-02-17 19:14 UTC
Labels: duplicate, error-report
