### ISSUE TITLE
Error on https://playsexgames.xxx/mummy-love-chapter-3/

### ISSUE THREAD

**Issue by Corwas** [ruffle-rs/ruffle#6797] opened 2022-04-24 18:50 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:499:50

# Player Info
Allows script access: true

# Page Info
Page URL: https://playsexgames.xxx/mummy-love-chapter-3/
SWF URL: https://playsexgames.xxx/play-sex-games/mummy_love_chapter_3.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-05
Channel: nightly
Built: 2021-05-05T00:12:57.039Z
Commit: b82391726f76c059b3c33636e6c9980a4fdac5c4

**Comment by Corwas** [comment] 2022-04-24 18:51
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:499:50
Error stack:
```
240/e/a.wbg.__wbg_new_df6e6ab7a65c4c4d@https://playsexgames.xxx/html/ruffle.js:1:7026
std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[1028]:0x2759ad
std::sync::once::Once::call_inner::hf7fd718057964857@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[1233]:0x2a5afa
core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[3718]:0x443b09
std::panicking::rust_panic_with_hook::h9d91fa0fae16500f@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2709]:0x394d06
rust_begin_unwind@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[3923]:0x4493db
core::panicking::panic_fmt::h91d2023e5afe1929@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[4064]:0x44fed2
core::option::expect_none_failed::h203584ddbc785ca2@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[3355]:0x434f5e
ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h9989bebaa574ac40@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[525]:0x172290
<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::hac0b7d4b707e2eb3@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2283]:0x3715d0
ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h6e796720111363d6@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[1614]:0x2ff6c6
ruffle_core::display_object::movie_clip::MovieClip::preload::ha37500235e5a02c5@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[616]:0x1af7c6
ruffle_core::player::Player::set_root_movie::hf9bbdab424c9270e@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[333]:0xaab27
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h58865a2bc9110d0e@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[496]:0x15b354
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h02a1ee96da13c6d2@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[1411]:0x2d8119
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hea761618c052ebca@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2258]:0x35f910
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hdce6c36b86516137@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[4201]:0x452087
T@https://playsexgames.xxx/html/ruffle.js:1:4150
a@https://playsexgames.xxx/html/ruffle.js:1:2798
promise callback*240/e/a.wbg.__wbg_then_367b3e718069cfb9@https://playsexgames.xxx/html/ruffle.js:1:29712
wasm_bindgen_futures::queue::Queue::push_task::h67b81f8c51853209@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2636]:0x38e953
wasm_bindgen_futures::task::singlethread::Task::into_raw_waker::raw_wake::hef6537ebc115360d@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2503]:0x385c81
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::finish::h9e396734d597f4a8@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2225]:0x35b8de
<T as wasm_bindgen::closure::WasmClosureFnOnce<A,R>>::into_fn_mut::{{closure}}::hc53565c4e2a2d8bb@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[3721]:0x443bf8
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hdce6c36b86516137@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[4201]:0x452087
T@https://playsexgames.xxx/html/ruffle.js:1:4150
a@https://playsexgames.xxx/html/ruffle.js:1:2798
promise callback*240/e/a.wbg.__wbg_then_ac66ca61394bfd21@https://playsexgames.xxx/html/ruffle.js:1:29789
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::he303a82549ffdc86@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[1330]:0x2bdec2
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h22c7a163c753dbe8@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[562]:0x18aed7
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h58865a2bc9110d0e@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[496]:0x15b045
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h02a1ee96da13c6d2@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[1411]:0x2d8119
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hea761618c052ebca@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2258]:0x35f910
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hdce6c36b86516137@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[4201]:0x452087
T@https://playsexgames.xxx/html/ruffle.js:1:4150
a@https://playsexgames.xxx/html/ruffle.js:1:2798
promise callback*240/e/a.wbg.__wbg_then_367b3e718069cfb9@https://playsexgames.xxx/html/ruffle.js:1:29712
wasm_bindgen_futures::queue::Queue::push_task::h67b81f8c51853209@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2636]:0x38e953
wasm_bindgen_futures::task::singlethread::Task::into_raw_waker::raw_wake::hef6537ebc115360d@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2503]:0x385c81
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::finish::h9e396734d597f4a8@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2225]:0x35b8de
<T as wasm_bindgen::closure::WasmClosureFnOnce<A,R>>::into_fn_mut::{{closure}}::hc53565c4e2a2d8bb@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[3721]:0x443bf8
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hdce6c36b86516137@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[4201]:0x452087
T@https://playsexgames.xxx/html/ruffle.js:1:4150
a@https://playsexgames.xxx/html/ruffle.js:1:2798
promise callback*240/e/a.wbg.__wbg_then_ac66ca61394bfd21@https://playsexgames.xxx/html/ruffle.js:1:29789
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::he303a82549ffdc86@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[1330]:0x2bdec2
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h22c7a163c753dbe8@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[562]:0x18acc7
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h58865a2bc9110d0e@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[496]:0x15b045
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h02a1ee96da13c6d2@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[1411]:0x2d8119
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hea761618c052ebca@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2258]:0x35f910
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hdce6c36b86516137@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[4201]:0x452087
T@https://playsexgames.xxx/html/ruffle.js:1:4150
a@https://playsexgames.xxx/html/ruffle.js:1:2798
promise callback*240/e/a.wbg.__wbg_then_367b3e718069cfb9@https://playsexgames.xxx/html/ruffle.js:1:29712
wasm_bindgen_futures::queue::Queue::push_task::h67b81f8c51853209@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[2636]:0x38e953
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::hb72fc232095bd84e@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[3589]:0x43fb3d
ruffle_stream_from@https://playsexgames.xxx/html/d6dd295efb44ba365d0d.wasm:wasm-function[3462]:0x43a437
stream_from@https://playsexgames.xxx/html/ruffle.js:1:5045
240/load/<@https://playsexgames.xxx/html/ruffle.js:1:51964
a@https://playsexgames.xxx/html/ruffle.js:1:45752
promise callback*c@https://playsexgames.xxx/html/ruffle.js:1:45917
240/oe/<@https://playsexgames.xxx/html/ruffle.js:1:45928
oe@https://playsexgames.xxx/html/ruffle.js:1:45695
load@https://playsexgames.xxx/html/ruffle.js:1:50840
connectedCallback@https://playsexgames.xxx/html/ruffle.js:1:64847
Te@https://playsexgames.xxx/html/ruffle.js:1:69687
Ne@https://playsexgames.xxx/html/ruffle.js:1:71166
polyfill@https://playsexgames.xxx/html/ruffle.js:1:75761
init@https://playsexgames.xxx/html/ruffle.js:1:74914
EventListener.handleEvent*De@https://playsexgames.xxx/html/ruffle.js:1:74305
negotiate@https://playsexgames.xxx/html/ruffle.js:1:75578
@https://playsexgames.xxx/html/ruffle.js:1:77122
@https://playsexgames.xxx/html/ruffle.js:1:77219
@https://playsexgames.xxx/html/ruffle.js:1:77223

```

# Player Info
Allows script access: true

# Page Info
Page URL: https://playsexgames.xxx/mummy-love-chapter-3/
SWF URL: https://playsexgames.xxx/play-sex-games/mummy_love_chapter_3.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-05
Channel: nightly
Built: 2021-05-05T00:12:57.039Z
Commit: b82391726f76c059b3c33636e6c9980a4fdac5c4

**Comment by Herschel** [comment] 2022-04-28 23:37
Dupe of #1905, also old Ruffle version.

**Closed by Herschel** 2022-04-28 23:37 UTC
Labels: nsfw, error-report
