### ISSUE TITLE
https://games.arantius.com/game.86.8+planet.html

### ISSUE THREAD

**Issue by cmlad26** [ruffle-rs/ruffle#3402] opened 2021-02-23 19:35 UTC
The game does not move to the next level.

![image](https://user-images.githubusercontent.com/76111979/108897618-f8c9c000-761e-11eb-83af-d8e5857fb7c7.png)

**Comment by n0samu** [comment] 2023-06-21 06:55
Duplicate of #3271

**Closed by n0samu** 2023-06-21 06:55 UTC
Labels: duplicate
