### ISSUE TITLE
Escaping the Prison: Overlapping music when failing on badass route.

### ISSUE THREAD

**Issue by Infinity48Games** [ruffle-rs/ruffle#8876] opened 2022-12-20 15:35 UTC
### Describe the bug

SWF: http://farm.stickpage.com/escapingtheprisongame.swf
In the chase segment after choosing "Drill" at the beginning, after you lose the music continues and starts overlapping with other instances of itself after you retry.

### Expected behavior

The music stops after you fail and restarts once you click retry.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome 108

### Additional information

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=http%3A%2F%2Ffarm.stickpage.com%2Fescapingtheprisongame.swf
SWF URL: http://farm.stickpage.com/escapingtheprisongame.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-20
Channel: nightly
Built: 2022-12-20T00:37:48.783Z
Commit: 9db6ace65f258097d1ed82664b0ef704bf693fdc
Is extension: true

# Metadata
width: 650
height: 450
frameRate: 30
numFrames: 15985
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 13613526

**Comment by LukeSaward1** [comment] 2022-12-20 23:48
Duplicate of #8067

**Comment by n0samu** [comment] 2022-12-21 05:54
I appreciate the additional detail though. I've added it as a comment to the original issue.

**Closed by n0samu** 2022-12-21 05:54 UTC
Labels: bug
