### ISSUE TITLE
Ruffle crashed

### ISSUE THREAD

**Issue by WenSimEHRP** [ruffle-rs/ruffle#18019] opened 2024-09-21 05:46 UTC
### Describe what you were doing

Launched and crashed

### What does the crash message say?

panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:786:18:
Error in Surface::configure: Validation Error

Caused by:
  Parent device is lost

### Ruffle Version

0.1.0-nightly (09b3bc25ba902f8c11e6c49cbb77f30a888b79b8 2024-09-20)

### Affected platform

Desktop app

### Operating system

Manjaro 24.0.8 (Wynsdey) [64-bit]

**Comment by evilpie** [comment] 2024-12-08 14:20
Duplicate of #18690

**Closed by evilpie** 2024-12-08 14:20 UTC
Labels: bug, panic
