### ISSUE TITLE
Error on https://res2-mssp2.gamesow.com/bin/WebLaucher.html

### ISSUE THREAD

**Issue by luiseduardovalenciaparra** [ruffle-rs/ruffle#8792] opened 2022-12-15 05:27 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://kfbchhhnkjenklhpbfidngphdhidmcan/dist/966.js:1:6972)
    at std::sync::once::Once::call_once::{{closure}}::hcfb484f0d9d0b673 (wasm://wasm/0191619e:wasm-function[926]:0x26b835)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0191619e:wasm-function[1405]:0x3196b3)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h71fbea26086442fa (wasm://wasm/0191619e:wasm-function[4979]:0x4bcdeb)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0191619e:wasm-function[3760]:0x47b60b)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0191619e:wasm-function[5219]:0x4c1c14)
    at core::option::expect_failed::h2290d18a0c9a6a24 (wasm://wasm/0191619e:wasm-function[5899]:0x4d53bf)
    at ruffle_core::display_object::stage::Stage::root_clip::h01b572eb09f00dc6 (wasm://wasm/0191619e:wasm-function[3695]:0x4756e9)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc812711a714b45dc (wasm://wasm/0191619e:wasm-function[1119]:0x2ab130)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3660decffd20cd4e (wasm://wasm/0191619e:wasm-function[1023]:0x28d54d)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://res2-mssp2.gamesow.com/bin/WebLaucher.html?userid=463010&username=463010&cm=1&server_id=S102&time=1671082026&server_name=S102&flag=90276319ed6b0d50eadd3942a3cb61ef
SWF URL: https://res2-mssp2.gamesow.com/bin/WebLaucher.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-15
Channel: nightly
Built: 2022-12-15T00:16:26.229Z
Commit: cf03ee743079ad4f08706410a1dc465351775108
Is extension: true

# Metadata
width: 1000
height: 600
frameRate: 24
numFrames: 1
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 26925

**Comment by n0samu** [comment] 2022-12-15 06:53
Duplicate of #8456

**Closed by n0samu** 2022-12-15 06:53 UTC
Labels: duplicate, error-report
