### ISSUE TITLE
Error on https://armorgames.com/play/4480/frontier

### ISSUE THREAD

**Issue by akerbabber** [ruffle-rs/ruffle#15180] opened 2024-02-10 02:11 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/display_object/container.rs:973:22:
called `Option::unwrap()` on a `None` value
Error stack:
```
Error: panicked at core/src/display_object/container.rs:973:22:
called `Option::unwrap()` on a `None` value
    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://agi.armorgames.com/ruffle/core.ruffle.67bc37f4e63c43ff9c64.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbaaeff1a92f05ba2 (wasm://wasm/035cabca:wasm-function[10705]:0xa04127)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/035cabca:wasm-function[6570]:0x8f2a2a)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/035cabca:wasm-function[10428]:0x9fde71)
    at core::panicking::panic::hd37d8d0a98259c88 (wasm://wasm/035cabca:wasm-function[9998]:0x9e35d6)
    at core::ops::function::FnOnce::call_once::h8c73e1e171a7eda7 (wasm://wasm/035cabca:wasm-function[988]:0x3686d6)
    at ruffle_core::avm1::function::Executable::exec::hfb96df7c867cde27 (wasm://wasm/035cabca:wasm-function[716]:0x2079b2)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hff4012539745a2d2 (wasm://wasm/035cabca:wasm-function[3016]:0x6d1a7d)
    at ruffle_core::avm1::activation::Activation::do_action::hce3c495630ea3091 (wasm://wasm/035cabca:wasm-function[1115]:0x3c4af3)
    at ruffle_core::avm1::function::Executable::exec::hfb96df7c867cde27 (wasm://wasm/035cabca:wasm-function[716]:0x2077b0)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, ANGLE Metal Renderer: Apple M1, Unspecified Version)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://armorgames.com/play/4480/frontier?tag-referral=rpg
SWF URL: https://cache.armorgames.com/files/games/frontier-4480.swf?v=1373587522

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-08
Channel: nightly
Built: 2024-01-08T00:15:28.895Z
Commit: 47db84473a639c405289bb86ce238a83af574137
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 40
swfVersion: 10
backgroundColor: #003300
isActionScript3: false
uncompressedLength: 6201007

**Comment by n0samu** [comment] 2024-06-22 03:48
Duplicate of #13577

**Closed by n0samu** 2024-06-22 03:48 UTC
Labels: duplicate, error-report
