### ISSUE TITLE
Error on https://www.newgrounds.com/portal/view/501065

### ISSUE THREAD

**Issue by Rho1Cancri** [ruffle-rs/ruffle#16975] opened 2024-07-03 02:16 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f77055/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f77055/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3701:21)
    at ruffle_web.wasm.js_sys::Error::new::h7d42a5777dfd5fa9 (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[12912]:0xa05b79)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h1d5d927fd22d08ce (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[9908]:0x99b106)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[6576]:0x87f972)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[10344]:0x9c6df0)
    at ruffle_web.wasm.core::panicking::panic_display::hbd841ae85eb3dff4 (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[9839]:0x993064)
    at ruffle_web.wasm.core::option::expect_failed::h637b3c5bf9792ea8 (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[10917]:0x9d19ec)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::h217715a57087d741 (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[765]:0xd81e8)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_object_static::h6302ac3115efdad3 (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[4477]:0x7941a2)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::h217715a57087d741 (wasm://wasm/ruffle_web.wasm-033febee:wasm-function[765]:0xd8053)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at General::Database$/()
    at General::Database$/    ()
    at Game.Challenges::ControllerSpaceship()
    at Main/update()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00004626) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: https://uploads.ungrounded.net/501000/501065_incredibots2.swf?123
Param wmode: direct
Param allowscriptaccess: never
Param allowfullscreen: true
Param allowfullscreeninteractive: true
Param flashvars: NewgroundsAPI_PublisherID=1&NewgroundsAPI_SandboxID=6684b2ef78193&NewgroundsAPI_SessionID=V5O1CAMpXIesav7sQPZw613a5030fa1ab2da4e0ffc47aad1278a4a29291ePajx&NewgroundsAPI_UserName=SpaceRanger196&NewgroundsAPI_UserID=10687330&ng_username=SpaceRanger196
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.newgrounds.com/portal/view/501065
SWF URL: https://uploads.ungrounded.net/501000/501065_incredibots2.swf?123

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-03
Channel: nightly
Built: 2024-07-03T00:05:23.559Z
Commit: 803a8c427ac6449fc4a604351c0b3ed654b5d29e
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #869CA7
isActionScript3: true
uncompressedLength: 1644015

**Comment by n0samu** [comment] 2024-07-03 05:08
Duplicate of #10520

**Closed by n0samu** 2024-07-03 05:08 UTC
Labels: duplicate, error-report
