### ISSUE TITLE
Error on https://games.crazygames.com/en_US/madness-project-nexus/index.html

### ISSUE THREAD

**Issue by thecowmilk** [ruffle-rs/ruffle#8513] opened 2022-11-10 10:38 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://files.crazygames.com/gameframe/ruffle/2022-10-08/core.ruffle.c00b1522f61b16f6f730.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/01800756:wasm-function[1035]:0x2a7210)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01800756:wasm-function[1498]:0x32a258)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/01800756:wasm-function[4956]:0x48841a)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01800756:wasm-function[3645]:0x444624)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01800756:wasm-function[5111]:0x48b8d0)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/01800756:wasm-function[4250]:0x46f245)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h87f89f6d933b9a5b (wasm://wasm/01800756:wasm-function[2568]:0x3e2484)
    at ruffle_core::display_object::render_base::h86fa7eaf5d8f56b5 (wasm://wasm/01800756:wasm-function[1216]:0x2e6e75)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hfa8c7706dc71138d (wasm://wasm/01800756:wasm-function[3870]:0x45a4af)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://games.crazygames.com/en_US/madness-project-nexus/index.html
SWF URL: https://files.crazygames.com/madness-project-nexus/1/MadnessNexus.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-08
Channel: nightly
Built: 2022-10-08T00:21:16.770Z
Commit: 5c9471436371f24f1d95011d21b5cddb7fc4ee7f
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by n0samu** [comment] 2022-11-10 20:42
Duplicate of #7978. This problem has already been fixed by #8248. Please contact the webmaster and ask them to update their copy of Ruffle.

**Closed by n0samu** 2022-11-10 20:42 UTC
Labels: duplicate, error-report
