### ISSUE TITLE
Error on https://gakko.pjwstk.edu.pl/materialy/262/lec/w9eng.htm

### ISSUE THREAD

**Issue by Omarowski** [ruffle-rs/ruffle#7009] opened 2022-05-17 15:13 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://nogekgelkgbdbgmmdbegcipojhhiobab/dist/966.js:1:7485)
    at std::sync::once::Once::call_once::{{closure}}::ha242d4d2b43703ce (chrome-extension://nogekgelkgbdbgmmdbegcipojhhiobab/dist/3ca577b52db5bd6a3fb0.wasm:wasm-function[978]:0x290403)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (chrome-extension://nogekgelkgbdbgmmdbegcipojhhiobab/dist/3ca577b52db5bd6a3fb0.wasm:wasm-function[1431]:0x30c1c8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h88636dd63977a123 (chrome-extension://nogekgelkgbdbgmmdbegcipojhhiobab/dist/3ca577b52db5bd6a3fb0.wasm:wasm-function[4913]:0x462e84)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (chrome-extension://nogekgelkgbdbgmmdbegcipojhhiobab/dist/3ca577b52db5bd6a3fb0.wasm:wasm-function[3250]:0x408a9a)
    at core::panicking::panic_fmt::h5118e89563022e7e (chrome-extension://nogekgelkgbdbgmmdbegcipojhhiobab/dist/3ca577b52db5bd6a3fb0.wasm:wasm-function[4994]:0x466b08)
    at core::result::unwrap_failed::ha62420c192a556da (chrome-extension://nogekgelkgbdbgmmdbegcipojhhiobab/dist/3ca577b52db5bd6a3fb0.wasm:wasm-function[4104]:0x44a9ec)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h0f002abcfeed1678 (chrome-extension://nogekgelkgbdbgmmdbegcipojhhiobab/dist/3ca577b52db5bd6a3fb0.wasm:wasm-function[717]:0x20f8c7)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::ha92a8909b5942424 (chrome-extension://nogekgelkgbdbgmmdbegcipojhhiobab/dist/3ca577b52db5bd6a3fb0.wasm:wasm-function[1703]:0x34866c)
    at ruffle_core::font::Font::from_swf_tag::h46254eafcb85bf7a (chrome-extension://nogekgelkgbdbgmmdbegcipojhhiobab/dist/3ca577b52db5bd6a3fb0.wasm:wasm-function[655]:0x1f19fd)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://gakko.pjwstk.edu.pl/materialy/262/lec/w9eng.htm
SWF URL: https://gakko.pjwstk.edu.pl/materialy/262/lec/fig9/u9.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-17
Channel: nightly
Built: 2022-05-17T00:16:53.792Z
Commit: ede81be4279e0af289ebc5057ebcdb12d5f99a38
Is extension: true

**Comment by Herschel** [comment] 2022-05-17 18:41
Dupe of #1905

**Closed by Herschel** 2022-05-17 18:41 UTC
Labels: error-report
