### ISSUE TITLE
Language Translation Mess

### ISSUE THREAD

**Issue by EhudKirsh** [ruffle-rs/ruffle#18817] opened 2024-12-01 09:26 UTC
### Describe the bug

The Hebrew language translation is a complete mess! Like, nobody checked whether it actually reads from right to left like it should! When you go to File -> Preferences... -> Language, all the lettes are reversed. For example, imagine in English if I write 'secnereferP' instead of 'Preferences'. 

You might wanna use the JS equivilant of .split('').reverse().join('')

It'd be good if you check the Arabic language as well, because it's probably another left-to-right mess as well.

### Expected behavior

It should read from right to left.

### Content Location

File -> Preferences... -> Language

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by kjarosh** [comment] 2024-12-01 09:44
Duplicate of https://github.com/ruffle-rs/ruffle/issues/16653

**Closed by kjarosh** 2024-12-01 09:44 UTC
Labels: bug
