### ISSUE TITLE
Belly Biff - You can't feed him

### ISSUE THREAD

**Issue by Nyehmeh** [ruffle-rs/ruffle#1451] opened 2020-11-02 03:06 UTC
https://web.archive.org/web/20010623081720id_/http://www.toomunchfun.com:80/eatit/biff.swf

Normally when you play this game you can drag objects to Biff's mouth and he'll eat them with an animation following. That doesn't happen in ruffle where instead he just leaves his mouth open with the object sitting there.

**Comment by Toad06** [comment] 2020-11-02 09:17
Thanks for your testings.
This seems to be a duplicate of #795 (`_droptarget` property currently unimplemented) but I'll let the devs verify.

**Comment by Herschel** [comment] 2021-06-16 20:12
Fixed by #4584.

**Closed by Herschel** 2021-06-16 20:12 UTC
