### ISSUE TITLE
Error on https://game70421.konggames.com/games/BoMToons/chibi-knight/frame/6cd1c6fe-8778-43f9-a9d5-f071e97ac726/

### ISSUE THREAD

**Issue by Zexoi** [ruffle-rs/ruffle#9418] opened 2023-02-05 05:09 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:756:32
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:756:32
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.89a2ee962fe0b0179ef6.js:1:5412)
    at std::sync::once::Once::call_once::{{closure}}::h24436b3e76607d05 (wasm://wasm/027a1966:wasm-function[1921]:0x48deaa)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027a1966:wasm-function[1855]:0x47dab2)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdf8faf7e861f36fc (wasm://wasm/027a1966:wasm-function[7118]:0x7611d5)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027a1966:wasm-function[5050]:0x6bedbf)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027a1966:wasm-function[7429]:0x76fed4)
    at core::panicking::panic::h364c37174a08a6a4 (wasm://wasm/027a1966:wasm-function[6843]:0x73c851)
    at core::ops::function::FnOnce::call_once::hc3dca223e3bc8c64 (wasm://wasm/027a1966:wasm-function[787]:0x27c07b)
    at ruffle_core::avm1::function::Executable::exec::h05de1024cd75b75b (wasm://wasm/027a1966:wasm-function[578]:0x1859f1)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hdb83886636a26c3d (wasm://wasm/027a1966:wasm-function[1384]:0x3ae37c)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game70421.konggames.com/games/BoMToons/chibi-knight/frame/6cd1c6fe-8778-43f9-a9d5-f071e97ac726/?kongregate_host=www.kongregate.com
SWF URL: https://game70421.konggames.com/gamez/0007/0421/live/beastgame_kong.swf?kongregate_game_version=1265086391

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-05
Channel: nightly
Built: 2023-02-05T00:19:41.427Z
Commit: 5e2f1a66eb878f937aa39f5da48dafb2c8d15340
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 25
numFrames: 7
swfVersion: 9
backgroundColor: #666666
isActionScript3: false
uncompressedLength: 7891171

**Comment by n0samu** [comment] 2023-02-06 08:46
Duplicate of #3756

**Closed by n0samu** 2023-02-06 08:46 UTC
Labels: duplicate, error-report
