### ISSUE TITLE
Error on https://prestigegames777.weebly.com/electric-man-2.html

### ISSUE THREAD

**Issue by sansbo** [ruffle-rs/ruffle#5869] opened 2021-12-15 19:36 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://prestigegames777.weebly.com/files/theme/Ruffle/ruffle.js:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h12990387e0d952cc (https://prestigegames777.weebly.com/files/theme/Ruffle/b5a25076313d154af4fd.wasm:wasm-function[993]:0x2f1b4a)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (https://prestigegames777.weebly.com/files/theme/Ruffle/b5a25076313d154af4fd.wasm:wasm-function[1347]:0x3699f8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc62fbac30903ce1c (https://prestigegames777.weebly.com/files/theme/Ruffle/b5a25076313d154af4fd.wasm:wasm-function[4721]:0x5095e7)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (https://prestigegames777.weebly.com/files/theme/Ruffle/b5a25076313d154af4fd.wasm:wasm-function[3331]:0x4b4ef1)
    at rust_begin_unwind (https://prestigegames777.weebly.com/files/theme/Ruffle/b5a25076313d154af4fd.wasm:wasm-function[4782]:0x50bc32)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (https://prestigegames777.weebly.com/files/theme/Ruffle/b5a25076313d154af4fd.wasm:wasm-function[4992]:0x5165e8)
    at core::panicking::panic::hceae0c79b0247f98 (https://prestigegames777.weebly.com/files/theme/Ruffle/b5a25076313d154af4fd.wasm:wasm-function[4717]:0x508e18)
    at core::ops::function::FnOnce::call_once::h8846ee79cfd6aeef (https://prestigegames777.weebly.com/files/theme/Ruffle/b5a25076313d154af4fd.wasm:wasm-function[1041]:0x30e134)
    at ruffle_core::avm1::function::Executable::exec::ha004f97b55bdbf5c (https://prestigegames777.weebly.com/files/theme/Ruffle/b5a25076313d154af4fd.wasm:wasm-function[429]:0x16fbaf)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://prestigegames777.weebly.com/electric-man-2.html
SWF URL: https://prestigegames777.weebly.com/uploads/1/1/2/6/112633177/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14150.87.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.124 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-29
Channel: nightly
Built: 2021-11-29T00:14:10.409Z
Commit: 2117ad8a4ce36d0c6ebdd6644fdc1df1f0ee2c32
Is extension: false

**Comment by relrelb** [comment] 2021-12-15 21:11
Duplicate of #4932.

**Closed by relrelb** 2021-12-15 21:11 UTC
Labels: duplicate, error-report
