### ISSUE TITLE
Error on https://game81398.konggames.com/games/likwidgames/castaway/frame/c454dbb2-05fd-4a77-94cf-1d14ee8ddf5e/

### ISSUE THREAD

**Issue by freddyjsg** [ruffle-rs/ruffle#8209] opened 2022-10-05 17:27 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:1014:22
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:1014:22
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.818bd70895644cf52bfd.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h5de940ebe16b9c56 (wasm://wasm/017fd55a:wasm-function[1024]:0x2a8161)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017fd55a:wasm-function[1487]:0x32b642)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he4ac1563548cf67a (wasm://wasm/017fd55a:wasm-function[4930]:0x489130)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017fd55a:wasm-function[3627]:0x445ee2)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017fd55a:wasm-function[5085]:0x48c5e6)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/017fd55a:wasm-function[4226]:0x47008a)
    at ruffle_core::bitmap::bitmap_data::BitmapData::draw::h32c0e264f83df184 (wasm://wasm/017fd55a:wasm-function[746]:0x241713)
    at ruffle_core::avm1::globals::bitmap_data::draw::hce54c72840698a91 (wasm://wasm/017fd55a:wasm-function[626]:0x203241)
    at ruffle_core::avm1::function::Executable::exec::heb7f82cdc90a6e68 (wasm://wasm/017fd55a:wasm-function[366]:0x1014a8)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://game81398.konggames.com/games/likwidgames/castaway/frame/c454dbb2-05fd-4a77-94cf-1d14ee8ddf5e/?kongregate_host=www.kongregate.com
SWF URL: https://game81398.konggames.com/gamez/0008/1398/live/castawayKon.swf?kongregate_game_version=1292015336

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-05
Channel: nightly
Built: 2022-10-05T00:18:27.765Z
Commit: 414e926e6a61b5c5c02d244ab3f4cc8079d7d0ae
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 5
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 7988051

**Comment by n0samu** [comment] 2022-10-06 03:36
Duplicate of #8016

**Closed by n0samu** 2022-10-06 03:36 UTC
Labels: duplicate, error-report
