### ISSUE TITLE
Error on https://games.crazygames.com/en_US/electric-man/index.html

### ISSUE THREAD

**Issue by carsuki** [ruffle-rs/ruffle#5297] opened 2021-09-14 09:16 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
n/s.wbg.__wbg_new_df6e6ab7a65c4c4d@https://files.crazygames.com/gameframe/ruffle/2021-07-14/ruffle.js:1:7476
std::sync::once::Once::call_once::{{closure}}::h5df181b90ad904c1@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[1008]:0x27f05e
std::sync::once::Once::call_inner::h79faa41f4d270a0b@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[974]:0x274b00
core::ops::function::FnOnce::call_once{{vtable.shim}}::hbd170ba35c598204@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[3882]:0x421769
std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[2999]:0x3c00dc
rust_begin_unwind@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[4094]:0x427111
core::panicking::panic_fmt::h3ab5417155b7ba3b@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[4244]:0x42dee4
core::panicking::panic::h5bfdfaa3db9a4b4a@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[4036]:0x424814
core::ops::function::FnOnce::call_once::h862d0560e2b20be7@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[869]:0x252490
ruffle_core::avm1::function::Executable::exec::h590beaec26993867@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[364]:0xd6a73
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::h17838fb60cb966bb@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[696]:0x1f9799
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hb455d984462640a0@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[779]:0x21f344
ruffle_core::avm1::activation::Activation::do_action::h2d1b276c41c1e6b2@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[291]:0xd12e
ruffle_core::avm1::activation::Activation::run_actions::h86894d3fb046d578@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[2416]:0x395dc3
ruffle_core::avm1::Avm1::run_stack_frame_for_action::h638001858e3c416b@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[936]:0x26a381
ruffle_core::player::Player::run_actions::h24d908358b6292d5@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[439]:0x12d851
ruffle_web::Ruffle::tick::h632b78b3c2948d6c@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[505]:0x17399c
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hd3c16f216034d06e@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[4767]:0x438168
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha3f653acc5815179@https://files.crazygames.com/gameframe/ruffle/2021-07-14/48b82e3e152a1a91a62f.wasm:wasm-function[4377]:0x42fe22
I@https://files.crazygames.com/gameframe/ruffle/2021-07-14/ruffle.js:1:4138
a@https://files.crazygames.com/gameframe/ruffle/2021-07-14/ruffle.js:1:3248
r@https://gameframe.crazygames.com/crazygames-gameframe-v1.bundle.js:2:61459

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.crazygames.com/en_US/electric-man/index.html
SWF URL: https://files.crazygames.com/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-14
Channel: nightly
Built: 2021-07-14T00:12:43.820Z
Commit: f9be5c2230b190549150a1cf058cbb284f6e36d8

**Comment by relrelb** [comment] 2021-09-14 14:50
Duplicate of #4932.

**Closed by relrelb** 2021-09-14 14:50 UTC
