### ISSUE TITLE
Cubefield: Graphical Line Glitch

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#5957] opened 2021-12-31 23:10 UTC
### Describe the bug

All the boxes seem to be connected by lines to either each other or to the ship itself. Load up the game with Ruffle and it should be noticable right away. Tested with the latest stable Browser Extension and nightly release desktop version. https://www.newgrounds.com/portal/view/288800
![Cubefield line bug](https://user-images.githubusercontent.com/78768499/147840778-d5d9380d-49a5-4b0f-826d-54acfd4e45b5.png)

### Expected behavior

The lines linking the boxes and the ship should be invisible.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Microsoft Edge 96

**Comment by relrelb** [comment] 2022-01-01 13:12
The regression introduced in #5573.

**Comment by Herschel** [comment] 2022-01-02 06:25
This specific issue is fixed by #5975, but lines are still not properly occluded because currently Ruffle always draws all lines after fills.

**Closed by Herschel** 2022-01-02 06:25 UTC
Labels: bug, rendering, regression
