### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by peepoostpin** [ruffle-rs/ruffle#11483] opened 2023-06-11 14:56 UTC
# Error Info
Error name: Error
Error message: Ruffle is panicking!
Error stack:
```
Error: Ruffle is panicking!
    at Je.load (https://ruffle.rs/demo/index.js:2:245703)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-11
Channel: nightly
Built: 2023-06-11T00:20:56.379Z
Commit: dced6445eebbab1775578fdf0a9331012120f359
Is extension: false

# Metadata

**Comment by n0samu** [comment] 2023-06-11 22:12
Hi, can you tell us what you were doing that led up to this error?

**Comment by Dinnerbone** [comment] 2024-07-12 22:05
Duplicate of #11042

**Closed by Dinnerbone** 2024-07-12 22:05 UTC
Labels: duplicate, error-report
