### ISSUE TITLE
Error on http://www.gamethoitrang.com/game/20751/thoi-trang-nu-kieu-1917.html

### ISSUE THREAD

**Issue by Hienkim23** [ruffle-rs/ruffle#7827] opened 2022-09-01 13:05 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:24:9

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.gamethoitrang.com/game/20751/thoi-trang-nu-kieu-1917.html
SWF URL: http://www.gamethoitrang.com/giaitri/game3/young-girl-collection.swf

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-30
Channel: nightly
Built: 2022-08-30T00:18:51.591Z
Commit: 36450619109b6ed510991b311f4888c0784eba8e
Is extension: false

# Metadata
width: 1000
height: 700
frameRate: 12
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 1296664

**Comment by n0samu** [comment] 2022-09-01 15:20
Duplicate of #6608. Updating your device to the latest iOS version should fix the issue!

**Closed by n0samu** 2022-09-01 15:20 UTC
Labels: duplicate, error-report
