### ISSUE TITLE
Error on https://play.cprewritten.net/

### ISSUE THREAD

**Issue by nicollelumertz** [ruffle-rs/ruffle#4420] opened 2021-05-24 20:34 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (https://play.cprewritten.net/assets/lib/ruffle/a650d1c2efa031acee25.wasm:wasm-function[1074]:0x27c453)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (https://play.cprewritten.net/assets/lib/ruffle/a650d1c2efa031acee25.wasm:wasm-function[945]:0x250063)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (https://play.cprewritten.net/assets/lib/ruffle/a650d1c2efa031acee25.wasm:wasm-function[3794]:0x41236b)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (https://play.cprewritten.net/assets/lib/ruffle/a650d1c2efa031acee25.wasm:wasm-function[2941]:0x39dfd6)
    at rust_begin_unwind (https://play.cprewritten.net/assets/lib/ruffle/a650d1c2efa031acee25.wasm:wasm-function[3999]:0x417bcf)
    at core::panicking::panic_fmt::hd44f353696296fec (https://play.cprewritten.net/assets/lib/ruffle/a650d1c2efa031acee25.wasm:wasm-function[4145]:0x41e5da)
    at core::option::expect_none_failed::hf7dab2706f1a5551 (https://play.cprewritten.net/assets/lib/ruffle/a650d1c2efa031acee25.wasm:wasm-function[3381]:0x401e46)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf8715be3ccc24b16 (https://play.cprewritten.net/assets/lib/ruffle/a650d1c2efa031acee25.wasm:wasm-function[569]:0x182210)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h32dd319cd7bb0e82 (https://play.cprewritten.net/assets/lib/ruffle/a650d1c2efa031acee25.wasm:wasm-function[490]:0x14e0cb)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://play.cprewritten.net/
SWF URL: https://play.cprewritten.net/assets/flash/global/games/boot.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.66
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-14
Channel: nightly
Built: 2021-05-14T00:14:43.779Z
Commit: ae038ccbb1ad0816a87196f7a598596c7127da7a

**Comment by relrelb** [comment] 2021-08-13 14:14
Duplicate of #4998.

**Closed by relrelb** 2021-08-13 14:14 UTC
