### ISSUE TITLE
Error on file:///C:/Users/mthorns1/Desktop/ruffle%20test/startDoom.htm

### ISSUE THREAD

**Issue by TheThornZ** [ruffle-rs/ruffle#2659] opened 2021-01-19 20:26 UTC
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at e (file:///C:/Users/mthorns1/Desktop/ruffle%20test/ruffle.js:1:31896)
    at i (file:///C:/Users/mthorns1/Desktop/ruffle%20test/ruffle.js:1:33923)
    at i.next (<anonymous>)
    at a (file:///C:/Users/mthorns1/Desktop/ruffle%20test/ruffle.js:1:34005)
```

# Player Info
Allows script access: true

# Page Info
Page URL: file:///C:/Users/mthorns1/Desktop/ruffle%20test/startDoom.htm

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by evilpie** [comment] 2021-01-19 21:10
Duplicate of #2619 ?

**Comment by Herschel** [comment] 2021-01-20 02:23
Ruffle will not run from a local filesystem due to security restrictions in browsers. You can [run a local test server](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server) or upload Ruffle to a server. Better error messages for this are coming in #2622. Hope this helps.

**Closed by Herschel** 2021-01-20 02:23 UTC
