### ISSUE TITLE
Error on https://watchdocumentaries.com/papas-pizzeria-game/

### ISSUE THREAD

**Issue by ASHSORIKIMA** [ruffle-rs/ruffle#7450] opened 2022-07-20 01:14 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 3 but the index is 3', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-1.0.0/src/fill.rs:1547:27
Error stack:
```
@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.20/core.ruffle.6a8055f3657eb7f0a640.js:1:6074
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h96c2b4473ff6d536]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h1c414562e2619117]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h14edbfd8adf99b9a]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h1c368a27f9b0afe1]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hcdb13a4b2416cf82]@[wasm code]
<?>.wasm-function[core::panicking::panic_bounds_check::he79659661cacde3e]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::process_events::hf251f5e99b1bb5f8]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_impl::h32fa761dd0b10154]@[wasm code]
<?>.wasm-function[ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h38b7a1aa623d20f4]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h4b191ae816bffbd7]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h665ec94c3be0bed1]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::hd5ec0228594cee8f]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::he9f95ae27d16e678]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h82b5c65339a45f8d]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h984fde7dc2510f7e]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::hd7ec8b4f637e00c8]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0b040046572af87d]@[wasm code]
wasm-stub@[native code]
k@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.20/core.ruffle.6a8055f3657eb7f0a640.js:1:3138
c@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.7.20/core.ruffle.6a8055f3657eb7f0a640.js:1:2438
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /wp-content/uploads/games/papas-pizzeria/papas-pizzeria.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://watchdocumentaries.com/papas-pizzeria-game/
SWF URL: https://watchdocumentaries.com/wp-content/uploads/games/papas-pizzeria/papas-pizzeria.swf

# Browser Info
User Agent: Mozilla/5.0 (iPad; CPU OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/103.0.5060.63 Mobile/15E148 Safari/604.1
Platform: iPad
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-20
Channel: nightly
Built: 2022-07-20T00:17:10.336Z
Commit: 6f142c21faca439b6cb1ac5c2db183974adad0b8
Is extension: false

**Comment by n0samu** [comment] 2022-07-20 01:16
Duplicate of #7443

**Closed by n0samu** 2022-07-20 01:16 UTC
Labels: duplicate, error-report
