### ISSUE TITLE
Error on https://www.experimonkey.com/games/learn-to-fly-2

### ISSUE THREAD

**Issue by Cadengummo** [ruffle-rs/ruffle#13303] opened 2023-09-24 20:29 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 0..12 would end up overrunning the bounds of the Source texture of X size 9

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 0..12 would end up overrunning the bounds of the Source texture of X size 9

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://www.experimonkey.com/js/libraries/ruffle/core.ruffle.c59ceecf1ce9e7258f90.js:1:51844)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9f0061f44a7e6f49 (wasm://wasm/030b6e02:wasm-function[9345]:0x92340c)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/030b6e02:wasm-function[6103]:0x824d02)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/030b6e02:wasm-function[9181]:0x91ea23)
    at core::ops::function::Fn::call::hd3e79eb2934301e2 (wasm://wasm/030b6e02:wasm-function[6304]:0x83098b)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::hacfc94e2d85ecf44 (wasm://wasm/030b6e02:wasm-function[4937]:0x78f409)
    at wgpu::backend::direct::Context::handle_error::hd66614ffdd0ccef7 (wasm://wasm/030b6e02:wasm-function[2542]:0x5e40ed)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h0964e450a3e25b6d (wasm://wasm/030b6e02:wasm-function[6680]:0x85c2dc)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h9c36955c579e1cae (wasm://wasm/030b6e02:wasm-function[5727]:0x80616a)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h6f3490135639b127 (wasm://wasm/030b6e02:wasm-function[1576]:0x47e86d)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.experimonkey.com/games/learn-to-fly-2
SWF URL: https://www.experimonkey.com/games/swf-games/learn-to-fly-2/learn-to-fly-2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-19
Channel: nightly
Built: 2023-09-19T00:26:29.263Z
Commit: 65d1ba48037290619bc8f1bef0eb931342e2c10c
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 33
numFrames: 46
swfVersion: 10
backgroundColor: #2379B1
isActionScript3: false
uncompressedLength: 7048724

**Comment by torokati44** [comment] 2023-11-10 23:33
Almost exact duplicate of #13298.

**Closed by torokati44** 2023-11-10 23:33 UTC
Labels: render-wgpu, error-report
