### ISSUE TITLE
Error on https://cheese12354326.github.io/chilibowlflash/eman2.html

### ISSUE THREAD

**Issue by acb124** [ruffle-rs/ruffle#6694] opened 2022-04-12 18:43 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://cheese12354326.github.io/chilibowlflash/ruffle.js:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::hdc00d7da63128799 (https://cheese12354326.github.io/chilibowlflash/74fac0424097d9527b7e.wasm:wasm-function[916]:0x24411f)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (https://cheese12354326.github.io/chilibowlflash/74fac0424097d9527b7e.wasm:wasm-function[1174]:0x2a1c7c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h34a21969c4579926 (https://cheese12354326.github.io/chilibowlflash/74fac0424097d9527b7e.wasm:wasm-function[4036]:0x42d23c)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (https://cheese12354326.github.io/chilibowlflash/74fac0424097d9527b7e.wasm:wasm-function[2909]:0x3c2681)
    at rust_begin_unwind (https://cheese12354326.github.io/chilibowlflash/74fac0424097d9527b7e.wasm:wasm-function[4251]:0x432e74)
    at core::panicking::panic_fmt::h1fea623755fffed7 (https://cheese12354326.github.io/chilibowlflash/74fac0424097d9527b7e.wasm:wasm-function[4407]:0x439c25)
    at core::panicking::panic::h38cac710b5048ca0 (https://cheese12354326.github.io/chilibowlflash/74fac0424097d9527b7e.wasm:wasm-function[4185]:0x43019a)
    at core::ops::function::FnOnce::call_once::ha40e6113ced28e4c (https://cheese12354326.github.io/chilibowlflash/74fac0424097d9527b7e.wasm:wasm-function[891]:0x23872e)
    at ruffle_core::avm1::function::Executable::exec::h6321fa6c8b3e93cb (https://cheese12354326.github.io/chilibowlflash/74fac0424097d9527b7e.wasm:wasm-function[383]:0xe4e62)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://cheese12354326.github.io/chilibowlflash/eman2.html
SWF URL: https://cheese12354326.github.io/chilibowlflash/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-24
Channel: nightly
Built: 2021-08-24T00:12:47.214Z
Commit: fd7d32bc14454372774cfde1428087ccba17a483
Is extension: false

**Comment by relrelb** [comment] 2022-04-13 13:21
Duplicate of #4932.

**Closed by relrelb** 2022-04-13 13:21 UTC
Labels: error-report
