### ISSUE TITLE
Error on https://web.archive.org/web/20090225212355/http://park.hongkongdisneyland.com/hkdl/zh_HK/home/home

### ISSUE THREAD

**Issue by Brybryanc** [ruffle-rs/ruffle#13345] opened 2023-09-28 12:15 UTC
# Error Info
Error name: TypeError
Error message: __webpack_modules__[moduleId] is not a function
Error stack:
```
TypeError: __webpack_modules__[moduleId] is not a function
    at Function.__webpack_require__ (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?id=87908450412:59:41)
    at https://web.archive.org/web/20090225212355js_/http://ahongkongdisneyland.disney.go.com/js/hkdl_v0200/global.js:155:22
    at async fetchRuffle (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?id=87908450412:891:39)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://web.archive.org/web/20090225212355/http://park.hongkongdisneyland.com/hkdl/zh_HK/home/home?name=HomePage

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-26
Channel: nightly
Built: 2023-09-26T00:20:19.266Z
Commit: 7e4e4d4c5b1f55614b98b33b7cc6f70567c52bab
Is extension: true

# Metadata

**Comment by Lord-McSweeney** [comment] 2023-10-19 15:14
Duplicate of #13187

**Closed by Lord-McSweeney** 2023-10-19 15:14 UTC
Labels: error-report
