### ISSUE TITLE
Error on https://www.play-games.com/embed/24956.html

### ISSUE THREAD

**Issue by parthg-livebird** [ruffle-rs/ruffle#7713] opened 2022-08-20 12:15 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
@https://www.play-games.com/js/frontend/vendor/ruffle/core.ruffle.d56713a8aacb20386203.js:1:5549
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hc005efe66820567d]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h1c414562e2619117]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h333199a3a4749bb8]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h1c368a27f9b0afe1]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hcdb13a4b2416cf82]@[wasm code]
<?>.wasm-function[core::panicking::panic::ha8ced62e366a0d64]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once::he6b960eb0e7a3615]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::hd1a31b7b31ac1395]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h812a9e6cbb0cb2b4]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::he2ac4b985b391192]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::Avm1::run_stack_frame_for_action::hfd25ac45f28f6155]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::h1f9a649057bbf0c1]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::hc89aa4c42a47b52b]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::ha86efd1a5c4d1204]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6fb7660881a72d58]@[wasm code]
wasm-stub@[native code]
F@https://www.play-games.com/js/frontend/vendor/ruffle/core.ruffle.d56713a8aacb20386203.js:1:3029
c@https://www.play-games.com/js/frontend/vendor/ruffle/core.ruffle.d56713a8aacb20386203.js:1:2481
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.play-games.com/embed/24956.html
SWF URL: https://www.play-games.com/files/swf/electric-man-1611670590.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-02
Channel: nightly
Built: 2022-08-02T00:19:12.167Z
Commit: 2ba82c92bc2f295d2a0269fa39feb574fc1fb183
Is extension: false

**Comment by n0samu** [comment] 2022-08-20 13:05
Duplicate of #4932

**Closed by n0samu** 2022-08-20 13:05 UTC
Labels: duplicate, error-report
