### ISSUE TITLE
Homestar Runner - Strongbad Emails Randomization

### ISSUE THREAD

**Issue by sombraguerrero** [ruffle-rs/ruffle#1434] opened 2020-10-30 07:15 UTC
### 10/29/20 Nightly build of the Chrome extension

This is in no way a critical bug, but I thought it might be an interesting functionality case.
At [http://homestarrunner.com/sbemail.html](url) there is the "Go Rando" link in the upper-right. This randomization typically parses through all the links available in the viewport and selects one at random with different animations.

Ruffle clearly doesn't support this because no matter how many times I reload or completely clear caches, it's the same sequence, with the same outcome every single time. (sbemail13.html). I'm assuming this is probably a hardcoded fallback value somewhere for when the randomization logic fails, so I'm wondering if there's a way to figure out what it is about this randomizer that Ruffle cannot do.
![sbemails](https://user-images.githubusercontent.com/24618934/97671205-c97eba00-1a55-11eb-8e47-f52742e8a056.png)

**Comment by Herschel** [comment] 2020-10-30 08:21
Dupe of #1182

**Closed by Herschel** 2020-10-30 08:21 UTC
