### ISSUE TITLE
Error on https://armorgames.com/play/14170/arkandian-explorer

### ISSUE THREAD

**Issue by atoime** [ruffle-rs/ruffle#4045] opened 2021-04-17 22:05 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 0 but the index is 4294967295', core/src/avm1/object/script_object.rs:807:17
Error stack:
```
e/a.wbg.__wbg_new_df6e6ab7a65c4c4d@https://agi.armorgames.com/ruffle/ruffle.js:1:6392
std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[1276]:0x25acf1
std::sync::once::Once::call_inner::h02eac160d339afc2@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[1533]:0x289f4e
core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4371]:0x36167b
std::panicking::rust_panic_with_hook::h123718ba3bf480af@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[3312]:0x338d3c
std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[3929]:0x356034
std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4705]:0x3669fe
rust_begin_unwind@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4583]:0x3651a1
core::panicking::panic_fmt::h285dc015a87be5a4@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4707]:0x366a62
core::panicking::panic_bounds_check::heedacfd10d9ec31d@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4114]:0x35b779
<ruffle_core::avm1::object::script_object::ScriptObject as ruffle_core::avm1::object::TObject>::set_array_element::h40ec764a84e28bf0@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[1462]:0x27e26a
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::set_array_element::h0ddfa8bed365f0cf@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[503]:0x14feda
ruffle_core::avm1::globals::shared_object::recursive_deserialize::hce35df333ea07b21@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[462]:0x134877
ruffle_core::avm1::globals::shared_object::recursive_deserialize::hce35df333ea07b21@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[462]:0x1347f6
ruffle_core::avm1::globals::shared_object::recursive_deserialize::hce35df333ea07b21@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[462]:0x13426b
ruffle_core::avm1::globals::shared_object::recursive_deserialize::hce35df333ea07b21@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[462]:0x13426b
ruffle_core::avm1::globals::shared_object::recursive_deserialize::hce35df333ea07b21@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[462]:0x13426b
ruffle_core::avm1::globals::shared_object::get_local::hd01e3fdb893db65d@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[349]:0xca50b
ruffle_core::avm1::function::Executable::exec::h8050e2dbdc0fb29c@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[358]:0xd633a
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::h8844d646b250176b@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[806]:0x1dc372
ruffle_core::avm1::object::TObject::call_method::hedd4cdf8247e7406@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[1513]:0x28690d
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7cf25154992b987e@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[955]:0x20c553
ruffle_core::avm1::activation::Activation::do_action::h61d393ca182436e1@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[288]:0x1cb57
ruffle_core::avm1::activation::Activation::run_actions::hc2d2b84ed3049569@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[2787]:0x316fc2
ruffle_core::avm1::Avm1::run_stack_frame_for_action::h4c7fe67cac537889@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[1129]:0x23a5a7
ruffle_core::player::Player::run_actions::he7fdab0787716ca8@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[438]:0x1215c8
ruffle_core::player::Player::run_frame::h17b828df9dd60151@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[732]:0x1c1228
ruffle_core::player::Player::tick::h6bf3bc364f7ba31b@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[3339]:0x33a4ed
std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[763]:0x1ccd5c
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h5147900df79a7f50@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4615]:0x36589e
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h078284a751df961e@https://agi.armorgames.com/ruffle/05be98acabee5bdacb848b714e072d80.wasm:wasm-function[4858]:0x36833f
O@https://agi.armorgames.com/ruffle/ruffle.js:1:4040
a@https://agi.armorgames.com/ruffle/ruffle.js:1:2840

```

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/14170/arkandian-explorer
SWF URL: https://cache.armorgames.com/files/games/arkandian-explorer-14170.swf?v=1373587528

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-01
Channel: nightly
Built: 2021-02-01T00:36:59.488Z
Commit: d1fb36fbe2b31b9392d995ac67315aa02aee3fbc

**Comment by Poopooracoocoo** [comment] 2021-04-18 17:27
Duplicate of #3614

**Closed by Poopooracoocoo** 2021-04-18 17:27 UTC
