### ISSUE TITLE
Error on https://games.crazygames.com/en_US/chibi-knight/index.html

### ISSUE THREAD

**Issue by AyushBajaj1** [ruffle-rs/ruffle#4267] opened 2021-05-07 22:47 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:982:18

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.crazygames.com/en_US/chibi-knight/index.html
SWF URL: https://files.crazygames.com/chibiknight.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-29
Channel: nightly
Built: 2021-04-29T00:18:02.433Z
Commit: 940cb8d2f7ca8992784d590b6337851f4cc3fe1e

**Comment by relrelb** [comment] 2021-05-08 06:00
Duplicate of #4048.

**Closed by relrelb** 2021-05-08 06:00 UTC
