### ISSUE TITLE
Error on https://www.spiele-umsonst.de/feudalism-2-t1552.html

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2885] opened 2021-01-26 16:39 UTC
Intro is bugged. IF you skip it the unwrap error won't come. But I saw more of those "unwrap" errors here on this github so maybe it needs to be fixed sooner than later :P

# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3108:14
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3108:14
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.spiele-umsonst.de/ruffle/ruffle.js?v24:1:6349)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://www.spiele-umsonst.de/ruffle/d8a009871c3fb1037844a7e998176a68.wasm:wasm-function[1265]:0x24d537)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://www.spiele-umsonst.de/ruffle/d8a009871c3fb1037844a7e998176a68.wasm:wasm-function[1526]:0x27d3b5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://www.spiele-umsonst.de/ruffle/d8a009871c3fb1037844a7e998176a68.wasm:wasm-function[4306]:0x35293f)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://www.spiele-umsonst.de/ruffle/d8a009871c3fb1037844a7e998176a68.wasm:wasm-function[3297]:0x32b606)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://www.spiele-umsonst.de/ruffle/d8a009871c3fb1037844a7e998176a68.wasm:wasm-function[3915]:0x348829)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://www.spiele-umsonst.de/ruffle/d8a009871c3fb1037844a7e998176a68.wasm:wasm-function[4652]:0x358079)
    at rust_begin_unwind (https://www.spiele-umsonst.de/ruffle/d8a009871c3fb1037844a7e998176a68.wasm:wasm-function[4523]:0x356657)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://www.spiele-umsonst.de/ruffle/d8a009871c3fb1037844a7e998176a68.wasm:wasm-function[4654]:0x3580dd)
    at core::panicking::panic::h0abe4e7a620ae568 (https://www.spiele-umsonst.de/ruffle/d8a009871c3fb1037844a7e998176a68.wasm:wasm-function[4457]:0x35551c)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.spiele-umsonst.de/feudalism-2-t1552.html
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/feudalism2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-24
Channel: nightly
Built: 2021-01-24T01:05:42.228Z
Commit: 86b4c20809d8778d498474a26601aeda4cec87c4

**Comment by relrelb** [comment] 2021-04-24 19:21
Duplicate of #2737.

**Closed by relrelb** 2021-04-24 19:21 UTC
