### ISSUE TITLE
Error on https://www.spiele-umsonst.de/d-space-t3629.html

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2801] opened 2021-01-23 19:14 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.spiele-umsonst.de/ruffle/ruffle.js?v21:1:6518)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://www.spiele-umsonst.de/ruffle/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[1282]:0x25c34b)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://www.spiele-umsonst.de/ruffle/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[1549]:0x28d0c2)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://www.spiele-umsonst.de/ruffle/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[4308]:0x3605d1)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://www.spiele-umsonst.de/ruffle/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[3302]:0x33958f)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://www.spiele-umsonst.de/ruffle/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[3915]:0x3564be)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://www.spiele-umsonst.de/ruffle/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[4654]:0x365d09)
    at rust_begin_unwind (https://www.spiele-umsonst.de/ruffle/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[4526]:0x364329)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://www.spiele-umsonst.de/ruffle/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[4656]:0x365d6d)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (https://www.spiele-umsonst.de/ruffle/0f45cf0b731a577a20886dbd5bf07618.wasm:wasm-function[3993]:0x358b9c)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.spiele-umsonst.de/d-space-t3629.html
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/dspace.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-21
Channel: nightly
Built: 2021-01-21T01:06:17.627Z
Commit: dc2b4fcc42e447097d6432479a122b34fcbc3999

**Comment by n0samu** [comment] 2022-10-05 03:45
Duplicate of #2536

**Closed by n0samu** 2022-10-05 03:45 UTC
Labels: duplicate, error-report

**Comment by n0samu** [comment] 2022-10-06 21:34
Sorry, I know GitHub's terminology is confusing. That's just the designation for issues closed as duplicate. (It's also used when closing invalid issues.)
