### ISSUE TITLE
Error on https://games.crazygames.com/en_US/electric-man/index.html

### ISSUE THREAD

**Issue by lEEjIN12** [ruffle-rs/ruffle#8560] opened 2022-11-17 11:25 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://files.crazygames.com/gameframe/ruffle/2022-10-08/core.ruffle.c00b1522f61b16f6f730.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/01800756:wasm-function[1035]:0x2a7210)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01800756:wasm-function[1498]:0x32a258)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/01800756:wasm-function[4956]:0x48841a)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01800756:wasm-function[3645]:0x444624)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01800756:wasm-function[5111]:0x48b8aa)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/01800756:wasm-function[5012]:0x4893d6)
    at core::ops::function::FnOnce::call_once::h2b64b87dbbaf5054 (wasm://wasm/01800756:wasm-function[1129]:0x2c6e48)
    at ruffle_core::avm1::function::Executable::exec::h7dbb30579b1dd750 (wasm://wasm/01800756:wasm-function[369]:0x100642)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h55e375c84faa5088 (wasm://wasm/01800756:wasm-function[443]:0x16274e)
    at ruffle_core::avm1::activation::Activation::run_actions::h263d8988998b3764 (wasm://wasm/01800756:wasm-function[303]:0x1bbdf)
    at ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h03e0123c0ba9f954 (wasm://wasm/01800756:wasm-function[924]:0x28599f)
    at ruffle_core::player::Player::run_actions::h3d8339652ee520af (wasm://wasm/01800756:wasm-function[512]:0x1a58a6)
    at ruffle_web::Ruffle::tick::hcce3b9c42455dc22 (wasm://wasm/01800756:wasm-function[673]:0x2180d8)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hfb791d31cd1d45d9 (wasm://wasm/01800756:wasm-function[6001]:0x4a5445)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h476982f031f67f47 (wasm://wasm/01800756:wasm-function[5472]:0x495d39)
    at A (https://files.crazygames.com/gameframe/ruffle/2022-10-08/core.ruffle.c00b1522f61b16f6f730.js:1:2554)
    at c (https://files.crazygames.com/gameframe/ruffle/2022-10-08/core.ruffle.c00b1522f61b16f6f730.js:1:2231)
    at r (https://gameframe.crazygames.com/static/js/1668526277024/2082.0c38c0e1.js:1:33787)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://games.crazygames.com/en_US/electric-man/index.html
SWF URL: https://files.crazygames.com/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.42
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-08
Channel: nightly
Built: 2022-10-08T00:21:16.770Z
Commit: 5c9471436371f24f1d95011d21b5cddb7fc4ee7f
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3641749

**Comment by n0samu** [comment] 2022-11-17 21:23
Duplicate of #4932

**Closed by n0samu** 2022-11-17 21:23 UTC
Labels: duplicate, error-report
