### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by BurgerBoi347** [ruffle-rs/ruffle#6421] opened 2022-03-08 02:22 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.cfafeead7fa4cdb619a5.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::h04c6018a30aae0b2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a99dca5f55f4f54048b7.wasm:wasm-function[1019]:0x2c1212)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a99dca5f55f4f54048b7.wasm:wasm-function[1458]:0x32fa13)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h629785d4908f37da (https://uploads.ungrounded.net/ruffle_wrapper/lib/a99dca5f55f4f54048b7.wasm:wasm-function[4925]:0x48459f)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a99dca5f55f4f54048b7.wasm:wasm-function[3240]:0x426969)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a99dca5f55f4f54048b7.wasm:wasm-function[5213]:0x4906ea)
    at core::panicking::panic::h5d6906e2c1099660 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a99dca5f55f4f54048b7.wasm:wasm-function[4922]:0x4840c6)
    at core::ops::function::FnOnce::call_once::hccd13e3d375a8a6e (https://uploads.ungrounded.net/ruffle_wrapper/lib/a99dca5f55f4f54048b7.wasm:wasm-function[1106]:0x2d7af5)
    at ruffle_core::avm1::function::Executable::exec::h79701af978203eb9 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a99dca5f55f4f54048b7.wasm:wasm-function[385]:0x10dba6)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hcdf54ba60d7772d4 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a99dca5f55f4f54048b7.wasm:wasm-function[433]:0x158f58)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1646237425%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226226b9a7e3c7b%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-02
Channel: nightly
Built: 2022-03-02T00:16:18.285Z
Commit: cbbdb7baa94e0996fd8696976a2fa3e1151c16f9
Is extension: false

**Comment by relrelb** [comment] 2022-04-30 08:35
Duplicate of #3756.

**Closed by relrelb** 2022-04-30 08:35 UTC
Labels: error-report
