### ISSUE TITLE
Angry Birds Refresh - XML Parser Failure: element is malformed

### ISSUE THREAD

**Issue by Fancy2209** [ruffle-rs/ruffle#16862] opened 2024-06-24 13:48 UTC
### Describe the bug

Angry Birds Refresh fails with 
```
Got "TypeError: Error #1090: XML parser failure: element is malformed.
	at XML/XML::init()
	at XML()
	at com.rovio.factory::XMLFactory$/fromOctetStreamClass()
	at AngryBirdsFacebook/getUIData()
	at AngryBirdsBase()
	at AngryBirdsFacebook()
	at AngryBirdsFacebookCanvas/func2()
	at AngryBirdsFacebookCanvas/init()
	at AngryBirdsFacebookCanvas()" when constructing AVM2 side of movie clip of type AngryBirdsFacebookCanvas
```

### Expected behavior

I'd see the Loading Screen and a Discord Login Popup would show up.

### Content Location

https://refresh.teamflashcord.com/

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Mozilla Firefox 127.0.0.1

**Comment by evilpie** [comment] 2024-06-30 17:58
The problem is this invalid piece of XML:
```xml
    <PopupView_Embed name="EmbedLevel" fromLibrary="True"
      overlay="True" width="1024" height="768" alignH="CENTER" alignV="CENTER">
    </PopupView_Embed scaleH="UP" scaleV="UP" aspectRatioFixed="TRUE" >
```
Note the unexpected attributes in the closing tag.

**Comment by ultra0000** [comment] 2024-06-30 18:33
An update will be pushed soon to fix this:
![image](https://github.com/ruffle-rs/ruffle/assets/43279290/d76e488e-d8bf-4a6b-8ebd-e579b8e2668f)
Should this issue be kept open? Also, there's another issue happening during loading where the game doesn't get its login data through ExternalInterface, should I open an issue for that too?

**Comment by evilpie** [comment] 2024-06-30 18:58
We can keep this open until we accept this bad syntax in Ruffle. Please open a new issue for the new ExternalInterface issue.

**Comment by Fancy2209** [comment] 2024-06-30 19:51
> We can keep this open until we accept this bad syntax in Ruffle. Please open a new issue for the new ExternalInterface issue.

#16942 was opened for this issue

**Closed** 2024-07-08 23:01 UTC
Labels: bug, avm2, xml
