### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Lavender1059** [ruffle-rs/ruffle#16652] opened 2024-06-09 12:22 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.20.0/src/gles/device.rs:775:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.20.0/src/gles/device.rs:775:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at Q.n.wbg.__wbg_new_28c511d9baebfa89 (https://ruffle.rs/demo/assets/ruffle_web-wasm_extensions-BMqvpKeD.js:2:76720)
    at ruffle_web.wasm.js_sys::Error::new::ha59a397dfb01052a (wasm://wasm/ruffle_web.wasm-0339c4d6:wasm-function[12849]:0x9fb6a4)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hfdf01bfa88fb72ec (wasm://wasm/ruffle_web.wasm-0339c4d6:wasm-function[9828]:0x98f495)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-0339c4d6:wasm-function[6559]:0x88a0b1)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-0339c4d6:wasm-function[10244]:0x9ba0a8)
    at ruffle_web.wasm.core::result::unwrap_failed::h8c7a47192e7f0267 (wasm://wasm/ruffle_web.wasm-0339c4d6:wasm-function[8344]:0x91754f)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_texture::h4ec0a4dcea68b18b (wasm://wasm/ruffle_web.wasm-0339c4d6:wasm-function[7565]:0x8d3271)
    at ruffle_web.wasm.wgpu::Device::create_texture::h175150188391f17b (wasm://wasm/ruffle_web.wasm-0339c4d6:wasm-function[5995]:0x859e27)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h45e784b3d40bf0d7 (wasm://wasm/ruffle_web.wasm-0339c4d6:wasm-function[5717]:0x842577)
    at ruffle_web.wasm.ruffle_core::display_object::render_base::h0aa5d25921ff1f0f (wasm://wasm/ruffle_web.wasm-0339c4d6:wasm-function[806]:0x1617c6)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mali-G76 MC4"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 4096, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-06-09
Channel: nightly
Built: 2024-06-09T00:07:03.378Z
Commit: 1d1eb6c966a17442c9e6a0730d0ba46f5d079879
Is extension: false

# Metadata
width: 750
height: 480
frameRate: 60
numFrames: 301
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2668419

**Comment by Dinnerbone** [comment] 2024-07-12 22:01
Duplicate of #16519

**Closed by Dinnerbone** 2024-07-12 22:01 UTC
Labels: duplicate, error-report
