### ISSUE TITLE
https://web.archive.org/web/20080430024705/http://park.hongkongdisneyland.com/hkdl/en_US/home/home

### ISSUE THREAD

**Issue by Brybryanc** [ruffle-rs/ruffle#13904] opened 2023-11-08 12:32 UTC
### Describe the bug

it is to access to the website

### Expected behavior

appears with visual and sound

### Content Location

http://park.hongkongdisneyland.com/hkdl/en_US/home/home?name=HomePage

### Affected platform

Browser's extension

### Operating system

Apple

### Browser

Google Chrome

**Comment by danielhjacobs** [comment] 2023-11-10 16:43
Duplicate of #13596. This is an issue with the JavaScript on the website interfering with the JavaScript Ruffle uses to run. It is not feasible to fix.

**Closed by danielhjacobs** 2023-11-10 16:43 UTC
Labels: bug
