### ISSUE TITLE
web: Detective Grimoire - Officer stuck in a loop

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2748] opened 2021-01-22 10:44 UTC
Hello,

dunno what black hole causes the officer to stay in that loop 📦 

https://www.newgrounds.com/portal/view/386799?emulate=flash

#happens right after the beginning if you start playing the game

**Comment by Poopooracoocoo** [comment] 2021-01-23 04:06
And you can't click on the next button either!

https://user-images.githubusercontent.com/51363864/105568325-8d28d480-5d8c-11eb-846d-c808d3345e3c.mp4

**Comment by ousia** [comment] 2021-01-23 22:15
Duplicate of #2583.

**Closed** 2021-07-03 09:02 UTC
Labels: duplicate
