### ISSUE TITLE
Error on http://twinbeard.com/frog-fractions/

### ISSUE THREAD

**Issue by urodov-orb** [ruffle-rs/ruffle#5914] opened 2021-12-23 03:54 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object.rs:1219:34

# Player Info
Allows script access: true

# Page Info
Page URL: http://twinbeard.com/frog-fractions/
SWF URL: http://twinbeard.com/binary/FrogFractions.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-09-14
Channel: nightly
Built: 2021-09-14T00:12:54.264Z
Commit: a882f85d14bd7d3d8e9d372dd3549e6e9fddc598
Is extension: true

**Comment by Poopooracoocoo** [comment] 2021-12-23 04:43
Duplicate of #5607

**Closed by Poopooracoocoo** 2021-12-23 04:43 UTC
Labels: duplicate, error-report

**Comment by Poopooracoocoo** [comment] 2021-12-23 04:46
@urodov-orb For best compatibility, you'll want to update Firefox to 95.0.2 and use Ruffle from AMO for automatic updates: https://addons.mozilla.org/en-US/firefox/addon/ruffle_rs/

**Comment by urodov-orb** [comment] 2021-12-23 04:50
thanks
