### ISSUE TITLE
Error on https://www.comdotgame.com/play/kasumi-rebirth

### ISSUE THREAD

**Issue by godbro2** [ruffle-rs/ruffle#10312] opened 2023-03-22 09:32 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:640:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:640:18
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://echo.comdotgame.com/ruffle/core.ruffle.31c166ab9c2b119e4092.js:1:46508)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h321a9078ff9936f2 (wasm://wasm/02962ab2:wasm-function[7834]:0x7cc186)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02962ab2:wasm-function[5302]:0x7125e6)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02962ab2:wasm-function[7726]:0x7c7730)
    at core::panicking::panic::ha3ebcac1438d9280 (wasm://wasm/02962ab2:wasm-function[7142]:0x79373f)
    at ruffle_core::display_object::container::ChildContainer::replace_at_depth::h2de1d6a0c6867e00 (wasm://wasm/02962ab2:wasm-function[1539]:0x41e990)
    at ruffle_core::display_object::container::TDisplayObjectContainer::replace_at_depth::h21501d2f3172dfbe (wasm://wasm/02962ab2:wasm-function[4772]:0x6e70df)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h195a33510c0b747d (wasm://wasm/02962ab2:wasm-function[732]:0x2765bc)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::{{closure}}::h7bf1329a46718fc5 (wasm://wasm/02962ab2:wasm-function[895]:0x2fa1d7)
    at ruffle_core::display_object::movie_clip::MovieClip::run_goto::hff866e088751f047 (wasm://wasm/02962ab2:wasm-function[659]:0x2200cc)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f7313836a835b6c3191ed00ca9751a1c.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Param base: https://echo.comdotgame.com/4x90xhl3k0/games/files/kasumi-rebirth/3.30/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/kasumi-rebirth
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f7313836a835b6c3191ed00ca9751a1c.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 13; SAMSUNG SM-G991N) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/20.0 Chrome/106.0.5249.126 Mobile Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-12
Channel: nightly
Built: 2023-03-12T00:19:04.440Z
Commit: 1deebc87e869387c962f97b665d26785d0a2b52f
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3848978

**Comment by n0samu** [comment] 2023-03-25 01:52
Duplicate of #10042

**Closed by n0samu** 2023-03-25 01:52 UTC
Labels: duplicate, nsfw, error-report
