### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm

### ISSUE THREAD

**Issue by CarFanatic23** [ruffle-rs/ruffle#5185] opened 2021-08-31 16:10 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/ruffle.js?uniqueMessageSuffix=3333290023:1:7476)
    at std::sync::once::Once::call_once::{{closure}}::h5df181b90ad904c1 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[1004]:0x27f5f7)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[968]:0x26aa7a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbd170ba35c598204 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[3879]:0x425bcc)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[3010]:0x3bfdb3)
    at rust_begin_unwind (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[4091]:0x42b574)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[4241]:0x432347)
    at core::panicking::panic::h5bfdfaa3db9a4b4a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[4033]:0x428c77)
    at core::ops::function::FnOnce::call_once::h862d0560e2b20be7 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[860]:0x23d092)
    at ruffle_core::avm1::function::Executable::exec::h590beaec26993867 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/da8291897c0cd59250d4.wasm:wasm-function[363]:0xdab8a)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm
SWF URL: http://www.freeworldgroup.com/games6/electricman2/electricman2hs_fwg.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-21
Channel: nightly
Built: 2021-07-21T00:12:58.313Z
Commit: d2eb46d3be8dcb884847f4ecf0e3f25f9fe075bc

**Comment by sombraguerrero** [comment] 2021-08-31 16:44
duplicate of #4932

**Closed** 2021-09-02 20:48 UTC
Labels: duplicate
