### ISSUE TITLE
Error on https://shsg.herokuapp.com/g/6f2e0289/electric-man-2

### ISSUE THREAD

**Issue by Jayden188** [ruffle-rs/ruffle#6865] opened 2022-05-02 16:54 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.f766d6f756b239246b3a.js:1:6879)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.2/d5ca47470fffe61d6697.wasm:wasm-function[1005]:0x2a51b4)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.2/d5ca47470fffe61d6697.wasm:wasm-function[1448]:0x31cbde)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.2/d5ca47470fffe61d6697.wasm:wasm-function[4937]:0x474ce5)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.2/d5ca47470fffe61d6697.wasm:wasm-function[3246]:0x417100)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.2/d5ca47470fffe61d6697.wasm:wasm-function[5023]:0x478dfa)
    at core::panicking::panic::he88f1b1582b09c8c (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.2/d5ca47470fffe61d6697.wasm:wasm-function[4935]:0x474878)
    at core::ops::function::FnOnce::call_once::hea116a8eeeb59311 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.2/d5ca47470fffe61d6697.wasm:wasm-function[1090]:0x2bdcbc)
    at ruffle_core::avm1::function::Executable::exec::h0a1a3c56ef393e7a (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.2/d5ca47470fffe61d6697.wasm:wasm-function[392]:0x12de2c)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf21230a28d8729f3 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.2/d5ca47470fffe61d6697.wasm:wasm-function[372]:0x111306)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://shsg.herokuapp.com/g/6f2e0289/electric-man-2
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14526.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.133 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-02
Channel: nightly
Built: 2022-05-02T00:19:35.677Z
Commit: 6c5a35d1bc00be28b7cbf309f808b682d959943e
Is extension: false

**Comment by ellieeet123** [comment] 2022-05-03 19:10
I believe this is a duplicate of #4932

**Closed** 2022-05-06 14:26 UTC
Labels: error-report
