### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by killergo1** [ruffle-rs/ruffle#3927] opened 2021-04-07 22:51 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1617817046:1:6915)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://uploads.ungrounded.net/ruffle_wrapper/lib/3931ef9ee9c2a202849e195637dfbcb2.wasm:wasm-function[1227]:0x2ac7ec)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://uploads.ungrounded.net/ruffle_wrapper/lib/3931ef9ee9c2a202849e195637dfbcb2.wasm:wasm-function[1852]:0x3300de)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://uploads.ungrounded.net/ruffle_wrapper/lib/3931ef9ee9c2a202849e195637dfbcb2.wasm:wasm-function[5330]:0x43be39)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://uploads.ungrounded.net/ruffle_wrapper/lib/3931ef9ee9c2a202849e195637dfbcb2.wasm:wasm-function[4135]:0x40eaf5)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (https://uploads.ungrounded.net/ruffle_wrapper/lib/3931ef9ee9c2a202849e195637dfbcb2.wasm:wasm-function[4811]:0x42e6c2)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (https://uploads.ungrounded.net/ruffle_wrapper/lib/3931ef9ee9c2a202849e195637dfbcb2.wasm:wasm-function[5713]:0x441de2)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/3931ef9ee9c2a202849e195637dfbcb2.wasm:wasm-function[5581]:0x440386)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://uploads.ungrounded.net/ruffle_wrapper/lib/3931ef9ee9c2a202849e195637dfbcb2.wasm:wasm-function[5715]:0x441e46)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h4d06e5cc335302b3 (https://uploads.ungrounded.net/ruffle_wrapper/lib/3931ef9ee9c2a202849e195637dfbcb2.wasm:wasm-function[1559]:0x2f9f79)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=mobile&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1617817046%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F443000%2F443187_FFSX6_Part_2.swf%3F1212882468%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22606e36fc93026%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A550%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F443000%2Fflash_443187_card.png%3Ff1608485501%22%7D
SWF URL: https://uploads.ungrounded.net/443000/443187_FFSX6_Part_2.swf?1212882468

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; Redmi Note 9S) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-07
Channel: nightly
Built: 2021-04-07T00:42:04.218Z
Commit: 1020aa84d6f9fb4be215411a5517cc49721c8a3a

**Comment by relrelb** [comment] 2021-04-09 09:44
Duplicate of #3695.

**Closed by relrelb** 2021-04-09 09:44 UTC
