### ISSUE TITLE
Error on https://11c71043-b955-411e-9487-8b3f13a8eea7.filesusr.com/html/ceae95_1ea82e4cb60f52363d98b993c4aea460.html

### ISSUE THREAD

**Issue by howard1990Hl** [ruffle-rs/ruffle#11576] opened 2023-06-16 19:30 UTC
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.cf9a18439af3234f2c03.js:1:51178)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0f1798cf38c8ca4b (wasm://wasm/02c61e22:wasm-function[8670]:0x83c3f7)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c61e22:wasm-function[5629]:0x763e36)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c61e22:wasm-function[8535]:0x838038)
    at alloc::raw_vec::capacity_overflow::h3bb4537b5f9f8404 (wasm://wasm/02c61e22:wasm-function[8282]:0x83158e)
    at swf::read::decompress_swf::hd376b787e8029e7a (wasm://wasm/02c61e22:wasm-function[692]:0x235d3d)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::hc812c8eb1b090f1c (wasm://wasm/02c61e22:wasm-function[849]:0x2e8540)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h80597e70c79ace5f (wasm://wasm/02c61e22:wasm-function[1021]:0x35bdf2)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::ha37f2732e67f2e3a (wasm://wasm/02c61e22:wasm-function[3691]:0x697a37)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h735d2626f98e113e (wasm://wasm/02c61e22:wasm-function[9306]:0x855378)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 600 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 700, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://11c71043-b955-411e-9487-8b3f13a8eea7.filesusr.com/html/ceae95_1ea82e4cb60f52363d98b993c4aea460.html
SWF URL: https://static.wixstatic.com/media/ceae95_4951db2f10204944ab76e5e3739d2a8b.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-16
Channel: nightly
Built: 2023-06-16T00:20:31.625Z
Commit: 69fce3f7f86d8c661a80c19873711956bcc7fbbc
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment] 2023-06-16 19:38
Duplicate of #11129.

**Closed by Lord-McSweeney** 2023-06-16 19:38 UTC
Labels: error-report
