### ISSUE TITLE
Error on https://www.sheppardsoftware.com/Africa/Africa_G2_1024_768.html

### ISSUE THREAD

**Issue by poyo77** [ruffle-rs/ruffle#3207] opened 2021-02-11 16:45 UTC
Whenever I drag a country to the wrong area, it still freezes.(level 3) When I did level 4 where you click, there weren't any issues. Is there anything wrong? 
Has there been a similar issue, on freezing, and a way to fix it.

**Comment by Toad06** [comment] 2021-02-11 19:21
Likely a duplicate of #2551.

**Closed** 2021-07-03 09:06 UTC
Labels: bug, duplicate
