### ISSUE TITLE
Error on https://bigfootshack.pages.dev/g/gfiles/gfiles/flash/

### ISSUE THREAD

**Issue by throwawawayacc** [ruffle-rs/ruffle#9619] opened 2023-02-17 22:10 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:610:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:610:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.e8eef2c4880936d412a5.js:1:5387)
    at std::sync::once::Once::call_once::{{closure}}::hfcec2cf17a6c3683 (wasm://wasm/027ff752:wasm-function[1947]:0x4a1ad2)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/027ff752:wasm-function[1882]:0x490b27)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h315d2ce986e29f2a (wasm://wasm/027ff752:wasm-function[7269]:0x772bc0)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/027ff752:wasm-function[5161]:0x6cd4cf)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/027ff752:wasm-function[7578]:0x781934)
    at core::option::expect_failed::hde6894209e142acf (wasm://wasm/027ff752:wasm-function[8768]:0x7abe80)
    at ruffle_core::display_object::stage::Stage::root_clip::hebdca7d6c5e3d7d9 (wasm://wasm/027ff752:wasm-function[5151]:0x6cc295)
    at ruffle_web::Ruffle::tick::hcd5ea5c8778cdd4b (wasm://wasm/027ff752:wasm-function[665]:0x21a7dc)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hdd4d66b11b56f7fa (wasm://wasm/027ff752:wasm-function[9215]:0x7bd20c)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://bigfootshack.pages.dev/g/gfiles/gfiles/flash/?swf=nv2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-17
Channel: nightly
Built: 2023-02-17T00:20:12.293Z
Commit: 559ec8356ddf909d2bc0ca6561d2fff334eb3151
Is extension: false

# Metadata
width: 792
height: 600
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1464627

**Comment by n0samu** [comment] 2023-02-20 02:57
Duplicate of #9219

**Closed by n0samu** 2023-02-20 02:57 UTC
Labels: duplicate, error-report
