### ISSUE TITLE
Error on https://game70421.konggames.com/games/BoMToons/chibi-knight/frame/45d7d0b5-3c82-4c22-b788-1285d4a7380d/

### ISSUE THREAD

**Issue by IlasTv** [ruffle-rs/ruffle#9028] opened 2023-01-04 20:27 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:760:32
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:760:32
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.92560d6d5d8902e06920.js:1:6432)
    at std::sync::once::Once::call_once::{{closure}}::h456b15a3372f5cac (wasm://wasm/018f3fbe:wasm-function[1111]:0x2ae7ed)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018f3fbe:wasm-function[1417]:0x31b07c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haaf675683a690fa4 (wasm://wasm/018f3fbe:wasm-function[5079]:0x4b5aeb)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018f3fbe:wasm-function[3751]:0x477728)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018f3fbe:wasm-function[5285]:0x4b9f02)
    at core::panicking::panic::h0859aaac783261b2 (wasm://wasm/018f3fbe:wasm-function[5099]:0x4b606b)
    at core::ops::function::FnOnce::call_once::hd3b716ed7fdfae1b (wasm://wasm/018f3fbe:wasm-function[1077]:0x2a4a01)
    at ruffle_core::avm1::function::Executable::exec::h9987a0481b631d31 (wasm://wasm/018f3fbe:wasm-function[363]:0xe8b73)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::ha9171779f3059a57 (wasm://wasm/018f3fbe:wasm-function[1458]:0x3273be)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://game70421.konggames.com/games/BoMToons/chibi-knight/frame/45d7d0b5-3c82-4c22-b788-1285d4a7380d/?kongregate_host=www.kongregate.com
SWF URL: https://game70421.konggames.com/gamez/0007/0421/live/beastgame_kong.swf?kongregate_game_version=1265086391

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-04
Channel: nightly
Built: 2023-01-04T00:14:51.216Z
Commit: 664a86161ac55eee8afd61c067b50578191c1088
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 25
numFrames: 7
swfVersion: 9
backgroundColor: #666666
isActionScript3: false
uncompressedLength: 7891171

**Comment by n0samu** [comment] 2023-01-04 22:24
Duplicate of #3756

**Closed by n0samu** 2023-01-04 22:24 UTC
Labels: duplicate, error-report
