### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by 69420nuggets** [ruffle-rs/ruffle#4229] opened 2021-05-03 23:23 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1620075578:1:7479)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://uploads.ungrounded.net/ruffle_wrapper/lib/349d49a671de87a3e810.wasm:wasm-function[1227]:0x2ba694)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://uploads.ungrounded.net/ruffle_wrapper/lib/349d49a671de87a3e810.wasm:wasm-function[1250]:0x2c22b8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://uploads.ungrounded.net/ruffle_wrapper/lib/349d49a671de87a3e810.wasm:wasm-function[3750]:0x44c00b)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://uploads.ungrounded.net/ruffle_wrapper/lib/349d49a671de87a3e810.wasm:wasm-function[2743]:0x3aa0ea)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/349d49a671de87a3e810.wasm:wasm-function[3956]:0x451cad)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://uploads.ungrounded.net/ruffle_wrapper/lib/349d49a671de87a3e810.wasm:wasm-function[4103]:0x458d4d)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::ha679d49c7aa61655 (https://uploads.ungrounded.net/ruffle_wrapper/lib/349d49a671de87a3e810.wasm:wasm-function[841]:0x247650)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h08b35b209a139415 (https://uploads.ungrounded.net/ruffle_wrapper/lib/349d49a671de87a3e810.wasm:wasm-function[4231]:0x45acb2)
    at A (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1620075578:1:3232)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1620075578%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2286028142.5ba476fc070906db8c97dcb66a34f89d5309d7a72e9008%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22609070cf685f5%22%2C%22NewgroundsAPI_SessionID%22%3A%22P54lOQfX9zEy9qSLBJZ1a039b27b7b5e17d796b2a19b70f0e10a58e281d3E1sJ%22%2C%22NewgroundsAPI_UserName%22%3A%2269420nuggets%22%2C%22NewgroundsAPI_UserID%22%3A8833509%2C%22ng_username%22%3A%2269420nuggets%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-03
Channel: nightly
Built: 2021-05-03T00:12:09.006Z
Commit: f2256a661be22fd12ae1ec3b40574d7cca670a27

**Comment by torokati44** [comment] 2021-06-09 01:00
Duplicate of 4226.

**Closed by torokati44** 2021-06-09 01:00 UTC
