### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm

### ISSUE THREAD

**Issue by sankalp7015** [ruffle-rs/ruffle#7518] opened 2022-07-30 15:12 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:822:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:822:18
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/core.ruffle.646778342f5b92d93721.js:1:6065)
    at std::sync::once::Once::call_once::{{closure}}::h5fd96c2e051bcaea (wasm://wasm/016124d2:wasm-function[1203]:0x2af94e)
    at std::sync::once::Once::call_inner::h1c414562e2619117 (wasm://wasm/016124d2:wasm-function[1386]:0x2e027b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h37057bbdf9b38d3b (wasm://wasm/016124d2:wasm-function[4725]:0x42b1f7)
    at std::panicking::rust_panic_with_hook::h1c368a27f9b0afe1 (wasm://wasm/016124d2:wasm-function[3075]:0x3ce36e)
    at core::panicking::panic_fmt::hcdb13a4b2416cf82 (wasm://wasm/016124d2:wasm-function[4911]:0x4312ae)
    at core::panicking::panic::ha8ced62e366a0d64 (wasm://wasm/016124d2:wasm-function[4822]:0x42d354)
    at core::ops::function::FnOnce::call_once::h6bf3c59fc0d6a678 (wasm://wasm/016124d2:wasm-function[1017]:0x271d69)
    at ruffle_core::avm1::function::Executable::exec::h779b8971096b5012 (wasm://wasm/016124d2:wasm-function[379]:0xf3398)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hbc611d601c3115b6 (wasm://wasm/016124d2:wasm-function[795]:0x2156fa)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm
SWF URL: http://www.freeworldgroup.com/games6/electricman2/electricman2hs_fwg.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 OPR/89.0.4447.64
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-29
Channel: nightly
Built: 2022-07-29T00:16:13.179Z
Commit: f2deeb4de87fc85fe2bf2a2ff6ce11b789be1d2f
Is extension: false

**Comment by n0samu** [comment] 2022-07-30 19:25
Duplicate of #4932

**Closed by n0samu** 2022-07-30 19:25 UTC
Labels: duplicate, error-report
