### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by libernum** [ruffle-rs/ruffle#10201] opened 2023-03-18 02:45 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:317:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:317:26
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2200:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0312d4caddbaee90 (wasm://wasm/02a65c2a:wasm-function[8039]:0x7f123e)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a65c2a:wasm-function[5354]:0x72830e)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a65c2a:wasm-function[7918]:0x7ec539)
    at core::panicking::panic::ha3ebcac1438d9280 (wasm://wasm/02a65c2a:wasm-function[7333]:0x7b9339)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h960eb6c6018f2e52 (wasm://wasm/02a65c2a:wasm-function[620]:0x1e145a)
    at ruffle_core::loader::Loader::preload_tick::h2b6adfbcbce13827 (wasm://wasm/02a65c2a:wasm-function[810]:0x2bee88)
    at ruffle_web::Ruffle::tick::hd363147e523d3ba1 (wasm://wasm/02a65c2a:wasm-function[690]:0x242c3a)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h36472d83d0669f8c (wasm://wasm/02a65c2a:wasm-function[9642]:0x82a97f)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h678c9e4dc3beaab6 (wasm://wasm/02a65c2a:wasm-function[8548]:0x7fd210)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=700&sp=0&questionSet=&r=6747117&&width=640&height=500&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-17
Channel: nightly
Built: 2023-03-17T00:21:29.148Z
Commit: 32f8330199d6c244e41d15fcbb9a9d028fc83af8
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by n0samu** [comment] 2023-04-22 07:40
Duplicate of #9972

**Closed by n0samu** 2023-04-22 07:40 UTC
Labels: duplicate, error-report
