### ISSUE TITLE
Error on https://flashthemes.net/

### ISSUE THREAD

**Issue by blind09** [ruffle-rs/ruffle#14760] opened 2024-01-15 10:04 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_a64e3f2afc2cf2f8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a435d7beef43b50 (wasm://wasm/03633e02:wasm-function[10788]:0xa1bc13)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/03633e02:wasm-function[6606]:0x903b11)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/03633e02:wasm-function[10500]:0xa15778)
    at core::panicking::assert_failed_inner::h003d4b5b03930769 (wasm://wasm/03633e02:wasm-function[4518]:0x7f7b21)
    at core::panicking::assert_failed::he3b51eda916f2b46 (wasm://wasm/03633e02:wasm-function[10552]:0xa1702a)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::h19da251e7ef3f574 (wasm://wasm/03633e02:wasm-function[2414]:0x63f2f7)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::heb2d58e3ea262753 (wasm://wasm/03633e02:wasm-function[1276]:0x43ecf9)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h007033b9284c7696 (wasm://wasm/03633e02:wasm-function[3705]:0x780570)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::he60536ce30c58d9e (wasm://wasm/03633e02:wasm-function[11732]:0xa36efa)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Qualcomm, Adreno (TM) 530, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param flashvars: movieId=0fSljuR2z0&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D1775&thumburl=%2Fmovie_thumbs%2Fthumb-0fSljuR2z0.png&v=1775&movieLid=6&pwm=0&ut=-1&apiserver=https%3A%2F%2Fflashthemes.net%2F&playcount=1&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=1&isInitFromExternal=0&isWide=0&appCode=go&is_slideshow=0&is_emessage=0&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=0&&&&isTemplate=0&showButtons=1&chain_mids=&endStyle=0&showshare=true
Param movie: /static/animationnew/414827163ad4eb60/player.swf
Param wmode: opaque
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-15
Channel: nightly
Built: 2024-01-15T00:15:42.928Z
Commit: a638715bd87d818d134a70659e7124234b992447
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment] 2024-01-16 20:57
Duplicate of #13974

**Closed by n0samu** 2024-01-16 20:57 UTC
Labels: duplicate, error-report
