### ISSUE TITLE
Error on https://f.kbhgames.com/RS/game.php

### ISSUE THREAD

**Issue by naruto109** [ruffle-rs/ruffle#5995] opened 2022-01-05 22:56 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://f.kbhgames.com/RS/asset/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::hdee01963557c8b87 (wasm://wasm/0193f982:wasm-function[1000]:0x30efb6)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (wasm://wasm/0193f982:wasm-function[1192]:0x35318b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e75ef83c7eceddf (wasm://wasm/0193f982:wasm-function[4707]:0x50c322)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (wasm://wasm/0193f982:wasm-function[3243]:0x4b900c)
    at rust_begin_unwind (wasm://wasm/0193f982:wasm-function[4770]:0x50d84f)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (wasm://wasm/0193f982:wasm-function[4983]:0x518753)
    at core::panicking::panic::hec1fc057bd0baf0b (wasm://wasm/0193f982:wasm-function[4704]:0x50bb88)
    at core::ops::function::FnOnce::call_once::hb83ea7c2d8824069 (wasm://wasm/0193f982:wasm-function[1050]:0x32ce28)
    at ruffle_core::avm1::function::Executable::exec::h97e3cc64039ed9c3 (wasm://wasm/0193f982:wasm-function[433]:0x1733db)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://f.kbhgames.com/RS/game.php?r=//f.kbhgames.com/2018/swf/electricalman2.swf&w=640&h=400
SWF URL: https://f.kbhgames.com/2018/swf/electricalman2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14268.67.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.111 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-16
Channel: nightly
Built: 2021-12-16T00:12:02.888Z
Commit: 07c533045604f42610bb3ca5480d9443b78f7fb7
Is extension: false

**Comment by Poopooracoocoo** [comment] 2022-01-06 00:16
Duplicate of #4932

**Closed by Poopooracoocoo** 2022-01-06 00:16 UTC
Labels: duplicate, error-report
