### ISSUE TITLE
Error on https://shsgames.github.io/g/6f2e0289/electric-man-2

### ISSUE THREAD

**Issue by JaxonPiced** [ruffle-rs/ruffle#6409] opened 2022-03-06 22:32 UTC
I'm Just playing the game and then the bots your supposed to fight it just skips ALL the instructions exept the first what five? then it still shows all the bots on there just incase your wondering its not supposed to do that then it pops up the file a bug screen

**Comment by relrelb** [comment] 2022-03-10 14:18
Duplicate of #4932.

**Closed by relrelb** 2022-03-10 14:18 UTC
Labels: error-report
