### ISSUE TITLE
Error on https://www.gameflare.com/embed/jacksmith/

### ISSUE THREAD

**Issue by 1zloy340** [ruffle-rs/ruffle#15807] opened 2024-03-29 16:37 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096


    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://www.gameflare.com/emulators/ruffle/core.ruffle.bb26a71ccb0aa747c8a7.js:1:73847)
    at js_sys::Error::new::h1454cf2a6de1ec1d (wasm://wasm/03a571ea:wasm-function[13919]:0xb2324c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb6b4ae70cf9cbae6 (wasm://wasm/03a571ea:wasm-function[11514]:0xacdbc4)
    at std::panicking::rust_panic_with_hook::h6b00a1542b7e827c (wasm://wasm/03a571ea:wasm-function[7085]:0x996b5c)
    at core::panicking::panic_fmt::h7d22643b0becf577 (wasm://wasm/03a571ea:wasm-function[11221]:0xac74c0)
    at core::ops::function::Fn::call::h78d1ab2f661a948a (wasm://wasm/03a571ea:wasm-function[7403]:0x9aeff0)
    at wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::hf316f3c586d2cdf4 (wasm://wasm/03a571ea:wasm-function[5859]:0x9249d2)
    at wgpu::backend::wgpu_core::ContextWgpuCore::handle_error::h1a200e9f35c88622 (wasm://wasm/03a571ea:wasm-function[3078]:0x715def)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h966fdf81949e6171 (wasm://wasm/03a571ea:wasm-function[10717]:0xa97dda)
    at wgpu::CommandEncoder::copy_texture_to_buffer::hed57d54777c87735 (wasm://wasm/03a571ea:wasm-function[9858]:0xa6df4e)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (ARM, Mali-G57, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 4096, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.gameflare.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-27
Channel: nightly
Built: 2024-03-27T00:05:34.252Z
Commit: 67a04dcc75838afa7de7130bc69dc3e81bc294a7
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by evilpie** [comment] 2024-04-09 15:04
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:04 UTC
Labels: render-wgpu, error-report
