### ISSUE TITLE
Error on https://www.gameflare.com/embed/chibi-knight/

### ISSUE THREAD

**Issue by ermalbela** [ruffle-rs/ruffle#9445] opened 2023-02-06 22:01 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:756:32
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:756:32
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://www.gameflare.com/emulators/ruffle/core.ruffle.2796ca293e6c92590943.js:1:5412)
    at std::sync::once::Once::call_once::{{closure}}::h24436b3e76607d05 (wasm://wasm/027c294e:wasm-function[1925]:0x4855e1)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027c294e:wasm-function[1857]:0x4758ab)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdf8faf7e861f36fc (wasm://wasm/027c294e:wasm-function[7197]:0x769895)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027c294e:wasm-function[5104]:0x6c4a1f)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027c294e:wasm-function[7502]:0x7783f5)
    at core::panicking::panic::h364c37174a08a6a4 (wasm://wasm/027c294e:wasm-function[6909]:0x744f61)
    at core::ops::function::FnOnce::call_once::hc3dca223e3bc8c64 (wasm://wasm/027c294e:wasm-function[788]:0x277622)
    at ruffle_core::avm1::function::Executable::exec::h05de1024cd75b75b (wasm://wasm/027c294e:wasm-function[573]:0x1801f9)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hdb83886636a26c3d (wasm://wasm/027c294e:wasm-function[1379]:0x3a360e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/chibi-knight/
SWF URL: https://data.gameflare.com/games/6255/H8me4QU2dF0alM.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-30
Channel: nightly
Built: 2023-01-30T00:19:04.244Z
Commit: 15c7b6520b525a67f5224855ec7e49eb0604aa07
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 25
numFrames: 7
swfVersion: 9
backgroundColor: #666666
isActionScript3: false
uncompressedLength: 7885259

**Comment by Lord-McSweeney** [comment] 2023-02-06 23:32
Duplicate of #3756.

**Closed by Lord-McSweeney** 2023-02-06 23:32 UTC
Labels: error-report
