### ISSUE TITLE
Error on http://www.mygamesworld.com/game/2816/Vector_TDX.html

### ISSUE THREAD

**Issue by Drixhen816** [ruffle-rs/ruffle#7315] opened 2022-06-30 09:49 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.mygamesworld.com/jscripts/core.ruffle.9257751f207a7db4a8f4.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::h04c6018a30aae0b2 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[1023]:0x2c1985)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[1459]:0x32fd41)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h629785d4908f37da (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[4922]:0x482981)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[3239]:0x4256ab)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[5209]:0x48eaab)
    at core::result::unwrap_failed::hd5a60243cf946632 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[4145]:0x46a928)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h6f9edb4006f336a4 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[739]:0x23d91a)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::hebed92ddf1de0244 (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[3246]:0x425c67)
    at ruffle_core::drawing::Drawing::render::h5bc57038455d981a (http://www.mygamesworld.com/jscripts/37414a2c1295e4921309.wasm:wasm-function[664]:0x219f54)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: http://www.mygamesworld.com/files/file/vectortdxTh.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://www.mygamesworld.com/game/2816/Vector_TDX.html
SWF URL: http://www.mygamesworld.com/files/file/vectortdxTh.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14695.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-04
Channel: nightly
Built: 2022-03-04T00:15:35.142Z
Commit: 31446785f9804fcd8090da4670a9f4038a558e6e
Is extension: false

**Comment by n0samu** [comment] 2022-07-01 04:42
Duplicate of #7169

**Closed by n0samu** 2022-07-01 04:42 UTC
Labels: duplicate, error-report
