### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by CoolDino1** [ruffle-rs/ruffle#6110] opened 2022-01-22 23:03 UTC
Could you add a download button for Flash files? To download files I need to disable ruffle. You could put it by the other buttons that appear when you right click.
Thanks,
CoolDino1

**Comment by torokati44** [comment] 2022-01-22 23:08
This is already possible with the browser extension: https://github.com/ruffle-rs/ruffle/pull/5602
As for why only there: https://github.com/ruffle-rs/ruffle/pull/1889

Also related issues: https://github.com/ruffle-rs/ruffle/issues/4670 https://github.com/ruffle-rs/ruffle/issues/4158 https://github.com/ruffle-rs/ruffle/issues/2500 https://github.com/ruffle-rs/ruffle/issues/1885 https://github.com/ruffle-rs/ruffle/issues/5696

**Comment by danielhjacobs** [comment] 2022-01-22 23:32
It's also possible with the self hosted version with the showSwfDownload configuration value. See also https://github.com/ruffle-rs/ruffle/issues/5825 for why the extension toggle doesn't currently work if a site self-hosts Ruffle.

**Comment by Poopooracoocoo** [comment] 2022-01-23 06:13
Closing this as a duplicate of #5825

**Closed by Poopooracoocoo** 2022-01-23 06:13 UTC
Labels: duplicate, enhancement
