### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by ObliviousPlant** [ruffle-rs/ruffle#7207] opened 2022-06-10 22:16 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.d8409feb7cfa6dd334fd.js:1:7024)
    at std::sync::once::Once::call_once::{{closure}}::hf4bd8358d66e2cc8 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bb8b9a8ee86b26f77767.wasm:wasm-function[1184]:0x2aed45)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bb8b9a8ee86b26f77767.wasm:wasm-function[1406]:0x2e9d97)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ffe884207fb3c6a (https://uploads.ungrounded.net/ruffle_wrapper/lib/bb8b9a8ee86b26f77767.wasm:wasm-function[4746]:0x4394ed)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bb8b9a8ee86b26f77767.wasm:wasm-function[3142]:0x3de058)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bb8b9a8ee86b26f77767.wasm:wasm-function[4928]:0x43f54e)
    at core::panicking::panic::hc28e7cc2aa792341 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bb8b9a8ee86b26f77767.wasm:wasm-function[4839]:0x43b547)
    at core::ops::function::FnOnce::call_once::h4faf124a219f785d (https://uploads.ungrounded.net/ruffle_wrapper/lib/bb8b9a8ee86b26f77767.wasm:wasm-function[1051]:0x287cc2)
    at ruffle_core::avm1::function::Executable::exec::h1e3c90f25dc88eb1 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bb8b9a8ee86b26f77767.wasm:wasm-function[358]:0xc9f6a)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h109691e3d62f182b (https://uploads.ungrounded.net/ruffle_wrapper/lib/bb8b9a8ee86b26f77767.wasm:wasm-function[541]:0x1944e1)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1654782845%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2244585047.2b8ff7b8ab3a26901d6fdd22bd23f61ff02eee9b20b7d1%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2262a3ba8b80fbb%22%2C%22NewgroundsAPI_SessionID%22%3A%22lKME0BnjffcPezUSbqaM58f20067c357d2757beed7ab3c48dba9166d6bb0qNQT%22%2C%22NewgroundsAPI_UserName%22%3A%22ObliviousPlant%22%2C%22NewgroundsAPI_UserID%22%3A11214819%2C%22ng_username%22%3A%22ObliviousPlant%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 OPR/86.0.4363.70
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-09
Channel: nightly
Built: 2022-06-09T00:14:19.246Z
Commit: dde21a2a606c479e96b454e9eba54084ae173b85
Is extension: false

**Comment by n0samu** [comment] 2022-06-10 22:23
Duplicate of #3756

**Closed by n0samu** 2022-06-10 22:23 UTC
Labels: duplicate, error-report
