### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Alphomegar** [ruffle-rs/ruffle#6284] opened 2022-02-13 18:53 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.25973f3ed2b17396c464.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (https://uploads.ungrounded.net/ruffle_wrapper/lib/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1016]:0x2f3fd8)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1152]:0x3276ac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4725]:0x4d3db3)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b2fc0abe3dbbf4e736aa.wasm:wasm-function[3192]:0x47f3dc)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4996]:0x4df9ff)
    at core::panicking::panic::h35778e3c18266c93 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4722]:0x4d38da)
    at core::ops::function::FnOnce::call_once::h63635e87c343a6bd (https://uploads.ungrounded.net/ruffle_wrapper/lib/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1053]:0x30a723)
    at ruffle_core::avm1::function::Executable::exec::h01bdca74588653f1 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b2fc0abe3dbbf4e736aa.wasm:wasm-function[395]:0x145b12)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hd2ac2ca7aecc5e6d (https://uploads.ungrounded.net/ruffle_wrapper/lib/b2fc0abe3dbbf4e736aa.wasm:wasm-function[381]:0x10b308)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1643840749%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2295492495.7263ae037490266b282a76e4b78dd918721abbac86c98a%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226209535639ea2%22%2C%22NewgroundsAPI_SessionID%22%3A%22o5IJHFs9dwbAjAmdHdpD3da3df5aad533ea46e4f81206805288701e93c40PYX9%22%2C%22NewgroundsAPI_UserName%22%3A%22CraftingFilip%22%2C%22NewgroundsAPI_UserID%22%3A6936374%2C%22ng_username%22%3A%22CraftingFilip%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.50
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-02
Channel: nightly
Built: 2022-02-02T00:18:10.903Z
Commit: 85ce9ebdcb644f8c9972243053a55d0c38b19b2f
Is extension: false

**Comment by Alphomegar** [comment] 2022-02-13 18:54
Help! Please! Fix this bug right now🥺🥺

**Comment by relrelb** [comment] 2022-03-01 06:10
Duplicate of #3756.

**Closed by relrelb** 2022-03-01 06:10 UTC
Labels: error-report
