### ISSUE TITLE
Mspacman keys not working

### ISSUE THREAD

**Issue by nigelcov** [ruffle-rs/ruffle#2442] opened 2021-01-12 22:16 UTC
https://www.webretrogames.com/mspacman.php  Keys not working to control game.

**Comment by Aaron1011** [comment] 2021-01-15 18:26
This is caused by https://github.com/ruffle-rs/ruffle/issues/458. The obfuscated code for the relevant `keyDown` handler performs a negative jump out of the ClipAction, and into the preceding tag (type 253).

**Comment by Herschel** [comment] 2021-01-20 23:13
Thanks for the report! Fixed by #2636.

**Closed by Herschel** 2021-01-20 23:13 UTC
Labels: actionscript, avm1, bug
