### ISSUE TITLE
Error on https://ruffle.rs/demo/ with attempt to run simai

### ISSUE THREAD

**Issue by Sam122715** [ruffle-rs/ruffle#7158] opened 2022-06-04 11:27 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:23:9
Error stack:
```
@https://ruffle.rs/demo/662.index.js:1:7796
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h074a5b43a199c982]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h8a142b2dcc139875]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h3cf43421fa49406f]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::he2a025723e105e28]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hb02133958c1e7d35]@[wasm code]
<?>.wasm-function[core::panicking::assert_failed_inner::hccef927c65b4d745]@[wasm code]
<?>.wasm-function[core::panicking::assert_failed::h54494374700e78d9]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbe68bc7307700f25]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4139724145661d88]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::hf6f8e75dc21a5b85]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6fb2540f55cb3894]@[wasm code]
wasm-stub@[native code]
O@https://ruffle.rs/demo/662.index.js:1:3954
c@https://ruffle.rs/demo/662.index.js:1:2479
promiseReactionJob@[native code]
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/605.1 NAVER(inapp; search; 1010; 11.11.0; 13MINI)
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-03
Channel: nightly
Built: 2022-06-03T00:17:03.624Z
Commit: 53ef80f51443342b6f40e48e843655a062bbd37c
Is extension: false

**Comment by n0samu** [comment] 2022-06-04 20:22
Duplicate of #6608. Updating your device to iOS 15.5 should fix the issue!

**Closed by n0samu** 2022-06-04 20:22 UTC
Labels: duplicate, error-report
