### ISSUE TITLE
The last stand: Union City: character not showing

### ISSUE THREAD

**Issue by DEVA5581** [ruffle-rs/ruffle#8279] opened 2022-10-13 04:35 UTC
### Describe the bug

the character and the background is not shown only moving background

### Expected behavior

the character and background are shown correctly

### Affected platform

Online demo

### Operating system

chrome OS

### Browser

Google CHrome

**Comment by DEVA5581** [comment] 2022-10-13 04:44
[128954_the_last_stand_union_city.zip](https://github.com/ruffle-rs/ruffle/files/9770837/128954_the_last_stand_union_city.zip)
this is the SWF file

**Comment by n0samu** [comment] 2022-10-13 16:42
Duplicate of #5516

**Closed by n0samu** 2022-10-13 16:42 UTC
Labels: bug, duplicate
