### ISSUE TITLE
Error on http://swordandsandals.top/swords-and-sandals-2-hacked/

### ISSUE THREAD

**Issue by ompa175** [ruffle-rs/ruffle#14502] opened 2023-12-24 16:32 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.4023be96d56a3c732101.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h643031ddb85c668c (wasm://wasm/03415476:wasm-function[9876]:0x9d21e2)
    at std::panicking::rust_panic_with_hook::hbf46ef0245cc9589 (wasm://wasm/03415476:wasm-function[6317]:0x8c0ae9)
    at core::panicking::panic_fmt::h14c85a61aa3d538e (wasm://wasm/03415476:wasm-function[9668]:0x9cce59)
    at core::result::unwrap_failed::hc368cb5845aa399d (wasm://wasm/03415476:wasm-function[7668]:0x93117d)
    at <T as wgpu::context::DynContext>::device_create_texture::h49848767f9aea23d (wasm://wasm/03415476:wasm-function[7116]:0x903411)
    at wgpu::Device::create_texture::hb37fd5364429be72 (wasm://wasm/03415476:wasm-function[5504]:0x87624d)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h7dbe49cff77f57ec (wasm://wasm/03415476:wasm-function[5347]:0x868f27)
    at ruffle_core::display_object::render_base::hc1306a2d695f2ed1 (wasm://wasm/03415476:wasm-function[625]:0x172681)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h987348dc9632b28a (wasm://wasm/03415476:wasm-function[6963]:0x8ee457)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 SUPER (0x00002187) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://swordandsandals.top/swords-and-sandals-2-hacked/
SWF URL: http://swordandsandals.top/wp-content/uploads/swordsandsandals2-hacked.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-24
Channel: nightly
Built: 2023-12-24T00:16:48.219Z
Commit: a7145380ac6c87a38c067e17dcddf717df3ad09c
Is extension: false

# Metadata
width: 700
height: 525
frameRate: 30
numFrames: 1
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 760

**Comment by evilpie** [comment] 2024-02-01 20:33
Duplicate of #11852

**Closed** 2024-02-01 20:35 UTC
Labels: error-report
