### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by beberagua** [ruffle-rs/ruffle#6036] opened 2022-01-12 16:24 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1641907039:1:7158)
    at std::sync::once::Once::call_once::{{closure}}::hd1b4f64c6a058fdf (https://uploads.ungrounded.net/ruffle_wrapper/lib/42ef41f25116839c8e75.wasm:wasm-function[995]:0x2f58da)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://uploads.ungrounded.net/ruffle_wrapper/lib/42ef41f25116839c8e75.wasm:wasm-function[1189]:0x33b8db)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7c91d9e8737f5a50 (https://uploads.ungrounded.net/ruffle_wrapper/lib/42ef41f25116839c8e75.wasm:wasm-function[4699]:0x505559)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://uploads.ungrounded.net/ruffle_wrapper/lib/42ef41f25116839c8e75.wasm:wasm-function[3242]:0x4b1ba1)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/42ef41f25116839c8e75.wasm:wasm-function[4766]:0x506d72)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://uploads.ungrounded.net/ruffle_wrapper/lib/42ef41f25116839c8e75.wasm:wasm-function[4978]:0x511c44)
    at core::panicking::panic::hec1fc057bd0baf0b (https://uploads.ungrounded.net/ruffle_wrapper/lib/42ef41f25116839c8e75.wasm:wasm-function[4696]:0x504dbf)
    at core::ops::function::FnOnce::call_once::h83f26a94bb6d39f3 (https://uploads.ungrounded.net/ruffle_wrapper/lib/42ef41f25116839c8e75.wasm:wasm-function[1047]:0x3128fa)
    at ruffle_core::avm1::function::Executable::exec::h00e69fc62e0063bd (https://uploads.ungrounded.net/ruffle_wrapper/lib/42ef41f25116839c8e75.wasm:wasm-function[432]:0x15c34e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1641907039%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261df00536661c%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14268.67.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.111 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-11
Channel: nightly
Built: 2022-01-11T00:13:04.329Z
Commit: b39ab9034c5bff008a6cff32d0890e5d4cc0942b
Is extension: false

**Comment by Poopooracoocoo** [comment] 2022-01-14 18:00
Duplicate of #3756

**Closed by Poopooracoocoo** 2022-01-14 18:00 UTC
Labels: duplicate, error-report
