### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by SrGerter** [ruffle-rs/ruffle#8394] opened 2022-10-26 13:26 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.891e9ea1d974528e08b2.js:1:6805)
    at std::sync::once::Once::call_once::{{closure}}::h5b3584428e2c6e9f (wasm://wasm/0181631a:wasm-function[1217]:0x2c3933)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0181631a:wasm-function[1494]:0x3130a1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2ad31bbb08635044 (wasm://wasm/0181631a:wasm-function[4902]:0x48a663)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0181631a:wasm-function[3603]:0x44806e)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0181631a:wasm-function[5123]:0x48edd4)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/0181631a:wasm-function[4957]:0x48b5d5)
    at core::ops::function::FnOnce::call_once::hb4b16575678782a6 (wasm://wasm/0181631a:wasm-function[1120]:0x29ee5d)
    at ruffle_core::avm1::function::Executable::exec::h7e5ed1117c7e817b (wasm://wasm/0181631a:wasm-function[362]:0xdc684)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h9a9a6510cccb34d5 (wasm://wasm/0181631a:wasm-function[1066]:0x28b2e5)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=7517&mp_game_uid=electricman-2&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Felectricman-2&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvZW1hbjIuc3dm&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=America%2FAsuncion&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/eman2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-26
Channel: nightly
Built: 2022-10-26T00:15:48.681Z
Commit: fd76f67bd22102879e119ccd18d646ae01390048
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment] 2022-10-26 14:20
Duplicate of #4932

**Closed by n0samu** 2022-10-26 14:20 UTC
Labels: duplicate, error-report
