### ISSUE TITLE
Error on https://ipsproarcade.com/index.php

### ISSUE THREAD

**Issue by C-Listensprechen** [ruffle-rs/ruffle#4499] opened 2021-06-03 17:05 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 15 but the index is 4294967295', render/webgl/src/lib.rs:1349:25
Error stack:
```
e/a.wbg.__wbg_new_df6e6ab7a65c4c4d@https://ipsproarcade.com/applications/ruffle/ruffle.js:1:7026
std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[1093]:0x287159
std::sync::once::Once::call_inner::h99e47643887ee5a5@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[963]:0x261594
core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[3852]:0x411d1f
std::panicking::rust_panic_with_hook::h03201bc01a0ed891@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[3000]:0x3b2435
rust_begin_unwind@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[4058]:0x4175d9
core::panicking::panic_fmt::hd44f353696296fec@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[4206]:0x41de83
core::panicking::panic_bounds_check::h6f1d19fbb70f7a33@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[3604]:0x40761b
ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h7b6baa2d9ddb917a@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[607]:0x1b4d12
<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h74b0c42b5fdc6385@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[2373]:0x385705
ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h08408286065ef93b@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[1840]:0x3347fa
ruffle_core::display_object::movie_clip::MovieClip::preload::h85f43b5eababe1bd@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[665]:0x1d1a25
ruffle_core::player::Player::set_root_movie::h1f37af46b06b118d@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[326]:0x9f16d
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hec010d7c15f8344d@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[548]:0x1888b8
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h05b19c3b164bd2bc@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[1493]:0x2ef9f8
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hf69000ae5b7fa7b3@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[2351]:0x383803
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h788d00844485fb90@https://ipsproarcade.com/applications/ruffle/d7e07f3de04238324353.wasm:wasm-function[4346]:0x42024c
T@https://ipsproarcade.com/applications/ruffle/ruffle.js:1:4150
a@https://ipsproarcade.com/applications/ruffle/ruffle.js:1:2798

```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://ipsproarcade.com/arcade/CircusConnectMahjong_HMv32.swf
Param movie: https://ipsproarcade.com/arcade/CircusConnectMahjong_HMv32.swf
Param pluginspage: http://www.macromedia.com/go/getflashplayer/
Param bgcolor: #000000
Param quality: high
Param menu: true
Param wmode: direct
Param allowScriptAccess: always
Param play: true
Param loop: true
Param hasPriority: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://ipsproarcade.com/index.php?ipsproarcade/playgame/28502-circus-connect-mahjong
SWF URL: https://ipsproarcade.com/arcade/CircusConnectMahjong_HMv32.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-01
Channel: nightly
Built: 2021-06-01T00:30:49.155Z
Commit: d3512ca3a1c08643edbc5a05904796e775778156

**Comment by relrelb** [comment] 2021-06-05 19:45
Duplicate of #3365.

**Closed by relrelb** 2021-06-05 19:45 UTC
