### ISSUE TITLE
Ruffle Error on https://www.electricman.space/

### ISSUE THREAD

**Issue by AmeenkimoB** [ruffle-rs/ruffle#7476] opened 2022-07-25 18:35 UTC
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at https://electricman.space/ruffle/ruffle.js:1:67052
    at Array.forEach (<anonymous>)
    at vi.f.wasm (https://electricman.space/ruffle/ruffle.js:1:66979)
    at https://electricman.space/ruffle/ruffle.js:1:35299
    at Array.reduce (<anonymous>)
    at vi.e (https://electricman.space/ruffle/ruffle.js:1:35276)
    at o (https://electricman.space/ruffle/ruffle.js:1:2595)
    at o.next (<anonymous>)
    at https://electricman.space/ruffle/ruffle.js:1:2895
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: electricman.swf
Param game: electricman.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.electricman.space/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36 OPR/88.0.4412.85
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-02
Channel: nightly
Built: 2021-01-02T00:44:12.942Z
Commit: 83c32e8693ec7d585713d457599b87b81e2057c3

**Comment by n0samu** [comment] 2022-07-25 18:42
Duplicate of #7460. Please visit the site using the URL https://electricman.space/ instead, or contact them and ask them to fix the problem with their website.

**Closed by n0samu** 2022-07-25 18:42 UTC
Labels: error-report
