### ISSUE TITLE
Ultimate Flash Sonic doesn't work on Ruffle

### ISSUE THREAD

**Issue by arthurgps2** [ruffle-rs/ruffle#2342] opened 2021-01-08 22:37 UTC
:c

**Comment by Fancy2209** [comment] 2021-01-08 23:43
You need to provide details or it'll will be marked as invalid

**Comment by Poopooracoocoo** [comment] 2021-01-09 04:10
Do issues #1441 and #1626 cover your problem? 
Are you playing it on a website like Newgrounds or Internet Archive? 
Which browser? 
Are you using the extension or the desktop build? 
Without additional information the developers won't be able to fix it to their best ability, especially if they can't reproduce it themselves. :)

**Comment by arthurgps2** [comment] 2021-01-11 17:26
Sorry for taking so long.
I'm trying to play it on this page:
https://www.clickjogos.com.br/Jogos-online/Acao-e-Aventura/Flash-Sonic
Whenever I click on the "Play with Ruffle" button, I get this message
saying "Something went wrong."

Also now I just noticed this "view error details" button. These are the
details:


# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status
code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code
is not ok
```

# Player Info
Allows script access: false
Player type: Object
SWF URL:
https://img.clickjogos.com.br/dl/c/c47a2f5af40caae1efe5e7c9547579dd/src.swf
Param movie:
https://img.clickjogos.com.br/dl/c/c47a2f5af40caae1efe5e7c9547579dd/src.swf
Param allowScriptAccess: never
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]

# Page Info
Page URL:
https://www.clickjogos.com.br/Jogos-online/Acao-e-Aventura/Flash-Sonic

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 OPR/72.0.3815.459
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em sáb., 9 de jan. de 2021 às 01:10, Poopooracoocoo <
notifications@github.com> escreveu:

**Comment by Poopooracoocoo** [comment] 2021-01-12 03:36
Looks like an issue with how Ruffle is implemented on that site. Loading up the SWF on the Ruffle demo works fine.

**Comment by relrelb** [comment] 2021-01-26 21:43
Should be fixed by #2561.

**Comment by Poopooracoocoo** [comment] 2021-01-27 03:11
Click Jogos fixed it! 🎉
Mind closing this issue?

**Comment by Toad06** [comment] 2021-01-30 14:19
Closing as per above comment.

**Closed** 2021-01-30 14:19 UTC
