### ISSUE TITLE
Error on https://www.juegosjuegos.com/embed/papa-cupcakeria

### ISSUE THREAD

**Issue by joh23-vn** [ruffle-rs/ruffle#4147] opened 2021-04-26 21:55 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): unknown section code #0x87 @+18525
Error stack:
```
CompileError: WebAssembly.instantiate(): unknown section code #0x87 @+18525
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.juegosjuegos.com/embed/papa-cupcakeria

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-02
Channel: nightly
Built: 2021-02-02T00:21:23.909Z
Commit: 5783021d99477357a1d291d47fc0fd16082fbd98

**Comment by Poopooracoocoo** [comment] 2021-04-29 11:59
Duplicate of #4107

**Closed by Poopooracoocoo** 2021-04-29 11:59 UTC
Labels: duplicate
