### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#8488] opened 2022-11-06 09:19 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (http://www.freeworldgroup.com/ruffle/core.ruffle.c12672100878cba6a22e.js:1:6805)
    at std::sync::once::Once::call_once::{{closure}}::h5b3584428e2c6e9f (wasm://wasm/01817c06:wasm-function[1219]:0x2c7431)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01817c06:wasm-function[1496]:0x316b40)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2ad31bbb08635044 (wasm://wasm/01817c06:wasm-function[4905]:0x48aa22)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01817c06:wasm-function[3604]:0x4482ee)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01817c06:wasm-function[5126]:0x48f193)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/01817c06:wasm-function[4960]:0x48b994)
    at core::ops::function::FnOnce::call_once::hb4b16575678782a6 (wasm://wasm/01817c06:wasm-function[1105]:0x29c807)
    at ruffle_core::avm1::function::Executable::exec::h7e5ed1117c7e817b (wasm://wasm/01817c06:wasm-function[362]:0xdc68b)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h9a9a6510cccb34d5 (wasm://wasm/01817c06:wasm-function[1068]:0x28edcf)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm
SWF URL: http://www.freeworldgroup.com/games6/electricman2/electricman2hs_fwg.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-30
Channel: nightly
Built: 2022-10-30T00:16:05.457Z
Commit: ee52ce32908d9f50e52c707575c6d404745117dc
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3914404

**Comment by n0samu** [comment] 2022-11-06 17:56
Duplicate of #4932

**Closed by n0samu** 2022-11-06 17:56 UTC
Labels: duplicate, error-report
