### ISSUE TITLE
Error on https://mississippitalks.com/index.php?/ipsproarcade/playfull/16391-easter-island-td-normal/

### ISSUE THREAD

**Issue by Mississippitalks-com** [ruffle-rs/ruffle#2764] opened 2021-01-22 18:41 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://mississippitalks.com/applications/ruffle/ruffle.js:1:6333)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://mississippitalks.com/applications/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[1280]:0x263ca7)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://mississippitalks.com/applications/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[1548]:0x294bd2)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://mississippitalks.com/applications/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4312]:0x368af7)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://mississippitalks.com/applications/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[3310]:0x341daf)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://mississippitalks.com/applications/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[3919]:0x35e91d)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://mississippitalks.com/applications/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4655]:0x36e191)
    at rust_begin_unwind (https://mississippitalks.com/applications/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4529]:0x36c811)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://mississippitalks.com/applications/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4657]:0x36e1f5)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (https://mississippitalks.com/applications/ruffle/43f8e1e34e0629f740121b10aab750da.wasm:wasm-function[4000]:0x3611f4)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://mississippitalks.com/arcade/easterislandtdNormalv32Th.swf
Param movie: https://mississippitalks.com/arcade/easterislandtdNormalv32Th.swf
Param pluginspage: http://www.macromedia.com/go/getflashplayer/
Param bgcolor: #ffffff
Param quality: high
Param menu: true
Param wmode: direct
Param allowScriptAccess: always
Param play: true
Param loop: true
Param hasPriority: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://mississippitalks.com/index.php?/ipsproarcade/playfull/16391-easter-island-td-normal/
SWF URL: https://mississippitalks.com/arcade/easterislandtdNormalv32Th.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by torokati44** [comment] 2021-06-09 00:51
Essentially a duplicate of #2763.

**Closed by torokati44** 2021-06-09 00:51 UTC
