### ISSUE TITLE
[HomestarRunner.com Main Page #24] Blur filter doesn't properly cover the AVM1Buttons

### ISSUE THREAD

**Issue by TheGentleChainsaw** [ruffle-rs/ruffle#12200] opened 2023-07-21 02:03 UTC
### Describe the bug

- Official pages:
  - https://homestarrunner.com/main/24 (updated site with self-hosted Ruffle player, though it's currently out of date by almost two months)
  - https://old.homestarrunner.com/main24.html (old-style SWF embeds, no included player)
- Direct link to SWF file: https://old.homestarrunner.com/main24.swf

This one has long been known as one of the few Ruffle compatibility gaps in old H*R content. Now it's been mostly fixed with the recently-added blur filters, the main joke of the page actually comes across now, but there are still a couple of issues. The main one is that the buttons on the left aren't being blurred at all, even though they would be in Flash Player:
![image 1](https://github.com/ruffle-rs/ruffle/assets/96608266/674ec977-1934-4e82-bf25-a60040bab411)

~~Also, when trying to play this in an up-to-date web player, the blur effect is... just *way* off. The detail gets washed out far too much, and the radius of the blur effect gets clipped by what I'm guessing are the outside margins of the original objects underneath:~~ (fixed already, my browser was just using an outdated build)
![image 1](https://github.com/ruffle-rs/ruffle/assets/96608266/797e77a7-b0da-49ba-ab03-2c22d82092b4)

### Expected behavior

The blur effect should apply to the entire displayed screen ~~and shouldn't be clipped at its edges~~. For comparison, here's what it looks like in Flash Player:
![image](https://github.com/ruffle-rs/ruffle/assets/96608266/294e2644-81df-41d5-8f4b-fa7531362af6)
(Ignore the lack of top-bar buttons, those are provided by external SWFs that I can't easily load in Flash Player.)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Mozilla Firefox 115

**Comment by Lord-McSweeney** [comment] 2023-07-21 04:42
That clipping was fixed in a more recent version of Ruffle.
![chrome-extension___donbcfbmhbcapadipfkeojnmajbakjdc_player html_url=https%3A%2F%2Fold homestarrunner com%2Fmain24 swf](https://github.com/ruffle-rs/ruffle/assets/84632019/e5d093d1-9ecc-4425-942b-d7ffd4b62581)
(web extension page)

**Comment by n0samu** [comment] 2023-07-21 07:29
This happens because in Ruffle, setting `DisplayObject.filters` for an AVM1Button does not render the filter. Here is a minimal reproduction of the problem: [ButtonFilterAS2.zip](https://github.com/ruffle-rs/ruffle/files/12117545/ButtonFilterAS2.zip)
The problem does not occur for AVM2Button or for movie clips.

**Closed** 2023-07-25 12:20 UTC
Labels: bug, avm1, filter-effects
