### ISSUE TITLE
Error on https://www.gameflare.com/embed/pre-civilization-marble-age/

### ISSUE THREAD

**Issue by kylewithsty1e** [ruffle-rs/ruffle#14018] opened 2023-11-14 21:08 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://www.gameflare.com/emulators/ruffle/core.ruffle.5dcaa225af3bc049878c.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0ac237062e7987e0 (wasm://wasm/033f8df2:wasm-function[9988]:0x9cdb73)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/033f8df2:wasm-function[6557]:0x8cdb63)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/033f8df2:wasm-function[9785]:0x9c88da)
    at core::ops::function::Fn::call::h3af7d6d7e5bfc22d (wasm://wasm/033f8df2:wasm-function[6740]:0x8d8400)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h840aa012e740d34e (wasm://wasm/033f8df2:wasm-function[5409]:0x86992b)
    at <T as wgpu::context::DynContext>::device_create_texture::heb56d714c5118845 (wasm://wasm/033f8df2:wasm-function[7300]:0x908065)
    at wgpu::Device::create_texture::h4889909991fdc2bf (wasm://wasm/033f8df2:wasm-function[5564]:0x877de0)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::h04aa24ba4435cc20 (wasm://wasm/033f8df2:wasm-function[2025]:0x59b472)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::h85e9887155a94623 (wasm://wasm/033f8df2:wasm-function[1471]:0x49647b)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1809()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce MX130 (0x0000174D) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/pre-civilization-marble-age/
SWF URL: https://data.gameflare.com/games/7934/Qm7DbTq9VBoiZJ.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-14
Channel: nightly
Built: 2023-11-14T00:21:56.078Z
Commit: b196c8d1bcc2d691c61d8d78b17b5fd60e0234b8
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9733381

**Comment by MartySVK** [comment] 2023-11-14 22:11
duplicate of https://github.com/ruffle-rs/ruffle/issues/13946

**Closed** 2024-01-03 07:58 UTC
Labels: duplicate, error-report
