### ISSUE TITLE
Error on https://www.gameflare.com/embed/chibi-knight/

### ISSUE THREAD

**Issue by jacobcarter5550** [ruffle-rs/ruffle#6148] opened 2022-01-26 12:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.gameflare.com/emulators/ruffle/core.ruffle.14afbe2b2ea587f28d56.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::hc85ce564f2ea66ba (https://www.gameflare.com/emulators/ruffle/94c05bf8f8acf3a139e6.wasm:wasm-function[1030]:0x301984)
    at std::sync::once::Once::call_inner::h6fd514b461aaa35e (https://www.gameflare.com/emulators/ruffle/94c05bf8f8acf3a139e6.wasm:wasm-function[1163]:0x3346d0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he301baa1a5c81c58 (https://www.gameflare.com/emulators/ruffle/94c05bf8f8acf3a139e6.wasm:wasm-function[4677]:0x4d1345)
    at std::panicking::rust_panic_with_hook::h19d99b2b2597d628 (https://www.gameflare.com/emulators/ruffle/94c05bf8f8acf3a139e6.wasm:wasm-function[3186]:0x4869d5)
    at core::panicking::panic_fmt::hbc500cb2b2c8690c (https://www.gameflare.com/emulators/ruffle/94c05bf8f8acf3a139e6.wasm:wasm-function[4951]:0x4dd0d6)
    at core::panicking::panic::h7ae74ceab81e332c (https://www.gameflare.com/emulators/ruffle/94c05bf8f8acf3a139e6.wasm:wasm-function[4674]:0x4d0e6c)
    at core::ops::function::FnOnce::call_once::h21e86c081da96d39 (https://www.gameflare.com/emulators/ruffle/94c05bf8f8acf3a139e6.wasm:wasm-function[1064]:0x317046)
    at ruffle_core::avm1::function::Executable::exec::haca684796bbce4b5 (https://www.gameflare.com/emulators/ruffle/94c05bf8f8acf3a139e6.wasm:wasm-function[413]:0x155a8b)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hff87abb433d6f83f (https://www.gameflare.com/emulators/ruffle/94c05bf8f8acf3a139e6.wasm:wasm-function[623]:0x221a08)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/chibi-knight/
SWF URL: https://data.gameflare.com/games/6255/H8me4QU2dF0alM.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-17
Channel: nightly
Built: 2022-01-17T00:18:08.085Z
Commit: 059c1a34174a546521d1ebc32fd1411a079c2708
Is extension: false

**Comment by Poopooracoocoo** [comment] 2022-01-26 13:22
Duplicate of #3756

**Closed by Poopooracoocoo** 2022-01-26 13:22 UTC
Labels: duplicate, error-report
