### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/fwgknight2.htm

### ISSUE THREAD

**Issue by 2669531054** [ruffle-rs/ruffle#16402] opened 2024-05-21 11:30 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/display_object/container.rs:1032:22:
called `Option::unwrap()` on a `None` value
Error stack:
```
Error: panicked at core/src/display_object/container.rs:1032:22:
called `Option::unwrap()` on a `None` value
    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.cf8ab83f3b3a01c63ca2.js:1:74791)
    at ruffle_web.wasm.js_sys::Error::new::h69c04334b4f73f11 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[12748]:0x9f83e5)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::he3ea582d6a7092c3 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[10505]:0x9b1d80)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[6525]:0x8771d0)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[10254]:0x9aaa12)
    at ruffle_web.wasm.core::panicking::panic::hb157b525de3fe68d (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[9986]:0x9935d4)
    at ruffle_web.wasm.core::option::unwrap_failed::hb5bacfb0dd292085 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[12251]:0x9e9ad6)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once::h2b8e2323ebd5f554 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[1371]:0x3dde2e)
    at ruffle_web.wasm.ruffle_core::avm1::function::Executable::exec::hd0c54e95b189fe16 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[853]:0x18942d)
    at ruffle_web.wasm.ruffle_core::avm1::object::TObject::call_method::ha04e90661ebc67e9 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[3666]:0x702dfe)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3050 Laptop GPU (0x000025A2) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/fwgknight2.htm
SWF URL: http://www.freeworldgroup.com/games6/fwgknight2/fwgknight2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-05-21
Channel: nightly
Built: 2024-05-21T00:06:02.596Z
Commit: d8b8ffa4f3f37d266e3def3325c5a20147aa1eed
Is extension: false

# Metadata
width: 640
height: 420
frameRate: 36
numFrames: 5
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3039424

**Comment by n0samu** [comment] 2024-07-13 05:51
Duplicate of #14167

**Closed by n0samu** 2024-07-13 05:51 UTC
Labels: duplicate, avm1, error-report
