### ISSUE TITLE
Twister IceFun hangs on the start game button

### ISSUE THREAD

**Issue by EZGames69** [ruffle-rs/ruffle#13105] opened 2023-09-08 03:52 UTC
### Describe the bug

As soon as you press the start game button, the game just hangs on this screen for the rest of the time. 
![image](https://github.com/ruffle-rs/ruffle/assets/44628443/ed60ee57-a175-448f-adf5-173e288fe81d)

Tested using the 09-08-2023 nightly

### Expected behavior

The game should be going into the game after this screen but just hangs the whole time.  No idea if it needs a website spoof or something.

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment] 2023-09-08 04:10
ZIP:
[twister ice fun.zip](https://github.com/ruffle-rs/ruffle/files/12555388/twister.ice.fun.zip)

**Comment by n0samu** [comment] 2023-09-08 05:00
Duplicate of #6707

**Closed by n0samu** 2023-09-08 05:00 UTC
Labels: bug, duplicate
