### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm

### ISSUE THREAD

**Issue by WarriorTheWise** [ruffle-rs/ruffle#7981] opened 2022-09-14 16:02 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/core.ruffle.44ea0bb01ee08a0e0757.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::ha360d592741a73b3 (wasm://wasm/0178b726:wasm-function[1138]:0x2be549)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/0178b726:wasm-function[1439]:0x3142c9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h613b00154d20bc2b (wasm://wasm/0178b726:wasm-function[4836]:0x46fa4b)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/0178b726:wasm-function[3601]:0x437d78)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/0178b726:wasm-function[5023]:0x476149)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/0178b726:wasm-function[4921]:0x4711e0)
    at core::ops::function::FnOnce::call_once::h9baee3432cd92051 (wasm://wasm/0178b726:wasm-function[1083]:0x2b0751)
    at ruffle_core::avm1::function::Executable::exec::hdfddf9496055cb0e (wasm://wasm/0178b726:wasm-function[358]:0xe4f56)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h15e49bfbb24125b9 (wasm://wasm/0178b726:wasm-function[852]:0x25da92)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm
SWF URL: http://www.freeworldgroup.com/games6/electricman2/electricman2hs_fwg.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-14
Channel: nightly
Built: 2022-09-14T00:18:10.072Z
Commit: e08f8d47ab17d27b28997cd94b650dbfd58555d2
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3914404

**Comment by n0samu** [comment] 2022-09-14 21:17
Duplicate of #4932

**Closed by n0samu** 2022-09-14 21:17 UTC
Labels: duplicate, error-report
