### ISSUE TITLE
Error on https://h-flash.com/sexually-instructing-my-corner-masturbating-student-eng/

### ISSUE THREAD

**Issue by Nelore1712** [ruffle-rs/ruffle#9252] opened 2023-01-21 17:49 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/cmp.rs:860:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/cmp.rs:860:9
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://h-flash.com/data/ruffle/core.ruffle.b5d6ce968050f90fdce9.js:1:6507)
    at std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9 (wasm://wasm/018fcb8a:wasm-function[1102]:0x2aa466)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018fcb8a:wasm-function[1415]:0x31b27d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542 (wasm://wasm/018fcb8a:wasm-function[5033]:0x4b585e)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018fcb8a:wasm-function[3756]:0x471db6)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018fcb8a:wasm-function[5275]:0x4ba6a9)
    at core::panicking::panic::h0859aaac783261b2 (wasm://wasm/018fcb8a:wasm-function[5087]:0x4b6790)
    at ruffle_core::player::Player::update_drag::h04c63746577775cf (wasm://wasm/018fcb8a:wasm-function[1417]:0x31b9ab)
    at ruffle_core::player::Player::handle_event::h5d73f62bdb9313b3 (wasm://wasm/018fcb8a:wasm-function[329]:0x98f08)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hf3707dc316dc4dbb (wasm://wasm/018fcb8a:wasm-function[1228]:0x2cf68b)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://h-flash.com/sexually-instructing-my-corner-masturbating-student-eng/
SWF URL: https://h-flash.com/data/swf/data/jsk-studio/kadoona-eng/kado.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 13; Pixel 6a) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36
Platform: Linux armv8l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-21
Channel: nightly
Built: 2022-12-21T00:16:40.503Z
Commit: 5cf5c8d5e5d3b37a38cf133aa587b7f925612f21
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 175
swfVersion: 41
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 32659412

**Comment by n0samu** [comment] 2023-01-22 01:27
Duplicate of #8839. This problem has already been fixed by #9108. Please contact the website owner and ask them to update their copy of Ruffle.

**Closed by n0samu** 2023-01-22 01:27 UTC
Labels: duplicate, nsfw, error-report
