### ISSUE TITLE
Error on http://swordandsandals.top/swords-and-sandals-2-full-version/

### ISSUE THREAD

**Issue by Wojtekadamski** [ruffle-rs/ruffle#12838] opened 2023-08-18 23:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.6fe0bf29459fa15846ac.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h665574cf5fec7903 (wasm://wasm/02fe7e36:wasm-function[9263]:0x8f7712)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02fe7e36:wasm-function[6061]:0x7f62f6)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02fe7e36:wasm-function[9105]:0x8f3084)
    at core::result::unwrap_failed::h73809cc05a786e48 (wasm://wasm/02fe7e36:wasm-function[7210]:0x85f489)
    at <T as wgpu::context::DynContext>::device_create_texture::h5b2464cb548b6611 (wasm://wasm/02fe7e36:wasm-function[6742]:0x837974)
    at wgpu::Device::create_texture::ha286c02a2720991e (wasm://wasm/02fe7e36:wasm-function[5108]:0x79f485)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::hee8e884525248e48 (wasm://wasm/02fe7e36:wasm-function[4948]:0x790e7a)
    at ruffle_core::display_object::render_base::h0f8c4edc612514bc (wasm://wasm/02fe7e36:wasm-function[560]:0x107a1e)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h68f9402807ce9c12 (wasm://wasm/02fe7e36:wasm-function[6637]:0x829b83)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://swordandsandals.top/swords-and-sandals-2-full-version/
SWF URL: http://swordandsandals.top/wp-content/uploads/swords-and-sandals-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-18
Channel: nightly
Built: 2023-08-18T00:23:15.604Z
Commit: 96faa8c5cebe22ccdd0ae0b8883834313cb690e4
Is extension: false

# Metadata
width: 640
height: 420
frameRate: 30
numFrames: 277
swfVersion: 8
backgroundColor: #FFCC66
isActionScript3: false
uncompressedLength: 5282134

**Comment by torokati44** [comment] 2023-11-11 00:03
Basically a duplicate of #11852.

**Closed by torokati44** 2023-11-11 00:03 UTC
Labels: error-report
