### ISSUE TITLE
Error on https://www.tienganh123.com/tieng-anh-tre-em-theo-chu-de/764-ngay-le-halloween.html

### ISSUE THREAD

**Issue by HuuBinh2012** [ruffle-rs/ruffle#6677] opened 2022-04-11 02:04 UTC
# Error Info
Error name: TypeError
Error message: WebAssembly.instantiate(): Argument 0 must be a buffer source
Error stack:
```
TypeError: WebAssembly.instantiate(): Argument 0 must be a buffer source
    at chrome-extension://jkbpgegeblidoaogmhfbckoeblbdpfjj/dist/966.js:1:37472
    at n (chrome-extension://jkbpgegeblidoaogmhfbckoeblbdpfjj/dist/966.js:1:37555)
    at async chrome-extension://jkbpgegeblidoaogmhfbckoeblbdpfjj/dist/ruffle.js?id=60681606742:1:4816
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.tienganh123.com/tieng-anh-tre-em-theo-chu-de/764-ngay-le-halloween.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-02
Channel: nightly
Built: 2022-04-02T00:18:51.687Z
Commit: e06506c2b901ed6a5298437ee320f1371167cd61
Is extension: true

**Comment by HuuBinh2012** [comment] 2022-04-11 02:05
e06506c

**Comment by relrelb** [comment] 2022-04-11 05:54
Duplicate of #6676.

**Closed by relrelb** 2022-04-11 05:54 UTC
Labels: error-report
