### ISSUE TITLE
Error on https://archive.org/details/gemcraft-1716

### ISSUE THREAD

**Issue by ShadSterling** [ruffle-rs/ruffle#12017] opened 2023-07-12 20:57 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.1/src/backend/direct.rs:3019:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.1/src/backend/direct.rs:3019:5
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://cors.archive.org/cors/emularity_engine_v1/ruffle/core.ruffle.9a24273e0a1180f66c43.js:1:51428)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc123de34c3ab8e83 (wasm://wasm/02d23fce:wasm-function[8764]:0x860673)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02d23fce:wasm-function[5747]:0x774433)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02d23fce:wasm-function[8625]:0x85c1c3)
    at core::ops::function::Fn::call::h580ca25c5d5e9b73 (wasm://wasm/02d23fce:wasm-function[6068]:0x78feaf)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h8449a13af88d7f44 (wasm://wasm/02d23fce:wasm-function[4552]:0x709d86)
    at <T as wgpu::context::DynContext>::device_create_buffer::h2609fd0238aaa756 (wasm://wasm/02d23fce:wasm-function[6642]:0x7c14e9)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h561fa5ad182067f8 (wasm://wasm/02d23fce:wasm-function[1457]:0x43adb5)
    at core::cell::once::OnceCell<T>::get_or_try_init::hd9139c1fe5c53e7d (wasm://wasm/02d23fce:wasm-function[3572]:0x676cea)
    at ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::h15308afb45446ee6 (wasm://wasm/02d23fce:wasm-function[1314]:0x400034)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (ATI Technologies Inc., AMD Radeon Pro 5600M OpenGL Engine, OpenGL 4.1)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 16384, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1120, height: 768, depth_or_array_layers: 1 }

# Page Info
Page URL: https://archive.org/details/gemcraft-1716

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-08
Channel: nightly
Built: 2023-07-08T00:23:31.270Z
Commit: b38bd604dbe2051b7febd6e0c3435801beecfbed
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 5
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 4987275

**Comment by Lord-McSweeney** [comment] 2023-07-12 20:59
Duplicate of #12016.

**Closed by Lord-McSweeney** 2023-07-12 20:59 UTC
Labels: error-report, wgpu-oom
