### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm

### ISSUE THREAD

**Issue by finn522** [ruffle-rs/ruffle#5156] opened 2021-08-27 20:46 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/ruffle.js:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::hdc00d7da63128799 (http://www.freeworldgroup.com/ruffle/e112735cbb3920aa6a3c.wasm:wasm-function[917]:0x244cff)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (http://www.freeworldgroup.com/ruffle/e112735cbb3920aa6a3c.wasm:wasm-function[1173]:0x2a28ed)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h34a21969c4579926 (http://www.freeworldgroup.com/ruffle/e112735cbb3920aa6a3c.wasm:wasm-function[4038]:0x42e625)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (http://www.freeworldgroup.com/ruffle/e112735cbb3920aa6a3c.wasm:wasm-function[2907]:0x3c34e4)
    at rust_begin_unwind (http://www.freeworldgroup.com/ruffle/e112735cbb3920aa6a3c.wasm:wasm-function[4252]:0x434029)
    at core::panicking::panic_fmt::h1fea623755fffed7 (http://www.freeworldgroup.com/ruffle/e112735cbb3920aa6a3c.wasm:wasm-function[4408]:0x43adda)
    at core::panicking::panic::h38cac710b5048ca0 (http://www.freeworldgroup.com/ruffle/e112735cbb3920aa6a3c.wasm:wasm-function[4187]:0x431583)
    at core::ops::function::FnOnce::call_once::ha40e6113ced28e4c (http://www.freeworldgroup.com/ruffle/e112735cbb3920aa6a3c.wasm:wasm-function[891]:0x238556)
    at ruffle_core::avm1::function::Executable::exec::h6321fa6c8b3e93cb (http://www.freeworldgroup.com/ruffle/e112735cbb3920aa6a3c.wasm:wasm-function[385]:0xe74c4)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm
SWF URL: http://www.freeworldgroup.com/games6/electricman2/electricman2hs_fwg.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-26
Channel: nightly
Built: 2021-08-26T00:12:02.563Z
Commit: 0aed180da897f27827da41b1e2d8db5b4c486658
Is extension: false

**Comment by sombraguerrero** [comment] 2021-08-31 16:45
duplicate of #4932

**Closed** 2021-09-02 20:48 UTC
