### ISSUE TITLE
Error on https://www.sethh.net/games/swfloader.html

### ISSUE THREAD

**Issue by nick-avacado** [ruffle-rs/ruffle#13095] opened 2023-09-07 12:34 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://www.sethh.net/games/ruffle/core.ruffle.2589a1776d37dadad80b.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h665574cf5fec7903 (wasm://wasm/02fe6fae:wasm-function[9263]:0x8f7370)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02fe6fae:wasm-function[6062]:0x7f64e0)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02fe6fae:wasm-function[9105]:0x8f2ce2)
    at core::ops::function::Fn::call::hfff022dcf68489d3 (wasm://wasm/02fe6fae:wasm-function[6741]:0x836448)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::hdaac7a9dec0bc1a6 (wasm://wasm/02fe6fae:wasm-function[4842]:0x75a3a1)
    at wgpu::backend::direct::Context::handle_error::hdc3e87d7bbbb00e9 (wasm://wasm/02fe6fae:wasm-function[2597]:0x5cb99c)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h5512ede0afeb509d (wasm://wasm/02fe6fae:wasm-function[6651]:0x82fa51)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h9525bd83d550f052 (wasm://wasm/02fe6fae:wasm-function[5679]:0x7d9f95)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h14058df32375850a (wasm://wasm/02fe6fae:wasm-function[1650]:0x485fc8)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.models::LobbySoldier/swapToSprite()
    at swordGame.models::LobbySoldier/walkCustomer()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.sethh.net/games/swfloader.html?title=Jacksmith&swf=papalouie%2Fjacksmith.swf
SWF URL: https://www.sethh.net/games/assets/papalouie/jacksmith.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-17
Channel: nightly
Built: 2023-08-17T00:20:13.730Z
Commit: f00671e9cca2fdf395ecf0c26873e50f7efd74cc
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9363111

**Comment by evilpie** [comment] 2024-04-09 15:24
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:24 UTC
Labels: render-wgpu, error-report
