### ISSUE TITLE
Error on https://www.jogos360.com.br/electricman_2.html

### ISSUE THREAD

**Issue by lauranha** [ruffle-rs/ruffle#6474] opened 2022-03-17 17:44 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.f5e16f52204d9499c76d.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::h8cc59a0b8a1b03e2 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.17/6eb258805834d3c235ef.wasm:wasm-function[1023]:0x2c3c5c)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.17/6eb258805834d3c235ef.wasm:wasm-function[1457]:0x330fa0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haa76f48d1b3c2435 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.17/6eb258805834d3c235ef.wasm:wasm-function[4908]:0x4827fd)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.17/6eb258805834d3c235ef.wasm:wasm-function[3229]:0x42594c)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.17/6eb258805834d3c235ef.wasm:wasm-function[5191]:0x48e899)
    at core::panicking::panic::h5d6906e2c1099660 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.17/6eb258805834d3c235ef.wasm:wasm-function[4905]:0x482324)
    at core::ops::function::FnOnce::call_once::hd40a0ab4006ca041 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.17/6eb258805834d3c235ef.wasm:wasm-function[1109]:0x2d9eda)
    at ruffle_core::avm1::function::Executable::exec::h34f53eabf17bd49f (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.17/6eb258805834d3c235ef.wasm:wasm-function[391]:0x11c595)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hdac537d2f3ea07cf (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.17/6eb258805834d3c235ef.wasm:wasm-function[431]:0x1565a8)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.jogos360.com.br/electricman_2.html
SWF URL: https://cdn.jogos360.com.br/files/games/el/ec/electricman-2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-17
Channel: nightly
Built: 2022-03-17T00:14:21.617Z
Commit: 50bdb4091434753016950707f7ace5f24df70989
Is extension: false

**Comment by relrelb** [comment] 2022-03-17 18:00
Duplicate of #4932.

**Closed by relrelb** 2022-03-17 18:00 UTC
Labels: error-report
