### ISSUE TITLE
Error on https://freeonlinemahjonggames.net/warmahjong.html

### ISSUE THREAD

**Issue by Lady-Marianne** [ruffle-rs/ruffle#6826] opened 2022-04-29 09:37 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:493:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:493:50
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://freeonlinemahjonggames.net/ruffle/ruffle.js:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::h12e3ca43ae762b16 (https://freeonlinemahjonggames.net/ruffle/c0edfb6cff7640dcfc70.wasm:wasm-function[900]:0x240987)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (https://freeonlinemahjonggames.net/ruffle/c0edfb6cff7640dcfc70.wasm:wasm-function[1144]:0x29a627)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc0e91a309058334a (https://freeonlinemahjonggames.net/ruffle/c0edfb6cff7640dcfc70.wasm:wasm-function[4027]:0x428d5f)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (https://freeonlinemahjonggames.net/ruffle/c0edfb6cff7640dcfc70.wasm:wasm-function[2900]:0x3be383)
    at rust_begin_unwind (https://freeonlinemahjonggames.net/ruffle/c0edfb6cff7640dcfc70.wasm:wasm-function[4243]:0x42e84f)
    at core::panicking::panic_fmt::h1fea623755fffed7 (https://freeonlinemahjonggames.net/ruffle/c0edfb6cff7640dcfc70.wasm:wasm-function[4399]:0x435677)
    at core::result::unwrap_failed::he87c4da48746e896 (https://freeonlinemahjonggames.net/ruffle/c0edfb6cff7640dcfc70.wasm:wasm-function[3571]:0x416120)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h039428097eb75edb (https://freeonlinemahjonggames.net/ruffle/c0edfb6cff7640dcfc70.wasm:wasm-function[642]:0x1ba881)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::he7f1d8d949e07ec4 (https://freeonlinemahjonggames.net/ruffle/c0edfb6cff7640dcfc70.wasm:wasm-function[2246]:0x36d609)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freeonlinemahjonggames.net/warmahjong.html
SWF URL: https://freeonlinemahjonggames.net/games/war-mahjong.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-23
Channel: nightly
Built: 2021-08-23T00:10:32.198Z
Commit: 2f07363aa7df1157f3ae0634af1fdf524920ec0c
Is extension: false

**Comment by Herschel** [comment] 2022-04-29 16:12
Dupe of #1905.

**Closed by Herschel** 2022-04-29 16:12 UTC
