### ISSUE TITLE
Save Windows Ruffle with swf file as exe file like Flash Projector

### ISSUE THREAD

**Issue by FrederiqueLesne** [ruffle-rs/ruffle#18677] opened 2024-11-20 03:01 UTC
Develop the code to allow a user to save a Windows 64 Ruffle with an SWF file as an exe file so it can be distributed like a game. This would allow users to create exe files that would show their swf content when started on another computer just as the Flash Projector did. It would also be great to do the same thing with the Mac desktop version of Ruffle so users could save their Ruffle + SWF file as a Mac application. In both cases it would be super fantastic if the user could "sign" the production as an Apple or Microsoft app developer.

**Comment by Lord-McSweeney** [comment] 2024-11-20 03:09
Duplicate of #4754

**Closed by Lord-McSweeney** 2024-11-20 03:09 UTC
Labels: duplicate, enhancement

**Comment by Lord-McSweeney** [comment] 2024-11-20 03:10
If you'd like you can add the feature to also be able to sign the exe as a comment on #4754

**Comment by FrederiqueLesne** [comment] 2024-11-20 03:22
It may be a duplicate and I'm sorry I missed it when I searched. But it would be a really useful addition to Ruffle and perhaps raising the issue again will encourage a brilliant coder to pitch in and do it.
