### ISSUE TITLE
Error on https://www.juegosarea.com/electricman-2.html

### ISSUE THREAD

**Issue by juanignaciomilo** [ruffle-rs/ruffle#8291] opened 2022-10-14 23:34 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.166543534d0d6de8f27f.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::hf9ee3cf8881ab9cc (wasm://wasm/01800c06:wasm-function[1030]:0x2a119d)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01800c06:wasm-function[1498]:0x327c9b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e53a26a8ce616de (wasm://wasm/01800c06:wasm-function[4930]:0x4868ea)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01800c06:wasm-function[3625]:0x444699)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01800c06:wasm-function[5121]:0x48a63c)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/01800c06:wasm-function[4985]:0x48785c)
    at core::ops::function::FnOnce::call_once::h091fd8f8c21617a7 (wasm://wasm/01800c06:wasm-function[1130]:0x2c1b89)
    at ruffle_core::avm1::function::Executable::exec::hd32a15aff1d93747 (wasm://wasm/01800c06:wasm-function[366]:0xfdbe3)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hddf815c9794947c7 (wasm://wasm/01800c06:wasm-function[407]:0x1352e9)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://www.juegosarea.com/electricman-2.html
SWF URL: https://cdn.juegosarea.com/files/games/el/ec/electricman-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-14
Channel: nightly
Built: 2022-10-14T00:22:21.438Z
Commit: b0b0e55c240e7d505d1ee64f61764de554885e5f
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by juanignaciomilo** [comment] 2022-10-14 23:34
buuuuu..... bad play

**Comment by n0samu** [comment] 2022-10-15 05:41
Duplicate of #4932

**Closed by n0samu** 2022-10-15 05:41 UTC
Labels: duplicate, error-report
