### ISSUE TITLE
Error on https://f.kbhgames.com/RS/game.php

### ISSUE THREAD

**Issue by Fritzmeinzer** [ruffle-rs/ruffle#6459] opened 2022-03-14 20:57 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://f.kbhgames.com/RS/asset/core.ruffle.cfafeead7fa4cdb619a5.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::h04c6018a30aae0b2 (wasm://wasm/017752a6:wasm-function[1019]:0x2c1212)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (wasm://wasm/017752a6:wasm-function[1458]:0x32fa13)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h629785d4908f37da (wasm://wasm/017752a6:wasm-function[4925]:0x48459f)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (wasm://wasm/017752a6:wasm-function[3240]:0x426969)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (wasm://wasm/017752a6:wasm-function[5213]:0x4906ea)
    at core::panicking::panic::h5d6906e2c1099660 (wasm://wasm/017752a6:wasm-function[4922]:0x4840c6)
    at core::ops::function::FnOnce::call_once::hccd13e3d375a8a6e (wasm://wasm/017752a6:wasm-function[1106]:0x2d79a7)
    at ruffle_core::avm1::function::Executable::exec::h79701af978203eb9 (wasm://wasm/017752a6:wasm-function[385]:0x10dba6)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hcdf54ba60d7772d4 (wasm://wasm/017752a6:wasm-function[433]:0x158f58)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://f.kbhgames.com/RS/game.php?r=//f.kbhgames.com/2018/swf/electricman2hs.swf&w=640&h=400
SWF URL: https://f.kbhgames.com/2018/swf/electricman2hs.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14469.41.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.57 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-02
Channel: nightly
Built: 2022-03-02T00:16:18.285Z
Commit: cbbdb7baa94e0996fd8696976a2fa3e1151c16f9
Is extension: false

**Comment by relrelb** [comment] 2022-03-14 21:05
Duplicate of #4932.

**Closed by relrelb** 2022-03-14 21:05 UTC
Labels: error-report
