### ISSUE TITLE
Error on https://www.panfu.us/play

### ISSUE THREAD

**Issue by Pamm111** [ruffle-rs/ruffle#18331] opened 2024-10-20 17:21 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/sync/mutex/no_threads.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2024.10.20/core.ruffle.c58867a007ff7bc79629.js:1:83434
wasm-stub@[wasm code]
ruffle_web.wasm.wasm-function[js_sys::Error::new::h6fac2ed5467ff7fa]@[wasm code]
ruffle_web.wasm.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hc0b3dd56841d0f47]@[wasm code]
ruffle_web.wasm.wasm-function[std::panicking::rust_panic_with_hook::he5c089ac7305193e]@[wasm code]
ruffle_web.wasm.wasm-function[core::panicking::panic_fmt::hdc8d2d914c0710e4]@[wasm code]
ruffle_web.wasm.wasm-function[core::panicking::assert_failed_inner::hac6df1fbe8940f48]@[wasm code]
ruffle_web.wasm.wasm-function[core::panicking::assert_failed::hb9538eb8ab2c7e62]@[wasm code]
ruffle_web.wasm.wasm-function[ruffle_core::loader::Loader::load_url_loader::{{closure}}::hd31302209832d71f]@[wasm code]
ruffle_web.wasm.wasm-function[<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hfc176a67356abd61]@[wasm code]
ruffle_web.wasm.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::hc36fc86a22c184f3]@[wasm code]
ruffle_web.wasm.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb2cce2a179e540a7]@[wasm code]
ruffle_web.wasm.wasm-function[closure7383 externref shim]@[wasm code]
wasm-stub@[native code]
P@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2024.10.20/core.ruffle.c58867a007ff7bc79629.js:1:3772
c@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2024.10.20/core.ruffle.c58867a007ff7bc79629.js:1:2836
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Apple GPU"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: best
Surface samples: 4
Surface size: (1544, 960, 1)
Player type: Object
SWF URL: https://www.panfu.us/flashclient-20241007181251/Panfu.swf
Param quality: best
Param menu: false
Param base: https://www.panfu.us/flashclient-20241007181251/
Param allowScriptAccess: always
Param wmode: transparent
Param flashvars: infoServer=https://info.panfu.us/gateway/amf/&lang=EN&sessionId=2146515590&mode=production
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.panfu.us/play
SWF URL: https://www.panfu.us/flashclient-20241007181251/Panfu.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-10-20
Channel: nightly
Built: 2024-10-20T00:06:42.325Z
Commit: e353fdc1c3e47939807e1d9b109050ed68ca5d62
Is extension: false

# Metadata
width: 772
height: 480
frameRate: 24
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 745926

**Comment by evilpie** [comment] 2024-10-22 12:59
Duplicate of #18326

**Closed by evilpie** 2024-10-22 12:59 UTC
Labels: error-report
