### ISSUE TITLE
Error on https://www.izzygames.com/electricman-2-t2305.html

### ISSUE THREAD

**Issue by Heriagustinos** [ruffle-rs/ruffle#7226] opened 2022-06-15 12:32 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.spiele-umsonst.de/ruffle/core.ruffle.3b64b24078093e7563da.js:1:7024)
    at std::sync::once::Once::call_once::{{closure}}::h2b3586a1c348e776 (https://www.spiele-umsonst.de/ruffle/0d3c79f331e54b6385be.wasm:wasm-function[1182]:0x2ae273)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://www.spiele-umsonst.de/ruffle/0d3c79f331e54b6385be.wasm:wasm-function[1406]:0x2e9848)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0e8f59b7c29e471d (https://www.spiele-umsonst.de/ruffle/0d3c79f331e54b6385be.wasm:wasm-function[4752]:0x4390a3)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://www.spiele-umsonst.de/ruffle/0d3c79f331e54b6385be.wasm:wasm-function[3140]:0x3dd913)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://www.spiele-umsonst.de/ruffle/0d3c79f331e54b6385be.wasm:wasm-function[4935]:0x43efca)
    at core::panicking::panic::hc28e7cc2aa792341 (https://www.spiele-umsonst.de/ruffle/0d3c79f331e54b6385be.wasm:wasm-function[4845]:0x43b0fd)
    at core::ops::function::FnOnce::call_once::h590cc274d810cad1 (https://www.spiele-umsonst.de/ruffle/0d3c79f331e54b6385be.wasm:wasm-function[1047]:0x286a3f)
    at ruffle_core::avm1::function::Executable::exec::hb7f77c6ff1c4ab01 (https://www.spiele-umsonst.de/ruffle/0d3c79f331e54b6385be.wasm:wasm-function[358]:0xca7a5)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hfe3077a0315fbbfe (https://www.spiele-umsonst.de/ruffle/0d3c79f331e54b6385be.wasm:wasm-function[537]:0x192c55)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.izzygames.com/electricman-2-t2305.html?gclid=EAIaIQobChMIxKGj6rmv-AIVlX4rCh1TLQpUEAAYASAAEgINcvD_BwE
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-30
Channel: nightly
Built: 2022-05-30T00:15:27.924Z
Commit: ec23a64a13041ae46a370d5516f961c12999d41d
Is extension: false

**Comment by relrelb** [comment] 2022-06-15 13:55
Duplicate of #4932.

**Closed by relrelb** 2022-06-15 13:55 UTC
Labels: error-report
