### ISSUE TITLE
Error on https://armorgames.com/play/5885/castaway

### ISSUE THREAD

**Issue by Kozzy-x** [ruffle-rs/ruffle#8058] opened 2022-09-23 13:47 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:1001:22
Error stack:
```
@https://agi.armorgames.com/ruffle/core.ruffle.6ab8bedfef797f7ebf93.js:1:5813
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hc7e1e9ccae1dc751]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h00971925aa1adad3]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::heaafb58166fe27c7]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h84feca33bd4bd229]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hc171d095bc4a492d]@[wasm code]
<?>.wasm-function[core::result::unwrap_failed::h68ab818eb89182b6]@[wasm code]
<?>.wasm-function[ruffle_core::bitmap::bitmap_data::BitmapData::draw::hc7b7f287487460ed]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::globals::bitmap_data::draw::hb54682cb84e6552d]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::he45fc3033712f2de]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7c0fd3dcbca5e586]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h71dcb8aee5af3555]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::he45fc3033712f2de]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7c0fd3dcbca5e586]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h71dcb8aee5af3555]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::he45fc3033712f2de]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7c0fd3dcbca5e586]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h71dcb8aee5af3555]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::hcbe115e2e3cc0140]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::h4ad92288360b3992]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h53edd6756d5bebd4]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hb27ea9ce8c471107]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h8f9fa9dd1a72e6bf]@[wasm code]
wasm-stub@[native code]
R@https://agi.armorgames.com/ruffle/core.ruffle.6ab8bedfef797f7ebf93.js:1:2732
c@https://agi.armorgames.com/ruffle/core.ruffle.6ab8bedfef797f7ebf93.js:1:2485
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://armorgames.com/play/5885/castaway
SWF URL: https://cache.armorgames.com/files/games/castaway-5885.swf?v=1373587523

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-12
Channel: nightly
Built: 2022-09-12T00:14:33.190Z
Commit: 474fd7fa8f74cabf40e7d091ac8e847dffd2814e
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 5
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 7984791

**Comment by Kozzy-x** [comment] 2022-09-23 13:49
The game Castaway is having flash issues.

**Comment by n0samu** [comment] 2022-09-23 23:10
Duplicate of #8016

**Closed by n0samu** 2022-09-23 23:10 UTC
Labels: duplicate, error-report
