### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by Kobe1987** [ruffle-rs/ruffle#12104] opened 2023-07-17 01:14 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he4e551a70a6b726d (wasm://wasm/02ef8b06:wasm-function[9059]:0x8c763f)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02ef8b06:wasm-function[5936]:0x7ca1ae)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02ef8b06:wasm-function[8897]:0x8c29f5)
    at core::panicking::panic::h42080e1e32ba4b73 (wasm://wasm/02ef8b06:wasm-function[8538]:0x8b2a82)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h31d4563c76476606 (wasm://wasm/02ef8b06:wasm-function[657]:0x1ddb35)
    at ruffle_core::loader::Loader::preload_tick::h248bbd804b66b5a0 (wasm://wasm/02ef8b06:wasm-function[1639]:0x467fbd)
    at ruffle_web::Ruffle::tick::hef5fd20aa09bf6b9 (wasm://wasm/02ef8b06:wasm-function[747]:0x24e2f4)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hdde492e120eadae4 (wasm://wasm/02ef8b06:wasm-function[10840]:0x906677)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::he71c42a52ee83398 (wasm://wasm/02ef8b06:wasm-function[9698]:0x8e44bc)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA Quadro P600 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=700&sp=0&questionSet=&r=6957777&&width=640&height=500&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-16
Channel: nightly
Built: 2023-07-16T00:22:13.709Z
Commit: cd2d01bf6f2565e1aa442da671ca7e27ed186629
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by torokati44** [comment] 2023-07-17 07:52
Duplicate of #12103.

**Closed by torokati44** 2023-07-17 07:52 UTC
Labels: error-report
