### ISSUE TITLE
Hot Dog Bush - Unable to operate

### ISSUE THREAD

**Issue by olux997** [ruffle-rs/ruffle#11778] opened 2023-06-28 15:00 UTC
### Describe the bug

Hot Dog Bush - Unable to operate

Work done:
<img width="350" alt="hotdog-bush-work" src="https://github.com/ruffle-rs/ruffle/assets/11493572/ac0c15f4-f10a-4ce8-83f5-9411f191f52b">

Ruffle : 2023-06-21
<img width="350" alt="hotdog-bush" src="https://github.com/ruffle-rs/ruffle/assets/11493572/d05dae21-3c4a-4234-b3b0-13fd28b4fdbc">

swf URL : 
https://www.gameflare.com/online-game/hotdog-bush/

### Expected behavior

Hot Dog Bush - Unable to operate

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Google Chrome 64bit,114.0.5735.134

### Additional information

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/hotdog-bush/
SWF URL: https://data.gameflare.com/games/14/1y73noB7bPXqs7.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-21
Channel: nightly
Built: 2023-06-21T00:19:43.730Z
Commit: b3c40ecda107ee33cbc44868fcd7dfdbdc634775
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 13
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3470924

**Comment by Lord-McSweeney** [comment] 2023-06-28 15:05
Interestingly, restarting the first day makes it work fine.

**Comment by waspennator** [comment] 2023-06-28 15:52
Duplicate of #4352

**Closed** 2023-06-28 22:55 UTC
Labels: bug, avm1
