### ISSUE TITLE
Error on http://www.hackedonlinegames.com/game/2240/ancient-planet

### ISSUE THREAD

**Issue by ghost** [ruffle-rs/ruffle#14030] opened 2023-11-15 22:16 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Error matching ShaderStages(NONE | FRAGMENT) shader requirements against the pipeline
    Location[1] is provided by the previous stage output but is not consumed as input by this stage.

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.0/src/backend/direct.rs:3019:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Error matching ShaderStages(NONE | FRAGMENT) shader requirements against the pipeline
    Location[1] is provided by the previous stage output but is not consumed as input by this stage.

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.0/src/backend/direct.rs:3019:5
    at W.n.wbg.__wbg_new_87297f22973157c8 (http://www.hackedonlinegames.com/applications/gameportal/js/ruffle-nightly-2023_05_24-web-selfhosted/core.ruffle.aeaca10e31ad891978a3.js:1:50966)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hafc7beb469c6cb04 (wasm://wasm/02c3cb9a:wasm-function[8617]:0x8309af)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c3cb9a:wasm-function[5612]:0x753a1a)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c3cb9a:wasm-function[8466]:0x82bd4a)
    at core::ops::function::Fn::call::h83da12931ee08b01 (wasm://wasm/02c3cb9a:wasm-function[5946]:0x7691a4)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h27ddee42d4a7dd38 (wasm://wasm/02c3cb9a:wasm-function[4428]:0x6ef14e)
    at <T as wgpu::context::DynContext>::device_create_render_pipeline::hf56930464c49d996 (wasm://wasm/02c3cb9a:wasm-function[7345]:0x7dacd8)
    at wgpu::Device::create_render_pipeline::hed6349f4daa7770d (wasm://wasm/02c3cb9a:wasm-function[5943]:0x768f06)
    at <ruffle_render_wgpu::context3d::WgpuContext3D as ruffle_render::backend::Context3D>::process_command::h54e9288cf0147e56 (wasm://wasm/02c3cb9a:wasm-function[531]:0xb3a99)
    at ruffle_core::avm2::globals::flash::display3D::context_3d::draw_triangles::hc5d35a0b24695efe (wasm://wasm/02c3cb9a:wasm-function[2375]:0x54f9f5)
```
AVM2 stack:
```
    at flash.display3D::Context3D/flash::display3D::Context3D::drawTriangles()
    at starling.display.materials::StandardMaterial/drawTriangles()
    at starling.display.graphics::Graphic/render()
    at starling.display::DisplayObjectContainer/render()
    at starling.display::DisplayObjectContainer/render()
    at starling.display::Sprite/render()
    at starling.display::DisplayObjectContainer/render()
    at starling.display::Sprite/render()
    at starling.display::DisplayObjectContainer/render()
    at starling.core::Starling/render()
    at starling.core::Starling/nextFrame()
    at starling.core::Starling/onEnterFrame()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: medium
Surface samples: 2
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://www.hackedonlinegames.com/game/2240/ancient-planet
SWF URL: http://cache.hackedonlinegames.com/uploads/games/files/252/X0TKS7GRGG08.swf?version=7

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-24
Channel: nightly
Built: 2023-05-24T00:22:28.395Z
Commit: 358beabf5a49807bafd0122a73ff62514ceb4b9a
Is extension: false

# Metadata
width: 768
height: 610
frameRate: 60
numFrames: 2
swfVersion: 16
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 22208924

**Comment by danielhjacobs** [comment] 2024-07-15 14:58
Duplicate of #10878

**Closed by danielhjacobs** 2024-07-15 14:58 UTC
Labels: error-report
