### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by basebrataspie1996** [ruffle-rs/ruffle#17815] opened 2024-09-08 02:25 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.


    at n.wbg.__wbg_new_796382978dfd4fb0 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.c88a82c0f3a39863189d.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::ha4990c08e4b8c418 (wasm://wasm/ruffle_web.wasm-031d4f92:wasm-function[12699]:0x97b9c3)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h9398b7d48db47bc6 (wasm://wasm/ruffle_web.wasm-031d4f92:wasm-function[9769]:0x90a47e)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-031d4f92:wasm-function[6264]:0x7eb7cb)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-031d4f92:wasm-function[10181]:0x926250)
    at ruffle_web.wasm.core::ops::function::Fn::call::h096d13d1829bc87a (wasm://wasm/ruffle_web.wasm-031d4f92:wasm-function[6590]:0x80f292)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::h529171fa57417315 (wasm://wasm/ruffle_web.wasm-031d4f92:wasm-function[7503]:0x8610a7)
    at ruffle_web.wasm.<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hb6a05bd04c14413f (wasm://wasm/ruffle_web.wasm-031d4f92:wasm-function[1853]:0x4b9e79)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::target::CommandTarget::new::haf270aeb72690035 (wasm://wasm/ruffle_web.wasm-031d4f92:wasm-function[1144]:0x3162af)
    at ruffle_web.wasm.ruffle_render_wgpu::surface::Surface::draw_commands::h0fb849c78c1c0c42 (wasm://wasm/ruffle_web.wasm-031d4f92:wasm-function[887]:0x1a8ff9)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 (0x00003EA0) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1725509728%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F489000%2F489716_PitSweeper_NG.swf%3F1238716380%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2266dd03f6bcb92%22%2C%22NewgroundsAPI_SessionID%22%3A%22qnpLqmAy9LVtp3gmzeIy53158b240cc82263a1919e9e419c710410239187YLPN%22%2C%22NewgroundsAPI_UserName%22%3A%22basebrataspie96%22%2C%22NewgroundsAPI_UserID%22%3A23609367%2C%22ng_username%22%3A%22basebrataspie96%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F489000%2Fflash_489716.png%3Ff1364575995%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/489000/489716_PitSweeper_NG.swf?1238716380

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-05
Channel: nightly
Built: 2024-09-05T00:05:37.479Z
Commit: f538f67a17a4d26db78528e2276a2c7b8d0c729c
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 3
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 1372282

**Comment by torokati44** [comment] 2024-09-10 10:31
Duplicate of https://github.com/ruffle-rs/ruffle/issues/17813.

**Closed by torokati44** 2024-09-10 10:31 UTC
Labels: error-report, wgpu-oom
