### ISSUE TITLE
Crash Bandicoot - Background Problem

### ISSUE THREAD

**Issue by barisyild** [ruffle-rs/ruffle#378] opened 2020-02-10 03:52 UTC
Ruffle:
![image](https://user-images.githubusercontent.com/25794892/74119703-acf1d780-4bd1-11ea-8cd8-189009c593e3.png)

Flash:
![image](https://user-images.githubusercontent.com/25794892/74119761-e6c2de00-4bd1-11ea-927e-2dda41860c11.png)

**Comment by Herschel** [comment] 2020-02-13 01:56
SWF:
http://www.dan-dare.info/org/FreeFun/Games/More/pjinns_crash_bandicoot.swf

Caused by #26, closing in favor of that bug

**Closed by Herschel** 2020-02-13 01:56 UTC
