### ISSUE TITLE
Error on https://game70421.konggames.com/games/BoMToons/chibi-knight/frame/5b3718f9-d869-4146-b8ad-776b1382d232/

### ISSUE THREAD

**Issue by EricAlves790** [ruffle-rs/ruffle#9453] opened 2023-02-07 15:45 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:838:32
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:838:32
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.db3735ad129c601c6f82.js:1:5412)
    at std::sync::once::Once::call_once::{{closure}}::hfb695c8f07f1e72c (wasm://wasm/027ca67e:wasm-function[1921]:0x493e07)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027ca67e:wasm-function[1856]:0x48283c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc93fb6a80fc6ff8b (wasm://wasm/027ca67e:wasm-function[7144]:0x768468)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027ca67e:wasm-function[5044]:0x6c399a)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027ca67e:wasm-function[7453]:0x7770ef)
    at core::panicking::panic::h364c37174a08a6a4 (wasm://wasm/027ca67e:wasm-function[6868]:0x743f3c)
    at core::ops::function::FnOnce::call_once::h209504342ab47a84 (wasm://wasm/027ca67e:wasm-function[815]:0x290ab0)
    at ruffle_core::avm1::function::Executable::exec::h7f1f893e2a617bbc (wasm://wasm/027ca67e:wasm-function[585]:0x19964e)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h4a6992c6c67e0ecd (wasm://wasm/027ca67e:wasm-function[1386]:0x3aef90)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game70421.konggames.com/games/BoMToons/chibi-knight/frame/5b3718f9-d869-4146-b8ad-776b1382d232/?kongregate_host=www.kongregate.com
SWF URL: https://game70421.konggames.com/gamez/0007/0421/live/beastgame_kong.swf?kongregate_game_version=1265086391

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-07
Channel: nightly
Built: 2023-02-07T00:21:37.543Z
Commit: 48f4df51a51cc1e2e009b2212eaa14459488a1e4
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 25
numFrames: 7
swfVersion: 9
backgroundColor: #666666
isActionScript3: false
uncompressedLength: 7891171

**Comment by Lord-McSweeney** [comment] 2023-02-08 00:45
Duplicate of #3756.

**Closed** 2023-02-08 00:45 UTC
Labels: error-report
