### ISSUE TITLE
Error on https://www.horseracingpark.com/liveracing/startrace.aspx

### ISSUE THREAD

**Issue by tmayo2462** [ruffle-rs/ruffle#4199] opened 2021-05-01 23:06 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:499:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:499:50
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.horseracingpark.com/javascript/ruffle/ruffle.js:1:6834)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://www.horseracingpark.com/javascript/ruffle/0fbea3a383da8dbb8b8d.wasm:wasm-function[820]:0x220a30)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://www.horseracingpark.com/javascript/ruffle/0fbea3a383da8dbb8b8d.wasm:wasm-function[1219]:0x2a4308)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://www.horseracingpark.com/javascript/ruffle/0fbea3a383da8dbb8b8d.wasm:wasm-function[3683]:0x42da74)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://www.horseracingpark.com/javascript/ruffle/0fbea3a383da8dbb8b8d.wasm:wasm-function[2678]:0x392b4c)
    at rust_begin_unwind (https://www.horseracingpark.com/javascript/ruffle/0fbea3a383da8dbb8b8d.wasm:wasm-function[3884]:0x432feb)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://www.horseracingpark.com/javascript/ruffle/0fbea3a383da8dbb8b8d.wasm:wasm-function[3992]:0x435d8e)
    at core::option::expect_none_failed::h203584ddbc785ca2 (https://www.horseracingpark.com/javascript/ruffle/0fbea3a383da8dbb8b8d.wasm:wasm-function[3313]:0x41e8e1)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::ha0f8d775218e7508 (https://www.horseracingpark.com/javascript/ruffle/0fbea3a383da8dbb8b8d.wasm:wasm-function[523]:0x16aa37)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::replace_shape::h56a65b76196007bb (https://www.horseracingpark.com/javascript/ruffle/0fbea3a383da8dbb8b8d.wasm:wasm-function[1746]:0x3188c6)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: liveracing293.swf?x=17618157
Param movie: liveracing291.swf?x=17618157
Param quality: high
Param bgcolor: #FFFFFF
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.horseracingpark.com/liveracing/startrace.aspx?raceid=17618157
SWF URL: https://www.horseracingpark.com/liveracing/liveracing293.swf?x=17618157

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-23
Channel: nightly
Built: 2021-04-23T00:16:00.658Z
Commit: f0bdb57996b6fdc200eaa7af60c9165dc78040fb

**Comment by torokati44** [comment] 2021-06-09 00:38
Duplicate of #4264.

**Closed by torokati44** 2021-06-09 00:38 UTC
