### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by amiramte** [ruffle-rs/ruffle#6323] opened 2022-02-20 14:52 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/cmp.rs:816:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/cmp.rs:816:9
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/966.index.js:1:7291)
    at std::sync::once::Once::call_once::{{closure}}::h241de8037c789067 (https://ruffle.rs/demo/593c7bba763056fd5ed9.wasm:wasm-function[1067]:0x2f918e)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (https://ruffle.rs/demo/593c7bba763056fd5ed9.wasm:wasm-function[1203]:0x32b2d9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2644d32550bf22ce (https://ruffle.rs/demo/593c7bba763056fd5ed9.wasm:wasm-function[4867]:0x4e2f91)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (https://ruffle.rs/demo/593c7bba763056fd5ed9.wasm:wasm-function[3299]:0x48cf29)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (https://ruffle.rs/demo/593c7bba763056fd5ed9.wasm:wasm-function[5151]:0x4f2827)
    at core::panicking::panic::h35778e3c18266c93 (https://ruffle.rs/demo/593c7bba763056fd5ed9.wasm:wasm-function[4864]:0x4e2ab8)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h202378b585a0a5ab (https://ruffle.rs/demo/593c7bba763056fd5ed9.wasm:wasm-function[722]:0x24e47b)
    at ruffle_web::Ruffle::tick::hac7cbe7d3f33bc61 (https://ruffle.rs/demo/593c7bba763056fd5ed9.wasm:wasm-function[647]:0x21be5c)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he7469abf47a4d165 (https://ruffle.rs/demo/593c7bba763056fd5ed9.wasm:wasm-function[367]:0xc29d5)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-19
Channel: nightly
Built: 2022-02-19T00:21:21.003Z
Commit: 2ca62ecf4bac5696d2da084b1f5d5c6ba2a4e0f7
Is extension: false

**Comment by ellieeet123** [comment] 2022-02-20 23:27
What SWF file did you try to play?

**Comment by amiramte** [comment] 2022-02-22 12:32
I was tring to use adobe connect

________________________________

**Comment by Dinnerbone** [comment] 2024-07-12 22:05
Duplicate of #6213

**Closed by Dinnerbone** 2024-07-12 22:05 UTC
Labels: duplicate, render-webgl, error-report
