### ISSUE TITLE
Error on https://neb.anirudhiscool.repl.co/proxy/aHR0cHM6Ly8za2gwLmdpdGh1Yi5pbw==/projects/thebattle/

### ISSUE THREAD

**Issue by Bobby123214** [ruffle-rs/ruffle#7236] opened 2022-06-16 07:46 UTC
# Error Info
Error name: TypeError
Error message: str.startsWith is not a function
Error stack:
```
TypeError: str.startsWith is not a function
    at rewrite_url (https://neb.anirudhiscool.repl.co/proxy/utils/assets/inject.js:11:13)
    at window.fetch (https://neb.anirudhiscool.repl.co/proxy/utils/assets/inject.js:31:11)
    at r (https://neb.anirudhiscool.repl.co/proxy/aHR0cHM6Ly8za2gwLmdpdGh1Yi5pbw==/projects/thebattle/ruffle.js:1:37197)
    at https://neb.anirudhiscool.repl.co/proxy/aHR0cHM6Ly8za2gwLmdpdGh1Yi5pbw==/projects/thebattle/ruffle.js:1:39645
    at H (https://neb.anirudhiscool.repl.co/proxy/aHR0cHM6Ly8za2gwLmdpdGh1Yi5pbw==/projects/thebattle/ruffle.js:1:39651)
    at ce.ensureFreshInstance (https://neb.anirudhiscool.repl.co/proxy/aHR0cHM6Ly8za2gwLmdpdGh1Yi5pbw==/projects/thebattle/ruffle.js:1:52378)
    at ce.load (https://neb.anirudhiscool.repl.co/proxy/aHR0cHM6Ly8za2gwLmdpdGh1Yi5pbw==/projects/thebattle/ruffle.js:1:54751)
    at https://neb.anirudhiscool.repl.co/proxy/aHR0cHM6Ly8za2gwLmdpdGh1Yi5pbw==/projects/thebattle/:22:16
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://neb.anirudhiscool.repl.co/proxy/aHR0cHM6Ly8za2gwLmdpdGh1Yi5pbw==/projects/thebattle/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14588.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-22
Channel: nightly
Built: 2021-12-22T00:14:15.814Z
Commit: 74ab24c0c3345025a1b7297c526c37783ecc9990
Is extension: false

**Comment by n0samu** [comment] 2022-06-16 23:55
Duplicate of #6392. See my comment on that issue.

**Closed by n0samu** 2022-06-16 23:55 UTC
Labels: duplicate, error-report
