### ISSUE TITLE
Fix this please!!!! :(

### ISSUE THREAD

**Issue by Ivyfrost** [ruffle-rs/ruffle#4074] opened 2021-04-21 06:46 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.Module doesn't parse at byte 0: modules doesn't start with '\0asm'

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.dolldivine.com/create-a-cat.php

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-06
Channel: nightly
Built: 2021-03-06T00:18:53.737Z
Commit: b68eeeae26ff9b09247bd16ab955dd1a4677af42

**Comment by torokati44** [comment] 2021-04-21 09:02
I don't get this error on the page you linked.

**Comment by torokati44** [comment] 2021-04-21 09:06
Also, in the report it says "Name: nightly 2021-03-06", while now I get 2021-04-18 in the context menu (without the extension installed) of that page.
Perhaps the self-hosted Ruffle version was corrupted, but was updated correctly since, and you need to "hard-refresh" (or clean the browser cache)?

**Comment by torokati44** [comment] 2021-04-23 07:10
Duplicate of #4070

**Closed by torokati44** 2021-04-23 07:10 UTC
