### ISSUE TITLE
AS2 : Two issues or bugs on clip-buttons and linked textfields with " .enabled " property  and " .onChanged() " function.

### ISSUE THREAD

**Issue by depPat** [ruffle-rs/ruffle#5560] opened 2021-10-28 18:03 UTC
### Describe the bug

- clipbutton1.enabled = false; doesn't work on clips (but with single button is ok)
- text.onChanged function is out of order

So : "false = true" !...and....password and login staff is zaped !

Example of script ( / actions panel of frame 1 of the flash file about password and login objects)

//zone_pass & zone_name are textfield's names
//champPass and champName are "variables" put in "options" property panel of two textfields

_clipbout.enabled = false;
zone_pass.onChanged = zone_name.onChanged = function {
if (champPass = "poutpout" && champName = "ouinouin6"){
clipbout.enabled = true;
}else{
clipbout.enabled = false;
}
};_

demo of bugs here :

http://kniaka.fr/testRuffle/ruffle-bugButtonsClips.html

### Expected behavior

- Desables a clip or clip-button, if "_.enabled = false_"... is notified and enable it with ".enabled = true" properties

- "_.onChanged_ () function " allows a changed text staff to work or not (password example)

### Affected platform

Self-hosted version

### Operating system

Windows10 - Android

### Browser

Opera, Firefox, Chrome, Edge....

**Comment by Toad06** [comment] 2022-02-05 21:01
Thanks for the report.

It seems like everything is now working as intended in the last releases. This was likely fixed by #6123.

**Closed** 2022-02-11 11:50 UTC
Labels: bug, avm1, input

**Comment by depPat** [comment] 2022-02-11 15:01
@Toad06 
Thanks for the work and thanks to the team too for allowing the sustain of Flash !
So,
".enabled=true/false" property 
and 
".onChanged()" function are now ok. 

(but the dynamical textfields linked, still bug - see other post at #5559)
