### ISSUE TITLE
Error on https://h-flash.com/kasumi-f-series/

### ISSUE THREAD

**Issue by hxggnctvhjbc** [ruffle-rs/ruffle#6786] opened 2022-04-22 22:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 40 but the index is 40', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/jpeg-decoder-0.2.1/src/upsampler.rs:219:22
Error stack:
```
@https://h-flash.com/data/ruffle/core.ruffle.574918e3d0d65e4627d9.js:1:6973
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h9279eef47cf85b81]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h47a0e203360b6c10]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h4ca53049f45e3264]@[wasm code]
<?>.wasm-function[core::panicking::panic_bounds_check::h859d2a727fd634e5]@[wasm code]
<?>.wasm-function[<jpeg_decoder::upsampler::UpsamplerH2V2 as jpeg_decoder::upsampler::Upsample>::upsample_row::hd79c1d5d501f7963]@[wasm code]
<?>.wasm-function[jpeg_decoder::decoder::compute_image::h4a993a76e4c89cdf]@[wasm code]
<?>.wasm-function[jpeg_decoder::decoder::Decoder<R>::decode_internal::hdb91a1feb9629dd4]@[wasm code]
<?>.wasm-function[ruffle_core::backend::render::decode_define_bits_jpeg::h9e44ada1e7f43172]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_jpeg_3_or_4::h5a67d6933cf7da18]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_bits_jpeg_3_or_4::hbd51d60f061fe93d]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h54ab68b9ccb8f47e]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h83070360117c29c4]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7fe0b0a8d1ec60ec]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2665a6b2ebc24af9]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::hee446ce30e910395]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0172ba65d472adb5]@[wasm code]
wasm-stub@[native code]
O@https://h-flash.com/data/ruffle/core.ruffle.574918e3d0d65e4627d9.js:1:3997
c@https://h-flash.com/data/ruffle/core.ruffle.574918e3d0d65e4627d9.js:1:2522
promiseReactionJob@[native code]
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://h-flash.com/kasumi-f-series/
SWF URL: https://h-flash.com/data/swf/2014/01/kasumi-f.swf

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/208.0.441531153 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-28
Channel: nightly
Built: 2022-01-28T00:18:15.390Z
Commit: c14569e3d4440038daa065c6e4099c2f326b5cb7
Is extension: false

**Comment by Herschel** [comment] 2022-04-28 23:43
Dupe of #6608 (iOS Safari 15.4)

**Closed by Herschel** 2022-04-28 23:43 UTC
Labels: error-report
