### ISSUE TITLE
Error on https://flash.riolubruh.repl.co/electricman2.html

### ISSUE THREAD

**Issue by WiscYT** [ruffle-rs/ruffle#8467] opened 2022-11-03 15:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://flash.riolubruh.repl.co/core.ruffle.e6330d73b0b106a08ebb.js:1:6979)
    at std::sync::once::Once::call_once::{{closure}}::h73fc39b54ec29717 (wasm://wasm/0180e27a:wasm-function[1027]:0x2a28cb)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0180e27a:wasm-function[1482]:0x3238bb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d648d6ec080e3d2 (wasm://wasm/0180e27a:wasm-function[4945]:0x48a646)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0180e27a:wasm-function[3637]:0x447183)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0180e27a:wasm-function[5095]:0x48d997)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/0180e27a:wasm-function[5000]:0x48b5b8)
    at core::ops::function::FnOnce::call_once::hc23e58910edbda0c (wasm://wasm/0180e27a:wasm-function[1115]:0x2c0d65)
    at ruffle_core::avm1::function::Executable::exec::ha1ebff59d66588d4 (wasm://wasm/0180e27a:wasm-function[367]:0xf970f)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h6e117415f5d8a106 (wasm://wasm/0180e27a:wasm-function[492]:0x193488)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://flash.riolubruh.repl.co/electricman2.html
SWF URL: https://flash.riolubruh.repl.co/swf/e2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-26
Channel: nightly
Built: 2022-09-26T00:18:09.507Z
Commit: 51c9e3714a71a6b67f97323f85639878156b95af
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment] 2022-11-03 22:03
Duplicate of #4932

**Closed by n0samu** 2022-11-03 22:03 UTC
Labels: duplicate, error-report

**Comment by WiscYT** [comment] 2022-11-04 13:42
What do you mean

**Comment by n0samu** [comment] 2022-11-04 16:43
The issue with this game has been reported hundreds of times already. Sorry, but the game does not work yet and likely won't work for some time.

**Comment by WiscYT** [comment] 2022-11-04 18:36
Oh ok sorry do you know why surviv.io is down
