### ISSUE TITLE
Error on https://archive.org/details/Example_flash13

### ISSUE THREAD

**Issue by morelj5** [ruffle-rs/ruffle#8108] opened 2022-09-27 16:50 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.9f799b172fb83660e1a8.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::ha360d592741a73b3 (wasm://wasm/017cacaa:wasm-function[1138]:0x2c083f)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/017cacaa:wasm-function[1447]:0x320287)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h613b00154d20bc2b (wasm://wasm/017cacaa:wasm-function[4879]:0x478fc0)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/017cacaa:wasm-function[3630]:0x441860)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/017cacaa:wasm-function[5070]:0x47f7c5)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/017cacaa:wasm-function[4967]:0x47a82b)
    at core::ops::function::FnOnce::call_once::h9baee3432cd92051 (wasm://wasm/017cacaa:wasm-function[1083]:0x2b2a2c)
    at ruffle_core::avm1::function::Executable::exec::hdfddf9496055cb0e (wasm://wasm/017cacaa:wasm-function[359]:0xe594e)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h15e49bfbb24125b9 (wasm://wasm/017cacaa:wasm-function[850]:0x256686)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://archive.org/details/Example_flash13

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-19
Channel: nightly
Built: 2022-09-19T00:15:10.357Z
Commit: 9b9c95bfe28cb862d44e9517e94e9de73acd9de3
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment] 2022-09-27 23:52
Duplicate of #4932

**Closed by n0samu** 2022-09-27 23:52 UTC
Labels: duplicate, error-report
