### ISSUE TITLE
Error on https://z0r.de/2216

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#7824] opened 2022-08-31 15:29 UTC
This seems like a regression - on z0r's version there at least no panic.

# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Cannot access property ::addTarget of null or undefined"', core/src/timer.rs:116:26
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Cannot access property ::addTarget of null or undefined"', core/src/timer.rs:116:26
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://bpbcolodjffokdjdifhklognjjkbijlg/dist/966.js:1:5743)
    at std::sync::once::Once::call_once::{{closure}}::h2b0dd13dece8b2bd (wasm://wasm/016b902e:wasm-function[943]:0x274ea3)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/016b902e:wasm-function[1380]:0x2fb420)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcedf29f658f02358 (wasm://wasm/016b902e:wasm-function[4818]:0x444048)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/016b902e:wasm-function[3539]:0x40b90a)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/016b902e:wasm-function[4993]:0x44988e)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/016b902e:wasm-function[4124]:0x42d912)
    at ruffle_web::Ruffle::tick::h3260ea7973306a7d (wasm://wasm/016b902e:wasm-function[614]:0x1d015a)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::ha1f959dd4d3755f8 (wasm://wasm/016b902e:wasm-function[5861]:0x461e70)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h5b91bd50d178d7c0 (wasm://wasm/016b902e:wasm-function[5357]:0x45497a)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://z0r.de/2216?flash
SWF URL: https://z0r.de/L/z0r-de_2216.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-31
Channel: nightly
Built: 2022-08-31T00:15:18.352Z
Commit: cc9e283191ea70931d51cef82a272822520ff957
Is extension: true

# Metadata
width: 600
height: 450
frameRate: 25
numFrames: 1
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 1085604

**Comment by torokati44** [comment] 2022-08-31 15:35
I think this was also caused by https://github.com/ruffle-rs/ruffle/pull/7428.

**Comment by torokati44** [comment] 2022-09-03 06:54
Fixed by https://github.com/ruffle-rs/ruffle/pull/7825.

**Closed by torokati44** 2022-09-03 06:54 UTC
Labels: avm2, regression, error-report
