### ISSUE TITLE
Text Not Displaying Right

### ISSUE THREAD

**Issue by 3mcee** [ruffle-rs/ruffle#3000] opened 2021-01-31 16:56 UTC
![Screenshot (490)](https://user-images.githubusercontent.com/78311880/106391393-bd86f900-63b2-11eb-91c7-7fbc57bb6f96.png)
https://blogofholding.com/dungeonrobber/index.php

It's one of those text-based adventures where it gives you options, you press a button, and it tells you what happens as a result. The issue is that the text log quickly fills up and the text window doesn't scroll down, so it's stuck only displaying the first few lines. Pretty easy to recreate. If you play around with it for minute, you'll see the problem.

I'm using the Ruffle browser extension (2021-01-31), Google Chrome, Windows 10.

**Comment by ousia** [comment] 2021-01-31 17:46
@3mcee,

many thanks for your report.

I’m afraid it might be not as easy to recreate as you imagine (for people who never played similar games before).

If you could provide a concise list of steps on how to reproduce the issue, this might help to get it fixed sooner.

Link to SWF file: https://blogofholding.com/dungeonrobber/randomdungeonmap14.swf.

**Comment by ousia** [comment] 2021-01-31 17:53
Sorry, but from your description it isn’t clear what the actual problem is: text not displaying right or text window not scrolling down?

**Comment by 3mcee** [comment] 2021-01-31 22:52
Sorry I don't know how to explain it any better than that, but if you go in and play around with it, you'll quickly see what the problem is as it makes the game unplayable after the text builds up. Looking back at the screenshot, I also noticed the text gets cut off. The game is called Dungeon Robber, and when you first enter the game, the first piece of text is "Welcome to DUNGEON ROBBER, <player name>." but if you look at the screenshot, it says "Welcome to DUNGEON ROB" and then it just immediately continues printing another piece of text on the same line.

**Comment by Poopooracoocoo** [comment] 2021-02-01 02:07
Ruffle demo version 2021-02-01 running in Chrome on left, Flash Player on right:

"What the heck is this?"
![image](https://user-images.githubusercontent.com/51363864/106405975-ffd03900-648b-11eb-9221-19b8770b6123.png)

Note: don't judge the text with my screenshots. Flash Player will always look bad because I have a high DPI screen.

Pressed "start new game" on main screen. Attempted to edit name in Ruffle to match Flash Player's default randomly generated name. Cursor won't go away after clicking outside of Chrome, while clicking outside of Flash Player makes its cursor disappear. The name was not actually edited.
![image](https://user-images.githubusercontent.com/51363864/106406516-9a7d4780-648d-11eb-8fc5-a71d98b00da3.png)



I can't see the buttons to keep or reroll the die.
![image](https://user-images.githubusercontent.com/51363864/106406535-a49f4600-648d-11eb-9163-beafc79448c7.png)

Text that should start on a new line doesn't. The text should automatically scroll up when new text is added, but is instead cut off on Ruffle. Text cannot be selected in Ruffle either
![image](https://user-images.githubusercontent.com/51363864/106406684-2becb980-648e-11eb-97bd-e4aad7746884.png)

**Comment by n0samu** [comment] 2022-10-30 00:09
All of these problems seem to be fixed now, except that editing the player name still doesn't actually change it in Ruffle.
The "Keep" and "Reroll" buttons are outside the bounds of the stage so I don't think they're supposed to be visible. When playing the game on the website, I don't see the buttons in Flash Player or Ruffle.

**Comment by kjarosh** [comment] 2024-11-23 09:33
This seems to be fixed, I can change the name and it works

**Closed by kjarosh** 2024-11-23 09:33 UTC
Labels: bug, text, A-avm1
