### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by PurpleZenith** [ruffle-rs/ruffle#7590] opened 2022-08-06 20:59 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:823:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:823:18
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.1fe3c100cd71bce304ce.js:1:5540)
    at std::sync::once::Once::call_once::{{closure}}::hc005efe66820567d (wasm://wasm/0169c4fe:wasm-function[1189]:0x2b644a)
    at std::sync::once::Once::call_inner::h1c414562e2619117 (wasm://wasm/0169c4fe:wasm-function[1378]:0x2f4c14)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h333199a3a4749bb8 (wasm://wasm/0169c4fe:wasm-function[4742]:0x44028c)
    at std::panicking::rust_panic_with_hook::h1c368a27f9b0afe1 (wasm://wasm/0169c4fe:wasm-function[3103]:0x3ee44a)
    at core::panicking::panic_fmt::hcdb13a4b2416cf82 (wasm://wasm/0169c4fe:wasm-function[4929]:0x445dd7)
    at core::panicking::panic::ha8ced62e366a0d64 (wasm://wasm/0169c4fe:wasm-function[4838]:0x441d19)
    at core::ops::function::FnOnce::call_once::he6b960eb0e7a3615 (wasm://wasm/0169c4fe:wasm-function[1007]:0x283b91)
    at ruffle_core::avm1::function::Executable::exec::hd1a31b7b31ac1395 (wasm://wasm/0169c4fe:wasm-function[354]:0xf69c1)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h812a9e6cbb0cb2b4 (wasm://wasm/0169c4fe:wasm-function[785]:0x225fc6)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1659378341%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2285307937.53843136dcee265bd33003025fdfa349218cadfc2fd34b%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2262eecd6314d62%22%2C%22NewgroundsAPI_SessionID%22%3A%22NTsGxy9gHxfQT9LtHeUX90c62508c13431fd5d8161fde25ca4cb86e40682RGP0%22%2C%22NewgroundsAPI_UserName%22%3A%22jupjup12345%22%2C%22NewgroundsAPI_UserID%22%3A5103362%2C%22ng_username%22%3A%22jupjup12345%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-01
Channel: nightly
Built: 2022-08-01T00:18:26.040Z
Commit: 2ce6679643d1e97c83becc4d8c4a8447f91c6471
Is extension: false

**Comment by n0samu** [comment] 2022-08-06 21:09
Duplicate of #3756

**Closed by n0samu** 2022-08-06 21:09 UTC
Labels: duplicate, error-report
