### ISSUE TITLE
Error on https://en.gameslol.net/mini-dash-329.html

### ISSUE THREAD

**Issue by Musamzz979** [ruffle-rs/ruffle#12824] opened 2023-08-18 15:31 UTC
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://en.gameslol.net/data/ruffle/core.ruffle.18e89839c4257ed9f1ae.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd045a4c294d004d3 (wasm://wasm/02faedb6:wasm-function[9213]:0x8ea9bb)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02faedb6:wasm-function[6049]:0x7fa9aa)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02faedb6:wasm-function[9057]:0x8e6375)
    at alloc::raw_vec::capacity_overflow::h0e982c690927e903 (wasm://wasm/02faedb6:wasm-function[9056]:0x8e6285)
    at alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h6e0e685015044e87 (wasm://wasm/02faedb6:wasm-function[5927]:0x7ee43a)
    at ruffle_core::avm2::globals::flash::utils::byte_array::set_length::h627879830513f877 (wasm://wasm/02faedb6:wasm-function[3383]:0x6947db)
    at ruffle_core::avm2::function::Executable::exec::h4c0b40e138b66391 (wasm://wasm/02faedb6:wasm-function[837]:0x2c67b6)
    at ruffle_core::avm2::object::TObject::call_method::h2d1ca5ee28c059b8 (wasm://wasm/02faedb6:wasm-function[2018]:0x53780b)
    at ruffle_core::avm2::object::TObject::set_property::h4751d6518e62575d (wasm://wasm/02faedb6:wasm-function[2327]:0x59787f)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::length()
    at global/F_avm2_casRamLength()
    at global/F___sys_mmap()
    at global/F_mmap()
    at global/F_pages_map()
    at global/F_base_pages_alloc()
    at global/F_base_alloc()
    at global/F_arenas_extend()
    at global/F_malloc_init()
    at global/F_malloc()
    at global/F__Znwj()
    at global/F__Z16CreateGameObjectv()
    at global/F_main()
    at global/F__start1()
    at com.adobe.flascc::CModule$/callI()
    at com.adobe.flascc::CModule$/start()
    at com.adobe.flascc::CModule$/startAsync()
    at com.adobe.flascc::Console/enterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 600 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://en.gameslol.net/mini-dash-329.html
SWF URL: https://en.gameslol.net/data/329.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-05
Channel: nightly
Built: 2023-08-05T00:19:09.531Z
Commit: f75b36a32a9cc1f1b99ed168107738218d7dabb3
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 0.1171875
numFrames: 1
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 20580648

**Comment by n0samu** [comment] 2023-08-19 22:52
Duplicate of #10851

**Closed by n0samu** 2023-08-19 22:52 UTC
Labels: duplicate, error-report
