### ISSUE TITLE
Error on https://e621.net/posts/2538204

### ISSUE THREAD

**Issue by llinkk01** [ruffle-rs/ruffle#3545] opened 2021-03-06 00:55 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32390
    at r (<anonymous>:3:32880)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/2538204?q=flash

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-04
Channel: nightly
Built: 2021-03-04T00:17:59.511Z
Commit: f64e5d5b4113249417570c9bb905be75c8401fb3

**Comment by Poopooracoocoo** [comment] 2021-03-06 01:31
#2201

**Comment by adrian17** [comment] 2021-03-10 16:12
Indeed, a duplicate of https://github.com/ruffle-rs/ruffle/issues/2201 .

**Closed by adrian17** 2021-03-10 16:12 UTC
