### ISSUE TITLE
Error on https://ruffle.rs/

### ISSUE THREAD

**Issue by christian-scheible** [ruffle-rs/ruffle#13717] opened 2023-10-26 09:01 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left


    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.fa55cd8e4a345c6a0df5.js:1:53228)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hee68611ee8147044 (wasm://wasm/032bf7de:wasm-function[9747]:0x995320)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032bf7de:wasm-function[6416]:0x8981dd)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032bf7de:wasm-function[9549]:0x990199)
    at core::ops::function::Fn::call::h29d499b8947f9422 (wasm://wasm/032bf7de:wasm-function[6577]:0x8a1a05)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h0b7e9b7bd4967d5c (wasm://wasm/032bf7de:wasm-function[5318]:0x838cd7)
    at <T as wgpu::context::DynContext>::device_create_buffer::h81ba37c770f75660 (wasm://wasm/032bf7de:wasm-function[7355]:0x8ebcec)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h481c6961f2e6a8f4 (wasm://wasm/032bf7de:wasm-function[1650]:0x4ce130)
    at ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::h710105d6c6426b17 (wasm://wasm/032bf7de:wasm-function[7541]:0x8f98de)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_shape::hc8fc2c030e179357 (wasm://wasm/032bf7de:wasm-function[1383]:0x454a10)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, Vulkan 1.3.246 (AMD Radeon Graphics (RADV RENOIR) (0x0000164C)), radv)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 711, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/
SWF URL: https://ruffle.rs/assets/logo-anim.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-26
Channel: nightly
Built: 2023-10-26T00:21:16.921Z
Commit: 27831d78810de2db5214c298b0eb46c7cc3c6299
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 1
swfVersion: 15
backgroundColor: #37528C
isActionScript3: false
uncompressedLength: 36643

**Comment by Dinnerbone** [comment] 2024-07-12 22:04
Duplicate of #13702

**Closed by Dinnerbone** 2024-07-12 22:04 UTC
Labels: duplicate, error-report, wgpu-oom
