### ISSUE TITLE
Error on https://www.flashthemes.net/

### ISSUE THREAD

**Issue by xzzson** [ruffle-rs/ruffle#14433] opened 2023-12-17 14:55 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
339/__wbg_get_imports/imports.wbg.__wbg_new_a64e3f2afc2cf2f8@moz-extension://3a51f943-dd9e-442a-812c-7eb58e400f54/dist/339.js:2624:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::haac704844d26e8c7@:wasm-function[9820]:0x9bae2d
std::panicking::rust_panic_with_hook::hbf46ef0245cc9589@:wasm-function[6286]:0x8a68e2
core::panicking::panic_fmt::h14c85a61aa3d538e@:wasm-function[9625]:0x9b5d49
core::panicking::assert_failed_inner::h4ee8cb46314b5c9b@:wasm-function[4279]:0x7ad053
core::panicking::assert_failed::h770bd6bdc9123011@:wasm-function[9644]:0x9b6f16
ruffle_core::loader::Loader::load_url_loader::{{closure}}::hcbc9ad76d7d8e7a4@:wasm-function[2305]:0x600451
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h0004829971776828@:wasm-function[1241]:0x4175ba
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h6b2c36ba05603144@:wasm-function[3558]:0x741904
wasm_bindgen::convert::closures::invoke1_mut::hb8fd63990c0cff2b@:wasm-function[10545]:0x9d654e
closure4451 externref shim@:wasm-function[10888]:0x9e2c27
__wbg_adapter_82@moz-extension://3a51f943-dd9e-442a-812c-7eb58e400f54/dist/339.js:310:10
real@moz-extension://3a51f943-dd9e-442a-812c-7eb58e400f54/dist/339.js:271:20

```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "NVIDIA GeForce GTX 980/PCIe/SSE2"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 32768, max_texture_dimension_2d: 32768, max_texture_dimension_3d: 16384, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.flashthemes.net/
SWF URL: https://www.flashthemes.net/home_banner-en_US.swf?v=412

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-09
Channel: nightly
Built: 2023-12-09T00:15:10.707Z
Commit: 8096146a0deba6dfdeead1cb09a677bd59c75e05
Is extension: true

# Metadata
width: 930
height: 280
frameRate: 24
numFrames: 1
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 29683

**Comment by n0samu** [comment] 2023-12-19 07:20
Duplicate of #13974

**Closed by n0samu** 2023-12-19 07:20 UTC
Labels: duplicate, error-report
