### ISSUE TITLE
My Dog Crash ...can't play.

### ISSUE THREAD

**Issue by olux997** [ruffle-rs/ruffle#12865] opened 2023-08-21 07:14 UTC
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.95374868be5907a95f46.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc22db995a124727b (wasm://wasm/03004632:wasm-function[9276]:0x8fe053)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/03004632:wasm-function[6084]:0x80aee9)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/03004632:wasm-function[9118]:0x8f9997)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hbeeb0737f319e977 (wasm://wasm/03004632:wasm-function[3174]:0x66dc2f)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h3f00b254ab831116 (wasm://wasm/03004632:wasm-function[3095]:0x65bb24)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hc45af507bb10e3af (wasm://wasm/03004632:wasm-function[1046]:0x35df6b)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h3d5684c99558c89b (wasm://wasm/03004632:wasm-function[1880]:0x50dfd8)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h5ad94e8cc2239754 (wasm://wasm/03004632:wasm-function[826]:0x2b6308)
    at ruffle_core::frame_lifecycle::catchup_display_object_to_frame::h098126cc9009a0d0 (wasm://wasm/03004632:wasm-function[6454]:0x821d34)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle-regressions.github.io/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-21
Channel: nightly
Built: 2023-08-21T00:23:16.665Z
Commit: 89cc0eb31d2fd38a545cefccb0b44e4a22807d5e
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2713401

SWF:
[my-dog.zip](https://github.com/ruffle-rs/ruffle/files/12393259/my-dog.zip)

==============================================================
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.95374868be5907a95f46.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc22db995a124727b (wasm://wasm/03004632:wasm-function[9276]:0x8fe053)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/03004632:wasm-function[6084]:0x80aee9)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/03004632:wasm-function[9118]:0x8f9997)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hbeeb0737f319e977 (wasm://wasm/03004632:wasm-function[3174]:0x66dc2f)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h3f00b254ab831116 (wasm://wasm/03004632:wasm-function[3095]:0x65bb24)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hc45af507bb10e3af (wasm://wasm/03004632:wasm-function[1046]:0x35df6b)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h3d5684c99558c89b (wasm://wasm/03004632:wasm-function[1880]:0x50dfd8)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h5ad94e8cc2239754 (wasm://wasm/03004632:wasm-function[826]:0x2b6308)
    at ruffle_core::frame_lifecycle::catchup_display_object_to_frame::h098126cc9009a0d0 (wasm://wasm/03004632:wasm-function[6454]:0x821d34)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle-regressions.github.io/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-21
Channel: nightly
Built: 2023-08-21T00:23:16.665Z
Commit: 89cc0eb31d2fd38a545cefccb0b44e4a22807d5e
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2713401

**Comment by Dinnerbone** [comment] 2024-07-12 22:02
Duplicate of #12594

**Closed by Dinnerbone** 2024-07-12 22:02 UTC
Labels: bug, duplicate, panic, mixed-avm
