### ISSUE TITLE
Error on https://www.joypadmedia.com/get_emulator.php?w=800&h=600&r=1&f=https://www.joypadmedia.com/emulator/f/666/rail-of-war.swf

### ISSUE THREAD

**Issue by rvh1986** [ruffle-rs/ruffle#3229] opened 2021-02-12 18:10 UTC
Error happens after selecting a train and clicking "Start".

# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/bitmap_data.rs:1137:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/bitmap_data.rs:1137:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.joypadmedia.com/emulator/e/ruffle/ruffle.js:1:6799)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (<anonymous>:wasm-function[1327]:0x26b533)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (<anonymous>:wasm-function[1603]:0x29e7b9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (<anonymous>:wasm-function[4637]:0x381cb3)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (<anonymous>:wasm-function[3509]:0x3576e4)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (<anonymous>:wasm-function[4145]:0x375270)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (<anonymous>:wasm-function[4983]:0x387384)
    at rust_begin_unwind (<anonymous>:wasm-function[4868]:0x385c81)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (<anonymous>:wasm-function[4984]:0x3873ba)
    at core::panicking::panic::h8e74859c8f9988ca (<anonymous>:wasm-function[4799]:0x384acb)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.joypadmedia.com/get_emulator.php?w=800&h=600&r=1&f=https://www.joypadmedia.com/emulator/f/666/rail-of-war.swf
SWF URL: https://www.joypadmedia.com/emulator/f/666/rail-of-war.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-12
Channel: nightly
Built: 2021-02-12T00:17:25.708Z
Commit: da86f7fc5afbe93c8b378366c550a0622f59d5b6

**Comment by relrelb** [comment] 2021-04-24 12:17
Duplicate of #3765.

**Closed by relrelb** 2021-04-24 12:17 UTC
