### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Bluest** [ruffle-rs/ruffle#6114] opened 2022-01-23 18:43 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.0342f13b023d3a8f14c5.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::hc85ce564f2ea66ba (https://uploads.ungrounded.net/ruffle_wrapper/lib/f2c3a62f45168abd7077.wasm:wasm-function[1030]:0x30339f)
    at std::sync::once::Once::call_inner::h6fd514b461aaa35e (https://uploads.ungrounded.net/ruffle_wrapper/lib/f2c3a62f45168abd7077.wasm:wasm-function[1165]:0x337bd5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he301baa1a5c81c58 (https://uploads.ungrounded.net/ruffle_wrapper/lib/f2c3a62f45168abd7077.wasm:wasm-function[4677]:0x4d4b76)
    at std::panicking::rust_panic_with_hook::h19d99b2b2597d628 (https://uploads.ungrounded.net/ruffle_wrapper/lib/f2c3a62f45168abd7077.wasm:wasm-function[3191]:0x48a7b0)
    at core::panicking::panic_fmt::hbc500cb2b2c8690c (https://uploads.ungrounded.net/ruffle_wrapper/lib/f2c3a62f45168abd7077.wasm:wasm-function[4951]:0x4e0904)
    at core::panicking::panic::h7ae74ceab81e332c (https://uploads.ungrounded.net/ruffle_wrapper/lib/f2c3a62f45168abd7077.wasm:wasm-function[4674]:0x4d469d)
    at core::ops::function::FnOnce::call_once::h21e86c081da96d39 (https://uploads.ungrounded.net/ruffle_wrapper/lib/f2c3a62f45168abd7077.wasm:wasm-function[1064]:0x319031)
    at ruffle_core::avm1::function::Executable::exec::haca684796bbce4b5 (https://uploads.ungrounded.net/ruffle_wrapper/lib/f2c3a62f45168abd7077.wasm:wasm-function[414]:0x156d93)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hff87abb433d6f83f (https://uploads.ungrounded.net/ruffle_wrapper/lib/f2c3a62f45168abd7077.wasm:wasm-function[623]:0x2227e7)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1642690932%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261ed9ab1e4d30%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-20
Channel: nightly
Built: 2022-01-20T00:14:58.083Z
Commit: 1e28e1da11f1af1d43d4a75c8271e2992c08a1b8
Is extension: false

**Comment by Poopooracoocoo** [comment] 2022-01-24 09:44
Duplicate of #3756

**Closed by Poopooracoocoo** 2022-01-24 09:44 UTC
Labels: duplicate, error-report
