### ISSUE TITLE
Error on https://kdata1.com/2023/04/jacksmith/

### ISSUE THREAD

**Issue by valen854** [ruffle-rs/ruffle#11559] opened 2023-06-15 17:53 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.1/src/backend/direct.rs:3019:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.1/src/backend/direct.rs:3019:5
    at U.n.wbg.__wbg_new_87297f22973157c8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.f350782df611eff36d48.js:1:51160)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha4de13118e9dd6b4 (wasm://wasm/02c04fd6:wasm-function[8605]:0x82949c)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c04fd6:wasm-function[5585]:0x74b259)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c04fd6:wasm-function[8471]:0x8250ec)
    at core::ops::function::Fn::call::h09ccf7236055d5d1 (wasm://wasm/02c04fd6:wasm-function[5907]:0x75f2a0)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::hc6b654ac3b8aff33 (wasm://wasm/02c04fd6:wasm-function[4453]:0x6eb1c2)
    at wgpu::backend::direct::Context::handle_error_nolabel::hda824b6895c2bd0c (wasm://wasm/02c04fd6:wasm-function[2814]:0x5d7b97)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h522d95aa416dd0ba (wasm://wasm/02c04fd6:wasm-function[6114]:0x7712a5)
    at wgpu::CommandEncoder::copy_texture_to_buffer::hb3b0c0866ae9f69f (wasm://wasm/02c04fd6:wasm-function[5204]:0x7307f6)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h59b0a77a3c8ce6bb (wasm://wasm/02c04fd6:wasm-function[1618]:0x461b34)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (Geminilake 2x6) , OpenGL 4.5)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 800, height: 600, depth_or_array_layers: 1 }

# Page Info
Page URL: https://kdata1.com/2023/04/jacksmith/?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=22517&mp_game_uid=jacksmith&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Fjacksmith&mp_int=1&mp_locale=es_ES&mp_player_type=IFRAME&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=Europe%2FMadrid&mp_view_type=
SWF URL: https://kdata1.com/2023/04/jacksmith/game.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-15
Channel: nightly
Built: 2023-06-15T00:24:42.967Z
Commit: cd2c7f6f2fc651073627085b0ab99bbe9203ff6b
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by Lord-McSweeney** [comment] 2023-06-15 17:55
@valen854 what were you doing when this error appeared?

**Comment by evilpie** [comment] 2024-02-16 14:21
Duplicate of #11591.

**Closed by evilpie** 2024-02-16 14:21 UTC
Labels: rendering, linux, error-report
