### ISSUE TITLE
Error on https://kdata1.com/RS/game.php

### ISSUE THREAD

**Issue by kkkovalchukkk** [ruffle-rs/ruffle#14623] opened 2024-01-05 16:46 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1851b3c74a4fa0cf65d5.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2784d75c097bd38f (wasm://wasm/035bd9fa:wasm-function[10700]:0xa01d11)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/035bd9fa:wasm-function[6560]:0x8ebe24)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/035bd9fa:wasm-function[10423]:0x9fba8e)
    at core::ops::function::Fn::call::h31fcd9672878c467 (wasm://wasm/035bd9fa:wasm-function[6862]:0x902a4b)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h55f5091b89514ccd (wasm://wasm/035bd9fa:wasm-function[5402]:0x88262e)
    at <T as wgpu::context::DynContext>::device_create_texture::h225b6453d716a130 (wasm://wasm/035bd9fa:wasm-function[7372]:0x92dd7d)
    at wgpu::Device::create_texture::h78431bdcb2a23fa9 (wasm://wasm/035bd9fa:wasm-function[5732]:0x8a0a39)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::h9e779c3e1c053376 (wasm://wasm/035bd9fa:wasm-function[2178]:0x5ec79c)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::hc5a276a0ba76aba6 (wasm://wasm/035bd9fa:wasm-function[1589]:0x4cfa45)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1837()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00009BC4) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 693, height: 600, depth_or_array_layers: 1 }

# Page Info
Page URL: https://kdata1.com/RS/game.php?r=//kdata1.com/2017/07/pre-civilization-marble-age.swf&w=800&h=533&warnsupport=true
SWF URL: https://kdata1.com/2017/07/pre-civilization-marble-age.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-05
Channel: nightly
Built: 2024-01-05T00:14:48.382Z
Commit: 89b7f7a6b8e851d5d76c94ca5db969a8457b5ab1
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9733381

**Comment by n0samu** [comment] 2024-01-16 20:52
Duplicate of #13946

**Closed by n0samu** 2024-01-16 20:52 UTC
Labels: duplicate, render-wgpu, error-report
