### ISSUE TITLE
Error on https://flashstorage.games/embed/tequila-zombies-3

### ISSUE THREAD

**Issue by warley369** [ruffle-rs/ruffle#15352] opened 2024-02-28 23:00 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f77055/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Mesa Intel(R) HD Graphics 4400 (HSW GT2), OpenGL 4.6)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://flashstorage.games/embed/tequila-zombies-3?emulator=ruffle&game=%7B%22id%22%3A18378%2C%22name%22%3A%22Tequila+Zombies+3%22%2C%22slug%22%3A%22tequila-zombies-3%22%2C%22file%22%3A%22%5B%7B%5C%22download_link%5C%22%3A%5C%22games%5C%5C%5C%2FJuly2023%5C%5C%5C%2FTequilaZombies3.swf%5C%22%2C%5C%22original_name%5C%22%3A%5C%22TequilaZombies3.swf%5C%22%7D%5D%22%2C%22alt_file%22%3A%22https%3A%5C%2F%5C%2Fflashstorage.games%22%2C%22alt_game%22%3Anull%2C%22width%22%3A800%2C%22height%22%3A600%2C%22origin%22%3Anull%2C%22extension%22%3A%22SWF%22%2C%22flashversion%22%3Anull%2C%22image%22%3A%22games%5C%2FJuly2023%5C%2FoIb9TRjKw00bqcQFi7cT.jpg%22%2C%22playable%22%3A0%2C%22resizable%22%3A1%2C%22updatedAt%22%3Anull%2C%22avm%22%3A2%2C%22flashvars%22%3Anull%2C%22emulator%22%3A%22ruffle%22%2C%22orientation%22%3A%22landscape%22%2C%22embed_options%22%3A%22%7B%5C%22wmode%5C%22%3A%5C%22opaque%5C%22%2C+%5C%22allowNetworking%5C%22%3A+%5C%22internal%5C%22%2C+%5C%22allowScriptAccess%5C%22%3A+%5C%22No%5C%22%7D%22%2C%22name_mvkb%22%3A%22%7B%5Cr%5Cn++++%5C%22KeyR%5C%22%3A+%7B%5C%22class%5C%22%3A+%5C%22reload%5C%22%2C+%5C%22title%5C%22%3A+%5C%22R%5C%22%7D%2C%5Cr%5Cn++++%5C%22KeyQ%5C%22%3A+%7B%5C%22class%5C%22%3A+%5C%22weapon%5C%22%2C+%5C%22title%5C%22%3A+%5C%22Weapon%5C%22%7D%2C%5Cr%5Cn++++%5C%22KeyE%5C%22%3A+%7B%5C%22class%5C%22%3A+%5C%22weapon-2%5C%22%2C+%5C%22title%5C%22%3A+%5C%22Weapon%5C%22%7D%2C%5Cr%5Cn++++%5C%22KeyS%5C%22%3A+%7B%5C%22title%5C%22%3A+%5C%22Search%5C%22%7D%2C%5Cr%5Cn++++%5C%22Space%5C%22%3A+%7B%5C%22class%5C%22%3A+%5C%22border%5C%22%2C+%5C%22name%5C%22%3A+%5C%22Super+Power%5C%22%2C+%5C%22title%5C%22%3A+%5C%22Space%5C%22%7D%2C%5Cr%5Cn++++%5C%22rightRound%5C%22%3A%7B%5Cr%5Cn++++++++%5C%22Space%5C%22%3A+%7B%5Cr%5Cn++++++++++++%5C%22KeyS%5C%22%3A+1%2C%5Cr%5Cn++++++++++++%5C%22KeyQ%5C%22%3A+2%2C%5Cr%5Cn++++++++++++%5C%22KeyE%5C%22%3A+3%2C%5Cr%5Cn++++++++++++%5C%22KeyR%5C%22%3A+4%5Cr%5Cn++++++++%7D%5Cr%5Cn++++%7D%5Cr%5Cn%7D%22%2C%22style_mvkb%22%3Anull%2C%22left_mvkb%22%3A%22%5B%5C%22WASD%5C%22%5D%22%2C%22right_mvkb%22%3A%22%5B%5C%2232%5C%22%2C%5C%2269%5C%22%2C%5C%2281%5C%22%2C%5C%2282%5C%22%2C%5C%2283%5C%22%5D%22%2C%22category_slug%22%3A%22zombies%22%2C%22updated_at%22%3Anull%2C%22star_user%22%3A105%7D
SWF URL: blob:https://flashstorage.games/b9689d8e-8fc0-4499-9085-5dc2e72ab2ca

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-02-28
Channel: nightly
Built: 2024-02-28T00:05:56.108Z
Commit: 05fc77e8cd81de547d25bb657d12adfb2659091d
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 21
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 38307363

**Comment by n0samu** [comment] 2024-07-27 07:01
Duplicate of #13748

**Closed by n0samu** 2024-07-27 07:01 UTC
Labels: duplicate, panic, error-report, amf
