### ISSUE TITLE
Error on https://incredibots.com/if/game.php

### ISSUE THREAD

**Issue by INDRELE** [ruffle-rs/ruffle#15063] opened 2024-02-02 00:03 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f976fb/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f976fb/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:3369:21)
    at js_sys::Error::new::h728118aa18eebd18 (wasm://wasm/038e038e:wasm-function[13715]:0xafbedf)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h83b48721c51f39ae (wasm://wasm/038e038e:wasm-function[11330]:0xaa69e0)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/038e038e:wasm-function[6926]:0x962323)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/038e038e:wasm-function[11052]:0xaa0062)
    at core::option::expect_failed::h0edfdc49383f4b56 (wasm://wasm/038e038e:wasm-function[9627]:0xa4784a)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h8f7ec267dae28a27 (wasm://wasm/038e038e:wasm-function[784]:0x12e730)
    at flash_lso::amf3::read::AMF3Decoder::parse_object_static::h8e64771063563a2e (wasm://wasm/038e038e:wasm-function[4668]:0x83ee2d)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h8f7ec267dae28a27 (wasm://wasm/038e038e:wasm-function[784]:0x12e5a4)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h8f7ec267dae28a27 (wasm://wasm/038e038e:wasm-function[784]:0x12bc8f)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at General::Database$/ExtractPartsFromByteArray()
    at General::Database$/ExtractRobotFromByteArray()
    at Game::ControllerMainMenu()
    at Main/update()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00003E9B) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://incredibots.com/if/game.php
SWF URL: https://incredibots.com/if/incredibots2.swf?1604326052

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-02-01
Channel: nightly
Built: 2024-02-01T00:16:24.742Z
Commit: abc88154450b6abe00d69a2100ef43ed9ce6fb8f
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 104991

**Comment by n0samu** [comment] 2024-07-03 05:08
Duplicate of #10520

**Closed by n0samu** 2024-07-03 05:08 UTC
Labels: duplicate, avm2, error-report, amf
