### ISSUE TITLE
Error on https://www.comdotgame.com/play/super-deepthroat

### ISSUE THREAD

**Issue by JoaoM818** [ruffle-rs/ruffle#11791] opened 2023-06-29 11:09 UTC
# Error Info
Error name: Error
Error message: panicked at 'not implemented: Unimplemented opcode Max', render/naga-pixelbender/src/lib.rs:725:29
Error stack:
```
Error: panicked at 'not implemented: Unimplemented opcode Max', render/naga-pixelbender/src/lib.rs:725:29
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2400:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h29556e60c8892742 (wasm://wasm/02cc33b2:wasm-function[8720]:0x852359)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02cc33b2:wasm-function[5672]:0x76de24)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02cc33b2:wasm-function[8582]:0x84ded1)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h38d5ad46b2101964 (wasm://wasm/02cc33b2:wasm-function[7220]:0x7e815c)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::h499ce55c412b9194 (wasm://wasm/02cc33b2:wasm-function[826]:0x2c6f95)
    at ruffle_core::avm2::function::Executable::exec::h7f5c710bb48597ca (wasm://wasm/02cc33b2:wasm-function[814]:0x2b34ab)
    at ruffle_core::avm2::object::TObject::call_property::h92676acd1a3d08c2 (wasm://wasm/02cc33b2:wasm-function[1124]:0x398786)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hc75e401718bd829c (wasm://wasm/02cc33b2:wasm-function[2688]:0x5c2828)
    at ruffle_core::avm2::activation::Activation::run_actions::h0ade8598513bdd11 (wasm://wasm/02cc33b2:wasm-function[517]:0x29110)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at DT()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 750 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f623ea7559ef39d96ebb0ca7530586b8.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/super-deepthroat
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f623ea7559ef39d96ebb0ca7530586b8.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-29
Channel: nightly
Built: 2023-06-29T00:21:28.268Z
Commit: 1430e98851fb6f6c0867343386fcdefd3bef2fb8
Is extension: true

# Metadata
width: 700
height: 600
frameRate: 30
numFrames: 3
swfVersion: 11
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 2251296

**Comment by n0samu** [comment] 2023-06-29 11:13
Duplicate of #11695

**Closed by n0samu** 2023-06-29 11:13 UTC
Labels: duplicate, nsfw, error-report
