### ISSUE TITLE
Error on http://img.lum.dolimg.com/v1/files/640e5ff0-7f37-11e4-a924-069a12000069/4e2c12308b84c584105a05c5_flash/index.html

### ISSUE THREAD

**Issue by kcprincess** [ruffle-rs/ruffle#11857] opened 2023-07-02 16:21 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 2 but the index is 2', /home/runner/.cargo/git/checkouts/nihav-vp6-660fee9efdd4622a/9416fcc/nihav-duck/src/codecs/vp56.rs:1032:12
Error stack:
```
Error: panicked at 'index out of bounds: the len is 2 but the index is 2', /home/runner/.cargo/git/checkouts/nihav-vp6-660fee9efdd4622a/9416fcc/nihav-duck/src/codecs/vp56.rs:1032:12
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2400:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h02df5e9c2be9a573 (wasm://wasm/02ce7e4a:wasm-function[8732]:0x858ef5)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02ce7e4a:wasm-function[5685]:0x77e246)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02ce7e4a:wasm-function[8594]:0x854a70)
    at core::panicking::panic_bounds_check::h0cfce459260a0a82 (wasm://wasm/02ce7e4a:wasm-function[6862]:0x7d8aec)
    at nihav_duck::codecs::vp56::VP56Decoder::predict_dc::h2d58dcdb9ffd938a (wasm://wasm/02ce7e4a:wasm-function[1901]:0x4dc964)
    at nihav_duck::codecs::vp56::VP56Decoder::decode_planes::hfc504ef38713c8a0 (wasm://wasm/02ce7e4a:wasm-function[527]:0xa8d04)
    at <ruffle_video_software::decoder::vp6::Vp6Decoder as ruffle_video_software::decoder::VideoDecoder>::decode_frame::h08672e98999b8b7a (wasm://wasm/02ce7e4a:wasm-function[675]:0x214ec4)
    at <ruffle_video_software::backend::SoftwareVideoBackend as ruffle_video::backend::VideoBackend>::decode_video_stream_frame::hbe189597894e70c9 (wasm://wasm/02ce7e4a:wasm-function[2356]:0x56d4db)
    at ruffle_core::display_object::video::Video::seek::hce8d00237384ccd2 (wasm://wasm/02ce7e4a:wasm-function[712]:0x246242)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: http://img.lum.dolimg.com/v1/files/640e5ff0-7f37-11e4-a924-069a12000069/4e2c12308b84c584105a05c5_flash/preLoader.swf
Param scale: exactfit
Param allowScriptAccess: always
Param bgcolor: 000000
Param base: .
Param menu: false
Param wmode: transparent
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://img.lum.dolimg.com/v1/files/640e5ff0-7f37-11e4-a924-069a12000069/4e2c12308b84c584105a05c5_flash/index.html?refOverride=na&coreGameId=4e2c12308b84c584105a05c5&apiVersion=&fileURL=http%3A%2F%2Fa.dolimg.com%2Fmedia%2Fen-US%2Fgames%2Fnondxdgames%2Fpre_mch_minniesmasqueradematchup%2FpreLoader.swf&minimumFlashPlayerVersion=10&techType=AS3&width=750&height=500&title=Minnie%27s%20Masquerade%20Match%20Up&color=000000&wmode=transparent&shrinkToFit=false&assetId=1854167&assetName=gam%7Cdjr%7Cmic%7Cdol%7Cspl%7Cfas%7C4e2c12308b84c584105a05c5%7Cminnies-masquerade-match-up&assetType=gam&bu=djr&gameName=minnies-masquerade-match-up&gameType=spl&genre=fas&owner=dol&property=mic
SWF URL: http://img.lum.dolimg.com/v1/files/640e5ff0-7f37-11e4-a924-069a12000069/4e2c12308b84c584105a05c5_flash/preLoader.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-01
Channel: nightly
Built: 2023-07-01T00:25:59.437Z
Commit: 29a5c6a4cd9918d5e1eb89cc42ccd03d4e920931
Is extension: true

# Metadata
width: 750
height: 500
frameRate: 16
numFrames: 1
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 78957

**Comment by Lord-McSweeney** [comment] 2023-07-02 16:22
Already fixed by https://github.com/ruffle-rs/ruffle/pull/11831, duplicate of #11855.

**Closed by Lord-McSweeney** 2023-07-02 16:22 UTC
Labels: error-report
