### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by 11aa2323** [ruffle-rs/ruffle#13638] opened 2023-10-20 19:44 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.770f9f77ba77cd048ff7.js:1:53228)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h307f95dbfd4e7fe6 (wasm://wasm/03297862:wasm-function[9716]:0x98c95f)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/03297862:wasm-function[6377]:0x891359)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/03297862:wasm-function[9525]:0x987928)
    at core::result::unwrap_failed::h8b3db0f11171b57b (wasm://wasm/03297862:wasm-function[7994]:0x90dabe)
    at <T as wgpu::context::DynContext>::device_create_texture::he876a6b2d583c4cf (wasm://wasm/03297862:wasm-function[7103]:0x8c9db8)
    at wgpu::Device::create_texture::h1488ca4a9eae3889 (wasm://wasm/03297862:wasm-function[5424]:0x840e60)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h6bc32d323fa51381 (wasm://wasm/03297862:wasm-function[5241]:0x82fab8)
    at ruffle_core::display_object::render_base::h3a668d845d026b36 (wasm://wasm/03297862:wasm-function[598]:0x149228)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::haf72a4b5fbd8e829 (wasm://wasm/03297862:wasm-function[6964]:0x8b741f)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00009BC8) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1697806188%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F498000%2F498969_Super_Mario_63__2009_.swf%3F1353774292%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226532d62354938%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A900%2C%22height%22%3A600%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F498000%2Fflash_498969_card.png%3Ff1623161851%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/498000/498969_Super_Mario_63__2009_.swf?1353774292

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-20
Channel: nightly
Built: 2023-10-20T00:20:58.027Z
Commit: 8b5b135a2d08ed7b311fd0d081b32bd087e24d21
Is extension: false

# Metadata
width: 450
height: 300
frameRate: 32
numFrames: 25
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 19339460

**Comment by n0samu** [comment] 2023-11-11 22:03
Duplicate of #13011

**Closed by n0samu** 2023-11-11 22:03 UTC
Labels: duplicate, render-wgpu, error-report
