### ISSUE TITLE
Error on https://flashstorage.games/embed/xenos

### ISSUE THREAD

**Issue by prithu121** [ruffle-rs/ruffle#14047] opened 2023-11-17 09:35 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.9319559a195fae019006.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb1c47d692dbcedf6 (wasm://wasm/0336f48a:wasm-function[9803]:0x9b0c0a)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/0336f48a:wasm-function[6278]:0x89aea5)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/0336f48a:wasm-function[9603]:0x9aba14)
    at core::result::unwrap_failed::hbe79a418fab461ff (wasm://wasm/0336f48a:wasm-function[7622]:0x90fbe2)
    at <T as wgpu::context::DynContext>::device_create_texture::hb8897fdf54cef433 (wasm://wasm/0336f48a:wasm-function[7078]:0x8e114d)
    at wgpu::Device::create_texture::h61f546518006c553 (wasm://wasm/0336f48a:wasm-function[5459]:0x854c03)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::hd39cec26a444aa9f (wasm://wasm/0336f48a:wasm-function[5304]:0x84643d)
    at ruffle_core::display_object::render_base::hadfe98c437b29b3b (wasm://wasm/0336f48a:wasm-function[625]:0x147af2)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::ha42887c16736696b (wasm://wasm/0336f48a:wasm-function[6931]:0x8cd664)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 (0x00003EA0) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://flashstorage.games/embed/xenos
SWF URL: https://flashstorage.games/public/storage/games/xenos-files/launcher.swf?multi_file=true

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-17
Channel: nightly
Built: 2023-11-17T00:14:46.670Z
Commit: a78a67ee24a4a172e6fae0ce03979e63864270c6
Is extension: false

# Metadata
width: 720
height: 480
frameRate: 30
numFrames: 4
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 21932555

**Comment by Dinnerbone** [comment] 2024-07-12 22:07
Duplicate of #13908

**Closed by Dinnerbone** 2024-07-12 22:07 UTC
Labels: duplicate, error-report
