### ISSUE TITLE
Error on https://funkypotato.com/tequila-zombies-3/

### ISSUE THREAD

**Issue by perelowski** [ruffle-rs/ruffle#15684] opened 2024-03-21 13:27 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f77055/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Apple M1, or similar"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: best
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: /gamez/tequila-zombies-3.swf
Param movie: /gamez/tequila-zombies-3.swf
Param quality: best
Param bgcolor: #000000
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://funkypotato.com/tequila-zombies-3/?preview_id=20366&preview_nonce=6a90124da1&_thumbnail_id=20370&preview=true
SWF URL: https://funkypotato.com/gamez/tequila-zombies-3.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-17
Channel: nightly
Built: 2024-03-17T00:07:02.167Z
Commit: 5d6d097fb1989ac381653270ad8127e7d2f4d4db
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 21
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 38270902

**Comment by n0samu** [comment] 2024-07-27 07:02
Duplicate of #13748

**Closed by n0samu** 2024-07-27 07:02 UTC
Labels: duplicate, error-report
