### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by lupeyboy** [ruffle-rs/ruffle#4073] opened 2021-04-20 22:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1618924278:1:6940)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a2ffc5857401154b1061e24f42acb224.wasm:wasm-function[820]:0x21a777)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a2ffc5857401154b1061e24f42acb224.wasm:wasm-function[1218]:0x29e3dc)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a2ffc5857401154b1061e24f42acb224.wasm:wasm-function[3677]:0x429d0e)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://uploads.ungrounded.net/ruffle_wrapper/lib/a2ffc5857401154b1061e24f42acb224.wasm:wasm-function[2677]:0x38f16f)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/a2ffc5857401154b1061e24f42acb224.wasm:wasm-function[3879]:0x42f6f9)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a2ffc5857401154b1061e24f42acb224.wasm:wasm-function[3987]:0x43249c)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h7c4957b2db028591 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a2ffc5857401154b1061e24f42acb224.wasm:wasm-function[1160]:0x28cbd4)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h595933476ce8a839 (https://uploads.ungrounded.net/ruffle_wrapper/lib/a2ffc5857401154b1061e24f42acb224.wasm:wasm-function[4120]:0x4345ce)
    at S (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1618924278:1:3010)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1618924278%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2260006643.688bd9f9a4f70696a46d3210b39ba73f074ccb3937dd45%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22607f4ab6103ed%22%2C%22NewgroundsAPI_SessionID%22%3A%228KlNyLLbR5UHBhqgki9a87005ca3311f35e85ba7cde46976a6330dc0441eq48v%22%2C%22NewgroundsAPI_UserName%22%3A%22lupeyboy%22%2C%22NewgroundsAPI_UserID%22%3A8354292%2C%22ng_username%22%3A%22lupeyboy%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-20
Channel: nightly
Built: 2021-04-20T00:42:08.381Z
Commit: c993ad8964774d53863772c82d50928c2e990afd

**Comment by Poopooracoocoo** [comment] 2021-11-29 10:49
Duplicate of #4038

**Closed by Poopooracoocoo** 2021-11-29 10:49 UTC
Labels: duplicate, error-report
