### ISSUE TITLE
Error on https://games.crazygames.com/en_US/electric-man/index.html

### ISSUE THREAD

**Issue by xxsteelshotxx3** [ruffle-rs/ruffle#6803] opened 2022-04-25 15:34 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
@https://files.crazygames.com/gameframe/ruffle/2022-02-19/core.ruffle.92a315f151da5016c01c.js:1:6973
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::ha69306374a0d7c42]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h9279eef47cf85b81]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hd4ed35f37e0c71aa]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h47a0e203360b6c10]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h4ca53049f45e3264]@[wasm code]
<?>.wasm-function[core::panicking::panic::h35778e3c18266c93]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once::h536ce3a2d6da6677]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::hf35d006d9e5c7bf8]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h8935321d91c5bc87]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::do_action::h5e94226e32f06f82]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::ha788639cb2d721f9]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::Avm1::run_stack_frame_for_action::h4b48152ee24c0776]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::hacbe5df29d340576]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::he9f9c79a3f561482]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h466717537c66ebc6]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h827399ce0eead02e]@[wasm code]
wasm-stub@[native code]
R@https://files.crazygames.com/gameframe/ruffle/2022-02-19/core.ruffle.92a315f151da5016c01c.js:1:3079
c@https://files.crazygames.com/gameframe/ruffle/2022-02-19/core.ruffle.92a315f151da5016c01c.js:1:2522
r@https://gameframe.crazygames.com/crazygames-gameframe-v1.bundle.js:2:337539
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.crazygames.com/en_US/electric-man/index.html

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-19
Channel: nightly
Built: 2022-02-19T00:15:44.456Z
Commit: 2ca62ecf4bac5696d2da084b1f5d5c6ba2a4e0f7
Is extension: false

**Comment by Poopooracoocoo** [comment] 2022-04-27 05:13
Duplicate of #4932

**Closed by Poopooracoocoo** 2022-04-27 05:13 UTC
Labels: error-report
