### ISSUE TITLE
Ruffle not working on windows 11

### ISSUE THREAD

**Issue by Wave3prime15** [ruffle-rs/ruffle#18902] opened 2024-12-08 05:19 UTC
### Describe what you were doing

Yo, Am trying to get ruffle working for windows 11 but i get this error when running ruffle

Any help plz

![Image](https://github.com/user-attachments/assets/1553eee2-d015-4841-a384-40e8dc5f13db)

### What does the crash message say?

panicked at desktop\src\app.rs:466:14:
GUI controller should be created: Parent device is lost

### Ruffle Version

0.1.0-nightly (8e4fbd262ba5deb3663f8709aa1ca19154620617 2024-12-07)

### Affected platform

Desktop app

### Operating system

Windows 10.0.26100 (Windows 11 Enterprise) [64-bit]

**Comment by evilpie** [comment] 2024-12-08 14:17
Duplicate of #18690

**Closed by evilpie** 2024-12-08 14:17 UTC
Labels: bug, panic, render-wgpu, windows
