### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Racmdx** [ruffle-rs/ruffle#5756] opened 2021-11-28 22:18 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18
    at u.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1637687094:1:7173)
    at std::sync::once::Once::call_once::{{closure}}::ha2a6e9c1727c0056 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ee4caa32f0417046b099.wasm:wasm-function[998]:0x2e492f)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ee4caa32f0417046b099.wasm:wasm-function[1330]:0x355f8f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5c1b8acd952e19de (https://uploads.ungrounded.net/ruffle_wrapper/lib/ee4caa32f0417046b099.wasm:wasm-function[4703]:0x4f1f00)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (https://uploads.ungrounded.net/ruffle_wrapper/lib/ee4caa32f0417046b099.wasm:wasm-function[3305]:0x4a11e9)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/ee4caa32f0417046b099.wasm:wasm-function[4766]:0x4f4896)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ee4caa32f0417046b099.wasm:wasm-function[4973]:0x4ff418)
    at core::panicking::panic::hceae0c79b0247f98 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ee4caa32f0417046b099.wasm:wasm-function[4699]:0x4f1731)
    at core::ops::function::FnOnce::call_once::h9c6fd61ccc88d039 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ee4caa32f0417046b099.wasm:wasm-function[1042]:0x2fe9c7)
    at ruffle_core::avm1::function::Executable::exec::h296dedb8318b3717 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ee4caa32f0417046b099.wasm:wasm-function[417]:0x1530e7)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1637687094%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2217984024.1ee72c04bf3a16279d92ae4c72921a75c595350d489842%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261a3fb40c353e%22%2C%22NewgroundsAPI_SessionID%22%3A%22zQgAVVjUXIHpDAOFiHVT86d6ff297d53521eddff8b1b18b2d09e5c3dc7aetMTL%22%2C%22NewgroundsAPI_UserName%22%3A%22SwordsNSouls%22%2C%22NewgroundsAPI_UserID%22%3A10067168%2C%22ng_username%22%3A%22SwordsNSouls%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-23
Channel: nightly
Built: 2021-11-23T00:14:22.573Z
Commit: cf1d0e7624fb84d23087bc0611e3dbf92dcb65e7
Is extension: false

**Comment by Poopooracoocoo** [comment] 2021-11-29 09:59
Link to Chibi Knight on Newgrounds: 
https://www.newgrounds.com/portal/view/526470

**Comment by Poopooracoocoo** [comment] 2021-11-29 10:00
Duplicate of #3756

**Closed by Poopooracoocoo** 2021-11-29 10:00 UTC
Labels: duplicate, error-report
