### ISSUE TITLE
Error on https://www.quickflashgames.com/games/black-navy-war/

### ISSUE THREAD

**Issue by so6228** [ruffle-rs/ruffle#14098] opened 2023-11-21 14:56 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.3ddb53debfc07c67b1a3.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h878d7563074f0d48 (wasm://wasm/03377f22:wasm-function[9789]:0x9b3ba3)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/03377f22:wasm-function[6285]:0x8a47f3)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/03377f22:wasm-function[9596]:0x9aeb17)
    at core::result::unwrap_failed::hbe79a418fab461ff (wasm://wasm/03377f22:wasm-function[7620]:0x91377a)
    at <T as wgpu::context::DynContext>::device_create_texture::hb8897fdf54cef433 (wasm://wasm/03377f22:wasm-function[7080]:0x8e4ed6)
    at wgpu::Device::create_texture::h61f546518006c553 (wasm://wasm/03377f22:wasm-function[5446]:0x85d89a)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::hc166507108c4e85f (wasm://wasm/03377f22:wasm-function[5294]:0x85089d)
    at ruffle_core::display_object::render_base::hc9a4f62457ab66b4 (wasm://wasm/03377f22:wasm-function[628]:0x150982)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h0f7fcec6f6dcbee5 (wasm://wasm/03377f22:wasm-function[6943]:0x8d0db6)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00009BC5) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.quickflashgames.com/games/black-navy-war/
SWF URL: https://www.quickflashgames.com/static/swfs/black-navy-war/navalBattle.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-21
Channel: nightly
Built: 2023-11-21T00:14:48.522Z
Commit: 1ce772befae148f2f6260dcb82e7a224e3d09d6b
Is extension: false

# Metadata
width: 900
height: 550
frameRate: 25
numFrames: 2
swfVersion: 10
backgroundColor: #006600
isActionScript3: true
uncompressedLength: 2628412

**Comment by Dinnerbone** [comment] 2024-07-12 22:04
Duplicate of #14001

**Closed by Dinnerbone** 2024-07-12 22:04 UTC
Labels: duplicate, render-wgpu, error-report
