### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by ExtemTheHedgepog** [ruffle-rs/ruffle#4374] opened 2021-05-20 05:08 UTC
Ok, so I was playing Madness: Project Nexus Classic with my controller using XPadder. I used left stick inwards, which I had mapped to Shift (the Bullet-Time button), and it just crashed on me. That's it. I don't know what happened ¯\_(ツ)_/¯

# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:661:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:661:48
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1621439857:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d044f0d011060fa3da19.wasm:wasm-function[1075]:0x283e42)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d044f0d011060fa3da19.wasm:wasm-function[949]:0x25c9fa)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d044f0d011060fa3da19.wasm:wasm-function[3823]:0x407344)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d044f0d011060fa3da19.wasm:wasm-function[2971]:0x3a837e)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/d044f0d011060fa3da19.wasm:wasm-function[4031]:0x40ce47)
    at core::panicking::panic_fmt::hd44f353696296fec (https://uploads.ungrounded.net/ruffle_wrapper/lib/d044f0d011060fa3da19.wasm:wasm-function[4179]:0x4138fe)
    at core::panicking::panic::ha58827a77b951c10 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d044f0d011060fa3da19.wasm:wasm-function[3974]:0x40aa17)
    at ruffle_render_webgl::WebGlRenderBackend::register_bitmap::h9c244c34e9655bce (https://uploads.ungrounded.net/ruffle_wrapper/lib/d044f0d011060fa3da19.wasm:wasm-function[1303]:0x2bb6e9)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_raw::he1ed7151f7896663 (https://uploads.ungrounded.net/ruffle_wrapper/lib/d044f0d011060fa3da19.wasm:wasm-function[3180]:0x3c3e19)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1621439857%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2219602244.95f5a34f5e5a06df7802c8a28806fe48a3d4c5e2730fda%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2260a5e5f43b70f%22%2C%22NewgroundsAPI_SessionID%22%3A%22qfQoPHgCWOZvLTEbiG6g0778bb452e507f68948dc8f647ea1ce13f5877fbEazj%22%2C%22NewgroundsAPI_UserName%22%3A%22ExtemTheHedgehog%22%2C%22NewgroundsAPI_UserID%22%3A7914585%2C%22ng_username%22%3A%22ExtemTheHedgehog%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-19
Channel: nightly
Built: 2021-05-19T00:14:09.203Z
Commit: 1dd669a0e37288af3acc786c6a924c579f4ec81b

**Comment by Poopooracoocoo** [comment] 2021-11-29 11:06
Duplicate of #5477

**Closed by Poopooracoocoo** 2021-11-29 11:06 UTC
Labels: duplicate, error-report
