### ISSUE TITLE
Error on http://www.freeworldgroup.com/g/i/zombidle.htm

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#17112] opened 2024-07-13 19:22 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/f9e3de5/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/f9e3de5/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
    at n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ad391ff401a39a13a919.js:1:79203)
    at ruffle_web.wasm.js_sys::Error::new::hda2cb16801956d39 (wasm://wasm/ruffle_web.wasm-033832ae:wasm-function[12812]:0x9e5135)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::ha3b644c21d404714 (wasm://wasm/ruffle_web.wasm-033832ae:wasm-function[9842]:0x97ad84)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-033832ae:wasm-function[6489]:0x86d9e5)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-033832ae:wasm-function[10240]:0x9a60e2)
    at ruffle_web.wasm.core::panicking::panic_display::hbd841ae85eb3dff4 (wasm://wasm/ruffle_web.wasm-033832ae:wasm-function[9775]:0x972fc3)
    at ruffle_web.wasm.core::option::expect_failed::h637b3c5bf9792ea8 (wasm://wasm/ruffle_web.wasm-033832ae:wasm-function[10813]:0x9b060d)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::hf8312b798bb217ef (wasm://wasm/ruffle_web.wasm-033832ae:wasm-function[770]:0xdfa78)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::utils::byte_array::read_object::hf001f3b0d2cb0921 (wasm://wasm/ruffle_web.wasm-033832ae:wasm-function[1087]:0x306ae0)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::h8e5a2e0eb95ca2e4 (wasm://wasm/ruffle_web.wasm-033832ae:wasm-function[1133]:0x32ff2f)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at com.berzerkstudio::ModelFla/loadFromByteArray()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadNextFla()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadBunch()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadAllFlas()
    at com.zombidle::MainGameWebStarling/loadModelFlas()
    at com.zombidle::MainGameWebStarling/loadZipFile()
    at Function/apply()
    at com.lachhh.io::Callback/call()
    at com.lachhhStarling::StarlingMain$/startGame()
    at MethodInfo-4267()
    at starling.utils::AssetManager/loadQueue()
    at com.lachhhStarling::StarlingMain$/loadAssetsDesktop()
    at MethodInfo-4265()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-2013()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 (0x00001C20) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: http://www.freeworldgroup.com/g/i/zombidle.htm#
SWF URL: http://www.freeworldgroup.com/g/zombidle/zombidle.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-13
Channel: nightly
Built: 2024-07-13T00:05:49.715Z
Commit: 48db0e23c42ca0a98ed7027aa10a1c799ef2ec34
Is extension: false

# Metadata
width: 960
height: 640
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 53335628

**Comment by n0samu** [comment] 2024-07-14 04:45
Duplicate of #10174

**Closed by n0samu** 2024-07-14 04:45 UTC
Labels: duplicate, error-report, amf
