### ISSUE TITLE
FutureSplash Movies

### ISSUE THREAD

**Issue by LeoKids** [ruffle-rs/ruffle#18260] opened 2024-10-13 21:18 UTC
**Describe the feature**
Flash Player supports running Adobe Flash movies and FutureSplash movies,however Ruffle currently only supports Adobe Flash movies,Adding support for FutureSplash will make many very early movies/content avaliable to be played on Ruffle. The file extension of those is .spl

**Comment by Lord-McSweeney** [comment] 2024-10-13 21:20
Ruffle should support FutureSplash movies as they are the same format as SWF; is there a file picker somewhere that only accepts `.swf` and not `.spl`? If the problem is with the movie itself, can you upload the SPL file? Thanks!

**Comment by n0samu** [comment] 2024-10-14 18:13
Closing, will reopen if a valid problem is identified

**Closed** 2024-10-14 18:12 UTC
Labels: enhancement
