### ISSUE TITLE
Error on https://files.twoplayergames.org/files/games/ruffle/player.html

### ISSUE THREAD

**Issue by Rohith1009-MR** [ruffle-rs/ruffle#8719] opened 2022-12-07 14:40 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://files.twoplayergames.org/files/games/ruffle/core.ruffle.f06ff3e73d33f54c7676.js:1:7449)
    at std::sync::once::Once::call_once::{{closure}}::hb5c0ce1b32735158 (wasm://wasm/0169505e:wasm-function[1401]:0x2f4523)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/0169505e:wasm-function[1362]:0x2ec7f8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h98d22a5c843316e5 (wasm://wasm/0169505e:wasm-function[4796]:0x43b014)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/0169505e:wasm-function[3508]:0x400d54)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/0169505e:wasm-function[4974]:0x4407a4)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/0169505e:wasm-function[4883]:0x43c828)
    at core::ops::function::FnOnce::call_once::hdd1cdf4581bca2d8 (wasm://wasm/0169505e:wasm-function[1010]:0x284a03)
    at ruffle_core::avm1::function::Executable::exec::h5653e67d8d507650 (wasm://wasm/0169505e:wasm-function[354]:0xdd106)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf7e31a222a3b0e4f (wasm://wasm/0169505e:wasm-function[448]:0x14db93)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://files.twoplayergames.org/files/games/ruffle/player.html?file=o1/Electricman_2.swf
SWF URL: https://files.twoplayergames.org/files/games/o1/Electricman_2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-23
Channel: nightly
Built: 2022-08-23T00:25:17.566Z
Commit: 25a77869abee2575767a9d33a6054094b5f39b82
Is extension: false

**Comment by n0samu** [comment] 2022-12-07 21:15
Duplicate of #4932

**Closed by n0samu** 2022-12-07 21:15 UTC
Labels: duplicate, error-report
