### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Alerixis** [ruffle-rs/ruffle#8218] opened 2022-10-06 22:34 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.a5a3737e9b5245475835.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/017ff2d2:wasm-function[1024]:0x2a831c)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017ff2d2:wasm-function[1487]:0x32b6b4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/017ff2d2:wasm-function[4934]:0x4897bc)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017ff2d2:wasm-function[3631]:0x446643)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017ff2d2:wasm-function[5089]:0x48cc72)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/017ff2d2:wasm-function[4229]:0x4706df)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h87f89f6d933b9a5b (wasm://wasm/017ff2d2:wasm-function[2557]:0x3e2fc2)
    at ruffle_core::display_object::render_base::h86fa7eaf5d8f56b5 (wasm://wasm/017ff2d2:wasm-function[1204]:0x2e8135)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hfa8c7706dc71138d (wasm://wasm/017ff2d2:wasm-function[3855]:0x45c4a6)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1665064988%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22633f576370252%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-06
Channel: nightly
Built: 2022-10-06T00:17:35.767Z
Commit: 4b2907ead56e5806f441fcb7e32e1030166cb2d2
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by n0samu** [comment] 2022-10-06 22:36
Duplicate of #7978

**Closed by n0samu** 2022-10-06 22:36 UTC
Labels: duplicate, error-report
