### ISSUE TITLE
Plasma Orchestra: Trail doesn't fade away after few seconds

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9574] opened 2023-02-14 14:47 UTC
### Describe the bug

Tested on Ruffle Nightly 2023-02-14
Plasma Orchestra SWF used: [388145_PLASMAORCHESTRAJOE2.zip](https://github.com/ruffle-rs/ruffle/files/10738620/388145_PLASMAORCHESTRAJOE2.zip)

This is what the game looks like in the Ruffle Demo.

https://user-images.githubusercontent.com/36887711/218770996-1f0ecc60-3d21-458f-a432-8abcfc063d14.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/218771487-1244fb5d-d17f-488c-81f4-f832c3da3da2.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

**Comment by n0samu** [comment] 2023-02-15 03:23
This is caused by Ruffle's incorrect implementation of the blur filter effect. Same problem as #9505.

**Comment by n0samu** [comment] 2023-03-03 14:41
I was wrong about this being the same problem as #9505, but I think it really is the same problem that I've been seeing in Symphony (#9832).

**Comment by n0samu** [comment] 2023-07-25 00:10
Fixed by #12225

**Closed by n0samu** 2023-07-25 00:10 UTC
Labels: bug, filter-effects
