### ISSUE TITLE
Run Hopy Run: Flickery buttons and instadeath softlock

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9117] opened 2023-01-11 16:22 UTC
### Describe the bug

[RunHopyRunAPI.zip](https://github.com/ruffle-rs/ruffle/files/10397338/RunHopyRunAPI.zip)

Yoinked the SWF itself for direct testing.
Certain clickable buttons seem to flicker wildly, like the region select buttons at the start, or the start level and the 2 arrow buttons on top of the map screen.

The game also breaks as soon as you start the first level, since it fills up the starting cavern as a solid wall and spawn kills you instantly.

![Hopy1](https://user-images.githubusercontent.com/78768499/211859032-45b26ed8-29b9-407b-9062-fe72c2e606f7.png)

### Expected behavior

The buttons shouldn't flicker rapidly and the starting cavern should look like this.

![Hopy2](https://user-images.githubusercontent.com/78768499/211859194-3ef4f43a-0254-43a9-9036-447516c0876d.png)

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by waspennator** [comment] 2023-02-25 02:17
Buttons are still flickering, there are weird visual glitches with the brick walls still, and for some reason my fruit count is now maxed out at 999, but I don't fall through the floor anymore and I was able to beat the first level now.

![Hopy3](https://user-images.githubusercontent.com/78768499/221331022-07888e1d-358c-4c99-9e2b-428060ce424a.png)

**Comment by waspennator** [comment] 2023-03-18 02:51
Tested on latest nightly, the buttons are no longer flickering wildly now and the maxed out fruits seems to be the same with testing it out on Flash, so the only issue left are the bricks you spawn infront of not being darker and more in the background.

**Comment by waspennator** [comment] 2023-04-07 01:53
Update, seems like build 2023-04-01 has broken the game again, Hopy has regressed back to falling through the floor and dying constantly.

**Comment by Toad06** [comment] 2023-04-07 09:09
I bisected this regression to c85910b46d66dd621e0566c220690c952fd677e3. This is the same commit that also causes #10579.

**Comment by waspennator** [comment] 2023-04-19 01:57
Hopy no longer seems to be falling through the floor as of the latest nightly, so that's good.

I am noticing a new issue playing through level 1, when you get to this part of the level, you can't pick up any of the fruit hanging around in the air unlike in flash.

![Hopy Ruffle 1](https://user-images.githubusercontent.com/78768499/232946760-60915166-f5b9-490d-a388-5f956cf3f49a.png)

**Comment by Toad06** [comment] 2023-04-19 08:45
The initial issue was fixed by #10725.

For the other issue you mentioned, I think it would be better if you open a new bug report, because this doesn't seem to be a regression (I checked with nightly-2023-02-24 and the issue was already there).

**Comment by n0samu** [comment] 2023-05-03 09:30
Closing since the original issue is fixed

**Closed by n0samu** 2023-05-03 09:30 UTC
Labels: bug, avm2
