### ISSUE TITLE
Error on https://www.gameflare.com/embed/vision-by-proxy/

### ISSUE THREAD

**Issue by kaiserrolll** [ruffle-rs/ruffle#13964] opened 2023-11-11 18:26 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    Copy of Y 4294967295..449 would end up overrunning the bounds of the Destination texture of Y size 450

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    Copy of Y 4294967295..449 would end up overrunning the bounds of the Destination texture of Y size 450


    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://www.gameflare.com/emulators/ruffle/core.ruffle.28be52cdb961c17d775f.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hef126beb4c745969 (wasm://wasm/03400b06:wasm-function[9963]:0x9cfe7b)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/03400b06:wasm-function[6528]:0x8d0434)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/03400b06:wasm-function[9760]:0x9cabe2)
    at core::ops::function::Fn::call::hab4d293b6b61afb0 (wasm://wasm/03400b06:wasm-function[6709]:0x8dab30)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::ha8d57641bba5ca8c (wasm://wasm/03400b06:wasm-function[5396]:0x86d463)
    at wgpu::backend::direct::Context::handle_error::h9d4ff0caae47f243 (wasm://wasm/03400b06:wasm-function[2759]:0x68c68a)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_texture::h91d0b8a3b74306df (wasm://wasm/03400b06:wasm-function[9239]:0x9a8c7e)
    at wgpu::CommandEncoder::copy_texture_to_texture::h2f0cfabfd193afc6 (wasm://wasm/03400b06:wasm-function[8705]:0x987aa6)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::apply_filter::had47d840b94e6806 (wasm://wasm/03400b06:wasm-function[2123]:0x5d7021)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::applyFilter()
    at VisionByProxy2/constantUpdate()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.utils::Timer/onUpdate()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon R3 Graphics (stoney LLVM 15.0.7 DRM 3.42 5.10.194-23408-gfb04e5e80fd6), OpenGL ES 3.2)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/vision-by-proxy/
SWF URL: https://data.gameflare.com/games/1989/gCNjnsfZmg6KnK.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-11
Channel: nightly
Built: 2023-11-11T00:21:36.380Z
Commit: 172b76d01f42ba71bedba7be5f36ddce1c5c5346
Is extension: false

# Metadata
width: 650
height: 450
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 7807481

**Comment by n0samu** [comment] 2024-01-19 01:23
Duplicate of #12359

**Closed by n0samu** 2024-01-19 01:23 UTC
Labels: duplicate, error-report
