### ISSUE TITLE
Error on https://www.comdotgame.com/play/kasumi-rebirth

### ISSUE THREAD

**Issue by Aroe54098** [ruffle-rs/ruffle#11235] opened 2023-05-27 10:46 UTC
<font class="papago-parent"><font class="papago-source" style="display:none;"># Error Info
</font>오류 정보</font><font class="papago-parent"><font class="papago-source" style="display:none;">Error name:</font>오류 이름:</font><font class="papago-parent"><font class="papago-source" style="display:none;"> Error
</font>오류</font><font class="papago-parent"><font class="papago-source" style="display:none;">Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:640:18
</font>오류 메시지: '없음' 값의 '옵션::unwrap()'에서 패닉 상태에 빠졌습니다. core/src/display_object/container.rs:640:18</font><font class="papago-parent"><font class="papago-source" style="display:none;">Error stack:</font>오류 스택:</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">```
</font>```</font><font class="papago-parent"><font class="papago-source" style="display:none;">Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:640:18
</font>오류: '없음' 값의 'Option::unwrap()'이라는 이름의 'Core/src/display_object/container.rs:640:18 '에서 패닉 상태에 빠졌습니다.</font><font class="papago-parent"><font class="papago-source" style="display:none;">    at W.n.wbg.</font>W.N.W.Bg로</font><font class="papago-parent"><font class="papago-source" style="display:none;">__wbg_new_15d3966e9981a196 (https://echo.comdotgame.com/ruffle/core.ruffle.31c166ab9c2b119e4092.js:1:46508)
</font>__digg_new_15d3966e9981a196 (https://echo.comdotgame.com/ruffle/core.ruffle.31c166ab9c2b119e4092.js:1:46508)</font><font class="papago-parent"><font class="papago-source" style="display:none;">    at core::ops::function:</font>at core::ops::function:</font><font class="papago-parent"><font class="papago-source" style="display:none;">:FnOnce::call_once{{vtable.</font>:FnOnce::call_once{vtable.</font><font class="papago-parent"><font class="papago-source" style="display:none;">shim}}::h321a9078ff9936f2 (wasm://wasm/02962ab2:wasm-function[7834]:0x7cc186)
</font>shim}}::h321a9078ff9936f2 (wasm://wasm/02962ab2:wasm-function[7834]:0x7cc186)</font><font class="papago-parent"><font class="papago-source" style="display:none;">    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02962ab2:wasm-function[5302]:0x7125e6)
</font>at std::패닝::rust_bullet_with_hook::h8d0a63d0479a36c8(wasm://wasm/02962ab2:wasm-function[5302]:0x7125e6)</font><font class="papago-parent"><font class="papago-source" style="display:none;">    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02962ab2:wasm-function[7726]:0x7c7730)
</font>core::paning::h2a7f454a5f5da218 (wasm://wasm/02962ab2:wasm-function[7726]:0x7c7730)</font><font class="papago-parent"><font class="papago-source" style="display:none;">    at core::panicking::panic::ha3ebcac1438d9280 (wasm://wasm/02962ab2:wasm-function[7142]:0x79373f)
</font>core::paning::ha3ebcac1438d9280 (wasm://wasm/02962ab2:wasm-function[7142]:0x79373f)</font><font class="papago-parent"><font class="papago-source" style="display:none;">    at ruffle_core::display_object::container:</font>attruffle_core::display_object::device:</font><font class="papago-parent"><font class="papago-source" style="display:none;">:ChildContainer::replace_at_depth::h2de1d6a0c6867e00 (wasm://wasm/02962ab2:wasm-function[1539]:0x41e990)
</font>:ChildContainer::replace_at_depth::h2de1d6a0c6867e00 (wasm://wasm/02962ab2:wasm-function[1539]:0x41e990)</font><font class="papago-parent"><font class="papago-source" style="display:none;">    at ruffle_core::display_object::container::</font>attruffle_core::display_object::display_object::</font><font class="papago-parent"><font class="papago-source" style="display:none;">TDisplayObjectContainer::replace_at_depth::h21501d2f3172dfbe (wasm://wasm/02962ab2:wasm-function[4772]:0x6e70df)
</font>TDisplayObjectContainer::replace_at_depth::h21501d2f3172dfbe (wasm://wasm/02962ab2:wasm-function[4772]:0x6e70df)</font><font class="papago-parent"><font class="papago-source" style="display:none;">    at ruffle_core::display_object::movie_clip::</font>attruffle_core::display_object::display_object::truffle_core:</font><font class="papago-parent"><font class="papago-source" style="display:none;">MovieClip::instantiate_child::h195a33510c0b747d (wasm://wasm/02962ab2:wasm-function[732]:0x2765bc)
</font>MovieClip::instantiate_child::h195a33510c0b747d(wasm://wasm/02962ab2:wasm-function[732]:0x2765bc)</font><font class="papago-parent"><font class="papago-source" style="display:none;">    at ruffle_core::display_object::movie_clip::</font>attruffle_core::display_object::display_object::truffle_core:</font><font class="papago-parent"><font class="papago-source" style="display:none;">MovieClip::run_goto::</font>MovieClip::run_goto::</font><font class="papago-parent"><font class="papago-source" style="display:none;">{{closure}}::h7bf1329a46718fc5 (wasm://wasm/02962ab2:wasm-function[895]:0x2fa1d7)
</font>{{closure}}::h7bf1329a46718fc5(wasm://wasm/02962ab2:wasm-function[895]:0x2fa1d7)</font><font class="papago-parent"><font class="papago-source" style="display:none;">    at ruffle_core::display_object::movie_clip::</font>attruffle_core::display_object::display_object::truffle_core:</font><font class="papago-parent"><font class="papago-source" style="display:none;">MovieClip::run_goto::hff866e088751f047 (wasm://wasm/02962ab2:wasm-function[659]:0x2200cc)
</font>MovieClip::run_goto::hff866e088751f047(wasm://wasm/02962ab2:wasm-function[659]:0x2200cc)</font><font class="papago-parent"><font class="papago-source" style="display:none;">```
</font>```</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;"># Player Info
</font>플레이어 정보</font><font class="papago-parent"><font class="papago-source" style="display:none;">Allows script access: true
</font>스크립트 액세스 허용: true</font><font class="papago-parent"><font class="papago-source" style="display:none;">Player type:</font>플레이어 유형:</font><font class="papago-parent"><font class="papago-source" style="display:none;"> Object
</font>물건</font><font class="papago-parent"><font class="papago-source" style="display:none;">SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f7313836a835b6c3191ed00ca9751a1c.swf
</font>SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f7313836a835b6c3191ed00ca9751a1c.swf</font><font class="papago-parent"><font class="papago-source" style="display:none;">Param allowscriptaccess: always
</font>매개 변수 스크립트 액세스 허용: 항상</font><font class="papago-parent"><font class="papago-source" style="display:none;">Param bgcolor: ffffff
</font>매개변수 bg 색상: fffffff</font><font class="papago-parent"><font class="papago-source" style="display:none;">Param wmode: gpu
</font>매개 변수 w 모드: GPU</font><font class="papago-parent"><font class="papago-source" style="display:none;">Param base: https://echo.comdotgame.com/4x90xhl3k0/games/files/kasumi-rebirth/3.30/
</font>매개변수 기준: https://echo.comdotgame.com/4x90xhl3k0/games/files/kasumi-rebirth/3.30/</font><font class="papago-parent"><font class="papago-source" style="display:none;">Attribute 0: undefined
</font>특성 0: 정의되지 않음</font><font class="papago-parent"><font class="papago-source" style="display:none;">Attribute 1: undefined
</font>특성 1: 정의되지 않음</font><font class="papago-parent"><font class="papago-source" style="display:none;">Attribute 2: undefined
</font>특성 2: 정의되지 않음</font><font class="papago-parent"><font class="papago-source" style="display:none;">Attribute 3: undefined
</font>특성 3: 정의되지 않음</font><font class="papago-parent"><font class="papago-source" style="display:none;">Attribute 4: undefined
</font>특성 4: 정의되지 않음</font><font class="papago-parent"><font class="papago-source" style="display:none;">Attribute 5: undefined
</font>속성 5: 정의되지 않음</font><font class="papago-parent"><font class="papago-source" style="display:none;">Attribute 6: undefined
</font>특성 6: 정의되지 않음</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;"># Page Info
</font>페이지 정보</font><font class="papago-parent"><font class="papago-source" style="display:none;">Page URL: https://www.comdotgame.com/play/kasumi-rebirth
</font>페이지 URL: https://www.comdotgame.com/play/kasumi-rebirth</font><font class="papago-parent"><font class="papago-source" style="display:none;">SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f7313836a835b6c3191ed00ca9751a1c.swf
</font>SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f7313836a835b6c3191ed00ca9751a1c.swf</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;"># Browser Info
</font>브라우저 정보</font><font class="papago-parent"><font class="papago-source" style="display:none;">User Agent: Mozilla/5.0 (Linux; Android 13; SM-S916N Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.189 Whale/1.0.0.0 Crosswalk/27.102.0.14 Mobile Safari/537.36 NAVER(inapp; search; 1010; 11.21.8)
</font>사용자 에이전트: Mozilla/5.0(Linux; Android 13; SM-S916N Build/TP1A.220624.014; wv) Apple WebKit/537.36(KHTML, Gecko와 유사) 버전/4.0 크롬/102.0.5005.189 Whale/1.0 횡단보도/27.102.0.0.14 모바일 Safari536(NAVER) 검색 11.21(10.10.10.10.10.21) 검색</font><font class="papago-parent"><font class="papago-source" style="display:none;">Platform: Linux aarch64
</font>플랫폼: 리눅스 arch64</font><font class="papago-parent"><font class="papago-source" style="display:none;">Has touch support: true
</font>터치 지원 있음: true</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;"># Ruffle Info
</font>러플 정보</font><font class="papago-parent"><font class="papago-source" style="display:none;">Version: 0.1.0</font>버전: 0.1.0</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Name: nightly 2023-03-12
</font>이름 : 야간 2023-03-12</font><font class="papago-parent"><font class="papago-source" style="display:none;">Channel: nightly
</font>채널: 밤마다</font><font class="papago-parent"><font class="papago-source" style="display:none;">Built: 2023-03-12T00:19:04.440Z
</font>제작: 2023-03-12T00:19:04.440Z</font><font class="papago-parent"><font class="papago-source" style="display:none;">Commit: 1deebc87e869387c962f97b665d26785d0a2b52f
</font>커밋: 1deebc87e869387c962f97b665d26785d0a2b52f</font><font class="papago-parent"><font class="papago-source" style="display:none;">Is extension: false
</font>확장명: false</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;"># Metadata
</font>메타데이터</font><font class="papago-parent"><font class="papago-source" style="display:none;">width: 800
</font>폭: 800</font><font class="papago-parent"><font class="papago-source" style="display:none;">height: 600
</font>높이: 600</font><font class="papago-parent"><font class="papago-source" style="display:none;">frameRate: 24
</font>프레임 속도: 24</font><font class="papago-parent"><font class="papago-source" style="display:none;">numFrames: 1
</font>numFrame: 1</font><font class="papago-parent"><font class="papago-source" style="display:none;">swfVersion: 8
</font>swfVersion: 8</font><font class="papago-parent"><font class="papago-source" style="display:none;">backgroundColor: #000000
</font>배경색 : #000000</font><font class="papago-parent"><font class="papago-source" style="display:none;">isActionScript3: false
</font>isActionScript3: false</font><font class="papago-parent"><font class="papago-source" style="display:none;">uncompressedLength: 3848978
</font>비압축길이 : 3848978</font>

**Comment by Lord-McSweeney** [comment] 2023-05-27 14:33
Duplicate of #10042.

**Closed by Lord-McSweeney** 2023-05-27 14:33 UTC
Labels: duplicate, nsfw, error-report
