### ISSUE TITLE
Error on https://e621.net/posts/106482?q=washa+animated

### ISSUE THREAD

**Issue by darthrenatus** [ruffle-rs/ruffle#3325] opened 2021-02-19 06:46 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:37079
    at e (<anonymous>:3:37569)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/106482?q=washa+animated

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by relrelb** [comment] 2021-02-19 08:30
Duplicate of #2201.

**Closed by relrelb** 2021-02-19 08:30 UTC
