### ISSUE TITLE
Error on https://www.flashthemes.net/

### ISSUE THREAD

**Issue by TheGamesss** [ruffle-rs/ruffle#16225] opened 2024-05-06 00:22 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys/sync/mutex/no_threads.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys/sync/mutex/no_threads.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3393:21)
    at ruffle_web.wasm.js_sys::Error::new::h2234a378a3d95323 (wasm://wasm/ruffle_web.wasm-03a269ba:wasm-function[14096]:0xb144ea)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hd3374b50dcd4a09d (wasm://wasm/ruffle_web.wasm-03a269ba:wasm-function[11628]:0xabfe8d)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-03a269ba:wasm-function[7062]:0x97db45)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-03a269ba:wasm-function[11327]:0xab8244)
    at ruffle_web.wasm.core::panicking::assert_failed_inner::h0379ad51ee2a5759 (wasm://wasm/ruffle_web.wasm-03a269ba:wasm-function[5115]:0x886a14)
    at ruffle_web.wasm.core::panicking::assert_failed::h295178c2343e5048 (wasm://wasm/ruffle_web.wasm-03a269ba:wasm-function[11369]:0xaba5d8)
    at ruffle_web.wasm.ruffle_core::loader::Loader::load_url_loader::{{closure}}::h79f3d7675859be63 (wasm://wasm/ruffle_web.wasm-03a269ba:wasm-function[4084]:0x7d88e1)
    at ruffle_web.wasm.<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h520e9425a1e88f09 (wasm://wasm/ruffle_web.wasm-03a269ba:wasm-function[1538]:0x4acdee)
    at ruffle_web.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::h408b096479b868da (wasm://wasm/ruffle_web.wasm-03a269ba:wasm-function[4294]:0x807539)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002488) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: low
Surface samples: 1
Surface size: (550, 400, 1)
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param flashvars: movieId=ZKJpr07M&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D72&thumburl=%2Fmovie_thumbs%2Fthumb-ZKJpr07M-5dc5a343-9f4c-44a4-a19f-ce786aaaa98b.png&v=72&movieLid=6&pwm=0&ut=-1&apiserver=https%3A%2F%2Fflashthemes.net%2F&playcount=1&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=1&isInitFromExternal=0&isWide=0&appCode=go&is_slideshow=0&is_emessage=0&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=0&&&&isTemplate=0&showButtons=1&chain_mids=&endStyle=0&showshare=true
Param movie: /static/animationnew/414827163ad4eb60/player.swf
Param wmode: opaque
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.flashthemes.net/
SWF URL: https://www.flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-05-04
Channel: nightly
Built: 2024-05-04T00:05:31.022Z
Commit: d1553a203e679d7bb6e8fc37979970087f344f73
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by sleepycatcoding** [comment] 2024-05-14 14:37
Duplicate of #13974.

**Closed** 2024-05-14 14:37 UTC
Labels: duplicate, error-report
