### ISSUE TITLE
Error on https://www.jogos360.com.br/electricman_2.html

### ISSUE THREAD

**Issue by TapiokaGyiu** [ruffle-rs/ruffle#6798] opened 2022-04-24 19:47 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.783a576b0cce6531afb8.js:1:7708)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.24/e9a8d78dcb3e1c347d81.wasm:wasm-function[1012]:0x2abbe8)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.24/e9a8d78dcb3e1c347d81.wasm:wasm-function[1443]:0x31f965)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.24/e9a8d78dcb3e1c347d81.wasm:wasm-function[4930]:0x47a59c)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.24/e9a8d78dcb3e1c347d81.wasm:wasm-function[3241]:0x41d094)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.24/e9a8d78dcb3e1c347d81.wasm:wasm-function[5012]:0x47e44f)
    at core::panicking::panic::he88f1b1582b09c8c (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.24/e9a8d78dcb3e1c347d81.wasm:wasm-function[4928]:0x47a12f)
    at core::ops::function::FnOnce::call_once::hea116a8eeeb59311 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.24/e9a8d78dcb3e1c347d81.wasm:wasm-function[1094]:0x2c3b61)
    at ruffle_core::avm1::function::Executable::exec::h0a1a3c56ef393e7a (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.24/e9a8d78dcb3e1c347d81.wasm:wasm-function[391]:0x12f9e6)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf21230a28d8729f3 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.24/e9a8d78dcb3e1c347d81.wasm:wasm-function[381]:0x119fff)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.jogos360.com.br/electricman_2.html
SWF URL: https://cdn.jogos360.com.br/files/games/el/ec/electricman-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14526.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.133 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-24
Channel: nightly
Built: 2022-04-24T00:17:47.431Z
Commit: 052cb401130272a5bdbf3c8f88bd0ec8fe4e128f
Is extension: false

**Comment by relrelb** [comment] 2022-04-29 20:01
Duplicate of #4932.

**Closed by relrelb** 2022-04-29 20:01 UTC
Labels: error-report
