### ISSUE TITLE
Error on https://archive.org/details/cannibals-missioneries

### ISSUE THREAD

**Issue by Tarunvats9068** [ruffle-rs/ruffle#8046] opened 2022-09-22 16:41 UTC
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/cannibals-missioneries#

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-19
Channel: nightly
Built: 2022-09-19T00:15:10.357Z
Commit: 9b9c95bfe28cb862d44e9517e94e9de73acd9de3
Is extension: false

# Metadata

**Comment by n0samu** [comment] 2022-09-22 22:37
Duplicate of #7582

**Closed by n0samu** 2022-09-22 22:37 UTC
Labels: duplicate, error-report
