### ISSUE TITLE
Fart Brother.....💥 Crash

### ISSUE THREAD

**Issue by olux997** [ruffle-rs/ruffle#12913] opened 2023-08-23 05:50 UTC
### Describe what you were doing

[fart-brother.zip](https://github.com/ruffle-rs/ruffle/files/12415620/fart-brother.zip)

# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.530cca0a4133b5d7dcb3.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h68328b569f1b749d (wasm://wasm/03009a16:wasm-function[9276]:0x8ff3ac)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/03009a16:wasm-function[6074]:0x7fea60)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/03009a16:wasm-function[9118]:0x8facf0)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h2c5f54c89ef9f6cc (wasm://wasm/03009a16:wasm-function[3161]:0x65c74b)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h410011965f892e3c (wasm://wasm/03009a16:wasm-function[3080]:0x648dda)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hfd6685df17449f5f (wasm://wasm/03009a16:wasm-function[1045]:0x35cb26)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::haaec52e5a1710d84 (wasm://wasm/03009a16:wasm-function[1867]:0x4f90bb)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h7d528294b2a1474d (wasm://wasm/03009a16:wasm-function[818]:0x2a60c0)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hfd6685df17449f5f (wasm://wasm/03009a16:wasm-function[1045]:0x35cb62)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle-regressions.github.io/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-23
Channel: nightly
Built: 2023-08-23T00:19:38.921Z
Commit: d55cc23f5503f53932c64edf516ca375eaa01764
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 5
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 1616099

==================================================

# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.530cca0a4133b5d7dcb3.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h68328b569f1b749d (wasm://wasm/03009a16:wasm-function[9276]:0x8ff3ac)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/03009a16:wasm-function[6074]:0x7fea60)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/03009a16:wasm-function[9118]:0x8facf0)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h2c5f54c89ef9f6cc (wasm://wasm/03009a16:wasm-function[3161]:0x65c74b)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h410011965f892e3c (wasm://wasm/03009a16:wasm-function[3080]:0x648dda)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hfd6685df17449f5f (wasm://wasm/03009a16:wasm-function[1045]:0x35cb26)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::haaec52e5a1710d84 (wasm://wasm/03009a16:wasm-function[1867]:0x4f90bb)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h7d528294b2a1474d (wasm://wasm/03009a16:wasm-function[818]:0x2a60c0)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hfd6685df17449f5f (wasm://wasm/03009a16:wasm-function[1045]:0x35cb62)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle-regressions.github.io/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-23
Channel: nightly
Built: 2023-08-23T00:19:38.921Z
Commit: d55cc23f5503f53932c64edf516ca375eaa01764
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 5
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 1616099

### What does the crash message say?

Fart Brother.....💥 Crash

### Ruffle Version

nightly 2023-08-16

### Affected platform

Self-hosted version

### Operating system

Windows 10

**Comment by Dinnerbone** [comment] 2024-07-12 22:02
Duplicate of #12594

**Closed by Dinnerbone** 2024-07-12 22:02 UTC
Labels: bug, duplicate, panic, mixed-avm
