### ISSUE TITLE
Error on http://sonic.sega.jp/riders/ShootingStarStory/

### ISSUE THREAD

**Issue by beefwomen** [ruffle-rs/ruffle#15258] opened 2024-02-17 20:59 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/string.rs:551:34:
string indices out of bounds
Error stack:
```
339/__wbg_get_imports/imports.wbg.__wbg_new_a64e3f2afc2cf2f8@moz-extension://14aa145b-9bae-426f-89c7-12965cc433aa/dist/339.js:2624:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a435d7beef43b50@:wasm-function[10793]:0xa1f551
std::panicking::rust_panic_with_hook::h62090d3fc0630473@:wasm-function[6608]:0x906d55
core::panicking::panic_fmt::hd79411a297d06dc8@:wasm-function[10505]:0xa190b6
core::option::expect_failed::h0edfdc49383f4b56@:wasm-function[9168]:0x9c74ae
ruffle_core::avm2::globals::string::substr::hdc89df4746093b48@:wasm-function[1738]:0x51e1d4
ruffle_core::avm2::function::Executable::exec::h0105c140d9037b4e@:wasm-function[873]:0x3181c4
ruffle_core::avm2::object::TObject::call_property::h401eaeae1a2342a4@:wasm-function[1298]:0x44b072
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hac0ffcc85a5aebf8@:wasm-function[2896]:0x6c17f1
ruffle_core::avm2::activation::Activation::run_actions::h8dfafc6a0c0a2658@:wasm-function[567]:0x33e61
ruffle_core::avm2::function::Executable::exec::h0105c140d9037b4e@:wasm-function[873]:0x317db6
ruffle_core::avm2::object::TObject::call_property::h343aae9513256c77@:wasm-function[1334]:0x45c9e3
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hac0ffcc85a5aebf8@:wasm-function[2896]:0x6c17cf
ruffle_core::avm2::activation::Activation::run_actions::h8dfafc6a0c0a2658@:wasm-function[567]:0x33e61
ruffle_core::avm2::function::Executable::exec::h0105c140d9037b4e@:wasm-function[873]:0x317db6
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h5b979538f4bfce79@:wasm-function[1062]:0x3c12a0
ruffle_core::avm2::events::dispatch_event_to_target::hb8842f4443c5c277@:wasm-function[1051]:0x3baa50
ruffle_core::avm2::events::dispatch_event::hff04f74263e136e1@:wasm-function[1281]:0x443785
ruffle_core::avm2::Avm2::broadcast_event::h0d3c21e33aa24a96@:wasm-function[757]:0x264e3d
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::enter_frame::h2d0c3121836fa00c@:wasm-function[2542]:0x66beeb
ruffle_web::Ruffle::tick::hed30aacb75495bbb@:wasm-function[860]:0x2efee5
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hcea0e3a9a03fb9f4@:wasm-function[12966]:0xa6eb6d
wasm_bindgen::convert::closures::invoke1_mut::h8a5a14e0511b153d@:wasm-function[11713]:0xa3a54c
__wbg_adapter_68@moz-extension://14aa145b-9bae-426f-89c7-12965cc433aa/dist/339.js:294:10
real@moz-extension://14aa145b-9bae-426f-89c7-12965cc433aa/dist/339.js:271:20

```
AVM2 stack:
```
    at String/substr()
    at myAS::textAnimation/randomTxtFnc()
    at myAS::textAnimation/textChange()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://sonic.sega.jp/riders/ShootingStarStory/
SWF URL: http://sonic.sega.jp/riders/ShootingStarStory/swf/top.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-13
Channel: nightly
Built: 2024-01-13T00:14:58.057Z
Commit: 2775c917bf61254dbddf67b604d36157efdff7d5
Is extension: true

# Metadata
width: 800
height: 720
frameRate: 26
numFrames: 177
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 415645

**Comment by Dinnerbone** [comment] 2024-07-12 22:06
Duplicate of #14557

**Closed by Dinnerbone** 2024-07-12 22:06 UTC
Labels: duplicate, avm2, error-report
