### ISSUE TITLE
Error on https://www.barfy.net/noobsquash/noobsquash.html

### ISSUE THREAD

**Issue by MarioGuyWasTaken** [ruffle-rs/ruffle#7049] opened 2022-05-21 23:20 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
@https://www.barfy.net/ruffle.js:1:7637
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h12990387e0d952cc]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h02a6489b0ecfb269]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hc62fbac30903ce1c]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h364974e717ed59ec]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hf69c8b08bc9d2ee5]@[wasm code]
<?>.wasm-function[core::result::unwrap_failed::h694db13a45aa6740]@[wasm code]
<?>.wasm-function[ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h83e1f7b62983f192]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h7b9782bfbdb46e92]@[wasm code]
<?>.wasm-function[ruffle_core::font::Font::from_swf_tag::ha89ccb16743560a9]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h94b16a334d01d26f]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h484112c4d5e6153d]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2656795a2ef7f5c0]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h7205236d067cc311]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hd152dc341c383afa]@[wasm code]
wasm-stub@[native code]
F@https://www.barfy.net/ruffle.js:1:4011
a@https://www.barfy.net/ruffle.js:1:2536
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: noobsquashgame.swf
Param movie: noobsquashgame.swf
Attribute 0: undefined
Attribute 1: undefined

# Page Info
Page URL: https://www.barfy.net/noobsquash/noobsquash.html
SWF URL: https://www.barfy.net/noobsquash/noobsquashgame.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-26
Channel: nightly
Built: 2021-11-26T00:12:46.315Z
Commit: f35b2666a36d1987154dcb4a73f79ab9379ba615
Is extension: false

**Comment by Herschel** [comment] 2022-05-22 02:47
Dupe of #1905

**Closed by Herschel** 2022-05-22 02:47 UTC
