### ISSUE TITLE
Error on https://www.popka.co.il/game-1060.html

### ISSUE THREAD

**Issue by ab262** [ruffle-rs/ruffle#7096] opened 2022-05-27 09:21 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.17.10/src/fill.rs:1942:74
Error stack:
```
@https://www.popka.co.il/ruffle/core.ruffle.6aaadd2d51f5af29a340.js:1:7581
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h9bbf01ee609e3a75]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h51a70f81ef530383]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h360f2d0dfec34f5b]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h12b2f0179ff84c92]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hf0d93ec1ac504cf9]@[wasm code]
<?>.wasm-function[core::panicking::panic::h5d6906e2c1099660]@[wasm code]
<?>.wasm-function[core::slice::sort::shift_tail::h3518023d644b82d3]@[wasm code]
<?>.wasm-function[core::slice::sort::recurse::hc980784b1c1c1b23]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::process_events::h05758abbb70b2c89]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_impl::h31add8ee55163ede]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_path::hd9376bf19de39217]@[wasm code]
<?>.wasm-function[ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h739c5209f6bd0aca]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h5f052a03e33decd3]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h720c2bb0c10f90d3]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h78fa62a7a8bf942d]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::hb1b12dff08246a90]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd7e727b078a08975]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbee82f94652be113]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h94b1dfb134b4d43c]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6769736ffe94a981]@[wasm code]
wasm-stub@[native code]
O@https://www.popka.co.il/ruffle/core.ruffle.6aaadd2d51f5af29a340.js:1:3997
c@https://www.popka.co.il/ruffle/core.ruffle.6aaadd2d51f5af29a340.js:1:2522
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.popka.co.il/files/swfs/1060.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.popka.co.il/game-1060.html
SWF URL: https://www.popka.co.il/files/swfs/1060.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-08
Channel: nightly
Built: 2022-03-08T00:15:05.022Z
Commit: 697ad92db5bab4d4100611843ffd59db1b581274
Is extension: false

**Comment by n0samu** [comment] 2024-06-23 23:31
Likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:31 UTC
Labels: error-report
