### ISSUE TITLE
Error on https://www.flashthemes.net/

### ISSUE THREAD

**Issue by JaydenGoanimate** [ruffle-rs/ruffle#14842] opened 2024-01-19 18:05 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h17602019b8af7fc3 (wasm://wasm/03667966:wasm-function[10825]:0xa25bcc)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/03667966:wasm-function[6633]:0x9103a6)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/03667966:wasm-function[10539]:0xa1f797)
    at core::panicking::assert_failed_inner::h003d4b5b03930769 (wasm://wasm/03667966:wasm-function[4528]:0x80014a)
    at core::panicking::assert_failed::h2ef43cee5e146325 (wasm://wasm/03667966:wasm-function[10584]:0xa20eb4)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::h9c21f39523f4eb69 (wasm://wasm/03667966:wasm-function[2423]:0x648e52)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hd35475b3eeab484b (wasm://wasm/03667966:wasm-function[1280]:0x44986e)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h48fd070f12b3fc32 (wasm://wasm/03667966:wasm-function[3718]:0x788c1e)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hd0b5dfa4f8b00eef (wasm://wasm/03667966:wasm-function[11770]:0xa425ee)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 SUPER (0x00001F06) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 825, height: 576, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param flashvars: movieId=6wEVM1tzzwR&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D2011&thumburl=%2Fmovie_thumbs%2Fthumb-6wEVM1tzzwR.png&v=2011&movieLid=6&pwm=0&ut=-1&apiserver=https%3A%2F%2Fflashthemes.net%2F&playcount=1&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=1&isInitFromExternal=0&isWide=0&appCode=go&is_slideshow=0&is_emessage=0&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=0&&&&isTemplate=0&showButtons=1&chain_mids=&endStyle=0&showshare=true
Param movie: /static/animationnew/414827163ad4eb60/player.swf
Param wmode: opaque
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.flashthemes.net/
SWF URL: https://www.flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0 (Edition std-1)
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-19
Channel: nightly
Built: 2024-01-19T00:15:24.643Z
Commit: 5f123c3c011b044670602c2b0bb986527fc57135
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment] 2024-01-20 01:34
Duplicate of #13974

**Closed by n0samu** 2024-01-20 01:34 UTC
Labels: duplicate, web, error-report
