### ISSUE TITLE
Error on https://flashthemes.net/movie/MieeLD3

### ISSUE THREAD

**Issue by LeoKids** [ruffle-rs/ruffle#15204] opened 2024-02-13 00:30 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/292.js:3369:21)
    at js_sys::Error::new::he329e38f5ae64355 (wasm://wasm/03910312:wasm-function[13751]:0xb047c0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9929706439805e04 (wasm://wasm/03910312:wasm-function[11363]:0xaae8e8)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/03910312:wasm-function[6940]:0x96bac8)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/03910312:wasm-function[11079]:0xaa7ee8)
    at core::panicking::assert_failed_inner::h161125ff96c9e54a (wasm://wasm/03910312:wasm-function[4832]:0x85c071)
    at core::panicking::assert_failed::h02ef34e890fad0c5 (wasm://wasm/03910312:wasm-function[11121]:0xaa955b)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::h3be0129d93b8b3a7 (wasm://wasm/03910312:wasm-function[2842]:0x6ba8b2)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hf801681c3397d38d (wasm://wasm/03910312:wasm-function[1440]:0x4618f5)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h18c98eaba3703a16 (wasm://wasm/03910312:wasm-function[4017]:0x7e2958)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: WebGL 1.0
Adapter Vendor: WebKit
Adapter Renderer: WebKit WebGL
Adapter Version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Surface samples: 1 x 
Surface size: 300 x 150
Player type: Object
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param wmode: transparent
Param flashvars: movieOwner=&movieOwnerId=44185&movieId=MieeLD3&movieLid=6&pwm=0&movieDesc=My%2520friend%2520on%2520discord%252C%2520leokids%2520used%2520chat%2520gpt%2520for%2520the%2520lyrics.%2520I%2520used%2520splash%2520pro%2520to%2520ai%2520generate%2520this%2520song.&userId=44185&username=&uemail=&ut=-1&numContact=&apiserver=https%3A%2F%2Fflashthemes.net%2F&duration=53&playcount=1&thumbnailURL=%2Fmovie_thumbs%2Fthumb-MieeLD3.png&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=0&isInitFromExternal=0&isWide=1&appCode=go&is_slideshow=0&is_emessage=0&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D44185&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=1&&&&isTemplate=0&showButtons=1&chain_mids=&averageRating=0&ratingCount=2&endStyle=0&showshare=false
Param movie: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/movie/MieeLD3
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-02-12
Channel: nightly
Built: 2024-02-12T00:15:34.455Z
Commit: 45c5d8f10c41f4bd24dff5ddeb8e6d7873b6fc2d
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment] 2024-05-12 21:36
Duplicate of #13974

**Closed by n0samu** 2024-05-12 21:36 UTC
Labels: duplicate, error-report
