### ISSUE TITLE
Error on https://flashthemes.net/videomaker/custom/full

### ISSUE THREAD

**Issue by Brothercompany249** [ruffle-rs/ruffle#13759] opened 2023-10-28 18:10 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left


    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://pipjjbgofgieknlpefmcckdmgaaegban/dist/339.js:2479:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hee68611ee8147044 (wasm://wasm/032bf7de:wasm-function[9747]:0x995320)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/032bf7de:wasm-function[6416]:0x8981dd)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/032bf7de:wasm-function[9549]:0x990199)
    at core::ops::function::Fn::call::h29d499b8947f9422 (wasm://wasm/032bf7de:wasm-function[6577]:0x8a1a05)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h0b7e9b7bd4967d5c (wasm://wasm/032bf7de:wasm-function[5318]:0x838cd7)
    at <T as wgpu::context::DynContext>::device_create_buffer::h81ba37c770f75660 (wasm://wasm/032bf7de:wasm-function[7355]:0x8ebcec)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h481c6961f2e6a8f4 (wasm://wasm/032bf7de:wasm-function[1650]:0x4ce254)
    at core::cell::once::OnceCell<T>::get_or_try_init::outlined_call::h6b4f42e75f30c838 (wasm://wasm/032bf7de:wasm-function[5922]:0x8749eb)
    at ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::h2b555591f68c507b (wasm://wasm/032bf7de:wasm-function[1687]:0x4dc1f9)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics (0x000022B1) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/go_fullw.swf
Param align: middle
Param allowScriptAccess: always
Param allowFullScreen: true
Param wmode: window
Param flashvars: apiserver=https%3A%2F%2Fflashthemes.net%2F&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E&isEmbed=1&tlist=2016&has_asset_char=1&ctc=go&initcb=studioLoaded&collab=0&ut=50&v=11944&bs=default&appCode=go&siteId=0&lid=0&retut=0&isLogin=Y&bgload=%2Fstatic%2Fanimationnew%2F414827163ad4eb60%2Fgo_fullw.swf&userId=11944&movieOwnerId=11944&movieOwner=Go'NAnimate&themeId=custom&tlang=en_US&isWide=1&tray=custom&upl=1&hb=1&pts=0&tm=FIN&nextUrl=https%3A%2F%2Fflashthemes.net%2Fmovie%2F%3CmovieId%3E&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&movieLid=0
Param movie: /static/animationnew/414827163ad4eb60/go_fullw.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/videomaker/custom/full
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/go_fullw.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-25
Channel: nightly
Built: 2023-10-25T00:24:21.468Z
Commit: 1a853803448ae68ce919ae19a2ee2c212476ac5b
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9419911

**Comment by n0samu** [comment] 2023-12-06 12:26
Duplicate of##13248

**Closed by n0samu** 2023-12-06 12:26 UTC
Labels: duplicate, error-report
