### ISSUE TITLE
Error on https://game244939.konggames.com/games/scriptwelder/dont-escape-3/frame/ffdca6d5-553e-44f2-89f3-bb74386e1f2d/

### ISSUE THREAD

**Issue by ArchercatNEO** [ruffle-rs/ruffle#10986] opened 2023-05-09 15:54 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 39032 but the index is 39032', core/src/bitmap/bitmap_data.rs:604:9
Error stack:
```
339/O/n.wbg.__wbg_new_15d3966e9981a196@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1f63c5b1396ac9e10d6d.js:1:49872
core::ops::function::FnOnce::call_once{{vtable.shim}}::haa731965db7740b6@:wasm-function[8572]:0x830b2a
std::panicking::rust_panic_with_hook::h7f7102b82d51338f@:wasm-function[5598]:0x754c53
core::panicking::panic_fmt::he4489d678d6570d5@:wasm-function[8421]:0x82b28e
core::panicking::panic_bounds_check::h1213b10c1e002d73@:wasm-function[6721]:0x7a9e91
ruffle_core::bitmap::operations::copy_on_cpu::h77f382aa99fa6357@:wasm-function[790]:0x2ad4bc
ruffle_core::bitmap::operations::copy_pixels::h1b4d32ad17038d9a@:wasm-function[4298]:0x6e631b
ruffle_core::avm2::globals::flash::display::bitmap_data::copy_pixels::hd0c99dec715eed5f@:wasm-function[724]:0x272fc8
ruffle_core::avm2::function::Executable::exec::h13c3bc91d186b7aa@:wasm-function[793]:0x2af197
ruffle_core::avm2::object::TObject::call_property::hf0564dd227fd8e78@:wasm-function[1118]:0x388d09
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h7f0fde775110e7d4@:wasm-function[2705]:0x5bf4dd
ruffle_core::avm2::activation::Activation::run_actions::h33d95af8444aca4f@:wasm-function[503]:0x28881
ruffle_core::avm2::function::Executable::exec::h13c3bc91d186b7aa@:wasm-function[793]:0x2b090d
ruffle_core::avm2::object::TObject::call_property::h23a57a50eb5c122b@:wasm-function[1101]:0x380cf3
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h7f0fde775110e7d4@:wasm-function[2705]:0x5bf400
ruffle_core::avm2::activation::Activation::run_actions::h33d95af8444aca4f@:wasm-function[503]:0x28881
ruffle_core::avm2::function::Executable::exec::h13c3bc91d186b7aa@:wasm-function[793]:0x2b090d
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h37174b4e1f76c4ab@:wasm-function[985]:0x343ab8
ruffle_core::avm2::events::dispatch_event_to_target::h724504ecd7fe23ab@:wasm-function[922]:0x31a88f
ruffle_core::avm2::events::dispatch_event::h09906c7ccdab0f58@:wasm-function[1078]:0x373a2c
ruffle_core::avm2::Avm2::broadcast_event::hcdd2cd1df36f24cb@:wasm-function[695]:0x247cc8
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::enter_frame::h5b0701b6b501880f@:wasm-function[4658]:0x706089
ruffle_web::Ruffle::tick::h13126fb025085e0e@:wasm-function[733]:0x27c800
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h2bbb2b8dc01f2e3b@:wasm-function[10330]:0x8744ec
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha5737c35365fbf19@:wasm-function[9174]:0x849ce9
A@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1f63c5b1396ac9e10d6d.js:1:2600
f@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1f63c5b1396ac9e10d6d.js:1:2277

```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at Game/drawGame()
    at Game/loop()
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game244939.konggames.com/games/scriptwelder/dont-escape-3/frame/ffdca6d5-553e-44f2-89f3-bb74386e1f2d/?kongregate_host=www.kongregate.com
SWF URL: https://game244939.konggames.com/gamez/0024/4939/live/dontescape3.swf?kongregate_game_version=1552484733

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-09
Channel: nightly
Built: 2023-05-09T00:25:26.314Z
Commit: 72769eeefa66b617d3d7f710a76f4ea78ec16104
Is extension: false

# Metadata
width: 720
height: 540
frameRate: 30
numFrames: 2
swfVersion: 22
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 11988533

**Comment by n0samu** [comment] 2023-05-10 08:15
Duplicate of #10955

**Closed by n0samu** 2023-05-10 08:15 UTC
Labels: duplicate, error-report
