### ISSUE TITLE
Error on https://lms2.infowerk.at/newcag/open-course/29402/2158/0

### ISSUE THREAD

**Issue by sgeoris** [ruffle-rs/ruffle#4414] opened 2021-05-24 14:42 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 15 but the index is 4294967295', render/webgl/src/lib.rs:541:37
Error stack:
```
Error: panicked at 'index out of bounds: the len is 15 but the index is 4294967295', render/webgl/src/lib.rs:541:37
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://lms2.infowerk.at/js/ruffle/ruffle.js:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://lms2.infowerk.at/js/ruffle/2866de769aa46ef052efb6d4443f238c.wasm:wasm-function[1417]:0x2a0b7a)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://lms2.infowerk.at/js/ruffle/2866de769aa46ef052efb6d4443f238c.wasm:wasm-function[1708]:0x2d7232)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://lms2.infowerk.at/js/ruffle/2866de769aa46ef052efb6d4443f238c.wasm:wasm-function[5043]:0x3d73fa)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://lms2.infowerk.at/js/ruffle/2866de769aa46ef052efb6d4443f238c.wasm:wasm-function[3855]:0x3aa156)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://lms2.infowerk.at/js/ruffle/2866de769aa46ef052efb6d4443f238c.wasm:wasm-function[4537]:0x3ca2e0)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://lms2.infowerk.at/js/ruffle/2866de769aa46ef052efb6d4443f238c.wasm:wasm-function[5408]:0x3dcfb3)
    at rust_begin_unwind (https://lms2.infowerk.at/js/ruffle/2866de769aa46ef052efb6d4443f238c.wasm:wasm-function[5285]:0x3db6ff)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://lms2.infowerk.at/js/ruffle/2866de769aa46ef052efb6d4443f238c.wasm:wasm-function[5409]:0x3dcfe9)
    at core::panicking::panic_bounds_check::h81a63bf79280172d (https://lms2.infowerk.at/js/ruffle/2866de769aa46ef052efb6d4443f238c.wasm:wasm-function[4771]:0x3d101c)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://lms2.infowerk.at/newcag/open-course/29402/2158/0
SWF URL: https://lms2.infowerk.at/player/swf_player_v2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-04
Channel: nightly
Built: 2021-03-04T00:17:59.511Z
Commit: f64e5d5b4113249417570c9bb905be75c8401fb3

**Comment by relrelb** [comment] 2021-06-05 19:45
Duplicate of #3365.

**Closed by relrelb** 2021-06-05 19:45 UTC
