### ISSUE TITLE
Error on https://gry.jeja.pl/353,elektryczny-czlowiek-2.html

### ISSUE THREAD

**Issue by Krzysiekksi6** [ruffle-rs/ruffle#9390] opened 2023-02-02 16:54 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://gry.jeja.pl/js/ruffle_2021_06_22/ruffle.js:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h5a73b3c37f29875c (wasm://wasm/015093b2:wasm-function[1006]:0x2823c1)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (wasm://wasm/015093b2:wasm-function[974]:0x2785fb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h265fbb84ca9e6c29 (wasm://wasm/015093b2:wasm-function[3858]:0x41fac3)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (wasm://wasm/015093b2:wasm-function[2986]:0x3bf2dc)
    at rust_begin_unwind (wasm://wasm/015093b2:wasm-function[4067]:0x4253a5)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (wasm://wasm/015093b2:wasm-function[4216]:0x42c145)
    at core::panicking::panic::h5bfdfaa3db9a4b4a (wasm://wasm/015093b2:wasm-function[4011]:0x422b27)
    at core::ops::function::FnOnce::call_once::h9fc1d1122882bf02 (wasm://wasm/015093b2:wasm-function[866]:0x255493)
    at ruffle_core::avm1::function::Executable::exec::h6e17f3d4d797cb93 (wasm://wasm/015093b2:wasm-function[343]:0xc8894)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://gry.jeja.pl/353,elektryczny-czlowiek-2.html
SWF URL: https://pobierak.jeja.pl/games/8/a/d/353.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-22
Channel: nightly
Built: 2021-06-22T00:10:37.922Z
Commit: e0107750996b5b3724680ead1acda0124002baea

**Comment by n0samu** [comment] 2023-02-06 08:28
Duplicate of #4932

**Closed by n0samu** 2023-02-06 08:28 UTC
Labels: duplicate, error-report
