### ISSUE TITLE
B.L.A.C.K. 2 - Game Freezes

### ISSUE THREAD

**Issue by theonlypwner** [ruffle-rs/ruffle#12390] opened 2023-07-29 05:27 UTC
### Describe the bug

1. Download SWF from https://uploads.ungrounded.net/356000/356980_black2.swf
2. Load SWF at https://ruffle.rs/demo/
3. Start the game.
4. Play the game for a while.

The game either freezes or goes into a white screen.

### Expected behavior

I expect the game to be playable.

### Affected platform

Online demo

### Operating system

Windows 11

### Browser

Chrome 115.0.5790.102

**Comment by Lord-McSweeney** [comment] 2023-07-29 08:24
I cannot reproduce this (though i only got up to the second level).

**Comment by theonlypwner** [comment] 2023-07-29 17:39
Sometimes, on loading, there is a white screen, followed by a glitched state:

https://github.com/ruffle-rs/ruffle/assets/802664/8c5ef741-bf75-421b-9731-df37da410ecf

When that doesn't happen, switching weapons and shooting seems to make it freeze. After a while, it enters the glitched state.

https://github.com/ruffle-rs/ruffle/assets/802664/46814f32-94ad-443b-9c6f-c07a657c9ced

https://github.com/ruffle-rs/ruffle/assets/802664/f4f2ed2f-57a5-4a43-91a5-556432d3bd6a

**Comment by n0samu** [comment] 2023-08-29 00:20
Fixed by #12956

**Closed by n0samu** 2023-08-29 00:20 UTC
Labels: bug, avm1

**Comment by n0samu** [comment] 2023-09-23 06:03
Game link: https://www.newgrounds.com/portal/view/356980/
