### ISSUE TITLE
Error on <!DOCTYPE HTML> <html>     <head>         <meta charset='utf8'>     </head>     <body>         <div id='ruffle'></div>         <script src='https://unpkg.com/@ruffle-rs/ruffle'></script>         <script> var swfobject = {};  swfobject.embedSWF = function(url, cont, width, height){     var ruffle = window.RufflePlayer.newest(),         player = Object.assign(document.getElementById(cont).appendChild(ruffle.createPlayer()), {             width: width,             height: height,             style: 'width: ' + width + 'px; height: ' + height + 'px',         });          player.load({ url: url }); }  swfobject.embedSWF('https://schoolImpostor.github.io/flash-games/electricman2.swf', 'ruffle', 500, 500);         </script>     </body> </html>

### ISSUE THREAD

**Issue by schoolImpostor** [ruffle-rs/ruffle#6316] opened 2022-02-20 00:13 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.3c40dc0bd68b80f95b7b.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::ha69306374a0d7c42 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.19/18f70695ff32c2ad02b2.wasm:wasm-function[1024]:0x2f8ea2)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.19/18f70695ff32c2ad02b2.wasm:wasm-function[1157]:0x32a34e)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd4ed35f37e0c71aa (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.19/18f70695ff32c2ad02b2.wasm:wasm-function[4695]:0x4d1df4)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.19/18f70695ff32c2ad02b2.wasm:wasm-function[3177]:0x47e42e)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.19/18f70695ff32c2ad02b2.wasm:wasm-function[4957]:0x4dd821)
    at core::panicking::panic::h35778e3c18266c93 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.19/18f70695ff32c2ad02b2.wasm:wasm-function[4692]:0x4d191b)
    at core::ops::function::FnOnce::call_once::h536ce3a2d6da6677 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.19/18f70695ff32c2ad02b2.wasm:wasm-function[1059]:0x30ec01)
    at ruffle_core::avm1::function::Executable::exec::hf35d006d9e5c7bf8 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.19/18f70695ff32c2ad02b2.wasm:wasm-function[396]:0x13f59f)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h8935321d91c5bc87 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.2.19/18f70695ff32c2ad02b2.wasm:wasm-function[462]:0x198756)
```

# Player Info
Allows script access: false

# Page Info
Page URL: file:///home/chronos/u-9f67bf0f0e0bd09b8900db8349a6ef7ea0f23dc5/MyFiles/index.html
SWF URL: https://schoolimpostor.github.io/flash-games/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14388.52.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.91 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-19
Channel: nightly
Built: 2022-02-19T00:15:44.456Z
Commit: 2ca62ecf4bac5696d2da084b1f5d5c6ba2a4e0f7
Is extension: false

**Comment by relrelb** [comment] 2022-02-20 05:36
Duplicate of #4932.

**Closed by relrelb** 2022-02-20 05:36 UTC
Labels: error-report
