### ISSUE TITLE
Error on https://www.addictinggames.com/action/electric-man-2

### ISSUE THREAD

**Issue by xxxlivinglegend** [ruffle-rs/ruffle#5790] opened 2021-12-02 19:15 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://jiopkpfbbboghccknjglpeainebedimc/dist/ruffle.js?id=29340804664:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h6f6ea56fd6eb0153 (chrome-extension://jiopkpfbbboghccknjglpeainebedimc/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[999]:0x3022e9)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (chrome-extension://jiopkpfbbboghccknjglpeainebedimc/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[1359]:0x37fe26)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he60880e8d4402e2b (chrome-extension://jiopkpfbbboghccknjglpeainebedimc/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[4748]:0x50ef4e)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (chrome-extension://jiopkpfbbboghccknjglpeainebedimc/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[3359]:0x4c7423)
    at rust_begin_unwind (chrome-extension://jiopkpfbbboghccknjglpeainebedimc/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[4809]:0x511599)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (chrome-extension://jiopkpfbbboghccknjglpeainebedimc/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[5017]:0x51c179)
    at core::panicking::panic::hceae0c79b0247f98 (chrome-extension://jiopkpfbbboghccknjglpeainebedimc/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[4744]:0x50e77f)
    at core::ops::function::FnOnce::call_once::hdb759497bce0542e (chrome-extension://jiopkpfbbboghccknjglpeainebedimc/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[1046]:0x31fd62)
    at ruffle_core::avm1::function::Executable::exec::h7fb418e1bf515804 (chrome-extension://jiopkpfbbboghccknjglpeainebedimc/dist/8abf0a0ffc50a9f61348.wasm:wasm-function[412]:0x149b88)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /sites/default/files/flash_games/electricman2_0.swf
Param menu: false
Param allowscriptaccess: always
Param allownetworking: all
Param movie: /sites/default/files/flash_games/electricman2_0.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.addictinggames.com/action/electric-man-2
SWF URL: https://www.addictinggames.com/sites/default/files/flash_games/electricman2_0.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-02
Channel: nightly
Built: 2021-12-02T00:11:23.895Z
Commit: e3dfeb5a44c3a728cfe50642e480f3ea3498c099
Is extension: true

**Comment by relrelb** [comment] 2021-12-03 07:00
Duplicate of #4932.

**Closed by relrelb** 2021-12-03 07:00 UTC
