### ISSUE TITLE
Toxic II is softlocked in the first room

### ISSUE THREAD

**Issue by ItsMaximum** [ruffle-rs/ruffle#3086] opened 2021-02-04 14:50 UTC
[Toxic 2](https://github.com/ruffle-rs/ruffle/files/5926451/toxic_2.zip) is a flash game by nitrome that loads completely fine in ruffle, but the game softlocks in the first room due to certain game mechanics not working. Bombs don't deal any damage to the player, and the door doesn't open after hitting the computer panel with a bomb. I am not sure if this is due to a limitation with ruffle or the heavily obfuscated nature of the code.

**Comment by n0samu** [comment] 2022-10-30 04:46
Seeing this message when a bomb explodes:
`[WARN  ruffle_core::avm1::globals::bitmap_data] BitmapData.threshold - not yet implemented`
I think this may be the reason for these problems, but I'm not sure.

**Comment by CUB3D** [comment] 2022-12-28 00:02
After taking a deeper look into this, I think the last missing piece of this is `BitmapData.draw` with blend modes (specifically "difference"). 

In `Player::checkPickUps` it seems to use this combined with `getColorBoundsRect` to decide if something should be "collected". Hitting the computer with a bomb eventually calls `FirstInfoPoint::endCollect` which checks to see if the computer has been "collected" as well as "hacked" (the "hacked" flag is set earlier by this functions caller, `FirstInfoPoint::hack`). It looks like the threshold pr won't do much to help here, but it might be needed at a later point.

**Comment by n0samu** [comment] 2022-12-28 05:18
That makes sense. There are a lot of other games that need BitmapData.draw with blend modes, such as #8920.

**Comment by waspennator** [comment] 2023-01-12 07:16
Testing on the latest desktop nightly, I can confirm that you can kill yourself with your own bombs and bombing the computer now opens up the first door too.

There seems to be a new issue now, bombing yourself should only take off a chunk of HP, but in Ruffle it just straight up kills you playing the animation that plays when you fall into acid. Same goes for when you collide with an enemy robot.

**Comment by Lord-McSweeney** [comment] 2023-01-20 02:16
A minor issue that I noticed: the "sound fx" and "music" buttons are grayed out, although I'm not sure if that behavior occurs in Flash Player or not.

**Comment by waspennator** [comment] 2023-01-28 00:46
Tested out further after discussing with another user on the ruffle discord server, on level 2, you take damage as normal and you don't seem to die from everything instantly, but it goes right back to insta death on level 3. Then on level 4 your bombs cant hurt you. I can't test any further past that cause you can't get past a destructible tile wall that's normally bombable on flash, but on ruffle just leaves a solid green texture.

**Comment by n0samu** [comment] 2023-02-21 09:23
This was regressed by #9301. The game is back to being broken as described in the original issue.

**Comment by waspennator** [comment] 2023-02-24 01:14
As of the latest build, the first room softlock is now fixed again, but taking any damage from bombing yourself or touching robots doesn't insta kill you (Unless you jump in the acid like intended), the only issue that seems to be left now is the soft lock from the indestructible walls on level 4

**Comment by n0samu** [comment] 2023-02-24 18:26
Actually the wall in level 1 is indestructible now too, which makes it impossible to complete level 1. Right?

https://user-images.githubusercontent.com/71368227/221260042-57ca03ca-5748-46b0-b3be-2dd7f5bb28da.mp4

**Comment by waspennator** [comment] 2023-02-24 18:31
> Actually the wall in level 1 is indestructible now too, which makes it impossible to complete level 1. Right?

Normally yes, but right after you bomb the computer terminal, you can wall jump around here to bypass it and beat level 1.

![Screenshot_20230224_112930_YouTube](https://user-images.githubusercontent.com/78768499/221261249-0a2610a9-f07b-44c4-b2ff-900f4a0fdef6.jpg)

**Comment by waspennator** [comment] 2023-07-09 18:23
Update: the indestructible walls on level 4 are still indestructible, but now they aren't visually changing at all now when you try and blow them up.

**Comment by n0samu** [comment] 2023-07-25 02:47
Looks like the walls are back to how they were before (still indestructible)

**Comment by Lord-McSweeney** [comment] 2024-08-10 17:14
Closing in favor of #17458.

**Closed by Lord-McSweeney** 2024-08-10 17:14 UTC
Labels: bug, rendering, avm1
