### ISSUE TITLE
Error on https://www.twoplayergames.org/gameframe/electricman-2

### ISSUE THREAD

**Issue by AmeenPopoola** [ruffle-rs/ruffle#8880] opened 2022-12-21 16:28 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://www.twoplayergames.org/dist/ruffle/core.ruffle.fe07824c1b902e12cdf0.js:1:6899)
    at std::sync::once::Once::call_once::{{closure}}::hade171d180e8c1b3 (wasm://wasm/018460fe:wasm-function[1059]:0x2a63ca)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/018460fe:wasm-function[1352]:0x30d4c4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b5ff8f72074c3e7 (wasm://wasm/018460fe:wasm-function[4886]:0x497380)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/018460fe:wasm-function[3635]:0x458938)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/018460fe:wasm-function[5116]:0x49beba)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/018460fe:wasm-function[4938]:0x49822a)
    at core::ops::function::FnOnce::call_once::h30d1d284d5fd9535 (wasm://wasm/018460fe:wasm-function[1244]:0x2e495a)
    at ruffle_core::avm1::function::Executable::exec::h21369c76f086a0ad (wasm://wasm/018460fe:wasm-function[355]:0xdc743)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::he8552b5e405132ad (wasm://wasm/018460fe:wasm-function[900]:0x26fed8)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://www.twoplayergames.org/gameframe/electricman-2

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-12
Channel: nightly
Built: 2022-11-12T00:15:57.157Z
Commit: 08270efee72ab8fe31b1448d76bcda09c8af264e
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment] 2022-12-22 08:26
Duplicate of #4932

**Closed by n0samu** 2022-12-22 08:26 UTC
Labels: duplicate, error-report
