### ISSUE TITLE
Error on https://flashga.me/embed/jacksmith

### ISSUE THREAD

**Issue by 1fsjsoqn** [ruffle-rs/ruffle#17703] opened 2024-08-30 14:06 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096


    at n.wbg.__wbg_new_28c511d9baebfa89 (https://flashga.me/public/js/emulators/ruffle/core.ruffle.cfb85070aea0b5df7cc1.js:1:79048)
    at ruffle_web.wasm.js_sys::Error::new::hda2cb16801956d39 (wasm://wasm/ruffle_web.wasm-03355ba2:wasm-function[12817]:0x9d9c81)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h4efee46b7e0e8825 (wasm://wasm/ruffle_web.wasm-03355ba2:wasm-function[9848]:0x970aee)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-03355ba2:wasm-function[6498]:0x8642f5)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-03355ba2:wasm-function[10248]:0x99acb4)
    at ruffle_web.wasm.core::ops::function::Fn::call::h3556f5a5fd59719b (wasm://wasm/ruffle_web.wasm-03355ba2:wasm-function[6797]:0x87dab6)
    at ruffle_web.wasm.wgpu::backend::wgpu_core::ContextWgpuCore::handle_error::hb62c767ff91fbf47 (wasm://wasm/ruffle_web.wasm-03355ba2:wasm-function[2101]:0x547418)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h13cff3807e4b63ba (wasm://wasm/ruffle_web.wasm-03355ba2:wasm-function[9829]:0x96d873)
    at ruffle_web.wasm.wgpu::CommandEncoder::copy_texture_to_buffer::h73af2ffbd6a880b3 (wasm://wasm/ruffle_web.wasm-03355ba2:wasm-function[9465]:0x94bc19)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::resolve_sync_handle::h630bdb828f428f4e (wasm://wasm/ruffle_web.wasm-03355ba2:wasm-function[2451]:0x5bf0a5)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Adreno (TM) 642L"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://flashga.me/embed/jacksmith
SWF URL: blob:https://flashga.me/239757ec-497b-4589-92bb-5d63178792ae

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 11; SM-A528B Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-12
Channel: nightly
Built: 2024-07-12T00:05:18.191Z
Commit: 393ffe05ef0894768f7d938c1dee0314cdcaa794
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9363111

**Comment by evilpie** [comment] 2024-08-30 20:11
Duplicate of #11591

**Closed by evilpie** 2024-08-30 20:11 UTC
Labels: error-report
