### ISSUE TITLE
Error on https://www.txori.com/index.php

### ISSUE THREAD

**Issue by AnothepersonItsme** [ruffle-rs/ruffle#6966] opened 2022-05-13 08:18 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/display_object/bitmap.rs:194:28
Error stack:
```
@https://www.txori.com/data/system/ruffle/core.ruffle.37fbe233a598628c0eb2.js:1:7496
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hc3464e04dbb9beda]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h07d0245bef259c27]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h44f701de063d4daa]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h623ac32ff431b114]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h5118e89563022e7e]@[wasm code]
<?>.wasm-function[core::result::unwrap_failed::ha62420c192a556da]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::set_prev_avm1_clip::h26c8e5c07b3ae4c0]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::post_instantiation::h75e861ed040442fc]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h2da5adffee6c951d]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h9fe0c4ec410d4e3a]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::run_goto::{{closure}}::h96cb6aa2eeb871a5]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::run_goto::h6a1d2777f163863d]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::goto_frame::h79f9880aaa58f616]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::globals::movie_clip::goto_frame::h9a366872ba7fb9fd]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once::h99a6b8488635c3df]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h114e6421d0b212e0]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h39023dca8cfb590d]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h995d6781178059cf]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h114e6421d0b212e0]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::hf2c56519d68fd85d]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h995d6781178059cf]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h114e6421d0b212e0]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::hf2c56519d68fd85d]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h995d6781178059cf]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h114e6421d0b212e0]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::hf2c56519d68fd85d]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h995d6781178059cf]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h114e6421d0b212e0]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::hf2c56519d68fd85d]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h995d6781178059cf]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h114e6421d0b212e0]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h39023dca8cfb590d]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::Avm1::run_stack_frame_for_method::hbe54d79b76c71f31]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::hc76dfb362b0051f3]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::update_mouse_state::h830bb488b647dae0]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::handle_event::h926bac47517e97bb]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hf689c55a360e92a6]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h7fb3f288caddac24]@[wasm code]
wasm-stub@[native code]
k@https://www.txori.com/data/system/ruffle/core.ruffle.37fbe233a598628c0eb2.js:1:3105
c@https://www.txori.com/data/system/ruffle/core.ruffle.37fbe233a598628c0eb2.js:1:2393
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: data/documents/dbz/dbdev.swf?id=1614081248
Param quality: high
Param AllowScriptAccess: sameDomain 
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.txori.com/index.php?static5/dbdevolution
SWF URL: https://www.txori.com/data/documents/dbz/dbdev.swf?id=1614081248

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-11
Channel: nightly
Built: 2022-05-11T00:16:36.001Z
Commit: 84b865018d79f006640692f1f4c9d3b8c1faca04
Is extension: false

**Comment by n0samu** [comment] 2024-06-23 23:35
Likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:35 UTC
Labels: error-report
