### ISSUE TITLE
Samsara Room: Unable to Enter Game. (AS3)

### ISSUE THREAD

**Issue by Spikestuff** [ruffle-rs/ruffle#8278] opened 2022-10-13 03:06 UTC
### Describe the bug

After selecting "Play" you are unable to advance into the game, and unable to click to skip a sequence of text.

### Expected behavior

After clicking "Play" the intro sequence of waking up into the room should greet you to a grandfather clock, this sequence of text can also be skipped by a normal click.

### Affected platform

Desktop app

### Operating system

Windows 10 x64

### Additional information

Bit of a recent regression as the last working build was 2022-10-07.

In terms of no major graphical issues (there was still some) the last working version (to my knowledge) was 2022-09-11.

If you get past that and are unable to click the clock's hour/minute hand or the tealight you have to go left/right, and back, as you're unable to interact with anything immediately in Ruffle. And you can only clear out the first area, as going into the underwater section, you can only do the first section of the room, and nothing else.

After loading into a game, the cogwheel in the top right, will lead you to a "reset game", before you check other versions of Ruffle reset your progress.

- - -

As I was testing which was the last version able to run the title correctly, current versions would run it correctly again. This was not the behavior I was getting when I was writing this report and only now was it behaving correctly after looking for the regression.

**Comment by n0samu** [comment] 2022-10-13 17:10
Hi, I am unable to reproduce the problem with entering the game in Ruffle. But I found that when opening the game in the Adobe Flash projector, I am unable to click the Play button. Did you get the two mixed up?

What graphical problems are you experiencing with the game? And does running `ruffle -g dx12` from the Command Prompt fix them? (This command switches to the DirectX 12 renderer.) 

I can confirm that the objects on the first screen are not interactable until I go to another room and back, and this problem does not occur in Flash Player.

Here is the link to the game file that I am testing: https://web.archive.org/web/20170827084156id_/https://games.jayisgames.com/samsararoom.swf

**Comment by Spikestuff** [comment] 2022-10-14 03:11
> Did you get the two mixed up?

No I didn't, cause I don't use Adobe Flash projector. As I wrote towards the end, this suddenly started working again when I started checking for where the regression begun.

> What graphical problems are you experiencing with the game? And does running `ruffle -g dx12` from the Command Prompt fix them? (This command switches to the DirectX 12 renderer.)

Preferably want to use OpenGL/Vulkan in the end, cause I do want to TAS it, but here's a direct comparison of the graphical issue, doesn't matter which renderer is being used.

![image](https://user-images.githubusercontent.com/12412764/195753519-c3c6ab33-1c77-43b7-83d6-4c6303f34129.png)
![image](https://user-images.githubusercontent.com/12412764/195753473-dba3be5b-cbf5-4edf-ad28-dec34ceb5163.png)

**Comment by n0samu** [comment] 2022-10-14 10:01
1. Okay, I guess the issue with the Play button is probably due to Ruffle's broken mouse pick logic then, which makes the button very difficult to click in certain places. (In particular, clicking the text of the button is not detected as clicking the button itself.)
2. The graphical problems shown in your screenshot seem to be consistent between Ruffle versions and are simply due to Ruffle not having transparency effects implemented yet. Did it really look better in a previous Ruffle version? (I tested version 2022-09-05 for comparison.)

**Comment by n0samu** [comment] 2022-10-15 11:15
Oh, I see what you're talking about now. This was actually recently fixed by #8282. The latest desktop build is a bit broken, but version 2022-10-14 should be good.

**Comment by Spikestuff** [comment] 2022-10-15 13:49
> Okay, I guess the issue with the Play button is probably due to Ruffle's broken mouse pick logic then, which makes the button very difficult to click in certain places. (In particular, clicking the text of the button is not detected as clicking the button itself.)

Ok got it happening again, and that's what's happening. When the cursor is a hand, it'll proceed into the game fine (and you can skip the "I woke up in a room I have never seen before" or leaving it alone will automatically take you to the game), but if you manage to click it when it's a pointer you'll be unable to both skip, and get into the game.

Thank you for being a bit on the wording, cause I honestly thought it was just my crappy luck, but when observing the cursor and clicking deliberately in time, it does what you wrote.

**Comment by n0samu** [comment] 2022-10-15 14:22
Ah, I see what you mean now! Yeah, I'm getting the same behavior. Looking at this more closely, I think the rapid cycling between pointer and hand cursors may be due to the white particles spawning off the cursor, which might actually obstruct the button for the purposes of Ruffle's (broken) mouse pick check.

**Comment by n0samu** [comment] 2022-10-15 14:42
> Looking at this more closely, I think the rapid cycling between pointer and hand cursors may be due to the white particles spawning off the cursor

Hmm, nope! I removed the call to function that makes particles from the button's mouseover handler, and it made no difference. I guess this is broken in a more fundamental way.

**Closed** 2022-12-18 20:32 UTC
Labels: bug, avm2, hitTest
