### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by PlagiarisePoison** [ruffle-rs/ruffle#9860] opened 2023-03-05 08:56 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:317:9
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:317:9
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2154:21)
    at std::sync::once::Once::call_once::{{closure}}::h97aad3534cecf95d (wasm://wasm/029406de:wasm-function[2041]:0x4f0c8d)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/029406de:wasm-function[1974]:0x4e173f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h58f54bbbf27f6496 (wasm://wasm/029406de:wasm-function[7451]:0x7b2f53)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/029406de:wasm-function[5250]:0x70a7f2)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/029406de:wasm-function[7780]:0x7c21c7)
    at core::panicking::panic::h27b5eefa3e4ff738 (wasm://wasm/029406de:wasm-function[7172]:0x78dfc0)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hc57a77f2751817cf (wasm://wasm/029406de:wasm-function[600]:0x1de3b4)
    at ruffle_core::loader::Loader::preload_tick::h4459d8164e57e13f (wasm://wasm/029406de:wasm-function[818]:0x2cb48e)
    at ruffle_web::Ruffle::tick::hf697cc8ddb70410e (wasm://wasm/029406de:wasm-function[672]:0x243b17)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=700&sp=0&questionSet=&r=6307800&&width=640&height=500&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-05
Channel: nightly
Built: 2023-03-05T00:24:08.325Z
Commit: 33064465b3311df870cbc20337d524bad47b5ee1
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by Lord-McSweeney** [comment] 2023-03-05 15:31
Duplicate of #9826.

**Closed by Lord-McSweeney** 2023-03-05 15:31 UTC
Labels: error-report
