### ISSUE TITLE
Learn How to Fly 3.swf

### ISSUE THREAD

**Issue by UMBreomn** [ruffle-rs/ruffle#13171] opened 2023-09-13 13:26 UTC
### Describe what you were doing

I booted it up like normally and after the 5 seconds i pressed start game and this happen it just show a error sign after that

![Screenshot 2023-09-13 9 19 57 AM](https://github.com/ruffle-rs/ruffle/assets/127705039/36a0f8f1-2910-4a77-803e-0517da30b95b)

### What does the crash message say?

it said it fail to load next screen

### Ruffle Version

online demo

### Affected platform

Online demo

### Operating system

Chrome OS

**Comment by n0samu** [comment] 2023-09-16 09:40
Duplicate of #10888

**Closed by n0samu** 2023-09-16 09:40 UTC
Labels: bug, duplicate
