### ISSUE TITLE
Focused menu item does not match mouse cursor position

### ISSUE THREAD

**Issue by ShiN-K-278** [ruffle-rs/ruffle#14448] opened 2023-12-18 06:11 UTC
### Describe the bug

In menu bars and dialogs, the position of the mouse cursor does not match the menu item that is focused.
The menu bar is also cut off in the middle.
This has been occurring since ver. 2023-12-15; ver. 2023-12-14 has no problem.
![cap-20231218](https://github.com/ruffle-rs/ruffle/assets/52000350/db39ba9c-3c9f-4924-82f1-95d05cde2092)

### Expected behavior

Match between the focus of the menu item and the position of the mouse cursor.
The menu bar should not be cut off in the middle.

### Content Location

All swf

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment] 2023-12-18 06:12
This was caused by bf9cf92af838b383537e7058df4a88edd1a96a23 and will likely be fixed by #14444.

**Comment by n0samu** [comment] 2023-12-18 06:16
Indeed, fixed by #14444

**Closed by n0samu** 2023-12-18 06:16 UTC
Labels: bug, desktop, regression
