### ISSUE TITLE
Error on https://flashthemes.net/character/creator/family/copy/importedUpload

### ISSUE THREAD

**Issue by ImTheRizzler** [ruffle-rs/ruffle#16133] opened 2024-04-26 15:06 UTC
# Error Info
Error name: Error
Error message: panicked at render/wgpu/src/surface.rs:198:21:
Shader blend should not need stencil buffer
Error stack:
```
Error: panicked at render/wgpu/src/surface.rs:198:21:
Shader blend should not need stencil buffer
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3393:21)
    at js_sys::Error::new::hdd220ef72a1ea21f (wasm://wasm/03a96b1e:wasm-function[13935]:0xb31b9c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0b0ddc27f3250923 (wasm://wasm/03a96b1e:wasm-function[11527]:0xadb90e)
    at std::panicking::rust_panic_with_hook::h9aabd906218897c3 (wasm://wasm/03a96b1e:wasm-function[7110]:0x9a3a37)
    at core::panicking::panic_fmt::h3aff855fe938c13f (wasm://wasm/03a96b1e:wasm-function[11243]:0xad539b)
    at ruffle_render_wgpu::surface::Surface::draw_commands::hd538510769290819 (wasm://wasm/03a96b1e:wasm-function[891]:0x219b94)
    at ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::h5868b15292249ab0 (wasm://wasm/03a96b1e:wasm-function[2850]:0x6cede5)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::submit_frame::h7abe6dcf23fd9ffc (wasm://wasm/03a96b1e:wasm-function[983]:0x2c2f5b)
    at ruffle_web::Ruffle::tick::ha8d7c94c78b040e4 (wasm://wasm/03a96b1e:wasm-function[1099]:0x357315)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h07cb9c73ce736e56 (wasm://wasm/03a96b1e:wasm-function[13873]:0xb31561)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (0x05404C42, Parallels Display Adapter (WDDM) (0x00000000) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/ccw.swf
Param align: middle
Param allowScriptAccess: always
Param allowFullScreen: true
Param wmode: transparent
Param flashvars: apiserver=https%3A%2F%2Fflashthemes.net%2F&userId=64232&isLogin=Y&m_mode=school&isEmbed=0&ctc=go&tlang=en_US&appCode=go&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E&ut=60&v=64232&nextUrl=https%3A%2F%2Fflashthemes.net%2Fcharacter%2Fbrowser&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&themeId=family&original_asset_id=custom
Param movie: /static/animationnew/414827163ad4eb60/ccw.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/character/creator/family/copy/importedUpload
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/ccw.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-04-25
Channel: nightly
Built: 2024-04-25T00:05:37.894Z
Commit: 868ab45c98bd8d1ec97b2fcfc2aea7d260240bae
Is extension: true

# Metadata
width: 960
height: 600
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1062659

**Comment by n0samu** [comment] 2024-05-12 21:37
Duplicate of #15155

**Closed by n0samu** 2024-05-12 21:37 UTC
Labels: duplicate, render-wgpu, error-report
