### ISSUE TITLE
Error on https://www.gameflare.com/embed/jacksmith/

### ISSUE THREAD

**Issue by uguraki** [ruffle-rs/ruffle#12178] opened 2023-07-20 13:12 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.2/src/backend/direct.rs:3019:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.2/src/backend/direct.rs:3019:5
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://www.gameflare.com/emulators/ruffle/core.ruffle.aab2b3501e3c0fcaac35.js:1:51547)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb515a2c9ffd29eb6 (wasm://wasm/02eff9ca:wasm-function[9059]:0x8c803a)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02eff9ca:wasm-function[5924]:0x7c9ed3)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02eff9ca:wasm-function[8903]:0x8c3549)
    at core::ops::function::Fn::call::h7391d934fac8ff6c (wasm://wasm/02eff9ca:wasm-function[6592]:0x80c264)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h5a183f2e818979d2 (wasm://wasm/02eff9ca:wasm-function[4720]:0x73500a)
    at wgpu::backend::direct::Context::handle_error::hd4d13572b49b1c0d (wasm://wasm/02eff9ca:wasm-function[2549]:0x5ac61b)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h19180337ba01c262 (wasm://wasm/02eff9ca:wasm-function[6479]:0x801eba)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h8b0fff45884e1e84 (wasm://wasm/02eff9ca:wasm-function[5535]:0x7ad147)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::hedb93f8524867137 (wasm://wasm/02eff9ca:wasm-function[1639]:0x46c229)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.models::LobbySoldier/swapToSprite()
    at swordGame.models::LobbySoldier/walkCustomer()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Qualcomm, Adreno (TM) 618, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-18
Channel: nightly
Built: 2023-07-18T00:20:26.948Z
Commit: a35ea3d9f21706237068a4978bf5044798591656
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by n0samu** [comment] 2023-07-20 21:53
Duplicate of #12177

**Closed by n0samu** 2023-07-20 21:53 UTC
Labels: duplicate, error-report
