### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Mil0Has** [ruffle-rs/ruffle#8225] opened 2022-10-07 09:19 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
Error stack:
```
966/W/e.wbg.__wbg_new_df6e6ab7a65c4c4d@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.a5a3737e9b5245475835.js:1:6847
std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f@:wasm-function[1024]:0x2a831c
std::sync::once::Once::call_inner::hb30cfbde5209eed0@:wasm-function[1487]:0x32b6b4
core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7@:wasm-function[4934]:0x4897bc
std::panicking::rust_panic_with_hook::hb09154fa23e06c37@:wasm-function[3631]:0x446643
core::panicking::panic_fmt::h9e229748e3ae9f9d@:wasm-function[5089]:0x48cc72
core::result::unwrap_failed::h5da0ab182d2c24a1@:wasm-function[4229]:0x4706df
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h87f89f6d933b9a5b@:wasm-function[2557]:0x3e2fc2
ruffle_core::display_object::render_base::h86fa7eaf5d8f56b5@:wasm-function[1204]:0x2e8135
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hfa8c7706dc71138d@:wasm-function[3855]:0x45c4a6
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h87f89f6d933b9a5b@:wasm-function[2557]:0x3e4663
ruffle_core::display_object::render_base::h86fa7eaf5d8f56b5@:wasm-function[1204]:0x2e8135
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hfa8c7706dc71138d@:wasm-function[3855]:0x45c4fa
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h87f89f6d933b9a5b@:wasm-function[2557]:0x3e4663
ruffle_core::bitmap::bitmap_data::BitmapData::draw::ha5472e54a47658c9@:wasm-function[747]:0x241ae2
ruffle_core::avm1::globals::bitmap_data::draw::h304f9dce76567b49@:wasm-function[626]:0x2032c1
ruffle_core::avm1::function::Executable::exec::h7dbb30579b1dd750@:wasm-function[365]:0xffee6
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h55e375c84faa5088@:wasm-function[491]:0x19b488
ruffle_core::avm1::activation::Activation::run_actions::h263d8988998b3764@:wasm-function[299]:0x1ba6c
ruffle_core::avm1::function::Executable::exec::h7dbb30579b1dd750@:wasm-function[365]:0x100f7f
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h55e375c84faa5088@:wasm-function[491]:0x198794
ruffle_core::avm1::activation::Activation::run_actions::h263d8988998b3764@:wasm-function[299]:0x1ba6c
ruffle_core::avm1::function::Executable::exec::h7dbb30579b1dd750@:wasm-function[365]:0x100f7f
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h55e375c84faa5088@:wasm-function[491]:0x198794
ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_method::h0d24c745a46191c3@:wasm-function[1930]:0x38daa5
ruffle_core::player::Player::run_actions::h3d8339652ee520af@:wasm-function[501]:0x1a4a12
ruffle_web::Ruffle::tick::hcce3b9c42455dc22@:wasm-function[664]:0x217d18
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hfb791d31cd1d45d9@:wasm-function[5970]:0x4a6754
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h476982f031f67f47@:wasm-function[5447]:0x497074
A@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.a5a3737e9b5245475835.js:1:2554
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.a5a3737e9b5245475835.js:1:2231

```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1665064988%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2277549651.9edd8db2bef336ef48b3d68a6c6a4373ad498fd6de5cf5%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22633feb2bda107%22%2C%22NewgroundsAPI_SessionID%22%3A%22Ur8v3dc3sXFTQAbelr6Yf3dab6a607661c013576644bd62dc0237245dfc0yO6l%22%2C%22NewgroundsAPI_UserName%22%3A%22Miorrio%22%2C%22NewgroundsAPI_UserID%22%3A10123731%2C%22ng_username%22%3A%22Miorrio%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-06
Channel: nightly
Built: 2022-10-06T00:17:35.767Z
Commit: 4b2907ead56e5806f441fcb7e32e1030166cb2d2
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by n0samu** [comment] 2022-10-07 09:24
Duplicate of #7978

**Closed by n0samu** 2022-10-07 09:24 UTC
Labels: duplicate, error-report
