### ISSUE TITLE
Error on https://game52567.konggames.com/games/raitendo/you-only-live-once/frame/0ad50e42-ad71-423a-94a9-393e05ac9227/

### ISSUE THREAD

**Issue by Bluewoif007** [ruffle-rs/ruffle#14147] opened 2023-11-25 02:02 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
Error stack:
```
Error: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.428756ab78fcf2125c7a.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h878d7563074f0d48 (wasm://wasm/03368bae:wasm-function[9801]:0x9aec31)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/03368bae:wasm-function[6280]:0x89efd7)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/03368bae:wasm-function[9608]:0x9a9b76)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h6afa4dbc9d5b14f3 (wasm://wasm/03368bae:wasm-function[3529]:0x72a872)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::hb6e7905efa964a4c (wasm://wasm/03368bae:wasm-function[5027]:0x82e608)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::ha271b5e6ec7abab4 (wasm://wasm/03368bae:wasm-function[1169]:0x3e5559)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hf247f4977f95734a (wasm://wasm/03368bae:wasm-function[2116]:0x5bf1e6)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h07b11d1fede59e89 (wasm://wasm/03368bae:wasm-function[950]:0x348477)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::ha271b5e6ec7abab4 (wasm://wasm/03368bae:wasm-function[1169]:0x3e5595)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 605 (0x00003184) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game52567.konggames.com/games/raitendo/you-only-live-once/frame/0ad50e42-ad71-423a-94a9-393e05ac9227/?kongregate_host=www.kongregate.com
SWF URL: https://game52567.konggames.com/gamez/0005/2567/live/yolo.swf?kongregate_game_version=1249158969

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-25
Channel: nightly
Built: 2023-11-25T00:14:25.732Z
Commit: 5920a6426ee82260c5249d7aa988488478ae0ae6
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 50
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 5566959

**Comment by Lord-McSweeney** [comment] 2023-11-25 02:12
Duplicate of #13614

**Closed by Lord-McSweeney** 2023-11-25 02:12 UTC
Labels: error-report, mixed-avm
