### ISSUE TITLE
issue on https://web.archive.org/web/20120918074326/https://www.brainpop.com/

### ISSUE THREAD

**Issue by dewdropsdrops** [ruffle-rs/ruffle#5749] opened 2021-11-27 14:53 UTC
### Describe the bug

Does not display content; instead shows a "Ruffle has encountered a major issue whilst trying to display this Flash content" message where the content should be.
![Screen Shot 2021-11-27 at 22 49 10](https://user-images.githubusercontent.com/77332054/143686245-635091f0-0615-4d67-b6b0-f16f4e269985.png)
The thing encouraged me to file a bug report, so here I am!

### Expected behavior

Some flash buttons/animations should have been displayed.

### Affected platform

Browser's extension

### Operating system

macOS Mojave 10.14.6

### Browser

Google Chrome version 96.0.4664.45

**Comment by Poopooracoocoo** [comment] 2021-11-29 01:35
What version of the extension are you using?

**Comment by dewdropsdrops** [comment] 2021-12-07 14:32
@Poopooracoocoo my bad for not replying earlier. I was using the latest release.

**Comment by Poopooracoocoo** [comment] 2021-12-08 04:18
Which version was that though?

**Comment by dewdropsdrops** [comment] 2021-12-08 05:51
It was version 0.1.0.173 of the Chrome Web Store extension, on macOS 10.14.6.

**Comment by Poopooracoocoo** [comment] 2021-12-08 07:17
Hm. You should see a date as the version of Ruffle. But since you say it's from the Chrome Web Store, it sounds like you've got nightly 2021-07-21. 

But unfortunately this looks like a CORS error. At least when I tested with the latest version of the extension.

**Comment by n0samu** [comment] 2022-09-23 05:09
This issue is not occurring for me. Is it still reproducible for either of you?

**Comment by Poopooracoocoo** [comment] 2022-09-23 05:30
Works here! Want to go ahead and close this issue?

**Closed** 2022-10-23 00:54 UTC
Labels: bug
