### ISSUE TITLE
Error on https://newcp.net/play/gameframe.html

### ISSUE THREAD

**Issue by casslpz** [ruffle-rs/ruffle#18016] opened 2024-09-21 02:44 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/sync/mutex/no_threads.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
69/_e/n.wbg.__wbg_new_796382978dfd4fb0@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1fd47a4dc99e652a91f6.js:1:83857
ruffle_web.wasm.js_sys::Error::new::hfb561c222a4e70eb@:wasm-function[12739]:0x9846c6
ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h8a2a563fa204b611@:wasm-function[9790]:0x914631
ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3@:wasm-function[6358]:0x80526c
ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1@:wasm-function[9509]:0x9052d1
ruffle_web.wasm.core::panicking::assert_failed_inner::hc95b7725cb4077cb@:wasm-function[4405]:0x73b402
ruffle_web.wasm.core::panicking::assert_failed::heb2c1b39dbd0b856@:wasm-function[10263]:0x92f885
ruffle_web.wasm.ruffle_core::loader::Loader::movie_loader::{{closure}}::h566c935379317178@:wasm-function[1053]:0x2bfd1c
ruffle_web.wasm.<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h13f3540dbe40e875@:wasm-function[1521]:0x41ae1f
ruffle_web.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::hf37247571cf9bbf7@:wasm-function[3650]:0x6b94e8
ruffle_web.wasm.<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hbfe4e784c792978a@:wasm-function[11353]:0x9433e6
ruffle_web.wasm.closure7334 externref shim@:wasm-function[11715]:0x949979
P@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1fd47a4dc99e652a91f6.js:1:3740
c@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1fd47a4dc99e652a91f6.js:1:2829

```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0), or similar"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: https://media1.newcp.net/play/v2/client/club_penguin.swf?clientVersion=1726673563
Param menu: false
Param quality: high
Param allowscriptaccess: always
Param wmode: direct
Param flashvars: play=https://media1.newcp.net/play/&client=https://media1.newcp.net/play/v2/client/&content=https://media1.newcp.net/play/v2/content/&games=https://media1.newcp.net/play/v2/games/&connectionID=cp68294&a=0&p=1&nau=&nal=&nas=&nad=&lang=en&phrasechat=https://n7vcp1clubpwns.newcp.net/social/autocomplete/v2/search/&isAS3WebServicesOn=true&cacheVersion=0&clientVersion=1726673563&configVersion=1726673563&contentVersion=1726673563&minigameVersion=1726673563
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute 7: undefined

# Page Info
Page URL: https://newcp.net/play/gameframe.html?cache=1726884905160#/login
SWF URL: https://media1.newcp.net/play/v2/client/club_penguin.swf?clientVersion=1726673563

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-21
Channel: nightly
Built: 2024-09-21T00:06:13.792Z
Commit: 09b3bc25ba902f8c11e6c49cbb77f30a888b79b8
Is extension: false

# Metadata
width: 760
height: 480
frameRate: 24
numFrames: 1
swfVersion: 38
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1172226

**Comment by evilpie** [comment] 2024-10-22 13:04
Duplicate of #17363

**Closed by evilpie** 2024-10-22 13:04 UTC
Labels: error-report
