### ISSUE TITLE
Error on https://dnalc.cshl.edu/view/15983-Today-s-DNA-profile.html

### ISSUE THREAD

**Issue by Karlladaiane** [ruffle-rs/ruffle#4605] opened 2021-06-18 00:21 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:360:46
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:360:46
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://dnalc.cshl.edu/assets/files/ruffle/ruffle.js?t=1623975698:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://dnalc.cshl.edu/assets/files/ruffle/047405885ed91cbe373c77aa56633685.wasm:wasm-function[1362]:0x27e9b3)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://dnalc.cshl.edu/assets/files/ruffle/047405885ed91cbe373c77aa56633685.wasm:wasm-function[1631]:0x2b10ae)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://dnalc.cshl.edu/assets/files/ruffle/047405885ed91cbe373c77aa56633685.wasm:wasm-function[4832]:0x3a6f7f)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://dnalc.cshl.edu/assets/files/ruffle/047405885ed91cbe373c77aa56633685.wasm:wasm-function[3685]:0x37b453)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://dnalc.cshl.edu/assets/files/ruffle/047405885ed91cbe373c77aa56633685.wasm:wasm-function[4347]:0x39a67d)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://dnalc.cshl.edu/assets/files/ruffle/047405885ed91cbe373c77aa56633685.wasm:wasm-function[5188]:0x3ac8ce)
    at rust_begin_unwind (https://dnalc.cshl.edu/assets/files/ruffle/047405885ed91cbe373c77aa56633685.wasm:wasm-function[5067]:0x3ab081)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://dnalc.cshl.edu/assets/files/ruffle/047405885ed91cbe373c77aa56633685.wasm:wasm-function[5189]:0x3ac904)
    at core::panicking::panic::h8e74859c8f9988ca (https://dnalc.cshl.edu/assets/files/ruffle/047405885ed91cbe373c77aa56633685.wasm:wasm-function[4999]:0x3a9f06)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://content.dnalc.org/content/c15/15983/method4.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://dnalc.cshl.edu/view/15983-Today-s-DNA-profile.html
SWF URL: https://content.dnalc.org/content/c15/15983/method4.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 11; SM-P615) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-01
Channel: nightly
Built: 2021-03-01T00:19:40.301Z
Commit: e7d7e19c24edd0d77ffcb5edd8ce0c8ab9d5cf46

**Comment by danielhjacobs** [comment] 2021-06-18 01:08
There's a known bug in Chrome 91 for Android (see https://github.com/ruffle-rs/ruffle/issues/4583#issuecomment-862210945), so it's likely this is caused by that, as it does not seem to be happening on my computer. Perhaps you can try to use the Beta version of Chrome 92 and see if that fixes it.

As a side note, this is the bug report page for the open source technology that page uses called Ruffle. However, purely by chance, since I look at the reported issues here occasionally, I happen to be the DNALC programmer who added Ruffle to the Flash sites it would work on. You should know that the animation on that page is missing a few embedded files, which is why a few slides on that page are mostly blank. If you want to view that animation properly, you can go to http://www.dnai.org/d/, click  "Human Identification", click "profiling", and click the right-most circle (blue).

**Comment by n0samu** [comment] 2022-06-06 19:42
Duplicate of #4583

**Closed by n0samu** 2022-06-06 19:42 UTC
Labels: error-report
