### ISSUE TITLE
Error on https://www.jogos360.com.br/head_action_soccer.html

### ISSUE THREAD

**Issue by Alice-Grem** [ruffle-rs/ruffle#6701] opened 2022-04-13 20:51 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 260 but the index is 260', core/src/backend/render.rs:487:33
Error stack:
```
Error: panicked at 'index out of bounds: the len is 260 but the index is 260', core/src/backend/render.rs:487:33
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.11593b13b6f3a0aa9271.js:1:7708)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.13/ffb28a46c1972f3fe88b.wasm:wasm-function[1011]:0x2a75af)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.13/ffb28a46c1972f3fe88b.wasm:wasm-function[1444]:0x31b161)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.13/ffb28a46c1972f3fe88b.wasm:wasm-function[4908]:0x4774a9)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.13/ffb28a46c1972f3fe88b.wasm:wasm-function[3233]:0x416e69)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.13/ffb28a46c1972f3fe88b.wasm:wasm-function[4990]:0x47b385)
    at core::panicking::panic_bounds_check::he4f030d1ec9ef522 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.13/ffb28a46c1972f3fe88b.wasm:wasm-function[4329]:0x467b81)
    at ruffle_core::backend::render::decode_define_bits_lossless::h7bba247c95cfe088 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.13/ffb28a46c1972f3fe88b.wasm:wasm-function[402]:0x13e1f6)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_png::h6c3d21a406fef216 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.13/ffb28a46c1972f3fe88b.wasm:wasm-function[3970]:0x457d3d)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_bits_lossless::h33cfda64a3fa6e6f (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.13/ffb28a46c1972f3fe88b.wasm:wasm-function[1291]:0x2fa847)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.jogos360.com.br/head_action_soccer.html
SWF URL: https://cdn.jogos360.com.br/files/games/he/ad/head-action-soccer.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-13
Channel: nightly
Built: 2022-04-13T00:18:12.140Z
Commit: e1fbcc70f8d2a837a78a061c781c5971cbc478ed
Is extension: false

**Comment by relrelb** [comment] 2022-04-17 12:53
Duplicate of #6258.

**Closed by relrelb** 2022-04-17 12:53 UTC
Labels: error-report
