### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Mimisor7** [ruffle-rs/ruffle#4169] opened 2021-04-28 19:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
e/a.wbg.__wbg_new_df6e6ab7a65c4c4d@https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1619614181:1:7830
std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407@https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[1039]:0x27cd55
std::sync::once::Once::call_inner::hf7fd718057964857@https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[1241]:0x2b103a
core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32@https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[3721]:0x43f570
std::panicking::rust_panic_with_hook::h9d91fa0fae16500f@https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[2719]:0x399921
rust_begin_unwind@https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[3925]:0x445194
core::panicking::panic_fmt::h91d2023e5afe1929@https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[4065]:0x44b91d
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h675b6a44d145fc3e@https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[833]:0x239ac1
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h387e364c5c8d2f45@https://uploads.ungrounded.net/ruffle_wrapper/lib/5d3e5d908118de813bff.wasm:wasm-function[4190]:0x44d823
R@https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1619614181:1:3686
a@https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1619614181:1:2799

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1619614181%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2243383831.7268da86bb9806fa17652015c06b985fc899517c297b46%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226089bb68aef65%22%2C%22NewgroundsAPI_SessionID%22%3A%229HBG93vgyVgDISvzGc7qc98a453288c673e649c08beec4eaa3676d9d2d38QAG0%22%2C%22NewgroundsAPI_UserName%22%3A%22mimi7%22%2C%22NewgroundsAPI_UserID%22%3A8986071%2C%22ng_username%22%3A%22mimi7%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-28
Channel: nightly
Built: 2021-04-28T00:15:05.059Z
Commit: 5a6117722d08695a471f62474f70d08ae1dcd760

**Comment by torokati44** [comment] 2021-06-09 00:31
Duplicate of #4168.

**Closed by torokati44** 2021-06-09 00:31 UTC

**Comment by Mimisor7** [comment] 2024-01-01 09:27
Please delete this issue! I do not consent to this being on my GitHub profile.
