### ISSUE TITLE
Error on https://archive.org/details/stick-rpg-complete

### ISSUE THREAD

**Issue by ZBLOCKHOGG** [ruffle-rs/ruffle#8606] opened 2022-11-23 16:15 UTC
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/stick-rpg-complete

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15117.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-19
Channel: nightly
Built: 2022-09-19T00:15:10.357Z
Commit: 9b9c95bfe28cb862d44e9517e94e9de73acd9de3
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment] 2022-11-23 18:03
This seems to work fine for me, on Chrome 107, Ubuntu 20.04 (Linux x86_64). I don't have the extension.

**Comment by n0samu** [comment] 2022-11-23 20:17
Hello @ZBLOCKHOGG, please follow the instructions in our FAQ to fix this problem: https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#internetarchive

**Comment by Dinnerbone** [comment] 2024-07-12 22:01
Duplicate of #7683

**Closed by Dinnerbone** 2024-07-12 22:01 UTC
Labels: duplicate, error-report
