### ISSUE TITLE
Error on https://www.friv.com/z/games/scaryscavengerhunt2/index-x.html

### ISSUE THREAD

**Issue by IT12666** [ruffle-rs/ruffle#6845] opened 2022-05-01 17:07 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
@https://www.friv.com/z/games/scaryscavengerhunt2/ruffle.js:1:7839
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hf7fd718057964857]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h9d91fa0fae16500f]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h91d2023e5afe1929]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::hcc9377f967fc44c7]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h96fab9296cbfa34d]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h2a4bc7e130fa01d5]@[wasm code]
wasm-stub@[native code]
I@https://www.friv.com/z/games/scaryscavengerhunt2/ruffle.js:1:3512
a@https://www.friv.com/z/games/scaryscavengerhunt2/ruffle.js:1:2800
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.friv.com/z/games/scaryscavengerhunt2/index-x.html
SWF URL: https://www.friv.com/z/games/scaryscavengerhunt2/ssh2.swf

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-02
Channel: nightly
Built: 2021-05-02T00:14:24.503Z
Commit: 5a4796407e361b03df203995f4782f4ea48ca7af

**Comment by Herschel** [comment] 2022-05-01 22:12
Dupe of #6608, iOS 15.4.

**Closed by Herschel** 2022-05-01 22:12 UTC
