### ISSUE TITLE
Error on https://frivold.menu/public/files/electric-man-2

### ISSUE THREAD

**Issue by MHER2007m** [ruffle-rs/ruffle#6506] opened 2022-03-22 16:35 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://friv2.online/resource/public/js/ruffle/ruffle.js?t=1647966822055:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h28627feee31e90eb (https://friv2.online/resource/public/js/ruffle/510213222482c40adc6b.wasm:wasm-function[1040]:0x31af69)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://friv2.online/resource/public/js/ruffle/510213222482c40adc6b.wasm:wasm-function[1252]:0x3750ae)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha861918671b1460e (https://friv2.online/resource/public/js/ruffle/510213222482c40adc6b.wasm:wasm-function[4757]:0x521a55)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://friv2.online/resource/public/js/ruffle/510213222482c40adc6b.wasm:wasm-function[3335]:0x4db0b4)
    at rust_begin_unwind (https://friv2.online/resource/public/js/ruffle/510213222482c40adc6b.wasm:wasm-function[4820]:0x524329)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://friv2.online/resource/public/js/ruffle/510213222482c40adc6b.wasm:wasm-function[5031]:0x52eeae)
    at core::panicking::panic::hec1fc057bd0baf0b (https://friv2.online/resource/public/js/ruffle/510213222482c40adc6b.wasm:wasm-function[4754]:0x5212bb)
    at core::ops::function::FnOnce::call_once::hc543e126b95bfc01 (https://friv2.online/resource/public/js/ruffle/510213222482c40adc6b.wasm:wasm-function[1104]:0x34aeae)
    at ruffle_core::avm1::function::Executable::exec::h1eede69262aac50e (https://friv2.online/resource/public/js/ruffle/510213222482c40adc6b.wasm:wasm-function[411]:0x15fbcf)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://frivold.menu/public/files/electric-man-2
SWF URL: https://frivold.menu/public/storage/games/November2021/iKueKPLrtlE2EsRtE6AZ.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-05
Channel: nightly
Built: 2021-12-05T00:13:33.026Z
Commit: 0b6cd454155ec9ecd4aef425055e44110240cc8a
Is extension: false

**Comment by relrelb** [comment] 2022-03-22 20:33
Duplicate of #4932.

**Closed by relrelb** 2022-03-22 20:33 UTC
