### ISSUE TITLE
Error on https://flashstorage.games/embed/mini-dash

### ISSUE THREAD

**Issue by NoahLewry** [ruffle-rs/ruffle#11728] opened 2023-06-25 08:56 UTC
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.a750f2f8d9923c3e7c85.js:1:51428)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02cb003e:wasm-function[8728]:0x84d063)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02cb003e:wasm-function[5668]:0x7675c2)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02cb003e:wasm-function[8591]:0x848bde)
    at alloc::raw_vec::capacity_overflow::h3bb4537b5f9f8404 (wasm://wasm/02cb003e:wasm-function[8338]:0x842145)
    at alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h9931bfabb20b44a9 (wasm://wasm/02cb003e:wasm-function[5529]:0x75f23f)
    at ruffle_core::avm2::globals::flash::utils::byte_array::set_length::h94d96dde2d7490c4 (wasm://wasm/02cb003e:wasm-function[3422]:0x65a6d1)
    at ruffle_core::avm2::function::Executable::exec::h3325d83591e2f464 (wasm://wasm/02cb003e:wasm-function[815]:0x2b0148)
    at ruffle_core::avm2::object::TObject::call_method::h7c7d83b9b3e6998f (wasm://wasm/02cb003e:wasm-function[1946]:0x4dea8b)
    at ruffle_core::avm2::object::TObject::set_property::h3a7fe6dd366f5bc5 (wasm://wasm/02cb003e:wasm-function[2164]:0x5299ac)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::length()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at global()
    at com.adobe.flascc::CModule$/callI()
    at com.adobe.flascc::CModule$/start()
    at com.adobe.flascc::CModule$/startAsync()
    at com.adobe.flascc::Console/enterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GT 1030 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://flashstorage.games/embed/mini-dash
SWF URL: https://flashstorage.games/public/storage/games/November2021/QD21VEcY10LnXC2ISIAK.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-25
Channel: nightly
Built: 2023-06-25T00:27:28.646Z
Commit: f24aabf74efbb39ec3858cfdbbe24d33c9dae25b
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 0.1171875
numFrames: 1
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 20666034

**Comment by n0samu** [comment] 2023-06-28 02:37
Duplicate of #10851

**Closed by n0samu** 2023-06-28 02:37 UTC
Labels: avm2, panic, error-report
