### ISSUE TITLE
Error on https://www.friv.cm/electricman-2/

### ISSUE THREAD

**Issue by Indigo2thou** [ruffle-rs/ruffle#8362] opened 2022-10-23 17:13 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.10.23/core.ruffle.da230e854a3dd36c17fb.js:1:7234
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hfe7eb802e4d6ae27]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hb30cfbde5209eed0]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h3a8d5809fdb8bfde]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::hb09154fa23e06c37]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h9e229748e3ae9f9d]@[wasm code]
<?>.wasm-function[core::panicking::panic::h6f5024a57ca8da86]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once::h4279d884d2309c1e]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h9daf60fa7255aaed]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h44d9f586785880a7]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::hd92d98e228b7bc9e]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h02328e28177fd106]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::ha534f70fe5582b5a]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h6e92b0763dce0040]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hcbe5b4d015a3dfc7]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hca52bc1927b605c1]@[wasm code]
wasm-stub@[native code]
E@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.10.23/core.ruffle.da230e854a3dd36c17fb.js:1:2911
c@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.10.23/core.ruffle.da230e854a3dd36c17fb.js:1:2509
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.friv.cm/electricman-2/
SWF URL: https://www.friv.cm/wp-content/games/electricman-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-23
Channel: nightly
Built: 2022-10-23T00:19:24.608Z
Commit: 919b38f20b0b15c5a10c704edb264797e69501da
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment] 2022-10-23 20:21
Duplicate of #4932

**Closed by n0samu** 2022-10-23 20:21 UTC
Labels: duplicate, error-report
