### ISSUE TITLE
Error on https://www.bubblebox.com/play/655/tomb-chess.htm

### ISSUE THREAD

**Issue by DragonGawain** [ruffle-rs/ruffle#4330] opened 2021-05-15 00:36 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://bubblebox.com/ruffle/ruffle.js:1:6924)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (<anonymous>:wasm-function[838]:0x228391)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (<anonymous>:wasm-function[1230]:0x2aacde)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (<anonymous>:wasm-function[3690]:0x43294f)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (<anonymous>:wasm-function[2689]:0x39a39b)
    at rust_begin_unwind (<anonymous>:wasm-function[3892]:0x438094)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (<anonymous>:wasm-function[4004]:0x43b989)
    at core::option::expect_none_failed::h203584ddbc785ca2 (<anonymous>:wasm-function[3321]:0x422f2c)
    at ruffle_core::avm2::object::TObject::install_foreign_trait::h4fbf15553b663e9f (<anonymous>:wasm-function[335]:0xade81)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::he3dc29bc9fd20ccc (<anonymous>:wasm-function[906]:0x2409c8)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.bubblebox.com/play/655/tomb-chess.htm
SWF URL: https://www.bubblebox.com/swf6/655/tomb-chess.swf?gameVersion=1

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-24
Channel: nightly
Built: 2021-04-24T00:32:40.634Z
Commit: 10b014bf1802d405c3c52a2243186f0022dcc0b8

**Comment by relrelb** [comment] 2021-07-22 16:49
Duplicate of #3824.

**Closed by relrelb** 2021-07-22 16:49 UTC
