### ISSUE TITLE
one more level . com  i have one day game not working

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#12500] opened 2023-08-02 17:07 UTC
### Describe the bug

i am useing rufflle on one more level . com and im trying to play the game i have one more day and the game isnt working right and i cant progress now it wont let me start my continue file or create a new file

### Expected behavior

the game to work obviously  

https://github.com/ruffle-rs/ruffle/assets/136838819/a1e401f8-0c4d-4af2-b4f4-0f656a3ba5ec

### Affected platform

Browser's extension

### Operating system

windows 11 

### Browser

microsoft edge

**Comment by ActionWavele** [comment] 2023-08-02 17:12
duplicate of https://github.com/ruffle-rs/ruffle/issues/9014

**Closed** 2023-08-02 17:20 UTC
Labels: bug, duplicate
