### ISSUE TITLE
Error on https://www.gamezhero.com/get-game-code/801fd8c2a4e79c1d24a40dc735c051ae

### ISSUE THREAD

**Issue by luciavelasco** [ruffle-rs/ruffle#10346] opened 2023-03-24 19:48 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmap_data.rs:262:46
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmap_data.rs:262:46
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://www.gamezhero.com/js/min/libs/ruffle/core.ruffle.491bd18f6064cdfdd2f6.js:1:48013)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h97b8c4d82111f198 (wasm://wasm/02ab2b12:wasm-function[8064]:0x7ffb63)
    at std::panicking::rust_panic_with_hook::ha23c8ba67d558e34 (wasm://wasm/02ab2b12:wasm-function[5408]:0x735907)
    at core::panicking::panic_fmt::h573ffd15dee74109 (wasm://wasm/02ab2b12:wasm-function[7947]:0x7fad6f)
    at core::result::unwrap_failed::h26e3bef5a756b770 (wasm://wasm/02ab2b12:wasm-function[6189]:0x774ee0)
    at gc_arena::gc_cell::GcCell<T>::read::h05a9bb5518d33577 (wasm://wasm/02ab2b12:wasm-function[7010]:0x7b9dc9)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::copy_pixels::h642c452e957c3d58 (wasm://wasm/02ab2b12:wasm-function[670]:0x225092)
    at ruffle_core::avm2::function::Executable::exec::h673fc86c77fddd66 (wasm://wasm/02ab2b12:wasm-function[910]:0x2fd8d4)
    at ruffle_core::avm2::object::TObject::call_property::h7bdc7bcd636dd8da (wasm://wasm/02ab2b12:wasm-function[1062]:0x354944)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hf45d0872e6e63e71 (wasm://wasm/02ab2b12:wasm-function[2706]:0x5bc545)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at TileSystem/SetTile()
    at TileSystem/SetPosition()
    at TileSystem/LoadMap()
    at Main/NewGameClick()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gamezhero.com/get-game-code/801fd8c2a4e79c1d24a40dc735c051ae
SWF URL: https://files.gamezhero.com/game/8d2/dfc/8d2dfc11bbfa9ac7/data/williamandsly2.swf

# Browser Info
Opera Version:96.0.4693.80 (arm64) (Opera == Chromium)
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 OPR/96.0.0.0
Platform: ~MacIntel~ M2 Pro chip
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-24
Channel: nightly
Built: 2023-03-24T00:24:35.383Z
Commit: eb44cc5395a9f2a0aa07e9bc9ef6b20d5c4249c2
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 7
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 9903209

**Comment by n0samu** [comment] 2023-03-24 20:33
Duplicate of #9970

**Closed by n0samu** 2023-03-24 20:33 UTC
Labels: duplicate, avm2, error-report
