### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by KazumiFurusawa** [ruffle-rs/ruffle#11034] opened 2023-05-13 07:41 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:350:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:350:26
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2318:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd86e7bc174459a62 (wasm://wasm/02c31cea:wasm-function[8575]:0x83123a)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c31cea:wasm-function[5597]:0x754a29)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c31cea:wasm-function[8426]:0x82c5a6)
    at core::panicking::panic::hea78c4e8b318407d (wasm://wasm/02c31cea:wasm-function[7701]:0x7f037b)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h91f05193ef640cfb (wasm://wasm/02c31cea:wasm-function[633]:0x1f1f4f)
    at ruffle_core::loader::Loader::preload_tick::hbd8c5ebe1da6293c (wasm://wasm/02c31cea:wasm-function[740]:0x287a29)
    at ruffle_web::Ruffle::tick::h13126fb025085e0e (wasm://wasm/02c31cea:wasm-function[734]:0x27c389)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h2bbb2b8dc01f2e3b (wasm://wasm/02c31cea:wasm-function[10331]:0x874b8f)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha5737c35365fbf19 (wasm://wasm/02c31cea:wasm-function[9176]:0x84a3c8)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) RX Vega 11 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=&sp=0&questionSet=&r=6665099&&width=640&height=500&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-13
Channel: nightly
Built: 2023-05-13T00:20:38.156Z
Commit: a023e11098d9f4dc1fe4a8c6768d7e3c47140dc8
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by n0samu** [comment] 2023-05-13 07:53
Duplicate of #9972

**Closed by n0samu** 2023-05-13 07:53 UTC
Labels: duplicate, error-report
