### ISSUE TITLE
Game is not functional

### ISSUE THREAD

**Issue by Pinkspoonbill** [ruffle-rs/ruffle#17647] opened 2024-08-26 01:37 UTC
### Describe the bug

The game at https://www.playitontheweb.com/games/Present-Click-game.htm does not work at all using my version of Ruffle which I downloaded in the last couple of weeks.  It appears to play, but simply runs a timer bar.  
![image](https://github.com/user-attachments/assets/cd8a3686-0b6f-40b8-aefc-eccab0449284)

I am attempting to attach a screenshot of it playing, but not sure if it will work.  In addition to being unable to play, the game does not submit the score, either.  This, however, may be a malfunction of the game site which is not being maintained by its system administrator. 

### Expected behavior

Christmas presents are supposed to appear on the screen for the player to click quickly on. 

### Content Location

https://www.playitontheweb.com/games/Present-Click-game.htm

### Affected platform

Desktop app

### Operating system

Windows 11 Home

### Browser

Firefox

### Additional information

It did not crash.  It simply did not run.  The game is not new.  It was published on this site in 2011.  The site is not being maintained by the system administrator or owner. Although I am pretty sure I know who the owner is, I do not know how to get him to update the game site.

**Comment by Lord-McSweeney** [comment] 2024-08-26 01:47
I can't reproduce this on Firefox. Are you using the web extension?

**Comment by Pinkspoonbill** [comment] 2024-08-26 01:58
I am using the Firefox on my desktop.  I am not sure how to determine which Firefox it is, but there are a number of games on Play It On  The Web and the vast majority of them work using this Firefox.

    On Sunday, August 25, 2024 at 08:47:36 PM CDT, Lord-McSweeney ***@***.***> wrote:  
 
 


I can't reproduce this on Firefox. Are you using the web extension?

**Comment by Pinkspoonbill** [comment] 2024-08-26 02:01
Looks  like it's Version 129 on Windows 11. 

    On Sunday, August 25, 2024 at 08:47:36 PM CDT, Lord-McSweeney ***@***.***> wrote:  
 
 


I can't reproduce this on Firefox. Are you using the web extension?

**Comment by Lord-McSweeney** [comment] 2024-08-26 02:02
The presents appear once you click; you do not click on the presents. Are you sure you're remembering the game correctly?

**Comment by Pinkspoonbill** [comment] 2024-08-26 02:07
Sorry for the extra emails.  This game is not that important.  I just thought you might be looking for content that you could use to find ways to improve Ruffle.  I found this submission form under Ruffle's homepage where it asks for assistance in testing out games.  

This is my very first submission to you, so it is a way that I am learning how to do that, too.  

I love this game site, but the owner of it is not maintaining it, and parts of it do not work.  If he were to assist, perhaps he would be able to help us troubleshoot problems, most likely.  Or, perhaps, the game is too old to run on newer systems.  I would like someone to assist with the gamesite itself, but I know that is beyond your scope.  If you know of anyone, please send them my way.  Or, perhaps no one is able to assist because the owner is the only one who can.  

Thank you for any help.  If this submission is not useful for you, do not worry too much about fixing Ruffle with the game. 

Cathy 
Pinkspoonbill

    On Sunday, August 25, 2024 at 08:47:36 PM CDT, Lord-McSweeney ***@***.***> wrote:  
 
 


I can't reproduce this on Firefox. Are you using the web extension?

**Comment by Pinkspoonbill** [comment] 2024-08-26 02:12
Ok, you are correct.  I thought is wasn't working correctly.  I didn't remember the game as it was a suggested game for a tournament.  I am so sorry.  It does appear to give me a score.  

However, the score is not submitting.  But I think that is because the system administrator isn't doing what he needs to do to repair bugs.  A few other games do not submit the score either.  

I apologize as it does have a score, and the presents do appear now that I click.  What I saw was the screenshot I sent, and I expected the presents to be on the screen. 

Unless Ruffle is preventing the score from submitting, then that is all that can be done.  

Thank you, 
Cathy

    On Sunday, August 25, 2024 at 09:03:18 PM CDT, Lord-McSweeney ***@***.***> wrote:  
 
 


The presents appear once you click; you do not click on the presents. Are you sure you're remembering the game correctly?

**Comment by Lord-McSweeney** [comment] 2024-08-26 02:54
It seems that the submission page is down (when I try to submit the score in FP I get the same result as when I try to do it in Ruffle, a 404 page- `allowNetworking` is also disabled for the SWF, though, so it can't open the URL in the first place). Since neither is an issue with Ruffle, closing this issue.

**Closed** 2024-08-26 02:54 UTC
