### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by RedLion23** [ruffle-rs/ruffle#8578] opened 2022-11-19 04:19 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.8c70adbf772225063284.js:1:6974)
    at std::sync::once::Once::call_once::{{closure}}::h868aa5cd1fef1a90 (wasm://wasm/0184dde6:wasm-function[1060]:0x2a6ba8)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0184dde6:wasm-function[1353]:0x30d91f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h117918d4b59dff10 (wasm://wasm/0184dde6:wasm-function[4892]:0x49833f)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0184dde6:wasm-function[3646]:0x459986)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0184dde6:wasm-function[5122]:0x49ce79)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/0184dde6:wasm-function[4944]:0x4991e9)
    at core::ops::function::FnOnce::call_once::hd91e6f3c9aad192c (wasm://wasm/0184dde6:wasm-function[1245]:0x2e4d7c)
    at ruffle_core::avm1::function::Executable::exec::hed811b2aa544b765 (wasm://wasm/0184dde6:wasm-function[355]:0xdc6c1)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h75382bd14e13c52a (wasm://wasm/0184dde6:wasm-function[903]:0x270d66)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=7517&mp_game_uid=electricman-2&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Felectricman-2&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvZW1hbjIuc3dm&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=America%2FPuerto_Rico&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/eman2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-19
Channel: nightly
Built: 2022-11-19T00:15:56.117Z
Commit: 7e2b876ab333dbd10488a5eebc0e5ca958d3f953
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment] 2023-02-16 13:03
Duplicate of #4932

**Closed by n0samu** 2023-02-16 13:03 UTC
Labels: duplicate, error-report
