### ISSUE TITLE
Error on http://127.0.0.1:5500/Games/ElectricMan2.html

### ISSUE THREAD

**Issue by dyzqy** [ruffle-rs/ruffle#5192] opened 2021-09-01 08:23 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://bopcnbbbbkcgmpjmemncoefdnadhcgpn/dist/ruffle.js?uniqueMessageSuffix=66488398384:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::hff9ad52745108e58 (chrome-extension://bopcnbbbbkcgmpjmemncoefdnadhcgpn/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[916]:0x244400)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (chrome-extension://bopcnbbbbkcgmpjmemncoefdnadhcgpn/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[1173]:0x2a260d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h33084a217c860dce (chrome-extension://bopcnbbbbkcgmpjmemncoefdnadhcgpn/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[4043]:0x42f325)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (chrome-extension://bopcnbbbbkcgmpjmemncoefdnadhcgpn/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[2912]:0x3c4234)
    at rust_begin_unwind (chrome-extension://bopcnbbbbkcgmpjmemncoefdnadhcgpn/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[4257]:0x434d29)
    at core::panicking::panic_fmt::h1fea623755fffed7 (chrome-extension://bopcnbbbbkcgmpjmemncoefdnadhcgpn/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[4416]:0x43bd55)
    at core::panicking::panic::h38cac710b5048ca0 (chrome-extension://bopcnbbbbkcgmpjmemncoefdnadhcgpn/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[4192]:0x432283)
    at core::ops::function::FnOnce::call_once::h507bf889ef500d88 (chrome-extension://bopcnbbbbkcgmpjmemncoefdnadhcgpn/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[890]:0x237e17)
    at ruffle_core::avm1::function::Executable::exec::hb45896e559f84c63 (chrome-extension://bopcnbbbbkcgmpjmemncoefdnadhcgpn/dist/d0109ad57d5486eb7e0e.wasm:wasm-function[385]:0xe79e9)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://127.0.0.1:5500/Games/ElectricMan2.html
SWF URL: http://127.0.0.1:5500/SWF/Elec2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-31
Channel: nightly
Built: 2021-08-31T00:13:32.984Z
Commit: 587c42302705258c31f9162493272edff73ca1d2
Is extension: true

i think it had a prop removing the enemies, i have some expirence with AS3 but im not good with it idk pls fix thx

**Comment by relrelb** [comment] 2021-09-02 20:48
Duplicate of #4932.

**Closed by relrelb** 2021-09-02 20:48 UTC
Labels: duplicate
