### ISSUE TITLE
Text Pop-Up Doesn't Bring Keyboard on Tablet

### ISSUE THREAD

**Issue by zohebnsr** [ruffle-rs/ruffle#3050] opened 2021-02-03 00:39 UTC
Just wanted to let you guys know that tested a game file that brings Text Pop-up to type your name. It works just fine on Computer, but when you tap on that in Mobile/Tablet, it doesn't bring Keyboard.

**Comment by Herschel** [comment] 2021-02-03 00:52
Thanks for the report. Duplicate of #1532.

**Closed by Herschel** 2021-02-03 00:52 UTC
Labels: bug
