### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.htm

### ISSUE THREAD

**Issue by Atulin** [ruffle-rs/ruffle#2771] opened 2021-01-23 00:28 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3110:14
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3110:14
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1611330356:1:6518)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://uploads.ungrounded.net/ruffle_wrapper/lib/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1272]:0x257d2b)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1537]:0x288710)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://uploads.ungrounded.net/ruffle_wrapper/lib/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4316]:0x35e2ca)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://uploads.ungrounded.net/ruffle_wrapper/lib/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[3311]:0x33733d)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[3923]:0x35414d)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://uploads.ungrounded.net/ruffle_wrapper/lib/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4662]:0x363a0c)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4534]:0x362022)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://uploads.ungrounded.net/ruffle_wrapper/lib/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4664]:0x363a70)
    at core::panicking::panic::h0abe4e7a620ae568 (https://uploads.ungrounded.net/ruffle_wrapper/lib/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4468]:0x360ee7)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1611330356%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F668000%2F668041_ponkaanalrodeo-v1-1.swf%3F1451053036%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22600b6d11dd963%22%2C%22NewgroundsAPI_SessionID%22%3A%223ILNcQZnahD9q7CO1Uowe01002914333daffa9f9cb79564550a9fcaa4351UWGP%22%2C%22NewgroundsAPI_UserName%22%3A%22Angius%22%2C%22NewgroundsAPI_UserID%22%3A3950999%2C%22ng_username%22%3A%22Angius%22%7D%2C%22width%22%3A910%2C%22height%22%3A506%2C%22icon%22%3A%22https%3A%2F%2Fimg.ngfiles.com%2Fdefaults%2Ficon-portal-xl-a.gif%3Ff1601395813%22%7D
SWF URL: https://uploads.ungrounded.net/668000/668041_ponkaanalrodeo-v1-1.swf?1451053036

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-22
Channel: nightly
Built: 2021-01-22T01:05:46.108Z
Commit: b05c6540e18bcca93dce9ed6f65fe1f38d65a979

**Comment by relrelb** [comment] 2021-04-24 19:17
Duplicate of #2737.

**Closed by relrelb** 2021-04-24 19:17 UTC
Labels: nsfw
