### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by evilmoocow** [ruffle-rs/ruffle#10338] opened 2023-03-23 23:40 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:326:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:326:26
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2215:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h83e4aeec3086bf1a (wasm://wasm/02a9d60e:wasm-function[8045]:0x7fc5d4)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02a9d60e:wasm-function[5406]:0x7336d8)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02a9d60e:wasm-function[7929]:0x7f79f1)
    at core::panicking::panic::ha3ebcac1438d9280 (wasm://wasm/02a9d60e:wasm-function[7343]:0x7c46d8)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h1532a8203f592d0b (wasm://wasm/02a9d60e:wasm-function[615]:0x1d7574)
    at ruffle_core::loader::Loader::preload_tick::hcefa90c00f063ad8 (wasm://wasm/02a9d60e:wasm-function[795]:0x29da6a)
    at ruffle_web::Ruffle::tick::h5cd98d380b979b43 (wasm://wasm/02a9d60e:wasm-function[694]:0x242e8b)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h1ea2a858f91575a3 (wasm://wasm/02a9d60e:wasm-function[9650]:0x834824)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h27e06ee46e17e7db (wasm://wasm/02a9d60e:wasm-function[8557]:0x8079e3)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=700&sp=0&questionSet=&r=9595204&&width=640&height=500&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-23
Channel: nightly
Built: 2023-03-23T00:19:23.827Z
Commit: f97827ef9c0a384c08af66eba1958ec083a3ccdc
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by n0samu** [comment] 2023-04-22 07:39
Duplicate of #9972

**Closed by n0samu** 2023-04-22 07:39 UTC
Labels: duplicate, error-report
