### ISSUE TITLE
Error on https://www.comdotgame.com/play/ben-10

### ISSUE THREAD

**Issue by slongdogbob1** [ruffle-rs/ruffle#10353] opened 2023-03-25 03:22 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 200000 but the index is 200004', /home/runner/.cargo/git/checkouts/h263-rs-6a92376340b27390/8c00d0e/h263/src/decoder/cpu/idct.rs:160:48
Error stack:
```
Error: panicked at 'index out of bounds: the len is 200000 but the index is 200004', /home/runner/.cargo/git/checkouts/h263-rs-6a92376340b27390/8c00d0e/h263/src/decoder/cpu/idct.rs:160:48
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://echo.comdotgame.com/ruffle/core.ruffle.31c166ab9c2b119e4092.js:1:46508)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h321a9078ff9936f2 (wasm://wasm/02962ab2:wasm-function[7834]:0x7cc186)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/02962ab2:wasm-function[5302]:0x7125e6)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/02962ab2:wasm-function[7726]:0x7c775e)
    at core::panicking::panic_bounds_check::h69c7a7cd0b1c2bb8 (wasm://wasm/02962ab2:wasm-function[6205]:0x755426)
    at h263_rs::decoder::cpu::idct::idct_channel::h0aadb2755ac8afeb (wasm://wasm/02962ab2:wasm-function[552]:0x181b7a)
    at <ruffle_video_software::decoder::h263::H263Decoder as ruffle_video_software::decoder::VideoDecoder>::decode_frame::h6d5ce1d005bb7b6c (wasm://wasm/02962ab2:wasm-function[3479]:0x64fe5d)
    at <ruffle_video_software::backend::SoftwareVideoBackend as ruffle_video::backend::VideoBackend>::decode_video_stream_frame::h0e9c5fe40137d194 (wasm://wasm/02962ab2:wasm-function[1668]:0x47794c)
    at ruffle_core::display_object::video::Video::seek::h0fced08fd91dc9f6 (wasm://wasm/02962ab2:wasm-function[704]:0x261968)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h588d4b7eb59a00e5 (wasm://wasm/02962ab2:wasm-function[3037]:0x5eca7b)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/be3a4ca5984a09d81697f973e8986ddc.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/ben-10
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/be3a4ca5984a09d81697f973e8986ddc.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-12
Channel: nightly
Built: 2023-03-12T00:19:04.440Z
Commit: 1deebc87e869387c962f97b665d26785d0a2b52f
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 30
numFrames: 3142
swfVersion: 9
backgroundColor: #4E4F54
isActionScript3: false
uncompressedLength: 8919915

**Comment by Lord-McSweeney** [comment] 2023-03-25 05:02
Closing as duplicate of #10117. The clamping issue is already fixed with Ruffle's latest versions.

**Closed** 2023-03-25 05:11 UTC
Labels: nsfw, error-report
