### ISSUE TITLE
Error on http://swordandsandals.top/swords-and-sandals-2-full-version/

### ISSUE THREAD

**Issue by FredrikNyberg1** [ruffle-rs/ruffle#13592] opened 2023-10-17 20:20 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu-hal/src/gles/device.rs:705:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1a8b743a0d73f9d3e1ce.js:1:53228)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hed77dbbefdc84f34 (wasm://wasm/0329cace:wasm-function[9712]:0x98e40b)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0329cace:wasm-function[6362]:0x892059)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0329cace:wasm-function[9515]:0x9892ac)
    at core::result::unwrap_failed::h8b3db0f11171b57b (wasm://wasm/0329cace:wasm-function[7985]:0x90f25e)
    at <T as wgpu::context::DynContext>::device_create_texture::he876a6b2d583c4cf (wasm://wasm/0329cace:wasm-function[7090]:0x8cab49)
    at wgpu::Device::create_texture::h1488ca4a9eae3889 (wasm://wasm/0329cace:wasm-function[5411]:0x841647)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::hab75f6c11801d47f (wasm://wasm/0329cace:wasm-function[5231]:0x831324)
    at ruffle_core::display_object::render_base::hddb3a7a71d7e085f (wasm://wasm/0329cace:wasm-function[598]:0x14748d)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h57ce6c1e3c2e4057 (wasm://wasm/0329cace:wasm-function[6934]:0x8b5c3e)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 (0x00002786) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://swordandsandals.top/swords-and-sandals-2-full-version/
SWF URL: http://swordandsandals.top/wp-content/uploads/swords-and-sandals-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-17
Channel: nightly
Built: 2023-10-17T00:21:46.873Z
Commit: b02038bcd25d933ed9f114954e9b59bd6c45d71f
Is extension: false

# Metadata
width: 640
height: 420
frameRate: 30
numFrames: 277
swfVersion: 8
backgroundColor: #FFCC66
isActionScript3: false
uncompressedLength: 5282134

**Comment by evilpie** [comment] 2024-02-01 20:34
Duplicate of https://github.com/ruffle-rs/ruffle/issues/11852

**Closed by evilpie** 2024-02-01 20:34 UTC
Labels: render-wgpu, error-report
