### ISSUE TITLE
Error on https://mm.metrogame.net/metro/ok/

### ISSUE THREAD

**Issue by Artem-kurnevic** [ruffle-rs/ruffle#6221] opened 2022-02-06 08:18 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:305:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/662.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/36e49a176f4711350d1e.wasm:wasm-function[965]:0x2fa5e1)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/36e49a176f4711350d1e.wasm:wasm-function[1178]:0x34496d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/36e49a176f4711350d1e.wasm:wasm-function[4733]:0x4f57a3)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/36e49a176f4711350d1e.wasm:wasm-function[3244]:0x4a2aec)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/36e49a176f4711350d1e.wasm:wasm-function[5003]:0x5018ea)
    at core::panicking::panic::h35778e3c18266c93 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/36e49a176f4711350d1e.wasm:wasm-function[4730]:0x4f52ca)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h640a2e26c8018276 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/36e49a176f4711350d1e.wasm:wasm-function[352]:0xdaf2d)
    at ruffle_core::avm2::activation::Activation::do_next_opcode::hfeb3a14a7657719f (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/36e49a176f4711350d1e.wasm:wasm-function[312]:0x2f140)
    at ruffle_core::avm2::activation::Activation::run_actions::h6d51e9527e6f32fc (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/36e49a176f4711350d1e.wasm:wasm-function[2851]:0x48191a)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: //st.metrogame.net/metro/st/files/450d220bbb25/ok_metro.swf
Param allowScriptAccess: always
Param allowFullScreenInteractive: true
Param wmode: opaque
Param flashvars: container=true&web_server=https://ok.ru&first_start=0&logged_user_id=582919448993&refplace=vitrine_user_apps&new_sig=1&apiconnection=93020928_1644135473223&authorized=1&session_key=-s-7CFmCrSofnKK8rVobCnJ9pyNgnpnDrvp9DHm8MyqgJpr9EupbDCJAKUpdm-rFHxodIrl-HuNBDqsBKVmgDErAGWpZoFmFIUp8GEmDtx3&clientLog=0&session_secret_key=8c15395ba7b8df3726dc4330a84693c3&auth_sig=e02750e374f6361bd09d0da4f8bc6ec2&api_server=https://api.ok.ru/&ip_geo_location=RU,46,Saransk&application_key=CBAEGMIGABABABABA&game.ref=vitrine_user_apps&protocol=http&game.server=ok.metrogame.net&game.static=st.metrogame.net&game.chat=95.213.174.12&game.user=582919448993&game.auth=636edc4396ad02e5a229997872aec8ca&auth=636edc4396ad02e5a229997872aec8ca&embed=metro
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://mm.metrogame.net/metro/ok/?container=true&web_server=https%3A%2F%2Fok.ru&first_start=0&logged_user_id=582919448993&sig=9f8bcabbf5a16458d48d191b00049ccc&refplace=vitrine_user_apps&new_sig=1&apiconnection=93020928_1644135473223&authorized=1&session_key=-s-7CFmCrSofnKK8rVobCnJ9pyNgnpnDrvp9DHm8MyqgJpr9EupbDCJAKUpdm-rFHxodIrl-HuNBDqsBKVmgDErAGWpZoFmFIUp8GEmDtx3&clientLog=0&session_secret_key=8c15395ba7b8df3726dc4330a84693c3&auth_sig=e02750e374f6361bd09d0da4f8bc6ec2&api_server=https%3A%2F%2Fapi.ok.ru%2F&ip_geo_location=RU%2C46%2CSaransk&application_key=CBAEGMIGABABABABA
SWF URL: https://st.metrogame.net/metro/st/files/450d220bbb25/ok_metro.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-06
Channel: nightly
Built: 2022-02-06T00:19:36.677Z
Commit: d7177b474d88041dc3aba3378f92332fb6eb3f8a
Is extension: true

**Comment by Toad06** [comment] 2022-02-06 11:55
Duplicate of #6218.

**Closed by Toad06** 2022-02-06 11:55 UTC
Labels: error-report
