### ISSUE TITLE
Flash Remoting not supported

### ISSUE THREAD

**Issue by ClaudioNunes** [ruffle-rs/ruffle#4482] opened 2021-06-01 15:25 UTC
It seems that  flash files that use flash remoting as RPC don´t work in Ruffle

**Comment by markhughes** [comment] 2023-09-21 09:50
Duplicates #3317

**Comment by danielhjacobs** [comment] 2023-10-20 20:40
Closing this as a duplicate of #3317

**Closed by danielhjacobs** 2023-10-20 20:40 UTC
Labels: enhancement
