### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by blenderbach** [ruffle-rs/ruffle#7125] opened 2022-05-31 16:24 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/966.index.js:1:6395)
    at std::sync::once::Once::call_once::{{closure}}::h074a5b43a199c982 (https://ruffle.rs/demo/69cc574c023b4418d1ce.wasm:wasm-function[1233]:0x2b9b57)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://ruffle.rs/demo/69cc574c023b4418d1ce.wasm:wasm-function[1462]:0x2f7baf)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3cf43421fa49406f (https://ruffle.rs/demo/69cc574c023b4418d1ce.wasm:wasm-function[4912]:0x451444)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://ruffle.rs/demo/69cc574c023b4418d1ce.wasm:wasm-function[3241]:0x3f29e5)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://ruffle.rs/demo/69cc574c023b4418d1ce.wasm:wasm-function[5105]:0x45b59e)
    at core::panicking::panic::hc28e7cc2aa792341 (https://ruffle.rs/demo/69cc574c023b4418d1ce.wasm:wasm-function[5006]:0x4534df)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h3d3d0cdbcda90dbb (https://ruffle.rs/demo/69cc574c023b4418d1ce.wasm:wasm-function[513]:0x15a84d)
    at ruffle_core::avm2::activation::Activation::run_actions::ha0daa767a9e905ce (https://ruffle.rs/demo/69cc574c023b4418d1ce.wasm:wasm-function[354]:0xa85c)
    at ruffle_core::avm2::function::Executable::exec::h1af4e69ff187e2b2 (https://ruffle.rs/demo/69cc574c023b4418d1ce.wasm:wasm-function[755]:0x204c5f)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-31
Channel: nightly
Built: 2022-05-31T00:14:51.997Z
Commit: e4ef3c64060224ed2cfde38c50a82782c3fc7d10
Is extension: false
[watch_as3-vflbRE_EL.zip](https://github.com/ruffle-rs/ruffle/files/8808872/watch_as3-vflbRE_EL.zip)

**Comment by n0samu** [comment] 2023-06-10 04:29
Panic is fixed now. The new error is:
```
INFO run_frame:run_all_phases_avm2: avm_trace: ArgumentError: Error #2012: Video$ class cannot be instantiated.
        at com.google.youtube.players::HTTPVideoPlayer()
        at com.google.youtube.players::PlayerFactory$/getPlayer()
        at com.google.youtube.application::VideoApplication/addVideoPlayer()
        at com.google.youtube.application::VideoApplication/initData()
        at com.google.youtube.application::WatchPageVideoApplication/initData()
        at Function/apply()
        at com.google.youtube.application::Application/guardedCall()
        at com.google.youtube.application::Application/init()
        at com.google.youtube.application::VideoApplication/init()
        at com.google.youtube.application::WatchPageVideoApplication/init()
        at com.google.youtube.application::Application/onInit()
```

**Comment by Dinnerbone** [comment] 2024-07-12 22:05
Duplicate of #7102

**Closed by Dinnerbone** 2024-07-12 22:05 UTC
Labels: duplicate, avm2, error-report
