### ISSUE TITLE
Error on https://www.gameszap.com/game/11139/pac-adventure-draculas-castle.html

### ISSUE THREAD

**Issue by SimulationWithDaniel** [ruffle-rs/ruffle#10436] opened 2023-03-28 22:26 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:296:45
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:296:45
    at U.n.wbg.__wbg_new_15d3966e9981a196 (https://www.gameszap.com/js/frontend/ruffle/core.ruffle.232c98a410606efcc0cf.js:1:47866)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h8cd677756bfcdf86 (wasm://wasm/0298ba0a:wasm-function[7876]:0x7d3f51)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/0298ba0a:wasm-function[5335]:0x717e4e)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/0298ba0a:wasm-function[7767]:0x7cf4f5)
    at core::result::unwrap_failed::h6072dd9795ba6508 (wasm://wasm/0298ba0a:wasm-function[6065]:0x750839)
    at ruffle_core::bitmap::bitmap_data::wrapper::BitmapDataWrapper::sync::h627ceda3dcc1301a (wasm://wasm/0298ba0a:wasm-function[3759]:0x678ea4)
    at ruffle_core::avm1::object::bitmap_data::BitmapDataObject::bitmap_data::h38e13eae5fd973f2 (wasm://wasm/0298ba0a:wasm-function[6777]:0x77dfd1)
    at ruffle_core::avm1::globals::bitmap_data::copy_pixels::hdcd8fed7871ba4cb (wasm://wasm/0298ba0a:wasm-function[637]:0x1f7ac9)
    at ruffle_core::avm1::function::Executable::exec::h38c958325b439c56 (wasm://wasm/0298ba0a:wasm-function[582]:0x19eb6e)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7abbd9838b46d90c (wasm://wasm/0298ba0a:wasm-function[1282]:0x3b63a0)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.gameszap.com/files/swf/pac-adventure-draculas-castle-1537793906.swf
Param movie: https://www.gameszap.com/files/swf/pac-adventure-draculas-castle-1537793906.swf
Param SCALE: exactfit
Param BGCOLOR: #FFF
Param AllowScriptAccess: always
Param quality: high
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.gameszap.com/game/11139/pac-adventure-draculas-castle.html
SWF URL: https://www.gameszap.com/files/swf/pac-adventure-draculas-castle-1537793906.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-13
Channel: nightly
Built: 2023-03-13T00:19:09.191Z
Commit: b527054a1e2317d9e17ed0dfbfc0e9cceaafd760
Is extension: false

# Metadata
width: 585
height: 585
frameRate: 20
numFrames: 2
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3194665

**Comment by Lord-McSweeney** [comment] 2023-03-28 23:06
Duplicate of #9653.

**Closed by Lord-McSweeney** 2023-03-28 23:06 UTC
Labels: error-report
