### ISSUE TITLE
Support (TCP) socket connections

### ISSUE THREAD

**Issue by fp07** [ruffle-rs/ruffle#905] opened 2020-07-22 19:52 UTC
Add support for TCP socket connections.

https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/Socket.html#includeExamplesSummary

Lot of games also have been created with https://www.smartfoxserver.com/, can we get this working also?

**Comment by KuromeSan** [comment] 2020-09-25 12:17
afaik html5 doesnt really have a way to deal with tcp sockets directly.. >_<

**Comment by ROBERT-MCDOWELL** [comment] 2020-09-25 14:32
not true, webtransport is coming, meanwhile there is already chrome.socket.udp, chrome.socket.tcp and chrome.socket.tcp_server
dunno other browser

**Comment by fp07** [comment] 2020-10-12 10:37
Is it an idea to use something like this: https://github.com/novnc/websockify as bridge for tcp support. Is there any similar rust project?

Since a lot of multiplayer games aren't working without support for tcp.

**Comment by spikything** [comment] 2020-12-31 15:29
Yes - this feature is certainly on my wishlist. My old multiplayer game, Dinky Bomb uses XMLSocket (Flash 5 / AVM1). I wish I knew more about how to start implementing this.

**Comment by KuromeSan** [comment] 2021-01-03 10:23
> 
> 
> Yes - this feature is certainly on my wishlist. My old multiplayer game, Dinky Bomb uses XMLSocket (Flash 5 / AVM1). I wish I knew more about how to start implementing this.

i have a private server / server emulator for HI1 .. it also uses xmlsocket

**Comment by KuromeSan** [comment] 2021-05-13 10:05
Oh, also- this could still be done in the windows "projector-like" application, even if it cant be done in HTML5. and potentially in browser extension version too

**Comment by spikything** [comment] 2021-05-13 11:08
> Oh, also- this could still be done in the windows "projector-like" application, even if it cant be done in HTML5. and potentially in browser extension version too

WebRTC I thought - though I'm not knowledgeable enough to implement it myself.

**Comment by ROBERT-MCDOWELL** [comment] 2021-05-13 11:10
@KuromeSan
please take a look at webtransport (HTTP3), it's the very near future of low leve UDP/TCP socket for browsers, you will be able to code any kind of protocols on top, like RTMP,RTMFP

**Comment by torokati44** [comment] 2023-07-29 06:37
At least on desktop, this is supposed to be fixed by https://github.com/ruffle-rs/ruffle/pull/12047.

**Comment by jedenastka** [comment] 2023-08-31 00:02
> not true, webtransport is coming, meanwhile there is already chrome.socket.udp, chrome.socket.tcp and chrome.socket.tcp_server dunno other browser

WebTransport is not TCP or UDP, it's a feature of HTTP3 that allows for functionality *similar* to using TCP or UDP. It still cannot connect to TCP or UDP sockets. That's deliberate browser design. I'm not gonna say if it's good or bad, that's a matter of opinion, and I don't want to start any arguments here, but it is deliberate.

The `chrome.sockets` APIs are Chrome-specific and deprecated. Also, they were part of the extension API (for Chrome Apps, to be specific, which are now deprecated in their entirety), so while the Ruffle extensions for Firefox and Chrome could *maybe* benefit from them, Ruffle builds for WebAssembly cannot.

---

The best way to support this for the WebAssembly target is probably to connect via WebSocket. It will not be supported by the old servers that don't expect WebSocket traffic, but if a server is maintained by the same organization that hosts the game itself, they could still make use of that.

Moreover, it might be useful to allow mapping server addresses to different ones (as a general feature, but especially for the WebAssembly target). This would allow users to host a WebSocket proxy (like the one suggested by fp07, but since it's simple to implement in general, we don't need to favour any specific one) at a different address, and have it point to the real deal. (It would be also useful to host alternative servers, thus it might work as a general feature).

**Comment by ROBERT-MCDOWELL** [comment] 2023-09-03 19:53
@jedenastka
WebTransport is in constant evolution and modification, the release version is still not out. here
https://github.com/w3c/webtransport/issues/542
they talk about datagram specifications (UDP) not clear.... Also with special manifest webassembly can allow low level sockets but here too it's not very clear (yet)

**Comment by jedenastka** [comment] 2023-09-03 22:49
> WebTransport is in constant evolution and modification, the release version is still not out.

It is indeed a draft, but it's already very precise on what it is, and it's not a way to connect to TCP or UDP sockets from the browser.

> here [w3c/webtransport#542](https://github.com/w3c/webtransport/issues/542) they talk about datagram specifications (UDP) not clear....

"Datagram" does not mean "UDP". A datagram is a general term describing an unit of data in a connectionless transport protocol. UDP is a connectionless transport protocol. WebTransport... well, it isn't, but the meaning of the word here is similar.

How do I know that? Because it's already well defined. The issue you posted is in a W3C repo, which does not track the WebTransport protocol, but the WebTransport *API*. The actual protocol is being worked on at IETF. Here's the definition of a "datagram" in WebTransport:

> A datagram is a sequence of bytes that is limited in size (generally to the path MTU) and is not expected to be transmitted reliably. The general goal for WebTransport datagrams is to be similar in behavior to UDP while being subject to common requirements expressed in Section 2.

https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-overview-05#name-datagrams

> Also with special manifest webassembly can allow low level sockets but here too it's not very clear (yet)

There are no plans to have support TCP or UDP in browsers. It's by design. If you believe I'm not correct, feel free to provide links to relevant proposals.

**Comment by ROBERT-MCDOWELL** [comment] 2023-09-05 19:26
@jedenastka
I agree with you. for now low level socket on browser's API is locked. But since I'm following webassembly spec repo on github I read that maybe some manifest will allow to bypass JS limitations in strict conditions. for now the best is indeed an external proxy that manage webrtc/rtmp/rtmfp locally and as a converter (why not).
maybe monaserver2 wrote in Lua and C++ can do the job https://github.com/MonaSolutions/MonaServer2
or the rust lib rtmfp https://github.com/CUB3D/rust-rtmfp , https://github.com/nintha/river , https://github.com/LMinJae/rtmp-rs , https://github.com/KallDrexx/rust-media-libs

**Comment by lanzer-gaia** [comment] 2023-09-08 23:00
Curious, since the Smartfox server support WebSocket, would it be able to interface with a webassembly client without the need for a proxy?

**Comment by n0samu** [comment] 2023-11-11 22:39
This has been implemented on web in #13094!
[See the FAQ for information on how to use it.](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#how-can-i-connect-to-a-tcpsocket-or-xmlsocket-from-the-web)

**Closed by n0samu** 2023-11-11 22:39 UTC
Labels: network
