### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by ZeelX** [ruffle-rs/ruffle#5777] opened 2021-12-01 10:34 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1637687094%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261a7491105d1e%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-23
Channel: nightly
Built: 2021-11-23T00:14:22.573Z
Commit: cf1d0e7624fb84d23087bc0611e3dbf92dcb65e7
Is extension: false

**Comment by Poopooracoocoo** [comment] 2021-12-01 10:56
Duplicate of #3756

**Closed by Poopooracoocoo** 2021-12-01 10:56 UTC
Labels: duplicate, error-report
