### ISSUE TITLE
Error on https://e621.net/posts/1925394?q=lugia+flash

### ISSUE THREAD

**Issue by BrazilianDood** [ruffle-rs/ruffle#2935] opened 2021-01-29 00:17 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32283
    at r (<anonymous>:3:32773)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/1925394?q=lugia+flash

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.53
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-28
Channel: nightly
Built: 2021-01-28T00:36:59.079Z
Commit: 5e0527c59944d5888128c63f37d23880fdb0c6ff

**Comment by Herschel** [comment] 2021-01-29 00:21
Duplicate of #2201.

**Closed by Herschel** 2021-01-29 00:21 UTC
Labels: nsfw
