### ISSUE TITLE
Error on https://www.supersmashflash.com/play/ssf2/

### ISSUE THREAD

**Issue by SN902** [ruffle-rs/ruffle#12672] opened 2023-08-10 03:51 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9
Error stack:
```
339/__wbg_get_imports/imports.wbg.__wbg_new_d258248ed531ff54@moz-extension://7746026e-258e-4076-8dc3-bb7a4d832467/dist/339.js:2423:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::h0862777a56a42e9b@:wasm-function[9205]:0x94491e
std::panicking::rust_panic_with_hook::hf98c7e0a0a18342f@:wasm-function[6078]:0x84cec6
core::panicking::panic_fmt::h76dddd2eea2620b6@:wasm-function[9050]:0x94034b
core::panicking::assert_failed_inner::h67b579cb785d4ba1@:wasm-function[4130]:0x74ece7
core::panicking::assert_failed::hea30055332618f08@:wasm-function[7650]:0x8c5b80
ruffle_core::loader::Loader::movie_loader::{{closure}}::hc3c41085fae0e2ec@:wasm-function[713]:0x247245
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hd84c1296fe00cbde@:wasm-function[1170]:0x3d7bea
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hbf3ad3dc7003e961@:wasm-function[4026]:0x73eab6
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hf5b26d58a5f5005b@:wasm-function[9857]:0x960029
__wbg_adapter_67@moz-extension://7746026e-258e-4076-8dc3-bb7a4d832467/dist/339.js:327:10
real@moz-extension://7746026e-258e-4076-8dc3-bb7a4d832467/dist/339.js:300:20

```
AVM2 stack:
```
    at com.mcleodgaming.ssf2.util::Utils$/d()
    at com.mcleodgaming.ssf2.util::Resource/getProp()
    at com.mcleodgaming.ssf2.engine::Stats$/init()
    at com.mcleodgaming.ssf2::Main$/initGame()
    at MethodInfo-13()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 640, height: 360, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /flash/?f=games/SSF2Beta_v1_3_1_2.swf
Param movie: /flash/?f=games/SSF2Beta_v1_3_1_2.swf
Param quality: high
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.supersmashflash.com/play/ssf2/
SWF URL: https://www.supersmashflash.com/flash/?f=games/SSF2Beta_v1_3_1_2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-02
Channel: nightly
Built: 2023-08-02T21:06:00.696Z
Commit: unknown
Is extension: true

# Metadata
width: 640
height: 360
frameRate: 30
numFrames: 1
swfVersion: 40
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 4246110

**Comment by n0samu** [comment] 2023-08-10 03:54
Duplicate of #12671

**Closed by n0samu** 2023-08-10 03:54 UTC
Labels: duplicate, error-report
