### ISSUE TITLE
Nightly build 2021-02-18 firefox extension doesn't work

### ISSUE THREAD

**Issue by haraldbre** [ruffle-rs/ruffle#3312] opened 2021-02-18 08:15 UTC
Though there still were a number of bugs, up to nightly build 2021-02-16 the firefox extension worked quite well for web page http://www.hwjyw.com/textbook/dzjc/zh/cdx/.., x from 1 to 12. Now it completely fails. 
For instance web page http://www.hwjyw.com/textbook/dzjc/zh/cd3/main8/index.htm with nightly build 2021-02-16 shows
![image](https://user-images.githubusercontent.com/40523009/108325445-5d24f380-71c9-11eb-9a5e-c4908a74adf3.png)
Nightly build 2021-02-16 shows
![image](https://user-images.githubusercontent.com/40523009/108325617-86de1a80-71c9-11eb-8337-2af2a1a4fd69.png)

Platform is Firefox 78.7.0esr (64-Bit) for openSuse Leap 15.2

**Comment by torokati44** [comment] 2021-02-18 09:09
Looks like a duplicate of https://github.com/ruffle-rs/ruffle/issues/3305

**Closed** 2021-02-18 09:14 UTC
Labels: bug, duplicate

**Comment by haraldbre** [comment] 2021-02-19 07:48
Has been fixed with nightly build 2921-02-19
