### ISSUE TITLE
Error on https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/0299768e-5f3f-4123-96f3-86933d037507/

### ISSUE THREAD

**Issue by frankheijnders** [ruffle-rs/ruffle#14613] opened 2024-01-04 16:21 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.bd7849cffafa6c039e79.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2784d75c097bd38f (wasm://wasm/035c5486:wasm-function[10701]:0xa03b08)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/035c5486:wasm-function[6566]:0x8edb9a)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/035c5486:wasm-function[10424]:0x9fd885)
    at core::ops::function::Fn::call::h31fcd9672878c467 (wasm://wasm/035c5486:wasm-function[6866]:0x9045e6)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h55f5091b89514ccd (wasm://wasm/035c5486:wasm-function[5407]:0x88481f)
    at <T as wgpu::context::DynContext>::device_create_texture::h225b6453d716a130 (wasm://wasm/035c5486:wasm-function[7380]:0x92fbf8)
    at wgpu::Device::create_texture::h78431bdcb2a23fa9 (wasm://wasm/035c5486:wasm-function[5736]:0x8a286d)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::h9e779c3e1c053376 (wasm://wasm/035c5486:wasm-function[2176]:0x5ecb18)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::hc5a276a0ba76aba6 (wasm://wasm/035c5486:wasm-function[1590]:0x4d0826)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1837()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00009B41) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/0299768e-5f3f-4123-96f3-86933d037507/?kongregate_host=www.kongregate.com
SWF URL: https://game286444.konggames.com/gamez/0028/6444/live/ma2.9.8GProt.swf?kongregate_game_version=1506420754

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-04
Channel: nightly
Built: 2024-01-04T00:14:57.973Z
Commit: 0a6a95e6f1bb9becd6dc97e590a06f90a75c083c
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9716767

**Comment by n0samu** [comment] 2024-01-05 06:30
Duplicate of #13946

**Closed by n0samu** 2024-01-05 06:30 UTC
Labels: duplicate, error-report
