### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Yeagh** [ruffle-rs/ruffle#8478] opened 2022-11-05 01:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/collections/btree/navigate.rs:522:22
Error stack:
```
@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.0c513c0e24fbd78a6fcf.js:1:6930
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h9abcd8d2861dbb63]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h34aee843864daceb]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h20c00e1373f93c44]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h70a0e195f4db2a29]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h751be80779d42b53]@[wasm code]
<?>.wasm-function[core::panicking::panic::h8af046397a2bf65d]@[wasm code]
<?>.wasm-function[<core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::h57d666519d14b41c]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::run_goto::h841b3f0b415af78b]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::goto_frame::h7a16684040cf4df6]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::globals::movie_clip::goto_frame::h5582f852bbbdc194]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h7275d552df1433b3]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h5e73298b5371df3e]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::h8684849bb7a36cd5]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h38087431bfe5118f]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hf5b270d4504b5c7d]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h71963c4857b1dd78]@[wasm code]
wasm-stub@[native code]
F@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.0c513c0e24fbd78a6fcf.js:1:3057
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.0c513c0e24fbd78a6fcf.js:1:2509
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=mobile&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1667576164%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F861000%2F861556_creambee-anaringu-v1.swf%3F1667058580%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226365b753932ea%22%2C%22NewgroundsAPI_SessionID%22%3A%22ttAEFjErxNbmYgS46GQV6a5c186d5b0873f272cde61e41b2b0d78d6c94b6Pr10%22%2C%22NewgroundsAPI_UserName%22%3A%22K7126061%22%2C%22NewgroundsAPI_UserID%22%3A7612945%2C%22ng_username%22%3A%22K7126061%22%7D%2C%22width%22%3A1060%2C%22height%22%3A920%2C%22icon%22%3A%22https%3A%2F%2Fimg.ngfiles.com%2Fdefaults%2Ficon-portal-xl-a.gif%3Ff1601395813%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/861000/861556_creambee-anaringu-v1.swf?1667058580

# Browser Info
User Agent: Mozilla/5.0 (iPad; CPU OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/107.0.5304.66 Mobile/15E148 Safari/604.1
Platform: iPad
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-04
Channel: nightly
Built: 2022-11-04T00:16:33.453Z
Commit: d16e9e15118bba9b01527ac042c3c00bb987a23f
Is extension: false

# Metadata
width: 1060
height: 997
frameRate: 29
numFrames: 5
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 13077652

**Comment by n0samu** [comment] 2022-11-08 03:51
Duplicate of #6608. Updating your device to the latest iOS version should fix the issue!

**Closed by n0samu** 2022-11-08 03:51 UTC
Labels: duplicate, nsfw, error-report
