### ISSUE TITLE
Error on https://f.silvergames.com/ruffle/player.php

### ISSUE THREAD

**Issue by Umar12ze** [ruffle-rs/ruffle#7437] opened 2022-07-18 03:30 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.17.10/src/fill.rs:1942:74
Error stack:
```
@https://f.silvergames.com/ruffle/20062022/core.ruffle.233301ec188ca77039a7.js:1:7033
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hcb68776b73c9e6d4]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h8a142b2dcc139875]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h06135d218edbba4d]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::he2a025723e105e28]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hb02133958c1e7d35]@[wasm code]
<?>.wasm-function[core::panicking::panic::hc28e7cc2aa792341]@[wasm code]
<?>.wasm-function[core::slice::sort::shift_tail::h5e526e666d6771cf]@[wasm code]
<?>.wasm-function[core::slice::sort::recurse::h61099cea617f7bf4]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::process_events::h864bd97e6f2f97bf]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_impl::h225feadf8e24f602]@[wasm code]
<?>.wasm-function[ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h876515d8424ede35]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h3aed498bf7a12a7a]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h2705940f1db3609f]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::hccd500b45af05397]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h0385c4b343183d16]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbd0a09a2cc56a00a]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7c8dc94962164a1f]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::hecbd40711c9dbe6f]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hd96d956c8ead6a7f]@[wasm code]
wasm-stub@[native code]
L@https://f.silvergames.com/ruffle/20062022/core.ruffle.233301ec188ca77039a7.js:1:3966
c@https://f.silvergames.com/ruffle/20062022/core.ruffle.233301ec188ca77039a7.js:1:2491
promiseReactionJob@[native code]
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://f.silvergames.com/ruffle/player.php?id=4523
SWF URL: https://f.silvergames.com/maggie-saw-game.swf

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-20
Channel: nightly
Built: 2022-06-20T00:17:11.892Z
Commit: b4bed3c931213ba369a3c835efc8b657e8becafd
Is extension: false

**Comment by n0samu** [comment] 2022-07-18 14:14
Duplicate of #6608
Updating your device to iOS 15.5 should fix the issue!

**Closed by n0samu** 2022-07-18 14:14 UTC
Labels: duplicate, error-report
