### ISSUE TITLE
Error on http://www.freeworldgroup.com/games8/gameindex/skiesofwar.htm

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#4075] opened 2021-04-21 06:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/bitmap_data.rs:1212:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/bitmap_data.rs:1212:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/ruffle.js:1:6940)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (http://www.freeworldgroup.com/ruffle/ecfd9aa337fb44257dd6055b94ce0b69.wasm:wasm-function[820]:0x21a777)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (http://www.freeworldgroup.com/ruffle/ecfd9aa337fb44257dd6055b94ce0b69.wasm:wasm-function[1218]:0x29e3dc)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (http://www.freeworldgroup.com/ruffle/ecfd9aa337fb44257dd6055b94ce0b69.wasm:wasm-function[3677]:0x429d3f)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (http://www.freeworldgroup.com/ruffle/ecfd9aa337fb44257dd6055b94ce0b69.wasm:wasm-function[2677]:0x38f1a0)
    at rust_begin_unwind (http://www.freeworldgroup.com/ruffle/ecfd9aa337fb44257dd6055b94ce0b69.wasm:wasm-function[3879]:0x42f703)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (http://www.freeworldgroup.com/ruffle/ecfd9aa337fb44257dd6055b94ce0b69.wasm:wasm-function[3987]:0x4324cd)
    at core::panicking::panic::h5da66f104e83c46a (http://www.freeworldgroup.com/ruffle/ecfd9aa337fb44257dd6055b94ce0b69.wasm:wasm-function[3820]:0x42cfba)
    at ruffle_core::avm1::globals::bitmap_data::load_bitmap::h4310f5fe6e4fe8a8 (http://www.freeworldgroup.com/ruffle/ecfd9aa337fb44257dd6055b94ce0b69.wasm:wasm-function[585]:0x18a853)
    at ruffle_core::avm1::function::Executable::exec::h2f10b52533c0dd6d (http://www.freeworldgroup.com/ruffle/ecfd9aa337fb44257dd6055b94ce0b69.wasm:wasm-function[352]:0xc9bd8)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games8/gameindex/skiesofwar.htm
SWF URL: http://www.freeworldgroup.com/games8/skiesofwar/skiesofwar.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-21
Channel: nightly
Built: 2021-04-21T00:41:42.992Z
Commit: 46ddc31254ae1394b34b4f2e666bd2dc7eecd75b

**Comment by relrelb** [comment] 2021-04-24 12:14
Duplicate of #3765.

**Closed by relrelb** 2021-04-24 12:14 UTC
