### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by omegawolf18** [ruffle-rs/ruffle#8066] opened 2022-09-24 03:58 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.b178705079809261f957.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::h8ea9ab9bf1a6fa87 (wasm://wasm/01821942:wasm-function[1012]:0x29c225)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01821942:wasm-function[1477]:0x328413)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7b268efc0b6187e5 (wasm://wasm/01821942:wasm-function[4965]:0x48fa2c)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01821942:wasm-function[3648]:0x44be72)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01821942:wasm-function[5118]:0x495878)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/01821942:wasm-function[4250]:0x475fff)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h5820ec0a83836068 (wasm://wasm/01821942:wasm-function[2545]:0x3e58e2)
    at ruffle_core::display_object::render_base::h7777b5167692c332 (wasm://wasm/01821942:wasm-function[1191]:0x2daa1e)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h3f188cc52db38393 (wasm://wasm/01821942:wasm-function[3867]:0x461af2)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1663941735%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2233293186.6cac7c66f7e2361de7b69b518ffd165a51084aab1e3b51%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22632e7f66c96f3%22%2C%22NewgroundsAPI_SessionID%22%3A%22MrwM2O6gFJiuTp81FrtM544b752d7d03a9307272da3f9794d9abdcb0e36brhs6%22%2C%22NewgroundsAPI_UserName%22%3A%22OMEGAWOLF12345%22%2C%22NewgroundsAPI_UserID%22%3A11923430%2C%22ng_username%22%3A%22OMEGAWOLF12345%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.84
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-23
Channel: nightly
Built: 2022-09-23T00:15:34.189Z
Commit: a17352a01ad50a0f52666c054b22cec51306689c
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by n0samu** [comment] 2022-09-24 04:02
Duplicate of #7978

**Closed by n0samu** 2022-09-24 04:02 UTC
Labels: duplicate, error-report
