### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm

### ISSUE THREAD

**Issue by Rackover** [ruffle-rs/ruffle#7440] opened 2022-07-18 12:54 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:822:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:822:18
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6063)
    at std::sync::once::Once::call_once::{{closure}}::h07c7135151ec780d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/12f10f41da8e23f802ac.wasm:wasm-function[1198]:0x2af267)
    at std::sync::once::Once::call_inner::hecc7c66a7de7e98e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/12f10f41da8e23f802ac.wasm:wasm-function[1376]:0x2e6ac9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h47122da6528de98d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/12f10f41da8e23f802ac.wasm:wasm-function[4688]:0x429f41)
    at std::panicking::rust_panic_with_hook::h8888bbc201384d7b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/12f10f41da8e23f802ac.wasm:wasm-function[3071]:0x3db3f5)
    at core::panicking::panic_fmt::h18b15be283411c65 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/12f10f41da8e23f802ac.wasm:wasm-function[4870]:0x430031)
    at core::panicking::panic::h0207b244811fef8b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/12f10f41da8e23f802ac.wasm:wasm-function[4781]:0x42bf8c)
    at core::ops::function::FnOnce::call_once::h46045b05db582bcc (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/12f10f41da8e23f802ac.wasm:wasm-function[1019]:0x27c722)
    at ruffle_core::avm1::function::Executable::exec::hb7781951e2a38809 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/12f10f41da8e23f802ac.wasm:wasm-function[383]:0xfa3b3)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h3726dd1057f6219a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/12f10f41da8e23f802ac.wasm:wasm-function[799]:0x21e673)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm
SWF URL: http://www.freeworldgroup.com/games6/electricman2/electricman2hs_fwg.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.49
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-18
Channel: nightly
Built: 2022-07-18T00:13:58.498Z
Commit: 22d2810ef97e0de903cfc2ff14937f1143a7f9fa
Is extension: true

**Comment by n0samu** [comment] 2022-07-18 14:12
Duplicate of #4932

**Closed by n0samu** 2022-07-18 14:12 UTC
Labels: duplicate, error-report
