### ISSUE TITLE
Performance regression in Starling becnhmark

### ISSUE THREAD

**Issue by HaimZik** [ruffle-rs/ruffle#11985] opened 2023-07-10 11:21 UTC
### Describe the bug

10/7 webgl build execute Starling benchmark more than twice slower.
Desktop build is slightly faster than 9/7.
It probable caused by 
https://github.com/ruffle-rs/ruffle/pull/11182
or https://github.com/ruffle-rs/ruffle/pull/11526

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-10
Channel: nightly
Built: 2023-07-10T00:19:59.996Z
Commit: f5b4fbce77b229de1df1738cd6375079c3b3bd3b
Is extension: false

# Metadata
width: 320
height: 480
frameRate: 60
numFrames: 1
swfVersion: 43
backgroundColor: #222222
isActionScript3: true
uncompressedLength: 1317843

### Expected behavior

Have higher sprite count than 9/7 build.

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome

### Additional information

[StarlingBenchmark.zip](https://github.com/ruffle-rs/ruffle/files/12001190/StarlingBenchmark.zip)

**Comment by n0samu** [comment] 2023-07-10 11:38
Ah yeah, I can see that the framerate is terrible in the animation tests now. Thanks for letting us know!

**Comment by n0samu** [comment] 2023-07-10 11:55
Testing the relevant commits, #11526 seems to be responsible. And the regression is most noticeable in Firefox for me.

**Comment by HaimZik** [comment] 2023-07-10 12:05
The swf is a benchmark so you can get exact numbers.
Also you can display fps counter by pressing the bottom of the screen, where "Dummy ruffle Driver" text is shown.
![image](https://github.com/ruffle-rs/ruffle/assets/1851717/f1b74146-83bd-4ecd-93c6-501b06ee6213)

**Comment by adrian17** [comment] 2024-07-09 19:56
This got fixed by https://github.com/ruffle-rs/ruffle/pull/17014 .

**Closed by adrian17** 2024-07-09 19:56 UTC
Labels: web, rendering, performance, regression
