### ISSUE TITLE
Error on https://www.gameflare.com/embed/jacksmith/

### ISSUE THREAD

**Issue by TheBurntLifeguard** [ruffle-rs/ruffle#13029] opened 2023-08-31 20:01 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://www.gameflare.com/emulators/ruffle/core.ruffle.0b7b3fa0b12148fa5c11.js:1:51650)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h81b6d13caa3cc4ad (wasm://wasm/0306a596:wasm-function[9275]:0x912ca4)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/0306a596:wasm-function[6027]:0x811d71)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/0306a596:wasm-function[9115]:0x90e37d)
    at core::ops::function::Fn::call::h45dbe8c37cd66acc (wasm://wasm/0306a596:wasm-function[6234]:0x81df26)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h237e755d96884256 (wasm://wasm/0306a596:wasm-function[4873]:0x77d7bf)
    at wgpu::backend::direct::Context::handle_error::hc2e6b8a3ef9311fd (wasm://wasm/0306a596:wasm-function[2511]:0x5d39f7)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h114c4afffc56c821 (wasm://wasm/0306a596:wasm-function[6616]:0x84af06)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h42712e3f80695e9c (wasm://wasm/0306a596:wasm-function[5651]:0x7f3a93)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h82c25ad0a71d68ba (wasm://wasm/0306a596:wasm-function[1565]:0x479c05)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 605 (GLK 3), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-29
Channel: nightly
Built: 2023-08-29T00:21:45.895Z
Commit: 0ed447b42877b10fdaaf913015eb2783cd9afb04
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by evilpie** [comment] 2024-02-16 14:21
Duplicate of #11591.

**Closed by evilpie** 2024-02-16 14:21 UTC
Labels: render-wgpu, error-report
