### ISSUE TITLE
Error on https://www.miniplay.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by esaipavan** [ruffle-rs/ruffle#15940] opened 2024-04-09 15:05 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f77055/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f77055/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.2aa8a522df98a3895030.js:1:73847)
    at js_sys::Error::new::he430f3df5e112981 (wasm://wasm/03a4ffaa:wasm-function[13930]:0xb204e9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hfac401b21583e2cb (wasm://wasm/03a4ffaa:wasm-function[11530]:0xacb60a)
    at std::panicking::rust_panic_with_hook::h5ca5fd3b2064be1b (wasm://wasm/03a4ffaa:wasm-function[7113]:0x99586d)
    at core::panicking::panic_fmt::h2582bddf31c1c986 (wasm://wasm/03a4ffaa:wasm-function[11237]:0xac4efa)
    at core::option::expect_failed::h7996a6a7be71bb45 (wasm://wasm/03a4ffaa:wasm-function[9804]:0xa69ae9)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::hdb0348dc9a7ae517 (wasm://wasm/03a4ffaa:wasm-function[775]:0x1102e4)
    at nom::multi::many_m_n::{{closure}}::h042ba55b12c6c518 (wasm://wasm/03a4ffaa:wasm-function[3433]:0x7622dc)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::hdb0348dc9a7ae517 (wasm://wasm/03a4ffaa:wasm-function[775]:0x10d92f)
    at flash_lso::amf3::read::AMF3Decoder::parse_object_static::h6715c4fa471ace3b (wasm://wasm/03a4ffaa:wasm-function[4529]:0x8451c2)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at BinaryData$/getMovieClipManager()
    at Game/onLoadComplete()
    at Game()
    at Main/createGame()
    at Main/onRootCreated()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1910()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x000046A3) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (1000, 750, 1)

# Page Info
Page URL: https://www.miniplay.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=206531&mp_game_uid=tequila-zombies-3&mp_game_url=https%3A%2F%2Fwww.miniplay.com%2Fembed%2Ftequila-zombies-3&mp_int=1&mp_locale=en_US&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vdjMvZ2FtZXMvZ2FtZXMvcHJvZC8yMDY1MzEvdGVxdWlsYS0zLnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_site_name=miniplay.com&mp_site_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_timezone=Europe%2FMadrid&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/v3/games/games/prod/206531/tequila-3.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-04-09
Channel: nightly
Built: 2024-04-09T00:06:34.219Z
Commit: f737739c15b92d687e8e4b2193519702a7d0a15b
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 21
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 38081696

**Comment by evilpie** [comment] 2024-07-23 10:11
Duplicate of #13748

**Closed** 2024-07-23 10:11 UTC
Labels: error-report, amf
