### ISSUE TITLE
Error on https://e621.net/posts/2260835

### ISSUE THREAD

**Issue by kirinknight** [ruffle-rs/ruffle#3869] opened 2021-04-02 01:57 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at chrome-extension://cpjccfjiocobbknepmfiecbigelhcaph/dist/ruffle.js?obfuscatedEventPrefix=rufEvent73167510627:1:32253
    at r (chrome-extension://cpjccfjiocobbknepmfiecbigelhcaph/dist/ruffle.js?obfuscatedEventPrefix=rufEvent73167510627:1:32743)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/2260835?q=gynomorph_penetrating_male

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-28
Channel: nightly
Built: 2021-03-28T00:41:48.808Z
Commit: 0063f40af9cd6dd39038d67880db1d996176c309

**Comment by Poopooracoocoo** [comment] 2021-04-10 03:17
Duplicate of #2201

**Closed by Poopooracoocoo** 2021-04-10 03:17 UTC
