### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by hackinghacker1** [ruffle-rs/ruffle#7166] opened 2022-06-05 14:10 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/966.index.js:1:7787)
    at std::sync::once::Once::call_once::{{closure}}::h074a5b43a199c982 (https://ruffle.rs/demo/87e91816d6525bcea69a.wasm:wasm-function[1235]:0x2ba461)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://ruffle.rs/demo/87e91816d6525bcea69a.wasm:wasm-function[1463]:0x2f7e3f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3cf43421fa49406f (https://ruffle.rs/demo/87e91816d6525bcea69a.wasm:wasm-function[4916]:0x45208f)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://ruffle.rs/demo/87e91816d6525bcea69a.wasm:wasm-function[3256]:0x3f3886)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://ruffle.rs/demo/87e91816d6525bcea69a.wasm:wasm-function[5107]:0x45bad9)
    at core::panicking::panic::hc28e7cc2aa792341 (https://ruffle.rs/demo/87e91816d6525bcea69a.wasm:wasm-function[5008]:0x453a1a)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h3d3d0cdbcda90dbb (https://ruffle.rs/demo/87e91816d6525bcea69a.wasm:wasm-function[513]:0x15a0b8)
    at ruffle_core::avm2::activation::Activation::run_actions::ha0daa767a9e905ce (https://ruffle.rs/demo/87e91816d6525bcea69a.wasm:wasm-function[354]:0xa844)
    at ruffle_core::avm2::function::Executable::exec::h1af4e69ff187e2b2 (https://ruffle.rs/demo/87e91816d6525bcea69a.wasm:wasm-function[757]:0x20570c)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-05
Channel: nightly
Built: 2022-06-05T00:17:47.100Z
Commit: 9e4d13f201634b5d24e2cc9a40c78fc9306eb3c3
Is extension: false

**Comment by Dinnerbone** [comment] 2024-07-12 22:05
Duplicate of #7102

**Closed by Dinnerbone** 2024-07-12 22:05 UTC
Labels: duplicate, error-report
