### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by XxMr-InKxX** [ruffle-rs/ruffle#3889] opened 2021-04-04 03:19 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1617493832:1:6915)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ac201885e6d7bf4f51cad3e98cd368d6.wasm:wasm-function[1196]:0x28eb16)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ac201885e6d7bf4f51cad3e98cd368d6.wasm:wasm-function[1782]:0x309bb5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ac201885e6d7bf4f51cad3e98cd368d6.wasm:wasm-function[5307]:0x418e9b)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://uploads.ungrounded.net/ruffle_wrapper/lib/ac201885e6d7bf4f51cad3e98cd368d6.wasm:wasm-function[4081]:0x3ea7fa)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (https://uploads.ungrounded.net/ruffle_wrapper/lib/ac201885e6d7bf4f51cad3e98cd368d6.wasm:wasm-function[4788]:0x40b75e)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (https://uploads.ungrounded.net/ruffle_wrapper/lib/ac201885e6d7bf4f51cad3e98cd368d6.wasm:wasm-function[5680]:0x41ebb3)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/ac201885e6d7bf4f51cad3e98cd368d6.wasm:wasm-function[5551]:0x41d1f7)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ac201885e6d7bf4f51cad3e98cd368d6.wasm:wasm-function[5682]:0x41ec17)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h4d06e5cc335302b3 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ac201885e6d7bf4f51cad3e98cd368d6.wasm:wasm-function[1501]:0x2d5ae2)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1617493832%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2260692db1a29e8%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-02
Channel: nightly
Built: 2021-04-02T00:48:56.172Z
Commit: bbded906971e98016cd104d47dcd2fa34fd001c2

**Comment by Poopooracoocoo** [comment] 2021-11-29 11:04
Duplicate of #4038

**Closed by Poopooracoocoo** 2021-11-29 11:04 UTC
Labels: duplicate, error-report
