### ISSUE TITLE
Error on https://www.spiele-umsonst.de/electricman-2-t2305.html

### ISSUE THREAD

**Issue by ozgurkoz** [ruffle-rs/ruffle#6863] opened 2022-05-02 12:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
@https://www.spiele-umsonst.de/ruffle/core.ruffle.3d3e163936d5b2fb2d83.js:1:7450
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h9d9f5504bc648392]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h51a70f81ef530383]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h682da277e124560a]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h12b2f0179ff84c92]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hf0d93ec1ac504cf9]@[wasm code]
<?>.wasm-function[core::panicking::panic::h5d6906e2c1099660]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once::h1f29f8ebf1f1a0a0]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h6c8637e3aed40f10]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hdb981699253ce5b7]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::hc19fd6225c223fcf]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::Avm1::run_stack_frame_for_action::h33f324b2d9ea2e35]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::hec7d4d69d10b2195]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h1c801e7ce2c62d83]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h25f97c557909082a]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h417449151b4e504c]@[wasm code]
wasm-stub@[native code]
M@https://www.spiele-umsonst.de/ruffle/core.ruffle.3d3e163936d5b2fb2d83.js:1:3714
c@https://www.spiele-umsonst.de/ruffle/core.ruffle.3d3e163936d5b2fb2d83.js:1:2391
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.spiele-umsonst.de/electricman-2-t2305.html
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-02
Channel: nightly
Built: 2022-04-02T00:18:51.687Z
Commit: e06506c2b901ed6a5298437ee320f1371167cd61
Is extension: false

**Comment by ozgurkoz** [comment] 2022-05-02 12:12
lan amk senin

**Comment by ellieeet123** [comment] 2022-05-03 19:11
likely a duplicate of #4932

**Closed** 2022-05-06 14:26 UTC
Labels: error-report
