### ISSUE TITLE
Error on https://mylabs.px.pearsoned.com/Pegasus/Modules/AssessmentTool/Presentation/frmStudentPresentation.aspx?intAssetID=5000002424217237&mode=test&AssetLinkID=5000000374011340&SelectedDay=&AssetSubTypeID=0&StudyPlanLinkID=0&from=sp&DRTID=5000002424216923&CreateModuleID=0&madd=&IsModule=&dsid=&ViewId=&mmnddal=

### ISSUE THREAD

**Issue by lytle12** [ruffle-rs/ruffle#5217] opened 2021-09-03 21:27 UTC
# Error Info
Error name: TypeError
Error message: WebAssembly.instantiate(): Argument 0 must be a buffer source
Error stack:
```
TypeError: WebAssembly.instantiate(): Argument 0 must be a buffer source
    at <anonymous>:3:32152
    at r (<anonymous>:3:32235)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://mylabs.px.pearsoned.com/Pegasus/Modules/AssessmentTool/Presentation/frmStudentPresentation.aspx?intAssetID=5000002424217237&mode=test&AssetLinkID=5000000374011340&SelectedDay=&AssetSubTypeID=0&StudyPlanLinkID=0&from=sp&DRTID=5000002424216923&CreateModuleID=0&madd=&IsModule=&dsid=&ViewId=&mmnddal=

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by relrelb** [comment] 2021-09-03 21:48
Duplicate of #4232.

**Closed by relrelb** 2021-09-03 21:48 UTC
