### ISSUE TITLE
Error on https://instantlearning.cf/swf.html

### ISSUE THREAD

**Issue by user00000000o** [ruffle-rs/ruffle#7206] opened 2022-06-10 14:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d8409feb7cfa6dd334fd.js:1:7024)
    at std::sync::once::Once::call_once::{{closure}}::hf4bd8358d66e2cc8 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.6.9/bb8b9a8ee86b26f77767.wasm:wasm-function[1184]:0x2aed45)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.6.9/bb8b9a8ee86b26f77767.wasm:wasm-function[1406]:0x2e9d97)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ffe884207fb3c6a (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.6.9/bb8b9a8ee86b26f77767.wasm:wasm-function[4746]:0x4394ed)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.6.9/bb8b9a8ee86b26f77767.wasm:wasm-function[3142]:0x3de058)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.6.9/bb8b9a8ee86b26f77767.wasm:wasm-function[4928]:0x43f54e)
    at core::panicking::panic::hc28e7cc2aa792341 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.6.9/bb8b9a8ee86b26f77767.wasm:wasm-function[4839]:0x43b547)
    at core::ops::function::FnOnce::call_once::h4faf124a219f785d (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.6.9/bb8b9a8ee86b26f77767.wasm:wasm-function[1051]:0x287b38)
    at ruffle_core::avm1::function::Executable::exec::h1e3c90f25dc88eb1 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.6.9/bb8b9a8ee86b26f77767.wasm:wasm-function[358]:0xc9f6a)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h109691e3d62f182b (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.6.9/bb8b9a8ee86b26f77767.wasm:wasm-function[541]:0x1944e1)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://instantlearning.cf/swf.html?notebook=electricman2
SWF URL: https://instantlearning.cf/swffiles/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14695.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.75 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-09
Channel: nightly
Built: 2022-06-09T00:14:19.246Z
Commit: dde21a2a606c479e96b454e9eba54084ae173b85
Is extension: false

**Comment by n0samu** [comment] 2022-06-10 22:15
Duplicate of #4932. (This game doesn't work yet, sorry!)

**Closed by n0samu** 2022-06-10 22:15 UTC
Labels: duplicate, error-report
