### ISSUE TITLE
Cursor always places itself in the left side of input textfields

### ISSUE THREAD

**Issue by delta04** [ruffle-rs/ruffle#3802] opened 2021-03-26 05:51 UTC
When an input text field is selected the cursor places itself on the left side, even if the text field is centered or right aligned. 
And when the text is deleted from the text field the cursor always jumps to the start position - left.
Only when a key is pressed will the cursor find its right position, - left, centered or right, -  which means, that the ruffle code has got it right somewhere along the line.
Would it be possible to change the ruffle code a little, so that the left, center or right alignment works one step earlier, - i.e. at the very moment, when the text field is selected ?
[textalign.zip](https://github.com/ruffle-rs/ruffle/files/6209616/textalign.zip)

**Comment by ousia** [comment] 2021-03-27 11:47
Many thanks for your report, @delta04.

I think it might be a duplicate of #3001.

**Comment by delta04** [comment] 2023-09-08 06:56
I'm not sure if the cursor still places itself on the left side, even if
the textalignment is centered or right, because now the cursor does not
appear when the textfield is selected.
It also disappears when the textfield is emptied using "backspace".
I added a litte cheat-function to the flash-file, to add an empty space " "
to the textfield, when it is emptied. The empty space is removed again,
when you start typing.
I thinks it shows that the problem has something to do with the zero-or
start position of the cursor in the ruffle code.
Please see the attached


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Den ons. 6. sep. 2023 kl. 17.14 skrev Pablo Rodríguez <
***@***.***>:

**Closed** 2024-08-02 15:56 UTC
Labels: text
