### ISSUE TITLE
Error on https://bgs.pages.dev/g/gfiles/gfiles/flash/

### ISSUE THREAD

**Issue by sponserme** [ruffle-rs/ruffle#9223] opened 2023-01-19 20:16 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.3d1c00c72fcfbb2885b0.js:1:5353)
    at std::sync::once::Once::call_once::{{closure}}::h5f93984c1300ca75 (wasm://wasm/0271625a:wasm-function[1568]:0x404867)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/0271625a:wasm-function[1975]:0x495c62)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he904c54109aabe24 (wasm://wasm/0271625a:wasm-function[7083]:0x7404dc)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/0271625a:wasm-function[5006]:0x6a15a5)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/0271625a:wasm-function[7403]:0x74f240)
    at core::option::expect_failed::hb1beef3e49ebedf1 (wasm://wasm/0271625a:wasm-function[8486]:0x7789db)
    at ruffle_core::display_object::stage::Stage::root_clip::hee2f08cf0070ee82 (wasm://wasm/0271625a:wasm-function[5016]:0x6a1e28)
    at ruffle_web::Ruffle::tick::h0417e6aa98969dee (wasm://wasm/0271625a:wasm-function[634]:0x20b040)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h64fd3f678b931ac2 (wasm://wasm/0271625a:wasm-function[8928]:0x788cfb)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://bgs.pages.dev/g/gfiles/gfiles/flash/?swf=nv2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-19
Channel: nightly
Built: 2023-01-19T00:18:19.997Z
Commit: f83c573734f569c08197840aeb0fb2cd3dd78028
Is extension: false

# Metadata
width: 792
height: 600
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1464627

**Comment by n0samu** [comment] 2023-01-20 03:51
Duplicate of #9219

**Closed by n0samu** 2023-01-20 03:51 UTC
Labels: avm2, error-report
