### ISSUE TITLE
Error on https://www.gameflare.com/embed/jacksmith/

### ISSUE THREAD

**Issue by NILDRONGIN** [ruffle-rs/ruffle#14762] opened 2024-01-15 16:11 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096


    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://www.gameflare.com/emulators/ruffle/core.ruffle.e83b1d16dc2d61092e10.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a435d7beef43b50 (wasm://wasm/03633e02:wasm-function[10788]:0xa1bc13)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/03633e02:wasm-function[6606]:0x903b11)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/03633e02:wasm-function[10500]:0xa15778)
    at core::ops::function::Fn::call::ha42a97d062520d10 (wasm://wasm/03633e02:wasm-function[6909]:0x91a821)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::haebbe3d4b91cfc0a (wasm://wasm/03633e02:wasm-function[5446]:0x89b9d7)
    at wgpu::backend::direct::Context::handle_error::hfab23430835c56fe (wasm://wasm/03633e02:wasm-function[2857]:0x6b72ba)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::hdfccc4a85d416fb3 (wasm://wasm/03633e02:wasm-function[9824]:0x9e4ca4)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h4cd6328882b9489a (wasm://wasm/03633e02:wasm-function[9142]:0x9c3221)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::hb9cd0b5744212f19 (wasm://wasm/03633e02:wasm-function[1963]:0x597f17)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Qualcomm, Adreno (TM) 618, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-15
Channel: nightly
Built: 2024-01-15T00:15:42.928Z
Commit: a638715bd87d818d134a70659e7124234b992447
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by n0samu** [comment] 2024-01-16 20:58
Duplicate of #11591

**Closed by n0samu** 2024-01-16 20:58 UTC
Labels: duplicate, error-report
