### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Liitel-Inkling50** [ruffle-rs/ruffle#7263] opened 2022-06-20 01:12 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:831:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:831:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.9df2a83ff6892aaaa9be.js:1:7024)
    at std::sync::once::Once::call_once::{{closure}}::hcb68776b73c9e6d4 (https://uploads.ungrounded.net/ruffle_wrapper/lib/281927c7350b43fd966f.wasm:wasm-function[1157]:0x2a9a0a)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://uploads.ungrounded.net/ruffle_wrapper/lib/281927c7350b43fd966f.wasm:wasm-function[1380]:0x2e533d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h06135d218edbba4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/281927c7350b43fd966f.wasm:wasm-function[4684]:0x42dfd7)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://uploads.ungrounded.net/ruffle_wrapper/lib/281927c7350b43fd966f.wasm:wasm-function[3091]:0x3d2eb0)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://uploads.ungrounded.net/ruffle_wrapper/lib/281927c7350b43fd966f.wasm:wasm-function[4867]:0x4341db)
    at core::panicking::panic::hc28e7cc2aa792341 (https://uploads.ungrounded.net/ruffle_wrapper/lib/281927c7350b43fd966f.wasm:wasm-function[4777]:0x430031)
    at core::ops::function::FnOnce::call_once::h85d65851a30b5f8f (https://uploads.ungrounded.net/ruffle_wrapper/lib/281927c7350b43fd966f.wasm:wasm-function[1029]:0x2875b5)
    at ruffle_core::avm1::function::Executable::exec::haa437e8445b56702 (https://uploads.ungrounded.net/ruffle_wrapper/lib/281927c7350b43fd966f.wasm:wasm-function[363]:0xed9c4)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hb42337eb45e8de67 (https://uploads.ungrounded.net/ruffle_wrapper/lib/281927c7350b43fd966f.wasm:wasm-function[359]:0xe5bd9)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1655649758%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2262afb98b7cd6e%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-19
Channel: nightly
Built: 2022-06-19T00:16:39.698Z
Commit: 754579eb07a9377c6b23df8c9fde77fb018fef34
Is extension: false

**Comment by n0samu** [comment] 2022-06-20 01:18
Duplicate of #3756

**Closed by n0samu** 2022-06-20 01:18 UTC
Labels: duplicate, error-report
