### ISSUE TITLE
Escaping The Prison: Badass Ending: Arrow noise keeps looping

### ISSUE THREAD

**Issue by replaymikey** [ruffle-rs/ruffle#10635] opened 2023-04-10 17:41 UTC
### Describe the bug

Once the green arrows appear on screen, the noise they make loops throughout the game (and if you were to fail at the section the noise would stack)

https://user-images.githubusercontent.com/40784301/230959217-a34a3a8d-8519-4ede-a0e9-0ecd73de9e42.mp4

### Expected behavior

the noise should only play when the arrows are on screen.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Google Chrome Verison 111.0.5563.148

### Additional information

no errors in console.

**Comment by LukeSaward1** [comment] 2023-04-10 19:11
Duplicate of #8067

**Closed** 2023-04-10 20:41 UTC
Labels: bug, duplicate
