### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml (Catch the Petpet)

### ISSUE THREAD

**Issue by IamTechknow** [ruffle-rs/ruffle#11779] opened 2023-06-28 15:24 UTC
Got this when launching a Neopets game called Catch the Petpet in https://www.neopets.com/games/game.phtml?game_id=1034&size=regular&quality=high&play=true

# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:350:26
Error stack:
```
339/__wbg_get_imports/imports.wbg.__wbg_new_d258248ed531ff54@moz-extension://0e9d5cf6-9e36-494f-adaf-0c16bd7f8f3b/dist/339.js:2388:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::h0f1798cf38c8ca4b@:wasm-function[8670]:0x83c74f
std::panicking::rust_panic_with_hook::h85b7f6628c291e12@:wasm-function[5629]:0x76418e
core::panicking::panic_fmt::hf5c4cd929d4aaa9e@:wasm-function[8535]:0x838390
core::panicking::panic::h2f041bf6aa990dfd@:wasm-function[7791]:0x807372
ruffle_core::display_object::movie_clip::MovieClip::preload::h56bd8d8e1113a61f@:wasm-function[644]:0x1f2fbf
ruffle_core::loader::Loader::preload_tick::hc657ebacec278d8e@:wasm-function[1661]:0x47e7fa
ruffle_web::Ruffle::tick::ha4f8f147edd78b74@:wasm-function[737]:0x269b19
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hb86c813e0169578f@:wasm-function[10467]:0x878637
wasm_bindgen::convert::closures::invoke1_mut::h9cfc3780464d44a8@:wasm-function[9277]:0x855345
__wbg_adapter_60@moz-extension://0e9d5cf6-9e36-494f-adaf-0c16bd7f8f3b/dist/339.js:294:10
real@moz-extension://0e9d5cf6-9e36-494f-adaf-0c16bd7f8f3b/dist/339.js:271:20

```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=&sp=0&questionSet=&r=8889764&&width=640&height=500&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-17
Channel: nightly
Built: 2023-06-17T00:19:30.791Z
Commit: 5e6366d14a18994431dc4de1d3665b765371b129
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by Lord-McSweeney** [comment] 2023-06-28 15:47
Duplicate of #9972.

**Closed by Lord-McSweeney** 2023-06-28 15:47 UTC
Labels: error-report
