### ISSUE TITLE
Loading inner SWFs incorrectly overrides background color

### ISSUE THREAD

**Issue by moulins** [ruffle-rs/ruffle#2133] opened 2020-12-28 14:38 UTC
Tested with commit 9e46757 of Ruffle.

The setup:
 - a `main.swf` file, with an orange background color, loads:
 - an `inner.swf` file, with a pink background color.

On Flash, the background color of `inner.swf` is ignored, so we get: 
![flash](https://user-images.githubusercontent.com/10963458/103221257-1843b580-491a-11eb-9fca-8ffd553ec7fe.png)

On Ruffle, the background color of `inner.swf` overrides the original one:
![ruffle](https://user-images.githubusercontent.com/10963458/103221276-27c2fe80-491a-11eb-9652-c7d173c27bc5.png)

Files: 
[loading-bg-color.zip](https://github.com/ruffle-rs/ruffle/files/5747663/loading-bg-color.zip)

**Comment by Txori** [comment] 2020-12-28 15:03
As of now, content from loaded swf tends to overwrite content from parent swf: #2037 
But I didn't know it would also happen with the background color.

**Comment by Toad06** [comment] 2020-12-28 15:57
relrelb suggested a fix for this in https://github.com/ruffle-rs/ruffle/issues/1100#issuecomment-726828908.

**Comment by Herschel** [comment] 2020-12-28 23:27
Dupe of #1100

**Closed by Herschel** 2020-12-28 23:27 UTC
