### ISSUE TITLE
Error on https://vertex-dev-app.wbs.only.sap/vertex-ui/vertextcc.jsp

### ISSUE THREAD

**Issue by somblr10** [ruffle-rs/ruffle#2903] opened 2021-01-27 14:43 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32083
    at r (<anonymous>:3:32573)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://vertex-dev-app.wbs.only.sap/vertex-ui/vertextcc.jsp

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-27
Channel: nightly
Built: 2021-01-27T00:33:31.688Z
Commit: a0159a5efaf9cb29f3d0e5b4a1e1173ad811728a

**Comment by relrelb** [comment] 2021-01-28 14:45
Duplicate of #2201.

**Closed** 2021-02-12 23:49 UTC
