### ISSUE TITLE
Error on https://flashpointproject.github.io/flashpoint-database/search/

### ISSUE THREAD

**Issue by flisan28** [ruffle-rs/ruffle#12794] opened 2023-08-16 12:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9
Error stack:
```
@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.8.16/core.ruffle.bf7826e7fb50abd81c4a.js:1:51562
wasm-stub@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h665574cf5fec7903]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h2d3c5586175098d9]@[wasm code]
<?>.wasm-function[core::panicking::assert_failed_inner::h2fddbed5b9a28a01]@[wasm code]
<?>.wasm-function[core::panicking::assert_failed::h32ed1b6aa6fe7a0b]@[wasm code]
<?>.wasm-function[ruffle_core::avm2::globals::flash::net::net_stream::get_bytes_total::hc2c8e25f942c5982]@[wasm code]
<?>.wasm-function[ruffle_core::avm2::function::Executable::exec::he43152352eaf271c]@[wasm code]
<?>.wasm-function[ruffle_core::avm2::object::TObject::call_method::h347bc732610aeff9]@[wasm code]
<?>.wasm-function[ruffle_core::avm2::object::TObject::get_property::hf957d4ea747cad72]@[wasm code]
<?>.wasm-function[<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::get_property::hf685058c9284c341]@[wasm code]
<?>.wasm-function[ruffle_core::avm2::activation::Activation::run_actions::h7b8351faf31ade1f]@[wasm code]
<?>.wasm-function[ruffle_core::avm2::function::Executable::exec::he43152352eaf271c]@[wasm code]
<?>.wasm-function[<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h7553715e916f9bd0]@[wasm code]
<?>.wasm-function[ruffle_core::avm2::object::TObject::call_property_local::hba7c0009a620f278]@[wasm code]
<?>.wasm-function[ruffle_core::avm2::object::TObject::call_property::h5540107cd25096b5]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h0877f7f48152a2a3]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h97e587a02ffeb386]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h004dca2a2e9e277b]@[wasm code]
S@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.8.16/core.ruffle.bf7826e7fb50abd81c4a.js:1:2811
f@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.8.16/core.ruffle.bf7826e7fb50abd81c4a.js:1:2512
```
AVM2 stack:
```
    at flash.net::NetStream/flash::net::NetStream::bytesTotal()
    at com.hutnu.util::MediaObj/onMetaData()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Apple GPU"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://flashpointproject.github.io/flashpoint-database/search/#9fba8ffc-7b4a-4ada-9905-647cd83b41ad
SWF URL: http://media.svt.se/spel/vintergatan/GameContainer.swf?swfPath=swf/&flvPath=./video/vintergatan/flv/&mp3Path=sound/&xmlPath=xml/

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-16
Channel: nightly
Built: 2023-08-16T00:25:12.644Z
Commit: b1981debc94b1dbe9378a53dae805206af9486da
Is extension: false

# Metadata
width: 1000
height: 580
frameRate: 25
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 310285

**Comment by n0samu** [comment] 2023-08-16 23:41
Duplicate of #12793

**Closed by n0samu** 2023-08-16 23:41 UTC
Labels: duplicate, error-report
