### ISSUE TITLE
Error on https://www.popka.co.il/game-838.html

### ISSUE THREAD

**Issue by 2963823** [ruffle-rs/ruffle#16436] opened 2024-05-24 07:36 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/shader_job.rs:76:26:
Shader property is not an object
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/shader_job.rs:76:26:
Shader property is not an object
    at N.n.wbg.__wbg_new_3a66822ed076951c (https://www.popka.co.il/ruffle/core.ruffle.d7a66e39a50acd53556d.js:1:72830)
    at js_sys::Error::new::he329e38f5ae64355 (wasm://wasm/03914afa:wasm-function[13733]:0xb05b81)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9929706439805e04 (wasm://wasm/03914afa:wasm-function[11349]:0xaaffa7)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/03914afa:wasm-function[6918]:0x96ef85)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/03914afa:wasm-function[11065]:0xaa95b2)
    at core::option::expect_failed::h65a8ce8e046de7db (wasm://wasm/03914afa:wasm-function[9648]:0xa501db)
    at <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next::heca425b3a885522a (wasm://wasm/03914afa:wasm-function[5248]:0x8c51db)
    at ruffle_core::avm2::globals::flash::display::shader_job::get_shader_args::h655d59e0a901f506 (wasm://wasm/03914afa:wasm-function[3382]:0x740fd0)
    at <ruffle_render::filters::Filter as ruffle_core::avm2::filters::FilterAvm2Ext>::from_avm2_object::h039e0b805be71239 (wasm://wasm/03914afa:wasm-function[787]:0x1397ea)
    at ruffle_core::avm2::globals::flash::display::display_object::set_filters::h015b6887af8449a9 (wasm://wasm/03914afa:wasm-function[1967]:0x55ee85)
```
AVM2 stack:
```
    at flash.display::DisplayObject/flash::display::DisplayObject::filters()
    at Main/loadLevelBitmap()
    at Main/openMapArea()
    at Main/handleTownClick()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Plus Graphics (0x00008A52) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: https://www.popka.co.il/files/swfs/838.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.popka.co.il/game-838.html
SWF URL: https://www.popka.co.il/files/swfs/838.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-02-13
Channel: nightly
Built: 2024-02-13T00:15:35.468Z
Commit: 555fcfa9c42ecf180a838bf2c9aca0d97ec45496
Is extension: false

# Metadata
width: 700
height: 600
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 3366039

**Comment by n0samu** [comment] 2024-05-24 07:47
Duplicate of #14540

**Closed by n0samu** 2024-05-24 07:47 UTC
Labels: duplicate, error-report
