### ISSUE TITLE
Error on http://localhost:8095/vertex-ui/vertextcc.jsp

### ISSUE THREAD

**Issue by Bobt1962** [ruffle-rs/ruffle#2720] opened 2021-01-21 16:13 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32083
    at r (<anonymous>:3:32573)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://10.137.16.119:8095/vertex-ui/vertextcc.jsp

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-21
Channel: nightly
Built: 2021-01-21T01:06:17.627Z
Commit: dc2b4fcc42e447097d6432479a122b34fcbc3999

**Comment by relrelb** [comment] 2021-02-12 23:52
Duplicate of #2201.

**Closed by relrelb** 2021-02-12 23:52 UTC
