### ISSUE TITLE
Error on https://flash.riolubruh.repl.co/electricman2.html

### ISSUE THREAD

**Issue by riolubruh** [ruffle-rs/ruffle#5256] opened 2021-09-09 01:44 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://flash.riolubruh.repl.co/ruffle.js:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::h7089835fb571ca66 (https://flash.riolubruh.repl.co/7de4851fa9d355f94591.wasm:wasm-function[955]:0x2718d8)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (https://flash.riolubruh.repl.co/7de4851fa9d355f94591.wasm:wasm-function[1206]:0x2cfe5d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h198e5f9f3cbd4e34 (https://flash.riolubruh.repl.co/7de4851fa9d355f94591.wasm:wasm-function[4148]:0x456180)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (https://flash.riolubruh.repl.co/7de4851fa9d355f94591.wasm:wasm-function[2994]:0x3f1453)
    at rust_begin_unwind (https://flash.riolubruh.repl.co/7de4851fa9d355f94591.wasm:wasm-function[4368]:0x45bd32)
    at core::panicking::panic_fmt::h1fea623755fffed7 (https://flash.riolubruh.repl.co/7de4851fa9d355f94591.wasm:wasm-function[4545]:0x463213)
    at core::panicking::panic::h38cac710b5048ca0 (https://flash.riolubruh.repl.co/7de4851fa9d355f94591.wasm:wasm-function[4303]:0x45928c)
    at core::ops::function::FnOnce::call_once::h9871537d77cb8de7 (https://flash.riolubruh.repl.co/7de4851fa9d355f94591.wasm:wasm-function[932]:0x269087)
    at ruffle_core::avm1::function::Executable::exec::hf11de42d2c7583d7 (https://flash.riolubruh.repl.co/7de4851fa9d355f94591.wasm:wasm-function[390]:0xf5a64)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://flash.riolubruh.repl.co/electricman2.html
SWF URL: https://flash.riolubruh.repl.co/swf/e2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-09-08
Channel: nightly
Built: 2021-09-08T00:21:38.644Z
Commit: e7bff63149bd255620d02358eaa920f05a32386d
Is extension: false

**Comment by relrelb** [comment] 2021-09-09 09:54
Duplicate of #4932.

**Closed by relrelb** 2021-09-09 09:54 UTC
