### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by OmegaSteve777** [ruffle-rs/ruffle#7724] opened 2022-08-21 22:31 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:823:18
Error stack:
```
966/V/e.wbg.__wbg_new_df6e6ab7a65c4c4d@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.b8761a63d4d1c4cf146c.js:1:7361
std::sync::once::Once::call_once::{{closure}}::hcbf386cd48bf2059@:wasm-function[1410]:0x2fc922
std::sync::once::Once::call_inner::h00971925aa1adad3@:wasm-function[1369]:0x2f3b00
core::ops::function::FnOnce::call_once{{vtable.shim}}::h670ec8284b02886c@:wasm-function[4781]:0x43e534
std::panicking::rust_panic_with_hook::h84feca33bd4bd229@:wasm-function[3493]:0x4044ee
core::panicking::panic_fmt::hc171d095bc4a492d@:wasm-function[4960]:0x443ca7
core::panicking::panic::h3b7a8a1eaf47fc0f@:wasm-function[4868]:0x43fd48
core::ops::function::FnOnce::call_once::h400c903770ad5cff@:wasm-function[1018]:0x28fcd6
ruffle_core::avm1::function::Executable::exec::hc3ada98c188e2acb@:wasm-function[352]:0xddb64
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hd62f7b9a7e4ca581@:wasm-function[454]:0x157a4b
ruffle_core::avm1::activation::Activation::run_actions::he3ff8ba6745bc7ed@:wasm-function[288]:0x1b025
ruffle_core::avm1::function::Executable::exec::hc3ada98c188e2acb@:wasm-function[352]:0xdebf2
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::h5ca09a7a5e7c93bb@:wasm-function[715]:0x20d00a
ruffle_core::avm1::activation::Activation::run_actions::he3ff8ba6745bc7ed@:wasm-function[288]:0x1b3a6
ruffle_core::avm1::function::Executable::exec::hc3ada98c188e2acb@:wasm-function[352]:0xdebf2
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::h5ca09a7a5e7c93bb@:wasm-function[715]:0x20d00a
ruffle_core::avm1::activation::Activation::run_actions::he3ff8ba6745bc7ed@:wasm-function[288]:0x1b3a6
ruffle_core::avm1::function::Executable::exec::hc3ada98c188e2acb@:wasm-function[352]:0xdebf2
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hd62f7b9a7e4ca581@:wasm-function[454]:0x157a4b
ruffle_core::avm1::Avm1::run_stack_frame_for_method::h8c6dc51ad3b5ae29@:wasm-function[1775]:0x354f92
ruffle_core::player::Player::run_actions::h1a9b7e0daf4ebddb@:wasm-function[430]:0x13faa2
ruffle_web::Ruffle::tick::h8177dde4acade174@:wasm-function[617]:0x1dde54
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::he19ac82522160dc3@:wasm-function[5824]:0x45d31c
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::he0a71768cc1b13a0@:wasm-function[5324]:0x44e8b7
F@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.b8761a63d4d1c4cf146c.js:1:2905
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.b8761a63d4d1c4cf146c.js:1:2480

```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1660835820%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226302b21533b17%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-18
Channel: nightly
Built: 2022-08-18T00:17:22.879Z
Commit: 1e18fc2227772efb8821891f092ad045088c130d
Is extension: false

**Comment by n0samu** [comment] 2022-08-22 06:46
Duplicate of #3756

**Closed by n0samu** 2022-08-22 06:46 UTC
Labels: duplicate, error-report
