### ISSUE TITLE
Error on https://sexflashgame.org/wp-content/games/harleys-prison-break/index.php

### ISSUE THREAD

**Issue by zxal20** [ruffle-rs/ruffle#8814] opened 2022-12-16 23:17 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://sexflashgame.org/wp-content/ruffle/core.ruffle.2207fcc0c3e0ff1941c8.js:1:7632)
    at std::sync::once::Once::call_once::{{closure}}::he80a94c0f5d51ad9 (https://sexflashgame.org/wp-content/ruffle/edf3a1c87f541166a17c.wasm:wasm-function[991]:0x27d356)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://sexflashgame.org/wp-content/ruffle/edf3a1c87f541166a17c.wasm:wasm-function[1426]:0x2f5927)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hfd41d197921787cc (https://sexflashgame.org/wp-content/ruffle/edf3a1c87f541166a17c.wasm:wasm-function[4827]:0x4463dd)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://sexflashgame.org/wp-content/ruffle/edf3a1c87f541166a17c.wasm:wasm-function[3205]:0x3ecafa)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://sexflashgame.org/wp-content/ruffle/edf3a1c87f541166a17c.wasm:wasm-function[4909]:0x44a078)
    at core::result::unwrap_failed::ha62420c192a556da (https://sexflashgame.org/wp-content/ruffle/edf3a1c87f541166a17c.wasm:wasm-function[4047]:0x42e144)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hc0c63944bfb28d77 (https://sexflashgame.org/wp-content/ruffle/edf3a1c87f541166a17c.wasm:wasm-function[731]:0x20ade9)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::hfd905a521eed9a8c (https://sexflashgame.org/wp-content/ruffle/edf3a1c87f541166a17c.wasm:wasm-function[3230]:0x3ee5dc)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::hf5a51b9aaa7a0969 (https://sexflashgame.org/wp-content/ruffle/edf3a1c87f541166a17c.wasm:wasm-function[2479]:0x3a8510)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://sexflashgame.org/wp-content/games/harleys-prison-break/index.php
SWF URL: https://sexflashgame.org/wp-content/games/harleys-prison-break/harleys-prison-break.swf.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 11; Redmi Note 9S) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-18
Channel: nightly
Built: 2022-05-18T00:14:23.914Z
Commit: 135833e4000168efe291bca926f718eedc0069bb
Is extension: false

**Comment by n0samu** [comment] 2022-12-17 04:42
Duplicate of #8705

**Closed by n0samu** 2022-12-17 04:42 UTC
Labels: duplicate, nsfw, error-report
