### ISSUE TITLE
Error on https://ellieeet123.github.io/games/

### ISSUE THREAD

**Issue by Arandomkid7** [ruffle-rs/ruffle#6644] opened 2022-04-07 17:34 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ellieeet123.github.io/ruffle/core.ruffle.25973f3ed2b17396c464.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (https://ellieeet123.github.io/ruffle/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1016]:0x2f3fd8)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (https://ellieeet123.github.io/ruffle/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1152]:0x3276ac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (https://ellieeet123.github.io/ruffle/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4725]:0x4d3db3)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (https://ellieeet123.github.io/ruffle/b2fc0abe3dbbf4e736aa.wasm:wasm-function[3192]:0x47f3dc)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (https://ellieeet123.github.io/ruffle/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4996]:0x4df9ff)
    at core::panicking::panic::h35778e3c18266c93 (https://ellieeet123.github.io/ruffle/b2fc0abe3dbbf4e736aa.wasm:wasm-function[4722]:0x4d38da)
    at core::ops::function::FnOnce::call_once::h63635e87c343a6bd (https://ellieeet123.github.io/ruffle/b2fc0abe3dbbf4e736aa.wasm:wasm-function[1053]:0x30a68b)
    at ruffle_core::avm1::function::Executable::exec::h01bdca74588653f1 (https://ellieeet123.github.io/ruffle/b2fc0abe3dbbf4e736aa.wasm:wasm-function[395]:0x145b12)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hd2ac2ca7aecc5e6d (https://ellieeet123.github.io/ruffle/b2fc0abe3dbbf4e736aa.wasm:wasm-function[381]:0x10b308)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ellieeet123.github.io/games/
SWF URL: https://raw.githubusercontent.com/ellieeet123/swf/main/swf/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14092.77.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.107 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-03
Channel: nightly
Built: 2022-02-03T00:19:02.660Z
Commit: 0152a6aa344927cc8290b090ac2d3b4db4ecd1fc
Is extension: false

**Comment by relrelb** [comment] 2022-04-08 06:53
Duplicate of #4932.

**Closed by relrelb** 2022-04-08 06:53 UTC
Labels: error-report
