### ISSUE TITLE
Error on https://kdata1.com/games/SSF9_2011/

### ISSUE THREAD

**Issue by elayraqhamza** [ruffle-rs/ruffle#12195] opened 2023-07-20 20:25 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
339/__wbg_get_imports/imports.wbg.__wbg_new_d258248ed531ff54@moz-extension://c8cee65b-5bd3-4b46-b2f1-f9d9eb851140/dist/339.js:2403:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ef40e3717251c02@:wasm-function[9019]:0x8c170c
std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d@:wasm-function[5897]:0x7c3e36
core::panicking::panic_fmt::h8a19fa1eb63fbb67@:wasm-function[8864]:0x8bcc29
core::panicking::panic::h42080e1e32ba4b73@:wasm-function[8506]:0x8aced0
ruffle_core::display_object::movie_clip::MovieClip::preload::h0b9f96de5a57a809@:wasm-function[656]:0x1dc2d8
ruffle_core::loader::Loader::preload_tick::h6200c892b8d58bc9@:wasm-function[1636]:0x4672dc
ruffle_web::Ruffle::tick::hb0c11c442422f4f4@:wasm-function[747]:0x24f236
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h3d1e4510e6b9c799@:wasm-function[10789]:0x9005ad
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hceb40709914c01ae@:wasm-function[9652]:0x8de48e
__wbg_adapter_60@moz-extension://c8cee65b-5bd3-4b46-b2f1-f9d9eb851140/dist/339.js:294:10
real@moz-extension://c8cee65b-5bd3-4b46-b2f1-f9d9eb851140/dist/339.js:271:20

```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: game.swf
Param movie: game.swf
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://kdata1.com/games/SSF9_2011/
SWF URL: https://kdata1.com/games/SSF9_2011/game.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0 
Name: nightly 2023-07-15
Channel: nightly
Built: 2023-07-15T00:22:32.222Z
Commit: ee7412d73396824392f6a08bbd4f9276c013cba5
Is extension: true

# Metadata
width: 800
height: 800
frameRate: 25
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 10342

**Comment by n0samu** [comment] 2023-07-20 21:52
Duplicate of #10505

**Closed by n0samu** 2023-07-20 21:52 UTC
Labels: duplicate, error-report
