### ISSUE TITLE
Text shown in SWF is not in the right place and cut off, and text shown when hovering is inaccurate too

### ISSUE THREAD

**Issue by danielhjacobs** [ruffle-rs/ruffle#3156] opened 2021-02-08 09:42 UTC
**Describe the bug**

This is a visual bug and a bit hard to explain. The bug can be seen in action when using the browser extension here:

_(Note: not reproducible anymore, see below for a SWF)_
HTML Page: http://www.dnai.org/timeline/index.html
SWF File: http://www.dnai.org/timeline/timeline_header.swf

**Expected behavior**

The problem is a bit hard to explain, so I have an image that explains it better than I can:
![ruffle_header_differences](https://user-images.githubusercontent.com/29206584/107202000-adc96f00-69c7-11eb-9c91-d09d7452c55c.png)

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

It applies to the extension and demo, and based on testing on my test server, also to the self-hosted version. Since it's a rendering/formatting issue, it seems to apply to every version

**What platform are you using?**

 I am using a Windows 10 computer, and tested both Chrome and Firefox

**Comment by craniumcadoo** [comment] 2021-02-11 08:19
I see there is a pull request out that would fix part of the issue, but that the author of said pull request said they don't fully understand the rest of the issue.

I doubted having more SWF files that are almost exactly the same and all have the exact same error on hover would help identify the other issue, which is why I did not include those files initially since I thought it would be redundant. but in case it helps, the following all have the exact same issue:

* http://www.dnai.org/a/ - http://www.dnai.org/a/header_mc1.swf
* http://www.dnai.org/b/ - http://www.dnai.org/b/header_mc2.swf
* http://www.dnai.org/c/ - http://www.dnai.org/c/header_mc3.swf
* http://www.dnai.org/d/ - http://www.dnai.org/d/header_mc4.swf
* http://www.dnai.org/e/ - http://www.dnai.org/e/header_mc5.swf

**Comment by craniumcadoo** [comment] 2021-02-11 08:45
Further testing:

http://www.dnai.org/timeline/, http://www.dnai.org/c/, and http://www.dnai.org/e/ - Upon moving the mouse to hover over (4), then (5), then back to (4), then ... repeatedly, the text just keeps moving further right, until it is eventually offscreen completely. 

The same applies to http://www.dnai.org/a/, however for that one, more often than not, the text starts so far to the right that it is already offscreen initially.

http://www.dnai.org/b/, http://www.dnai.org/d/ - In these two files, the same action moves the text to the left until  it is offscreen.

**Comment by craniumcadoo** [comment] 2021-02-14 04:28
Since 26ffbdfe23851ed9c7a835589a09833f75813d12 was committed, the issue is a lot less problematic. The text is still not in the right place sometimes, but its position is a lot more consistent and close to where it's meant to be. It no longer jumps around. Check the swfs/pages to see the issue in action now.

**Comment by danielhjacobs** [comment] 2021-03-02 17:24
I don't know whether to close this or not, so I'm leaving it open and I'll let someone with the authority to close issues decide whether to close it. It was not fixed. However, since it did not seem to be progressing, we updated those animations, so the issue is no longer visible by viewing them.

**Comment by n0samu** [comment] 2023-06-21 03:26
I think this is an instance of #10660

**Closed** 2024-11-15 16:41 UTC
Labels: bug, text
