### ISSUE TITLE
Error on https://evilgames.eu/flashgames/tails-nightmare.htm

### ISSUE THREAD

**Issue by nik312123** [ruffle-rs/ruffle#3164] opened 2021-02-08 23:12 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32083
    at r (<anonymous>:3:32573)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: ../swf/tails-nightmare.swf
Param wmode: direct
Param quality: high
Param allowNetworking: internal
Param AllowScriptAccess: never
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://evilgames.eu/flashgames/tails-nightmare.htm

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-21
Channel: nightly
Built: 2021-01-21T01:06:17.627Z
Commit: dc2b4fcc42e447097d6432479a122b34fcbc3999

**Comment by relrelb** [comment] 2021-02-12 23:49
Duplicate of #2201.

**Closed by relrelb** 2021-02-12 23:49 UTC
