### ISSUE TITLE
Error on https://www.comdotgame.com/play/how-to-discipline-a-shoplifting-girl-english

### ISSUE THREAD

**Issue by birdman6521** [ruffle-rs/ruffle#9069] opened 2023-01-08 13:09 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/cmp.rs:869:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/cmp.rs:869:9
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://echo.comdotgame.com/ruffle/core.ruffle.da135b622b824b611fe9.js:1:6974)
    at std::sync::once::Once::call_once::{{closure}}::hcd46b3a2543691b9 (wasm://wasm/01919246:wasm-function[927]:0x26cae0)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/01919246:wasm-function[1403]:0x319a4c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb7a03847d0b7780a (wasm://wasm/01919246:wasm-function[4992]:0x4bd53a)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/01919246:wasm-function[3769]:0x47c2fa)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/01919246:wasm-function[5233]:0x4c2369)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/01919246:wasm-function[5047]:0x4be4b5)
    at ruffle_core::player::Player::update_drag::h3b82de7de88e95e5 (wasm://wasm/01919246:wasm-function[1506]:0x3363f0)
    at ruffle_core::player::Player::handle_event::h67a0dcfc0425a08f (wasm://wasm/01919246:wasm-function[326]:0x92e2b)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hadcfa7fd1304c7f0 (wasm://wasm/01919246:wasm-function[1220]:0x2d699f)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/70013404b08967ba2c8d5f70b0d4a1d3.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Param base: https://echo.comdotgame.com/4x90xhl3k0/games/files/how-to-discipline-a-shoplifting-girl-english/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/how-to-discipline-a-shoplifting-girl-english
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/70013404b08967ba2c8d5f70b0d4a1d3.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile DuckDuckGo/5 Safari/537.36
Platform: Linux armv8l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-07
Channel: nightly
Built: 2022-12-07T00:18:07.185Z
Commit: 2bb4e2e549ab39d2f2cb7d8194ac21bb1ca2e682
Is extension: false

# Metadata
width: 600
height: 600
frameRate: 24
numFrames: 124
swfVersion: 10
backgroundColor: #999999
isActionScript3: true
uncompressedLength: 18499220

**Comment by Lord-McSweeney** [comment] 2023-01-08 15:34
Duplicate of #8916.

**Closed** 2023-01-09 08:32 UTC
Labels: duplicate, nsfw, error-report
