### ISSUE TITLE
Error on chrome-extension://cnagbmhbgbegippbcpepimihedfnebpm/player.html

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#7797] opened 2022-08-29 14:09 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://cnagbmhbgbegippbcpepimihedfnebpm/dist/966.js:1:5538)
    at std::sync::once::Once::call_once::{{closure}}::h56e11cc0c0ce9fb5 (wasm://wasm/0167931e:wasm-function[1399]:0x2f6ea7)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/0167931e:wasm-function[1356]:0x2ed714)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hadbf8162df7b3024 (wasm://wasm/0167931e:wasm-function[4745]:0x43779e)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/0167931e:wasm-function[3464]:0x3fe63c)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/0167931e:wasm-function[4925]:0x43d06b)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/0167931e:wasm-function[4835]:0x439087)
    at core::ops::function::FnOnce::call_once::h9cc9721234e980fe (wasm://wasm/0167931e:wasm-function[1002]:0x27f96c)
    at ruffle_core::avm1::function::Executable::exec::h6e75598bf7d6c546 (wasm://wasm/0167931e:wasm-function[354]:0xef53c)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h4700a540beb36b1d (wasm://wasm/0167931e:wasm-function[785]:0x222c65)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://cnagbmhbgbegippbcpepimihedfnebpm/player.html?url=http%3A%2F%2Fi.notdoppler.com%2Ffiles%2Felectricman2.swf
SWF URL: http://i.notdoppler.com/files/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-12
Channel: nightly
Built: 2022-08-12T00:15:03.560Z
Commit: 9d1f27484b8f8b72f1fc499aca57aeed9fd920b6
Is extension: true

**Comment by n0samu** [comment] 2022-08-29 18:25
Duplicate of #4932

**Closed by n0samu** 2022-08-29 18:25 UTC
Labels: duplicate, error-report
