### ISSUE TITLE
Crash on papascheeseria_102.swf

### ISSUE THREAD

**Issue by MapleRiddle** [ruffle-rs/ruffle#18312] opened 2024-10-18 17:26 UTC
### Describe what you were doing

Playing a Papa Louie game and want to save a back up just in case. I have several backups from the browser demo, but when I try to create one from the desktop application no file is shown (created?) and the app crashes. However progress isn't lost, I can still play from my last save point. My most recent backup file are levels behind so if anything crashes more severely I'd have to start over from there.

### What does the crash message say?

panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-app-kit-0.2.2/src/generated/NSSavePanel.rs:83:1:
unexpected NULL returned from +[NSSavePanel savePanel]

### Ruffle Version

0.1.0-nightly (5faa313a70d6ad47af18ad4b2f6517696118ef07 2024-10-17)

### Affected platform

Desktop app

### Operating system

Mac OS 13.0.1 [64-bit]

### Additional information

Filename: papascheeseria_102.swf

### AVM2 Callstack
```
	at flash.net::FileReference/flash::net::FileReference::save()
	at _-8I::_-8X/_-W()
	at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
	at _-6T::_-Y/_-65()
```

### Render Info
Renderer: wgpu
Adapter Backend: Metal
Adapter Name: "Intel(R) Iris(TM) Plus Graphics"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH_CLIP_CONTROL | DEPTH32FLOAT_STENCIL8 | INDIRECT_FIRST_INSTANCE | SHADER_F16 | RG11B10UFLOAT_RENDERABLE | BGRA8UNORM_STORAGE | TEXTURE_FORMAT_16BIT_NORM | MAPPABLE_PRIMARY_BUFFERS | TEXTURE_BINDING_ARRAY | STORAGE_RESOURCE_BINDING_ARRAY | SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING | UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING | MULTI_DRAW_INDIRECT | PUSH_CONSTANTS | ADDRESS_MODE_CLAMP_TO_ZERO | ADDRESS_MODE_CLAMP_TO_BORDER | POLYGON_MODE_LINE | VERTEX_WRITABLE_STORAGE | CLEAR_TEXTURE | SHADER_PRIMITIVE_INDEX | DUAL_SOURCE_BLENDING | SHADER_INT64 | SUBGROUP | SUBGROUP_BARRIER)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 2147483648, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: low
Surface samples: 1
Surface size: (1600, 1200, 1)

**Comment by n0samu** [comment] 2024-10-18 20:08
Duplicate of #17844

**Closed by n0samu** 2024-10-18 20:08 UTC
Labels: bug, duplicate, panic, macos
