### ISSUE TITLE
False sitelock on Animator vs Animation the game

### ISSUE THREAD

**Issue by A-UNUSED-ACCOUNT** [ruffle-rs/ruffle#988] opened 2020-08-07 02:02 UTC
Causes the stolen from atom.com error in ruffle but not in native

https://raw.githack.com/tsukisuperior/flash-games/master/Animator-Vs-Animation-Special-Edition.swf

**Comment by kmeisthax** [comment] 2020-08-07 02:19
Animator vs Animation appears to implement sitelocking by way of calling `new LocalConnection().domain()`. Looking at the AS2 specs, this appears to be the domain portion of `_url`, so we could at least stub this.

`LocalConnection` itself appears to be a Flash-specific version of `Window.postMessage`, which means we could at least theoretically emulate it in scenarios where the communicating SWFs have a frame relationship with one another. However, I'm not sure if that's entirely useful as this was intended to allow far broader cross-window communication than HTML standards ordinarily allowed.

It also appears to load a cross-domain policy file for a site that appears to no longer exist. If it did exist, we still wouldn't be able to emulate whatever connectivity functions it was attempting to use unless that website also happened to support CORS requests.

**Comment by tsukisuperior** [comment] 2020-08-07 02:51
ok thank you
the swf was modified

**Comment by n0samu** [comment] 2022-09-11 02:41
Fixed by #6806. Tested here: https://kbhgames.com/game/animator-vs-animation-se. (KBHGames is one of the allowed domains)

**Closed by n0samu** 2022-09-11 02:41 UTC
Labels: avm1
