### ISSUE TITLE
Error on https://sexflashgame.org/wp-content/games/harleys-prison-break/index.php

### ISSUE THREAD

**Issue by iStayMute** [ruffle-rs/ruffle#8707] opened 2022-12-06 07:50 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: UnableToCreateVAO', render/webgl/src/lib.rs:583:23
Error stack:
```
966/D/n.wbg.__wbg_new_f9bb493369a83c12@moz-extension://64f2a22e-033c-4bbe-9956-69afa8dfd4e8/dist/966.js:1:6972
std::sync::once::Once::call_once::{{closure}}::hcd46b3a2543691b9@:wasm-function[926]:0x26c33e
std::sync::once::Once::call_inner::h34aee843864daceb@:wasm-function[1396]:0x316459
core::ops::function::FnOnce::call_once{{vtable.shim}}::hb7a03847d0b7780a@:wasm-function[4991]:0x4b93e7
std::panicking::rust_panic_with_hook::h70a0e195f4db2a29@:wasm-function[3769]:0x477891
core::panicking::panic_fmt::h751be80779d42b53@:wasm-function[5232]:0x4be244
core::result::unwrap_failed::h2dc706d948c22960@:wasm-function[4304]:0x49d38f
ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h39481cf67e911f67@:wasm-function[635]:0x1e4016
<ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::hb1e159725a79a649@:wasm-function[3567]:0x469732
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h62a123c0ad5f2252@:wasm-function[2662]:0x41320a
ruffle_core::display_object::render_base::hf0ac98f76d14b508@:wasm-function[1274]:0x2f3173
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::had095be16a786686@:wasm-function[3969]:0x48b9e3
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h62a123c0ad5f2252@:wasm-function[2662]:0x41348e
ruffle_core::display_object::render_base::hf0ac98f76d14b508@:wasm-function[1274]:0x2f3173
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::had095be16a786686@:wasm-function[3969]:0x48b9f1
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h62a123c0ad5f2252@:wasm-function[2662]:0x41340d
ruffle_core::display_object::render_base::hf0ac98f76d14b508@:wasm-function[1274]:0x2f3173
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::had095be16a786686@:wasm-function[3969]:0x48b9f1
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h62a123c0ad5f2252@:wasm-function[2662]:0x41340d
ruffle_core::display_object::render_base::hf0ac98f76d14b508@:wasm-function[1274]:0x2f3173
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::had095be16a786686@:wasm-function[3969]:0x48b9f1
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h62a123c0ad5f2252@:wasm-function[2662]:0x41340d
ruffle_core::display_object::render_base::hf0ac98f76d14b508@:wasm-function[1274]:0x2f3173
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::had095be16a786686@:wasm-function[3969]:0x48b9f1
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h62a123c0ad5f2252@:wasm-function[2662]:0x41340d
ruffle_core::display_object::render_base::hf0ac98f76d14b508@:wasm-function[1274]:0x2f3173
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::had095be16a786686@:wasm-function[3969]:0x48b9f1
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h62a123c0ad5f2252@:wasm-function[2662]:0x411ad7
ruffle_core::display_object::render_base::hf0ac98f76d14b508@:wasm-function[1274]:0x2f3173
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::render::ha26a360a522643e6@:wasm-function[1116]:0x2a906c
ruffle_web::Ruffle::tick::ha75571213826a268@:wasm-function[644]:0x1eb88a
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h2f891ef58527c159@:wasm-function[6159]:0x4d9ea4
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha5bbdaf30b9327e7@:wasm-function[5597]:0x4c7fea
S@moz-extension://64f2a22e-033c-4bbe-9956-69afa8dfd4e8/dist/966.js:1:2576
c@moz-extension://64f2a22e-033c-4bbe-9956-69afa8dfd4e8/dist/966.js:1:2253

```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://sexflashgame.org/wp-content/games/harleys-prison-break/index.php
SWF URL: https://sexflashgame.org/wp-content/games/harleys-prison-break/harleys-prison-break.swf.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-06
Channel: nightly
Built: 2022-12-06T00:15:51.215Z
Commit: 7b64fcf5fa9890084c8f0947953fd4245b57742c
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 2308

**Comment by n0samu** [comment] 2022-12-06 07:51
Duplicate of #8705

**Closed by n0samu** 2022-12-06 07:51 UTC
Labels: duplicate, nsfw, error-report
