### ISSUE TITLE
Error on https://www.gameflare.com/embed/chibi-knight/

### ISSUE THREAD

**Issue by awet14** [ruffle-rs/ruffle#5643] opened 2021-11-11 17:57 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.gameflare.com/emulators/ruffle/ruffle.js?id=da8d984f7e8e19a42727:1:6803)
    at std::sync::once::Once::call_once::{{closure}}::hbc3e76004faf5843 (https://www.gameflare.com/emulators/ruffle/da8d984f7e8e19a42727.wasm:wasm-function[1029]:0x2ca3e6)
    at std::sync::once::Once::call_inner::hc44ad7f626385660 (https://www.gameflare.com/emulators/ruffle/da8d984f7e8e19a42727.wasm:wasm-function[1292]:0x327a8c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h23da166c23bc7e1a (https://www.gameflare.com/emulators/ruffle/da8d984f7e8e19a42727.wasm:wasm-function[4385]:0x4bde7b)
    at std::panicking::rust_panic_with_hook::he9bfe03219d715ba (https://www.gameflare.com/emulators/ruffle/da8d984f7e8e19a42727.wasm:wasm-function[3224]:0x456fe3)
    at rust_begin_unwind (https://www.gameflare.com/emulators/ruffle/da8d984f7e8e19a42727.wasm:wasm-function[4617]:0x4c3f45)
    at core::panicking::panic_fmt::hbf21a3d4bbb82bf8 (https://www.gameflare.com/emulators/ruffle/da8d984f7e8e19a42727.wasm:wasm-function[4811]:0x4cb653)
    at core::panicking::panic::h2fd385a887c8bf13 (https://www.gameflare.com/emulators/ruffle/da8d984f7e8e19a42727.wasm:wasm-function[4550]:0x4c1230)
    at core::ops::function::FnOnce::call_once::h8686fa0177bbb676 (https://www.gameflare.com/emulators/ruffle/da8d984f7e8e19a42727.wasm:wasm-function[1006]:0x2c15da)
    at ruffle_core::avm1::function::Executable::exec::h67427effb9e1e718 (https://www.gameflare.com/emulators/ruffle/da8d984f7e8e19a42727.wasm:wasm-function[425]:0x1294be)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/chibi-knight/
SWF URL: https://data.gameflare.com/games/6255/H8me4QU2dF0alM.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 Edg/95.0.1020.40
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-13
Channel: nightly
Built: 2021-10-13T00:10:34.426Z
Commit: c0021204c6956ba61e869db3dfd2d9dadbe0bcd0
Is extension: false

**Comment by Poopooracoocoo** [comment] 2021-11-11 18:27
Duplicate of #3756

**Closed by Poopooracoocoo** 2021-11-11 18:27 UTC
Labels: error-report
