### ISSUE TITLE
Papa Louie 2 & 3: Freeze and high memory usage

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9736] opened 2023-02-26 03:19 UTC
### Describe the bug

When trying to play [Papa Louie 2](https://www.flipline.com/games/papalouie2/index.html) and [Papa Louie 3](https://www.flipline.com/games/papalouie3/index.html), the games freeze on the "Loading levels" screen:
![image](https://user-images.githubusercontent.com/71368227/221390400-5da353de-cd95-4677-be45-bdea875cdb59.png)

Ruffle's memory usage skyrockets, and then it crashes.

### Expected behavior

At the very least, we should try to fix the memory issue. Maybe by implementing #8416?

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox 110

**Comment by MartySVK** [comment] 2023-02-26 08:36
Same probably for Cactus McCoy and Cactus McCoy 2

**Comment by CreaZyp154** [comment] 2023-05-31 19:43
In the devtools it shows this (tested with Papa Louie 2): 
```js
Uncaught RuntimeError: unreachable executed
    __wbg_adapter_64 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:294
    real moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:271
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1340
    handleError moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:309
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1339
    __wbg_adapter_64 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:294
    real moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:271
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1340
    handleError moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:309
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1339
    __wbg_adapter_64 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:294
    real moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:271
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1340
    handleError moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:309
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1339
    __wbg_adapter_64 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:294
    real moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:271
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1340
    handleError moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:309
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1339
    __wbg_adapter_64 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:294
    real moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:271
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1340
    handleError moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:309
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1339
    __wbg_adapter_64 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:294
    real moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:271
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1340
    handleError moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:309
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1339
    __wbg_adapter_64 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:294
    real moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:271
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1340
    handleError moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:309
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1339
    __wbg_adapter_64 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:294
    real moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:271
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1340
    handleError moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:309
    __wbg_requestAnimationFrame_d28701d8e57998d1 moz-extension://58f0dc8b-0eca-495d-ae4d-43543be8493e/dist/339.js:1339
```
followed by a bunch of `Unable to lock Ruffle core` errors. On chromium (Edge) it crashes after a while with `SBOX_FATAL_MEMORY_EXCEEDED`
On desktop it takes a while to load and uses all available memory (at least it looks like it), and at about 2 third in it crashed with error `memory allocation of 1570888 bytes failed`

**Comment by MartySVK** [comment] 2023-07-31 20:51
Added nosamu's comment from discord, maybe it will help later

```
if it's not dependent strings, it could maybe just be something about loading such a gigantic XML from a string in general
the game works in a super weird way, where its level data is stored in a bitmap image where each pixel color corresponds to an ascii character
and so it getPixels in a loop to build a huge string and then constructs an XML from it
I expect that the problem is in that loop though, maybe each time the game adds a letter to the string, the old version of the string is also kept around in memory
```

**Comment by illerokcob** [comment] 2023-11-24 19:05
Indeed, I've confirmed @n0samu's theory. After patching the swf file's bytecode and removing this getPixel loop and hardcoding the whole xml as a string into the code, the game will load without freezing. Still, there's an issue somewhere with the GC because this shouldn't happen.
However, memory usage is still high (~700-800 MB while playing on a level) compared to the original flash player's relatively low memory footprint (max. 300 MB on a level), and CPU usage is quite high on a midrange hardware. Anyway, probably these are not game specific things.

**Comment by MartySVK** [comment] 2024-05-27 08:58
fixed by https://github.com/ruffle-rs/ruffle/pull/16308

**Closed** 2024-05-29 05:42 UTC
Labels: bug, avm2
