### ISSUE TITLE
Error on https://web.archive.org/web/20060703064119/http://www.outrun2006.com/en/index.html

### ISSUE THREAD

**Issue by TheMidnightSnack** [ruffle-rs/ruffle#4219] opened 2021-05-03 11:24 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch
    at <anonymous>:3:16304
    at Function.apply (https://web.archive.org/_static/js/wombat.js?v=cRqOKCOw:21:58614)
    at <anonymous>:3:4543
    at web_sys::features::gen_Response::Response::array_buffer::h8a5ee0104e321171 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4452]:0x35610a)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h19b5f0e1e7ddee24 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[671]:0x19ea69)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdc6b19a73e3641bc (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[530]:0x157ee2)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h40e37f08dfd85701 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1748]:0x29fc0d)
    at wasm_bindgen_futures::task::singlethread::Task::run::h77783617ec01e4f4 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3097]:0x320dff)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h802303e3f3bfcb39 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[2809]:0x30d1bf)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h82a10ca5ab1cea38 (chrome-extension://hnicgckkbamlonjfbkdilljeegpbjabo/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4841]:0x35ae27))', web/src/navigator.rs:201:18

# Player Info
Allows script access: false

# Page Info
Page URL: https://web.archive.org/web/20060703064119/http://www.outrun2006.com/en/index.html
SWF URL: http://www.outrun2006.com/OR2006_main.swf?language=en

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by adrian17** [comment] 2021-05-17 22:06
It's very likely this was already fixed in newer version of Ruffle.
In fact, it's possible that this was already fixed by the time you posted this report - the issue is that the extension you used didn't use an up to date version of Ruffle. In fact, not only that extension isn't endorsed by us, it was recently removed from Chrome for being malware. With that in mind, I'd recommend trying a newer official version of Ruffle instead.

**Closed by adrian17** 2021-05-17 22:06 UTC
