### ISSUE TITLE
Error on chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/player.html

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#5270] opened 2021-09-10 05:29 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/dist/player.js:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::h8abebda14d1aaa35 (chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/dist/f68c9bc95bf377554b04.wasm:wasm-function[951]:0x2665ca)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/dist/f68c9bc95bf377554b04.wasm:wasm-function[1203]:0x2c3839)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he4589c2a93c6a647 (chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/dist/f68c9bc95bf377554b04.wasm:wasm-function[4160]:0x455261)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/dist/f68c9bc95bf377554b04.wasm:wasm-function[2986]:0x3e6c61)
    at rust_begin_unwind (chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/dist/f68c9bc95bf377554b04.wasm:wasm-function[4380]:0x45ae25)
    at core::panicking::panic_fmt::h1fea623755fffed7 (chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/dist/f68c9bc95bf377554b04.wasm:wasm-function[4556]:0x46229e)
    at core::panicking::panic::h38cac710b5048ca0 (chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/dist/f68c9bc95bf377554b04.wasm:wasm-function[4316]:0x4583be)
    at core::ops::function::FnOnce::call_once::hd98defe2b00ec2f0 (chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/dist/f68c9bc95bf377554b04.wasm:wasm-function[928]:0x25d949)
    at ruffle_core::avm1::function::Executable::exec::h6c71aa42e4096714 (chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/dist/f68c9bc95bf377554b04.wasm:wasm-function[389]:0xf310d)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://ggiacipfblbhpijccocjgghaaefijjom/player.html?url=http://farm.stickpage.com/electricman2game.swf
SWF URL: http://farm.stickpage.com/electricman2game.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-09-07
Channel: nightly
Built: 2021-09-07T00:13:42.794Z
Commit: b90436cffe3499acb42c5a41856002ddd1dc7024
Is extension: true

**Comment by relrelb** [comment] 2021-09-15 14:55
Duplicate of #4932.

**Closed by relrelb** 2021-09-15 14:55 UTC
