### ISSUE TITLE
[SUGGESTION] Implement disabling Action Script 3

### ISSUE THREAD

**Issue by nagayev** [ruffle-rs/ruffle#2033] opened 2020-12-19 08:27 UTC
Hello.
The support of ActionScript is at a very low level.
So maybe it's a good idea to add option to disable support of AS3?
And if user visit website with content using AS3 user will see screen with the text:
"Sorry, We don't support AS3 now"

**Comment by Herschel** [comment] 2020-12-19 08:32
Duplicate of #1978

**Closed by Herschel** 2020-12-19 08:32 UTC

**Comment by nagayev** [comment] 2020-12-19 08:41
@Herschel Sorry.

**Comment by Herschel** [comment] 2020-12-19 10:15
@nagayev No worries :-)
