### ISSUE TITLE
Error on https://images-opensocial.googleusercontent.com/gadgets/ifr

### ISSUE THREAD

**Issue by wafflezzzzz** [ruffle-rs/ruffle#11760] opened 2023-06-27 07:20 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu-hal/src/gles/device.rs:722:52
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu-hal/src/gles/device.rs:722:52
    at W.n.wbg.__wbg_new_15d3966e9981a196 (https://cdn.jsdelivr.net/gh/h3sj7v2f6k/ruffleswf@c51c3d65132f30d9ef0e571832ade4445b2d6606/core.ruffle.3f25a242b7e474a088e3.js:1:46443)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0f330faf47f8cac8 (wasm://wasm/0295bba2:wasm-function[7830]:0x7cb3fc)
    at std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8 (wasm://wasm/0295bba2:wasm-function[5304]:0x712d4e)
    at core::panicking::panic_fmt::h2a7f454a5f5da218 (wasm://wasm/0295bba2:wasm-function[7727]:0x7c6ccf)
    at core::result::unwrap_failed::h6072dd9795ba6508 (wasm://wasm/0295bba2:wasm-function[6027]:0x749da4)
    at <T as wgpu::context::DynContext>::device_create_texture::h120b62ad1e0fb784 (wasm://wasm/0295bba2:wasm-function[5841]:0x73977d)
    at wgpu::Device::create_texture::h38fdca8b79047a6f (wasm://wasm/0295bba2:wasm-function[4091]:0x6a3917)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::h463392d0d88fe8c3 (wasm://wasm/0295bba2:wasm-function[1300]:0x3bcbb2)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::ha991464b6467b5cd (wasm://wasm/0295bba2:wasm-function[1225]:0x39a3fc)
    at ruffle_core::bitmap::bitmap_data::BitmapData::update_dirty_texture::h2ea5b972ade740de (wasm://wasm/0295bba2:wasm-function[1229]:0x39b832)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at swordGame.models::Soldier/spriteSheetBlit()
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/h3sj7v2f6k/jd832xj4la@e26125944fdda12a2497f0fd66b4dc3fa572b0ac/Jacksmith/jacksmith.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://s3.amazonaws.com/production-assetsbucket-8ljvyr1xczmb/1ee20621-61bc-4ec8-a8ec-5e839c2e6edc%2Fjacksmith.xml
SWF URL: https://cdn.jsdelivr.net/gh/h3sj7v2f6k/jd832xj4la@e26125944fdda12a2497f0fd66b4dc3fa572b0ac/Jacksmith/jacksmith.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-10
Channel: nightly
Built: 2023-03-10T00:19:23.354Z
Commit: 8c91c734c3056c2622f81b9f6c38c6c1ed75ff4e
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9363111

**Comment by n0samu** [comment] 2023-06-27 07:41
Duplicate of #11279

**Closed by n0samu** 2023-06-27 07:41 UTC
Labels: duplicate, error-report
