### ISSUE TITLE
Error on https://games.crazygames.com/en_US/electric-man/index.html

### ISSUE THREAD

**Issue by MrEpicGamer247** [ruffle-rs/ruffle#9637] opened 2023-02-19 10:56 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
Error stack:
```
966/D/n.wbg.__wbg_new_f9bb493369a83c12@https://files.crazygames.com/gameframe/ruffle/2022-12-21/core.ruffle.b5d6ce968050f90fdce9.js:1:6507
std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9@:wasm-function[1102]:0x2aa466
std::sys_common::once::generic::Once::call::h62f79875d8dd2a00@:wasm-function[1415]:0x31b27d
core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542@:wasm-function[5033]:0x4b585e
std::panicking::rust_panic_with_hook::he04cb00575f2a1e3@:wasm-function[3756]:0x471db6
core::panicking::panic_fmt::h586d720a90aa8503@:wasm-function[5275]:0x4ba6a9
core::panicking::panic::h0859aaac783261b2@:wasm-function[5087]:0x4b6790
core::ops::function::FnOnce::call_once::h7337c1ac486f5426@:wasm-function[1120]:0x2afed2
ruffle_core::avm1::function::Executable::exec::h0481198b4eba6fc1@:wasm-function[366]:0xeda9c
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h4be3085cc114bb53@:wasm-function[1455]:0x323d14
ruffle_core::avm1::activation::Activation::run_actions::h079d6bd6c21aea97@:wasm-function[302]:0x2b2bf
ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h55cd115eb740ef0a@:wasm-function[946]:0x2752ed
ruffle_core::player::Player::run_actions::hd89f218b98acfade@:wasm-function[462]:0x15be32
ruffle_web::Ruffle::tick::hdcb4afd54d8a568d@:wasm-function[648]:0x1f4045
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h5b63cba1bdda8f36@:wasm-function[6195]:0x4d5ef8
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h290fb0fdd8b6051e@:wasm-function[5634]:0x4c4476
S@https://files.crazygames.com/gameframe/ruffle/2022-12-21/core.ruffle.b5d6ce968050f90fdce9.js:1:2578
c@https://files.crazygames.com/gameframe/ruffle/2022-12-21/core.ruffle.b5d6ce968050f90fdce9.js:1:2255

```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://games.crazygames.com/en_US/electric-man/index.html
SWF URL: https://files.crazygames.com/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-21
Channel: nightly
Built: 2022-12-21T00:16:40.503Z
Commit: 5cf5c8d5e5d3b37a38cf133aa587b7f925612f21
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3641749

**Comment by n0samu** [comment] 2023-02-20 02:47
Duplicate of #4932

**Closed by n0samu** 2023-02-20 02:47 UTC
Labels: duplicate, error-report
