### ISSUE TITLE
Rendering errors and script errors.

### ISSUE THREAD

**Issue by gxlydlyf** [ruffle-rs/ruffle#18391] opened 2024-10-27 04:47 UTC
### Describe the bug

Rendering errors and script errors.
The console does not contain any error messages.
This flash game can be played using a real flash player.
I use the latest version (ver. nightly-2024-10-06).
It can enter the game normally, but the following page appears on the start game page after entering the game. As shown in the picture, a black square appears. It can't be displayed and can't be clicked to enter the game.
![Image](https://github.com/user-attachments/assets/1e577438-af7d-40f1-98fd-a3541d7e5cde)
I tried switching the ruffle version, and the ruffle@2021.12.31 version shows the following interface, but it still can't be clicked.
![Image](https://github.com/user-attachments/assets/2369d4ff-25a8-424b-8c00-126f69bbc0c9)
And the ruffle@ruffle@2021.3.19 version shows the following interface, and you can click to enter the game.
![Image](https://github.com/user-attachments/assets/8804dbba-ebf2-48a8-8e76-eaf6ce6e0adb)

### Expected behavior

The following page should appear, and clicking on the black paint next to "start" should enter the game.
![Image](https://github.com/user-attachments/assets/768ee845-5fae-49e7-97f5-164e66ce1e05)

### Content Location

http://farm.stickpage.com/stickwar_08.swf
[upload stickwar_08.zip](https://github.com/user-attachments/files/17532820/stickwar_08.zip)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0

### Additional information

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 600 (0x00003185) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: http://localhost:63342/Basic/StickWar/StickWar.html?_ijt=a93hnvpg7pdcldg1lqobvqrlag&_ij_reload=RELOAD_ON_SAVE
SWF URL: http://localhost:63342/Basic/StickWar/stickwar_08.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-10-06
Channel: nightly
Built: 2024-10-06T00:06:14.925Z
Commit: a93370135746a018930f2552fa9caa5fca2b027d
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 132
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 8106635

**Comment by Lord-McSweeney** [comment] 2024-10-27 04:51
Duplicate of #5126

**Closed by Lord-McSweeney** 2024-10-27 04:51 UTC
Labels: bug
