### ISSUE TITLE
Error on https://binbashbanana.github.io/gfiles/gfiles/flash/

### ISSUE THREAD

**Issue by Groovzthegameguy** [ruffle-rs/ruffle#6943] opened 2022-05-10 20:16 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/display_object/movie_clip.rs:3056:22
Error stack:
```
@https://binbashbanana.github.io/gfiles/gfiles/flash/ruffle.js:1:6712
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hdee01963557c8b87]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hf9144d66ddc67dec]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e75ef83c7eceddf]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h606d7c7f7a423b98]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h6314b5c91abe7349]@[wasm code]
<?>.wasm-function[core::result::unwrap_failed::hd584efb7b84bf326]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h1af7cb16f5b4181a]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h1c1370c90cf3ecfa]@[wasm code]
<?>.wasm-function[ruffle_load_data]@[wasm code]
wasm-stub@[native code]
load_data@https://binbashbanana.github.io/gfiles/gfiles/flash/ruffle.js:1:4978
@https://binbashbanana.github.io/gfiles/gfiles/flash/ruffle.js:1:55123
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://binbashbanana.github.io/gfiles/gfiles/flash/?swf=fancypantsadventure.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-21
Channel: nightly
Built: 2021-12-21T00:14:34.280Z
Commit: ccef61d0764c66d2f034ea07273d218b0f98e529
Is extension: false

**Comment by n0samu** [comment] 2024-06-23 23:40
Likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:40 UTC
Labels: error-report
