### ISSUE TITLE
Error on https://www.gameflare.com/embed/learn-to-fly-3/

### ISSUE THREAD

**Issue by cescotoescoba** [ruffle-rs/ruffle#17786] opened 2024-09-06 13:44 UTC
# Error Info
Error name: Error
Error message: panicked at library/core/src/slice/sort/shared/smallsort.rs:862:5:
user-provided comparison function does not correctly implement a total order
Error stack:
```
Error: panicked at library/core/src/slice/sort/shared/smallsort.rs:862:5:
user-provided comparison function does not correctly implement a total order
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://www.gameflare.com/emulators/ruffle/core.ruffle.1fad5110710476fd8724.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::hfb561c222a4e70eb (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[12753]:0x98635f)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h81099db94754a517 (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[9827]:0x917b42)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[6388]:0x80ffe8)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[9548]:0x90888f)
    at ruffle_web.wasm.core::slice::sort::shared::smallsort::panic_on_ord_violation::h6266206df1341888 (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[10504]:0x935194)
    at ruffle_web.wasm.core::slice::sort::shared::smallsort::sort8_stable::h9208d16bd48b1f86 (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[2481]:0x5b2833)
    at ruffle_web.wasm.core::slice::sort::unstable::quicksort::quicksort::hbd9cdfc66b3cdad0 (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[1160]:0x33041f)
    at ruffle_web.wasm.ruffle_core::avm2::globals::vector::sort::hcdd80dd73f6420ca (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[1536]:0x436822)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::hc31dc0a4622656ce (wasm://wasm/ruffle_web.wasm-0320469e:wasm-function[1355]:0x3ccc8e)
```
AVM2 stack:
```
    at __AS3__.vec::Vector.<*>/sort()
    at src.gui.menus::EndGameScreen/generateCards()
    at src.gui.menus::EndGameScreen/tickBrightness()
    at org.osflash.signals::Slot/execute()
    at org.osflash.signals::OnceSignal/dispatch()
    at src::Main/enterFrameTick()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Mesa Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 128, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.gameflare.com/embed/learn-to-fly-3/
SWF URL: https://data.gameflare.com/games/6897/qOzPxl4TTIqgMm.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-06
Channel: nightly
Built: 2024-09-06T00:06:03.493Z
Commit: 5550443fdb27d6318e3882949dedffd48725e05a
Is extension: false

# Metadata
width: 720
height: 540
frameRate: 60
numFrames: 3
swfVersion: 28
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 21982504

**Comment by kjarosh** [comment] 2024-09-06 16:32
Duplicate of https://github.com/ruffle-rs/ruffle/issues/17785

**Closed by kjarosh** 2024-09-06 16:32 UTC
Labels: error-report
