### ISSUE TITLE
Some loops are looping with the wrong period

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle#2699] opened 2021-01-20 23:18 UTC
One example SWF is: https://z0r.de/L/z0r-de_2139.swf

This .swf "lies" in its header about the number of frames it has:
![image](https://user-images.githubusercontent.com/288816/105251483-e7068000-5b7b-11eb-8808-d6ab2ed623ab.png)

The `frameCount` property is `9000`, while there are only actually `153` frames with any data in them.

This means that this clip (with its 15 fps frame rate) will loop in ruffle with 10 minute periods. (I tried, and it does indeed loop around eventually.)
While in Adobe's player, it loops with the "expected" ~15.3s period.

I don't know if the `end` tag is supposed to instantly rewind the clip; or if the first "empty" frame should do that; or simply any empty frames (with no data) should be skipped - I haven't checked these options with the Adobe player yet.

**Comment by Herschel** [comment] 2021-01-20 23:24
Dupe of #932

**Closed by Herschel** 2021-01-20 23:24 UTC

**Comment by torokati44** [comment] 2021-01-20 23:26
Oh, okay, sorry, haven't found that one.

**Comment by Herschel** [comment] 2021-01-20 23:42
No worries :-)
