### ISSUE TITLE
Error on http://www.freeworldgroup.com/games8/gameindex/dspace.htm

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#2828] opened 2021-01-25 04:42 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/ruffle.js:1:6349)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (http://www.freeworldgroup.com/ruffle/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1265]:0x24e3c9)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (http://www.freeworldgroup.com/ruffle/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1528]:0x27e7a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (http://www.freeworldgroup.com/ruffle/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4309]:0x3537a0)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (http://www.freeworldgroup.com/ruffle/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3299]:0x32c417)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (http://www.freeworldgroup.com/ruffle/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3916]:0x3495f5)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (http://www.freeworldgroup.com/ruffle/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4655]:0x358eda)
    at rust_begin_unwind (http://www.freeworldgroup.com/ruffle/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4526]:0x3574b8)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (http://www.freeworldgroup.com/ruffle/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4657]:0x358f3e)
    at core::option::expect_none_failed::hb95d2b1dc5448c17 (http://www.freeworldgroup.com/ruffle/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3996]:0x34be07)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games8/gameindex/dspace.htm
SWF URL: http://www.freeworldgroup.com/games8/dspace/dspace_release_encrypt.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by Toad06** [comment] 2021-02-20 17:09
Duplicate of #2536.

**Closed by Toad06** 2021-02-20 17:09 UTC
