### ISSUE TITLE
Error on https://www.miniplay.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by LucasBaneke** [ruffle-rs/ruffle#4181] opened 2021-04-30 20:14 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://hmdhgacjpagdkbnfcfihminakbajndoa/dist/ruffle.js?uniqueMessageSuffix=8760191534:1:8279)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (chrome-extension://hmdhgacjpagdkbnfcfihminakbajndoa/dist/a7cf393d55f020dbf210.wasm:wasm-function[1045]:0x2866eb)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (chrome-extension://hmdhgacjpagdkbnfcfihminakbajndoa/dist/a7cf393d55f020dbf210.wasm:wasm-function[1248]:0x2bbefb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (chrome-extension://hmdhgacjpagdkbnfcfihminakbajndoa/dist/a7cf393d55f020dbf210.wasm:wasm-function[3728]:0x446707)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (chrome-extension://hmdhgacjpagdkbnfcfihminakbajndoa/dist/a7cf393d55f020dbf210.wasm:wasm-function[2725]:0x3a4495)
    at rust_begin_unwind (chrome-extension://hmdhgacjpagdkbnfcfihminakbajndoa/dist/a7cf393d55f020dbf210.wasm:wasm-function[3933]:0x44c36b)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (chrome-extension://hmdhgacjpagdkbnfcfihminakbajndoa/dist/a7cf393d55f020dbf210.wasm:wasm-function[4075]:0x452f3a)
    at core::option::expect_none_failed::h203584ddbc785ca2 (chrome-extension://hmdhgacjpagdkbnfcfihminakbajndoa/dist/a7cf393d55f020dbf210.wasm:wasm-function[3360]:0x437ba1)
    at ruffle_core::avm2::object::TObject::install_foreign_trait::ha05d434e1f91a6a9 (chrome-extension://hmdhgacjpagdkbnfcfihminakbajndoa/dist/a7cf393d55f020dbf210.wasm:wasm-function[323]:0x9c3af)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::h607731069cd142dc (chrome-extension://hmdhgacjpagdkbnfcfihminakbajndoa/dist/a7cf393d55f020dbf210.wasm:wasm-function[445]:0x134683)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/desertrifle2.swf
Param quality: high
Param allowscriptaccess: always
Param allowfullscreen: false
Param wmode: direct
Param flashvars: mp_log_level=4&mp_game_id=16593&mp_game_url=https%3A%2F%2Fwww.miniplay.com%2Fembed%2Fdesert-rifle-2&mp_site_name=miniplay.com&mp_site_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_api_id=&mp_api_as3_url=&mp_api_as3_url_bck=&mp_api_user_id=&mp_api_user_token=&mp_locale=en_US&mp_timezone=Europe%2FAmsterdam&mp_embed=false&mp_base_path=https%3A%2F%2Fwww.minijuegosgratis.com%2Fflash1234%2Fno_hotlink%2F
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.miniplay.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=16593&mp_game_uid=desert-rifle-2&mp_game_url=https%3A%2F%2Fwww.miniplay.com%2Fembed%2Fdesert-rifle-2&mp_int=1&mp_locale=en_US&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvZGVzZXJ0cmlmbGUyLnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_site_name=miniplay.com&mp_site_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_timezone=Europe%2FAmsterdam&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/desertrifle2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-30
Channel: nightly
Built: 2021-04-30T00:13:56.245Z
Commit: c465e268bfd43eb1eeb5b6e39ca3952c20e42f86

**Comment by relrelb** [comment] 2021-11-12 18:40
Duplicate of #4182.

**Closed by relrelb** 2021-11-12 18:40 UTC
Labels: error-report
