### ISSUE TITLE
Error on https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.html?f=graviteevfinal15cm.swf&w=700&h=500

### ISSUE THREAD

**Issue by Peiprjs** [ruffle-rs/ruffle#3668] opened 2021-03-15 13:22 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
e/a.wbg.__wbg_new_df6e6ab7a65c4c4d@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.js:1:6799
std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[1333]:0x26daf5
std::sync::once::Once::call_inner::h02eac160d339afc2@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[1612]:0x2a14b7
core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[4651]:0x3840c9
std::panicking::rust_panic_with_hook::h123718ba3bf480af@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[3487]:0x3580a5
std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[4150]:0x377320
std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[5003]:0x3898a7
rust_begin_unwind@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[4880]:0x38801b
core::panicking::panic_fmt::h285dc015a87be5a4@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[5005]:0x38990b
core::option::expect_none_failed::hb95d2b1dc5448c17@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[4247]:0x37a3f9
ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hdbc2f83981320245@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[464]:0x133d8b
<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h9a835e0bbc2eb0c2@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[2982]:0x33829d
ruffle_core::drawing::Drawing::render::h816ff26d153fbdae@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[852]:0x1ef6c6
ruffle_core::display_object::TDisplayObject::render::h4357ecbb915ae63b@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[1582]:0x29c396
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h98955a76fb9b16cf@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[4327]:0x37c88c
ruffle_core::display_object::container::TDisplayObjectContainer::render_children::h7a2522531a6d650a@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[1243]:0x25a956
ruffle_core::display_object::TDisplayObject::render::h4357ecbb915ae63b@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[1582]:0x29c3aa
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h98955a76fb9b16cf@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[4327]:0x37c88c
ruffle_core::player::Player::render::h24df90c739ca44e6@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[860]:0x1f2251
std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[784]:0x1d7631
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hc579618b4ad6cfcd@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[4912]:0x388717
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hfc6d3990177bfa48@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/f04dfee887674fda8ce19b49c74b614e.wasm:wasm-function[5163]:0x38b2fd
F@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.js:1:3584
a@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.js:1:2840

```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.coolmath-games.com/sites/cmatgame/files/games/graviteevfinal15cm.swf
Param allowScriptAccess: always
Param movie: graviteevfinal15cm.swf
Param menu: false
Param quality: high
Param wmode: direct
Param scale: exactfit
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.html?f=graviteevfinal15cm.swf&w=700&h=500
SWF URL: https://www.coolmath-games.com/sites/cmatgame/files/games/graviteevfinal15cm.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-11
Channel: nightly
Built: 2021-02-11T00:18:16.959Z
Commit: 09c6def7f0df64f3868631be6b2c188c6b61ae75

**Comment by relrelb** [comment] 2021-03-15 18:04
Duplicate of #3642.

**Closed by relrelb** 2021-03-15 18:04 UTC
