### ISSUE TITLE
Error on https://www.gamesflow.com/jeux.php

### ISSUE THREAD

**Issue by javi6458** [ruffle-rs/ruffle#9386] opened 2023-02-01 23:07 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.gamesflow.com/include/p_jeux/ruffle/core.ruffle.9f799b172fb83660e1a8.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::ha360d592741a73b3 (wasm://wasm/017cacaa:wasm-function[1138]:0x2c083f)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/017cacaa:wasm-function[1447]:0x320287)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h613b00154d20bc2b (wasm://wasm/017cacaa:wasm-function[4879]:0x478fc0)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/017cacaa:wasm-function[3630]:0x441860)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/017cacaa:wasm-function[5070]:0x47f7eb)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/017cacaa:wasm-function[4231]:0x4650d4)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::ha218e368eb1b9341 (wasm://wasm/017cacaa:wasm-function[2532]:0x3e2edb)
    at ruffle_core::display_object::render_base::hc7954d410b384b2c (wasm://wasm/017cacaa:wasm-function[1157]:0x2c5bf4)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h4a7b29cc39190024 (wasm://wasm/017cacaa:wasm-function[3854]:0x44f9c5)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.gamesflow.com/jeux.php?id=5002341
SWF URL: https://www.gamesflow.com/jeux/57bee6645d6d9.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-19
Channel: nightly
Built: 2022-09-19T00:15:10.357Z
Commit: 9b9c95bfe28cb862d44e9517e94e9de73acd9de3
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: null
isActionScript3: false
uncompressedLength: 20459422

**Comment by n0samu** [comment] 2023-02-06 08:29
Duplicate of #7978. This problem has already been fixed by #8248. Please contact the website owner and ask them to update their copy of Ruffle.

**Closed by n0samu** 2023-02-06 08:29 UTC
Labels: duplicate, error-report
