### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by rchualopez** [ruffle-rs/ruffle#8059] opened 2022-09-23 14:26 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:24:9
Error stack:
```
966/W/n.wbg.__wbg_new_df6e6ab7a65c4c4d@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.b178705079809261f957.js:1:5314
std::sync::once::Once::call_once::{{closure}}::h8ea9ab9bf1a6fa87@:wasm-function[1012]:0x29c225
std::sync::once::Once::call_inner::hb30cfbde5209eed0@:wasm-function[1477]:0x328413
core::ops::function::FnOnce::call_once{{vtable.shim}}::h7b268efc0b6187e5@:wasm-function[4965]:0x48fa2c
std::panicking::rust_panic_with_hook::hb09154fa23e06c37@:wasm-function[3648]:0x44be72
core::panicking::panic_fmt::h9e229748e3ae9f9d@:wasm-function[5118]:0x495878
core::panicking::assert_failed_inner::hfbd38b17d5176c0e@:wasm-function[2262]:0x3c7237
core::panicking::assert_failed::h2b44d5d0602a16ff@:wasm-function[4727]:0x48a779
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hab5b1fa51223acb6@:wasm-function[1075]:0x2b41f8
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h60743e88a2732810@:wasm-function[1024]:0x2a020f
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h9792d5aa1e4e1f3d@:wasm-function[2284]:0x3cae2e
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6ad9b96f16c63cc6@:wasm-function[5485]:0x49f528
closure2928 externref shim@:wasm-function[5607]:0x4a1c59
S@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.b178705079809261f957.js:1:2706
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.b178705079809261f957.js:1:2231

```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1663941735%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F484000%2F484931_peeps.swf%3F1509024282%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22632dc1e8f3ea6%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A450%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F484000%2Fflash_484931_card.png%3Ff1609851325%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/484000/484931_peeps.swf?1509024282

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-23
Channel: nightly
Built: 2022-09-23T00:15:34.189Z
Commit: a17352a01ad50a0f52666c054b22cec51306689c
Is extension: false

# Metadata
width: 640
height: 450
frameRate: 35
numFrames: 19
swfVersion: 9
backgroundColor: #999999
isActionScript3: false
uncompressedLength: 12314677

**Comment by n0samu** [comment] 2022-09-23 23:06
Duplicate of #4043. I'm surprised this error has shown up again - could you add a comment to that issue explaining what you were doing leading up to that error?

**Closed by n0samu** 2022-09-23 23:06 UTC
Labels: error-report
