### ISSUE TITLE
2021-10-15 does not start

### ISSUE THREAD

**Issue by ShiN-K-278** [ruffle-rs/ruffle#8296] opened 2022-10-15 12:44 UTC
### Describe the bug

The Windows version of 2021-10-15 does not boot. Versions prior to 2021-10-14 can be booted.

### Expected behavior

After selecting the file, a Flash window will be displayed.

### Affected platform

Desktop app

### Operating system

Windows 11 22H2

**Comment by n0samu** [comment] 2022-10-15 12:49
I assume you mean 2022? 😉 
Anyway, duplicate of #8295.

**Closed by n0samu** 2022-10-15 12:49 UTC
Labels: bug, duplicate
