### ISSUE TITLE
Error on https://www.gameflare.com/embed/can-your-pet/

### ISSUE THREAD

**Issue by slilima** [ruffle-rs/ruffle#7950] opened 2022-09-11 17:50 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/array.rs:61:37
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/array.rs:61:37
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.gameflare.com/emulators/ruffle/core.ruffle.cea989e40903bfeeffd4.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::h53c4bd4dfa98b52c (wasm://wasm/0171ba0a:wasm-function[946]:0x2737bd)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/0171ba0a:wasm-function[1399]:0x2f6e70)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hfdd3b2ecbbfe0d5b (wasm://wasm/0171ba0a:wasm-function[4866]:0x452bc4)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/0171ba0a:wasm-function[3619]:0x41bcb8)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/0171ba0a:wasm-function[5050]:0x459205)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/0171ba0a:wasm-function[4953]:0x4543ea)
    at <ruffle_core::avm2::object::array_object::ArrayObject as ruffle_core::avm2::object::TObject>::set_property_local::h1f98ebcfb6b3b190 (wasm://wasm/0171ba0a:wasm-function[1161]:0x2b0e53)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::h0bc8ad5e60b680f4 (wasm://wasm/0171ba0a:wasm-function[392]:0x11705d)
    at ruffle_core::avm2::activation::Activation::run_actions::hdc9afe4a3b47ebaf (wasm://wasm/0171ba0a:wasm-function[290]:0x25929)
```
AVM2 stack:
```
    at scaryama.transitions::FlashingBtn/onChange()
    at flash.events::EventDispatcher/dispatchEvent()
    at fl.transitions::Tween/setPosition()
    at fl.transitions::Tween/update()
    at fl.transitions::Tween/set time()
    at fl.transitions::Tween/nextFrame()
    at fl.transitions::Tween/onEnterFrame()
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://www.gameflare.com/embed/can-your-pet/
SWF URL: https://data.gameflare.com/games/5432/VYxeLzwlUs5C8b.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-10
Channel: nightly
Built: 2022-09-10T00:17:33.840Z
Commit: 5de21428f5972e7ce4834e62714d4a11e7b214e9
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 45
numFrames: 1734
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 1867130

**Comment by n0samu** [comment] 2022-09-11 18:18
Duplicate of #7865

**Closed by n0samu** 2022-09-11 18:18 UTC
Labels: duplicate, error-report
