### ISSUE TITLE
Error on http://andkon.com/arcade/adventureaction/electricman2/

### ISSUE THREAD

**Issue by toaster42** [ruffle-rs/ruffle#7700] opened 2022-08-19 06:46 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7359)
    at std::sync::once::Once::call_once::{{closure}}::he3cf99cdc4fda287 (wasm://wasm/016a2792:wasm-function[1401]:0x2f7d60)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/016a2792:wasm-function[1363]:0x2f02ad)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha1e2d21f5521daa9 (wasm://wasm/016a2792:wasm-function[4786]:0x43f171)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/016a2792:wasm-function[3508]:0x404e1a)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/016a2792:wasm-function[4965]:0x444944)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/016a2792:wasm-function[4873]:0x440985)
    at core::ops::function::FnOnce::call_once::h5d896e6757363123 (wasm://wasm/016a2792:wasm-function[1013]:0x288b04)
    at ruffle_core::avm1::function::Executable::exec::h617d7843d3858b48 (wasm://wasm/016a2792:wasm-function[354]:0xdf2ef)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hddfd162220c32fa4 (wasm://wasm/016a2792:wasm-function[451]:0x151eef)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://andkon.com/arcade/adventureaction/electricman2/
SWF URL: http://andkon.com/arcade/adventureaction/electricman2/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS aarch64 14909.100.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-19
Channel: nightly
Built: 2022-08-19T00:32:19.002Z
Commit: 7a53322cbb09d84e3cb1ddaa8d0d67703aa80eb3
Is extension: true

**Comment by n0samu** [comment] 2022-08-19 07:07
Duplicate of #4932

**Closed by n0samu** 2022-08-19 07:07 UTC
Labels: duplicate, error-report
