### ISSUE TITLE
Error on https://www.comdotgame.com/play/swords-and-sandals-2-full

### ISSUE THREAD

**Issue by ntanackovic00** [ruffle-rs/ruffle#11989] opened 2023-07-10 15:52 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.1/src/gles/device.rs:704:52
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.1/src/gles/device.rs:704:52
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7df5da66b3223953 (wasm://wasm/02d9541a:wasm-function[8829]:0x87b44a)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02d9541a:wasm-function[5879]:0x789065)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02d9541a:wasm-function[8692]:0x876fff)
    at core::result::unwrap_failed::he0ddc269083098af (wasm://wasm/02d9541a:wasm-function[6760]:0x7d9f09)
    at <T as wgpu::context::DynContext>::device_create_texture::ha110d46419c4ac16 (wasm://wasm/02d9541a:wasm-function[6539]:0x7c8c1e)
    at wgpu::Device::create_texture::h2caca62f0a8c3a4d (wasm://wasm/02d9541a:wasm-function[4571]:0x71be50)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h6d50d53878fb0fd9 (wasm://wasm/02d9541a:wasm-function[4899]:0x73801e)
    at ruffle_core::display_object::render_base::h21d1b25324feb5e4 (wasm://wasm/02d9541a:wasm-function[646]:0x1ebed0)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hd2c4b787dd66067e (wasm://wasm/02d9541a:wasm-function[6339]:0x7b52e2)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/9b60499a5698f6ebe5b5ad3cc192469e.swf
Param allowscriptaccess: always
Param bgcolor: 000000
Param wmode: gpu
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/swords-and-sandals-2-full
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/9b60499a5698f6ebe5b5ad3cc192469e.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-10
Channel: nightly
Built: 2023-07-10T00:23:25.536Z
Commit: f5b4fbce77b229de1df1738cd6375079c3b3bd3b
Is extension: true

# Metadata
width: 640
height: 420
frameRate: 30
numFrames: 278
swfVersion: 8
backgroundColor: #FFCC66
isActionScript3: false
uncompressedLength: 5227470

**Comment by evilpie** [comment] 2024-02-01 20:34
Duplicate of https://github.com/ruffle-rs/ruffle/issues/11852

**Closed by evilpie** 2024-02-01 20:34 UTC
Labels: error-report
