### ISSUE TITLE
Nightlies 2021-03-01 and 2021-03-02 flickering

### ISSUE THREAD

**Issue by Padre2** [ruffle-rs/ruffle#3501] opened 2021-03-02 06:55 UTC
Up to and including Nightly 2021-02-27, most SWF flies open without problems.
Some complex interactive files have dropdown menus which do not open in chromium-based browsers, but do open in Firefox and Gecko-based browsers. Although the drop-down menus do open, selections cannot be made.

With the Nightlies dated 2021-03-01 and 2021-03-02, all SWF files tried produce a rapidly flickering display,

The above on Windows desktop with Ruffle Demo and with browsers opening files on website with Ruffle nightly installed.

**Comment by torokati44** [comment] 2021-03-02 11:49
Could this be because of https://github.com/ruffle-rs/ruffle/pull/3066 ?

**Comment by jooy0224** [comment] 2021-03-02 12:19
have the same problem with me. A game that used to work well appears flickering after the March 1st build.
It can be reproduced with the following flash file (Side Kick 2007).
(Does not go to the next frame in the "please wait..." screen)

[sidekick2007.zip](https://github.com/ruffle-rs/ruffle/files/6068507/sidekick2007.zip)

**Comment by Toad06** [comment] 2021-03-02 12:53
There's also an issue with [Bomb Jack](https://www.y8.com/games/bomb_jack), you can no longer play the game.

I ran a bisect, it appears that issues in _Bomb Jack_ and _Side Kick 2007_ started with commit dad21d43986a9f51a535cca9747b3f1198738f18

**Comment by Padre2** [comment] 2021-03-04 06:07
Nightly 2021-03-04 self-hosted has the same issue. Checking several  files in the Demo, it appears to occur when files have some form of obfuscation or protection applied to the code.

**Comment by torokati44** [comment] 2021-03-05 01:43
At least Side Kick 2007 is fixed by the two-line change in https://github.com/ruffle-rs/ruffle/issues/3525#issuecomment-791077972 .

**Closed** 2021-03-08 08:49 UTC
Labels: avm1, avm2, swf
