### ISSUE TITLE
Error on https://fgn.cdn.serverable.com/common/flashes/nf/how_to_discipline_a_shoplifting_girl/index.html

### ISSUE THREAD

**Issue by Alekss35** [ruffle-rs/ruffle#8916] opened 2022-12-24 21:19 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/cmp.rs:865:9
Error stack:
```
@https://fgn.cdn.serverable.com/common/flashes/js/ruffle221013/core.ruffle.e771ebbe2c77caceae25.js:1:7398
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hf9ee3cf8881ab9cc]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hb30cfbde5209eed0]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e53a26a8ce616de]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::hb09154fa23e06c37]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h9e229748e3ae9f9d]@[wasm code]
<?>.wasm-function[core::panicking::panic::h6f5024a57ca8da86]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::update_drag::hc3ae1c868be4ef62]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::hcb865cc692df77c5]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h8271d03c5ade39ce]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::heb1d46c70fb35121]@[wasm code]
wasm-stub@[native code]
T@https://fgn.cdn.serverable.com/common/flashes/js/ruffle221013/core.ruffle.e771ebbe2c77caceae25.js:1:3033
c@https://fgn.cdn.serverable.com/common/flashes/js/ruffle221013/core.ruffle.e771ebbe2c77caceae25.js:1:2485
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: start.swf
Param movie: start.swf
Param quality: high
Param bgcolor: #999999
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param allowFullScreen: true
Param devicefont: false
Param allowScriptAccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://fgn.cdn.serverable.com/common/flashes/nf/how_to_discipline_a_shoplifting_girl/index.html?d=20170708135810?e=MTY3MTczNTY1MA%3D%3D
SWF URL: https://fgn.cdn.serverable.com/common/flashes/nf/how_to_discipline_a_shoplifting_girl/start.swf

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 YaBrowser/22.11.7.76.10 SA/3 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-13
Channel: nightly
Built: 2022-10-13T00:21:23.904Z
Commit: feda41d6c1e22027dbebfc157087050adc4a9acb
Is extension: false

# Metadata
width: 600
height: 600
frameRate: 24
numFrames: 124
swfVersion: 10
backgroundColor: #999999
isActionScript3: true
uncompressedLength: 15427115

**Comment by n0samu** [comment] 2022-12-25 04:03
Duplicate of #8845

**Comment by n0samu** [comment] 2023-01-05 11:13
Reopening because the original issue was deleted

**Closed** 2023-01-10 23:09 UTC
Labels: nsfw, error-report
