### ISSUE TITLE
Error on https://simply-history.xyz/swf

### ISSUE THREAD

**Issue by Serphos27** [ruffle-rs/ruffle#9399] opened 2023-02-03 13:50 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:747:33
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:747:33
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.c110e09463ad81cadf9e.js:1:5412)
    at std::sync::once::Once::call_once::{{closure}}::h24436b3e76607d05 (wasm://wasm/027a13a6:wasm-function[1921]:0x48dea0)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027a13a6:wasm-function[1855]:0x47daa8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdf8faf7e861f36fc (wasm://wasm/027a13a6:wasm-function[7118]:0x7611cb)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027a13a6:wasm-function[5050]:0x6bedb5)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027a13a6:wasm-function[7429]:0x76feca)
    at core::panicking::panic::h364c37174a08a6a4 (wasm://wasm/027a13a6:wasm-function[6843]:0x73c847)
    at core::ops::function::FnOnce::call_once::hc3dca223e3bc8c64 (wasm://wasm/027a13a6:wasm-function[787]:0x27c5d1)
    at ruffle_core::avm1::function::Executable::exec::h05de1024cd75b75b (wasm://wasm/027a13a6:wasm-function[578]:0x1859e7)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hdb83886636a26c3d (wasm://wasm/027a13a6:wasm-function[1384]:0x3ae372)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://simply-history.xyz/swf?notebook=electricman2
SWF URL: https://simply-history.xyz/swffiles/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-02
Channel: nightly
Built: 2023-02-02T00:19:19.827Z
Commit: 198e40fd2ef4a36b7a3679d24dd3e567bdc63423
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3641749

**Comment by n0samu** [comment] 2023-02-06 08:56
Duplicate of #4932

**Closed by n0samu** 2023-02-06 08:56 UTC
Labels: duplicate, error-report
