### ISSUE TITLE
Error on https://play.cprewritten.net/

### ISSUE THREAD

**Issue by jsanon01** [ruffle-rs/ruffle#4772] opened 2021-07-04 20:13 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h5a73b3c37f29875c (https://play.cprewritten.net/assets/lib/ruffle/ed8fb1278950d8015875.wasm:wasm-function[1006]:0x2823c1)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (https://play.cprewritten.net/assets/lib/ruffle/ed8fb1278950d8015875.wasm:wasm-function[974]:0x2785fb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h265fbb84ca9e6c29 (https://play.cprewritten.net/assets/lib/ruffle/ed8fb1278950d8015875.wasm:wasm-function[3858]:0x41fac3)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://play.cprewritten.net/assets/lib/ruffle/ed8fb1278950d8015875.wasm:wasm-function[2986]:0x3bf2dc)
    at rust_begin_unwind (https://play.cprewritten.net/assets/lib/ruffle/ed8fb1278950d8015875.wasm:wasm-function[4067]:0x4253cc)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://play.cprewritten.net/assets/lib/ruffle/ed8fb1278950d8015875.wasm:wasm-function[4216]:0x42c145)
    at core::result::unwrap_failed::h9bf99bca88ba05dc (https://play.cprewritten.net/assets/lib/ruffle/ed8fb1278950d8015875.wasm:wasm-function[3432]:0x40d521)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h99b84a46942446fa (https://play.cprewritten.net/assets/lib/ruffle/ed8fb1278950d8015875.wasm:wasm-function[593]:0x1be119)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::haacb17a40530aa94 (https://play.cprewritten.net/assets/lib/ruffle/ed8fb1278950d8015875.wasm:wasm-function[501]:0x17a748)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://play.cprewritten.net/
SWF URL: https://play.cprewritten.net/assets/flash/global/games/boot.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13904.41.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.81 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-22
Channel: nightly
Built: 2021-06-22T00:10:37.922Z
Commit: e0107750996b5b3724680ead1acda0124002baea

**Comment by relrelb** [comment] 2021-08-13 14:13
Duplicate of #4998.

**Closed by relrelb** 2021-08-13 14:13 UTC
