### ISSUE TITLE
Error on https://ooooooooo.ooo/static/

### ISSUE THREAD

**Issue by soupboy895** [ruffle-rs/ruffle#13305] opened 2023-09-24 22:45 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.38d6cc97fe16314132cf.js:1:51844)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h57def9a78408b97f (wasm://wasm/030bf8fe:wasm-function[9332]:0x925370)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/030bf8fe:wasm-function[6098]:0x825e87)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/030bf8fe:wasm-function[9168]:0x920987)
    at core::ops::function::Fn::call::h9c7f5d1e973a4a59 (wasm://wasm/030bf8fe:wasm-function[6303]:0x8321cd)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h09222b538ec8307d (wasm://wasm/030bf8fe:wasm-function[4935]:0x790535)
    at wgpu::backend::direct::Context::handle_error::hf547d7fa4fc41168 (wasm://wasm/030bf8fe:wasm-function[2546]:0x5e2cf0)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h8036b8dcb3f54166 (wasm://wasm/030bf8fe:wasm-function[6685]:0x85e8e3)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h52173ae4f44f48b2 (wasm://wasm/030bf8fe:wasm-function[5721]:0x8072f7)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h644e2d11edbcc2b0 (wasm://wasm/030bf8fe:wasm-function[1577]:0x48638a)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (ARM, Mali-G52, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 4096, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ooooooooo.ooo/static/?a94d865c-cb38-4d31-96f3-dda26502c4a3
SWF URL: http://i.flipline.com/gamefiles/jacksmith/jacksmith_v2.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-24
Channel: nightly
Built: 2023-09-24T00:20:46.080Z
Commit: 8aec2f17037506d9d8ecf36cbc4908a061652daf
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9363111

**Comment by evilpie** [comment] 2024-04-09 15:23
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:23 UTC
Labels: error-report
