### ISSUE TITLE
Error on https://incredibots.com/if/game.php

### ISSUE THREAD

**Issue by Late-Is-Cool** [ruffle-rs/ruffle#16464] opened 2024-05-25 22:24 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f77055/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mozilla"
Adapter Device Type: Other
Adapter Driver Name: "WebGL"
Adapter Driver Info: "2.0"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 2048, max_texture_dimension_2d: 2048, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://incredibots.com/if/game.php
SWF URL: https://incredibots.com/if/incredibots2.swf?1604326052

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-05-18
Channel: nightly
Built: 2024-05-18T00:05:25.487Z
Commit: f573f7b1412e745879aee42519eb5e08fb7614bb
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 104991

**Comment by n0samu** [comment] 2024-07-03 05:08
Duplicate of #10520

**Closed by n0samu** 2024-07-03 05:08 UTC
Labels: duplicate, error-report, amf
