### ISSUE TITLE
Error on https://www.superhry.cz/games/812/

### ISSUE THREAD

**Issue by majko666** [ruffle-rs/ruffle#6163] opened 2022-01-29 13:24 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.superhry.cz/js/ruffle_20220104/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::hd1b4f64c6a058fdf (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[983]:0x2f9eff)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[1181]:0x33f23b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7c91d9e8737f5a50 (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[4674]:0x5052ae)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[3234]:0x4b0abb)
    at rust_begin_unwind (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[4737]:0x5067d8)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[4949]:0x5116c1)
    at core::panicking::panic::hec1fc057bd0baf0b (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[4671]:0x504b14)
    at core::ops::function::FnOnce::call_once::h83f26a94bb6d39f3 (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[1040]:0x31858a)
    at ruffle_core::avm1::function::Executable::exec::h00e69fc62e0063bd (https://www.superhry.cz/js/ruffle_20220104/cd7e6f7aaff275ad7eb9.wasm:wasm-function[435]:0x163992)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.superhry.cz/games/812/
SWF URL: https://www.superhry.cz/cnt_img/000/812.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-04
Channel: nightly
Built: 2022-01-04T00:13:48.083Z
Commit: a9e86a73cf17845356a3bd38fe42c50e584a693c
Is extension: false

**Comment by Poopooracoocoo** [comment] 2022-01-30 12:39
Duplicate of #4932.

**Closed by Poopooracoocoo** 2022-01-30 12:39 UTC
Labels: duplicate, error-report
