### ISSUE TITLE
Error on https://www.gameflare.com/embed/chibi-knight/

### ISSUE THREAD

**Issue by nunosard** [ruffle-rs/ruffle#5008] opened 2021-08-06 03:46 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.gameflare.com/emulators/ruffle/ruffle.js?id=d5e54bfb7acfbe074052:1:7476)
    at std::sync::once::Once::call_once::{{closure}}::h5df181b90ad904c1 (https://www.gameflare.com/emulators/ruffle/d5e54bfb7acfbe074052.wasm:wasm-function[1008]:0x282ec2)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (https://www.gameflare.com/emulators/ruffle/d5e54bfb7acfbe074052.wasm:wasm-function[975]:0x278d20)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbd170ba35c598204 (https://www.gameflare.com/emulators/ruffle/d5e54bfb7acfbe074052.wasm:wasm-function[3880]:0x424f57)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://www.gameflare.com/emulators/ruffle/d5e54bfb7acfbe074052.wasm:wasm-function[2996]:0x3c380c)
    at rust_begin_unwind (https://www.gameflare.com/emulators/ruffle/d5e54bfb7acfbe074052.wasm:wasm-function[4092]:0x42a8ff)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://www.gameflare.com/emulators/ruffle/d5e54bfb7acfbe074052.wasm:wasm-function[4242]:0x4316d2)
    at core::panicking::panic::h5bfdfaa3db9a4b4a (https://www.gameflare.com/emulators/ruffle/d5e54bfb7acfbe074052.wasm:wasm-function[4034]:0x428002)
    at core::ops::function::FnOnce::call_once::h862d0560e2b20be7 (https://www.gameflare.com/emulators/ruffle/d5e54bfb7acfbe074052.wasm:wasm-function[869]:0x255ff0)
    at ruffle_core::avm1::function::Executable::exec::h590beaec26993867 (https://www.gameflare.com/emulators/ruffle/d5e54bfb7acfbe074052.wasm:wasm-function[364]:0xda8e4)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/chibi-knight/
SWF URL: https://data.gameflare.com/games/6255/H8me4QU2dF0alM.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-19
Channel: nightly
Built: 2021-07-19T00:11:43.934Z
Commit: 536526a34216e1f7e1e05d83e3466fff0bc06c31

**Comment by relrelb** [comment] 2021-08-13 14:06
Duplicate of #4624.

**Closed by relrelb** 2021-08-13 14:06 UTC
