### ISSUE TITLE
Error on https://sh--9pfs.repl.co/g/6f2e0289/electric-man-2

### ISSUE THREAD

**Issue by Roughlake** [ruffle-rs/ruffle#7994] opened 2022-09-16 15:41 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.44ea0bb01ee08a0e0757.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::ha360d592741a73b3 (wasm://wasm/0179a60e:wasm-function[1138]:0x2be547)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/0179a60e:wasm-function[1439]:0x3142c7)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h613b00154d20bc2b (wasm://wasm/0179a60e:wasm-function[4836]:0x46fa49)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/0179a60e:wasm-function[3601]:0x437d76)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/0179a60e:wasm-function[5023]:0x476147)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/0179a60e:wasm-function[4921]:0x4711de)
    at core::ops::function::FnOnce::call_once::h9baee3432cd92051 (wasm://wasm/0179a60e:wasm-function[1083]:0x2b074f)
    at ruffle_core::avm1::function::Executable::exec::hdfddf9496055cb0e (wasm://wasm/0179a60e:wasm-function[358]:0xe4f54)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h15e49bfbb24125b9 (wasm://wasm/0179a60e:wasm-function[852]:0x25da90)
```

# Player Info
Allows script access: false
Renderer: WebGL
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://sh--9pfs.repl.co/g/6f2e0289/electric-man-2
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14695.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-16
Channel: nightly
Built: 2022-09-16T00:18:50.669Z
Commit: c63f915ae21ab99df8f923c9628c67ba93517e1a
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment] 2022-09-16 19:04
Duplicate of #4932

**Closed by n0samu** 2022-09-16 19:04 UTC
Labels: duplicate, error-report
