### ISSUE TITLE
Error on https://www.sticksports.com/web-games/game/stick-cricket/world-domination/

### ISSUE THREAD

**Issue by waleedadnan670** [ruffle-rs/ruffle#13090] opened 2023-09-07 01:17 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.7e479ef3f72b52693aec.js:1:51650)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b6e7c02fb5a9114 (wasm://wasm/03077b4e:wasm-function[9271]:0x91640b)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/03077b4e:wasm-function[6048]:0x815988)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/03077b4e:wasm-function[9113]:0x911b51)
    at core::ops::function::Fn::call::h4c603b2b614ebd5a (wasm://wasm/03077b4e:wasm-function[6250]:0x82197c)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h1b8a583e295cf94c (wasm://wasm/03077b4e:wasm-function[4889]:0x781c50)
    at <T as wgpu::context::DynContext>::device_create_buffer::h24832c7c53b35d24 (wasm://wasm/03077b4e:wasm-function[6959]:0x86ec84)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hdc3aa924a8914d3d (wasm://wasm/03077b4e:wasm-function[1540]:0x468696)
    at core::cell::once::OnceCell<T>::get_or_try_init::hccfc4b19f0b271d8 (wasm://wasm/03077b4e:wasm-function[4070]:0x70f829)
    at ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::h86ceb99f08bb1bfc (wasm://wasm/03077b4e:wasm-function[1416]:0x435a65)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://www.sticksports.com/web-games/flash/game/sc_wd_20120323.swf
Param bgcolor: #000000
Param allowScriptAccess: always
Param flashvars: fv_phpDir=https://www.sticksports.com/web-games/flash/php/cricket/&fv_gameRoot=https://www.sticksports.com/web-games/flash/game/&fv_engineFile=sc_engine_20120332.swf&fv_stadiumFile=sydney_20120220&fv_gameID=sc_wd&fv_matchID=&fv_userID=45003924&fv_lastPlayed=&fv_region=pk
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.sticksports.com/web-games/game/stick-cricket/world-domination/
SWF URL: https://www.sticksports.com/web-games/flash/game/sc_wd_20120323.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-07
Channel: nightly
Built: 2023-09-07T00:20:20.983Z
Commit: 9c7eb90d69fc228b631fccee50045365313f1f9f
Is extension: false

# Metadata
width: 728
height: 440
frameRate: 48
numFrames: 75
swfVersion: 8
backgroundColor: #666666
isActionScript3: false
uncompressedLength: 1063246

**Comment by Dinnerbone** [comment] 2024-07-12 22:04
Duplicate of #12397

**Closed by Dinnerbone** 2024-07-12 22:04 UTC
Labels: duplicate, error-report, wgpu-oom
