### ISSUE TITLE
Endless War 3 - All AI Shoot Backwards

### ISSUE THREAD

**Issue by BlueMaxima** [ruffle-rs/ruffle#1418] opened 2020-10-28 08:46 UTC
![image](https://user-images.githubusercontent.com/35991016/97412899-4460ab80-1956-11eb-8a5a-c98272607d1c.png)

**Comment by torokati44** [comment] 2021-06-09 00:47
I can't reproduce this with the latest nightly (2021-06-09).
There is a different bug though - I can't click "OK" after winning a level.

**Comment by Sonikkustar** [comment] 2023-12-15 23:25
Both issues from @BlueMaxima and @torokati44 appear to be fixed as of nightly-2023-12-15.

![image](https://github.com/ruffle-rs/ruffle/assets/22226938/88064f40-bfcc-42ec-9b25-6bd7f37aea85)

A bit of a tangent, but a funny glitch happens when you right-click the window and click on Play. The game seems to try and load the enemies from every level in the game all at once. Probably a different issue not related to this game though:

![image](https://github.com/ruffle-rs/ruffle/assets/22226938/b4fe4227-3bb8-4a95-90b3-502cbbc214a2)

**Closed** 2023-12-15 23:31 UTC
