### ISSUE TITLE
Error on https://www.langenthaler.com/rufflelight/001/Natoshopaa2222Nmobile-1.php

### ISSUE THREAD

**Issue by aluetz** [ruffle-rs/ruffle#11709] opened 2023-06-24 08:31 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/display_object/avm1_button.rs:237:28
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/display_object/avm1_button.rs:237:28
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.4aca22fbd1367f86fc4e.js:1:51428)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02cafe5a:wasm-function[8726]:0x84d372)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02cafe5a:wasm-function[5668]:0x766dff)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02cafe5a:wasm-function[8589]:0x848f1b)
    at core::result::unwrap_failed::he0ddc269083098af (wasm://wasm/02cafe5a:wasm-function[6641]:0x7b8de0)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::invalidate_cached_bitmap::h62dbfe63286afd74 (wasm://wasm/02cafe5a:wasm-function[856]:0x2f2e16)
    at ruffle_core::display_object::edit_text::EditText::redraw_border::h1bb074a4aaa8e65f (wasm://wasm/02cafe5a:wasm-function[2695]:0x5c097a)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::set_matrix::h135ca5dd79fb6b53 (wasm://wasm/02cafe5a:wasm-function[1435]:0x427953)
    at ruffle_core::display_object::avm1_button::Avm1Button::set_state::h2260407e4a3763e4 (wasm://wasm/02cafe5a:wasm-function[844]:0x2e3e58)
    at <ruffle_core::display_object::interactive::InteractiveObject as ruffle_core::display_object::interactive::TInteractiveObject>::handle_clip_event::h0498d37ba06cef94 (wasm://wasm/02cafe5a:wasm-function[2092]:0x51655d)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.langenthaler.com/rufflelight/001/Natoshopaa2222Nmobile-1.php
SWF URL: https://www.langenthaler.com/rufflelight/001/natoshop6000aa2222-1.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-24
Channel: nightly
Built: 2023-06-24T00:25:29.354Z
Commit: 6d77ff1fc41aa34848188aa79ddb8c283671df4a
Is extension: false

# Metadata
width: 750
height: 1100
frameRate: 30
numFrames: 2011
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 8959169

**Comment by n0samu** [comment] 2023-06-24 08:32
Duplicate of #11706

**Comment by aluetz** [comment] 2023-06-24 08:32
Im sorry, I have had a new website with cross URLs. I have them removed. And now, all should be correct with no cross URL. Thanks a lot to correct my domaines as secure:

www.rufflesafe.com
www.ruffleshop.de
www.ruffle.zip        ( is just corrected and has had wrong URL from php to swf  with implemented jpg 800 x 450 pixels 6000 items
www.ruffehops.com
www.ruffleapps.com
www.rufflelight.com
www.rufflesafe.de
www.langenthaler.com
www.langenthaler.ch
www.schweizerinnen.ch
www. schlossthunstetten.ch
www.kirchelangenthal.ch
www.stadtlangenthal.ch

My father and I are very happy to set alle back to secure. Thanks a lot to the GitHub Teams.
Andreas Lützenberger
support@a4whosting.ch

**Closed by n0samu** 2023-06-24 08:32 UTC
Labels: duplicate, error-report
