### ISSUE TITLE
Error on https://www.gamesflow.com/jeux.php

### ISSUE THREAD

**Issue by Drixhen816** [ruffle-rs/ruffle#7318] opened 2022-07-01 00:20 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.gamesflow.com/include/p_jeux/ruffle/core.ruffle.f5e16f52204d9499c76d.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::h8cc59a0b8a1b03e2 (https://www.gamesflow.com/include/p_jeux/ruffle/6eb258805834d3c235ef.wasm:wasm-function[1023]:0x2c3c5c)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://www.gamesflow.com/include/p_jeux/ruffle/6eb258805834d3c235ef.wasm:wasm-function[1457]:0x330fa0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haa76f48d1b3c2435 (https://www.gamesflow.com/include/p_jeux/ruffle/6eb258805834d3c235ef.wasm:wasm-function[4908]:0x4827fd)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://www.gamesflow.com/include/p_jeux/ruffle/6eb258805834d3c235ef.wasm:wasm-function[3229]:0x42594c)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://www.gamesflow.com/include/p_jeux/ruffle/6eb258805834d3c235ef.wasm:wasm-function[5191]:0x48e8ba)
    at core::result::unwrap_failed::hd5a60243cf946632 (https://www.gamesflow.com/include/p_jeux/ruffle/6eb258805834d3c235ef.wasm:wasm-function[4133]:0x46a34f)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h151e83d5ba38548e (https://www.gamesflow.com/include/p_jeux/ruffle/6eb258805834d3c235ef.wasm:wasm-function[738]:0x23ea43)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::ha2a1f4d487d61a29 (https://www.gamesflow.com/include/p_jeux/ruffle/6eb258805834d3c235ef.wasm:wasm-function[3237]:0x42687e)
    at ruffle_core::drawing::Drawing::render::haf55c1d0bfe64a08 (https://www.gamesflow.com/include/p_jeux/ruffle/6eb258805834d3c235ef.wasm:wasm-function[660]:0x219863)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.gamesflow.com/jeux.php?id=2000811
SWF URL: https://www.gamesflow.com/jeux/4dceb19fea291.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14695.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-18
Channel: nightly
Built: 2022-03-18T00:17:54.702Z
Commit: e5b6e8c8b7198cd016bb0f37a683718f30a3bcac
Is extension: false

**Comment by n0samu** [comment] 2022-07-01 04:43
Duplicate of #7169

**Closed by n0samu** 2022-07-01 04:43 UTC
Labels: duplicate, error-report
