### ISSUE TITLE
Error on https://www.twoplayergames.org/gameframe/gun-mayhem

### ISSUE THREAD

**Issue by MisterDoenerHD** [ruffle-rs/ruffle#6801] opened 2022-04-25 07:06 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.17.10/src/fill.rs:1942:74
Error stack:
```
@https://www.twoplayergames.org/dist/build/ruffle/ruffle.667efded.js:1:7054
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h5c607ed08f988e53]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hf1b92ab8c222362b]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h3097032c631d0165]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::ha223473efd20893e]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hca0bee0b11468063]@[wasm code]
<?>.wasm-function[core::panicking::panic::hb05521048dcb55f3]@[wasm code]
<?>.wasm-function[core::slice::sort::shift_tail::h769160bae463f1ae]@[wasm code]
<?>.wasm-function[core::slice::sort::recurse::h0f8cb89a601fd2f6]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::process_events::h7087ba3ef76c77fa]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_impl::h7f30dabcc392136e]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_path::h3de3f213ded80c9c]@[wasm code]
<?>.wasm-function[ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hf1750bd21578be22]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::hfb8ab905473651dd]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::ha12c357ff04eb7bc]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h8a5ff362cfe8b452]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h07de25875a1be39d]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc6415900609d5a7b]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7c60523d12ffb915]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::hb072da29a842b4fa]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h68ad5c03d43a71a4]@[wasm code]
wasm-stub@[native code]
F@https://www.twoplayergames.org/dist/build/ruffle/ruffle.667efded.js:1:4016
a@https://www.twoplayergames.org/dist/build/ruffle/ruffle.667efded.js:1:2541
promiseReactionJob@[native code]
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.twoplayergames.org/gameframe/gun-mayhem
SWF URL: https://files.twoplayergames.org/files/games/o3/Gun_Mayhem.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-01
Channel: nightly
Built: 2021-11-01T00:13:10.095Z
Commit: b0b1c79143a80f1bb457833bdb78139944464d9c
Is extension: false

**Comment by n0samu** [comment] 2024-06-23 23:40
Likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:40 UTC
Labels: error-report
