### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by KolosTV** [ruffle-rs/ruffle#4954] opened 2021-07-30 21:17 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:655:48
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', render/webgl/src/lib.rs:655:48
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1627482820:1:7451)
    at std::sync::once::Once::call_once::{{closure}}::hffa00ec013760742 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc0dca71c99df687a576.wasm:wasm-function[1023]:0x2899fb)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc0dca71c99df687a576.wasm:wasm-function[988]:0x2756ea)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h66812a3cc7a9c482 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc0dca71c99df687a576.wasm:wasm-function[3931]:0x424831)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc0dca71c99df687a576.wasm:wasm-function[3072]:0x3d3e4c)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc0dca71c99df687a576.wasm:wasm-function[4147]:0x42a77b)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc0dca71c99df687a576.wasm:wasm-function[4301]:0x431611)
    at core::panicking::panic::h5bfdfaa3db9a4b4a (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc0dca71c99df687a576.wasm:wasm-function[4086]:0x427bdc)
    at ruffle_render_webgl::WebGlRenderBackend::register_bitmap::hf6bcd9860ff84dae (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc0dca71c99df687a576.wasm:wasm-function[1333]:0x2dd0af)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_raw::had1bd0a072a59e10 (https://uploads.ungrounded.net/ruffle_wrapper/lib/bc0dca71c99df687a576.wasm:wasm-function[3297]:0x3e6074)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1627482820%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261046865ebc64%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36 OPR/77.0.4054.275
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-28
Channel: nightly
Built: 2021-07-28T00:12:40.544Z
Commit: 508f541ada24a626fddd0691d52ef57af8957bbe

**Comment by torokati44** [comment] 2021-08-03 19:39
Duplicate of #4833. Different Ruffle build, but the stack trace is essentially the same.

**Closed by torokati44** 2021-08-03 19:39 UTC
