### ISSUE TITLE
Teen Titans Go! Grab that Grub

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#15922] opened 2024-04-08 08:29 UTC
### Describe the bug

The game is not loading.

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xcb9078 }) to handler FunctionObject(FunctionObject { ptr: 0xbab1e8, name: Ok("org.flixel::FlxGame/create()") }) : RustError("Ruffle does not support sparse arrays yet.")`

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x426c450 }) to handler FunctionObject(FunctionObject { ptr: 0xbab1e8, name: Ok("org.flixel::FlxGame/create()") }) : ArgumentError: Error #2025: The supplied DisplayObject must be a child of the caller.`

### Expected behavior

To load correctly.

### Content Location

[Ruffle](https://www.getgames.io/games/ruffle/?swf=cn/teentitans/grab_that_grub.swf&params=&name=Teen%20Titans%20Go!%20Grab%20that%20Grub)

[Flash](https://www.havana24.net/?pag=play&sub=teen_titans_go_grab_that_grub)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

**Comment by Lord-McSweeney** [comment] 2024-04-08 12:54
Duplicate of #15421

**Closed by Lord-McSweeney** 2024-04-08 12:54 UTC
Labels: bug
