### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by danuvita** [ruffle-rs/ruffle#4059] opened 2021-04-19 18:24 UTC
Apparently, there's trouble loading a chunk

**Comment by torokati44** [comment] 2021-04-19 18:27
Please provide more details.

**Comment by torokati44** [comment] 2021-04-21 10:15
Most likely the same issue as these: https://github.com/ruffle-rs/ruffle/issues/2567 https://github.com/ruffle-rs/ruffle/issues/3456 https://github.com/ruffle-rs/ruffle/issues/3284 https://github.com/ruffle-rs/ruffle/issues/2463
And if so, it's caused by how Ruffle is deployed on the site you were visiting.

**Comment by relrelb** [comment] 2022-01-07 14:17
Closing due to lack of information.

**Closed by relrelb** 2022-01-07 14:17 UTC
