### ISSUE TITLE
Error on https://shsgames.github.io/g/6f2e0289/electric-man-2

### ISSUE THREAD

**Issue by jakestarcast** [ruffle-rs/ruffle#5612] opened 2021-11-07 00:06 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://shsgames.github.io/ruffle/ruffle.js:1:6803)
    at std::sync::once::Once::call_once::{{closure}}::hbc3e76004faf5843 (https://shsgames.github.io/ruffle/ad53e8217f52fd8fe10c.wasm:wasm-function[1028]:0x2c9dca)
    at std::sync::once::Once::call_inner::hc44ad7f626385660 (https://shsgames.github.io/ruffle/ad53e8217f52fd8fe10c.wasm:wasm-function[1291]:0x327471)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h23da166c23bc7e1a (https://shsgames.github.io/ruffle/ad53e8217f52fd8fe10c.wasm:wasm-function[4386]:0x4bdbac)
    at std::panicking::rust_panic_with_hook::he9bfe03219d715ba (https://shsgames.github.io/ruffle/ad53e8217f52fd8fe10c.wasm:wasm-function[3225]:0x456d2e)
    at rust_begin_unwind (https://shsgames.github.io/ruffle/ad53e8217f52fd8fe10c.wasm:wasm-function[4617]:0x4c3c2b)
    at core::panicking::panic_fmt::hbf21a3d4bbb82bf8 (https://shsgames.github.io/ruffle/ad53e8217f52fd8fe10c.wasm:wasm-function[4811]:0x4cb339)
    at core::panicking::panic::h2fd385a887c8bf13 (https://shsgames.github.io/ruffle/ad53e8217f52fd8fe10c.wasm:wasm-function[4550]:0x4c0f16)
    at core::ops::function::FnOnce::call_once::h8686fa0177bbb676 (https://shsgames.github.io/ruffle/ad53e8217f52fd8fe10c.wasm:wasm-function[1005]:0x2c0e95)
    at ruffle_core::avm1::function::Executable::exec::h67427effb9e1e718 (https://shsgames.github.io/ruffle/ad53e8217f52fd8fe10c.wasm:wasm-function[424]:0x1285b6)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://shsgames.github.io/g/6f2e0289/electric-man-2
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14150.64.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.104 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-15
Channel: nightly
Built: 2021-10-15T00:11:11.011Z
Commit: c5ad8e76ee805f62ffa4594aee5ec15087d573d3
Is extension: false

**Comment by relrelb** [comment] 2021-11-07 05:50
Duplicate of #4932.

**Closed by relrelb** 2021-11-07 05:50 UTC
Labels: error-report
