### ISSUE TITLE
Error on http://apps.encodigo.com/apps/?id=3

### ISSUE THREAD

**Issue by Leire-as** [ruffle-rs/ruffle#2749] opened 2021-01-22 11:01 UTC
# Error Info
Error name: TypeError
Error message: Cannot read property 'toString' of undefined
Error stack:
```
TypeError: Cannot read property 'toString' of undefined
    at Object.ns.IsCorsRequest (http://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=N8UHgA17W8hM0wEdcbP_Tp4mmAwquAmp5Jmfa_yCZ266nCNmj1lwXUaGxti0chbEmlowy8MLqJnBB2pZllk8EQ:224:45)
    at window.fetch (http://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=N8UHgA17W8hM0wEdcbP_Tp4mmAwquAmp5Jmfa_yCZ266nCNmj1lwXUaGxti0chbEmlowy8MLqJnBB2pZllk8EQ:3968:34)
    at <anonymous>:3:67938
    at Array.forEach (<anonymous>)
    at Object.Si.f.wasm (<anonymous>:3:67865)
    at <anonymous>:3:35558
    at Array.reduce (<anonymous>)
    at Function.Si.e (<anonymous>:3:35535)
    at o (<anonymous>:3:2085)
    at o.next (<anonymous>)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /resources/swf/apps/preload/preload.swf?cacheBuster=1611313265520
Param allowFullScreenInteractive: true
Param allowFullScreen: true
Param allowScriptAccess: sameDomain
Param AllowNetworking: all
Param flashvars: archivo=/media/apps/3/app.swf?cacheBuster=1611313265520&language=eus&ruta_resources=/media/apps/3/resources/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute 7: undefined
Attribute 8: undefined
Attribute 9: undefined
Attribute 10: undefined
Attribute 11: undefined
Attribute 12: undefined

# Page Info
Page URL: http://apps.encodigo.com/apps/?id=3

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-16
Channel: nightly
Built: 2021-01-16T01:09:33.302Z
Commit: 9df7facdb8d37a5d007a13c25efcc176ed4675e0

**Comment by n0samu** [comment] 2022-10-04 06:56
Duplicate of #2468

**Closed by n0samu** 2022-10-04 06:56 UTC
Labels: duplicate, web, error-report
