### ISSUE TITLE
Error on https://armorgames.com/play/4480/frontier

### ISSUE THREAD

**Issue by Mntako** [ruffle-rs/ruffle#14400] opened 2023-12-15 10:37 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/display_object/container.rs:942:22:
called `Option::unwrap()` on a `None` value
Error stack:
```
Error: panicked at core/src/display_object/container.rs:942:22:
called `Option::unwrap()` on a `None` value
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://agi.armorgames.com/ruffle/core.ruffle.9fec9a1b17acdaaddfc5.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b09d9124792ee2e (wasm://wasm/0340e2b2:wasm-function[9968]:0x9d3407)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0340e2b2:wasm-function[6530]:0x8d3507)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0340e2b2:wasm-function[9765]:0x9ce140)
    at core::panicking::panic::h0f0c05b20da93dd7 (wasm://wasm/0340e2b2:wasm-function[9430]:0x9c0013)
    at core::ops::function::FnOnce::call_once::h84d4867e648f1f92 (wasm://wasm/0340e2b2:wasm-function[1022]:0x39a8f1)
    at ruffle_core::avm1::function::Executable::exec::h9eed79833c5aa4fe (wasm://wasm/0340e2b2:wasm-function[712]:0x2122f5)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h076224b1f124c4aa (wasm://wasm/0340e2b2:wasm-function[3109]:0x6e78c8)
    at ruffle_core::avm1::activation::Activation::run_actions::hd5ba556330326e7b (wasm://wasm/0340e2b2:wasm-function[567]:0x24e2b)
    at ruffle_core::avm1::function::Executable::exec::h9eed79833c5aa4fe (wasm://wasm/0340e2b2:wasm-function[712]:0x212182)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon RX 7900 XTX (0x0000744C) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://armorgames.com/play/4480/frontier
SWF URL: https://cache.armorgames.com/files/games/frontier-4480.swf?v=1373587522

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-13
Channel: nightly
Built: 2023-11-13T00:14:23.579Z
Commit: 11c5a68452e53858871a0c3567a3c8368d6596be
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 40
swfVersion: 10
backgroundColor: #003300
isActionScript3: false
uncompressedLength: 6201007

**Comment by Lord-McSweeney** [comment] 2023-12-15 14:59
Duplicate of #13577

**Closed by Lord-McSweeney** 2023-12-15 14:59 UTC
Labels: error-report
