### ISSUE TITLE
Angry Birds Space: problem on level select screen and lag

### ISSUE THREAD

**Issue by swaggybaguette** [ruffle-rs/ruffle#12519] opened 2023-08-03 07:19 UTC
### Describe the bug

On the level select screen all of the stars attached to the levels fall, and the game can get very laggy to the point that the game visually starts messing up, this is noticeable in level 3 and later levels

### Expected behavior

The game runs smoothly without these issues

### Affected platform

Online demo

### Operating system

Manjaro

### Additional information

This is the swf https://cdn.discordapp.com/attachments/1055372256429219844/1136558085293490236/angry-birds-space.swf

**Comment by Lord-McSweeney** [comment] 2023-08-03 10:34
Only after playing the first level did the stars on the level select screen fall (at least for me).

This stub is mentioned, but it doesn't seem too important: `DisplayObjectContainer.getObjectsUnderPoint()`

**Comment by n0samu** [comment] 2023-12-02 05:20
The stub warning was related. Same root cause as #12365. Fixed by #11970!

**Closed by n0samu** 2023-12-02 05:20 UTC
Labels: bug, avm2, performance
