### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1613144486%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2203720163.563b31977a6206afcc924b62d4ff5a114d1e54a3deaa65%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226026a77914d6e%22%2C%22NewgroundsAPI_SessionID%22%3A%22WFtDSrUgv8aGfqECNthM8378329f3a90fbe68cb30328cb365339a2185d09rW1L%22%2C%22NewgroundsAPI_UserName%22%3A%22cyanscarf%22%2C%22NewgroundsAPI_UserID%22%3A8627521%2C%22ng_username%22%3A%22cyanscarf%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D

### ISSUE THREAD

**Issue by BenisTheGreat** [ruffle-rs/ruffle#3227] opened 2021-02-12 17:16 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:781:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:781:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1613144486:1:6799)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[1327]:0x26b533)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[1603]:0x29e7b9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[4637]:0x381cb3)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[3509]:0x3576e4)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[4145]:0x375270)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[4983]:0x387384)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[4868]:0x385c81)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[4984]:0x3873ba)
    at core::panicking::panic::h8e74859c8f9988ca (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[4799]:0x384acb)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1613144486%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2203720163.563b31977a6206afcc924b62d4ff5a114d1e54a3deaa65%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226026a77914d6e%22%2C%22NewgroundsAPI_SessionID%22%3A%22WFtDSrUgv8aGfqECNthM8378329f3a90fbe68cb30328cb365339a2185d09rW1L%22%2C%22NewgroundsAPI_UserName%22%3A%22cyanscarf%22%2C%22NewgroundsAPI_UserID%22%3A8627521%2C%22ng_username%22%3A%22cyanscarf%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-12
Channel: nightly
Built: 2021-02-12T00:17:25.708Z
Commit: da86f7fc5afbe93c8b378366c550a0622f59d5b6

**Comment by relrelb** [comment] 2021-04-03 18:37
Duplicate of #3756.

**Closed by relrelb** 2021-04-03 18:37 UTC
