### ISSUE TITLE
Error on https://www.gameflare.com/embed/can-your-pet/

### ISSUE THREAD

**Issue by mayrinluvstabby** [ruffle-rs/ruffle#7992] opened 2022-09-16 06:28 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/array.rs:61:37

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://www.gameflare.com/embed/can-your-pet/
SWF URL: https://data.gameflare.com/games/5432/VYxeLzwlUs5C8b.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-13
Channel: nightly
Built: 2022-09-13T00:14:48.844Z
Commit: bff0855435987bb9f19f48e120ad7cbb77f9d924
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 45
numFrames: 1734
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 1867130

**Comment by n0samu** [comment] 2022-09-16 06:41
Duplicate of #7950

**Closed by n0samu** 2022-09-16 06:41 UTC
Labels: duplicate, error-report
