### ISSUE TITLE
Error on chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/player.html

### ISSUE THREAD

**Issue by RandomSteve** [ruffle-rs/ruffle#5352] opened 2021-09-22 23:44 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/dist/player.js:1:6803)
    at std::sync::once::Once::call_once::{{closure}}::hc3bcbfc24932baf7 (chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/dist/519bcd15a39b51540f93.wasm:wasm-function[962]:0x2747c9)
    at std::sync::once::Once::call_inner::hc44ad7f626385660 (chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/dist/519bcd15a39b51540f93.wasm:wasm-function[1209]:0x2c85aa)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h80923a9f85d6269c (chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/dist/519bcd15a39b51540f93.wasm:wasm-function[4176]:0x457902)
    at std::panicking::rust_panic_with_hook::he9bfe03219d715ba (chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/dist/519bcd15a39b51540f93.wasm:wasm-function[3021]:0x3f1ab8)
    at rust_begin_unwind (chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/dist/519bcd15a39b51540f93.wasm:wasm-function[4395]:0x45d464)
    at core::panicking::panic_fmt::hbf21a3d4bbb82bf8 (chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/dist/519bcd15a39b51540f93.wasm:wasm-function[4578]:0x464a19)
    at core::panicking::panic::h2fd385a887c8bf13 (chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/dist/519bcd15a39b51540f93.wasm:wasm-function[4332]:0x45aa51)
    at core::ops::function::FnOnce::call_once::hd74add08a66e90b4 (chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/dist/519bcd15a39b51540f93.wasm:wasm-function[940]:0x26a15f)
    at ruffle_core::avm1::function::Executable::exec::h65ee8181ab74fba8 (chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/dist/519bcd15a39b51540f93.wasm:wasm-function[384]:0xf29cd)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://ohcdpnedcdaojmkenelafhgffglegdpf/player.html?url=http://farm.stickpage.com/electricman2game.swf
SWF URL: http://farm.stickpage.com/electricman2game.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-09-22
Channel: nightly
Built: 2021-09-22T00:31:47.798Z
Commit: 42275f43f3a410c572f698aa8577c63c0f06159f
Is extension: true

**Comment by relrelb** [comment] 2021-10-15 08:02
Duplicate of #4932.

**Closed by relrelb** 2021-10-15 08:02 UTC
