### ISSUE TITLE
Error on https://games.crazygames.com/en_US/chibi-knight/index.html

### ISSUE THREAD

**Issue by Tera-Hornet** [ruffle-rs/ruffle#5786] opened 2021-12-02 01:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:858:18

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.crazygames.com/en_US/chibi-knight/index.html
SWF URL: https://files.crazygames.com/chibiknight.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14150.87.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.124 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-10
Channel: nightly
Built: 2021-11-10T00:14:29.631Z
Commit: 51af0f708f2db85188ffcf7b744eb7f7cb76fd79
Is extension: false

**Comment by Poopooracoocoo** [comment] 2021-12-02 03:02
Duplicate of #3756

**Closed by Poopooracoocoo** 2021-12-02 03:02 UTC
Labels: duplicate
