### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by xaviermythblade** [ruffle-rs/ruffle#3795] opened 2021-03-25 17:48 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1616674496:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://uploads.ungrounded.net/ruffle_wrapper/lib/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[1483]:0x2c9b25)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[1771]:0x2ff7df)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://uploads.ungrounded.net/ruffle_wrapper/lib/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[5275]:0x40bea6)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://uploads.ungrounded.net/ruffle_wrapper/lib/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[4041]:0x3dce1e)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://uploads.ungrounded.net/ruffle_wrapper/lib/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[4761]:0x3fe968)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://uploads.ungrounded.net/ruffle_wrapper/lib/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[5648]:0x411c18)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[5522]:0x4102c3)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://uploads.ungrounded.net/ruffle_wrapper/lib/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[5649]:0x411c4e)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h6c9c894eccc08131 (https://uploads.ungrounded.net/ruffle_wrapper/lib/44a34a452a04b301ca6e4923f6f0828e.wasm:wasm-function[1495]:0x2cc587)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1616674496%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F782000%2F782567_arcane-maiden-v1-4-compre.swf%3F1615329844%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2263479153.4fed11f6bcc506150259b5c2d5689db29cd15a3206ea3d%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22605cccaca1598%22%2C%22NewgroundsAPI_SessionID%22%3A%22NVX89OhKUdmODm1osauEec98572297f00c5db0373d8d8658eea83b7ee187Idnm%22%2C%22NewgroundsAPI_UserName%22%3A%22TanjiroSenpai%22%2C%22NewgroundsAPI_UserID%22%3A8849835%2C%22ng_username%22%3A%22TanjiroSenpai%22%7D%2C%22width%22%3A1024%2C%22height%22%3A576%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F782000%2Fflash_782567_card.png%3Ff1614452781%22%7D
SWF URL: https://uploads.ungrounded.net/782000/782567_arcane-maiden-v1-4-compre.swf?1615329844

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS aarch64 13505.63.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-25
Channel: nightly
Built: 2021-03-25T00:36:18.574Z
Commit: f96a41403697d362aa051d0977873489269300b3

**Comment by torokati44** [comment] 2021-06-09 00:57
Duplicate of #3695.

**Closed by torokati44** 2021-06-09 00:57 UTC
