### ISSUE TITLE
Error on https://simple-education.xyz/swf.html

### ISSUE THREAD

**Issue by d0ntask0** [ruffle-rs/ruffle#6821] opened 2022-04-28 19:08 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.42226413fcddb0ba52ab.js:1:7708)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.27/ae5cb174a07ba7100ab3.wasm:wasm-function[1008]:0x2a52de)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.27/ae5cb174a07ba7100ab3.wasm:wasm-function[1446]:0x31c029)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.27/ae5cb174a07ba7100ab3.wasm:wasm-function[4922]:0x4742a3)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.27/ae5cb174a07ba7100ab3.wasm:wasm-function[3242]:0x416be4)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.27/ae5cb174a07ba7100ab3.wasm:wasm-function[5007]:0x47822b)
    at core::panicking::panic::he88f1b1582b09c8c (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.27/ae5cb174a07ba7100ab3.wasm:wasm-function[4920]:0x473e36)
    at core::ops::function::FnOnce::call_once::hea116a8eeeb59311 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.27/ae5cb174a07ba7100ab3.wasm:wasm-function[1089]:0x2be097)
    at ruffle_core::avm1::function::Executable::exec::h0a1a3c56ef393e7a (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.27/ae5cb174a07ba7100ab3.wasm:wasm-function[391]:0x12c992)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf21230a28d8729f3 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.4.27/ae5cb174a07ba7100ab3.wasm:wasm-function[371]:0xe6836)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://simple-education.xyz/swf.html?notebook=electricman2
SWF URL: https://simple-education.xyz/swffiles/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14268.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.207 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-27
Channel: nightly
Built: 2022-04-27T00:15:21.542Z
Commit: 4a9d6867baf98483ef886119808d4762a606fdfa
Is extension: false

**Comment by relrelb** [comment] 2022-04-29 20:01
Duplicate of #4932.

**Closed by relrelb** 2022-04-29 20:01 UTC
Labels: error-report
