### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by csorax100** [ruffle-rs/ruffle#9350] opened 2023-01-30 03:07 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:756:32
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:756:32
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.bcc051e635a9e70a739a.js:1:5353)
    at std::sync::once::Once::call_once::{{closure}}::h7e6b96cea392c96b (wasm://wasm/027a46de:wasm-function[1590]:0x415453)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/027a46de:wasm-function[1995]:0x4a9f65)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd937bf3f89ff4f2e (wasm://wasm/027a46de:wasm-function[7150]:0x760542)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/027a46de:wasm-function[5077]:0x6bcf17)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/027a46de:wasm-function[7474]:0x76f008)
    at core::panicking::panic::hff08c7cf90edd9fe (wasm://wasm/027a46de:wasm-function[7191]:0x762498)
    at core::ops::function::FnOnce::call_once::hd4ce787ae042843c (wasm://wasm/027a46de:wasm-function[794]:0x2a39aa)
    at ruffle_core::avm1::function::Executable::exec::he9df1cdfcd8cc66c (wasm://wasm/027a46de:wasm-function[577]:0x1ac6b0)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h3812f1a332a42cbd (wasm://wasm/027a46de:wasm-function[1357]:0x3ca359)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1674747793%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F484000%2F484931_peeps.swf%3F1509024282%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2223610029.51fc5d39e27d36eebe2e76984f807ffd71547bb19c003e%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2263d732f1bf167%22%2C%22NewgroundsAPI_SessionID%22%3A%22DFsPBmnuH6eM1cjxASbm6eb35e5bd901ba993dad6f3768679470375465ccWrXN%22%2C%22NewgroundsAPI_UserName%22%3A%22Rax100%22%2C%22NewgroundsAPI_UserID%22%3A4467429%2C%22ng_username%22%3A%22Rax100%22%7D%2C%22width%22%3A640%2C%22height%22%3A450%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F484000%2Fflash_484931_card.png%3Ff1609851325%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/484000/484931_peeps.swf?1509024282

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-26
Channel: nightly
Built: 2023-01-26T00:19:01.046Z
Commit: 56fd9adbf91c01440fae7dc1d2024aa297938b43
Is extension: false

# Metadata
width: 640
height: 450
frameRate: 35
numFrames: 19
swfVersion: 9
backgroundColor: #999999
isActionScript3: false
uncompressedLength: 12314677

**Comment by n0samu** [comment] 2023-02-06 08:35
Duplicate of #8875

**Closed by n0samu** 2023-02-06 08:35 UTC
Labels: duplicate, error-report
