### ISSUE TITLE
Error on https://clonetrooper134579474.github.io/Scratch.html

### ISSUE THREAD

**Issue by clonetrooper134579474** [ruffle-rs/ruffle#18970] opened 2024-12-14 14:57 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/shader_data.rs:72:10:
Failed to compile PixelBender shader: Unimplemented("compile_pixelbender_shader")
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/shader_data.rs:72:10:
Failed to compile PixelBender shader: Unimplemented("compile_pixelbender_shader")
    at imports.wbg.__wbg_new_4d81617a04bc1b5b (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:2877:21)
    at ruffle_web.wasm.js_sys::Error::new::h5021eff635514cb9 (wasm://wasm/ruffle_web.wasm-031ad3f6:wasm-function[12842]:0x989844)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h0bb50781b11bf63c (wasm://wasm/ruffle_web.wasm-031ad3f6:wasm-function[9742]:0x9058f3)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-031ad3f6:wasm-function[6424]:0x82f14a)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-031ad3f6:wasm-function[9451]:0x8fe8a5)
    at ruffle_web.wasm.core::result::unwrap_failed::h472431483d5eea7f (wasm://wasm/ruffle_web.wasm-031ad3f6:wasm-function[7991]:0x8a9949)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::display::shader_data::init::h142acae725a95e85 (wasm://wasm/ruffle_web.wasm-031ad3f6:wasm-function[1186]:0x33c0a0)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::hb46228635fd7c4b8 (wasm://wasm/ruffle_web.wasm-031ad3f6:wasm-function[1358]:0x3bae8d)
    at ruffle_web.wasm.ruffle_core::avm2::object::TObject::call_method::hd8b52391dae27a69 (wasm://wasm/ruffle_web.wasm-031ad3f6:wasm-function[2427]:0x5889eb)
    at ruffle_web.wasm.ruffle_core::avm2::activation::Activation::run_actions::he95a10f6c9ed792a (wasm://wasm/ruffle_web.wasm-031ad3f6:wasm-function[772]:0x12caa)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at filters::FilterPack()
    at scratchplayer::ScratchSprite/setEmptyStage()
    at scratchplayer::StageArea/emptyProject()
    at Scratch()
```

# Player Info
Allows script access: true
Renderer: WebGL 1.0
Adapter Vendor: WebKit
Adapter Renderer: WebKit WebGL
Adapter Version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Surface samples: 1 x 
Surface size: 1920 x 1080

# Page Info
Page URL: https://clonetrooper134579474.github.io/Scratch.html
SWF URL: https://clonetrooper134579474.github.io/Scratchv20100725.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chromium/44 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-12-14
Channel: nightly
Built: 2024-12-14T00:06:42.324Z
Commit: 24ebd8ffaa09e36796207ef872531ac88dd3b5dd
Is extension: true

# Metadata
width: 1000
height: 630
frameRate: 24
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 446286

**Comment by Lord-McSweeney** [comment] 2024-12-14 17:03
Duplicate of https://github.com/ruffle-rs/ruffle/issues/13325

**Closed by Lord-McSweeney** 2024-12-14 17:03 UTC
Labels: error-report
