### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm

### ISSUE THREAD

**Issue by ozgurozbek** [ruffle-rs/ruffle#6788] opened 2022-04-22 23:14 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/core.ruffle.dd36e2bac3ace0621100.js:1:7708)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (http://www.freeworldgroup.com/ruffle/fd5663aa3e9b01bfddfa.wasm:wasm-function[1013]:0x2ab4e3)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (http://www.freeworldgroup.com/ruffle/fd5663aa3e9b01bfddfa.wasm:wasm-function[1443]:0x31e45a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (http://www.freeworldgroup.com/ruffle/fd5663aa3e9b01bfddfa.wasm:wasm-function[4919]:0x4781d2)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (http://www.freeworldgroup.com/ruffle/fd5663aa3e9b01bfddfa.wasm:wasm-function[3239]:0x41ae58)
    at core::panicking::panic_fmt::h5118e89563022e7e (http://www.freeworldgroup.com/ruffle/fd5663aa3e9b01bfddfa.wasm:wasm-function[5001]:0x47c088)
    at core::panicking::panic::he88f1b1582b09c8c (http://www.freeworldgroup.com/ruffle/fd5663aa3e9b01bfddfa.wasm:wasm-function[4917]:0x477d65)
    at core::ops::function::FnOnce::call_once::hea116a8eeeb59311 (http://www.freeworldgroup.com/ruffle/fd5663aa3e9b01bfddfa.wasm:wasm-function[1093]:0x2c1c8f)
    at ruffle_core::avm1::function::Executable::exec::h0a1a3c56ef393e7a (http://www.freeworldgroup.com/ruffle/fd5663aa3e9b01bfddfa.wasm:wasm-function[393]:0x132999)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf21230a28d8729f3 (http://www.freeworldgroup.com/ruffle/fd5663aa3e9b01bfddfa.wasm:wasm-function[380]:0x118928)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm
SWF URL: http://www.freeworldgroup.com/games6/electricman2/electricman2hs_fwg.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-17
Channel: nightly
Built: 2022-04-17T00:14:46.170Z
Commit: 87e85e16da58bcaa3e538d5406b5bc4218ccb417
Is extension: false

**Comment by relrelb** [comment] 2022-04-23 09:25
Duplicate of #4932.

**Closed by relrelb** 2022-04-23 09:25 UTC
Labels: error-report
