### ISSUE TITLE
Error on https://evilgames.eu/flashgames/truck-loader-2.htm

### ISSUE THREAD

**Issue by commendedfish** [ruffle-rs/ruffle#3389] opened 2021-02-23 01:45 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32390
    at r (<anonymous>:3:32880)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: ../swf/truck-loader-2.swf
Param wmode: direct
Param menu: false
Param quality: high
Param allowNetworking: internal
Param AllowScriptAccess: never
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://evilgames.eu/flashgames/truck-loader-2.htm

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.68
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-21
Channel: nightly
Built: 2021-02-21T00:20:18.629Z
Commit: eb173f06ca0918e2d2b488cd14849152db607e51

**Comment by relrelb** [comment] 2021-03-17 10:10
Duplicate of #2201.

**Closed by relrelb** 2021-03-17 10:10 UTC
Labels: duplicate
