### ISSUE TITLE
Error on https://www.gameflare.com/embed/bloons-tower-defense-5/

### ISSUE THREAD

**Issue by jfcooper13** [ruffle-rs/ruffle#11534] opened 2023-06-14 11:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA Quadro P400 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/bloons-tower-defense-5/
SWF URL: https://data.gameflare.com/games/3550/WDzRSvadTXBNOR.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-13
Channel: nightly
Built: 2023-06-13T03:01:33.033Z
Commit: c4e4eba63f5e2f7a24b598eec7fa560c241212d0
Is extension: false

# Metadata
width: 800
height: 620
frameRate: 30
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 11236157

**Comment by n0samu** [comment] 2023-06-15 19:45
Hello @jfcooper13, can you tell us what led up to this error? Did it happen at a specific point in the game?

**Comment by jfcooper13** [comment] 2023-06-15 21:17
Right while trying to open the game. It hadn't even started yet. I hit
"play" and then it tried to load and came up with that error after about 20
seconds.

**Comment by n0samu** [comment] 2023-06-15 21:31
Okay, thanks for letting us know!

**Comment by MeltaReal** [comment] 2023-06-17 17:16
BTD5 is in action script 3.0 btw so i dont think ruffle supports it yet

**Comment by jfcooper13** [comment] 2023-06-17 18:31
Ok. It had been working fine when I played the previous 3 or 4 days. It
slowed down a bit when there was a lot of movement, but it worked.

**Comment by n0samu** [comment] 2023-06-18 01:31
Would you be willing to test the SWF in a few different Ruffle versions using https://ruffle-regressions.github.io/ and let us know on what version it breaks? Here is the link to download the SWF file: https://data.gameflare.com/games/3550/WDzRSvadTXBNOR.swf

**Comment by n0samu** [comment] 2023-06-20 08:50
Okay, I've confirmed that the problem is also occurring on my end. This seems to be happening specifically in Chrome and Chromium-based browsers, and it is indeed a regression caused by #11261. And newer versions of BTD5 are not working at all (for likely the same reason) (#11642).

**Comment by MartySVK** [comment] 2023-11-07 17:08
this game was working for me a few weeks ago, no I see panic error on web:

```
0337a80a:0x2e5ac4 Uncaught RangeError: Maximum call stack size exceeded
    at ruffle_core::avm2::function::Executable::exec::hf82ffb5f0197d6d7 (0337a80a:0x2e5ac4)
    at ruffle_core::avm2::activation::Activation::super_init::hd9970b185ee827e4 (0337a80a:0x7f5ea3)
    at ruffle_core::avm2::globals::flash::display::display_object::native_instance_init::h004e04c3ca44c9b3 (0337a80a:0x7d8b93)
    at ruffle_core::avm2::function::Executable::exec::hf82ffb5f0197d6d7 (0337a80a:0x2e790e)
    at ruffle_core::avm2::activation::Activation::super_init::hd9970b185ee827e4 (0337a80a:0x7f5ea3)
    at ruffle_core::avm2::globals::flash::display::interactive_object::native_instance_init::h00cd5503fe8c2137 (0337a80a:0x94628e)
    at ruffle_core::avm2::function::Executable::exec::hf82ffb5f0197d6d7 (0337a80a:0x2e790e)
    at ruffle_core::avm2::activation::Activation::super_init::hd9970b185ee827e4 (0337a80a:0x7f5ea3)
    at ruffle_core::avm2::globals::flash::display::interactive_object::native_instance_init::h00cd5503fe8c2137 (0337a80a:0x94628e)
    at ruffle_core::avm2::function::Executable::exec::hf82ffb5f0197d6d7 (0337a80a:0x2e790e)
```

```
core.ruffle.d6ede36daa7d43d6d79e.js:1 panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false

Stack:

Error
    at H.n.wbg.__wbg_new_abda76e883ba8a5f (https://www.gameflare.com/emulators/ruffle/core.ruffle.d6ede36daa7d43d6d79e.js:1:8691)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ee9579dbb0a58f1 (wasm://wasm/0337a80a:wasm-function[9890]:0x9b49be)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0337a80a:wasm-function[6522]:0x8b702b)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0337a80a:wasm-function[9691]:0x9afb8c)
    at core::panicking::assert_failed_inner::hef8aa9140ed3b15c (wasm://wasm/0337a80a:wasm-function[4701]:0x7d7169)
    at core::panicking::assert_failed::hed21541878cc9e0e (wasm://wasm/0337a80a:wasm-function[9715]:0x9b0e5a)
    at ruffle_core::loader::Loader::movie_loader_bytes::{{closure}}::h5b35eca82df85c2c (wasm://wasm/0337a80a:wasm-function[1675]:0x4eb9b9)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h1886dc56c5ef218b (wasm://wasm/0337a80a:wasm-function[1274]:0x415320)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h9b62c1bee715c81d (wasm://wasm/0337a80a:wasm-function[4463]:0x7b7804)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9e8fd55686842caf (wasm://wasm/0337a80a:wasm-function[10670]:0x9d17c0)
```

**Comment by n0samu** [comment] 2024-06-27 17:40
This seems to be fixed now!

**Closed by n0samu** 2024-06-27 17:40 UTC
Labels: avm2, performance, regression, error-report
