### ISSUE TITLE
Ancient Jewels - Levels are bugged and ??? as text

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10651] opened 2023-04-11 14:19 UTC
### Describe the bug

https://www.newgrounds.com/portal/view/515309?emulate=flash - First you can't get the level goals after a level is played ??? Dunno if this is an encoding issue with charsets. 

Second all the levels are bugged and not loaded correctly it seems. Normally in this game you need to match symbols on 3 on tiles that got a background. The background in each level is at the top left. Normally there are many all of the level and the layout varies from level to level. So it looks like the level layouts are not correctly loaded.

Level 1 Ruffle:

![image](https://user-images.githubusercontent.com/23042167/231190119-99f48e4f-8469-4434-b403-e32aa270e5f8.png)

Level 1 Flash:

![image](https://user-images.githubusercontent.com/23042167/231192555-4c403e82-cfd1-4eb7-8f71-6322b51a51f0.png)

### Expected behavior

As above..

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by desertking** [comment] 2023-06-20 11:26
This seems to be fixed now? At least I played the first 3 levels fine. Maybe some XML update? Anyone confirms

**Comment by desertking** [comment] 2024-01-07 13:22
This worked good until some of the later updates broke it again and the background is black now...

**Comment by n0samu** [comment] 2024-01-08 09:21
Seems to be another regression caused by #13966 😭

**Comment by desertking** [comment] 2024-01-08 10:08
Seems to have caused more problems than it solved 🗡️

**Comment by n0samu** [comment] 2024-01-19 00:54
Fixed by #14801

**Closed by n0samu** 2024-01-19 00:54 UTC
Labels: bug, avm2, xml, regression
