### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/blobular.htm

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#4544] opened 2021-06-10 06:38 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/ruffle.js:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (http://www.freeworldgroup.com/ruffle/4d4fb07a0f03fbaddb3a.wasm:wasm-function[1092]:0x289023)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (http://www.freeworldgroup.com/ruffle/4d4fb07a0f03fbaddb3a.wasm:wasm-function[963]:0x25efcb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (http://www.freeworldgroup.com/ruffle/4d4fb07a0f03fbaddb3a.wasm:wasm-function[3835]:0x41e1a6)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (http://www.freeworldgroup.com/ruffle/4d4fb07a0f03fbaddb3a.wasm:wasm-function[2994]:0x3ba1e8)
    at rust_begin_unwind (http://www.freeworldgroup.com/ruffle/4d4fb07a0f03fbaddb3a.wasm:wasm-function[4042]:0x423aae)
    at core::panicking::panic_fmt::hd44f353696296fec (http://www.freeworldgroup.com/ruffle/4d4fb07a0f03fbaddb3a.wasm:wasm-function[4191]:0x42a3da)
    at core::option::expect_none_failed::hf7dab2706f1a5551 (http://www.freeworldgroup.com/ruffle/4d4fb07a0f03fbaddb3a.wasm:wasm-function[3423]:0x40c611)
    at ruffle_core::avm2::object::TObject::install_foreign_trait::h98b49cb56a66db93 (http://www.freeworldgroup.com/ruffle/4d4fb07a0f03fbaddb3a.wasm:wasm-function[323]:0x9fbe9)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::h118094ac041c9bf1 (http://www.freeworldgroup.com/ruffle/4d4fb07a0f03fbaddb3a.wasm:wasm-function[938]:0x24dd3b)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/blobular.htm
SWF URL: http://www.freeworldgroup.com/games6/blobular/blobular.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-10
Channel: nightly
Built: 2021-06-10T00:12:19.423Z
Commit: 5135b140235c3e10a808aa78ab68aed8638e95a5

**Comment by torokati44** [comment] 2021-06-15 15:44
Duplicate of #4436.

**Closed by torokati44** 2021-06-15 15:44 UTC
