### ISSUE TITLE
Error on http://www.stickmangames247.com/game/electricman2hs.html

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#6175] opened 2022-01-31 11:17 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://cmbhnckdpkphpjgdnikiiinjgmgjfgga/dist/966.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (chrome-extension://cmbhnckdpkphpjgdnikiiinjgmgjfgga/dist/f91bedccc781eba86e58.wasm:wasm-function[1019]:0x2f8ef2)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (chrome-extension://cmbhnckdpkphpjgdnikiiinjgmgjfgga/dist/f91bedccc781eba86e58.wasm:wasm-function[1157]:0x32aaba)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (chrome-extension://cmbhnckdpkphpjgdnikiiinjgmgjfgga/dist/f91bedccc781eba86e58.wasm:wasm-function[4721]:0x4d76d9)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (chrome-extension://cmbhnckdpkphpjgdnikiiinjgmgjfgga/dist/f91bedccc781eba86e58.wasm:wasm-function[3188]:0x482726)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (chrome-extension://cmbhnckdpkphpjgdnikiiinjgmgjfgga/dist/f91bedccc781eba86e58.wasm:wasm-function[4992]:0x4e3325)
    at core::panicking::panic::h35778e3c18266c93 (chrome-extension://cmbhnckdpkphpjgdnikiiinjgmgjfgga/dist/f91bedccc781eba86e58.wasm:wasm-function[4718]:0x4d7200)
    at core::ops::function::FnOnce::call_once::h63635e87c343a6bd (chrome-extension://cmbhnckdpkphpjgdnikiiinjgmgjfgga/dist/f91bedccc781eba86e58.wasm:wasm-function[1058]:0x3101d5)
    at ruffle_core::avm1::function::Executable::exec::h01bdca74588653f1 (chrome-extension://cmbhnckdpkphpjgdnikiiinjgmgjfgga/dist/f91bedccc781eba86e58.wasm:wasm-function[395]:0x146ca3)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hd2ac2ca7aecc5e6d (chrome-extension://cmbhnckdpkphpjgdnikiiinjgmgjfgga/dist/f91bedccc781eba86e58.wasm:wasm-function[381]:0x10c8d5)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.stickmangames247.com/game/electricman2hs.html
SWF URL: http://www.stickmangames247.com/games/stickman_fighting_games_19/electricman2_20100505_1251750293.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 Edg/97.0.1072.76
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-28
Channel: nightly
Built: 2022-01-28T00:18:15.390Z
Commit: c14569e3d4440038daa065c6e4099c2f326b5cb7
Is extension: true

**Comment by Poopooracoocoo** [comment] 2022-01-31 11:42
Duplicate of #4932

**Closed by Poopooracoocoo** 2022-01-31 11:42 UTC
Labels: duplicate, error-report
