### ISSUE TITLE
Error on https://www.dolldivine.com/create-a-cat.php

### ISSUE THREAD

**Issue by the-starry-night-sky** [ruffle-rs/ruffle#4071] opened 2021-04-20 17:55 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.Module doesn't parse at byte 0: modules doesn't start with '\0asm'

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.dolldivine.com/create-a-cat.php

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-06
Channel: nightly
Built: 2021-03-06T00:18:53.737Z
Commit: b68eeeae26ff9b09247bd16ab955dd1a4677af42

**Comment by torokati44** [comment] 2021-04-23 07:08
Duplicate of #4070

**Closed by torokati44** 2021-04-23 07:08 UTC
