### ISSUE TITLE
regression in gradients

### ISSUE THREAD

**Issue by AllinolCP** [ruffle-rs/ruffle#9892] opened 2023-03-07 02:04 UTC
### Describe the bug

i believe this is a regression caused by #9821
[swf used](https://github.com/ruffle-rs/ruffle/files/10904489/mtn.zip)
![image](https://user-images.githubusercontent.com/56921534/223300248-e274aed1-7f77-45e4-8188-cf9d8fe61431.png)

### Expected behavior

this is what it should look like (2023.3.6)
![image](https://user-images.githubusercontent.com/56921534/223300136-f147d65e-ea1e-4cbb-ad3b-c3d4acb0aa3f.png)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by AllinolCP** [comment] 2023-03-07 03:15
[here is another test FLA/SWF File](https://github.com/ruffle-rs/ruffle/files/10905049/regression.zip)

**Comment by shinstc** [comment] 2023-03-07 04:36
Similarly, Nanaca Crash's starting launch animation is affected; the launch animation should always start its fill from the corner but as of 3/7 is shrinking away from it. Above image is 3/7, below is a previous build (intended behavior):

![image](https://user-images.githubusercontent.com/79029874/223321557-63585042-5d4d-4140-84b1-951fab94f50a.png)

**Comment by n0samu** [comment] 2023-03-07 06:20
This is also causing the loading bar in Papa's games (#9201) to no longer fill up correctly:

https://user-images.githubusercontent.com/71368227/223337272-87ec535c-1bd2-4d85-9443-726fbc6464fb.mp4

**Comment by torokati44** [comment] 2023-03-07 21:04
This should be fixed by #9902.

**Closed** 2023-03-08 01:05 UTC
Labels: bug, rendering, regression
