### ISSUE TITLE
Error on http://www.freeworldgroup.com/games9/gameindex/tank2012.htm

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#7955] opened 2022-09-11 21:38 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:572:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:572:14
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/core.ruffle.cea989e40903bfeeffd4.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::h53c4bd4dfa98b52c (wasm://wasm/0171ba56:wasm-function[946]:0x2737c7)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/0171ba56:wasm-function[1399]:0x2f6e7a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hfdd3b2ecbbfe0d5b (wasm://wasm/0171ba56:wasm-function[4866]:0x452bd7)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/0171ba56:wasm-function[3619]:0x41bccb)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/0171ba56:wasm-function[5050]:0x45923e)
    at core::option::expect_failed::h0a5cf22f891a14fb (wasm://wasm/0171ba56:wasm-function[5743]:0x46b62e)
    at ruffle_core::display_object::stage::Stage::root_clip::hbdeebd76caabd066 (wasm://wasm/0171ba56:wasm-function[3584]:0x4180b0)
    at ruffle_web::Ruffle::tick::ha9336fb11fd4fc47 (wasm://wasm/0171ba56:wasm-function[613]:0x1d9266)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h6e88bf424f20e5d8 (wasm://wasm/0171ba56:wasm-function[5968]:0x473d55)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://www.freeworldgroup.com/games9/gameindex/tank2012.htm
SWF URL: http://www.freeworldgroup.com/games9/tank2012/ENsecure.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-11
Channel: nightly
Built: 2022-09-11T00:14:51.457Z
Commit: 8370bc792dc56a7c0ae983280ed525622f1cebf2
Is extension: false

# Metadata
width: 700
height: 600
frameRate: 30
numFrames: 2
swfVersion: 15
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 9723788

**Comment by n0samu** [comment] 2022-09-11 22:02
Duplicate of #5832

**Closed by n0samu** 2022-09-11 22:02 UTC
Labels: duplicate, error-report
