### ISSUE TITLE
Error on https://www.xpmonkey.com/feed-me-moar

### ISSUE THREAD

**Issue by resin9761** [ruffle-rs/ruffle#17203] opened 2024-07-20 22:38 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    Copy of X 4294967293..517 would end up overrunning the bounds of the Destination texture of X size 720

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    Copy of X 4294967293..517 would end up overrunning the bounds of the Destination texture of X size 720


    at n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1273091992c76771839b.js:1:79242)
    at ruffle_web.wasm.js_sys::Error::new::h5917b4042e40a5aa (wasm://wasm/ruffle_web.wasm-0338c0c6:wasm-function[12818]:0x9e6683)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hb23f6524e13658ef (wasm://wasm/ruffle_web.wasm-0338c0c6:wasm-function[9852]:0x97c533)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-0338c0c6:wasm-function[6488]:0x86efd0)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-0338c0c6:wasm-function[10251]:0x9a789d)
    at ruffle_web.wasm.core::ops::function::Fn::call::hd1b7c39003bbada4 (wasm://wasm/ruffle_web.wasm-0338c0c6:wasm-function[6782]:0x889565)
    at ruffle_web.wasm.wgpu::backend::wgpu_core::ContextWgpuCore::handle_error::h08b66b3882162c01 (wasm://wasm/ruffle_web.wasm-0338c0c6:wasm-function[2118]:0x5528c3)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::command_encoder_copy_texture_to_texture::hd1f42a6f21701bb7 (wasm://wasm/ruffle_web.wasm-0338c0c6:wasm-function[9834]:0x97aab8)
    at ruffle_web.wasm.wgpu::CommandEncoder::copy_texture_to_texture::h0d93d4bc8ea1e43d (wasm://wasm/ruffle_web.wasm-0338c0c6:wasm-function[9472]:0x9577ad)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::apply_filter::h6b533c838f2c2a26 (wasm://wasm/ruffle_web.wasm-0338c0c6:wasm-function[3685]:0x708491)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::applyFilter()
    at game.display.render::WaterRenderer/renderWater()
    at game.display.render::WaterRenderer/render()
    at engine::Screen/update()
    at engine.level::Level/update()
    at engine.level::GameLevel/update()
    at Main/update()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00009A78) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: low
Surface samples: 1
Surface size: (550, 400, 1)
Player type: Object
SWF URL: /resources/swf/feed-me-moar/feed-me-moar.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.xpmonkey.com/feed-me-moar
SWF URL: https://www.xpmonkey.com/resources/swf/feed-me-moar/feed-me-moar.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-20
Channel: nightly
Built: 2024-07-20T00:05:09.529Z
Commit: 1c8e95a061a40ccd4b2fdca30a66eb7cc2fbe12d
Is extension: false

# Metadata
width: 700
height: 525
frameRate: 30
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 7395482

**Comment by n0samu** [comment] 2024-07-21 04:43
Duplicate of #14027

**Closed by n0samu** 2024-07-21 04:43 UTC
Labels: duplicate, error-report
