### ISSUE TITLE
German umlauts are not displayed in some cases.

### ISSUE THREAD

**Issue by eruedin** [ruffle-rs/ruffle#3185] opened 2021-02-10 14:13 UTC
If I open [http://zkm-lizenzen.ch/lindaweb/start.html] in Vivaldi/Chrome browser, in the title, I can read the umlauts, but not on the coloured squares.

**Comment by eruedin** [comment] 2021-02-10 14:16
screen shot: [URL=https://www.directupload.net/file/d/6090/8phda979_jpg.htm][IMG]https://s12.directupload.net/images/210210/temp/8phda979.jpg[/IMG][/URL]

**Comment by ousia** [comment] 2021-02-10 16:45
@eruedin, the link reads http://zkm-lizenzen.ch/lindaweb/start.html.

The screenshot shows the problem:

![linda-klasse](https://user-images.githubusercontent.com/203767/107541023-fb5ffa80-6bc6-11eb-9e55-88312dd13c38.png)

This is an already known issue.

The difference between is that _Ruffle_ displays fonts fine when they are included in the SWF file (the animation itself).

But it does it poorly when it has to read fonts not included in the SWF file.

Right now it is faked: _Ruffle_ includes a font with many characters removed (this is why they are missing in your animation).

I think this issue is a duplicate of  #1862. If you allow me a suggestion, I’d close this issue and subscribe to  #1862.

I hope it helps.

**Comment by torokati44** [comment] 2022-02-10 00:21
All German letters were added to the fake device font in #6224.
The bigger issue is still not entirely fixed though, so #1862 is of course still open.

**Closed by torokati44** 2022-02-10 00:21 UTC
