### ISSUE TITLE
Error on https://extrememath.dev/swf

### ISSUE THREAD

**Issue by academic-help** [ruffle-rs/ruffle#8798] opened 2022-12-15 17:50 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.10c73117bb64ec8963af.js:1:6974)
    at std::sync::once::Once::call_once::{{closure}}::hcfb484f0d9d0b673 (wasm://wasm/0191619e:wasm-function[926]:0x26b835)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0191619e:wasm-function[1405]:0x3196b3)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h71fbea26086442fa (wasm://wasm/0191619e:wasm-function[4979]:0x4bcdeb)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0191619e:wasm-function[3760]:0x47b60b)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0191619e:wasm-function[5219]:0x4c1be6)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/0191619e:wasm-function[5034]:0x4bdd66)
    at core::ops::function::FnOnce::call_once::hb8f56d4134b06810 (wasm://wasm/0191619e:wasm-function[1284]:0x2ec73c)
    at ruffle_core::avm1::function::Executable::exec::h1a5d66921dea61e4 (wasm://wasm/0191619e:wasm-function[370]:0xf3c8f)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hd8e934ef5a5cd12a (wasm://wasm/0191619e:wasm-function[1445]:0x323ec5)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://extrememath.dev/swf?notebook=electricman2
SWF URL: https://extrememath.dev/swffiles/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.46
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-15
Channel: nightly
Built: 2022-12-15T00:16:26.229Z
Commit: cf03ee743079ad4f08706410a1dc465351775108
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3641749

**Comment by n0samu** [comment] 2022-12-15 19:32
Duplicate of #4932

**Closed by n0samu** 2022-12-15 19:32 UTC
Labels: duplicate, error-report
