### ISSUE TITLE
Error on https://www.play-games.com/game/scary-scavenger-hunt/index.html

### ISSUE THREAD

**Issue by Hfuueube** [ruffle-rs/ruffle#7977] opened 2022-09-13 23:39 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-1.0.1/src/fill.rs:1990:74
Error stack:
```
@https://www.play-games.com/js/frontend/vendor/ruffle/core.ruffle.d56713a8aacb20386203.js:1:5549
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hc005efe66820567d]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h1c414562e2619117]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h333199a3a4749bb8]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h1c368a27f9b0afe1]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hcdb13a4b2416cf82]@[wasm code]
<?>.wasm-function[core::panicking::panic::ha8ced62e366a0d64]@[wasm code]
<?>.wasm-function[core::slice::sort::shift_tail::h17c5fa2e4e71bbee]@[wasm code]
<?>.wasm-function[core::slice::sort::recurse::h3a7b53c573fe97ee]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::process_events::h26822e63bc926ec2]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_impl::h3f3b916e1b1a8e71]@[wasm code]
<?>.wasm-function[ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h113a6c72802646c2]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h911ec5d924ea5eec]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::he3411ec3be5a1f00]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h32ac4d8387a8d9ad]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::hdfd7130701b1f37a]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0e939f6a6e6bd632]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4a5310c550b24edd]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4f96c79adb87a72e]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h439672805b8361e6]@[wasm code]
wasm-stub@[native code]
k@https://www.play-games.com/js/frontend/vendor/ruffle/core.ruffle.d56713a8aacb20386203.js:1:3181
c@https://www.play-games.com/js/frontend/vendor/ruffle/core.ruffle.d56713a8aacb20386203.js:1:2481
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.play-games.com/game/scary-scavenger-hunt/index.html
SWF URL: https://www.play-games.com/game/scary-scavenger-hunt/ssh.swf

# Browser Info
User Agent: Mozilla/5.0 (iPad; CPU OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/228.0.471065565 Mobile/15E148 Safari/604.1
Platform: iPad
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-02
Channel: nightly
Built: 2022-08-02T00:19:12.167Z
Commit: 2ba82c92bc2f295d2a0269fa39feb574fc1fb183
Is extension: false

**Comment by n0samu** [comment] 2022-09-13 23:44
Duplicate of #6608. Updating your iPad to the latest OS version should fix the issue!

**Closed by n0samu** 2022-09-13 23:44 UTC
Labels: duplicate, error-report
