### ISSUE TITLE
Error on https://www.twoplayergames.org/gameframe/electricman-2

### ISSUE THREAD

**Issue by TimmyTyrone** [ruffle-rs/ruffle#8186] opened 2022-10-04 00:25 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.twoplayergames.org/dist/ruffle/core.ruffle.71c27bd6ee6f84a3fed6.js:1:7449)
    at std::sync::once::Once::call_once::{{closure}}::he3cf99cdc4fda287 (wasm://wasm/016aa9d6:wasm-function[1406]:0x2f8674)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/016aa9d6:wasm-function[1368]:0x2f0bc1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha1e2d21f5521daa9 (wasm://wasm/016aa9d6:wasm-function[4804]:0x440210)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/016aa9d6:wasm-function[3522]:0x405ac1)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/016aa9d6:wasm-function[4983]:0x4459d7)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/016aa9d6:wasm-function[4891]:0x441a24)
    at core::ops::function::FnOnce::call_once::h5d896e6757363123 (wasm://wasm/016aa9d6:wasm-function[1012]:0x2880b4)
    at ruffle_core::avm1::function::Executable::exec::h617d7843d3858b48 (wasm://wasm/016aa9d6:wasm-function[354]:0xde45f)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hddfd162220c32fa4 (wasm://wasm/016aa9d6:wasm-function[451]:0x1510af)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.twoplayergames.org/gameframe/electricman-2

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-21
Channel: nightly
Built: 2022-08-21T00:17:09.470Z
Commit: b18329c8feb06d4b2feaba64687abbf580599952
Is extension: false

**Comment by n0samu** [comment] 2022-10-04 00:34
Duplicate of #4932

**Closed by n0samu** 2022-10-04 00:34 UTC
Labels: duplicate, error-report
