### ISSUE TITLE
"Something went wrong" message

### ISSUE THREAD

**Issue by CarlKCarlK** [ruffle-rs/ruffle#1660] opened 2020-11-23 02:47 UTC
On http://slugco.com/games/InsultMachine/index3.htm

# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:54:21
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:54:21
    at Object.$ (http://slugco.com/games/InsultMachine/core.ruffle.7f6d216454b6a4a07936.js:1:20278)
    at __wbg_new_df6e6ab7a65c4c4d (http://slugco.com/games/InsultMachine/ruffle.js:1:31106)
    at http://slugco.com/games/InsultMachine/85f5e4a29d83ee43a391.module.wasm:wasm-function[1201]:0x22757d
    at http://slugco.com/games/InsultMachine/85f5e4a29d83ee43a391.module.wasm:wasm-function[1358]:0x2436eb
    at http://slugco.com/games/InsultMachine/85f5e4a29d83ee43a391.module.wasm:wasm-function[3589]:0x2eee47
    at http://slugco.com/games/InsultMachine/85f5e4a29d83ee43a391.module.wasm:wasm-function[2813]:0x2d15fd
    at http://slugco.com/games/InsultMachine/85f5e4a29d83ee43a391.module.wasm:wasm-function[3884]:0x2f3a65
    at http://slugco.com/games/InsultMachine/85f5e4a29d83ee43a391.module.wasm:wasm-function[3913]:0x2f3f9a
    at http://slugco.com/games/InsultMachine/85f5e4a29d83ee43a391.module.wasm:wasm-function[3789]:0x2f2642
    at http://slugco.com/games/InsultMachine/85f5e4a29d83ee43a391.module.wasm:wasm-function[3914]:0x2f3fd0
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://slugco.com/games/InsultMachine/index3.htm

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by adrian17** [comment] 2024-03-02 14:43
Unfortunately, the URL isn't reachable anymore, so can't reproduce :(

That said, most of the BorrowError from that era were fixed by now.

**Closed by adrian17** 2024-03-02 14:43 UTC
Labels: error-report

**Comment by CarlKCarlK** [comment] 2024-03-02 15:41
I confirmed that it is now working. Thanks.
