### ISSUE TITLE
Error on https://ruffle.rs/demo/ (world's hardest game)

### ISSUE THREAD

**Issue by uhokay4** [ruffle-rs/ruffle#9713] opened 2023-02-25 00:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    not enough memory left

', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu/src/backend/direct.rs:2973:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    not enough memory left

', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu/src/backend/direct.rs:2973:5
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://ruffle.rs/demo/966.index.js:1:5375)
    at std::sync::once::Once::call_once::{{closure}}::h2b820ce1023fd9d3 (wasm://wasm/028324a6:wasm-function[1953]:0x4a8bd6)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/028324a6:wasm-function[1890]:0x498dda)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d2a247897973255 (wasm://wasm/028324a6:wasm-function[7295]:0x77d3d3)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/028324a6:wasm-function[5184]:0x6d7720)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/028324a6:wasm-function[7605]:0x78c18e)
    at core::ops::function::Fn::call::h5ef784b6a2ac4e14 (wasm://wasm/028324a6:wasm-function[5429]:0x6e905d)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h0a7899309d670e42 (wasm://wasm/028324a6:wasm-function[4055]:0x672913)
    at <T as wgpu::context::DynContext>::device_create_buffer::h61a56a6e58015ad8 (wasm://wasm/028324a6:wasm-function[5876]:0x70eeef)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h84d8b38675041572 (wasm://wasm/028324a6:wasm-function[1278]:0x3947d8)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-24
Channel: nightly
Built: 2023-02-24T00:19:40.015Z
Commit: 5a7cd92bfed181aecb90f8bb631b8bbf5506d86f
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 30
numFrames: 180
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 997983

**Comment by LukeSaward1** [comment] 2023-02-25 09:12
is this happening on game load? If so, I cannot seem to reproduce this.

**Comment by uhokay4** [comment] 2023-04-08 16:41
it happens when around when the snubbyland logo shows up

**Comment by LukeSaward1** [comment] 2023-04-08 18:13
Can you please link the SWF you're using?

**Comment by Dinnerbone** [comment] 2024-07-12 22:00
Duplicate of #9293

**Closed by Dinnerbone** 2024-07-12 22:00 UTC
Labels: duplicate, render-wgpu, error-report
