### ISSUE TITLE
Stick War gets stuck

### ISSUE THREAD

**Issue by mero09-99** [ruffle-rs/ruffle#7952] opened 2022-09-11 18:11 UTC
### Describe the bug

When trying to play the first mission, the mission banner unfurls as normal, then prevents you from clicking start
![lockk](https://user-images.githubusercontent.com/109428504/189542606-ad726ba4-6da5-4d6e-8b23-ee98e6711e2c.jpg)

### Expected behavior

the game should be able to be played

### Affected platform

Online demo

### Operating system

Windows 10 Firefox 

### Browser

Firefox

### Additional information

![log](https://user-images.githubusercontent.com/109428504/189542638-b0226802-7e4d-40d8-aca8-80f04dd2e1a9.jpg)
this is the log

**Comment by mero09-99** [comment] 2022-09-11 18:12
[stickwar_08.zip](https://github.com/ruffle-rs/ruffle/files/9543237/stickwar_08.zip)
here is the SWF

**Comment by n0samu** [comment] 2022-09-11 18:21
Duplicate of #5126

**Closed by n0samu** 2022-09-11 18:21 UTC
Labels: bug, duplicate
