### ISSUE TITLE
Error on http://swordandsandals.top/swords-and-sandals-2-full-version/

### ISSUE THREAD

**Issue by DennisLaz** [ruffle-rs/ruffle#14818] opened 2024-01-18 11:43 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.


    at H.n.wbg.__wbg_new_3a66822ed076951c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.11487f53402d68a59956.js:1:56211)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h17602019b8af7fc3 (wasm://wasm/0366be16:wasm-function[10827]:0xa26765)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/0366be16:wasm-function[6635]:0x910b85)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/0366be16:wasm-function[10541]:0xa20330)
    at core::ops::function::Fn::call::h5c3bbc5f192c8d63 (wasm://wasm/0366be16:wasm-function[6942]:0x926cb2)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h8d87cf405961e005 (wasm://wasm/0366be16:wasm-function[5462]:0x8a644c)
    at <T as wgpu::context::DynContext>::device_create_buffer::hc2d9d26dcccb9181 (wasm://wasm/0366be16:wasm-function[7743]:0x96c5ec)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hb9cbd1f981a041f6 (wasm://wasm/0366be16:wasm-function[1811]:0x5522f0)
    at ruffle_render_wgpu::surface::target::CommandTarget::new::h2e5ebce8ee4159d7 (wasm://wasm/0366be16:wasm-function[906]:0x32659c)
    at ruffle_render_wgpu::surface::Surface::draw_commands::h9573944c75185287 (wasm://wasm/0366be16:wasm-function[610]:0x1102ba)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 SUPER (0x00001F06) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://swordandsandals.top/swords-and-sandals-2-full-version/
SWF URL: http://swordandsandals.top/wp-content/uploads/swords-and-sandals-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-18
Channel: nightly
Built: 2024-01-18T00:15:03.619Z
Commit: d89ab3dc835b0490611d50981c49bf14a7283bce
Is extension: false

# Metadata
width: 640
height: 420
frameRate: 30
numFrames: 277
swfVersion: 8
backgroundColor: #FFCC66
isActionScript3: false
uncompressedLength: 5282134

**Comment by evilpie** [comment] 2024-02-14 21:06
Duplicate of #14782.

**Closed by evilpie** 2024-02-14 21:06 UTC
Labels: error-report, wgpu-oom
