### ISSUE TITLE
Error on https://extrememath.info/swf

### ISSUE THREAD

**Issue by THERANDOMCHEEMS12** [ruffle-rs/ruffle#8770] opened 2022-12-13 16:12 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ae8cf5f5f14f7f2fd26f.js:1:6974)
    at std::sync::once::Once::call_once::{{closure}}::h4f7445f5740cc36b (wasm://wasm/019183be:wasm-function[926]:0x26bfb3)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/019183be:wasm-function[1401]:0x319534)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7dfd384227ef6d86 (wasm://wasm/019183be:wasm-function[4989]:0x4bd65f)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/019183be:wasm-function[3768]:0x47c447)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/019183be:wasm-function[5230]:0x4c248e)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/019183be:wasm-function[5044]:0x4be5da)
    at core::ops::function::FnOnce::call_once::hd510ce4d6a04ed25 (wasm://wasm/019183be:wasm-function[1286]:0x2f7f99)
    at ruffle_core::avm1::function::Executable::exec::hdfa083dba6195d53 (wasm://wasm/019183be:wasm-function[367]:0xf07b1)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h1f3adeccbcf51c60 (wasm://wasm/019183be:wasm-function[1446]:0x3251d3)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://extrememath.info/swf?notebook=electricman2
SWF URL: https://extrememath.info/swffiles/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15183.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-13
Channel: nightly
Built: 2022-12-13T00:16:27.259Z
Commit: 02360b28dca80263c8e93cde2467c487688770ac
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3641749

**Comment by THERANDOMCHEEMS12** [comment] 2022-12-13 16:13
it just not worked after level 3

**Comment by n0samu** [comment] 2022-12-13 19:03
Duplicate of #4932

**Closed by n0samu** 2022-12-13 19:03 UTC
Labels: duplicate, error-report
