### ISSUE TITLE
Error on https://www.gameflare.com/embed/jacksmith/

### ISSUE THREAD

**Issue by YourMeyn** [ruffle-rs/ruffle#16593] opened 2024-06-04 15:17 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.0/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.0/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096


    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://www.gameflare.com/emulators/ruffle/core.ruffle.b57d145c0b62e53e730b.js:1:74974)
    at ruffle_web.wasm.js_sys::Error::new::ha59a397dfb01052a (wasm://wasm/ruffle_web.wasm-033978ae:wasm-function[12826]:0x9fb9bf)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d553c011316b6be (wasm://wasm/ruffle_web.wasm-033978ae:wasm-function[10465]:0x9b5e61)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-033978ae:wasm-function[6541]:0x87ee1a)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-033978ae:wasm-function[10206]:0x9aea71)
    at ruffle_web.wasm.core::ops::function::Fn::call::ha4719dc1d08feb58 (wasm://wasm/ruffle_web.wasm-033978ae:wasm-function[7498]:0x8c55c1)
    at ruffle_web.wasm.wgpu::backend::wgpu_core::ContextWgpuCore::handle_error::h87ba4eeca0adddc1 (wasm://wasm/ruffle_web.wasm-033978ae:wasm-function[2144]:0x56c07d)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h904a2355f0357d11 (wasm://wasm/ruffle_web.wasm-033978ae:wasm-function[9776]:0x9814d2)
    at ruffle_web.wasm.wgpu::CommandEncoder::copy_texture_to_buffer::h43a9cd8ce76c1182 (wasm://wasm/ruffle_web.wasm-033978ae:wasm-function[9422]:0x961e98)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::resolve_sync_handle::h4902ce7a4cf483c7 (wasm://wasm/ruffle_web.wasm-033978ae:wasm-function[6017]:0x852317)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.models::LobbySoldier/swapToSprite()
    at swordGame.models::LobbySoldier/walkCustomer()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mali-G52 MC2"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 16383, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.gameflare.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-06-04
Channel: nightly
Built: 2024-06-04T00:05:37.409Z
Commit: 6af5a9f7ab0ff36ec49364f95e535ad4c0f833df
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by evilpie** [comment] 2024-06-05 11:57
Duplicate of #11591.

**Closed by evilpie** 2024-06-05 11:57 UTC
Labels: error-report
