### ISSUE TITLE
Error on https://www.numuki.com/gameframe/ben-to-the-rescue

### ISSUE THREAD

**Issue by ArashTechDev** [ruffle-rs/ruffle#14869] opened 2024-01-21 02:36 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/display_object/container.rs:973:22:
called `Option::unwrap()` on a `None` value
Error stack:
```
Error: panicked at core/src/display_object/container.rs:973:22:
called `Option::unwrap()` on a `None` value
    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://www.numuki.com/include/js/ruffle/latest/core.ruffle.e83b1d16dc2d61092e10.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a435d7beef43b50 (wasm://wasm/03633e02:wasm-function[10788]:0xa1bc13)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/03633e02:wasm-function[6606]:0x903b11)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/03633e02:wasm-function[10500]:0xa15745)
    at core::panicking::panic::hd37d8d0a98259c88 (wasm://wasm/03633e02:wasm-function[10069]:0x9fb76a)
    at core::ops::function::FnOnce::call_once::h8f83249133bfe479 (wasm://wasm/03633e02:wasm-function[999]:0x388e2b)
    at ruffle_core::avm1::function::Executable::exec::h5a1c21ef9587fa3f (wasm://wasm/03633e02:wasm-function[670]:0x1b7db4)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h91d47f1a4587ab51 (wasm://wasm/03633e02:wasm-function[7083]:0x9258cd)
    at ruffle_core::avm1::activation::Activation::run_actions::hcbc7f77f0c37d3fd (wasm://wasm/03633e02:wasm-function[568]:0x48a7b)
    at ruffle_core::avm1::function::Executable::exec::h5a1c21ef9587fa3f (wasm://wasm/03633e02:wasm-function[670]:0x1b7c25)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 (0x00005917) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 750, height: 500, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.numuki.com/gameframe/ben-to-the-rescue
SWF URL: https://media.numuki.com/ben-10/games/ben-to-the-rescue/preload.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-15
Channel: nightly
Built: 2024-01-15T00:15:42.928Z
Commit: a638715bd87d818d134a70659e7124234b992447
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 43
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 63469

**Comment by n0samu** [comment] 2024-01-21 10:23
Duplicate of #12698

**Closed by n0samu** 2024-01-21 10:23 UTC
Labels: duplicate, avm1, error-report
