### ISSUE TITLE
Error on https://www.comdotgame.com/play/ashiage-samus

### ISSUE THREAD

**Issue by Ttyuuuyyyuy** [ruffle-rs/ruffle#11221] opened 2023-05-26 11:24 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(2, 18, Gl)>`
    In a pass parameter
      note: command buffer = `<CommandBuffer-(2, 18, Gl)>`
    Attempted to use a texture (mips 0..1 layers 0..1) with conflicting usages. Current usage RESOURCE and new usage COLOR_TARGET. COLOR_TARGET is an exclusive usage and cannot be used with any otherusages within the usage scope (renderpass or compute dispatch).

', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu/src/backend/direct.rs:2973:5
Error stack:
```
@https://echo.comdotgame.com/ruffle/core.ruffle.31c166ab9c2b119e4092.js:1:46517
wasm-stub@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h321a9078ff9936f2]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h2a7f454a5f5da218]@[wasm code]
<?>.wasm-function[core::ops::function::Fn::call::hd089cc074b4450ee]@[wasm code]
<?>.wasm-function[wgpu::backend::direct::ErrorSinkRaw::handle_error::h6c7fafc1615c2235]@[wasm code]
<?>.wasm-function[<T as wgpu::context::DynContext>::command_encoder_end_render_pass::h7e11412c46d20f86]@[wasm code]
<?>.wasm-function[<wgpu::RenderPass as core::ops::drop::Drop>::drop::he9bac048fe19685b]@[wasm code]
<?>.wasm-function[ruffle_render_wgpu::surface::Surface::draw_commands::h7199112b60f4534f]@[wasm code]
<?>.wasm-function[ruffle_render_wgpu::surface::Surface::draw_commands_to::hcf6cb8dc04e91c9e]@[wasm code]
<?>.wasm-function[<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::render_offscreen::h2fea9c572779f697]@[wasm code]
<?>.wasm-function[ruffle_core::bitmap::bitmap_data::BitmapData::draw::ha4743a21ff9389c9]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::globals::bitmap_data::draw::he5f36e3e115b0462]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h38c958325b439c56]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7abbd9838b46d90c]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h9017a8ee32124b3e]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h38c958325b439c56]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7abbd9838b46d90c]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_method::h085e05b35aa73885]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::hd36ae2ead33b20c6]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h2000682d298368c3]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h820d06e21ce20de4]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha6dba4b7bc395bcc]@[wasm code]
wasm-stub@[wasm code]
A@https://echo.comdotgame.com/ruffle/core.ruffle.31c166ab9c2b119e4092.js:1:2687
f@https://echo.comdotgame.com/ruffle/core.ruffle.31c166ab9c2b119e4092.js:1:2241
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/550453758eb3306a30f16d0d0cabb811.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/ashiage-samus
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/550453758eb3306a30f16d0d0cabb811.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
Platform: MacIntel
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-12
Channel: nightly
Built: 2023-03-12T00:19:04.440Z
Commit: 1deebc87e869387c962f97b665d26785d0a2b52f
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 20
numFrames: 4
swfVersion: 17
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 2349502

**Comment by n0samu** [comment] 2023-05-27 00:01
Duplicate of #9923. This problem has already been fixed by #10315. Please contact the website owner and ask them to update their copy of Ruffle.

**Closed by n0samu** 2023-05-27 00:01 UTC
Labels: duplicate, nsfw, error-report
