### ISSUE TITLE
Error on http://www.freeworldgroup.com/games9/gameindex/tank2012.htm

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#8255] opened 2022-10-10 18:45 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/core.ruffle.96e8bbc4ac06599a18dc.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/017fda8e:wasm-function[1035]:0x2a678f)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017fda8e:wasm-function[1500]:0x32a080)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/017fda8e:wasm-function[4959]:0x487777)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017fda8e:wasm-function[3648]:0x444156)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017fda8e:wasm-function[5114]:0x48ac37)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/017fda8e:wasm-function[5788]:0x49d441)
    at ruffle_web::Ruffle::tick::hcce3b9c42455dc22 (wasm://wasm/017fda8e:wasm-function[673]:0x21a00b)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hfb791d31cd1d45d9 (wasm://wasm/017fda8e:wasm-function[6005]:0x4a47b5)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h476982f031f67f47 (wasm://wasm/017fda8e:wasm-function[5475]:0x4950a0)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://www.freeworldgroup.com/games9/gameindex/tank2012.htm
SWF URL: http://www.freeworldgroup.com/games9/tank2012/ENsecure.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-10
Channel: nightly
Built: 2022-10-10T00:16:25.636Z
Commit: 10c19fef5751b3fd648fb997864f953de9ce9a72
Is extension: false

# Metadata
width: 700
height: 600
frameRate: 30
numFrames: 2
swfVersion: 15
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 9723788

**Comment by n0samu** [comment] 2022-10-12 16:09
Duplicate of #5832

**Closed by n0samu** 2022-10-12 16:09 UTC
Labels: duplicate, error-report
