### ISSUE TITLE
Error on https://pelikone.fi/pelit/arcade-pelit/Monkey-GO-Happy-3/7772

### ISSUE THREAD

**Issue by Piezku** [ruffle-rs/ruffle#13373] opened 2023-09-30 17:20 UTC
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2414:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h327b73cb23b2fa83 (wasm://wasm/032916fa:wasm-function[9709]:0x98b9d0)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/032916fa:wasm-function[6338]:0x882c95)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/032916fa:wasm-function[9542]:0x986f14)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h6848b10fb58f5799 (wasm://wasm/032916fa:wasm-function[3318]:0x6d3891)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h5800325acd5f098e (wasm://wasm/032916fa:wasm-function[3227]:0x6bf8f7)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h26b33f7858119546 (wasm://wasm/032916fa:wasm-function[1075]:0x3966fe)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::he2761d539d81ebd5 (wasm://wasm/032916fa:wasm-function[1931]:0x55d249)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h9da906cece72cf22 (wasm://wasm/032916fa:wasm-function[842]:0x2e30e1)
    at <ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::hccce0e225c6ac94c (wasm://wasm/032916fa:wasm-function[2697]:0x638f23)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://pelikone.fi/games/files/gaXxp0qVLly9B4g.swf
Param wmode: gpu
Param allowscriptaccess: always
Param bgcolor: 000000
Param base: https://pelikone.fi/games/files/7772/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute 7: undefined

# Page Info
Page URL: https://pelikone.fi/pelit/arcade-pelit/Monkey-GO-Happy-3/7772?archive=true
SWF URL: https://pelikone.fi/games/files/gaXxp0qVLly9B4g.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-30
Channel: nightly
Built: 2023-09-30T00:20:30.366Z
Commit: f140e7a14b379993625b07524c4453ae98592384
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 40
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 3943324

**Comment by Lord-McSweeney** [comment] 2023-09-30 17:21
Duplicate of #13371

**Closed by Lord-McSweeney** 2023-09-30 17:21 UTC
Labels: error-report
