### ISSUE TITLE
Error on https://flashthemes.net/

### ISSUE THREAD

**Issue by JarrodArceeBlake** [ruffle-rs/ruffle#14432] opened 2023-12-17 14:19 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_a64e3f2afc2cf2f8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h853353504563e1d1 (wasm://wasm/03419ee6:wasm-function[9859]:0x9d4552)
    at std::panicking::rust_panic_with_hook::hbf46ef0245cc9589 (wasm://wasm/03419ee6:wasm-function[6306]:0x8c04f4)
    at core::panicking::panic_fmt::h14c85a61aa3d538e (wasm://wasm/03419ee6:wasm-function[9650]:0x9cf19e)
    at core::panicking::assert_failed_inner::h4ee8cb46314b5c9b (wasm://wasm/03419ee6:wasm-function[4320]:0x7c7385)
    at core::panicking::assert_failed::h234a88e378db4ad2 (wasm://wasm/03419ee6:wasm-function[9676]:0x9d04d5)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::h4a71b0056b31566e (wasm://wasm/03419ee6:wasm-function[2340]:0x617715)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hd75709e492bced9d (wasm://wasm/03419ee6:wasm-function[1255]:0x457844)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hee8d58dba3b26db3 (wasm://wasm/03419ee6:wasm-function[3593]:0x75d939)
    at wasm_bindgen::convert::closures::invoke1_mut::ha9a30d0d24e166d7 (wasm://wasm/03419ee6:wasm-function[10582]:0x9efeb5)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 687, height: 480, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param flashvars: movieId=rVfogKen&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D1401&thumburl=%2Fmovie_thumbs%2Fthumb-rVfogKen.png&v=1401&movieLid=6&pwm=0&ut=-1&apiserver=https%3A%2F%2Fflashthemes.net%2F&playcount=1&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=1&isInitFromExternal=0&isWide=0&appCode=go&is_slideshow=0&is_emessage=0&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=0&&&&isTemplate=0&showButtons=1&chain_mids=&endStyle=0&showshare=true
Param movie: /static/animationnew/414827163ad4eb60/player.swf
Param wmode: opaque
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-17
Channel: nightly
Built: 2023-12-17T00:15:52.659Z
Commit: 375c99e601b28683058d09ad7ea76deb423ced1f
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment] 2023-12-19 07:19
Duplicate of #13974

**Closed by n0samu** 2023-12-19 07:19 UTC
Labels: duplicate, error-report
