### ISSUE TITLE
Ruffle Error on https://sonic.ee/

### ISSUE THREAD

**Issue by OpticallyIllusional** [ruffle-rs/ruffle#7163] opened 2022-06-05 07:32 UTC
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at https://cdn.w3technic.com/flash/ruffle.js:1:67050
    at Array.forEach (<anonymous>)
    at Object.vi.f.wasm (https://cdn.w3technic.com/flash/ruffle.js:1:66977)
    at https://cdn.w3technic.com/flash/ruffle.js:1:35299
    at Array.reduce (<anonymous>)
    at Function.vi.e (https://cdn.w3technic.com/flash/ruffle.js:1:35276)
    at o (https://cdn.w3technic.com/flash/ruffle.js:1:2595)
    at o.next (<anonymous>)
    at https://cdn.w3technic.com/flash/ruffle.js:1:2895
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://sonic.ee/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 OPR/86.0.4363.70
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by Toad06** [comment] 2022-06-05 17:48
Closing as duplicate of #5844.

This website is also using a version of Ruffle which is really outdated; newer versions fixed many issues in this Sonic game. So it would be better to play this game at https://www.newgrounds.com/portal/view/151706/format/flash?emulate=flash (for instance).

Thank you.

**Closed by Toad06** 2022-06-05 17:48 UTC
