### ISSUE TITLE
Error on https://newcp.net/play/gameframe.html

### ISSUE THREAD

**Issue by ZoePuffLaPingou** [ruffle-rs/ruffle#17392] opened 2024-08-06 11:10 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/device.rs:775:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/device.rs:775:52:
called `Result::unwrap()` on an `Err` value: "Unable to create texture object"
    at n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.7c33c311625b6980ad83.js:1:79747)
    at ruffle_web.wasm.js_sys::Error::new::ha367eb220e837752 (wasm://wasm/ruffle_web.wasm-033442d2:wasm-function[12817]:0x9d5c51)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h61f15f58f281740d (wasm://wasm/ruffle_web.wasm-033442d2:wasm-function[9867]:0x96c2ef)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h844c7fdc9e749b51 (wasm://wasm/ruffle_web.wasm-033442d2:wasm-function[6493]:0x860800)
    at ruffle_web.wasm.core::panicking::panic_fmt::h8d7e2d43cfcec163 (wasm://wasm/ruffle_web.wasm-033442d2:wasm-function[10261]:0x996da6)
    at ruffle_web.wasm.core::result::unwrap_failed::h2ad2a8f9767ffb30 (wasm://wasm/ruffle_web.wasm-033442d2:wasm-function[8106]:0x8e9452)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_texture::hdfc2ae0c1c09f35e (wasm://wasm/ruffle_web.wasm-033442d2:wasm-function[7535]:0x8ac766)
    at ruffle_web.wasm.wgpu::Device::create_texture::h52463a701495d7b8 (wasm://wasm/ruffle_web.wasm-033442d2:wasm-function[5901]:0x829a8b)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h1f6a1dbfdaa0cf34 (wasm://wasm/ruffle_web.wasm-033442d2:wasm-function[5667]:0x812db3)
    at ruffle_web.wasm.ruffle_core::display_object::render_base::h56d415fbc21726f2 (wasm://wasm/ruffle_web.wasm-033442d2:wasm-function[817]:0x15b174)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Vulkan 1.3.274 (Intel(R) UHD Graphics (JSL) (0x00004E55)), Intel open-source Mesa driver)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 64, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 112, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: https://media1.newcp.net/play/v2/client/club_penguin.swf?clientVersion=1722771435
Param menu: false
Param quality: high
Param allowscriptaccess: always
Param wmode: direct
Param flashvars: play=https://media1.newcp.net/play/&client=https://media1.newcp.net/play/v2/client/&content=https://media1.newcp.net/play/v2/content/&games=https://media1.newcp.net/play/v2/games/&connectionID=cp68294&a=0&p=1&nau=&nal=&nas=&nad=&lang=en&phrasechat=https://n7vcp1clubpwns.newcp.net/social/autocomplete/v2/search/&isAS3WebServicesOn=true&cacheVersion=0&clientVersion=1722771435&configVersion=1722771435&contentVersion=1722771435&minigameVersion=1722771435
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined
Attribute 7: undefined

# Page Info
Page URL: https://newcp.net/play/gameframe.html?cache=1722942475680#/login
SWF URL: https://media1.newcp.net/play/v2/client/club_penguin.swf?clientVersion=1722771435

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-08-06
Channel: nightly
Built: 2024-08-06T00:05:25.298Z
Commit: 07c9901efe278ea228a5a80467efdbe40bf1c33f
Is extension: false

# Metadata
width: 760
height: 480
frameRate: 24
numFrames: 1
swfVersion: 38
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1172240

**Comment by n0samu** [comment] 2024-08-06 22:42
Duplicate of #17389

**Closed by n0samu** 2024-08-06 22:42 UTC
Labels: duplicate, error-report
