### ISSUE TITLE
Error on all projects; player does not play, waterfox classic .12 freezes

### ISSUE THREAD

**Issue by sunlightspectre** [ruffle-rs/ruffle#2568] opened 2021-01-16 00:56 UTC
All videos display a url-to-swf path filed by :3.

Rather then being a cute(?) cat-face of doom, it is - alas! - a more frustrating occurrence that is easy to reduplicate... For _me._ 
I think, in all likelihood, it's a waterfox incompatibility, rather then a ruffle issue, but filing this just-in-case.

**Steps to reproduce:** Common; occurs with any video, game, etc; seems common to all variants of flash.

**Steps taken to ameliorate:** 

- Installed the nightly.

- Removed/re-installed ruffle.

- tried lightspark, cannot say i recommend

- Tested with a fresh, portable, installation, ruffle being the only add-on.
Take care out there. Thank you for your time.

**Comment by ousia** [comment] 2021-01-17 13:39
@sunlightspectre, many thanks for your issue report.

In order to make easier for the developers to understand the issue you are facing, could you please provide an address of an animation that is problematic to you?

Or do you want to ask simply whether Ruffle is compatible with Waterfox?

**Comment by sunlightspectre** [comment] 2021-01-18 10:48
But of course, my good ousia!

[Here's an example, picked at random. ](https://uploads.ungrounded.net//599000//599903_Tanooky_1_7_coolbuddy.swf?f1343493051) I have not found any flashes compatible with ruffle yet. Actually, if you can give me the address of a flash known to play nice with ruffle to test, that'd be excellent. The demo page at ruffle.rs also has a javascript hang for me; it shouldn't be blocked or filtered in anyway on my end.

Just in case it is a Waterfox isssue, here's the exact version of WF I'm using as of this report:

Waterfox Classic 2020.12 (64-bit).

Take your time, this is incredibly low priority and more about me wanting to help contribute in some fashion then 'needing' a personal fix. The same will be true of any other issues I open. I hope this, in some small manner, can help further the team's work.

**Comment by ousia** [comment] 2021-01-19 17:08
@sunlightspectre,

many thanks for your reply.

https://uploads.ungrounded.net//599000//599903_Tanooky_1_7_coolbuddy.swf doesn’t display anything to me.

https://ousia.github.io/ruffle-demo should work (both animations are only one).

**Comment by sunlightspectre** [comment] 2021-01-21 11:05
@ousia

Naturally, you're quite welcome! Hmn, and that's interesting - I noticed that Ruffle doesn't render on protected browsers, which I'm assuming means Private Browsing modes. Fine, I went and tried loading your link - https://ousia.github.io/ruffle-demo - and get the flash end of life screen with a blue background. Ruffle appears to be stuck on checking its own status; see attached image.

https://i.imgur.com/UF9gvGu.png

**Comment by ousia** [comment] 2021-01-22 17:02
@sunlightspectre, this is really weird, since I don’t have browsers that don’t work in private mode.

BTW, GitHub enables attaching both images and videos (no external servers are needed).

https://www.free-culture.tk/original/ should work for you (while https://www.free-culture.tk/ doesn’t work, since it lacks many features, such as the loader).

I think you should enable _Ignore website compatibility warnings_.

**Comment by sunlightspectre** [comment] 2021-01-23 04:14
Ooops, sorry, haha. Old habits die hard..!

@ousia, I tested the following on a safe mode, zero-addons, scripts, etc run of Waterfox Classic, through the test/debug addons feature. I still get the same odd script freeze; just for the sake of completeness, the presentation works fine with the chrome version of Ruffle? Weird..!

![a12afg415ybaz3](https://user-images.githubusercontent.com/77517834/105568393-df66e880-5ced-11eb-8df6-98433712e361.png)

Website compatibility warnings disabled, too; it's a real headscratcher! I'll probably close this after registering this one, I think it _must_ be some kind of refusal to play nice with Waterfox? I'd love to summon another WF user out of the aether and ask them if they're having the same issues... Anyway.

Thanks, as ever!

**Comment by Incoming5643** [comment] 2021-01-24 08:32
Another waterfox classic user being summoned out of the aether here to say yes, same problem. 

Something ruffle relies on probably isn't in WFC.

**Comment by sunlightspectre** [comment] 2021-01-25 20:49
Thanks for verifying, @Incoming5643 !

I wish I was clever enough to narrow it down, but knowing that it's not just an individual error is a good starting place. Even if it's as simple as 'Ruffle requires js that WFC simply doesn't have,' pinning it down might be useful for later... Anyway.

Thank you for *somehow* warping out of the aether and answering my telepathic plea, ahahaha!

**Comment by Herschel** [comment] 2021-01-25 21:33
Thanks for testing all, Ruffle doesn't officially support Waterfox but I agree it'd be good to try to track down what the specific issues are and if they're resolvable!

**Comment by sunlightspectre** [comment] 2021-01-26 22:32
Quite, @Herschel ! I feel as if I should probably close this particular issue, as I don't want to distract from other, more pressing ones, but I'm gonna poke around actionscript, which is what I _think_ is causing the hang. I am an absolute novice compared to you all, so do take that statement with a pound of salt...

**Comment by sunlightspectre** [comment] 2021-01-30 13:36
Issue closed; issue related to browser status. Will re-open issue if it's possible to isolate why, and how to rectify.

**Comment by Herschel** [comment] 2021-02-03 22:10
I'm going to keep this open for reference. I can confirm this happens to me as well on Waterfox Classic 2020.12. The script get stuck in execution for an unknown reason. I haven't investigated what the cause might be; it's possible that Waterfox Classic does not quite support the features that Ruffle needs.

Modern Waterfox G3.0.2 works successfully.

**Comment by sunlightspectre** [comment] 2021-02-04 01:45
Gotcha - quick question, I won't be stepping on any toes if I try to figure out what might be the cause? It's been ages since I've done a pull request, and the last thing I want to do is make more work.

Thanks for verifying Waterfox Modern works, though - I wonder...

**Comment by Herschel** [comment] 2021-02-04 02:46
Not at all, in fact help is welcome. :-)

**Comment by Herschel** [comment] 2021-04-09 21:46
Waterfox Classic hang is fixed in #3729 -- unfortunately, Ruffle will still not function in this browser due to lack of Custom Elements support. But this will allow the classic Flash NPAPI plugin to work in some cases if it's available

**Closed** 2021-04-09 21:47 UTC
Labels: web
