### ISSUE TITLE
Error on https://www.twoplayergames.org/gameframe/electricman-2

### ISSUE THREAD

**Issue by rswee39** [ruffle-rs/ruffle#5630] opened 2021-11-10 02:45 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.twoplayergames.org/dist/build/ruffle/ruffle.667efded.js:1:7045)
    at std::sync::once::Once::call_once::{{closure}}::h5c607ed08f988e53 (https://www.twoplayergames.org/dist/build/ruffle/4a5f4eae5d478724299e.234e9476.wasm:wasm-function[1003]:0x2f08f4)
    at std::sync::once::Once::call_inner::hf1b92ab8c222362b (https://www.twoplayergames.org/dist/build/ruffle/4a5f4eae5d478724299e.234e9476.wasm:wasm-function[1324]:0x35ed2b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3097032c631d0165 (https://www.twoplayergames.org/dist/build/ruffle/4a5f4eae5d478724299e.234e9476.wasm:wasm-function[4573]:0x4e4657)
    at std::panicking::rust_panic_with_hook::ha223473efd20893e (https://www.twoplayergames.org/dist/build/ruffle/4a5f4eae5d478724299e.234e9476.wasm:wasm-function[3241]:0x49fe31)
    at rust_begin_unwind (https://www.twoplayergames.org/dist/build/ruffle/4a5f4eae5d478724299e.234e9476.wasm:wasm-function[4634]:0x4e6aeb)
    at core::panicking::panic_fmt::hca0bee0b11468063 (https://www.twoplayergames.org/dist/build/ruffle/4a5f4eae5d478724299e.234e9476.wasm:wasm-function[4834]:0x4f15ad)
    at core::panicking::panic::hb05521048dcb55f3 (https://www.twoplayergames.org/dist/build/ruffle/4a5f4eae5d478724299e.234e9476.wasm:wasm-function[4569]:0x4e3e88)
    at core::ops::function::FnOnce::call_once::hb91e844e13e6f7ac (https://www.twoplayergames.org/dist/build/ruffle/4a5f4eae5d478724299e.234e9476.wasm:wasm-function[1044]:0x30bd73)
    at ruffle_core::avm1::function::Executable::exec::hec774c8187191712 (https://www.twoplayergames.org/dist/build/ruffle/4a5f4eae5d478724299e.234e9476.wasm:wasm-function[420]:0x15fe27)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.twoplayergames.org/gameframe/electricman-2
SWF URL: https://files.twoplayergames.org/files/games/o1/Electricman_2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 OPR/80.0.4170.91
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-01
Channel: nightly
Built: 2021-11-01T00:13:10.095Z
Commit: b0b1c79143a80f1bb457833bdb78139944464d9c
Is extension: false

**Comment by relrelb** [comment] 2021-11-10 06:07
Duplicate of #4932.

**Closed by relrelb** 2021-11-10 06:07 UTC
Labels: error-report
