### ISSUE TITLE
Error on https://whentai.com/view/1981/zone

### ISSUE THREAD

**Issue by TrinityVrol** [ruffle-rs/ruffle#6703] opened 2022-04-13 22:36 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
@https://whentai.com/js/ruffle/ruffle.js:1:6924
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hf7fd718057964857]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h9d91fa0fae16500f]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h91d2023e5afe1929]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h4d06e5cc335302b3]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1c9b256bef969e15]@[wasm code]
wasm-stub@[native code]
I@https://whentai.com/js/ruffle/ruffle.js:1:3550
a@https://whentai.com/js/ruffle/ruffle.js:1:2841
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://whentai.com/view/1981/zone
SWF URL: https://f4s5z4k8.ssl.hwcdn.net/uploads/6/7/0/67013572f50d00c30b742885f82d5547.swf?ttl=1649889956&token=45d0fb9bca7e873d49630bad8323856a

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/206.1.438432329 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-01
Channel: nightly
Built: 2021-04-01T00:41:20.918Z
Commit: e453cbf0efd932218ccfc0f06f09d2fc4a95d4ea

**Comment by n0samu** [comment] 2022-05-20 17:03
Very old version of Ruffle and iOS 15.4, dupe of #6608. Updating your device to iOS 15.5 should fix the issue!

**Closed by n0samu** 2022-05-20 17:03 UTC
Labels: nsfw, error-report
