### ISSUE TITLE
Error on Electric Man 2 (https://meb.coveryourselfinoil.com/gm/view.php?id=40)

### ISSUE THREAD

**Issue by KVRX** [ruffle-rs/ruffle#6769] opened 2022-04-21 11:17 UTC
It happened after completing training. For some reason, the enemies load in before even selecting a level, then they start attacking you before the fight starts, and then this happens.

```
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:

r/s.wbg.__wbg_new_df6e6ab7a65c4c4d@https://meb.coveryourselfinoil.com/rf/ruffle.js:1:6803
std::sync::once::Once::call_once::{{closure}}::h647d1f7832046459@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[1012]:0x29a498
std::sync::once::Once::call_inner::hc44ad7f626385660@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[1276]:0x2f19ab
core::ops::function::FnOnce::call_once{{vtable.shim}}::hec2c3e1e216f4525@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[4332]:0x48b659
std::panicking::rust_panic_with_hook::he9bfe03219d715ba@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[3151]:0x41a79d
rust_begin_unwind@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[4557]:0x49134e
core::panicking::panic_fmt::hbf21a3d4bbb82bf8@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[4743]:0x498916
core::panicking::panic::h2fd385a887c8bf13@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[4494]:0x48e93a
core::ops::function::FnOnce::call_once::h2af075b8415a08a5@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[991]:0x291858
ruffle_core::avm1::function::Executable::exec::h9282a304943b15d7@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[392]:0x1022a5
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::h031c1e239ea047c6@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[750]:0x228f90
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h2eea8dcd15079742@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[464]:0x152d20
ruffle_core::avm1::activation::Activation::do_action::hb37cb283fad24ff7@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[304]:0xd71e
ruffle_core::avm1::activation::Activation::run_actions::hb70c8a8fa0a84c13@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[2702]:0x3f8547
ruffle_core::avm1::Avm1::run_stack_frame_for_action::h90904cb2e9a7321e@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[1039]:0x2a41c4
ruffle_core::player::Player::run_actions::h426c05d7708cb27d@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[470]:0x15a78e
ruffle_web::Ruffle::tick::h1e4b85a3d5b0fe05@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[568]:0x1a56c2
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h9373a7d130885352@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[5277]:0x4a4940
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9e9673f013ffbba7@https://meb.coveryourselfinoil.com/rf/46a51821ed7f1aeb7f0a.wasm:wasm-function[4879]:0x49a8e8
A@https://meb.coveryourselfinoil.com/rf/ruffle.js:1:3580
a@https://meb.coveryourselfinoil.com/rf/ruffle.js:1:2535

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://meb.coveryourselfinoil.com/gm/view.php?id=40
SWF URL: https://meb.coveryourselfinoil.com/u/f/40_guSAfb.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-04
Channel: nightly
Built: 2021-10-04T00:11:57.485Z
Commit: ee9341cb1c4bb8bb4b7324a8c6aa2f76bf847381
Is extension: false

```

**Comment by relrelb** [comment] 2022-04-22 13:42
Duplicate of #4932.

**Closed by relrelb** 2022-04-22 13:42 UTC
