### ISSUE TITLE
Error on https://incredibots.com/if/game.php

### ISSUE THREAD

**Issue by Real-The-One-Time** [ruffle-rs/ruffle#13664] opened 2023-10-22 05:09 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:418:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:418:14:
Unable to get Object
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2479:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h307f95dbfd4e7fe6 (wasm://wasm/03299f4a:wasm-function[9707]:0x98d8fb)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/03299f4a:wasm-function[6367]:0x892520)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/03299f4a:wasm-function[9515]:0x98889a)
    at core::option::expect_failed::hea22cf135ad64e98 (wasm://wasm/03299f4a:wasm-function[8929]:0x95efe3)
    at flash_lso::amf3::read::AMF3Decoder::parse_element_object::hd9b49926bf1e8bd3 (wasm://wasm/03299f4a:wasm-function[701]:0x223d6a)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h732c6207cdeec25b (wasm://wasm/03299f4a:wasm-function[595]:0x13e330)
    at flash_lso::amf3::read::AMF3Decoder::parse_object_static::h8fbeac513fdcae0f (wasm://wasm/03299f4a:wasm-function[4076]:0x76f98b)
    at flash_lso::amf3::read::AMF3Decoder::parse_element_object::hd9b49926bf1e8bd3 (wasm://wasm/03299f4a:wasm-function[701]:0x223b38)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h732c6207cdeec25b (wasm://wasm/03299f4a:wasm-function[595]:0x13e330)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at General::Database$/ExtractPartsFromByteArray()
    at General::Database$/ExtractRobotFromByteArray()
    at Game::ControllerMainMenu()
    at Main/update()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon RX 640 (0x00006987) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://incredibots.com/if/game.php
SWF URL: https://incredibots.com/if/incredibots2.swf?1604326052

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-22
Channel: nightly
Built: 2023-10-22T00:21:00.197Z
Commit: 5f217a6b9a5c593c42de5c6f3b67f4ef290a7f84
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 104991

**Comment by Lord-McSweeney** [comment] 2023-10-22 05:56
Duplicate of #10520

**Closed by Lord-McSweeney** 2023-10-22 05:56 UTC
Labels: error-report, amf
