### ISSUE TITLE
Error on https://1232382071-atari-embeds.googleusercontent.com/embeds/16cb204cf3a9d4d223a0a3fd8b0eec5d/inner-frame-minified.html

### ISSUE THREAD

**Issue by Rekid28** [ruffle-rs/ruffle#9409] opened 2023-02-04 14:41 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:750:32
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:750:32
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://xxsibxx.github.io/ruffleembedsetup112/ruffle/core.ruffle.4a4391e10bc6afa5ec80.js:1:6899)
    at std::sync::once::Once::call_once::{{closure}}::h0ab5ca72bc5fb51e (wasm://wasm/0190d1aa:wasm-function[927]:0x26ccbe)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0190d1aa:wasm-function[1399]:0x3175fd)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1fcf7cbfc0d55608 (wasm://wasm/0190d1aa:wasm-function[4964]:0x4bc0a8)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0190d1aa:wasm-function[3762]:0x47b2d0)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0190d1aa:wasm-function[5202]:0x4c0dff)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/0190d1aa:wasm-function[5020]:0x4bd061)
    at core::ops::function::FnOnce::call_once::hbb0991013a5c8917 (wasm://wasm/0190d1aa:wasm-function[1285]:0x2f7225)
    at ruffle_core::avm1::function::Executable::exec::h3aad39b3ff2b2237 (wasm://wasm/0190d1aa:wasm-function[367]:0xefa4b)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hbeb39f19b62e58f5 (wasm://wasm/0190d1aa:wasm-function[1437]:0x3212e3)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://1232382071-atari-embeds.googleusercontent.com/embeds/16cb204cf3a9d4d223a0a3fd8b0eec5d/inner-frame-minified.html?jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.lb.en.AMZ27oQJoUI.O%2Fd%3D1%2Frs%3DAHpOoo9dsXwz2g0gTMdQFEKa7ZoVvtQf4g%2Fm%3D__features__
SWF URL: https://tristansword.github.io/Chibi/dagobah_Chibi_Knight.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15117.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-27
Channel: nightly
Built: 2022-11-27T00:19:26.108Z
Commit: 0c851ecfdea3b8bd0160d81795c9c0ad7186846b
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 25
numFrames: 7
swfVersion: 9
backgroundColor: #666666
isActionScript3: false
uncompressedLength: 7676582

**Comment by Lord-McSweeney** [comment] 2023-02-08 00:45
Duplicate of #3756.

**Closed by Lord-McSweeney** 2023-02-08 00:45 UTC
Labels: error-report
