### ISSUE TITLE
Error on http://res-mspt.gamesow.com/bin/WebLaucher.html

### ISSUE THREAD

**Issue by valtercisecco** [ruffle-rs/ruffle#8809] opened 2022-12-16 16:05 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:645:21)
    at std::sync::once::Once::call_once::{{closure}}::ha7687e41144ec39a (wasm://wasm/01912dba:wasm-function[1095]:0x2a377c)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/01912dba:wasm-function[1404]:0x31a16a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb259f62dc432889a (wasm://wasm/01912dba:wasm-function[5027]:0x4bb576)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/01912dba:wasm-function[3730]:0x475899)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/01912dba:wasm-function[5268]:0x4c03cb)
    at core::option::expect_failed::h1e9a9cbb22bbd6ac (wasm://wasm/01912dba:wasm-function[5944]:0x4d395b)
    at ruffle_core::display_object::stage::Stage::root_clip::hb205d199bc57325a (wasm://wasm/01912dba:wasm-function[3734]:0x475bd8)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h30875fe83331fc42 (wasm://wasm/01912dba:wasm-function[1124]:0x2ad449)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h93056684f72a4e12 (wasm://wasm/01912dba:wasm-function[1025]:0x28dede)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://res-mspt.gamesow.com/bin/WebLaucher.html?userid=2430378&username=2430378&cm=1&server_id=S330&time=1671206690&server_name=S330&flag=bcf7e9f5305e818fcd940e7f5496829d
SWF URL: http://res-mspt.gamesow.com/bin/WebLaucher.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 OPR/93.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-16
Channel: nightly
Built: 2022-12-16T00:16:00.140Z
Commit: d26b5ab0188c86c4ee73e32a6400eb7902473148
Is extension: true

# Metadata
width: 1000
height: 600
frameRate: 24
numFrames: 1
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 26568

**Comment by n0samu** [comment] 2022-12-17 04:36
Duplicate of #8456

**Closed by n0samu** 2022-12-17 04:36 UTC
Labels: duplicate, error-report
