### ISSUE TITLE
Player got Stuck after jump or move in Megaman vs Ghosts'n Goblins.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#3119] opened 2021-02-06 12:18 UTC
**Describe the bug**
### [Issue A] Jump and Stuck
![megaman](https://user-images.githubusercontent.com/75052171/107117431-a1f18600-68bd-11eb-906d-058ad3ebd6c7.gif)

In Megaman vs Ghosts'n Goblins, the Arrow Key works without problems until you hit the jump (keyboard Z key).
**But After pressing the jump key, the following problem occurs.**

1. The player's position is fixed (stuck) at the last point and does not move.
2. Even if the player jumps or slides, it returns to where it stopped.

The player literally got stuck in the same spot after the jump. You can check the detailed symptoms through the gif at the top.

### [Issue B] Move and Stuck
![megaman-move](https://user-images.githubusercontent.com/75052171/107117787-06ade000-68c0-11eb-82a9-cb2a22346d78.gif)
(Graphics may look broken while reducing the gif size. This is not a problem with Ruffle.)

This time, simply press the Right Arrow Key to reproduce. The character seems to move well, but suddenly comes back to the starting point and gets stuck.

### Others...
Considering the results of both problems are the same, I think it is probably the same problem, but I was unable to determine where the problem was due to my inability to decompile the SWF. So, I'll also attach a file that might help.

Thank you for the hard work of the Ruffle team.

[megaman-vs-ghostsngoblins.zip](https://github.com/ruffle-rs/ruffle/files/5936788/megaman-vs-ghostsngoblins.zip)

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Probably happens on all platforms

**What platform are you using?**
Desktop: Windows 10 x64, Google Chrome (Latest), Ruffle Nightly 2021-02-06

**Comment by n0samu** [comment] 2022-10-31 22:27
Can confirm that these problems are still occurring!

**Comment by adrian17** [comment] 2022-11-02 16:59
Found the cause, https://github.com/ruffle-rs/ruffle/issues/3119 . (for the record, the variable is `newPos`)

**Comment by Toad06** [comment] 2023-01-10 10:17
Fixed by #8953

**Closed by Toad06** 2023-01-10 10:17 UTC
Labels: bug, avm1
