### ISSUE TITLE
Error on https://www.friv.cm/electricman-2/

### ISSUE THREAD

**Issue by Jahir-Saif** [ruffle-rs/ruffle#5488] opened 2021-10-17 11:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.friv.cm/ruffle/ruffle.js?x97934:1:6803)
    at std::sync::once::Once::call_once::{{closure}}::hc3bcbfc24932baf7 (https://www.friv.cm/ruffle/ea909a8547b6a00d7a49.wasm:wasm-function[1012]:0x2a17a9)
    at std::sync::once::Once::call_inner::hc44ad7f626385660 (https://www.friv.cm/ruffle/ea909a8547b6a00d7a49.wasm:wasm-function[1272]:0x2f784d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h80923a9f85d6269c (https://www.friv.cm/ruffle/ea909a8547b6a00d7a49.wasm:wasm-function[4321]:0x487ebf)
    at std::panicking::rust_panic_with_hook::he9bfe03219d715ba (https://www.friv.cm/ruffle/ea909a8547b6a00d7a49.wasm:wasm-function[3152]:0x421ab7)
    at rust_begin_unwind (https://www.friv.cm/ruffle/ea909a8547b6a00d7a49.wasm:wasm-function[4542]:0x48dab4)
    at core::panicking::panic_fmt::hbf21a3d4bbb82bf8 (https://www.friv.cm/ruffle/ea909a8547b6a00d7a49.wasm:wasm-function[4728]:0x49513f)
    at core::panicking::panic::h2fd385a887c8bf13 (https://www.friv.cm/ruffle/ea909a8547b6a00d7a49.wasm:wasm-function[4480]:0x48b0d8)
    at core::ops::function::FnOnce::call_once::hd74add08a66e90b4 (https://www.friv.cm/ruffle/ea909a8547b6a00d7a49.wasm:wasm-function[986]:0x295ae6)
    at ruffle_core::avm1::function::Executable::exec::h65ee8181ab74fba8 (https://www.friv.cm/ruffle/ea909a8547b6a00d7a49.wasm:wasm-function[398]:0x10f55a)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.friv.cm/electricman-2/
SWF URL: https://www.friv.cm/wp-content/games/electricman-2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-09-26
Channel: nightly
Built: 2021-09-26T00:31:31.264Z
Commit: 2007b0e5c320bb21601dd007ec676e77d23dbfba
Is extension: false

**Comment by relrelb** [comment] 2021-10-17 18:52
Duplicate of #4932.

**Closed by relrelb** 2021-10-17 18:52 UTC
