### ISSUE TITLE
Error on Dukateers Bling Bling Blaster

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#14099] opened 2023-11-21 16:20 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
Error stack:
```
Error: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://www.spiele-umsonst.de/ruffle/core.ruffle.f8d86a1fb855b0d2aaff.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb1c47d692dbcedf6 (wasm://wasm/0336fd8e:wasm-function[9803]:0x9b0e3e)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/0336fd8e:wasm-function[6278]:0x89b0d9)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/0336fd8e:wasm-function[9603]:0x9abc15)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h3bd7ad21da6efcfe (wasm://wasm/0336fd8e:wasm-function[3647]:0x74458e)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h1f0d50969e874f42 (wasm://wasm/0336fd8e:wasm-function[5112]:0x8336b8)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hf81a2bfb40282681 (wasm://wasm/0336fd8e:wasm-function[1177]:0x3f01e4)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::h0a8b2ddc0d5454d0 (wasm://wasm/0336fd8e:wasm-function[2117]:0x5c4722)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h6029d08287eb4e72 (wasm://wasm/0336fd8e:wasm-function[936]:0x33a938)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hf81a2bfb40282681 (wasm://wasm/0336fd8e:wasm-function[1177]:0x3f0220)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti (0x00001C82) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/dukateersblingblingblaster.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-20
Channel: nightly
Built: 2023-11-20T00:14:33.063Z
Commit: 23a65c50f22195f916dc4c19453c04a915962f89
Is extension: false

# Metadata
width: 600
height: 460
frameRate: 35
numFrames: 2
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 879262

**Comment by Lord-McSweeney** [comment] 2023-11-24 17:51
Duplicate of #11932.

**Closed by Lord-McSweeney** 2023-11-24 17:51 UTC
Labels: error-report, mixed-avm
