### ISSUE TITLE
Error on https://r2cdn-encs.r2games.com/bin/WebLaucher.html

### ISSUE THREAD

**Issue by rincoreiys** [ruffle-rs/ruffle#8957] opened 2022-12-29 02:51 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:640:21)
    at std::sync::once::Once::call_once::{{closure}}::h07c839951d6d0b0f (wasm://wasm/018ff4e6:wasm-function[1095]:0x2bb1e7)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018ff4e6:wasm-function[1400]:0x3215a4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a01fde47a9be61a (wasm://wasm/018ff4e6:wasm-function[5064]:0x4b50de)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018ff4e6:wasm-function[3744]:0x476567)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018ff4e6:wasm-function[5305]:0x4b9f15)
    at core::option::expect_failed::h1e9a9cbb22bbd6ac (wasm://wasm/018ff4e6:wasm-function[5981]:0x4cd306)
    at ruffle_core::display_object::stage::Stage::root_clip::h08fdee4bec874afd (wasm://wasm/018ff4e6:wasm-function[3749]:0x47697d)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9d7bc20f2f90af6e (wasm://wasm/018ff4e6:wasm-function[1124]:0x2c516a)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h826340abc9d077ae (wasm://wasm/018ff4e6:wasm-function[1028]:0x2a49c7)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://r2cdn-encs.r2games.com/bin/WebLaucher.html?ost=http%3A%2F%2Fcs.r2games.com&fb=1&fc=1&userid=361234368&username=361234368&time=1672282218&flag=7bed2c6398a1cd5f968eb53885578aef&cm=1&server_id=S87&server_name=
SWF URL: https://r2cdn-encs.r2games.com/bin/WebLaucher.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-29
Channel: nightly
Built: 2022-12-29T00:16:34.344Z
Commit: 8b9bae8ca610fa6081ef84a267453936784c2ac5
Is extension: true

# Metadata
width: 1000
height: 600
frameRate: 24
numFrames: 1
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 26568

**Comment by n0samu** [comment] 2022-12-29 05:09
Duplicate of #8203

**Closed by n0samu** 2022-12-29 05:09 UTC
Labels: duplicate, error-report
