### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by r-handsfield** [ruffle-rs/ruffle#6902] opened 2022-05-07 01:28 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
Error stack:
```
966/n/c.wbg.__wbg_new_df6e6ab7a65c4c4d@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.d9ac1083cc51964a91e9.js:1:6879
std::sync::once::Once::call_once::{{closure}}::h34724c5a615dd91e@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[1004]:0x29ef2c
std::sync::once::Once::call_inner::h07d0245bef259c27@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[1455]:0x317ed5
core::ops::function::FnOnce::call_once{{vtable.shim}}::h1cc7f1c9e77acd09@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[4941]:0x46f5d0
std::panicking::rust_panic_with_hook::h623ac32ff431b114@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[3268]:0x413e09
core::panicking::panic_fmt::h5118e89563022e7e@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[5026]:0x473763
core::result::unwrap_failed::ha62420c192a556da@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[4124]:0x456c06
ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h690f3fb6ae0c5eb3@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[729]:0x21d093
<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h278ed3167d1b5765@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[1740]:0x356f29
ruffle_core::font::Font::from_swf_tag::haaf38308173eb1dd@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[668]:0x200e80
ruffle_core::player::Player::set_root_movie::heca3e8c2690bfe26@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[377]:0x118816
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdd7ae6a58a47d6ba@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[567]:0x1cda9b
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8db228c2a2d3a6c6@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[2008]:0x382d74
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hd30ea1dad5a4584c@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[2229]:0x3a31fb
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hec88b2cd29ae0335@https://uploads.ungrounded.net/ruffle_wrapper/lib/be50d821cdf1f4d4809f.wasm:wasm-function[5413]:0x47ea2b
O@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.d9ac1083cc51964a91e9.js:1:3744
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.d9ac1083cc51964a91e9.js:1:2392

```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1651671727%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F840000%2F840534_voltarms-ver-1-0-final.swf%3F1651489837%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226275c93c4e3b1%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A1024%2C%22height%22%3A580%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F840000%2Fflash_840534_card.png%3Ff1650485458%22%7D
SWF URL: https://uploads.ungrounded.net/840000/840534_voltarms-ver-1-0-final.swf?1651489837

# Browser Info
Useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-04
Channel: nightly
Built: 2022-05-04T00:18:20.135Z
Commit: d1d6b56615ef701794c2b642ffb8a5b986f874e8
Is extension: false

**Comment by Herschel** [comment] 2022-05-07 17:12
Dupe of #1905

**Closed by Herschel** 2022-05-07 17:12 UTC
Labels: error-report
