### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by MooC0ww** [ruffle-rs/ruffle#4783] opened 2021-07-05 17:25 UTC
# Error Info
Error name: TypeError
Error message: Could not download wasm module
Error stack:
```
TypeError: Could not download wasm module
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1625496096%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F118000%2F118826_madnessng.swf%3F1078582222%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2260e33f2c55108%22%2C%22NewgroundsAPI_SessionID%22%3A%22EoLpZkFUdK1R8lvL1HhSa64ba0a7fb3ac341bccd478943514d39e2246f0fUsHd%22%2C%22NewgroundsAPI_UserName%22%3A%22notAfanBOI%22%2C%22NewgroundsAPI_UserID%22%3A8880272%2C%22ng_username%22%3A%22notAfanBOI%22%7D%2C%22width%22%3A600%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F118000%2Fflash_118826_card.png%3Ff1608744507%22%7D

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-07-05
Channel: nightly
Built: 2021-07-05T00:10:48.739Z
Commit: d9b5b1a0af749771cb7770bc87e649bee4109ba0

**Comment by torokati44** [comment] 2021-07-19 09:33
Duplicate of #4250.

**Closed by torokati44** 2021-07-19 09:33 UTC
