### ISSUE TITLE
Error on https://interstellar-h8pi.onrender.com/play/electric_man_2/index.html

### ISSUE THREAD

**Issue by mcking21212** [ruffle-rs/ruffle#9768] opened 2023-02-27 18:19 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:842:33
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:842:33
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.e4c416130e5620dc2233.js:1:5386)
    at std::sync::once::Once::call_once::{{closure}}::hfcec2cf17a6c3683 (wasm://wasm/0284770a:wasm-function[1956]:0x4b22bc)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0284770a:wasm-function[1887]:0x4a27fb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h315d2ce986e29f2a (wasm://wasm/0284770a:wasm-function[7354]:0x77d81c)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0284770a:wasm-function[5179]:0x6d52dd)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0284770a:wasm-function[7673]:0x78c80d)
    at core::panicking::panic::h27b5eefa3e4ff738 (wasm://wasm/0284770a:wasm-function[7084]:0x758b1e)
    at core::ops::function::FnOnce::call_once::hb46f501b2201d688 (wasm://wasm/0284770a:wasm-function[799]:0x2a7ca2)
    at ruffle_core::avm1::function::Executable::exec::hb977d246bf02dffc (wasm://wasm/0284770a:wasm-function[576]:0x1a15e3)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h22ff378a55e8134d (wasm://wasm/0284770a:wasm-function[1406]:0x3dbad5)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://interstellar-h8pi.onrender.com/play/electric_man_2/index.html
SWF URL: https://interstellar-h8pi.onrender.com/play/electric_man_2/electricman_2_hs.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-27
Channel: nightly
Built: 2023-02-27T00:20:18.745Z
Commit: 23192b41498c431f4b745a8eabefa707acc5d32a
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3575587

**Comment by Lord-McSweeney** [comment] 2023-02-27 22:41
Duplicate of #4932.

**Closed by Lord-McSweeney** 2023-02-27 22:41 UTC
Labels: error-report
