### ISSUE TITLE
Error on http://www.freeworldgroup.com/games9/gameindex/tank2012.htm

### ISSUE THREAD

**Issue by mynameisCEO** [ruffle-rs/ruffle#8152] opened 2022-10-02 05:01 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/core.ruffle.bca1371f982df7946ed0.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h73fc39b54ec29717 (wasm://wasm/017e8b06:wasm-function[1021]:0x2a382a)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017e8b06:wasm-function[1486]:0x3273a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d648d6ec080e3d2 (wasm://wasm/017e8b06:wasm-function[4920]:0x484684)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017e8b06:wasm-function[3620]:0x4413e8)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017e8b06:wasm-function[5073]:0x487acd)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/017e8b06:wasm-function[5742]:0x49a2ab)
    at ruffle_web::Ruffle::tick::h6af632469979f791 (wasm://wasm/017e8b06:wasm-function[663]:0x215ede)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h60d726a424d28b1d (wasm://wasm/017e8b06:wasm-function[5953]:0x4a14d7)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h970c39b503fdbae6 (wasm://wasm/017e8b06:wasm-function[5431]:0x491f7d)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://www.freeworldgroup.com/games9/gameindex/tank2012.htm
SWF URL: http://www.freeworldgroup.com/games9/tank2012/ENsecure.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.53
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-29
Channel: nightly
Built: 2022-09-29T00:19:25.847Z
Commit: 8f72842b2f186c4098ff277c510af41272d14377
Is extension: false

# Metadata
width: 700
height: 600
frameRate: 30
numFrames: 2
swfVersion: 15
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 9723788

**Comment by n0samu** [comment] 2022-10-02 05:10
Duplicate of #5832

**Closed by n0samu** 2022-10-02 05:10 UTC
Labels: duplicate, error-report
