### ISSUE TITLE
pictures does not display

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#7820] opened 2022-08-31 13:15 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/98996990/187685247-bc770307-1241-4281-8f6e-345e36322875.png)
[Miracle∞Hinacle.zip](https://github.com/ruffle-rs/ruffle/files/9461791/Miracle.Hinacle.zip)

### Expected behavior

![GIF3](https://user-images.githubusercontent.com/98996990/187686531-3d987f7b-8fc8-44ed-bc51-10be47bb3e97.gif)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

![image](https://user-images.githubusercontent.com/98996990/187691872-14669a38-0fb4-4717-b12d-ec21ae9d9b4e.png)

**Comment by n0samu** [comment] 2022-08-31 14:01
> [2022-08-31T13:56:56Z WARN  ruffle_core::display_object] Blend mode 'overlay' is unsupported and will not render correctly.

This is due to missing support for the 'overlay' blend mode, see #58.

**Comment by Yuri-K7** [comment] 2022-10-25 01:24
> [2022-10-25T01:11:18Z WARN  ruffle_core::display_object] Blend mode 'darken' is unsupported and will not render correctly.

This is the real problem, without displaying it, the animation is visible. It's that "folded paper" texture that have to be transparent but isn't.

The overlay mode is used  for the light spot that we can see in the expected behavior gif and aren't displayed properly either.

**Comment by n0samu** [comment] 2022-10-25 10:48
Oh that makes sense, thanks!

**Comment by Yuri-K7** [comment] 2022-10-26 20:17
I played the swf with https://github.com/ruffle-rs/ruffle/pull/8262, and the darken blend mode for the paper texture seems to correctly blend with most of the objects, excepts the characters red clothes for some reason :

![miracle blend red 2](https://user-images.githubusercontent.com/97262618/198120335-83448377-f144-46c8-8b14-4f32f1ea7866.png)
![miracle blend red](https://user-images.githubusercontent.com/97262618/198120341-caa5a601-9680-4787-8f4f-513f9ad6baf6.png)
Expected behavior : https://youtu.be/lVlZYiAuy8I?t=24 red clothes aren't supposed to get that texture.

The scenes with other blend mode effects are broken :

**Screen blend mode**
![miracle blend screen](https://user-images.githubusercontent.com/97262618/198121016-142067f9-60b6-480a-8f9e-20aee7351cf0.png)
Expected : https://youtu.be/lVlZYiAuy8I?t=108 (that sunlight scene thingy)

**Layer blend mode**
![miracle blend layer](https://user-images.githubusercontent.com/97262618/198121181-a0e81904-76a1-46a7-bd8e-f55a2b57e14b.png)
Expected : https://youtu.be/lVlZYiAuy8I?t=123 (looking at the background scene)

![miracle blend layer 2](https://user-images.githubusercontent.com/97262618/198121178-c02bbc9c-3f75-4fd7-8a9b-1793a7de6122.png)
Expected : https://youtu.be/lVlZYiAuy8I?t=153 (showing dazzling light sphere in her hand scene)

**Overlay blend mode**
![miracle blend overlay](https://user-images.githubusercontent.com/97262618/198123279-bec9a2f0-eb53-4673-a5b5-0c5070070d8f.png)
Expected : the light spot scene in OP's gif


Beside those few short scenes and the lacking outline effect, it renders properly.

**Comment by Lord-McSweeney** [comment] 2023-06-26 23:20
The only filter left unimplemented in this one is the glow filter. Performance issues can be tracked in #11755.

**Comment by waspennator** [comment] 2023-07-09 20:44
![Screenshot 2023-07-09 144304](https://github.com/ruffle-rs/ruffle/assets/78768499/375ad03d-6642-4ce8-8e58-66b9cf9915e1)
Filters should be fully resolved by #11878

**Comment by Lord-McSweeney** [comment] 2023-07-12 17:32
Fixed by #11878.

**Closed by Lord-McSweeney** 2023-07-12 17:32 UTC
Labels: bug, rendering, unimplemented, filter-effects
