### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by raulhubgit** [ruffle-rs/ruffle#9446] opened 2023-02-07 00:22 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:747:33
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:747:33
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:596:21)
    at std::sync::once::Once::call_once::{{closure}}::h0c5feae1cf72bb4f (wasm://wasm/027b8916:wasm-function[1913]:0x4901fd)
    at std::sys_common::once::generic::Once::call::he3f17a186e209b2a (wasm://wasm/027b8916:wasm-function[1848]:0x47f6d7)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h351b880b7be8aaac (wasm://wasm/027b8916:wasm-function[7126]:0x7647d1)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/027b8916:wasm-function[5027]:0x6c01e9)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/027b8916:wasm-function[7435]:0x773458)
    at core::panicking::panic::h364c37174a08a6a4 (wasm://wasm/027b8916:wasm-function[6850]:0x740071)
    at core::ops::function::FnOnce::call_once::h4c7eac4b7b4ac398 (wasm://wasm/027b8916:wasm-function[814]:0x290501)
    at ruffle_core::avm1::function::Executable::exec::h03845149f54b40f3 (wasm://wasm/027b8916:wasm-function[586]:0x19a0e1)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7618e90098b14591 (wasm://wasm/027b8916:wasm-function[1378]:0x3ac464)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Ffiles.twoplayergames.org%2Ffiles%2Fgames%2Fo1%2FElectricman_2.swf
SWF URL: https://files.twoplayergames.org/files/games/o1/Electricman_2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.78
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-06
Channel: nightly
Built: 2023-02-06T00:19:27.549Z
Commit: 00c7e8f634ac8cdb530d943a924652723828009e
Is extension: true

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment] 2023-02-07 00:25
Duplicate of #4932

**Closed by n0samu** 2023-02-07 00:25 UTC
Labels: duplicate, error-report
