### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by 3UPPER** [ruffle-rs/ruffle#13011] opened 2023-08-30 07:19 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2406:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h81b6d13caa3cc4ad (wasm://wasm/0306a596:wasm-function[9275]:0x912ca4)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/0306a596:wasm-function[6027]:0x811d71)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/0306a596:wasm-function[9115]:0x90e37d)
    at core::result::unwrap_failed::h7ed8731a69ab17a3 (wasm://wasm/0306a596:wasm-function[7183]:0x87ac30)
    at <T as wgpu::context::DynContext>::device_create_texture::h828d0e859fa3277d (wasm://wasm/0306a596:wasm-function[6707]:0x852b97)
    at wgpu::Device::create_texture::h5a68f39943465385 (wasm://wasm/0306a596:wasm-function[5094]:0x7bf463)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h881ba18cc574c618 (wasm://wasm/0306a596:wasm-function[4931]:0x7aee4a)
    at ruffle_core::display_object::render_base::h5fc6f4dcd5bf9771 (wasm://wasm/0306a596:wasm-function[565]:0x1163d2)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hdfa7ce01bfcd940a (wasm://wasm/0306a596:wasm-function[6604]:0x844d48)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1693225772%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F498000%2F498969_Super_Mario_63__2009_.swf%3F1353774292%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2296355771.47726234ceee464eb7872e82ac545d067f6052b37eb6b1%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2264eeec4327108%22%2C%22NewgroundsAPI_SessionID%22%3A%22FQa7wdLQ8nQFivsXGFIV4d6f5e79cff4f6d057eee0da6ba1e9aecbde1d4dU2CB%22%2C%22NewgroundsAPI_UserName%22%3A%22mariojapan%22%2C%22NewgroundsAPI_UserID%22%3A6796541%2C%22ng_username%22%3A%22mariojapan%22%7D%2C%22width%22%3A900%2C%22height%22%3A600%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F498000%2Fflash_498969_card.png%3Ff1623161851%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/498000/498969_Super_Mario_63__2009_.swf?1353774292

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-29
Channel: nightly
Built: 2023-08-29T00:21:45.895Z
Commit: 0ed447b42877b10fdaaf913015eb2783cd9afb04
Is extension: true

# Metadata
width: 450
height: 300
frameRate: 32
numFrames: 25
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 19339460

**Comment by n0samu** [comment] 2023-11-11 22:07
Duplicate of #11904

**Closed by n0samu** 2023-11-11 22:07 UTC
Labels: duplicate, render-wgpu, error-report
