### ISSUE TITLE
Error on https://www.pog.com/games/electricman_2_hs

### ISSUE THREAD

**Issue by BuggyColton** [ruffle-rs/ruffle#5706] opened 2021-11-23 05:53 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at u.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://fdffhapknlcjmbppidhdlkhemlkiploe/dist/ruffle.js?id=16821268551:1:7173)
    at std::sync::once::Once::call_once::{{closure}}::ha2a6e9c1727c0056 (chrome-extension://fdffhapknlcjmbppidhdlkhemlkiploe/dist/ee4caa32f0417046b099.wasm:wasm-function[998]:0x2e492f)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (chrome-extension://fdffhapknlcjmbppidhdlkhemlkiploe/dist/ee4caa32f0417046b099.wasm:wasm-function[1330]:0x355f8f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5c1b8acd952e19de (chrome-extension://fdffhapknlcjmbppidhdlkhemlkiploe/dist/ee4caa32f0417046b099.wasm:wasm-function[4703]:0x4f1f00)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (chrome-extension://fdffhapknlcjmbppidhdlkhemlkiploe/dist/ee4caa32f0417046b099.wasm:wasm-function[3305]:0x4a11e9)
    at rust_begin_unwind (chrome-extension://fdffhapknlcjmbppidhdlkhemlkiploe/dist/ee4caa32f0417046b099.wasm:wasm-function[4766]:0x4f4896)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (chrome-extension://fdffhapknlcjmbppidhdlkhemlkiploe/dist/ee4caa32f0417046b099.wasm:wasm-function[4973]:0x4ff418)
    at core::panicking::panic::hceae0c79b0247f98 (chrome-extension://fdffhapknlcjmbppidhdlkhemlkiploe/dist/ee4caa32f0417046b099.wasm:wasm-function[4699]:0x4f1731)
    at core::ops::function::FnOnce::call_once::h9c6fd61ccc88d039 (chrome-extension://fdffhapknlcjmbppidhdlkhemlkiploe/dist/ee4caa32f0417046b099.wasm:wasm-function[1042]:0x2fe92f)
    at ruffle_core::avm1::function::Executable::exec::h296dedb8318b3717 (chrome-extension://fdffhapknlcjmbppidhdlkhemlkiploe/dist/ee4caa32f0417046b099.wasm:wasm-function[417]:0x1530e7)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.pog.com/games/electricman_2_hs
SWF URL: https://img-hws.pog.com/cloud/y8-flash-game/contents/item_versions/flash_games/794/original/electricman_2_hs.swf?1521282395

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 Edg/96.0.1054.26
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-23
Channel: nightly
Built: 2021-11-23T00:14:22.573Z
Commit: cf1d0e7624fb84d23087bc0611e3dbf92dcb65e7
Is extension: true

**Comment by relrelb** [comment] 2021-11-23 16:04
Duplicate of #4932.

**Closed by relrelb** 2021-11-23 16:04 UTC
