### ISSUE TITLE
Detective Grimoire (AS2) - Stuck on Officer James convo

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#8017] opened 2022-09-18 15:07 UTC
### Describe the bug

https://www.newgrounds.com/portal/view/386799/format/flash?emulate=flash

Start up Detective Grimoire, select play and skip the intro. You'll end up on a screen talking to Officer James but James' poses are stuck in a loop and clicking Next doesn't advance the dialog.

(game is AS2)

### Expected behavior

Expected to be able to advance the conversation. Works in Flash Player.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome

**Comment by desertking** [comment] 2022-10-02 13:50
Duplicate of https://github.com/ruffle-rs/ruffle/issues/2583. and also my https://github.com/ruffle-rs/ruffle/issues/2748
Maybe it's time to fix it team 🗡️

**Comment by n0samu** [comment] 2022-10-03 08:06
Like most remaining AVM1 issues, it's a big architectural problem that would require some wide-ranging changes, so it's not likely to be fixed soon.

**Comment by desertking** [comment] 2022-10-03 08:34
Thanks it's a good idea to keep focusing on quick repairs first to get a broader amount of games to work.

**Comment by n0samu** [comment] 2022-10-06 05:42
Closing as duplicate

**Closed by n0samu** 2022-10-06 05:42 UTC
Labels: bug, duplicate
