### ISSUE TITLE
Ruffle vulkan render seems not compatible with nvidia driver

### ISSUE THREAD

**Issue by l12436** [ruffle-rs/ruffle#13467] opened 2023-10-08 14:20 UTC
### Describe the bug

when using nvidia driver with lastest ruffle, the vulkan always load failed.
here is log from vulkan: [log.gz](https://github.com/ruffle-rs/ruffle/files/12840898/log.gz)
here is vulkaninfo: [vulkaninfo.gz](https://github.com/ruffle-rs/ruffle/files/12840900/vulkaninfo.gz)

when this happened ruffle just not output anything
![image](https://github.com/ruffle-rs/ruffle/assets/2596649/571dbc60-598b-466d-8d8e-e2e85a7a2a93)

### Expected behavior

ruffle should be able to use vulkan under linux

### Affected platform

Desktop app

### Operating system

Ubuntu 22.04 with nvidia driver 525.125.06

**Comment by l12436** [comment] 2023-10-08 14:29
Now workaround is using llvmpipe which is /usr/share/vulkan/icd.d/lvp_icd.x86_64.json in my computer

**Comment by Lord-McSweeney** [comment] 2023-10-08 14:31
Unfortunately we can't help without getting some more GPU info. I can use Vulkan fine on my Ubuntu 20.04 install.
Did you try just starting Ruffle without providing it a SWF file (this should open a window with a prompt to open a SWF file)?

**Comment by l12436** [comment] 2023-10-08 14:37
GPU: Nvidia RTX 3060

open ruffle without swf file will show a screen that has some ruffle settings, it normal, only open swf file will 
![image](https://github.com/ruffle-rs/ruffle/assets/2596649/36e7f3ad-d098-4552-81b5-71c9aaece3b7)

if I using that screen to open a flash, it will only show the first screen of swf file, and no input is working. also the menu bar also not working. the audio has play normally

**Comment by Lord-McSweeney** [comment] 2023-10-08 14:42
Can you upload the specific SWF here (Github doesn't accept SWFs, you'll need to ZIP the file)? Also, can you try running `ruffle https://ruffle.rs/assets/logo-anim.swf` (the Ruffle animation logo, which is one of the least resource-intensive SWFs I know)?

**Comment by l12436** [comment] 2023-10-08 14:51
I found out that if you load flash from URL, it will render normal
but if you download is into local file, and run through local file, BUG will shown.
your ruffle logo-anim.swf will also re-produce this issue

Run through local file
![image](https://github.com/ruffle-rs/ruffle/assets/2596649/376016a1-c89b-4a30-a45f-66850916932c)
Run through url
![image](https://github.com/ruffle-rs/ruffle/assets/2596649/db737bb8-28aa-4d25-bf67-da2edc696557)

maybe you did not use vulkan when load with url, but use vulkan in local file.

**Comment by l12436** [comment] 2023-10-08 15:03
only -g vulkan work, -g gl will say that "Error: Ruffle requires hardware acceleration, but no compatible graphics device was found supporting Open GL"
which is weird for linux

**Comment by sleepycatcoding** [comment] 2023-10-09 15:52
I seem to have the same issue, opening local files, hangs/slows down the whole desktop and does not render anything in the Ruffle window, but opening the same file from a HTTP server, the issue does not appear.

GPU: NVIDIA GeForce GTX 1650 (Driver Version: 525.125.06)
System: Linux Mint 21.2
Kernel: 5.15.0-84-generic

I also bisected the issue and it seems to start with 2dcd78326144920bb6f0f39e05757fc1c077faf3.

There is a related issue in wgpu repo https://github.com/gfx-rs/wgpu/issues/4180, and that seemed to be fixed by https://github.com/gfx-rs/wgpu/pull/4184, so I think the only thing we need to do is rebase the backport on newer wgpu, since `wgpu-hal` got bumped to `1.17.2`.

**Comment by kreudom** [comment] 2023-10-09 20:14
I can confirm that 0.17.2 fixes the issue for me (see also #13422)

**Comment by l12436** [comment] 2023-10-18 00:35
after ruffle update to wgpu 0.17.2, it now working again with vulkan under nvidia

**Closed** 2023-10-18 17:42 UTC
Labels: bug, desktop, render-wgpu
