### ISSUE TITLE
Error on https://jatek-online.hu/zx0i0p/electric_man_2.htm

### ISSUE THREAD

**Issue by KissBencex** [ruffle-rs/ruffle#7531] opened 2022-08-01 13:44 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://jatek-online.hu/zx0i0p/ruffle.js:1:7158)
    at std::sync::once::Once::call_once::{{closure}}::hd1b4f64c6a058fdf (https://jatek-online.hu/zx0i0p/88fc5bf74ae9135144e7.wasm:wasm-function[984]:0x2f60fa)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://jatek-online.hu/zx0i0p/88fc5bf74ae9135144e7.wasm:wasm-function[1187]:0x33e03d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7c91d9e8737f5a50 (https://jatek-online.hu/zx0i0p/88fc5bf74ae9135144e7.wasm:wasm-function[4703]:0x505c75)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://jatek-online.hu/zx0i0p/88fc5bf74ae9135144e7.wasm:wasm-function[3238]:0x4aea41)
    at rust_begin_unwind (https://jatek-online.hu/zx0i0p/88fc5bf74ae9135144e7.wasm:wasm-function[4767]:0x5071de)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://jatek-online.hu/zx0i0p/88fc5bf74ae9135144e7.wasm:wasm-function[4980]:0x512197)
    at core::panicking::panic::hec1fc057bd0baf0b (https://jatek-online.hu/zx0i0p/88fc5bf74ae9135144e7.wasm:wasm-function[4700]:0x5054db)
    at core::ops::function::FnOnce::call_once::h83f26a94bb6d39f3 (https://jatek-online.hu/zx0i0p/88fc5bf74ae9135144e7.wasm:wasm-function[1041]:0x314750)
    at ruffle_core::avm1::function::Executable::exec::h00e69fc62e0063bd (https://jatek-online.hu/zx0i0p/88fc5bf74ae9135144e7.wasm:wasm-function[434]:0x162415)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://jatek-online.hu/zx0i0p/electric_man_2.htm
SWF URL: https://jatek-online.hu/zx0i0p/electric_man_2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.77
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-10
Channel: nightly
Built: 2022-01-10T00:14:34.425Z
Commit: b79144c122990c10fd15a53bb2afde650ab139b7
Is extension: false

**Comment by n0samu** [comment] 2022-08-01 19:49
Duplicate of #4932

**Closed by n0samu** 2022-08-01 19:49 UTC
Labels: duplicate, error-report
