### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by TheMonkeExe** [ruffle-rs/ruffle#5664] opened 2021-11-15 04:37 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:17136)
    at std::sync::once::Once::call_once::{{closure}}::h859beab4695995ed (https://ruffle.rs/demo/48cdf09c9f141b975d36.wasm:wasm-function[1051]:0x302d4f)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (https://ruffle.rs/demo/48cdf09c9f141b975d36.wasm:wasm-function[1388]:0x378cf7)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h584631ea7f5ce3f1 (https://ruffle.rs/demo/48cdf09c9f141b975d36.wasm:wasm-function[4863]:0x51183b)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (https://ruffle.rs/demo/48cdf09c9f141b975d36.wasm:wasm-function[3430]:0x4c9e21)
    at rust_begin_unwind (https://ruffle.rs/demo/48cdf09c9f141b975d36.wasm:wasm-function[4934]:0x517de3)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (https://ruffle.rs/demo/48cdf09c9f141b975d36.wasm:wasm-function[5145]:0x522afc)
    at core::panicking::panic::hceae0c79b0247f98 (https://ruffle.rs/demo/48cdf09c9f141b975d36.wasm:wasm-function[4859]:0x51106c)
    at core::ops::function::FnOnce::call_once::h2833b5d2ac249e2e (https://ruffle.rs/demo/48cdf09c9f141b975d36.wasm:wasm-function[1096]:0x31eed9)
    at ruffle_core::avm1::function::Executable::exec::he3090bb7e3912417 (https://ruffle.rs/demo/48cdf09c9f141b975d36.wasm:wasm-function[455]:0x164fab)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14150.87.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.124 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-15
Channel: nightly
Built: 2021-11-15T00:13:16.915Z
Commit: 2083d771008d997e694d050ca7ba0f27e59dd7a2
Is extension: false

**Comment by relrelb** [comment] 2021-11-15 05:49
Can you please elaborate on what SWF caused the issue? Otherwise we have no way of analyzing it.

**Comment by TheMonkeExe** [comment] 2021-11-15 11:32
can i just give you the swf ? if you want here :
[Electric Man.zip](https://github.com/ruffle-rs/ruffle/files/7538310/Electric.Man.zip)

**Comment by relrelb** [comment] 2021-11-15 12:13
So this is a duplicate of #4932.

**Closed by relrelb** 2021-11-15 12:13 UTC
Labels: error-report
