### ISSUE TITLE
Error on http://localhost:4343/cc

### ISSUE THREAD

**Issue by JaydenGoanimate** [ruffle-rs/ruffle#14868] opened 2024-01-21 01:08 UTC
# Error Info
Error name: Error
Error message: panicked at render/wgpu/src/surface.rs:195:21:
Shader blend should not need stencil buffer
Error stack:
```
Error: panicked at render/wgpu/src/surface.rs:195:21:
Shader blend should not need stencil buffer
    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h17602019b8af7fc3 (wasm://wasm/0366dd32:wasm-function[10831]:0xa26c14)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/0366dd32:wasm-function[6640]:0x911193)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/0366dd32:wasm-function[10545]:0xa207ac)
    at ruffle_render_wgpu::surface::Surface::draw_commands::h9573944c75185287 (wasm://wasm/0366dd32:wasm-function[610]:0x111f47)
    at ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::he955463055ba0962 (wasm://wasm/0366dd32:wasm-function[2565]:0x67417e)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::submit_frame::hd0b162ee7b8dca3b (wasm://wasm/0366dd32:wasm-function[768]:0x25e3f5)
    at ruffle_web::Ruffle::tick::h04abad491481789c (wasm://wasm/0366dd32:wasm-function[859]:0x2edb1d)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0a32415ba58115a3 (wasm://wasm/0366dd32:wasm-function[13017]:0xa781a5)
    at wasm_bindgen::convert::closures::invoke1_mut::h4fbef7d605bc0da6 (wasm://wasm/0366dd32:wasm-function[11752]:0xa43360)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 SUPER (0x00001F06) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1440, height: 900, depth_or_array_layers: 1 }
Player type: Object
SWF URL: /animation/414827163ad4eb60/cc.swf
Param flashvars: appCode=go&ctc=go&isEmbed=1&isLogin=Y&m_mode=school&page=&siteId=go&tlang=en_US&ut=60&bs=adam&original_asset_id=&themeId=family&apiserver=%2F&storePath=%2Fstore%2F3a981f5cb2739137%2F%3Cstore%3E&clientThemePath=%2Fstatic%2Fad44370a650793d9%2F%3Cclient_theme%3E
Param allowScriptAccess: always
Param movie: /animation/414827163ad4eb60/cc.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://localhost:4343/cc?themeId=family&bs=adam
SWF URL: http://localhost:4343/animation/414827163ad4eb60/cc.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0 (Edition std-1)
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-20
Channel: nightly
Built: 2024-01-20T00:14:55.065Z
Commit: a107d97e469a3c7b0700543d05e7be3433a9df57
Is extension: true

# Metadata
width: 960
height: 600
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1056334

**Comment by n0samu** [comment] 2024-01-21 07:22
Duplicate of #14735

**Closed by n0samu** 2024-01-21 07:22 UTC
Labels: duplicate, render-wgpu, error-report, pixelbender
