### ISSUE TITLE
Desktop GUI: Can't Spoof Url Normaly.

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#11461] opened 2023-06-10 13:10 UTC
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/75534590/c7f66955-9d80-4612-9d8f-095932185544

### Expected behavior

This can't not happen.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment] 2023-06-11 02:18
To clarify, the problem is that the URL set for the spoof URL setting is incorrectly saved for the "Custom Base URL" and "Proxy" settings too. So if you go back to the Open Advanced menu and load the SWF again without changing any settings, it may not work the second time because a custom proxy and base URL will be incorrectly set. This is especially problematic for multiasset games, which will fail to work if the proxy is set wrong. Try this version of Bejeweled for example: [bejeweled.zip](https://github.com/ruffle-rs/ruffle/files/11713692/bejeweled.zip)

https://github.com/ruffle-rs/ruffle/assets/71368227/27578d28-129d-4118-9ebe-3b483335bda8

This seems to have been caused by #11351. Pinging @moulins

**Closed** 2023-06-11 17:46 UTC
Labels: bug, desktop, regression
