### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by dmarku** [ruffle-rs/ruffle#6813] opened 2022-04-26 10:10 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
Error stack:
```
966/e/c.wbg.__wbg_new_df6e6ab7a65c4c4d@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.f6cd19fddd4f688cfec1.js:1:7708
std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[1013]:0x2ab43f
std::sync::once::Once::call_inner::h07d0245bef259c27@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[1443]:0x31e454
core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[4920]:0x4783ed
std::panicking::rust_panic_with_hook::h623ac32ff431b114@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[3240]:0x41b033
core::panicking::panic_fmt::h5118e89563022e7e@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[5002]:0x47c2a0
core::panicking::panic::he88f1b1582b09c8c@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[4918]:0x477f80
core::ops::function::FnOnce::call_once::hea116a8eeeb59311@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[1093]:0x2c1da6
ruffle_core::avm1::function::Executable::exec::h0a1a3c56ef393e7a@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[393]:0x132918
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf21230a28d8729f3@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[380]:0x1188a7
ruffle_core::avm1::activation::Activation::run_actions::h2284c9e2edc4dc25@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[312]:0x3baf2
ruffle_core::avm1::function::Executable::exec::h0a1a3c56ef393e7a@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[393]:0x133a45
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::h90c349fd3c638887@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[714]:0x21d575
ruffle_core::avm1::activation::Activation::run_actions::h2284c9e2edc4dc25@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[312]:0x3c048
ruffle_core::avm1::function::Executable::exec::h0a1a3c56ef393e7a@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[393]:0x133a45
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::h90c349fd3c638887@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[714]:0x21d575
ruffle_core::avm1::activation::Activation::run_actions::h2284c9e2edc4dc25@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[312]:0x3c048
ruffle_core::avm1::function::Executable::exec::h0a1a3c56ef393e7a@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[393]:0x133a45
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf21230a28d8729f3@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[380]:0x1188a7
ruffle_core::avm1::Avm1::run_stack_frame_for_method::h264245ebaf3e174f@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[1823]:0x37180f
ruffle_core::player::Player::run_actions::ha1daac1be36b2642@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[467]:0x17df4b
ruffle_web::Ruffle::tick::h4000be57199ea5b7@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[549]:0x1c45ad
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h499560f5f1a2f344@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[5794]:0x4929cb
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h3adcd0d2435f5e7b@https://uploads.ungrounded.net/ruffle_wrapper/lib/bc8758488c7afe706462.wasm:wasm-function[5369]:0x487367
F@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.f6cd19fddd4f688cfec1.js:1:3291
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.f6cd19fddd4f688cfec1.js:1:2392

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1650293381%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226267ba7bad395%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-18
Channel: nightly
Built: 2022-04-18T00:19:04.299Z
Commit: 3305ac69c456fe62c08d244b875775a5c9b7479e
Is extension: false

**Comment by dmarku** [comment] 2022-04-26 10:12
Ruffle crashed while playing "Chibi Knight" on Newgrounds: https://www.newgrounds.com/portal/view/526470. The crash occured exactly upon leaving the "Three Knights" Dungeon after defeating the three knights.

**Comment by relrelb** [comment] 2022-04-30 08:35
Duplicate of #3756.

**Closed by relrelb** 2022-04-30 08:35 UTC
Labels: error-report
