### ISSUE TITLE
Error on https://www.gameflare.com/embed/intrusion-2-demo/

### ISSUE THREAD

**Issue by niafas** [ruffle-rs/ruffle#10729] opened 2023-04-18 09:41 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 512 but the index is 512', core/src/bitmap/bitmap_data.rs:596:9
Error stack:
```
Error: panicked at 'index out of bounds: the len is 512 but the index is 512', core/src/bitmap/bitmap_data.rs:596:9
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://www.gameflare.com/emulators/ruffle/core.ruffle.dcbb4a112d0621488d8f.js:1:47949)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hbac0af9b7f44ed2e (wasm://wasm/02a7737e:wasm-function[8135]:0x7ee656)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02a7737e:wasm-function[5463]:0x7272f5)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02a7737e:wasm-function[8017]:0x7e92f3)
    at core::panicking::panic_bounds_check::h8c0b59521a475ac0 (wasm://wasm/02a7737e:wasm-function[6406]:0x76dbec)
    at ruffle_core::bitmap::operations::copy_channel::h9c6c101512cf728e (wasm://wasm/02a7737e:wasm-function[1300]:0x3b788c)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::copy_channel::h3a5ef16ac340cffd (wasm://wasm/02a7737e:wasm-function[804]:0x2a4d2e)
    at ruffle_core::avm2::function::Executable::exec::h459ce63d33fcd2f3 (wasm://wasm/02a7737e:wasm-function[921]:0x2f90fa)
    at ruffle_core::avm2::object::TObject::call_property::h1097bc6af6a3d974 (wasm://wasm/02a7737e:wasm-function[1057]:0x346577)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h3f129770ed67884e (wasm://wasm/02a7737e:wasm-function[2646]:0x59df97)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyChannel()
    at BitmapFont()
    at  "/Init()
    at Main/init()
    at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
    at Preloader/startup()
    at Preloader/loadingFinished()
    at Preloader/checkFrame()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/intrusion-2-demo/
SWF URL: https://data.gameflare.com/games/2808/64lzyW7CI1KVSH.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-18
Channel: nightly
Built: 2023-04-18T00:18:32.683Z
Commit: 78b386d77512b8159444131d49c9bdda34d2d681
Is extension: false

# Metadata
width: 720
height: 540
frameRate: 30
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 20750030

**Comment by n0samu** [comment] 2023-04-19 01:37
Duplicate of #10618

**Closed by n0samu** 2023-04-19 01:37 UTC
Labels: duplicate, rendering, error-report
