### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by saradonnelly97** [ruffle-rs/ruffle#10472] opened 2023-03-31 03:41 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:347:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:347:26
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2212:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb025c08ea6ea4a5 (wasm://wasm/02ac91b6:wasm-function[8130]:0x801cff)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02ac91b6:wasm-function[5419]:0x735c1b)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02ac91b6:wasm-function[8014]:0x7fcf10)
    at core::panicking::panic::h54beb3f515dd3c6d (wasm://wasm/02ac91b6:wasm-function[7424]:0x7c8c43)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hf9a6c3a4f2422dbb (wasm://wasm/02ac91b6:wasm-function[618]:0x1e5527)
    at ruffle_core::loader::Loader::preload_tick::hb9e75697781a2c49 (wasm://wasm/02ac91b6:wasm-function[796]:0x2b1530)
    at ruffle_web::Ruffle::tick::hd2a4887144973149 (wasm://wasm/02ac91b6:wasm-function[690]:0x243154)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h022e5d2803da3015 (wasm://wasm/02ac91b6:wasm-function[9742]:0x83a783)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::he1e1e06d8de4de3c (wasm://wasm/02ac91b6:wasm-function[8641]:0x80d530)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=&sp=0&questionSet=&r=8871366&&width=640&height=500&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-31
Channel: nightly
Built: 2023-03-31T00:21:30.510Z
Commit: ad2e60adcc0eadd6927143fb97d3e6bf5e52f5d7
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by n0samu** [comment] 2023-04-22 07:33
Game is Catch the Petpet: https://www.neopets.com/games/game.phtml?game_id=1034

This error is caused by an AVM1 movie loading an AVM2 movie, which Ruffle does not yet support.

**Comment by n0samu** [comment] 2023-04-22 07:36
Closing as duplicate of #9972

**Closed by n0samu** 2023-04-22 07:36 UTC
Labels: error-report, mixed-avm
