### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=mobile&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1613144486%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F443000%2F443187_FFSX6_Part_2.swf%3F1212882468%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22602701eb62bed%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A550%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F443000%2Fflash_443187_card.png%3Ff1608485501%22%7D

### ISSUE THREAD

**Issue by killergo1** [ruffle-rs/ruffle#3233] opened 2021-02-12 22:33 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1613144486:1:6799)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[1327]:0x26b533)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[1603]:0x29e7b9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[4637]:0x381cb3)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[3509]:0x3576e4)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[4145]:0x375297)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[4983]:0x387384)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[4868]:0x385c81)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[4984]:0x3873ba)
    at std::thread::local::LocalKey<T>::with::hd56bd27bc5f64716 (https://uploads.ungrounded.net/ruffle_wrapper/lib/70f2ff166435b3e35b95e8688d461a08.wasm:wasm-function[783]:0x1d71bd)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=mobile&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1613144486%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F443000%2F443187_FFSX6_Part_2.swf%3F1212882468%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22602701eb62bed%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A550%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F443000%2Fflash_443187_card.png%3Ff1608485501%22%7D
SWF URL: https://uploads.ungrounded.net/443000/443187_FFSX6_Part_2.swf?1212882468

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; Redmi Note 9S) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-12
Channel: nightly
Built: 2021-02-12T00:17:25.708Z
Commit: da86f7fc5afbe93c8b378366c550a0622f59d5b6

**Comment by relrelb** [comment] 2021-04-03 18:39
Duplicate of #3695.

**Closed by relrelb** 2021-04-03 18:39 UTC
