### ISSUE TITLE
Error on https://electricman2.club/

### ISSUE THREAD

**Issue by execution** [ruffle-rs/ruffle#6220] opened 2022-02-06 00:36 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
966/n/c.wbg.__wbg_new_df6e6ab7a65c4c4d@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js:1:6964
std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[1032]:0x303aa1
std::sync::once::Once::call_inner::h9279eef47cf85b81@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[1171]:0x3397a9
core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[4680]:0x4d6936
std::panicking::rust_panic_with_hook::h47a0e203360b6c10@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[3195]:0x48c602
core::panicking::panic_fmt::h4ca53049f45e3264@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[4954]:0x4e26c1
core::panicking::panic::h35778e3c18266c93@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[4677]:0x4d645d
core::ops::function::FnOnce::call_once::h63635e87c343a6bd@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[1068]:0x319d58
ruffle_core::avm1::function::Executable::exec::h2f4c44ab37d80dc0@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[414]:0x157014
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hd2ac2ca7aecc5e6d@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[624]:0x223065
ruffle_core::avm1::activation::Activation::do_action::h07f2242128234aad@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[313]:0x49737
ruffle_core::avm1::activation::Activation::run_actions::h22c8af94557c5815@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[3041]:0x47b04c
ruffle_core::avm1::Avm1::run_stack_frame_for_action::h3672d0baa6296ff5@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[1169]:0x338fc9
ruffle_core::player::Player::run_actions::h64e0ea011a76d899@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[463]:0x19126d
ruffle_web::Ruffle::tick::hf8a4913ed3d1fe2b@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[618]:0x21784c
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h66b090fd1f9bd1c2@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[5540]:0x4eef2b
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb36bbfafe0278747@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js line 1 > WebAssembly.instantiate:wasm-function[5092]:0x4e489a
k@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js:1:3575
c@https://electricman2.club/core.ruffle.dc5de1903c2c3222d97f.js:1:2521

```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://electricman2.club/electric-man-2.swf
Param game: https://electricman2.club/electric-man-2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://electricman2.club/
SWF URL: https://electricman2.club/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-21
Channel: nightly
Built: 2022-01-21T00:17:44.053Z
Commit: 4d8db1e64d36cc59c98c63b6883971cf01c5c9e3
Is extension: false

**Comment by Poopooracoocoo** [comment] 2022-02-06 01:01
Duplicate of #4932

**Closed by Poopooracoocoo** 2022-02-06 01:01 UTC
Labels: duplicate, error-report
