### ISSUE TITLE
Error on https://f.kbhgames.com/RS/game.php

### ISSUE THREAD

**Issue by L0stMedia** [ruffle-rs/ruffle#18026] opened 2024-09-21 18:53 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Queue::write_texture
    Copy of X 0..252 would end up overrunning the bounds of the Destination texture of X size 250

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Queue::write_texture
    Copy of X 0..252 would end up overrunning the bounds of the Destination texture of X size 250


    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1fd47a4dc99e652a91f6.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::hfb561c222a4e70eb (wasm://wasm/ruffle_web.wasm-0320e85a:wasm-function[12739]:0x9846c6)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h8a2a563fa204b611 (wasm://wasm/ruffle_web.wasm-0320e85a:wasm-function[9790]:0x914631)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-0320e85a:wasm-function[6358]:0x80526c)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-0320e85a:wasm-function[9509]:0x9052d1)
    at ruffle_web.wasm.core::ops::function::Fn::call::h76c12b2f57631e6d (wasm://wasm/ruffle_web.wasm-0320e85a:wasm-function[6585]:0x81e699)
    at ruffle_web.wasm.wgpu::backend::wgpu_core::ContextWgpuCore::handle_error::hccb1a8488f7079b4 (wasm://wasm/ruffle_web.wasm-0320e85a:wasm-function[2130]:0x52386d)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::queue_write_texture::h72304744d7085155 (wasm://wasm/ruffle_web.wasm-0320e85a:wasm-function[9554]:0x9099cf)
    at ruffle_web.wasm.wgpu::Queue::write_texture::h0812742b8b216e69 (wasm://wasm/ruffle_web.wasm-0320e85a:wasm-function[10018]:0x92157f)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::update_texture::h9db57eead5583775 (wasm://wasm/ruffle_web.wasm-0320e85a:wasm-function[2412]:0x5936ef)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::applyFilter()
    at _-Qy/_-1T()
    at _-Qy/_-Lk()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at _-VW/_-k1()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Graphics (0x0000A7AC) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (1000, 625, 1)

# Page Info
Page URL: https://f.kbhgames.com/RS/game.php?r=//f.kbhgames.com/2018/swf/echoes-operation-stranglehold.swf&w=800&h=500&warnsupport=true
SWF URL: https://f.kbhgames.com/2018/swf/echoes-operation-stranglehold.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-09-21
Channel: nightly
Built: 2024-09-21T00:06:13.792Z
Commit: 09b3bc25ba902f8c11e6c49cbb77f30a888b79b8
Is extension: false

# Metadata
width: 800
height: 500
frameRate: 30
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 65179379

**Comment by Croworbit** [comment] 2024-09-21 19:03
I wouldn't get your hopes up. this is a player for flash games, not necessarily a preservation project

if this website doesn't have all the files needed to run the game, ruffle can't fix that.

**Comment by Lord-McSweeney** [comment] 2024-09-21 19:06
All the files are present, this is an issue with Ruffle

**Comment by L0stMedia** [comment] 2024-09-21 19:12
> All the files are present, this is an issue with Ruffle

What is the best course of action for me to do then?

**Comment by n0samu** [comment] 2024-09-22 03:35
@L0stMedia You can play the game in Flashpoint: https://flashpointarchive.org/downloads

Can you give us a little more info on when exactly this crash occurred, though? I haven't been able to get it to happen myself.

**Comment by L0stMedia** [comment] 2024-09-22 04:05
> @L0stMedia You can play the game in Flashpoint: https://flashpointarchive.org/downloads
> 
> Can you give us a little more info on when exactly this crash occurred, though? I haven't been able to get it to happen myself.
So on Kongregate and KBHgames, I would get right past the tutorial of the game and then my game would give me an error. I'm sorry, but that's all the information I really have as of the moment.

**Comment by n0samu** [comment] 2024-09-22 06:57
Thanks, that info is helpful! I've reproduced the bug now and will pass this info to the Ruffle devs.

**Comment by n0samu** [comment] 2024-09-22 07:10
Duplicate of #10549

**Closed by n0samu** 2024-09-22 07:10 UTC
Labels: render-wgpu, error-report
