### ISSUE TITLE
Error on https://r2cdn-encs.r2games.com/bin/WebLaucher.html

### ISSUE THREAD

**Issue by rincoreiys** [ruffle-rs/ruffle#8767] opened 2022-12-13 09:26 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6972)
    at std::sync::once::Once::call_once::{{closure}}::h4f7445f5740cc36b (wasm://wasm/019183be:wasm-function[926]:0x26bfb3)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/019183be:wasm-function[1401]:0x319534)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7dfd384227ef6d86 (wasm://wasm/019183be:wasm-function[4989]:0x4bd65f)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/019183be:wasm-function[3768]:0x47c447)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/019183be:wasm-function[5230]:0x4c24bc)
    at core::option::expect_failed::h2290d18a0c9a6a24 (wasm://wasm/019183be:wasm-function[5911]:0x4d5c16)
    at ruffle_core::display_object::stage::Stage::root_clip::h2ccf9ee627d305ec (wasm://wasm/019183be:wasm-function[3704]:0x476d85)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h01e4ce08ffe0eff4 (wasm://wasm/019183be:wasm-function[1122]:0x2ac718)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfdd4e385a365b716 (wasm://wasm/019183be:wasm-function[1024]:0x28e5da)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://r2cdn-encs.r2games.com/bin/WebLaucher.html?ost=http%3A%2F%2Fcs.r2games.com&fb=1&fc=1&userid=361234368&username=361234368&time=1670923545&flag=3310fc85d21f509098aa51ac28bb5d27&cm=1&server_id=S173&server_name=
SWF URL: https://r2cdn-encs.r2games.com/bin/WebLaucher.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.46
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-13
Channel: nightly
Built: 2022-12-13T00:16:27.259Z
Commit: 02360b28dca80263c8e93cde2467c487688770ac
Is extension: true

# Metadata
width: 1000
height: 600
frameRate: 24
numFrames: 1
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 26568

**Comment by n0samu** [comment] 2022-12-13 09:57
Duplicate of #8203

**Closed by n0samu** 2022-12-13 09:57 UTC
Labels: duplicate, error-report
