### ISSUE TITLE
The game appears then goes black

### ISSUE THREAD

**Issue by Craozz** [ruffle-rs/ruffle#16294] opened 2024-05-12 12:50 UTC
### Describe the bug

The game appears then goes black

### Expected behavior

The game appears then goes black

### Content Location

https://game24h.vn/tinh-diem/chiec-cau-cua-jerry-c145g742b16.html

### Affected platform

Desktop app

### Operating system

Windows 10 Enterprise

### Browser

Microsoft Edge Version 117.0.2045.31 (Official build) (64-bit)

**Comment by Lord-McSweeney** [comment] 2024-05-12 14:09
Duplicate of #13263

**Closed by Lord-McSweeney** 2024-05-12 14:09 UTC
Labels: bug
