### ISSUE TITLE
Error on https://r2cdn-encs.r2games.com/bin/WebLaucher.html

### ISSUE THREAD

**Issue by leblancp995** [ruffle-rs/ruffle#8572] opened 2022-11-18 09:26 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:572:9
Error stack:
```
966/W/n.wbg.__wbg_new_f9bb493369a83c12@moz-extension://ddc60592-c440-4723-b77e-800e176e5222/dist/966.js:1:6972
std::sync::once::Once::call_once::{{closure}}::h868aa5cd1fef1a90@:wasm-function[1059]:0x2a65b0
std::sync::once::Once::call_inner::h34aee843864daceb@:wasm-function[1352]:0x30d6aa
core::ops::function::FnOnce::call_once{{vtable.shim}}::h117918d4b59dff10@:wasm-function[4886]:0x497566
std::panicking::rust_panic_with_hook::h70a0e195f4db2a29@:wasm-function[3635]:0x458b1e
core::panicking::panic_fmt::h751be80779d42b53@:wasm-function[5116]:0x49c0ce
core::option::expect_failed::h2290d18a0c9a6a24@:wasm-function[5775]:0x4ae07b
ruffle_core::display_object::stage::Stage::root_clip::h9bca82d36afedc2b@:wasm-function[3573]:0x4536a8
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0951ed43f743a068@:wasm-function[1106]:0x2b54ed
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h07eb7e3176dfa379@:wasm-function[1006]:0x2961bd
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hb52c7898c215ef92@:wasm-function[2141]:0x3c01d0
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hda4ce02dc8cb37c1@:wasm-function[5477]:0x4a5986
closure2900 externref shim@:wasm-function[5597]:0x4a88be
C@moz-extension://ddc60592-c440-4723-b77e-800e176e5222/dist/966.js:1:2728
c@moz-extension://ddc60592-c440-4723-b77e-800e176e5222/dist/966.js:1:2253

```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://r2cdn-encs.r2games.com/bin/WebLaucher.html?ost=http%3A%2F%2Fcs.r2games.com&fb=1&fc=1&userid=4481315&username=4481315&time=1668763562&flag=8b231a09018d6e984567156a982d367e&cm=1&server_id=S79&server_name=
SWF URL: https://r2cdn-encs.r2games.com/bin/WebLaucher.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-16
Channel: nightly
Built: 2022-11-16T00:18:41.332Z
Commit: b3debc96afab2882c70ee27cf4dd5230874e803b
Is extension: true

# Metadata
width: 1000
height: 600
frameRate: 24
numFrames: 1
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 26568

**Comment by n0samu** [comment] 2022-12-13 09:57
Duplicate of #8203

**Closed by n0samu** 2022-12-13 09:57 UTC
Labels: duplicate, avm2, error-report
