### ISSUE TITLE
Castaway 2 is unplayable

### ISSUE THREAD

**Issue by ActionWavele** [ruffle-rs/ruffle#12843] opened 2023-08-19 15:13 UTC
### Describe the bug

the game doesn't respond to pressing space and that is the only way to continue from the beginning 
![ery](https://github.com/ruffle-rs/ruffle/assets/120395932/41542a3e-88ca-4c41-84c4-9e5a308021b4)

### Expected behavior

playing the game should be allowed

### Affected platform

Desktop app

### Operating system

windows 10

### Additional information

also this game has that annoying bouncing ad which shouldn't bounce, and no one has fixed yet

[castaway-2-11261.zip](https://github.com/ruffle-rs/ruffle/files/12386179/castaway-2-11261.zip)

**Comment by Lord-McSweeney** [comment] 2023-08-19 15:14
The annoying bouncing ad will be fixed by #11005.

**Comment by Lord-McSweeney** [comment] 2023-08-19 15:23
For whatever reason this crashes on the OpenGL backend for me (see #12844). I can reproduce the bug on the WGPU backend, but I don't see any errors, and no relevant stubs. Here are the stubs:
```
Encountered stub: AVM2 flash.display.Loader.unload()
Encountered stub: AVM2 flash.media.Sound constructor with arguments
Encountered stub: AVM2 flash.net.registerClassAlias()
Encountered stub: AVM2 flash.net.NetConnection.addHeader()
Encountered stub: AVM2 flash.net.NetConnection.connect() with non-null command
Encountered stub: AVM2 flash.net.Responder constructor
Encountered stub: AVM2 flash.net.NetConnection.call()
Encountered stub: AVM2 flash.text.TextField.restrict setter
```

**Comment by Lord-McSweeney** [comment] 2024-01-29 01:59
This was reported to be still reproducible.

**Comment by Aaron1011** [comment] 2024-02-04 20:50
This is caused by the fact that we don't update the `FocusManager` when the focused dobj is no longer on the stage. We need to figure out exactly when the focus should get cleared.

**Comment by n0samu** [comment] 2024-07-30 05:08
This seems to be fixed now! 🎉

**Closed by n0samu** 2024-07-30 05:08 UTC
Labels: bug, avm2

**Comment by nooki-sama** [comment] 2025-03-23 17:47
okay so you can press space now, though as soon as i got hit by the snake with the ring around it i get perma stunned and cant move, childhood feels taken away from me
