### ISSUE TITLE
Keyboard isn't triggered on iOS when selecting text input

### ISSUE THREAD

**Issue by bls1999** [ruffle-rs/ruffle#3069] opened 2021-02-04 04:33 UTC
**Describe the bug**
In all the games I've tested, selecting a text input doesn't trigger the iOS keyboard to pop up. The cursor shows on text fields when a font isn't anti-aliased (as normal), but it doesn't show on anti-aliased fonts.

**Expected behavior**
The keyboard should pop up as if selecting a regular textbox on a webpage or in iOS.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted version, nightly 2021-02-04.

**What platform are you using?**
iPhone -- iOS Safari, iOS 14.4

**Comment by Herschel** [comment] 2021-02-04 07:03
Duplicate of #1532.

**Closed by Herschel** 2021-02-04 07:03 UTC
Labels: bug

**Comment by bls1999** [comment] 2021-02-06 18:56
> Duplicate of #1532.

Sorry, I'll do a better search next time. Thanks!
