### ISSUE TITLE
Error on https://www.vap.co.jp/elfenlied/staff.html    

### ISSUE THREAD

**Issue by Andym8** [ruffle-rs/ruffle#14425] opened 2023-12-17 05:43 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:1315:26:
called `Option::unwrap()` on a `None` value
Error stack:
```
Error: panicked at core/src/avm1/activation.rs:1315:26:
called `Option::unwrap()` on a `None` value
    at imports.wbg.__wbg_new_a64e3f2afc2cf2f8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h853353504563e1d1 (wasm://wasm/03419ee6:wasm-function[9859]:0x9d4552)
    at std::panicking::rust_panic_with_hook::hbf46ef0245cc9589 (wasm://wasm/03419ee6:wasm-function[6306]:0x8c04f4)
    at core::panicking::panic_fmt::h14c85a61aa3d538e (wasm://wasm/03419ee6:wasm-function[9650]:0x9cf16b)
    at core::panicking::panic::hb41dbc4083d9884e (wasm://wasm/03419ee6:wasm-function[9283]:0x9b3ce4)
    at ruffle_core::avm1::activation::Activation::run_actions::h894657fc1e85833e (wasm://wasm/03419ee6:wasm-function[567]:0x167c6)
    at ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h2a7f3c782c9418c2 (wasm://wasm/03419ee6:wasm-function[1161]:0x41cd54)
    at ruffle_core::player::Player::run_actions::h7942d33ce646cef1 (wasm://wasm/03419ee6:wasm-function[943]:0x37a805)
    at ruffle_web::Ruffle::tick::h7941e6f51cb5e552 (wasm://wasm/03419ee6:wasm-function[862]:0x312e2a)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hc975d7d5cb614626 (wasm://wasm/03419ee6:wasm-function[12003]:0xa23c62)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x000046A3) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.vap.co.jp/elfenlied/staff.html
SWF URL: https://www.vap.co.jp/elfenlied/staff.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-17
Channel: nightly
Built: 2023-12-17T00:15:52.659Z
Commit: 375c99e601b28683058d09ad7ea76deb423ced1f
Is extension: true

# Metadata
width: 750
height: 450
frameRate: 24
numFrames: 89
swfVersion: 6
backgroundColor: #FFE5EE
isActionScript3: false
uncompressedLength: 68249

**Comment by Andym8** [comment] 2023-12-17 05:44
will this ever get fixed ;(

**Comment by n0samu** [comment] 2023-12-17 06:14
Duplicate of #8912. I appreciate the reminder about this issue though, because I think I mistook it for a standard mixed AVM issue last time. This actually seems to be a separate issue related to loading text files in AVM1, maybe also related to encodings or Japanese characters. Hopefully we can look into it soon.

**Closed by n0samu** 2023-12-17 06:14 UTC
Labels: duplicate, error-report
