### ISSUE TITLE
Changing tabs in chrome causes animations to lag behind music.

### ISSUE THREAD

**Issue by Guy-Sowden** [ruffle-rs/ruffle#1661] opened 2020-11-23 04:15 UTC
the item in question is 
https://archive.org/details/cows_with_guns_202011

it seem when you change tabs the video is paused but the audio track continues. causing audio to be out of sync with the animation.

no errors are thrown

Chrome 86, windows 10

**Comment by parkerlreed** [comment] 2020-11-23 04:32
Can verify I see the same behavior on Chromium 87

**Comment by Herschel** [comment] 2020-11-23 05:03
Thanks for the report! Dupe of #347.

**Closed by Herschel** 2020-11-23 05:03 UTC
