### ISSUE TITLE
Error on https://es.y8.com/games/zombidle

### ISSUE THREAD

**Issue by MichaTruki** [ruffle-rs/ruffle#17544] opened 2024-08-17 04:52 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/f9e3de5/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/f9e3de5/flash-lso/src/amf3/read.rs:435:14:
Unable to get Object
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3743:21)
    at ruffle_web.wasm.js_sys::Error::new::h69e363d74b15dc09 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[12698]:0x980ef6)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h16a6474029cce8cf (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[9749]:0x9100de)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[6288]:0x806882)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[10158]:0x92b23d)
    at ruffle_web.wasm.core::option::expect_failed::h9d0c8588efc786aa (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[8879]:0x8dda4c)
    at ruffle_web.wasm.flash_lso::amf3::read::AMF3Decoder::parse_single_element::hbd15cbf71a6adcf3 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[783]:0xec0b1)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::utils::byte_array::read_object::hc3719501fe387ca9 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[1219]:0x36e201)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::ha40ac113834e121c (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[1368]:0x3ccabc)
    at ruffle_web.wasm.ruffle_core::avm2::object::TObject::call_method::h8997ce94768e7100 (wasm://wasm/ruffle_web.wasm-031e4e6e:wasm-function[2436]:0x5a6305)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at com.berzerkstudio::ModelFla/loadFromByteArray()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadNextFla()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadAllFlas()
    at com.zombidle::MainGameWebStarling/loadModelFlas()
    at com.zombidle::MainGameWebStarling/loadZipFile()
    at Function/apply()
    at com.lachhh.io::Callback/call()
    at com.lachhhStarling::StarlingMain$/startGame()
    at MethodInfo-3324()
    at starling.utils::AssetManager/loadQueue()
    at com.lachhhStarling::StarlingMain$/loadAssetsDesktop()
    at MethodInfo-3322()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-2018()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 600 (0x00003185) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (960, 640, 1)

# Page Info
Page URL: https://es.y8.com/games/zombidle
SWF URL: https://img.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/74199/original/zombidle.swf?1522273530

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-08-17
Channel: nightly
Built: 2024-08-17T00:05:11.451Z
Commit: d885697d9b1060ae0886b22fe0d12b6c6e56bd5d
Is extension: true

# Metadata
width: 960
height: 640
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 22341052

**Comment by n0samu** [comment] 2024-08-17 05:10
Duplicate of #10174

**Closed by n0samu** 2024-08-17 05:10 UTC
Labels: duplicate, error-report
