### ISSUE TITLE
Error on https://simple-education.xyz/swf.html

### ISSUE THREAD

**Issue by Arrow141** [ruffle-rs/ruffle#6948] opened 2022-05-11 19:28 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.765f7e9782b5d9856d69.js:1:7487)
    at std::sync::once::Once::call_once::{{closure}}::hc3464e04dbb9beda (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.11/83fc461cb755d7e745c6.wasm:wasm-function[979]:0x290599)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.11/83fc461cb755d7e745c6.wasm:wasm-function[1427]:0x30b370)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h44f701de063d4daa (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.11/83fc461cb755d7e745c6.wasm:wasm-function[4913]:0x462ec2)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.11/83fc461cb755d7e745c6.wasm:wasm-function[3249]:0x4089d4)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.11/83fc461cb755d7e745c6.wasm:wasm-function[4994]:0x466b20)
    at core::panicking::panic::he88f1b1582b09c8c (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.11/83fc461cb755d7e745c6.wasm:wasm-function[4911]:0x462a5b)
    at core::ops::function::FnOnce::call_once::h0e85a184fa37f64b (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.11/83fc461cb755d7e745c6.wasm:wasm-function[1071]:0x2ab560)
    at ruffle_core::avm1::function::Executable::exec::h114e6421d0b212e0 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.11/83fc461cb755d7e745c6.wasm:wasm-function[379]:0x103bba)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h39023dca8cfb590d (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.11/83fc461cb755d7e745c6.wasm:wasm-function[557]:0x1b372e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://simple-education.xyz/swf.html?notebook=electricman2
SWF URL: https://simple-education.xyz/swffiles/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14588.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.59 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-11
Channel: nightly
Built: 2022-05-11T00:16:36.001Z
Commit: 84b865018d79f006640692f1f4c9d3b8c1faca04
Is extension: false

**Comment by relrelb** [comment] 2022-05-12 10:30
Duplicate of #4932.

**Closed by relrelb** 2022-05-12 10:30 UTC
Labels: error-report
