### ISSUE TITLE
Error on https://www.izzygames.com/metalix-tower-defense-t2269.html

### ISSUE THREAD

**Issue by dragonslayer555** [ruffle-rs/ruffle#6008] opened 2022-01-09 04:57 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
r/s.wbg.__wbg_new_df6e6ab7a65c4c4d@https://www.spiele-umsonst.de/ruffle/ruffle.js?v31:1:6703
std::sync::once::Once::call_once::{{closure}}::hd1b4f64c6a058fdf@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[983]:0x2f9eff
std::sync::once::Once::call_inner::hf9144d66ddc67dec@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[1181]:0x33f23b
core::ops::function::FnOnce::call_once{{vtable.shim}}::h7c91d9e8737f5a50@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[4674]:0x5052ae
std::panicking::rust_panic_with_hook::h606d7c7f7a423b98@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[3234]:0x4b0abb
rust_begin_unwind@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[4737]:0x5067f9
core::panicking::panic_fmt::h6314b5c91abe7349@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[4949]:0x5116c1
core::result::unwrap_failed::hd584efb7b84bf326@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[3989]:0x4ee3ca
ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hc83a1cdc841376ca@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[700]:0x250e12
<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::replace_shape::h2eff2f11d49ef1c4@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[2171]:0x427453
ruffle_core::drawing::Drawing::render::h0be51281b250957e@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[809]:0x28b326
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h62c68d123be17901@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[3200]:0x4adf82
ruffle_core::display_object::render_base::h6b56754f9fb937ae@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[1600]:0x3ac970
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::he54cb64b96d4577e@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[3794]:0x4de9e6
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h62c68d123be17901@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[3200]:0x4ae1a1
ruffle_core::display_object::render_base::h6b56754f9fb937ae@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[1600]:0x3ac970
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::he54cb64b96d4577e@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[3794]:0x4de9e6
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h62c68d123be17901@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[3200]:0x4abdcb
ruffle_core::display_object::render_base::h6b56754f9fb937ae@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[1600]:0x3ac970
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::render::h59a3b6e5887e1c9f@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[1329]:0x36a5f8
ruffle_web::Ruffle::tick::h8820f05fbb36117f@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[593]:0x1fad3b
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0fd3c78b3db543bb@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[5534]:0x51def7
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h546afa1d1f99eb9c@https://www.spiele-umsonst.de/ruffle/cd7e6f7aaff275ad7eb9.wasm:wasm-function[5094]:0x5137fa
x@https://www.spiele-umsonst.de/ruffle/ruffle.js?v31:1:2659
a@https://www.spiele-umsonst.de/ruffle/ruffle.js?v31:1:2535

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.izzygames.com/metalix-tower-defense-t2269.html
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/metalixtd.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-04
Channel: nightly
Built: 2022-01-04T00:13:48.083Z
Commit: a9e86a73cf17845356a3bd38fe42c50e584a693c
Is extension: false

**Comment by torokati44** [comment] 2022-01-12 01:56
Duplicate of #5628.

**Closed by torokati44** 2022-01-12 01:56 UTC
Labels: error-report
