### ISSUE TITLE
Error on https://www.play-games.com/game/24956/electric-man.html

### ISSUE THREAD

**Issue by goongon** [ruffle-rs/ruffle#6561] opened 2022-03-29 12:10 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.play-games.com/js/frontend/vendor/ruffle/core.ruffle.f933f6b66e3a45092f95.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::ha27d2325af960a5b (https://www.play-games.com/js/frontend/vendor/ruffle/1efd2883e915fdd7784d.wasm:wasm-function[1024]:0x2c4eb0)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://www.play-games.com/js/frontend/vendor/ruffle/1efd2883e915fdd7784d.wasm:wasm-function[1467]:0x334f07)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf341824e07fc18a0 (https://www.play-games.com/js/frontend/vendor/ruffle/1efd2883e915fdd7784d.wasm:wasm-function[4915]:0x48382d)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://www.play-games.com/js/frontend/vendor/ruffle/1efd2883e915fdd7784d.wasm:wasm-function[3231]:0x426a51)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://www.play-games.com/js/frontend/vendor/ruffle/1efd2883e915fdd7784d.wasm:wasm-function[5201]:0x48f8e7)
    at core::panicking::panic::h5d6906e2c1099660 (https://www.play-games.com/js/frontend/vendor/ruffle/1efd2883e915fdd7784d.wasm:wasm-function[4912]:0x483354)
    at core::ops::function::FnOnce::call_once::h9b3e858464c5e596 (https://www.play-games.com/js/frontend/vendor/ruffle/1efd2883e915fdd7784d.wasm:wasm-function[1111]:0x2db4ad)
    at ruffle_core::avm1::function::Executable::exec::h85473c3832012ed8 (https://www.play-games.com/js/frontend/vendor/ruffle/1efd2883e915fdd7784d.wasm:wasm-function[394]:0x122771)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h3a8e27a001f84d8e (https://www.play-games.com/js/frontend/vendor/ruffle/1efd2883e915fdd7784d.wasm:wasm-function[434]:0x15c392)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.play-games.com/game/24956/electric-man.html
SWF URL: https://www.play-games.com/files/swf/electric-man-1611670590.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14469.41.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.57 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-15
Channel: nightly
Built: 2022-03-15T00:16:55.349Z
Commit: e9167cf43c44f6511145301c0127722446b6ece5
Is extension: false

**Comment by relrelb** [comment] 2022-03-29 22:05
Duplicate of #4932.

**Closed by relrelb** 2022-03-29 22:05 UTC
Labels: error-report
