### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Minty4614** [ruffle-rs/ruffle#8299] opened 2022-10-15 14:58 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.166543534d0d6de8f27f.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::hf9ee3cf8881ab9cc (wasm://wasm/01800c06:wasm-function[1030]:0x2a119d)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01800c06:wasm-function[1498]:0x327c9b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e53a26a8ce616de (wasm://wasm/01800c06:wasm-function[4930]:0x4868ea)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01800c06:wasm-function[3625]:0x444699)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01800c06:wasm-function[5121]:0x48a63c)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/01800c06:wasm-function[4985]:0x48785c)
    at core::ops::function::FnOnce::call_once::h091fd8f8c21617a7 (wasm://wasm/01800c06:wasm-function[1130]:0x2c1b89)
    at ruffle_core::avm1::function::Executable::exec::hd32a15aff1d93747 (wasm://wasm/01800c06:wasm-function[366]:0xfdbe3)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hddf815c9794947c7 (wasm://wasm/01800c06:wasm-function[407]:0x1352e9)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1665754563%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F363000%2F363447_electricman2hs_fwg.swf%3F1180965842%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22634aca05f1ee6%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F363000%2Fflash_363447_card.png%3Ff1643296262%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/363000/363447_electricman2hs_fwg.swf?1180965842

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14816.131.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-14
Channel: nightly
Built: 2022-10-14T00:22:21.438Z
Commit: b0b0e55c240e7d505d1ee64f61764de554885e5f
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3275243

**Comment by n0samu** [comment] 2022-10-15 15:10
Duplicate of #4932

**Closed by n0samu** 2022-10-15 15:10 UTC
Labels: duplicate, error-report
