### ISSUE TITLE
Error on https://localhost/index.html

### ISSUE THREAD

**Issue by DxnisRu** [ruffle-rs/ruffle#15641] opened 2024-03-19 16:14 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096


    at J.n.wbg.__wbg_new_3a66822ed076951c (https://localhost/ruffle/core.ruffle.e326c566e0469c00ddc9.js:1:73764)
    at js_sys::Error::new::h4a1ed0b447087498 (wasm://wasm/038fc87e:wasm-function[13744]:0xb00ca9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2dca30bde0528490 (wasm://wasm/038fc87e:wasm-function[11354]:0xaab2cf)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/038fc87e:wasm-function[6912]:0x96a86d)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/038fc87e:wasm-function[11067]:0xaa482d)
    at core::ops::function::Fn::call::h98cd4260b74faf10 (wasm://wasm/038fc87e:wasm-function[7233]:0x981df7)
    at wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::h93030089deff7c27 (wasm://wasm/038fc87e:wasm-function[5743]:0x8fc1b5)
    at wgpu::backend::wgpu_core::ContextWgpuCore::handle_error::hb67f0380418a0e1e (wasm://wasm/038fc87e:wasm-function[3027]:0x6ed0bd)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h644d50d01f277e52 (wasm://wasm/038fc87e:wasm-function[10324]:0xa71368)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h4c3c179bb13cf8e3 (wasm://wasm/038fc87e:wasm-function[9626]:0xa4aacf)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (ARM, Mali-G68 MC4, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 4096, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://localhost/index.html
SWF URL: https://localhost/jacksmith.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 14; SM-A346B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.105 Mobile Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-02-23
Channel: nightly
Built: 2024-02-23T00:05:28.155Z
Commit: d2e854fb732f4356625f2726d2b62641aba0cc6e
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by evilpie** [comment] 2024-04-09 15:04
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:04 UTC
Labels: render-wgpu, error-report
