### ISSUE TITLE
Error on http://www.oyunkuzusu.com/gladyator-2-tam-ekran.html

### ISSUE THREAD

**Issue by Ahmetay882** [ruffle-rs/ruffle#13075] opened 2023-09-05 11:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.171538958d5cb4380d39.js:1:51650)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b6e7c02fb5a9114 (wasm://wasm/03081d2e:wasm-function[9276]:0x9194e2)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/03081d2e:wasm-function[6063]:0x819152)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/03081d2e:wasm-function[9118]:0x914c28)
    at core::result::unwrap_failed::h7ed8731a69ab17a3 (wasm://wasm/03081d2e:wasm-function[7202]:0x8816d5)
    at <T as wgpu::context::DynContext>::device_create_texture::hce7852bd7d20a8e9 (wasm://wasm/03081d2e:wasm-function[6718]:0x85904d)
    at wgpu::Device::create_texture::h3d3b2d581b201f48 (wasm://wasm/03081d2e:wasm-function[5119]:0x7c5154)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::ha4b647a1b2e2bcc5 (wasm://wasm/03081d2e:wasm-function[4958]:0x7b7e56)
    at ruffle_core::display_object::render_base::h15b1267069433e1b (wasm://wasm/03081d2e:wasm-function[565]:0x116438)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hdb28de37fce3d5f0 (wasm://wasm/03081d2e:wasm-function[6631]:0x84bd05)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1898, height: 840, depth_or_array_layers: 1 }

# Page Info
Page URL: http://www.oyunkuzusu.com/gladyator-2-tam-ekran.html
SWF URL: http://www.oyunkuzusu.com/oyunlar/gladyator_2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-05
Channel: nightly
Built: 2023-09-05T00:23:52.734Z
Commit: dabc2d56b91e677f4a08fa166968db8d5dff4e8d
Is extension: false

# Metadata
width: 640
height: 420
frameRate: 30
numFrames: 278
swfVersion: 8
backgroundColor: #FFCC66
isActionScript3: false
uncompressedLength: 5227470

**Comment by n0samu** [comment] 2023-09-05 22:41
Duplicate of #13074

**Closed by n0samu** 2023-09-05 22:41 UTC
Labels: duplicate, error-report
