### ISSUE TITLE
Ruffle Error on https://freesimon.org/

### ISSUE THREAD

**Issue by CassKat** [ruffle-rs/ruffle#16625] opened 2024-06-07 02:31 UTC
![Uploading ruffleissue.jpg…]()
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:67050
    at Array.forEach (<anonymous>)
    at vi.f.wasm (https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:66977)
    at https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:35299
    at Array.reduce (<anonymous>)
    at vi.e (https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:35276)
    at o (https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:2595)
    at o.next (<anonymous>)
    at https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:2895
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freesimon.org/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by evilpie** [comment] 2024-06-22 20:32
Duplicate of #16705.

**Closed by evilpie** 2024-06-22 20:32 UTC
