### ISSUE TITLE
Regression: Wake Up The Box 3 is stuck on loading screen

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#14067] opened 2023-11-19 12:59 UTC
### Describe the bug

The game is currently stuck on the loading screen, last working build is ruffle-nightly-2023_11_10

### Expected behavior

start the game

### Content Location

Game URL - https://www.gameflare.com/online-game/wake-up-the-box-3/
SWF URL - https://data.gameflare.com/games/2231/8IcAVEucA3EXcc.swf

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by MartySVK** [comment] 2023-11-19 13:09
looks like the problem is @Aaron1011 's PR https://github.com/ruffle-rs/ruffle/pull/12386

**Comment by Lord-McSweeney** [comment] 2023-11-19 16:05
This is SWFv10

**Comment by Aaron1011** [comment] 2023-11-19 20:45
This was caused by my PR - the avm2 button frame is still different with SWF > 9.

**Comment by Aaron1011** [comment] 2023-11-19 20:47
This will be fixed by https://github.com/ruffle-rs/ruffle/pull/14073

**Closed** 2023-11-20 01:52 UTC
Labels: bug, avm2, regression
