### ISSUE TITLE
Error on https://extrememath.org/swf.html

### ISSUE THREAD

**Issue by dpfivndsldcjkgbr** [ruffle-rs/ruffle#8465] opened 2022-11-03 14:08 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.85b17119080a80c7d668.js:1:6805)
    at std::sync::once::Once::call_once::{{closure}}::hbf2034d80a3bea7d (wasm://wasm/01824e8e:wasm-function[1220]:0x2c969d)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01824e8e:wasm-function[1498]:0x319489)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc013e36522e0a1cf (wasm://wasm/01824e8e:wasm-function[4912]:0x48d811)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01824e8e:wasm-function[3609]:0x44b0fd)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01824e8e:wasm-function[5133]:0x491f82)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/01824e8e:wasm-function[4967]:0x48e783)
    at core::ops::function::FnOnce::call_once::h0ed82986c4b1a19e (wasm://wasm/01824e8e:wasm-function[1107]:0x29f1b1)
    at ruffle_core::avm1::function::Executable::exec::h981112079d828fef (wasm://wasm/01824e8e:wasm-function[363]:0xde9ac)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::he050cabdcb83777e (wasm://wasm/01824e8e:wasm-function[1070]:0x291779)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://extrememath.org/swf.html?notebook=electricman2
SWF URL: https://extrememath.org/swffiles/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15117.86.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-03
Channel: nightly
Built: 2022-11-03T00:18:21.788Z
Commit: 6dbf78ae59aa325145ca8d55902cbfc3cd23a24e
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3641749

**Comment by n0samu** [comment] 2022-11-03 22:05
Duplicate of #4932

**Closed by n0samu** 2022-11-03 22:05 UTC
Labels: duplicate, error-report
