### ISSUE TITLE
Error on http://www.freeworldgroup.com/games9/gameindex/tank2012chinese.htm

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#7430] opened 2022-07-16 23:18 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:576:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:576:14
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/core.ruffle.fc1803165034f0fa22f7.js:1:6065)
    at std::sync::once::Once::call_once::{{closure}}::h85c54b3c29530646 (http://www.freeworldgroup.com/ruffle/9d9a64ebb81e38075891.wasm:wasm-function[1208]:0x2b17d5)
    at std::sync::once::Once::call_inner::hecc7c66a7de7e98e (http://www.freeworldgroup.com/ruffle/9d9a64ebb81e38075891.wasm:wasm-function[1385]:0x2e8b80)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7b3cf28d15b79444 (http://www.freeworldgroup.com/ruffle/9d9a64ebb81e38075891.wasm:wasm-function[4688]:0x42c014)
    at std::panicking::rust_panic_with_hook::h8888bbc201384d7b (http://www.freeworldgroup.com/ruffle/9d9a64ebb81e38075891.wasm:wasm-function[3078]:0x3ddc28)
    at core::panicking::panic_fmt::h18b15be283411c65 (http://www.freeworldgroup.com/ruffle/9d9a64ebb81e38075891.wasm:wasm-function[4871]:0x43216e)
    at core::option::expect_failed::h710363cb391a4194 (http://www.freeworldgroup.com/ruffle/9d9a64ebb81e38075891.wasm:wasm-function[5484]:0x43f571)
    at ruffle_core::display_object::stage::Stage::root_clip::ha4499f7abe1d1cd0 (http://www.freeworldgroup.com/ruffle/9d9a64ebb81e38075891.wasm:wasm-function[3405]:0x3f3d10)
    at ruffle_web::Ruffle::tick::h2d21b703c5219555 (http://www.freeworldgroup.com/ruffle/9d9a64ebb81e38075891.wasm:wasm-function[608]:0x1bf077)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0806d4a9f9086613 (http://www.freeworldgroup.com/ruffle/9d9a64ebb81e38075891.wasm:wasm-function[5662]:0x44710c)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games9/gameindex/tank2012chinese.htm
SWF URL: http://www.freeworldgroup.com/games9/tank2012/CNsecure.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-14
Channel: nightly
Built: 2022-07-14T00:14:22.180Z
Commit: cfc9f51c5d3c53c4591e6e2f631f1be17234ea5b
Is extension: false

**Comment by n0samu** [comment] 2022-08-21 12:13
Duplicate of #5832

**Closed by n0samu** 2022-08-21 12:13 UTC
Labels: duplicate, error-report
