### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by apika-ally** [ruffle-rs/ruffle#3992] opened 2021-04-13 19:13 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1618322710:1:6924
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hf7fd718057964857]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h9d91fa0fae16500f]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h91d2023e5afe1929]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hfae0ccd566ab4384]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1c9b256bef969e15]@[wasm code]
wasm-stub@[native code]
F@https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1618322710:1:4006
a@https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1618322710:1:2841
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1618322710%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F512000%2F512407_hank2009.swf%3F1605221180%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2244370491.06a06106ce57067d1b45062eeeb2a09867e3be02a78396%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226075ec8b7c205%22%2C%22NewgroundsAPI_SessionID%22%3A%22eXP5LDo8fvQe1jGvJ6VTcbc0ec42b2e9a8ba5f6cd31e8448abb88731548athIE%22%2C%22NewgroundsAPI_UserName%22%3A%22nightspiss%22%2C%22NewgroundsAPI_UserID%22%3A8275175%2C%22ng_username%22%3A%22nightspiss%22%7D%2C%22width%22%3A720%2C%22height%22%3A405%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F512000%2Fflash_512407_card.png%3Ff1605218420%22%7D
SWF URL: https://uploads.ungrounded.net/512000/512407_hank2009.swf?1605221180

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-13
Channel: nightly
Built: 2021-04-13T00:43:43.545Z
Commit: ae9be9882160c4fead586570d0d15376cf965f64

**Comment by Poopooracoocoo** [comment] 2021-11-29 10:54
Link to Madness Accelerant (Madness Day 2009) on Newgrounds:
https://www.newgrounds.com/portal/view/512407

**Comment by Poopooracoocoo** [comment] 2021-11-29 11:14
Duplicate of #3694

**Closed by Poopooracoocoo** 2021-11-29 11:14 UTC
Labels: duplicate, error-report
