### ISSUE TITLE
Ruffle panics before eventually loading multi-asset Flash media

### ISSUE THREAD

**Issue by madprogramer** [ruffle-rs/ruffle#2408] opened 2021-01-12 09:33 UTC
Error Info
-----

Error name: Panic (attempting to unwrap a TypeError)
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch TypeError: Failed to fetch)', web/src/navigator.rs:162:18 Stack: Error

Error stack:

Error:
```
panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch TypeError: Failed to fetch)', web/src/navigator.rs:162:18
Stack: Error
at dist/core.ruffle.js:1 (Object.ee)
at <anonymous>:3 (__wbg_new_59cb74e423758ede)
```

Player Info
-----

Allows script access: true
Player type: Object
SWF URL: koshiandoh.com/top_060720.swf
Param movie: koshiandoh.com/top_060720.swf

Page Info
-----

Page URL: http://koshiandoh.com/index.shtml
SWF URL: http://koshiandoh.com/top_060720.swf

Browser Info
-----

Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

Ruffle Info
-----

Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z (?)
Commit: cce3a81

**Comment by devdce** [comment] 2021-01-12 12:01
confirmed

**Comment by n0samu** [comment] 2022-10-04 03:09
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.

**Closed by n0samu** 2022-10-04 03:09 UTC
Labels: error-report
