### ISSUE TITLE
Error on https://flash.riolubruh.repl.co/electricman2.html

### ISSUE THREAD

**Issue by mpegues12** [ruffle-rs/ruffle#6802] opened 2022-04-25 13:49 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://flash.riolubruh.repl.co/core.ruffle.f5e16f52204d9499c76d.js:1:7572)
    at std::sync::once::Once::call_once::{{closure}}::h8cc59a0b8a1b03e2 (https://flash.riolubruh.repl.co/6eb258805834d3c235ef.wasm:wasm-function[1023]:0x2c3c5c)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://flash.riolubruh.repl.co/6eb258805834d3c235ef.wasm:wasm-function[1457]:0x330fa0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haa76f48d1b3c2435 (https://flash.riolubruh.repl.co/6eb258805834d3c235ef.wasm:wasm-function[4908]:0x4827fd)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://flash.riolubruh.repl.co/6eb258805834d3c235ef.wasm:wasm-function[3229]:0x42594c)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://flash.riolubruh.repl.co/6eb258805834d3c235ef.wasm:wasm-function[5191]:0x48e899)
    at core::panicking::panic::h5d6906e2c1099660 (https://flash.riolubruh.repl.co/6eb258805834d3c235ef.wasm:wasm-function[4905]:0x482324)
    at core::ops::function::FnOnce::call_once::hd40a0ab4006ca041 (https://flash.riolubruh.repl.co/6eb258805834d3c235ef.wasm:wasm-function[1109]:0x2d9eda)
    at ruffle_core::avm1::function::Executable::exec::h34f53eabf17bd49f (https://flash.riolubruh.repl.co/6eb258805834d3c235ef.wasm:wasm-function[391]:0x11c595)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hdac537d2f3ea07cf (https://flash.riolubruh.repl.co/6eb258805834d3c235ef.wasm:wasm-function[431]:0x1565a8)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://flash.riolubruh.repl.co/electricman2.html
SWF URL: https://flash.riolubruh.repl.co/swf/e2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14388.61.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.107 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-18
Channel: nightly
Built: 2022-03-18T00:17:54.702Z
Commit: e5b6e8c8b7198cd016bb0f37a683718f30a3bcac
Is extension: false

**Comment by Poopooracoocoo** [comment] 2022-04-27 05:13
Duplicate of #4932

**Closed by Poopooracoocoo** 2022-04-27 05:13 UTC
Labels: error-report
