### ISSUE TITLE
Error on https://freegames.org/mahjong-titans/

### ISSUE THREAD

**Issue by mieketo** [ruffle-rs/ruffle#6883] opened 2022-05-03 18:36 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/activation.rs:501:57
Error stack:
```
@https://freegames.org/js/ruffle/ruffle.js:1:6342
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h02eac160d339afc2]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h123718ba3bf480af]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h285dc015a87be5a4]@[wasm code]
<?>.wasm-function[core::panicking::panic::h0abe4e7a620ae568]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::do_action::h7da99c43fec9791d]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::Avm1::run_stack_frame_for_action::hc5eedf081711a902]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::hb7593a543e99557c]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_frame::h42af906b99d492b6]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::tick::h39e13d2cc5f5f98e]@[wasm code]
<?>.wasm-function[std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::ha6ff201f499682f2]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h38b6df632eacf5a9]@[wasm code]
wasm-stub@[native code]
R@https://freegames.org/js/ruffle/ruffle.js:1:3993
a@https://freegames.org/js/ruffle/ruffle.js:1:2825
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freegames.org/mahjong-titans/
SWF URL: https://freegames.org/swf/mahjong.g

# Browser Info
Useragent: Mozilla/5.0 (iPad; CPU OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/101.0.4951.44 Mobile/15E148 Safari/604.1
OS: iPad

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-20
Channel: nightly
Built: 2021-01-20T01:07:01.467Z
Commit: 75967e377576cad9a679f1172d0b7f6e5ffd85c0

**Comment by Herschel** [comment] 2022-05-03 18:43
Dupe of #6608, iOS 15.4

**Closed by Herschel** 2022-05-03 18:43 UTC
