### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by notchris12** [ruffle-rs/ruffle#10949] opened 2023-05-05 12:52 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:618:51
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:618:51
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://ruffle.rs/demo/339.index.js:1:48973)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb6ca29193f91948 (wasm://wasm/02b84d56:wasm-function[8422]:0x8126f2)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02b84d56:wasm-function[5515]:0x734295)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02b84d56:wasm-function[8275]:0x80cf0a)
    at core::panicking::panic::hea78c4e8b318407d (wasm://wasm/02b84d56:wasm-function[7579]:0x7d2aeb)
    at ruffle_core::bitmap::bitmap_data::BitmapData::update_dirty_texture::h69e242bde85db84e (wasm://wasm/02b84d56:wasm-function[1285]:0x3d9cb0)
    at ruffle_core::bitmap::operations::draw::hba4e79233cd20803 (wasm://wasm/02b84d56:wasm-function[803]:0x2c6134)
    at ruffle_core::avm2::globals::flash::display::bitmap_data::draw::hae63a30bb1476f73 (wasm://wasm/02b84d56:wasm-function[810]:0x2cc20c)
    at ruffle_core::avm2::function::Executable::exec::hb5981ebd76854dce (wasm://wasm/02b84d56:wasm-function[783]:0x2ac20e)
    at ruffle_core::avm2::object::TObject::call_property::hbef9b7a23152cbbb (wasm://wasm/02b84d56:wasm-function[1119]:0x386ea4)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at swordGame.models::LobbySoldier/spriteSheetBlit()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-05
Channel: nightly
Built: 2023-05-05T00:19:58.361Z
Commit: 58d786b8694d46fd12a10418604968d067ac7684
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9363111

**Comment by n0samu** [comment] 2023-05-08 07:07
Duplicate of #10927

**Closed by n0samu** 2023-05-08 07:07 UTC
Labels: duplicate, error-report
