### ISSUE TITLE
Error on https://www.minigamers.com/games/adventure-time-jumping-finn~10525/

### ISSUE THREAD

**Issue by LETSGOBAI** [ruffle-rs/ruffle#12881] opened 2023-08-21 22:27 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 0..4200 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 0..4200 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.95374868be5907a95f46.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc22db995a124727b (wasm://wasm/03004632:wasm-function[9276]:0x8fe053)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/03004632:wasm-function[6084]:0x80aee9)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/03004632:wasm-function[9118]:0x8f99c5)
    at core::ops::function::Fn::call::h7ead762dc2a125d1 (wasm://wasm/03004632:wasm-function[6750]:0x83d8c1)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h2884fc23ac7c775c (wasm://wasm/03004632:wasm-function[4864]:0x772312)
    at wgpu::backend::direct::Context::handle_error::h32d323b60d1dea0d (wasm://wasm/03004632:wasm-function[2606]:0x5dc0c4)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h2c10c4507b11d2c7 (wasm://wasm/03004632:wasm-function[6659]:0x836c6f)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h78226c564349474c (wasm://wasm/03004632:wasm-function[5699]:0x7ee700)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h994ed2778eed2263 (wasm://wasm/03004632:wasm-function[1653]:0x495d6d)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at currentGame.gameObjects::Level/update()
    at currentGame.states::StateGame/update()
    at ilmare.StateLib::StateManager/update()
    at Main/update()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.utils::Timer/onUpdate()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.minigamers.com/games/adventure-time-jumping-finn~10525/
SWF URL: https://games.macrojuegos.com/14000/14245/fda1e6c1a3701698ff948acfbfccgfuy.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-21
Channel: nightly
Built: 2023-08-21T00:23:16.665Z
Commit: 89cc0eb31d2fd38a545cefccb0b44e4a22807d5e
Is extension: false

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 7452286

**Comment by n0samu** [comment] 2023-08-22 00:11
Duplicate of #12879

**Closed by n0samu** 2023-08-22 00:11 UTC
Labels: duplicate, error-report
