### ISSUE TITLE
Fancy Pants Adventure World 2 is a horror game

### ISSUE THREAD

**Issue by SelixGithub** [ruffle-rs/ruffle#2966] opened 2021-01-29 20:29 UTC
Some images, such as the backgrounds, fail to render. 
"Moving" sprites, some ground textures, UI, and collision still work. 
https://user-images.githubusercontent.com/77213983/106324102-6d325e80-622d-11eb-8506-d58f30e4f683.mov

**Comment by relrelb** [comment] 2021-08-07 16:17
Duplicate of #4646.

**Closed by relrelb** 2021-08-07 16:17 UTC
