### ISSUE TITLE
Error on https://www.electricman.space/

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#8076] opened 2022-09-24 18:01 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://jponbockdnfhhjljflbflmnokmpnlieh/dist/966.js:1:5312)
    at std::sync::once::Once::call_once::{{closure}}::h8ea9ab9bf1a6fa87 (wasm://wasm/01821942:wasm-function[1012]:0x29c225)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01821942:wasm-function[1477]:0x328413)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7b268efc0b6187e5 (wasm://wasm/01821942:wasm-function[4965]:0x48fa2c)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01821942:wasm-function[3648]:0x44be72)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01821942:wasm-function[5118]:0x495852)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/01821942:wasm-function[5021]:0x4909e8)
    at core::ops::function::FnOnce::call_once::h7628fce5e7bf8dee (wasm://wasm/01821942:wasm-function[1098]:0x2b9984)
    at ruffle_core::avm1::function::Executable::exec::he62c50bb92746ad9 (wasm://wasm/01821942:wasm-function[360]:0xfa1a9)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::ha32257fbf3878d3b (wasm://wasm/01821942:wasm-function[893]:0x271b96)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: electricman.swf
Param game: electricman.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.electricman.space/
SWF URL: https://www.electricman.space/electricman.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.42
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-23
Channel: nightly
Built: 2022-09-23T00:15:34.189Z
Commit: a17352a01ad50a0f52666c054b22cec51306689c
Is extension: true

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3571190

**Comment by n0samu** [comment] 2022-09-24 18:26
Duplicate of #4932

**Closed by n0samu** 2022-09-24 18:26 UTC
Labels: duplicate, error-report
