### ISSUE TITLE
Ruffle Error on https://learn.genetics.utah.edu/content/cloning/clickandclone/

### ISSUE THREAD

**Issue by campbellschm** [ruffle-rs/ruffle#5712] opened 2021-11-23 23:42 UTC
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://learn.genetics.utah.edu/content/cloning/clickandclone/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14150.74.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-22
Channel: nightly
Built: 2020-12-22T00:39:03.522Z
Commit: f7797f85d6a2c340b0dfb97c42a3cc04be32b997

**Comment by Poopooracoocoo** [comment] 2021-11-29 09:46
Do you happen to also be running the Ruffle extension?

**Comment by Poopooracoocoo** [comment] 2021-11-29 09:48
Duplicate of #5713

**Closed by Poopooracoocoo** 2021-11-29 09:48 UTC
Labels: duplicate, error-report
