### ISSUE TITLE
Error on https://www.furaffinity.net/view/36925686/

### ISSUE THREAD

**Issue by Michaelalaska1998** [ruffle-rs/ruffle#5480] opened 2021-10-14 21:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:493:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:493:50
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://d.furaffinity.net/media/ruffle-nightly-2021_08_16-selfhosted/ruffle.js:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::hc21fddb12f017ead (https://d.furaffinity.net/media/ruffle-nightly-2021_08_16-selfhosted/8e1df94e23318dc419ca.wasm:wasm-function[891]:0x23d49a)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (https://d.furaffinity.net/media/ruffle-nightly-2021_08_16-selfhosted/8e1df94e23318dc419ca.wasm:wasm-function[1127]:0x296bb9)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h43f0c52a841ff0e2 (https://d.furaffinity.net/media/ruffle-nightly-2021_08_16-selfhosted/8e1df94e23318dc419ca.wasm:wasm-function[3955]:0x413637)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (https://d.furaffinity.net/media/ruffle-nightly-2021_08_16-selfhosted/8e1df94e23318dc419ca.wasm:wasm-function[2836]:0x3aa427)
    at rust_begin_unwind (https://d.furaffinity.net/media/ruffle-nightly-2021_08_16-selfhosted/8e1df94e23318dc419ca.wasm:wasm-function[4168]:0x41902e)
    at core::panicking::panic_fmt::h1fea623755fffed7 (https://d.furaffinity.net/media/ruffle-nightly-2021_08_16-selfhosted/8e1df94e23318dc419ca.wasm:wasm-function[4323]:0x41fe6b)
    at core::result::unwrap_failed::he87c4da48746e896 (https://d.furaffinity.net/media/ruffle-nightly-2021_08_16-selfhosted/8e1df94e23318dc419ca.wasm:wasm-function[3509]:0x400d81)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hf0b3b6ca61b93af4 (https://d.furaffinity.net/media/ruffle-nightly-2021_08_16-selfhosted/8e1df94e23318dc419ca.wasm:wasm-function[632]:0x1b7808)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::hb6d04ce5d0e9e1ac (https://d.furaffinity.net/media/ruffle-nightly-2021_08_16-selfhosted/8e1df94e23318dc419ca.wasm:wasm-function[2202]:0x358fc0)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: //d.furaffinity.net/art/amiafurryoraminotidkk/1592892868/1592892868.amiafurryoraminotidkk_dolhpv.swf
Param movie: //d.furaffinity.net/art/amiafurryoraminotidkk/1592892868/1592892868.amiafurryoraminotidkk_dolhpv.swf
Param quality: high
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.furaffinity.net/view/36925686/
SWF URL: https://d.furaffinity.net/art/amiafurryoraminotidkk/1592892868/1592892868.amiafurryoraminotidkk_dolhpv.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 5.0.1; YOGA Tablet 2-1050L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-16
Channel: nightly
Built: 2021-08-16T00:12:09.649Z
Commit: f4da77c400bc26770b4af865b8fe9a3147f78ba6
Is extension: false

**Comment by Herschel** [comment] 2021-10-18 02:08
Duplicate of #5479.

**Closed by Herschel** 2021-10-18 02:08 UTC
Labels: duplicate, nsfw, render-webgl
