### ISSUE TITLE
Error on https://games-porno.net/porno-igry-online/meet-fuck/1977-naruto-trakhaet-tsunade.html

### ISSUE THREAD

**Issue by Nurbakjam** [ruffle-rs/ruffle#7453] opened 2022-07-20 08:33 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.17.10/src/fill.rs:1942:74
Error stack:
```
@https://games-porno.net/ruffle/ruffle.js?2:1:7775
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h8b88e6aa08fbb40d]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hf9144d66ddc67dec]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h3ab0488d22755852]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h606d7c7f7a423b98]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h6314b5c91abe7349]@[wasm code]
<?>.wasm-function[core::panicking::panic::hec1fc057bd0baf0b]@[wasm code]
<?>.wasm-function[core::slice::sort::shift_tail::hb74b78854b18b9a6]@[wasm code]
<?>.wasm-function[core::slice::sort::recurse::he4dc5a8dfa28e650]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::process_events::h80c8ad9f349584c9]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_impl::hf2ed013f62132d10]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_path::h80b66e367dedfa7c]@[wasm code]
<?>.wasm-function[ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h574ca6939809b723]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h472520d2afcf3e0c]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h2023dc93a22e7a17]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h289d50fd1b558c2a]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::he58c7f1bb3469412]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h51bf8062cb35abe8]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9064c2b7a191eb23]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h963ed9cd7b2e9f2d]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hac88976f78e5472d]@[wasm code]
wasm-stub@[native code]
F@https://games-porno.net/ruffle/ruffle.js?2:1:4011
a@https://games-porno.net/ruffle/ruffle.js?2:1:2536
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /images/games_porno/fall-asleep-tsunade.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://games-porno.net/porno-igry-online/meet-fuck/1977-naruto-trakhaet-tsunade.html
SWF URL: https://games-porno.net/images/games_porno/fall-asleep-tsunade.swf

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 YaBrowser/22.7.10 YaApp_iOS/120.00 YaApp_iOS_Browser/120.00 Safari/604.1 SA/3
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-13
Channel: nightly
Built: 2021-12-13T00:13:39.740Z
Commit: cc4853236efee5f15ac82d12df146a3af16c744a
Is extension: false

**Comment by n0samu** [comment] 2022-07-20 08:41
Duplicate of #6608. Updating your device to iOS 15.5 should fix the issue!

**Closed by n0samu** 2022-07-20 08:41 UTC
Labels: duplicate, nsfw, error-report
