### ISSUE TITLE
Madness Accelerant Red screen error

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#9505] opened 2023-02-10 17:55 UTC
### Describe the bug

https://user-images.githubusercontent.com/80902993/218160712-024cf872-6ed7-4613-8f31-b8e2b9a02a69.mp4

this is red screen bug but it's working game it's good
there is problem ''red screen''
https://www.newgrounds.com/portal/view/512407

### Expected behavior

it's official, this is flash player
this is old video for youtube
https://www.youtube.com/watch?v=saHLq_d8cvU&ab_channel=sirjavier
it's official

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Edge

### Additional information

Ryzen 3
Radeon Graphic
8GB RAM (5.95 GB RAM)

my pc

**Comment by n0samu** [comment] 2023-02-11 04:19
I haven't looked at the SWF itself, but looking at the video, this seems to be caused by our incorrect implementation of the blur filter. The same problem also happens in [Symphony](http://www.notdoppler.com/symphony.php), which uses a blur filter.

**Comment by n0samu** [comment] 2023-03-03 14:11
Turns out this wasn't the same problem, and it is now fixed! Not sure what fixed it though.

**Comment by waspennator** [comment] 2023-03-13 01:43
Red Screen when Tricky transforms issue seems to have returned as of the latest nightly build.

**Comment by Lord-McSweeney** [comment] 2023-03-13 02:13
Broken in latest nightly.

**Comment by Lord-McSweeney** [comment] 2023-03-13 02:57
Commit de8448e00acb2815828ef3f5b9e58ce9edb3a711 seems to cause the issue. @Aaron1011, pinging you to let you know.

**Comment by waspennator** [comment] 2023-03-13 03:04
Doing further regression testing, the issue seemed to last appear in build 2023-02-24, then fixed itself on 2023-02-25 and stayed that way until said commit broke it for tonights build apparently.

**Comment by Lord-McSweeney** [comment] 2023-03-16 01:04
Specifically, the issue now can be fixed by reverting the last commit in #9845 (which was squashed).

**Comment by Lord-McSweeney** [comment] 2023-03-19 14:57
Fixed by #10170.

**Closed by Lord-McSweeney** 2023-03-19 14:57 UTC
Labels: bug, rendering, regression
