### ISSUE TITLE
Error on https://www.minijuegos.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by Estalin1501** [ruffle-rs/ruffle#15748] opened 2024-03-23 23:56 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f77055/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f77055/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ba112b96c7e0a3c21070.js:1:73847)
    at js_sys::Error::new::hef550139643a029c (wasm://wasm/03a2c03a:wasm-function[13900]:0xb18259)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdd59db8e12749b4f (wasm://wasm/03a2c03a:wasm-function[11486]:0xac1813)
    at std::panicking::rust_panic_with_hook::h6b00a1542b7e827c (wasm://wasm/03a2c03a:wasm-function[7064]:0x98b1ab)
    at core::panicking::panic_fmt::h7d22643b0becf577 (wasm://wasm/03a2c03a:wasm-function[11194]:0xabb13d)
    at core::option::expect_failed::hd82c6d6933db2709 (wasm://wasm/03a2c03a:wasm-function[9760]:0xa5fe02)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::hd5cc392abbdaa6b1 (wasm://wasm/03a2c03a:wasm-function[774]:0x1091c4)
    at nom::multi::many_m_n::{{closure}}::h356fb109010f9972 (wasm://wasm/03a2c03a:wasm-function[3426]:0x75ff8c)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::hd5cc392abbdaa6b1 (wasm://wasm/03a2c03a:wasm-function[774]:0x10680f)
    at flash_lso::amf3::read::AMF3Decoder::parse_object_static::h54992503221adb54 (wasm://wasm/03a2c03a:wasm-function[4509]:0x8413fd)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at BinaryData$/getMovieClipManager()
    at Game/onLoadComplete()
    at Game()
    at Main/createGame()
    at Main/onRootCreated()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1908()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 5500 (0x00001616) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (800, 600, 1)

# Page Info
Page URL: https://www.minijuegos.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=206531&mp_game_uid=tequila-zombies-3&mp_game_url=https%3A%2F%2Fwww.minijuegos.com%2Fembed%2Ftequila-zombies-3&mp_int=1&mp_locale=es_ES&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vdjMvZ2FtZXMvZ2FtZXMvcHJvZC8yMDY1MzEvdGVxdWlsYS0zLnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_site_name=minijuegos.com&mp_site_url=https%3A%2F%2Fwww.minijuegos.com%2F&mp_timezone=America%2FGuayaquil&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/v3/games/games/prod/206531/tequila-3.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-23
Channel: nightly
Built: 2024-03-23T00:05:24.393Z
Commit: d70560cb8250d4dd6c34c812b4fbec027907faea
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 21
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 38081696

**Comment by n0samu** [comment] 2024-07-27 07:02
Duplicate of #13748

**Closed by n0samu** 2024-07-27 07:02 UTC
Labels: duplicate, error-report
