### ISSUE TITLE
Error on https://www.spiele-umsonst.de/castaway-t1731.html

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#8198] opened 2022-10-04 21:56 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:1014:22
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:1014:22
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.spiele-umsonst.de/ruffle/core.ruffle.bca1371f982df7946ed0.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h73fc39b54ec29717 (wasm://wasm/017e8b06:wasm-function[1021]:0x2a382a)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017e8b06:wasm-function[1486]:0x3273a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d648d6ec080e3d2 (wasm://wasm/017e8b06:wasm-function[4920]:0x484684)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017e8b06:wasm-function[3620]:0x4413e8)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017e8b06:wasm-function[5073]:0x487acd)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/017e8b06:wasm-function[4217]:0x46b637)
    at ruffle_core::bitmap::bitmap_data::BitmapData::draw::h73fe75191fcb268e (wasm://wasm/017e8b06:wasm-function[743]:0x23bcdf)
    at ruffle_core::avm1::globals::bitmap_data::draw::h3741067adbf98faa (wasm://wasm/017e8b06:wasm-function[624]:0x1fe259)
    at ruffle_core::avm1::function::Executable::exec::ha1ebff59d66588d4 (wasm://wasm/017e8b06:wasm-function[364]:0xf1f99)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://www.spiele-umsonst.de/castaway-t1731.html
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/castaway.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-29
Channel: nightly
Built: 2022-09-29T00:19:25.847Z
Commit: 8f72842b2f186c4098ff277c510af41272d14377
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 5
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 7988051

**Comment by n0samu** [comment] 2022-10-04 22:04
Duplicate of #8016

**Closed by n0samu** 2022-10-04 22:04 UTC
Labels: duplicate, error-report
