### ISSUE TITLE
Error on http://www.bcae1.com/switchingpowersupplydesign/switchingpowersupplytut01.htm

### ISSUE THREAD

**Issue by dread40** [ruffle-rs/ruffle#3533] opened 2021-03-04 23:50 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6449)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (chrome-extension://boeioaidieaplcanmejfefpbacgjffdi/dist/847b95bd90f709290b04678d5ffd9fa9.wasm:wasm-function[1362]:0x27e9e5)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (chrome-extension://boeioaidieaplcanmejfefpbacgjffdi/dist/847b95bd90f709290b04678d5ffd9fa9.wasm:wasm-function[1632]:0x2b1404)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (chrome-extension://boeioaidieaplcanmejfefpbacgjffdi/dist/847b95bd90f709290b04678d5ffd9fa9.wasm:wasm-function[4833]:0x3a72d5)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (chrome-extension://boeioaidieaplcanmejfefpbacgjffdi/dist/847b95bd90f709290b04678d5ffd9fa9.wasm:wasm-function[3686]:0x37b7a9)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (chrome-extension://boeioaidieaplcanmejfefpbacgjffdi/dist/847b95bd90f709290b04678d5ffd9fa9.wasm:wasm-function[4348]:0x39a9fa)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (chrome-extension://boeioaidieaplcanmejfefpbacgjffdi/dist/847b95bd90f709290b04678d5ffd9fa9.wasm:wasm-function[5189]:0x3acc24)
    at rust_begin_unwind (chrome-extension://boeioaidieaplcanmejfefpbacgjffdi/dist/847b95bd90f709290b04678d5ffd9fa9.wasm:wasm-function[5068]:0x3ab3d7)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (chrome-extension://boeioaidieaplcanmejfefpbacgjffdi/dist/847b95bd90f709290b04678d5ffd9fa9.wasm:wasm-function[5190]:0x3acc5a)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (chrome-extension://boeioaidieaplcanmejfefpbacgjffdi/dist/847b95bd90f709290b04678d5ffd9fa9.wasm:wasm-function[4448]:0x39dc33)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.bcae1.com/switchingpowersupplydesign/switchingpowersupplytut01.htm
SWF URL: http://www.bcae1.com/switchingpowersupplydesign/6inchpowersupplyphoto02.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-02
Channel: nightly
Built: 2021-03-02T00:17:52.607Z
Commit: 697ab274146e96a762b49ae047a6f528337ceb20

**Comment by relrelb** [comment] 2021-03-26 13:40
Duplicate of #2598.

**Closed by relrelb** 2021-03-26 13:40 UTC
