### ISSUE TITLE
Error on https://theimpossiblequiz.net/impossiblequiz2.html

### ISSUE THREAD

**Issue by BautistaConTodo** [ruffle-rs/ruffle#4564] opened 2021-06-12 20:16 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://pembdfbhedanekkenpffhalchdkllhik/dist/ruffle.js?uniqueMessageSuffix=73258245365:1:7476)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (chrome-extension://pembdfbhedanekkenpffhalchdkllhik/dist/b475d98597d6727f5846.wasm:wasm-function[1091]:0x28d389)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (chrome-extension://pembdfbhedanekkenpffhalchdkllhik/dist/b475d98597d6727f5846.wasm:wasm-function[961]:0x262ff8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (chrome-extension://pembdfbhedanekkenpffhalchdkllhik/dist/b475d98597d6727f5846.wasm:wasm-function[3833]:0x41c70d)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (chrome-extension://pembdfbhedanekkenpffhalchdkllhik/dist/b475d98597d6727f5846.wasm:wasm-function[2989]:0x3b811c)
    at rust_begin_unwind (chrome-extension://pembdfbhedanekkenpffhalchdkllhik/dist/b475d98597d6727f5846.wasm:wasm-function[4040]:0x422015)
    at core::panicking::panic_fmt::hd44f353696296fec (chrome-extension://pembdfbhedanekkenpffhalchdkllhik/dist/b475d98597d6727f5846.wasm:wasm-function[4189]:0x428941)
    at core::option::expect_none_failed::hf7dab2706f1a5551 (chrome-extension://pembdfbhedanekkenpffhalchdkllhik/dist/b475d98597d6727f5846.wasm:wasm-function[3422]:0x40ab2a)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h17ee6b739e165840 (chrome-extension://pembdfbhedanekkenpffhalchdkllhik/dist/b475d98597d6727f5846.wasm:wasm-function[585]:0x19bf25)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h583e2d607789ab7a (chrome-extension://pembdfbhedanekkenpffhalchdkllhik/dist/b475d98597d6727f5846.wasm:wasm-function[545]:0x18428f)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://theimpossiblequiz.net/impossiblequiz2.html
SWF URL: https://theimpossiblequiz.net/impossiblequiz2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-09
Channel: nightly
Built: 2021-06-09T00:13:19.098Z
Commit: 5acc4767893bfcf9c97699b1f21a9c2eda3d56b9

**Comment by torokati44** [comment] 2021-06-15 15:40
Essentially a duplicate of #4524.

**Closed by torokati44** 2021-06-15 15:40 UTC
