### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by peepoostpin** [ruffle-rs/ruffle#7127] opened 2022-06-01 14:51 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/966.index.js:1:6395)
    at std::sync::once::Once::call_once::{{closure}}::h074a5b43a199c982 (https://ruffle.rs/demo/fd32871b7e173fc403ec.wasm:wasm-function[1233]:0x2b9b07)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://ruffle.rs/demo/fd32871b7e173fc403ec.wasm:wasm-function[1462]:0x2f7b5f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3cf43421fa49406f (https://ruffle.rs/demo/fd32871b7e173fc403ec.wasm:wasm-function[4912]:0x4513f4)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://ruffle.rs/demo/fd32871b7e173fc403ec.wasm:wasm-function[3241]:0x3f2995)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://ruffle.rs/demo/fd32871b7e173fc403ec.wasm:wasm-function[5105]:0x45b54e)
    at core::panicking::panic::hc28e7cc2aa792341 (https://ruffle.rs/demo/fd32871b7e173fc403ec.wasm:wasm-function[5006]:0x45348f)
    at core::ops::function::FnOnce::call_once::h1bafb086eef23c57 (https://ruffle.rs/demo/fd32871b7e173fc403ec.wasm:wasm-function[1100]:0x293017)
    at ruffle_core::avm1::function::Executable::exec::h215b1d2b2988d0a3 (https://ruffle.rs/demo/fd32871b7e173fc403ec.wasm:wasm-function[397]:0xcffb8)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7cce8a68da8fadfc (https://ruffle.rs/demo/fd32871b7e173fc403ec.wasm:wasm-function[580]:0x19cf9d)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.62 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-01
Channel: nightly
Built: 2022-06-01T00:17:34.589Z
Commit: 4fb77edfb1807bb523a391f929af73a66de223ab
Is extension: false

**Comment by n0samu** [comment] 2022-06-01 20:32
Duplicate of #4932. (This game doesn't work yet, sorry!)

**Closed by n0samu** 2022-06-01 20:32 UTC
Labels: error-report
