### ISSUE TITLE
Error on https://game179258.konggames.com/games/randomnine/cardinal-quest-2/frame/926c8571-d256-494f-b3ff-3b400861c739/

### ISSUE THREAD

**Issue by BenMeierRecurrency** [ruffle-rs/ruffle#18247] opened 2024-10-12 11:11 UTC
# Error Info
Error name: Error
Error message: panicked at render/naga-pixelbender/src/lib.rs:1223:29:
Unimplemented opcode Step
Error stack:
```
Error: panicked at render/naga-pixelbender/src/lib.rs:1223:29:
Unimplemented opcode Step
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ac4022413c9bc47922d2.js:1:84118)
    at ruffle_web.wasm.js_sys::Error::new::h707edc16dc8b9bc8 (wasm://wasm/ruffle_web.wasm-03227eb2:wasm-function[12778]:0x989304)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hdac645c719d844de (wasm://wasm/ruffle_web.wasm-03227eb2:wasm-function[9837]:0x919554)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-03227eb2:wasm-function[6399]:0x811825)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-03227eb2:wasm-function[9558]:0x909c55)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h5d705f763ace27e7 (wasm://wasm/ruffle_web.wasm-03227eb2:wasm-function[8421]:0x8b1b6e)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::display::shader_data::init::h9187bf7af49d2287 (wasm://wasm/ruffle_web.wasm-03227eb2:wasm-function[1384]:0x3cab7b)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::h56440b0d5908271a (wasm://wasm/ruffle_web.wasm-03227eb2:wasm-function[1351]:0x3b2f25)
    at ruffle_web.wasm.ruffle_core::avm2::object::TObject::call_method::h306a4ca5c3314582 (wasm://wasm/ruffle_web.wasm-03227eb2:wasm-function[2451]:0x59ddac)
    at ruffle_web.wasm.ruffle_core::avm2::activation::Activation::run_actions::h995717eae69a8179 (wasm://wasm/ruffle_web.wasm-03227eb2:wasm-function[758]:0x11d9e)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at flixelcq.tile::FlxCqTilemap()
    at cq::CqLevel()
    at cq::CqWorld/executeGoToLevel()
    at cq.states::GameState/continueInitialisation()
    at cq.states::GameState/update()
    at flixel::FlxState/tryUpdate()
    at flixel::FlxGame/update()
    at cq::Main/update()
    at flixel::FlxGame/step()
    at flixel::FlxGame/onEnterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mali-G715"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 65536, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 134217728, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game179258.konggames.com/games/randomnine/cardinal-quest-2/frame/926c8571-d256-494f-b3ff-3b400861c739/?kongregate_host=www.kongregate.com
SWF URL: https://game179258.konggames.com/gamez/0017/9258/live/cq2.swf?kongregate_game_version=1465851167

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-10-12
Channel: nightly
Built: 2024-10-12T00:05:59.291Z
Commit: 95177748ce9f6dafb880aea912842a4ff633eaac
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 15
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 20519535

**Comment by evilpie** [comment] 2024-10-12 16:11
Duplicate of #14068

**Closed by evilpie** 2024-10-12 16:11 UTC
