### ISSUE TITLE
Tab key does not work

### ISSUE THREAD

**Issue by rikkoooo** [ruffle-rs/ruffle#14554] opened 2023-12-29 21:42 UTC
### Describe the bug

Tab key does not selects buttons in order, and this is very bad for most movies. Tab key must select buttons in order and mark they with yellow borders likely in original Flash Player, and arrow keys must also switch between highlighted buttons. This happens in all movies in all platforms.

### Expected behavior

Happens in all behaviors.

### Content Location

This happens in all movies, not only one movie.

### Affected platform

Desktop app

### Operating system

WIN10

**Comment by n0samu** [comment] 2023-12-29 22:04
Duplicate of #5443

**Closed by n0samu** 2023-12-29 22:04 UTC
Labels: bug, duplicate
