### ISSUE TITLE
Passing variables to PHP mailer

### ISSUE THREAD

**Issue by charco57** [ruffle-rs/ruffle#13019] opened 2023-08-30 21:24 UTC
### Describe the bug

I have several test programs that used to send the results to a php mailer program:

function endGame() {
	fillForm();
	summary.sendit.onRelease = function() {
		// send variables in form movieclip (the textfields)
		// to email PHP page which will send the mail
		summary.loadVariables("../mail/mc_test.php","POST");
		summary.onEnterFrame = function() {// do or show whatever you want after the form is sent, splash screen?
			//_root.attachMovie("thanks","thanks",_root.getNextHighestDepth(),{_x:0, _y:0});
			removeMovieClip(summary);
		};
		removeMovieClip("formula");
		quickReset();
		my_txt.removeTextField();
	};
}

// declare variables to be passed
var testName:String;
var me:String;
var email:String;
var marks:Number;
var asked:Number;
var realname:String;
var destination:String;
var wrong:String;
var minsUsed:Number;
var andSeconds:Number;
var initial_time:Number;
var minutes_elapsed:Number;
var seconds_elapsed:Number;
var showWrongOnes:String="";
var txtFile:String;

/*
The following function has a dual purpose. 
1. It displays all of the test information to the testee.
2. On closing it sends the required information to the .php program for processing and sending an email.
*/

function fillForm() {
	// displays the summary results
	summary.myName.text = me;
	summary.myMail.text = email;
	summary.score.text = correct;
	summary.questions_asked.text = numQ;
	var percentage = Math.round(100*correct/numQ);
	summary.perc.text = percentage;
	for(var w=0; w<wrongUns.length; w++){
		showWrongOnes += wrongUns[w]+"<br>";  // this is fine for summary screen, but not for emailed results.
	}
	summary.further_study.htmlText = showWrongOnes;  // display errors on summary screen
	elapsed();
	summary.m.text = minutes_elapsed;
	summary.s.text = seconds_elapsed;

	// now the variables to be sent by mail
	summary.testName=testName;
	summary.realname = me;
	summary.marks = correct;
	summary.asked = numQ;
	summary.percentage = percentage;
	summary.timeTakenMin = minutes_elapsed;
	summary.timeTakenSec = seconds_elapsed;
	summary.destination = email;// the email address input by the person doing the test
	summary.wrongOnes = wrongUnsPhp; // this emails the whole array string separated by <br> tags for processing by php
	summary.txtFile = txtFile;
}

/* ---------------- end submit results   -------------------- */

### Expected behavior

The variables were received by a php script: 
summary.loadVariables("../mail/mc_test.php","POST");

as POST variables

$subject=$_POST["testName"];
$data1=$_POST["realname"];
$data2=$_POST["marks"];
$data3=$_POST["asked"];
$data5=$_POST["txtFile"];
$incomingArray = $_POST["wrongOnes"];
$sendTo=$_POST["destination"];
$data7=$_POST["percentage"];

for further processing and mailing.

But, although the email is sent by the php mailer to a default mailbox, there are no variables received by the php.

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

All platforms, eg FF116.03 64 bit

**Comment by n0samu** [comment] 2023-08-30 21:31
This seems to be a duplicate of #4338. And I thought we already solved your issue in #10571. Please check again, and if something is still not working, please add a comment to #4338 letting us know.

**Closed by n0samu** 2023-08-30 21:31 UTC
Labels: bug
