### ISSUE TITLE
Error on https://rerise.4mir.net/game/

### ISSUE THREAD

**Issue by govras** [ruffle-rs/ruffle#2798] opened 2021-01-23 14:43 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3110:14
Error stack:
```
e/a.wbg.__wbg_new_df6e6ab7a65c4c4d@https://rerise.4mir.net/ruffle/ruffle.js:1:6518
std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1272]:0x257d2b
std::sync::once::Once::call_inner::h02eac160d339afc2@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1537]:0x288710
core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4316]:0x35e2ca
std::panicking::rust_panic_with_hook::h123718ba3bf480af@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[3311]:0x33733d
std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[3923]:0x35414d
std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4662]:0x363a0c
rust_begin_unwind@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4534]:0x362022
core::panicking::panic_fmt::h285dc015a87be5a4@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4664]:0x363a70
core::panicking::panic::h0abe4e7a620ae568@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4468]:0x360ee7
ruffle_core::display_object::movie_clip::ClipAction::from_action_and_movie::h5947c408104e25ed@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[2285]:0x2e8cab
<core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next::hd27aefc78ac0e0f5@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1214]:0x24b9c5
<alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter::h3951c062be645d8f@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1165]:0x2405d9
ruffle_core::display_object::TDisplayObject::apply_place_object::hd6345e81ebcf0d57@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[827]:0x1e099f
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::apply_place_object::h59028f5e03c925c8@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[3991]:0x35638d
ruffle_core::display_object::movie_clip::MovieClip::run_goto::{{closure}}::h94289c4103630058@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[2458]:0x2f9a52
ruffle_core::display_object::movie_clip::MovieClip::run_goto::h258cdecbe3dc0f58@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[450]:0x128966
ruffle_core::display_object::movie_clip::MovieClip::goto_frame::h52665f30c69ebde6@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[2747]:0x312981
ruffle_core::avm1::globals::movie_clip::goto_frame::hc6e17867c0bcdd39@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1217]:0x24c5d7
core::ops::function::FnOnce::call_once::h1eb18f40d34cab23@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[3820]:0x35047e
ruffle_core::avm1::function::Executable::exec::h730c08f0eeeaf423@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[354]:0xcde99
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::hd9c62149769d407b@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[808]:0x1da1ea
ruffle_core::avm1::object::TObject::call_method::hbfb35770c5808609@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1555]:0x28b577
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h4bb72bef8c160084@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[954]:0x209a99
ruffle_core::avm1::activation::Activation::do_action::hd598f2a9929e1825@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[286]:0x1c0f5
ruffle_core::avm1::activation::Activation::run_actions::h937245a24cf3d918@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[2784]:0x3154c0
ruffle_core::avm1::Avm1::run_stack_frame_for_action::h07d1a3879bea63ef@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[1017]:0x21b711
ruffle_core::player::Player::run_actions::hbcdf7db7936243f9@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[417]:0x10d034
ruffle_core::player::Player::run_frame::h20f759f5a4862255@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[874]:0x1f07ba
ruffle_core::player::Player::tick::hc63353bedee00885@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[3330]:0x3383eb
std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[760]:0x1c8d87
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hc9990c794ee9c7af@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4566]:0x36271c
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hbc76ba63e1f5e772@https://rerise.4mir.net/ruffle/8d62e449f4e6f83e50950ed46a920f36.wasm:wasm-function[4845]:0x3658f6
O@https://rerise.4mir.net/ruffle/ruffle.js:1:4040
a@https://rerise.4mir.net/ruffle/ruffle.js:1:2840

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://rerise.4mir.net/game/
SWF URL: https://rerise.4mir.net/game/swf/game.swf?userlogin=

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-22
Channel: nightly
Built: 2021-01-22T01:05:46.108Z
Commit: b05c6540e18bcca93dce9ed6f65fe1f38d65a979

**Comment by Herschel** [comment] 2021-01-25 04:04
Duplicate of #2797.

**Closed by Herschel** 2021-01-25 04:04 UTC
Labels: duplicate
