### ISSUE TITLE
Passing variables to php using AS2 (FF in W10, but other browsers fail also)

### ISSUE THREAD

**Issue by charco66** [ruffle-rs/ruffle#4338] opened 2021-05-15 17:14 UTC
Hi Ruffle developers,

I have many educational flash quiz programs that pass the quiz results as variables to a php mailer that sends them to the teacher (me). However, this does not work in Ruffle. The php script does not receive/recognise the information. Is there a work around I can use?

Actionscript 2
The variables are loaded into a moviclip called "summary".
```

function fillForm() {
// displays the summary results
summary.myName.text = me;
summary.score.text = correct;
summary.questions_asked.text = numQ;
var percentage = Math.round(100*correct/numQ);
summary.perc.text = percentage;
displayArray="";
for(i=0;i<wrongUns.length;i++){
displayArray+=wrongUns[i]+"
";
}
summary.further_study.htmlText = displayArray;
elapsed();
summary.m.text = minutes_elapsed;
summary.s.text = seconds_elapsed;

// now the variables to be sent by mail
summary.realname = me;
summary.marks = correct;
summary.asked = numQ;
summary.timeTakenMin = minutes_elapsed;
summary.timeTakenSec = seconds_elapsed;
summary.destination = myMail;// the email address of the person doing the test
summary.wrongOnes = wrongUnsPhp+"\n";

}
```

Here is the bare bones of the actionscript 2 'end' function:

```
function end() {
fillForm();
summary.sendit.onRelease = function() {
// send variables in form movieclip (the textfields)
// to email PHP page which will send the mail
summary.loadVariables("../mail/shapes_sl.php","POST");
summary.onEnterFrame = function() {
_root.attachMovie("thanks","thanks",_root.getNextHighestDepth(),{_x:0, _y:0});
removeMovieClip(summary);
};
removeMovieClip("formula");
};
}
```

The php mailer simply receives the variables and processes them. For example:

```
$data1=$_POST["realname"];
$data2=$_POST["marks"];
$data3=$_POST["asked"];

```
All of this worked a dream in Flash, but not using Ruffle. I would love to contribute to the development, but I fear that the programming required is waaay beyond my level. The job you're all doing is fantastic.

If anyone could help with Flash >>> php I would really appreciate it.

Cheers,

Charco

**Comment by n0samu** [comment] 2023-08-30 21:33
@charco66 Please check whether this is working, and if it is not, please zip and upload your PHP script, SWF files, and anything else required to reproduce the bug. Thanks!

**Comment by charco57** [comment] 2023-08-30 21:44
I am just testing and some of the programs now work, but crash from time to time. 
This may be due to my poor programming, so I'm going to check them out.
The variables are indeed now being POSTed correctly.
Sorry if I have wasted your time.
Thanks again.

**Comment by n0samu** [comment] 2023-08-30 23:05
Glad to hear it's working! I'll close the issue for now, but please leave a comment if you find any more problems.

**Closed by n0samu** 2023-08-30 23:05 UTC
Labels: bug
