### ISSUE TITLE
Papa's Donuteria never finishes loading

### ISSUE THREAD

**Issue by Lord-McSweeney** [ruffle-rs/ruffle#9015] opened 2023-01-04 02:30 UTC
### Describe the bug

On Papa's Donuteria (SWF https://i.flipline.com/gamefiles/papasdonuteria/papasdonuteria_102.swf), the game will never finish loading, even though the loading bar will fill the box. The error `Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x485de0 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x1ad3ac4 }))) : RustError("Cannot coerce String(\"<response><pre_image>http://www.fliplineads.com/serve/images/v15_donuteriaTG.swf</pre_image><pre_link></pre_link><pre_uselink>false</pre_uselink><pre_dim>640x480</pre_dim><pre_delay>5</pre_delay><int_image>http://www.fliplineads.com/serve/images/v12_scooperiaTG.swf</int_image><int_link></int_link><int_uselink>false</int_uselink><int_dim>640x480</int_dim><int_delay>5</int_delay><alt_image>http://www.fliplineads.com/serve/images/v15_donuteriaTG.swf</alt_image><alt_link></alt_link><alt_uselink>false</alt_uselink><alt_dim>640x480</alt_dim><alt_delay>5</alt_delay><new_image>http://www.fliplineads.com/serve/images/scooperiaTG_badge.png</new_image><new_link>https://itunes.apple.com/app/id1392608717?ls=1&mt=8</new_link><new_uselink>true</new_uselink><new_usecont>true</new_usecont><promo1_image>http://www.fliplineads.com/serve/images/donuteriaTG_badge.png</promo1_image><promo1_link>https://itunes.apple.com/app/id1462324486?ls=1&mt=8</promo1_link><promo1_uselink>true</promo1_uselink><promo1_usecont>true</promo1_usecont><promo2_image>http://www.fliplineads.com/serve/images/donuteriaTG_badge.png</promo2_image><promo2_link>https://itunes.apple.com/app/id1462324486?ls=1&mt=8</promo2_link><promo2_uselink>true</promo2_uselink><promo2_usecont>true</promo2_usecont><version>1.0</version><ato>10</ato><bto>5</bto><success>true</success></response>\") to an XML")` is logged in the console due to missing XML functionality in AVM2.

### Expected behavior

The game can finish loading.

### Affected platform

Browser's extension

### Operating system

Linux

### Browser

Chrome 108

### Additional information

The XML is loaded over the network.

**Comment by n0samu** [comment] 2023-01-04 05:07
Duplicate of #8808

**Closed by n0samu** 2023-01-04 05:07 UTC
Labels: bug, duplicate
