### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by Ky-Fi** [ruffle-rs/ruffle#12385] opened 2023-07-28 22:18 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
339/__wbg_get_imports/imports.wbg.__wbg_new_d258248ed531ff54@moz-extension://61eeff85-00ed-4ca9-889f-784f7479d8af/dist/339.js:2403:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::hb515a2c9ffd29eb6@:wasm-function[9095]:0x8d153a
std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d@:wasm-function[5945]:0x7d3756
core::panicking::panic_fmt::h8a19fa1eb63fbb67@:wasm-function[8939]:0x8cca1b
core::panicking::panic::h42080e1e32ba4b73@:wasm-function[8578]:0x8bd813
ruffle_core::display_object::movie_clip::MovieClip::preload::hb5b85f61fb48e0e1@:wasm-function[657]:0x1e0b06
ruffle_core::loader::Loader::preload_tick::h7b094ab8a5707123@:wasm-function[1635]:0x46e68c
ruffle_web::Ruffle::tick::he69ac8c81235f518@:wasm-function[751]:0x256823
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hf7a7d99b76257725@:wasm-function[10883]:0x910c9a
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h09228ee8fa7220ea@:wasm-function[9739]:0x8ee4d5
__wbg_adapter_55@moz-extension://61eeff85-00ed-4ca9-889f-784f7479d8af/dist/339.js:290:10
real@moz-extension://61eeff85-00ed-4ca9-889f-784f7479d8af/dist/339.js:271:20

```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "GeForce GTX 980/PCIe/SSE2"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 32768, max_texture_dimension_2d: 32768, max_texture_dimension_3d: 16384, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1031&nc_referer=&age=1&hiscore=&sp=0&questionSet=&r=7027218&&width=600&height=600&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_24.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-22
Channel: nightly
Built: 2023-07-22T00:19:38.712Z
Commit: 77c0dac64be338500e8dbba1d8ad37d13a10cb5b
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 24
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by n0samu** [comment] 2023-07-29 03:40
Duplicate of #10614

**Closed by n0samu** 2023-07-29 03:40 UTC
Labels: duplicate, error-report
