### ISSUE TITLE
Ruffle Error on https://hentaijoy.com/meet-and-fuck-hentai-games/xxx-teen-action/

### ISSUE THREAD

**Issue by 1285576** [ruffle-rs/ruffle#10969] opened 2023-05-07 18:41 UTC
#错误信息n错误名称:类型错误n错误消息:无法下载wasm模块n错误堆栈:n``` nTypeError:无法下载wasm模块n``` n n #玩家信息n允许脚本访问:false n n#页面信息n页面URL:https://hentai joy . com/meet-and-fuck-hentai-games/XXX-teen-action/n n #浏览器信息nuser agent:Mozilla/5.0(Linux；u；安卓12；zh-cn；NTH-AN00 Build/HONORNTH-AN00)AppleWebKit/537.36(KHTML，像壁虎一样)版本/4.0 Chrome/98 . 0 . 4758 . 102 MQQBrowser/13.8 Mobile Safari/537.36 COVC/046415 nOS:Linux aarch 64n n # Ruffle Info n Version:0 . 1 . 0 nName:nightly 21-01-01n channel:nightly nbuilded:200

**Comment by Lord-McSweeney** [comment] 2023-05-07 18:45
Duplicate of https://github.com/ruffle-rs/ruffle/issues/10967.

**Closed by Lord-McSweeney** 2023-05-07 18:45 UTC
