### ISSUE TITLE
Error on https://www.gameflare.com/embed/jacksmith/

### ISSUE THREAD

**Issue by Juan2241** [ruffle-rs/ruffle#13285] opened 2023-09-23 18:26 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://www.gameflare.com/emulators/ruffle/core.ruffle.94ad4a844ac59e0f95cb.js:1:51844)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h57def9a78408b97f (wasm://wasm/030ad9d6:wasm-function[9339]:0x920b83)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/030ad9d6:wasm-function[6103]:0x822330)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/030ad9d6:wasm-function[9175]:0x91c19a)
    at core::ops::function::Fn::call::h9c7f5d1e973a4a59 (wasm://wasm/030ad9d6:wasm-function[6305]:0x82e3cc)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h09222b538ec8307d (wasm://wasm/030ad9d6:wasm-function[4938]:0x78ce73)
    at wgpu::backend::direct::Context::handle_error::hf547d7fa4fc41168 (wasm://wasm/030ad9d6:wasm-function[2533]:0x5dc439)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h8036b8dcb3f54166 (wasm://wasm/030ad9d6:wasm-function[6684]:0x859922)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h52173ae4f44f48b2 (wasm://wasm/030ad9d6:wasm-function[5724]:0x8034a4)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h644e2d11edbcc2b0 (wasm://wasm/030ad9d6:wasm-function[1570]:0x4835bf)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Qualcomm, Adreno (TM) 630, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-23
Channel: nightly
Built: 2023-09-23T00:20:20.140Z
Commit: dc537584880b733b65765088d71ed88e443be7b6
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by TheHunter1231** [comment] 2023-09-29 16:39
I had a similar issue where after i unlocked the spear the game had the something went wrong screen apeared and its now where if you try to launch the game you get the spear unlock screen to then open shop and then when the cow who wants the spear appears and a few seconds later the game crashes

**Comment by evilpie** [comment] 2024-04-09 15:11
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:11 UTC
Labels: error-report
