### ISSUE TITLE
Error on https://simple-education.xyz/swf.html

### ISSUE THREAD

**Issue by Elpupuxd** [ruffle-rs/ruffle#8106] opened 2022-09-27 03:35 UTC
# Error Info
Error name: age of war not working bug 
![F9C4ED74-AE91-4EDC-877B-BF65DF9B3BC4](https://user-images.githubusercontent.com/114459283/192425838-688d967d-2153-4da3-b086-522f9188ed42.png)
Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-1.0.1/src/fill.rs:1990:74
Error stack:
```
@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.9.27/core.ruffle.73cd4b2216766003e577.js:1:7398
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h73fc39b54ec29717]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hb30cfbde5209eed0]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d648d6ec080e3d2]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::hb09154fa23e06c37]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h9e229748e3ae9f9d]@[wasm code]
<?>.wasm-function[core::panicking::panic::h6f5024a57ca8da86]@[wasm code]
<?>.wasm-function[core::slice::sort::shift_tail::h69d58cf439ff2ae1]@[wasm code]
<?>.wasm-function[core::slice::sort::recurse::h573467996f10820f]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::process_events::hbfde468c8c6a8ae7]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_impl::h593e347f70351e0c]@[wasm code]
<?>.wasm-function[ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hffe9537af5eeb8f3]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_render::backend::RenderBackend>::register_shape::hc463b3066c1f18d1]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::hf272c26606a41f61]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h8b6e3bd874b89bcc]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h6af632469979f791]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h60d726a424d28b1d]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h970c39b503fdbae6]@[wasm code]
wasm-stub@[native code]
T@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.9.27/core.ruffle.73cd4b2216766003e577.js:1:3033
c@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.9.27/core.ruffle.73cd4b2216766003e577.js:1:2485
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://simple-education.xyz/swf.html?notebook=ageofwar
SWF URL: https://simple-education.xyz/swffiles/ageofwar.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Platform: MacIntel
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-27
Channel: nightly
Built: 2022-09-27T00
![0CCE1DC3-3520-47CF-B1E5-775ACEA04013](https://user-images.githubusercontent.com/114459283/192425890-2e83a35b-2dd2-4c48-98df-08f7f5a5c15e.png)
:19:30.237Z
Commit: 66fa67cdcc6d802664e63cf2a5f8c6264d54fa31
Is extension: false

# Metadata
width: 650
height: 450
frameRate: 40
numFrames: 15
swfVersion: 9
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 4098898

**Comment by n0samu** [comment] 2022-09-27 03:40
Duplicate of #6608. You need to update your iPadOS version to get Ruffle to work properly.

**Closed by n0samu** 2022-09-27 03:40 UTC
Labels: duplicate, error-report
