### ISSUE TITLE
Error on https://unblockedgames.blogbucket.org/electric-man-2-hacked/

### ISSUE THREAD

**Issue by kitty927** [ruffle-rs/ruffle#5665] opened 2021-11-15 07:29 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unblockedgames.blogbucket.org/ruffleupdate/ruffle.js:1:6803)
    at std::sync::once::Once::call_once::{{closure}}::h647d1f7832046459 (https://unblockedgames.blogbucket.org/ruffleupdate/d767eb345dcb54775753.wasm:wasm-function[993]:0x28c34d)
    at std::sync::once::Once::call_inner::hc44ad7f626385660 (https://unblockedgames.blogbucket.org/ruffleupdate/d767eb345dcb54775753.wasm:wasm-function[1257]:0x2e65d6)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hec2c3e1e216f4525 (https://unblockedgames.blogbucket.org/ruffleupdate/d767eb345dcb54775753.wasm:wasm-function[4306]:0x480b92)
    at std::panicking::rust_panic_with_hook::he9bfe03219d715ba (https://unblockedgames.blogbucket.org/ruffleupdate/d767eb345dcb54775753.wasm:wasm-function[3134]:0x411f07)
    at rust_begin_unwind (https://unblockedgames.blogbucket.org/ruffleupdate/d767eb345dcb54775753.wasm:wasm-function[4529]:0x4867fc)
    at core::panicking::panic_fmt::hbf21a3d4bbb82bf8 (https://unblockedgames.blogbucket.org/ruffleupdate/d767eb345dcb54775753.wasm:wasm-function[4714]:0x48ddb4)
    at core::panicking::panic::h2fd385a887c8bf13 (https://unblockedgames.blogbucket.org/ruffleupdate/d767eb345dcb54775753.wasm:wasm-function[4466]:0x483de1)
    at core::ops::function::FnOnce::call_once::h2af075b8415a08a5 (https://unblockedgames.blogbucket.org/ruffleupdate/d767eb345dcb54775753.wasm:wasm-function[972]:0x282e8d)
    at ruffle_core::avm1::function::Executable::exec::h9282a304943b15d7 (https://unblockedgames.blogbucket.org/ruffleupdate/d767eb345dcb54775753.wasm:wasm-function[404]:0x112a3e)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://files.blogbucket.org/2017/electricman2_hack.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://unblockedgames.blogbucket.org/electric-man-2-hacked/
SWF URL: https://files.blogbucket.org/2017/electricman2_hack.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14150.87.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.124 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-01
Channel: nightly
Built: 2021-10-01T00:11:02.353Z
Commit: 2d306865d673a949b86262311bace568fecea205
Is extension: false

**Comment by relrelb** [comment] 2021-11-15 12:15
Duplicate of #4932.

**Closed by relrelb** 2021-11-15 12:15 UTC
