### ISSUE TITLE
Error on https://images-opensocial.googleusercontent.com/gadgets/ifr

### ISSUE THREAD

**Issue by CraigtheSnake14323** [ruffle-rs/ruffle#13349] opened 2023-09-28 16:54 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
    at O.n.wbg.__wbg_new_d258248ed531ff54 (https://cdn.jsdelivr.net/gh/ruffle-rs/demo@master/339.index.js:1:51811)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h970f11018b2be85d (wasm://wasm/030be266:wasm-function[9338]:0x925405)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/030be266:wasm-function[6110]:0x8271ac)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/030be266:wasm-function[9174]:0x920a1c)
    at core::ops::function::Fn::call::hb22928db381f2032 (wasm://wasm/030be266:wasm-function[6304]:0x832804)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h2e9011c163e8e180 (wasm://wasm/030be266:wasm-function[4952]:0x78e4b5)
    at wgpu::backend::direct::Context::handle_error::hef02f17debce92eb (wasm://wasm/030be266:wasm-function[2545]:0x5dee54)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h79c33bd606b17a79 (wasm://wasm/030be266:wasm-function[6684]:0x85ea21)
    at wgpu::CommandEncoder::copy_texture_to_buffer::hef05d2fd822d2f6b (wasm://wasm/030be266:wasm-function[5736]:0x808552)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h3b415ae63c546b24 (wasm://wasm/030be266:wasm-function[1573]:0x47ee1e)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/dadsstash/swf-files@93b7a945ccbd0b0dd9ae1028df26f13928020dfa/jacksmith.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://s3.amazonaws.com/production-assetsbucket-8ljvyr1xczmb/1ee20621-61bc-4ec8-a8ec-5e839c2e6edc%2Fjacksmith.xml
SWF URL: https://cdn.jsdelivr.net/gh/dadsstash/swf-files@93b7a945ccbd0b0dd9ae1028df26f13928020dfa/jacksmith.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-26
Channel: nightly
Built: 2023-09-26T00:25:18.615Z
Commit: 7e4e4d4c5b1f55614b98b33b7cc6f70567c52bab
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9363111

**Comment by evilpie** [comment] 2024-04-09 15:22
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:22 UTC
Labels: render-wgpu, error-report
