### ISSUE TITLE
Error on https://gaymes.net/locus/

### ISSUE THREAD

**Issue by Leoncantonio** [ruffle-rs/ruffle#6190] opened 2022-02-01 17:49 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/display_object/graphic.rs:105:28
Error stack:
```
@https://gaymes.net/wp-content/themes/gameking/ruffle/ruffle.js:1:6712
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hdee01963557c8b87]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hf9144d66ddc67dec]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e75ef83c7eceddf]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h606d7c7f7a423b98]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h6314b5c91abe7349]@[wasm code]
<?>.wasm-function[core::result::unwrap_failed::hd584efb7b84bf326]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::apply_place_object::h2b96db7f562c2d57]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::place_object::hf25d83bf39efd28e]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::run_frame_internal::h379497c7b76fb30a]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::run_frame::h16bda9ef998a6f08]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::hb9d842e238c03a03]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hf1137b90d4f64c37]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hf7532dd40cfdddb1]@[wasm code]
wasm-stub@[native code]
C@https://gaymes.net/wp-content/themes/gameking/ruffle/ruffle.js:1:3549
a@https://gaymes.net/wp-content/themes/gameking/ruffle/ruffle.js:1:2536
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://gaymes.net/locus/
SWF URL: https://gaymes.net/wp-content/uploads/games/custom/E/e0d9f42a89e707820f8b62c51852824f-1.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-16
Channel: nightly
Built: 2021-12-16T00:12:02.888Z
Commit: 07c533045604f42610bb3ca5480d9443b78f7fb7
Is extension: false

**Comment by n0samu** [comment] 2024-06-23 23:39
Likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:39 UTC
Labels: nsfw, error-report
