### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by DA-TENSHI** [ruffle-rs/ruffle#9515] opened 2023-02-11 12:56 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    not enough memory left

', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu/src/backend/direct.rs:2973:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    not enough memory left

', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu/src/backend/direct.rs:2973:5
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://ruffle.rs/demo/966.index.js:1:5400)
    at std::sync::once::Once::call_once::{{closure}}::h3a9cf7405ac8602d (wasm://wasm/027e4382:wasm-function[1904]:0x487c5a)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/027e4382:wasm-function[1842]:0x477a40)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1b5f0905e39c576d (wasm://wasm/027e4382:wasm-function[7167]:0x76d87e)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/027e4382:wasm-function[5085]:0x6c99ed)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/027e4382:wasm-function[7483]:0x77c7aa)
    at core::ops::function::Fn::call::h0c6867852f20e27c (wasm://wasm/027e4382:wasm-function[5328]:0x6dafab)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::hc02868615e05272b (wasm://wasm/027e4382:wasm-function[3963]:0x665575)
    at <T as wgpu::context::DynContext>::device_create_buffer::ha3a8da1137c16e46 (wasm://wasm/027e4382:wasm-function[5755]:0x6ff9a7)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::ha9b22f61f5dda997 (wasm://wasm/027e4382:wasm-function[1245]:0x36fd9c)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-11
Channel: nightly
Built: 2023-02-11T00:19:06.082Z
Commit: a2cd3ee06edcb889e8adc70a221eabb80ad342e5
Is extension: false

# Metadata
width: 1000
height: 800
frameRate: 30
numFrames: 13
swfVersion: 8
backgroundColor: #666666
isActionScript3: false
uncompressedLength: 12571635

**Comment by Dinnerbone** [comment] 2024-07-12 22:00
Duplicate of #9293

**Closed by Dinnerbone** 2024-07-12 22:00 UTC
Labels: duplicate, render-wgpu, error-report
