### ISSUE TITLE
Error on https://shsgames.github.io/g/6f2e0289/electric-man-2

### ISSUE THREAD

**Issue by ChenBeixuan2** [ruffle-rs/ruffle#5881] opened 2021-12-17 15:12 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at https://shsgames.github.io/ruffle/ruffle.js:1:7628
    at std::sync::once::Once::call_once::{{closure}}::h8b88e6aa08fbb40d (https://shsgames.github.io/ruffle/731179ae1716fbb60e1c.wasm?__uncache=12%2F15%2F2021%2C%207%3A32%3A34%20PM:wasm-function[986]:0x309429)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://shsgames.github.io/ruffle/731179ae1716fbb60e1c.wasm?__uncache=12%2F15%2F2021%2C%207%3A32%3A34%20PM:wasm-function[1175]:0x34d23f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3ab0488d22755852 (https://shsgames.github.io/ruffle/731179ae1716fbb60e1c.wasm?__uncache=12%2F15%2F2021%2C%207%3A32%3A34%20PM:wasm-function[4623]:0x4f98ff)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://shsgames.github.io/ruffle/731179ae1716fbb60e1c.wasm?__uncache=12%2F15%2F2021%2C%207%3A32%3A34%20PM:wasm-function[3217]:0x4b37c5)
    at rust_begin_unwind (https://shsgames.github.io/ruffle/731179ae1716fbb60e1c.wasm?__uncache=12%2F15%2F2021%2C%207%3A32%3A34%20PM:wasm-function[4686]:0x4fb01d)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://shsgames.github.io/ruffle/731179ae1716fbb60e1c.wasm?__uncache=12%2F15%2F2021%2C%207%3A32%3A34%20PM:wasm-function[4896]:0x505b86)
    at core::panicking::panic::hec1fc057bd0baf0b (https://shsgames.github.io/ruffle/731179ae1716fbb60e1c.wasm?__uncache=12%2F15%2F2021%2C%207%3A32%3A34%20PM:wasm-function[4620]:0x4f9165)
    at core::ops::function::FnOnce::call_once::hf2847eaac0d0b0dc (https://shsgames.github.io/ruffle/731179ae1716fbb60e1c.wasm?__uncache=12%2F15%2F2021%2C%207%3A32%3A34%20PM:wasm-function[1033]:0x325754)
    at ruffle_core::avm1::function::Executable::exec::hd3e79afc52b5b7a9 (https://shsgames.github.io/ruffle/731179ae1716fbb60e1c.wasm?__uncache=12%2F15%2F2021%2C%207%3A32%3A34%20PM:wasm-function[437]:0x194baa)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://shsgames.github.io/g/6f2e0289/electric-man-2
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14150.87.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.124 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-12
Channel: nightly
Built: 2021-12-12T00:14:30.969Z
Commit: 1f5979f1681cd886e0e2b8245ec43190175b58ba
Is extension: false

**Comment by relrelb** [comment] 2021-12-17 19:05
Duplicate of #4932.

**Closed by relrelb** 2021-12-17 19:05 UTC
