### ISSUE TITLE
Ruffle Error on https://freeasteroids.org/

### ISSUE THREAD

**Issue by fzlink** [ruffle-rs/ruffle#9368] opened 2023-01-31 17:57 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch
    at Object.<anonymous> (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/core.ruffle.5e850f90e6e2fab0bb54.js:1:26394)
    at Object.<anonymous> (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/core.ruffle.5e850f90e6e2fab0bb54.js:1:19567)
    at __wbg_arrayBuffer_0ba17dfaad804b6f (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:49169)
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4190]:0x33a6f1
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[688]:0x1a64a7
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[596]:0x17ecf2
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[1682]:0x28fa47
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[2963]:0x30a2c9
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[2694]:0x2f7a5b
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4580]:0x33f5ec)', web/src/navigator.rs:157:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch
    at Object.<anonymous> (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/core.ruffle.5e850f90e6e2fab0bb54.js:1:26394)
    at Object.<anonymous> (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/core.ruffle.5e850f90e6e2fab0bb54.js:1:19567)
    at __wbg_arrayBuffer_0ba17dfaad804b6f (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:49169)
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4190]:0x33a6f1
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[688]:0x1a64a7
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[596]:0x17ecf2
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[1682]:0x28fa47
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[2963]:0x30a2c9
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[2694]:0x2f7a5b
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4580]:0x33f5ec)', web/src/navigator.rs:157:18
    at Object.Q (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/core.ruffle.5e850f90e6e2fab0bb54.js:1:20877)
    at __wbg_new_df6e6ab7a65c4c4d (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:38192)
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[1324]:0x254c8e
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[1491]:0x272a47
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4066]:0x338300
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[3161]:0x315621
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4375]:0x33d2f1
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4405]:0x33d854
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4277]:0x33be08
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/cbe7657b7dc9d70da5a6.module.wasm:wasm-function[4406]:0x33d88a
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freeasteroids.org/
SWF URL: https://freeasteroids.org/asteroids.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by Lord-McSweeney** [comment] 2023-01-31 22:12
Duplicate of #9163.

**Closed by Lord-McSweeney** 2023-01-31 22:12 UTC
Labels: error-report
