### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by sebbiestar** [ruffle-rs/ruffle#3781] opened 2021-03-24 18:41 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
e/a.wbg.__wbg_new_df6e6ab7a65c4c4d@https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1616425469:1:6553
std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4@https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[1470]:0x2c47ba
std::sync::once::Once::call_inner::hd3d269a4946f2df2@https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[1760]:0x2fa94f
core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258@https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[5222]:0x404b8b
std::panicking::rust_panic_with_hook::h4f753dc70b771d8e@https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[4007]:0x3d664d
std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8@https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[4717]:0x3f7a92
std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21@https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[5590]:0x40a7e9
rust_begin_unwind@https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[5465]:0x408ec7
core::panicking::panic_fmt::hbd8a975261a5f466@https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[5591]:0x40a81f
std::thread::local::LocalKey<T>::with::hd56bd27bc5f64716@https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[854]:0x21b647
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h9877cf7ae83a558a@https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[5499]:0x409648
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hd7e66b2406f7cb9d@https://uploads.ungrounded.net/ruffle_wrapper/lib/dd280c8a7aa464beeccc78df18fd16df.wasm:wasm-function[5737]:0x40bffe
A@https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1616425469:1:3265
a@https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1616425469:1:2840

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1616425469%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F782000%2F782567_arcane-maiden-v1-4-compre.swf%3F1615329844%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22605b783c4be36%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A1024%2C%22height%22%3A576%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F782000%2Fflash_782567_card.png%3Ff1614452781%22%7D
SWF URL: https://uploads.ungrounded.net/782000/782567_arcane-maiden-v1-4-compre.swf?1615329844

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-22
Channel: nightly
Built: 2021-03-22T00:19:43.563Z
Commit: 760e8421ab2b41ed11e124334d81325c7e0f235e

**Comment by relrelb** [comment] 2021-04-03 18:34
Duplicate of #3795.

**Closed by relrelb** 2021-04-03 18:34 UTC
