### ISSUE TITLE
Error on https://f.silvergames.com/ruffle/player.php

### ISSUE THREAD

**Issue by milas248** [ruffle-rs/ruffle#10728] opened 2023-04-18 08:18 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:595:51
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:595:51
    at V.n.wbg.__wbg_new_15d3966e9981a196 (https://f.silvergames.com/ruffle/23042023/core.ruffle.14495c7254c43299a2c5.js:1:50226)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h927501cce3fc7417 (<anonymous>:wasm-function[8190]:0x845f40)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (<anonymous>:wasm-function[5484]:0x7720ef)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (<anonymous>:wasm-function[8072]:0x840d89)
    at core::panicking::panic::h54beb3f515dd3c6d (<anonymous>:wasm-function[7468]:0x806557)
    at ruffle_core::bitmap::bitmap_data::BitmapData::update_dirty_texture::hee3ddbdfbdc50e9d (<anonymous>:wasm-function[1229]:0x3daf97)
    at <ruffle_core::library::MovieLibrarySource as ruffle_render::bitmap::BitmapSource>::bitmap_handle::h0909caf8b3654249 (<anonymous>:wasm-function[3276]:0x66e291)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_shape::hd515b52f2b24d068 (<anonymous>:wasm-function[970]:0x34ce2a)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h2a01979e41768b81 (<anonymous>:wasm-function[2276]:0x56cf34)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h8b435e95ba744ef1 (<anonymous>:wasm-function[615]:0x1e2713)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://f.silvergames.com/ruffle/player.php?id=273
SWF URL: https://f.silvergames.com/TU-95.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-02
Channel: nightly
Built: 2023-04-02T00:19:29.297Z
Commit: 58cbc38983ff175005522d009da3fbfcf6208ef3
Is extension: false

# Metadata
width: 670
height: 450
frameRate: 24
numFrames: 31
swfVersion: 9
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3871229

**Comment by n0samu** [comment] 2023-05-25 12:17
Duplicate of #10699

**Closed by n0samu** 2023-05-25 12:17 UTC
Labels: error-report
