### ISSUE TITLE
Error on https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/787ceabe-8014-4ab6-8130-775d546be4ba/

### ISSUE THREAD

**Issue by BionicScout** [ruffle-rs/ruffle#14780] opened 2024-01-16 06:10 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at H.n.wbg.__wbg_new_3a66822ed076951c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.277e1c0c8411b070fb05.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9723d5197bb8db17 (wasm://wasm/03641ffe:wasm-function[10795]:0xa1eb9a)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/03641ffe:wasm-function[6619]:0x906f09)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/03641ffe:wasm-function[10517]:0xa188de)
    at core::ops::function::Fn::call::hb978f9f48a799a28 (wasm://wasm/03641ffe:wasm-function[6925]:0x91de6c)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::hc51c5f6fae9dc4b8 (wasm://wasm/03641ffe:wasm-function[5458]:0x8a0180)
    at <T as wgpu::context::DynContext>::device_create_texture::hd49f06c9d2e89e43 (wasm://wasm/03641ffe:wasm-function[7435]:0x94a8b8)
    at wgpu::Device::create_texture::h99fc2b89c1de6bae (wasm://wasm/03641ffe:wasm-function[5787]:0x8bbb23)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::hc837859f57e5fea4 (wasm://wasm/03641ffe:wasm-function[2199]:0x5ff889)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::h7bdf08110a5dd467 (wasm://wasm/03641ffe:wasm-function[1603]:0x4e1705)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1868()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics (0x00004626) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/787ceabe-8014-4ab6-8130-775d546be4ba/?kongregate_host=www.kongregate.com
SWF URL: https://game286444.konggames.com/gamez/0028/6444/live/ma2.9.8GProt.swf?kongregate_game_version=1506420754

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-16
Channel: nightly
Built: 2024-01-16T00:15:30.688Z
Commit: 3f17d1c7788b198519b8c66953a47d44afc60798
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9716767

**Comment by MartySVK** [comment] 2024-01-16 09:36
already created - https://github.com/ruffle-rs/ruffle/issues/13946

**Comment by evilpie** [comment] 2024-01-16 10:15
duplicate of #13946

**Closed** 2024-01-16 10:15 UTC
Labels: error-report
