### ISSUE TITLE
Error on https://website-aio.herokuapp.com/5.html

### ISSUE THREAD

**Issue by jminyard07** [ruffle-rs/ruffle#8339] opened 2022-10-20 12:51 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://website-aio.herokuapp.com/ruffle/core.ruffle.a5a3737e9b5245475835.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/017ff2d2:wasm-function[1024]:0x2a831c)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017ff2d2:wasm-function[1487]:0x32b6b4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/017ff2d2:wasm-function[4934]:0x4897bc)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017ff2d2:wasm-function[3631]:0x446643)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017ff2d2:wasm-function[5089]:0x48cc4c)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/017ff2d2:wasm-function[4990]:0x48a778)
    at core::ops::function::FnOnce::call_once::h2b64b87dbbaf5054 (wasm://wasm/017ff2d2:wasm-function[1116]:0x2c7c51)
    at ruffle_core::avm1::function::Executable::exec::h7dbb30579b1dd750 (wasm://wasm/017ff2d2:wasm-function[365]:0xffee6)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h55e375c84faa5088 (wasm://wasm/017ff2d2:wasm-function[491]:0x198794)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://website-aio.herokuapp.com/5.html#U2FsdGVkX19gFqgEbayr2g04yV7R67eiPflx/utbkJez3ZqwQK1/5bEO5iqiO0Y73rQhlDuuNC9+brrMT2j5UpDm9r0w/+Nr2kMb6fXHReIoSt1stBRAxD1QxSPWwlga
SWF URL: https://holy-unblocker.github.io/theatre/public/flash/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-06
Channel: nightly
Built: 2022-10-06T00:17:35.767Z
Commit: 4b2907ead56e5806f441fcb7e32e1030166cb2d2
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3275243

**Comment by n0samu** [comment] 2022-10-20 13:04
Duplicate of #4932

**Closed by n0samu** 2022-10-20 13:04 UTC
Labels: duplicate, error-report
