### ISSUE TITLE
Error on moz-extension://d0213744-04e7-4e3c-a252-2f2c6e5d0b10/player.html

### ISSUE THREAD

**Issue by Mershan13** [ruffle-rs/ruffle#10352] opened 2023-03-25 03:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmap_data.rs:262:46

# Player Info
Allows script access: false

# Page Info
Page URL: moz-extension://d0213744-04e7-4e3c-a252-2f2c6e5d0b10/player.html?url=https%3A%2F%2Fi.flipline.com%2Fgamefiles%2Fpapaspastaria%2Fpapaspastaria_v2.swf
SWF URL: https://i.flipline.com/gamefiles/papaspastaria/papaspastaria_v2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-19
Channel: nightly
Built: 2023-03-19T00:19:16.337Z
Commit: 5aac938e868e7dab2550d9482f754a6daf314921
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 13955205

**Comment by n0samu** [comment] 2023-03-25 03:07
Duplicate of #9852

**Closed by n0samu** 2023-03-25 03:07 UTC
Labels: duplicate, error-report
