### ISSUE TITLE
Error on http://www.freeworldgroup.com/games9/gameindex/tank2012.htm

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#7126] opened 2022-05-31 22:40 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:576:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:576:14
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/core.ruffle.b1d2ea65e946d5e007e4.js:1:7024)
    at std::sync::once::Once::call_once::{{closure}}::h2b3586a1c348e776 (http://www.freeworldgroup.com/ruffle/313ff82c6594a4402510.wasm:wasm-function[1182]:0x2ae273)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (http://www.freeworldgroup.com/ruffle/313ff82c6594a4402510.wasm:wasm-function[1406]:0x2e9848)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0e8f59b7c29e471d (http://www.freeworldgroup.com/ruffle/313ff82c6594a4402510.wasm:wasm-function[4752]:0x4390a3)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (http://www.freeworldgroup.com/ruffle/313ff82c6594a4402510.wasm:wasm-function[3140]:0x3dd913)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (http://www.freeworldgroup.com/ruffle/313ff82c6594a4402510.wasm:wasm-function[4935]:0x43eff0)
    at core::option::expect_failed::h919b9707962a9d34 (http://www.freeworldgroup.com/ruffle/313ff82c6594a4402510.wasm:wasm-function[5538]:0x44c45b)
    at ruffle_core::display_object::stage::Stage::root_clip::h4a80d66d336a1510 (http://www.freeworldgroup.com/ruffle/313ff82c6594a4402510.wasm:wasm-function[3485]:0x3f5aa5)
    at ruffle_web::Ruffle::tick::hfe95d35e069fc81b (http://www.freeworldgroup.com/ruffle/313ff82c6594a4402510.wasm:wasm-function[610]:0x1c90c6)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0f46189c0304e339 (http://www.freeworldgroup.com/ruffle/313ff82c6594a4402510.wasm:wasm-function[5715]:0x453e98)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games9/gameindex/tank2012.htm
SWF URL: http://www.freeworldgroup.com/games9/tank2012/ENsecure.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-28
Channel: nightly
Built: 2022-05-28T00:16:17.265Z
Commit: aad3ad6c087816b2259123c78f00b3d22b1b61de
Is extension: false

**Comment by relrelb** [comment] 2022-06-01 18:58
Duplicate of #5832.

**Closed by relrelb** 2022-06-01 18:58 UTC
Labels: error-report
