### ISSUE TITLE
Error on https://games.kidzsearch.com/computer/flashgame_data/ruffleplayer.html

### ISSUE THREAD

**Issue by TigervirusK** [ruffle-rs/ruffle#8938] opened 2022-12-27 15:53 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:760:32
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:760:32
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://games.kidzsearch.com/computer/ruffle/core.ruffle.908f55297e6fed608f53.js:1:6974)
    at std::sync::once::Once::call_once::{{closure}}::h868aa5cd1fef1a90 (wasm://wasm/0184666e:wasm-function[1059]:0x2a65b0)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/0184666e:wasm-function[1352]:0x30d6aa)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h117918d4b59dff10 (wasm://wasm/0184666e:wasm-function[4886]:0x497566)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0184666e:wasm-function[3635]:0x458b1e)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0184666e:wasm-function[5116]:0x49c0a0)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/0184666e:wasm-function[4938]:0x498410)
    at core::ops::function::FnOnce::call_once::hd91e6f3c9aad192c (wasm://wasm/0184666e:wasm-function[1244]:0x2e4cc9)
    at ruffle_core::avm1::function::Executable::exec::hed811b2aa544b765 (wasm://wasm/0184666e:wasm-function[355]:0xdc856)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h75382bd14e13c52a (wasm://wasm/0184666e:wasm-function[900]:0x2700be)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://games.kidzsearch.com/computer/flashgame_data/ruffleplayer.html?game=chibi-knight-ks120414-153146
SWF URL: https://games.kidzsearch.com/computer/flashgame_data/2/ksff_153146_H8me4QU2dF0alM.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14695.166.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-16
Channel: nightly
Built: 2022-11-16T00:18:41.332Z
Commit: b3debc96afab2882c70ee27cf4dd5230874e803b
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 25
numFrames: 7
swfVersion: 9
backgroundColor: #666666
isActionScript3: false
uncompressedLength: 7885259

**Comment by n0samu** [comment] 2022-12-27 21:34
Duplicate of #3756

**Closed by n0samu** 2022-12-27 21:34 UTC
Labels: duplicate, error-report

**Comment by TigervirusK** [comment] 2022-12-28 03:26
is it fixed

**Comment by TigervirusK** [comment] 2022-12-28 03:28
![image](https://user-images.githubusercontent.com/121506623/209752720-d872eb22-49df-49a7-84d9-59ba2f018d1f.png)

it is still not fixed

**Comment by n0samu** [comment] 2022-12-28 05:16
No, this problem has existed for more than a year and we don't know how to fix it at the moment, sorry.
