### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by OrionGrinn** [ruffle-rs/ruffle#9853] opened 2023-03-04 22:09 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:317:9
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:317:9
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2154:21)
    at std::sync::once::Once::call_once::{{closure}}::h97aad3534cecf95d (wasm://wasm/0293e1ca:wasm-function[2038]:0x4e93a9)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/0293e1ca:wasm-function[1973]:0x4db496)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h58f54bbbf27f6496 (wasm://wasm/0293e1ca:wasm-function[7457]:0x7b20f6)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/0293e1ca:wasm-function[5249]:0x70a1d3)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/0293e1ca:wasm-function[7786]:0x7c136a)
    at core::panicking::panic::h27b5eefa3e4ff738 (wasm://wasm/0293e1ca:wasm-function[7178]:0x78ddc8)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hc57a77f2751817cf (wasm://wasm/0293e1ca:wasm-function[599]:0x1dc530)
    at ruffle_core::loader::Loader::preload_tick::h4459d8164e57e13f (wasm://wasm/0293e1ca:wasm-function[817]:0x2c5d94)
    at ruffle_web::Ruffle::tick::hf697cc8ddb70410e (wasm://wasm/0293e1ca:wasm-function[673]:0x244bb1)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=700&sp=0&questionSet=&r=3701083&&width=640&height=500&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-04
Channel: nightly
Built: 2023-03-04T00:19:50.818Z
Commit: 1ef539e31bc58569d10abda9a70ab9c0d5c03349
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by Lord-McSweeney** [comment] 2023-03-05 15:31
Duplicate of #9826.

**Closed by Lord-McSweeney** 2023-03-05 15:31 UTC
Labels: avm1, error-report
