### ISSUE TITLE
Error on https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/f5032761-91db-4cfb-8137-2d25e2911b01/

### ISSUE THREAD

**Issue by Fesisurpe** [ruffle-rs/ruffle#16060] opened 2024-04-21 09:35 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.4/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.4/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.0ddf9f5ca88b07c12187.js:1:73847)
    at js_sys::Error::new::hf655a9c3d4762b78 (wasm://wasm/03a92632:wasm-function[13958]:0xb2f82d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h90bd631d8898e3d0 (wasm://wasm/03a92632:wasm-function[11549]:0xad92d5)
    at std::panicking::rust_panic_with_hook::h9aabd906218897c3 (wasm://wasm/03a92632:wasm-function[7122]:0x9a0cbd)
    at core::panicking::panic_fmt::h3aff855fe938c13f (wasm://wasm/03a92632:wasm-function[11260]:0xad2ca1)
    at core::ops::function::Fn::call::h80c4b4c756a0def7 (wasm://wasm/03a92632:wasm-function[7441]:0x9b8f50)
    at wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::hb8450b865ef430f2 (wasm://wasm/03a92632:wasm-function[5876]:0x92ee3f)
    at <T as wgpu::context::DynContext>::device_create_texture::hc292514770858add (wasm://wasm/03a92632:wasm-function[7936]:0x9e196d)
    at wgpu::Device::create_texture::h433c111865266591 (wasm://wasm/03a92632:wasm-function[6247]:0x952d16)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::h9f52ffc6ad75ee7d (wasm://wasm/03a92632:wasm-function[2318]:0x621100)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1910()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Inc., Intel(R) HD Graphics 6000, OpenGL 4.1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/f5032761-91db-4cfb-8137-2d25e2911b01/?kongregate_host=www.kongregate.com
SWF URL: https://game286444.konggames.com/gamez/0028/6444/live/ma2.9.8GProt.swf?kongregate_game_version=1506420754

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-04-21
Channel: nightly
Built: 2024-04-21T00:06:10.857Z
Commit: 8a4946fa03ca1eb1e1119c0284f3462252e4366e
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9716767

**Comment by MartySVK** [comment] 2024-04-21 11:12
Duplicate of https://github.com/ruffle-rs/ruffle/issues/13946

**Closed** 2024-05-21 13:17 UTC
Labels: duplicate, render-wgpu, error-report
