### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by RevontuletCXVII** [ruffle-rs/ruffle#6378] opened 2022-03-01 01:15 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1645741783%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2294904944.80a8dbb8c6d126185261d0f2de5ed3f766aa63ff747d1e%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22621d707a01eb8%22%2C%22NewgroundsAPI_SessionID%22%3A%22PO4N4ZnXfdUVZUOzRcVF40213580c3a4c8cd7e3e6a0916f5a237d349cee8w0pA%22%2C%22NewgroundsAPI_UserName%22%3A%22RevontuletCXVII%22%2C%22NewgroundsAPI_UserID%22%3A10343989%2C%22ng_username%22%3A%22RevontuletCXVII%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-24
Channel: nightly
Built: 2022-02-24T00:17:59.239Z
Commit: 056eee8b46c91e2dbbb54530bb30554766a703ff
Is extension: false

**Comment by relrelb** [comment] 2022-03-01 06:10
Duplicate of #3756.

**Closed by relrelb** 2022-03-01 06:10 UTC
Labels: error-report
