### ISSUE TITLE
Error on https://shsgames.github.io/g/6f2e0289/electric-man-2

### ISSUE THREAD

**Issue by yobrododo** [ruffle-rs/ruffle#6578] opened 2022-03-31 08:34 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.85c76c80d7a8e44da68e.js:1:7441)
    at std::sync::once::Once::call_once::{{closure}}::h9d9f5504bc648392 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.31/c79b28123812624c4e6f.wasm:wasm-function[1019]:0x2afd76)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.31/c79b28123812624c4e6f.wasm:wasm-function[1480]:0x3303cb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h682da277e124560a (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.31/c79b28123812624c4e6f.wasm:wasm-function[4947]:0x485eda)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.31/c79b28123812624c4e6f.wasm:wasm-function[3320]:0x42bca8)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.31/c79b28123812624c4e6f.wasm:wasm-function[5233]:0x492212)
    at core::panicking::panic::h5d6906e2c1099660 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.31/c79b28123812624c4e6f.wasm:wasm-function[4944]:0x485a01)
    at core::ops::function::FnOnce::call_once::h1f29f8ebf1f1a0a0 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.31/c79b28123812624c4e6f.wasm:wasm-function[1112]:0x2c9c47)
    at ruffle_core::avm1::function::Executable::exec::h6c8637e3aed40f10 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.31/c79b28123812624c4e6f.wasm:wasm-function[393]:0x135022)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hdb981699253ce5b7 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.31/c79b28123812624c4e6f.wasm:wasm-function[384]:0x126ac4)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://shsgames.github.io/g/6f2e0289/electric-man-2
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14469.58.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.86 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-31
Channel: nightly
Built: 2022-03-31T00:18:08.983Z
Commit: 7e8738d82e1c35d8d1ac0bd442288e6969f60bdf
Is extension: false

**Comment by relrelb** [comment] 2022-03-31 15:11
Duplicate of #4932.

**Closed by relrelb** 2022-03-31 15:11 UTC
Labels: error-report
