### ISSUE TITLE
ruffle.js:1 AVM2 error: VerifyError: Trait z in class BitmapAsset marked as override, does not override any other trait

### ISSUE THREAD

**Issue by Lhinger** [ruffle-rs/ruffle#7631] opened 2022-08-10 18:51 UTC
### Describe the bug

i dont know what it is

### Expected behavior

the game to work

### Affected platform

Self-hosted version

### Operating system

windows 10

**Comment by torokati44** [comment] 2022-08-10 19:04
It would be nice if you could link to the content you were watching/playing when encountering this error!

**Comment by torokati44** [comment] 2022-08-10 19:11
FWIW https://z0r.de/6740 gives the exact same error BTW, and it has this class embedded in it:

```as3
package mx.core
{
   import flash.display.BitmapData;
   import flash.display.DisplayObjectContainer;
   import flash.events.Event;
   import flash.geom.Point;
   import flash.system.ApplicationDomain;
   
   use namespace mx_internal;
   
   public class BitmapAsset extends FlexBitmap implements IFlexAsset, IFlexDisplayObject, ILayoutDirectionElement
```

and this one:
```as3
package mx.core
{
   import flash.display.Bitmap;
   import flash.display.BitmapData;
   import mx.utils.NameUtil;
   
   use namespace mx_internal;
   
   public class FlexBitmap extends Bitmap
```

And the problem is that our `DisplayObject` class only has a few properties implemented, and `z` is not one of them.

**Comment by adrian17** [comment] 2022-08-10 21:06
Yeah, the issue is that `z` was added in later version, so we should probably implement namespace versioning first.

**Comment by mero09-99** [comment] 2022-09-27 13:53
any fix for this?

**Comment by Lord-McSweeney** [comment] 2024-06-30 07:59
z0r 7887 needs `NetStream.appendBytes()`. z0r 6740 is working. Version-gating for `DisplayObject.z` has been implemented, so I'm closing this issue.

**Closed by Lord-McSweeney** 2024-06-30 07:59 UTC
Labels: bug, avm2
