### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by MrShadow041** [ruffle-rs/ruffle#18755] opened 2024-11-25 20:28 UTC
### Describe what you were doing

I just tried to execute de .exe

### What does the crash message say?

panicked at desktop\src\app.rs:466:14:
GUI controller should be created: No compatible graphics backends of any kind were available

### Ruffle Version

0.1.0-nightly (5da69aaa04642af2593679d1761482b16955517e 2024-11-25)

### Affected platform

Desktop app

### Operating system

Windows 10.0.19045 (Windows 10 Home Single Language) [64-bit]

**Comment by kjarosh** [comment] 2024-11-25 20:58
Duplicate of https://github.com/ruffle-rs/ruffle/issues/18672

**Closed by kjarosh** 2024-11-25 20:58 UTC
Labels: bug, panic
