### ISSUE TITLE
Grey screen when using Ruffle emulator on Neopets

### ISSUE THREAD

**Issue by Ampton** [ruffle-rs/ruffle#12931] opened 2023-08-24 02:25 UTC
### Describe the bug

I installed the Ruffle emulator to Firefox to get access to the Neopets flash games not currently working through Neopets' in-site integration of Ruffle. At first this allowed me to play a wide variety of games (notably Snot Splatter, a favourite game, which did not work without me adding Ruffle to my browser, and worked perfectly when I did add it). However, any game I load up now (including ones that worked without Ruffle added to my browser) results in the grey square shown in the picture below.

![image](https://github.com/ruffle-rs/ruffle/assets/51313349/d9a4ea21-1357-4026-8b76-6b12e522212e)

### Expected behavior

I expected the game to run as normal like it had been in the past, but it resulted only in the grey screen.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Mozilla Firefox (latest version)

**Comment by Lord-McSweeney** [comment] 2023-08-24 02:29
On https://www.neopets.com/games/game.phtml?game_id=1100&size=regular&quality=high&play=true , if you right-click on the gray area where the game is supposed to be, is there an option that says "Copy Debug Info"? If so, could you click it and paste the output here?

**Comment by n0samu** [comment] 2023-08-24 02:30
Duplicate of #12700. This would already be fixed by #12744, but unfortunately Mozilla still hasn't approved our update. Hopefully it will be up soon.

**Closed by n0samu** 2023-08-24 02:30 UTC
Labels: bug
