### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by A-dot2** [ruffle-rs/ruffle#4568] opened 2021-06-13 09:42 UTC
# Error Info
Error name: TypeError
Error message: Could not download wasm module
Error stack:
```
TypeError: Could not download wasm module
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1623249483%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592864_UberSceneCreator2.swf%3F1333232588%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2246115829.8d60442e2d5c0639d41b2be58590135069e9141ebebc3c%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2260c5d2f114024%22%2C%22NewgroundsAPI_SessionID%22%3A%22yUYP1vVGU6wRJ2gv5s774e875758b485681b78161089c116c16aee5c1ebbTCpH%22%2C%22NewgroundsAPI_UserName%22%3A%22nonameok%22%2C%22NewgroundsAPI_UserID%22%3A8376073%2C%22ng_username%22%3A%22nonameok%22%7D%2C%22width%22%3A700%2C%22height%22%3A700%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592864_card.png%3Ff1601421052%22%7D

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-09
Channel: nightly
Built: 2021-06-09T00:13:19.098Z
Commit: 5acc4767893bfcf9c97699b1f21a9c2eda3d56b9

**Comment by torokati44** [comment] 2021-06-13 12:16
Duplicate of #4250.

**Closed by torokati44** 2021-06-13 12:16 UTC
