### ISSUE TITLE
How to play .flv format video

### ISSUE THREAD

**Issue by xutian111** [ruffle-rs/ruffle#7968] opened 2022-09-13 06:15 UTC
![image](https://user-images.githubusercontent.com/89231915/189824071-66891466-266a-4bcf-a9c7-14dfb0706e0c.png)

**Comment by n0samu** [comment] 2022-09-13 06:36
Sorry, but this is not possible right now. Ruffle does not yet support this feature. Closing as duplicate of #7966.

**Closed by n0samu** 2022-09-13 06:36 UTC
Labels: duplicate, question
