### ISSUE TITLE
Error on https://game179258.konggames.com/games/randomnine/cardinal-quest-2/frame/9afcc9fd-0230-4af6-84ee-180a4c4bb2a5/

### ISSUE THREAD

**Issue by skrall5** [ruffle-rs/ruffle#18187] opened 2024-10-05 17:38 UTC
# Error Info
Error name: Error
Error message: panicked at render/naga-pixelbender/src/lib.rs:1223:29:
Unimplemented opcode Step
Error stack:
```
Error: panicked at render/naga-pixelbender/src/lib.rs:1223:29:
Unimplemented opcode Step
    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.dcfa3c9d8d109b5ae831.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::hea22a414f237eb04 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[12745]:0x9886b8)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::he009475d8c349687 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[9803]:0x918ca0)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[6378]:0x8112e3)
    at ruffle_web.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[9525]:0x909a43)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h9a7cc7e49d4d677d (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[8397]:0x8b4178)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::display::shader_data::init::h15c1631a764034ba (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[1382]:0x3d437b)
    at ruffle_web.wasm.ruffle_core::avm2::function::exec::h37b1e7377a08145e (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[1335]:0x3b1cac)
    at ruffle_web.wasm.ruffle_core::avm2::object::TObject::call_method::h5e60a58765904240 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[2095]:0x523c5d)
    at ruffle_web.wasm.ruffle_core::avm2::activation::Activation::run_actions::h9931339145612994 (wasm://wasm/ruffle_web.wasm-03223006:wasm-function[755]:0x29eeb)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at flixelcq.tile::FlxCqTilemap()
    at cq::CqLevel()
    at cq::CqWorld/executeGoToLevel()
    at cq.states::GameState/continueInitialisation()
    at cq.states::GameState/update()
    at flixel::FlxState/tryUpdate()
    at flixel::FlxGame/update()
    at cq::Main/update()
    at flixel::FlxGame/step()
    at flixel::FlxGame/onEnterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game179258.konggames.com/games/randomnine/cardinal-quest-2/frame/9afcc9fd-0230-4af6-84ee-180a4c4bb2a5/?kongregate_host=www.kongregate.com
SWF URL: https://game179258.konggames.com/gamez/0017/9258/live/cq2.swf?kongregate_game_version=1465851167

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-10-05
Channel: nightly
Built: 2024-10-05T00:06:07.565Z
Commit: eecb77a26442b9ef7cb9d85fc1b6d4f7f5df6db6
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 15
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 20519535

**Comment by evilpie** [comment] 2024-10-12 16:11
Duplicate of #14068

**Closed by evilpie** 2024-10-12 16:11 UTC
Labels: unimplemented, error-report, pixelbender
