### ISSUE TITLE
Error on https://playgamesfreeaz.info/learntofly.html

### ISSUE THREAD

**Issue by Adam129Pro** [ruffle-rs/ruffle#6648] opened 2022-04-08 06:57 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
@https://playgamesfreeaz.info/ruffle/ruffle.js:1:6924
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hf7fd718057964857]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h9d91fa0fae16500f]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h91d2023e5afe1929]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h4d06e5cc335302b3]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1c9b256bef969e15]@[wasm code]
wasm-stub@[native code]
I@https://playgamesfreeaz.info/ruffle/ruffle.js:1:3550
a@https://playgamesfreeaz.info/ruffle/ruffle.js:1:2841
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://playgamesfreeaz.info/swf/learntofly.swf
Param base: http://playgamesfreeaz.info/swf/learntofly.swf
Param quality: autohigh
Param allowFullScreen: false
Param wmode: direct
Param allowScriptAccess: always
Param scale: showall
Param bgcolor: #000000
Param hasPriority: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://playgamesfreeaz.info/learntofly.html
SWF URL: https://playgamesfreeaz.info/swf/learntofly.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-04
Channel: nightly
Built: 2021-04-04T00:42:01.875Z
Commit: e2f124ee34eb27c0f6463a76534b4936e750d58a

**Comment by n0samu** [comment] 2024-06-23 23:37
Likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:37 UTC
Labels: error-report
