### ISSUE TITLE
Binding of isaac not loading in all details

### ISSUE THREAD

**Issue by BurritoHangover** [ruffle-rs/ruffle#8733] opened 2022-12-10 03:34 UTC
### Describe the bug

There is a glitch in Binding of isaac flash (all of the boi versions including wrath of the lamb) where all the details are invisible. This includes invisible rocks on the ground making most of the levels an invisible maze, and also making it look like all the doors are open, and making it look like there are more doors than normal. Also all the tiny details on the walls, and cobwebs on the walls are gone too.

### Expected behavior

There should be visible rocks and details in the game. There should be doors that are not fake.

### Affected platform

Online demo

### Operating system

Every OS

### Browser

Google Chrome 93

**Comment by n0samu** [comment] 2022-12-10 06:33
This is fixed in the Ruffle desktop app since BitmapData.Draw was implemented there. The feature should come to web builds of Ruffle at some point in the future. The implementation is being worked on in #6629.

Closing as duplicate of #5522.

**Closed by n0samu** 2022-12-10 06:33 UTC
Labels: bug, duplicate
