### ISSUE TITLE
Error on https://connectdot.connectsolutions.com/l8sxlq958m4/?refresh-parent=true

### ISSUE THREAD

**Issue by SBCounty79** [ruffle-rs/ruffle#2912] opened 2021-01-27 23:15 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29

# Player Info
Allows script access: true

# Page Info
Page URL: https://connectdot.connectsolutions.com/l8sxlq958m4/?refresh-parent=true
SWF URL: https://connectdot.connectsolutions.com/l8sxlq958m4/default/viewer.swf?aicc_url=https%3A%2F%2Fconnectdot.connectsolutions.com%2Fservlet%2Fverify%3Fsco-id%3D1040471472%3B1303272860%26airspeed%3D1&aicc_sid=5yh9kpkwsw2bbi3zs4rfqxtyox8peg4v&airspeed=1%2Flmsproxy%3Fsco-id%3D1040471472%26link-transcript-id%3D1303272860%26sid%3D5yh9kpkwsw2bbi3zs4rfqxtyox8peg4v%26qdata%3D&baseurl=%2Fl8sxlq958m4%2Fdefault%2F&plugin=plugin.swf&host=connectdot.connectsolutions.com&link-transcript-id=1303272860&path=%2Fl8sxlq958m4%2F&refresh-parent=true&reserved-license-id=1303272861&sco-id=1040480818&ticket=5yh9kpkwsw2bbi3zs4rfqxtyox8peg4v&transcript-id=1303272859&isLive=false&room=1040471472;session=breezbreezrstc2zt6aa88afin&ticket=5yh9kpkwsw2bbi3zs4rfqxtyox8peg4v&proxy=false&appInstance=7/1030773862-2/output/&ott=gkyzi9fkzc&css=airspeed&fcsContent=true&pbMode=normal&conStrings=rtmps%3A%2F%2Fdot-fms7.connectsolutions.com%3A443%2F%3Frtmp%3A%2F%2Flocalhost%3A8506%2F&connectors=iad-acts06.cosocloud.com,iad-acts04.cosocloud.com&connector_proto=wss:443&lang=en&account_id=7

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-27
Channel: nightly
Built: 2021-01-27T00:33:31.688Z
Commit: a0159a5efaf9cb29f3d0e5b4a1e1173ad811728a

**Comment by n0samu** [comment] 2022-10-29 23:04
Duplicate of #2915

**Closed by n0samu** 2022-10-29 23:04 UTC
Labels: duplicate, error-report
