### ISSUE TITLE
Error on https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/57bc5504-a9cf-476e-b867-e4ac07fb1497/

### ISSUE THREAD

**Issue by laiaazure** [ruffle-rs/ruffle#14849] opened 2024-01-19 22:12 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at H.n.wbg.__wbg_new_3a66822ed076951c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.520782bf6846ea730530.js:1:56211)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h17602019b8af7fc3 (wasm://wasm/03667966:wasm-function[10825]:0xa25bcc)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/03667966:wasm-function[6633]:0x9103a6)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/03667966:wasm-function[10539]:0xa1f797)
    at core::ops::function::Fn::call::h5c3bbc5f192c8d63 (wasm://wasm/03667966:wasm-function[6940]:0x9264e5)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h8d87cf405961e005 (wasm://wasm/03667966:wasm-function[5463]:0x8a5fb5)
    at <T as wgpu::context::DynContext>::device_create_texture::h1b5a7255b74614d8 (wasm://wasm/03667966:wasm-function[7445]:0x952798)
    at wgpu::Device::create_texture::h14fab7c9d8eec759 (wasm://wasm/03667966:wasm-function[5795]:0x8c3120)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::hafa483ccc9e211e2 (wasm://wasm/03667966:wasm-function[2205]:0x609860)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::h22a734f76c89e797 (wasm://wasm/03667966:wasm-function[1613]:0x4ed701)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1871()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Plus Graphics (0x00008A52) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game286444.konggames.com/games/clarusvictoria/pre-civilization-marble-age/frame/57bc5504-a9cf-476e-b867-e4ac07fb1497/?kongregate_host=www.kongregate.com
SWF URL: https://game286444.konggames.com/gamez/0028/6444/live/ma2.9.8GProt.swf?kongregate_game_version=1506420754

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-19
Channel: nightly
Built: 2024-01-19T00:15:24.643Z
Commit: 5f123c3c011b044670602c2b0bb986527fc57135
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9716767

**Comment by evilpie** [comment] 2024-01-19 22:32
Duplicate of #13946.

**Closed by evilpie** 2024-01-19 22:32 UTC
Labels: error-report
