### ISSUE TITLE
Error on http://www.shiftup.net/flash/mono/ruffle.html

### ISSUE THREAD

**Issue by knishitani41** [ruffle-rs/ruffle#7078] opened 2022-05-24 13:27 UTC
# Error Info
Error name: Error
Error message: panicked at 'cannot recursively acquire mutex', /home/gsm64/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
Error stack:
```
@http://www.shiftup.net/flash/ruffle_jp/ruffle.js:1:6255
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h2bcfbde11c23034f]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hf0c8a8316e3dd073]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h95ac9d37c251b3e8]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::hc5713da015ebaa19]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic::{{closure}}::h4e3b5b9a1001f3ac]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h762ffacf7f1a31f9]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic::h878099173ba960dd]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hccf096e1fa9d8b40]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1209a9c1d54186e6]@[wasm code]
wasm-stub@[native code]
P@http://www.shiftup.net/flash/ruffle_jp/ruffle.js:1:3699
a@http://www.shiftup.net/flash/ruffle_jp/ruffle.js:1:2841
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.shiftup.net/flash/mono/ruffle.html
SWF URL: http://www.shiftup.net/flash/mono/Base.swf?saveData=&pname=

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-09
Channel: nightly
Built: 2021-03-09T14:20:58.566Z
Commit: 47950110aa2357051a956adbe8154ac60a128559

**Comment by knishitani41** [comment] 2022-05-24 13:28
I am unable to play this game

**Comment by Toad06** [comment] 2022-05-24 13:48
If your device is an iPad, updating it to 15.5 should fix the issue.

**Comment by n0samu** [comment] 2024-06-23 23:32
Closing as likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:32 UTC
Labels: error-report
