### ISSUE TITLE
Error on https://papasgamesfree.io/flipline/jacksmith/

### ISSUE THREAD

**Issue by Dududueedu104** [ruffle-rs/ruffle#17643] opened 2024-08-25 20:12 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In CommandEncoder::copy_texture_to_buffer
    Copy error
      Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In CommandEncoder::copy_texture_to_buffer
    Copy error
      Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096


    at n.wbg.__wbg_new_796382978dfd4fb0 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1c418e86b251861b5eca.js:1:83857)
    at ruffle_web.wasm.js_sys::Error::new::he5ee53fe8c974231 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[12738]:0x9849fe)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::hd277f71cef9d6cd2 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[9803]:0x913517)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[6265]:0x7f7d18)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[10213]:0x92f03b)
    at ruffle_web.wasm.core::ops::function::Fn::call::h6a322d70a0e95231 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[6576]:0x81a541)
    at ruffle_web.wasm.wgpu::backend::wgpu_core::ContextWgpuCore::handle_error::h862246c3d5ae0228 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[2069]:0x5088db)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::hdadbe15059c042cd (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[9781]:0x90ff89)
    at ruffle_web.wasm.wgpu::CommandEncoder::copy_texture_to_buffer::h09d33a43c3c1d37a (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[9403]:0x8f1033)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::resolve_sync_handle::hddfdad96c2464ce0 (wasm://wasm/ruffle_web.wasm-0320043a:wasm-function[5791]:0x7d0318)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mali-G68"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 16383, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 124, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: best
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://papasgamesfree.io/flipline/jacksmith/
SWF URL: https://papasgamesfree.io/flipline/jacksmith/jacksmith.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-08-25
Channel: nightly
Built: 2024-08-25T00:06:04.595Z
Commit: 6fca7444b6b0be3157e1de9f24aa928ec969bd50
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9363111

**Comment by evilpie** [comment] 2024-08-30 20:10
Duplicate of #11591

**Closed by evilpie** 2024-08-30 20:10 UTC
Labels: error-report
