### ISSUE TITLE
Error on https://h-flash.com/aisha-clanclan-hentai-flash/

### ISSUE THREAD

**Issue by Yeagh** [ruffle-rs/ruffle#10617] opened 2023-04-09 08:01 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 231154 but the index is 234472', /home/runner/.cargo/git/checkouts/h263-rs-6a92376340b27390/8c00d0e/h263/src/decoder/cpu/idct.rs:142:48
Error stack:
```
@https://h-flash.com/data/ruffle/core.ruffle.77b76ff8ebf10abc4963.js:1:48787
wasm-stub@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h321a9078ff9936f2]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h2a7f454a5f5da218]@[wasm code]
<?>.wasm-function[core::panicking::panic_bounds_check::h69c7a7cd0b1c2bb8]@[wasm code]
<?>.wasm-function[h263_rs::decoder::cpu::idct::idct_channel::h0aadb2755ac8afeb]@[wasm code]
<?>.wasm-function[<ruffle_video_software::decoder::h263::H263Decoder as ruffle_video_software::decoder::VideoDecoder>::decode_frame::h6d5ce1d005bb7b6c]@[wasm code]
<?>.wasm-function[<ruffle_video_software::backend::SoftwareVideoBackend as ruffle_video::backend::VideoBackend>::decode_video_stream_frame::h0e9c5fe40137d194]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::video::Video::seek::h0fced08fd91dc9f6]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h588d4b7eb59a00e5]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h195a33510c0b747d]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::place_object::ha18b2972f2fca4d7]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::run_frame_internal::he8cb896a61d96162]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::run_frame_avm1::h4f543e565d34280c]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h2000682d298368c3]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h820d06e21ce20de4]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha6dba4b7bc395bcc]@[wasm code]
wasm-stub@[native code]
E@https://h-flash.com/data/ruffle/core.ruffle.77b76ff8ebf10abc4963.js:1:3044
f@https://h-flash.com/data/ruffle/core.ruffle.77b76ff8ebf10abc4963.js:1:2496
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://h-flash.com/aisha-clanclan-hentai-flash/
SWF URL: https://h-flash.com/data/swf/2014/03/aisha-clanclan-hentai-flash.swf

# Browser Info
User Agent: Mozilla/5.0 (iPad; CPU OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/111.0.5563.101 Mobile/15E148 Safari/604.1
Platform: iPad
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-12
Channel: nightly
Built: 2023-03-12T00:19:04.440Z
Commit: 1deebc87e869387c962f97b665d26785d0a2b52f
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 30
numFrames: 3142
swfVersion: 6
backgroundColor: #4E4F54
isActionScript3: false
uncompressedLength: 6542124

**Comment by Lord-McSweeney** [comment] 2023-04-19 14:06
Duplicate of #10117, the issue has since been fixed.

**Closed by Lord-McSweeney** 2023-04-19 14:06 UTC
Labels: nsfw, error-report
