### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by WidowCurioZero** [ruffle-rs/ruffle#7109] opened 2022-05-29 14:14 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.4eb0604eba48fe4cbd7c.js:1:7024)
    at std::sync::once::Once::call_once::{{closure}}::hfcef47ecdbff91ce (https://uploads.ungrounded.net/ruffle_wrapper/lib/533d00859b2aae889211.wasm:wasm-function[1207]:0x2b2c48)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://uploads.ungrounded.net/ruffle_wrapper/lib/533d00859b2aae889211.wasm:wasm-function[1413]:0x2ec791)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb9fff54a76be75f (https://uploads.ungrounded.net/ruffle_wrapper/lib/533d00859b2aae889211.wasm:wasm-function[4754]:0x43bb43)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://uploads.ungrounded.net/ruffle_wrapper/lib/533d00859b2aae889211.wasm:wasm-function[3189]:0x3e27ef)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://uploads.ungrounded.net/ruffle_wrapper/lib/533d00859b2aae889211.wasm:wasm-function[4937]:0x441a1d)
    at core::panicking::panic::hc28e7cc2aa792341 (https://uploads.ungrounded.net/ruffle_wrapper/lib/533d00859b2aae889211.wasm:wasm-function[4846]:0x43db58)
    at core::ops::function::FnOnce::call_once::hd48b4ba212e63ff9 (https://uploads.ungrounded.net/ruffle_wrapper/lib/533d00859b2aae889211.wasm:wasm-function[1053]:0x28bfdf)
    at ruffle_core::avm1::function::Executable::exec::heb2985dc6453fec6 (https://uploads.ungrounded.net/ruffle_wrapper/lib/533d00859b2aae889211.wasm:wasm-function[360]:0xd05cd)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h2542da9dd7871d71 (https://uploads.ungrounded.net/ruffle_wrapper/lib/533d00859b2aae889211.wasm:wasm-function[545]:0x199c6f)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1653065402%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2222268804.331e931bf739268ac76520f4a03bc6590db7bb43ae2905%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2262937fb13afe3%22%2C%22NewgroundsAPI_SessionID%22%3A%22w25mj6Qv5AGrqFQU9xENcf694a1f0b45068f61f9c410e902959e90de7a55U3Fi%22%2C%22NewgroundsAPI_UserName%22%3A%22HelpThe%22%2C%22NewgroundsAPI_UserID%22%3A9381008%2C%22ng_username%22%3A%22HelpThe%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14588.123.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.72 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-20
Channel: nightly
Built: 2022-05-20T00:13:55.393Z
Commit: c503f78e13d9a595be0e315b18ce27267cdf94fc
Is extension: false

**Comment by relrelb** [comment] 2022-07-13 06:19
Duplicate of #3756.

**Closed by relrelb** 2022-07-13 06:19 UTC
Labels: error-report
