### ISSUE TITLE
Error on https://game253127.konggames.com/games/BerzerkStudio/zombidle/frame/974e7f24-cf39-4ace-9a8d-70ee53a13c66/

### ISSUE THREAD

**Issue by RemyWillowRoussel** [ruffle-rs/ruffle#16110] opened 2024-04-24 12:14 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f77055/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f77055/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
    at J.n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.22214d8f93677f6269cd.js:1:73847)
    at js_sys::Error::new::hdd220ef72a1ea21f (wasm://wasm/03a9687a:wasm-function[13935]:0xb31b9c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0b0ddc27f3250923 (wasm://wasm/03a9687a:wasm-function[11527]:0xadb90e)
    at std::panicking::rust_panic_with_hook::h9aabd906218897c3 (wasm://wasm/03a9687a:wasm-function[7110]:0x9a3a37)
    at core::panicking::panic_fmt::h3aff855fe938c13f (wasm://wasm/03a9687a:wasm-function[11243]:0xad53d2)
    at core::option::expect_failed::h236a0500ffc66273 (wasm://wasm/03a9687a:wasm-function[9821]:0xa7a7db)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h267cbcbc90d607c4 (wasm://wasm/03a9687a:wasm-function[776]:0x118592)
    at ruffle_core::avm2::globals::flash::utils::byte_array::read_object::hb07864c2bf17f808 (wasm://wasm/03a9687a:wasm-function[1234]:0x3d5492)
    at ruffle_core::avm2::function::Executable::exec::h3eafd8018957ba4e (wasm://wasm/03a9687a:wasm-function[1033]:0x2fb5f4)
    at ruffle_core::avm2::object::TObject::call_property::h0593119735fc65f7 (wasm://wasm/03a9687a:wasm-function[1514]:0x4969da)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at com.berzerkstudio::ModelFla/loadFromByteArray()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadNextFla()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadBunch()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadAllFlas()
    at com.zombidle::MainGameWebStarling/loadModelFlas()
    at com.zombidle::MainGameWebStarling/loadZipFile()
    at Function/apply()
    at com.lachhh.io::Callback/call()
    at com.lachhhStarling::StarlingMain$/startGame()
    at MethodInfo-5838()
    at starling.utils::AssetManager/loadQueue()
    at com.lachhhStarling::StarlingMain$/loadAssetsDesktop()
    at MethodInfo-5836()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1921()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 530 (0x0000191B) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://game253127.konggames.com/games/BerzerkStudio/zombidle/frame/974e7f24-cf39-4ace-9a8d-70ee53a13c66/?kongregate_host=www.kongregate.com
SWF URL: https://game253127.konggames.com/gamez/0025/3127/live/ZI_FGL.swf?kongregate_game_version=1570126011

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-04-24
Channel: nightly
Built: 2024-04-24T00:06:53.855Z
Commit: f30c04e8b4d77bae221b2cfc3ce03faf1f06eeb2
Is extension: false

# Metadata
width: 960
height: 640
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 64218669

**Comment by n0samu** [comment] 2024-07-14 04:47
Duplicate of #10174

**Closed by n0samu** 2024-07-14 04:47 UTC
Labels: duplicate, avm2, error-report, amf
