### ISSUE TITLE
Once again: avm1: .swf file does not save to .sol file........

### ISSUE THREAD

**Issue by Ghost-Program** [ruffle-rs/ruffle#18188] opened 2024-10-05 18:29 UTC
### Describe the bug

https://github.com/ruffle-rs/ruffle/issues/16115

### Expected behavior

https://github.com/ruffle-rs/ruffle/issues/16115

### Content Location

https://github.com/ruffle-rs/ruffle/issues/16115

### Affected platform

Self-hosted version

### Operating system

windows 10 or above

### Browser

latest chrome

**Comment by adrian17** [comment] 2024-10-05 20:55
Duplicate of https://github.com/ruffle-rs/ruffle/issues/16115 .

**Closed by adrian17** 2024-10-05 20:55 UTC
Labels: bug
