### ISSUE TITLE
Error on https://prestigegames777.weebly.com/electric-man-2.html

### ISSUE THREAD

**Issue by Nightmare089** [ruffle-rs/ruffle#6122] opened 2022-01-24 17:31 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://prestigegames777.weebly.com/files/theme/Ruffle/ruffle.js:1:7158)
    at std::sync::once::Once::call_once::{{closure}}::hd1b4f64c6a058fdf (https://prestigegames777.weebly.com/files/theme/Ruffle/88fc5bf74ae9135144e7.wasm:wasm-function[984]:0x2f60fa)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://prestigegames777.weebly.com/files/theme/Ruffle/88fc5bf74ae9135144e7.wasm:wasm-function[1187]:0x33e03d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7c91d9e8737f5a50 (https://prestigegames777.weebly.com/files/theme/Ruffle/88fc5bf74ae9135144e7.wasm:wasm-function[4703]:0x505c75)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://prestigegames777.weebly.com/files/theme/Ruffle/88fc5bf74ae9135144e7.wasm:wasm-function[3238]:0x4aea41)
    at rust_begin_unwind (https://prestigegames777.weebly.com/files/theme/Ruffle/88fc5bf74ae9135144e7.wasm:wasm-function[4767]:0x5071de)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://prestigegames777.weebly.com/files/theme/Ruffle/88fc5bf74ae9135144e7.wasm:wasm-function[4980]:0x512197)
    at core::panicking::panic::hec1fc057bd0baf0b (https://prestigegames777.weebly.com/files/theme/Ruffle/88fc5bf74ae9135144e7.wasm:wasm-function[4700]:0x5054db)
    at core::ops::function::FnOnce::call_once::h83f26a94bb6d39f3 (https://prestigegames777.weebly.com/files/theme/Ruffle/88fc5bf74ae9135144e7.wasm:wasm-function[1041]:0x314750)
    at ruffle_core::avm1::function::Executable::exec::h00e69fc62e0063bd (https://prestigegames777.weebly.com/files/theme/Ruffle/88fc5bf74ae9135144e7.wasm:wasm-function[434]:0x162415)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://prestigegames777.weebly.com/electric-man-2.html
SWF URL: https://prestigegames777.weebly.com/uploads/1/1/2/6/112633177/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS aarch64 14150.87.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.124 Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-10
Channel: nightly
Built: 2022-01-10T00:14:34.425Z
Commit: b79144c122990c10fd15a53bb2afde650ab139b7
Is extension: false

**Comment by Poopooracoocoo** [comment] 2022-01-24 18:18
Duplicate of #4932

**Closed by Poopooracoocoo** 2022-01-24 18:18 UTC
Labels: duplicate, error-report
