### ISSUE TITLE
Error on https://www.azdressup.com/fantasy-dress-up/best-dressed-holiday-couple.html

### ISSUE THREAD

**Issue by Rarity057** [ruffle-rs/ruffle#6795] opened 2022-04-23 21:47 UTC
# Error Info
Error name: Error
Error message: R��cked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.17.10/src/fill.rs:1942:74
Error stack:
```
@https://www.azdressup.com/css/ruffle.js:1:7182
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::ha2a6e9c1727c0056]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h02a6489b0ecfb269]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h5c1b8acd952e19de]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h364974e717ed59ec]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hf69c8b08bc9d2ee5]@[wasm code]
<?>.wasm-function[core::panicking::panic::hceae0c79b0247f98]@[wasm code]
<?>.wasm-function[core::slice::sort::shift_tail::h06d8fb322e05a13f]@[wasm code]
<?>.wasm-function[core::slice::sort::recurse::h62ef53cef67647f0]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::process_events::h8c6e72bab723bdff]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_impl::h4144057b3fbc5f9d]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_path::hcf33913141137885]@[wasm code]
<?>.wasm-function[ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h4a49cf94641b67f6]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::hd996a481ac2384f4]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h0c217b14cd08a2c1]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::heb7a6a44dffc56e5]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h40b5fa60195af0b1]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha320ba57067ea0cb]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he6cd5fcab5567cc9]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h7205236d067cc311]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hd152dc341c383afa]@[wasm code]
wasm-stub@[native code]
F@https://www.azdressup.com/css/ruffle.js:1:4011
a@https://www.azdressup.com/css/ruffle.js:1:2536
promiseReactionJob@[native code]
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.azdressup.com/fantasy-dress-up/best-dressed-holiday-couple.html
SWF URL: https://www.azdressup.com/media/1512/sweet_holiday_couple.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-21
Channel: nightly
Built: 2021-11-21T00:13:29.381Z
Commit: a305b80789234133cd666e1c9f1abcde247818cb
Is extension: false

**Comment by n0samu** [comment] 2024-06-23 23:36
Likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:36 UTC
Labels: error-report
