### ISSUE TITLE
Error on https://blogofsex.com/files/games.php

### ISSUE THREAD

**Issue by Inseantiel** [ruffle-rs/ruffle#9646] opened 2023-02-19 22:16 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:629:28
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:629:28
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://blogofsex.com/files/ruffle/core.ruffle.1482fba686d796606d22.js:1:5412)
    at std::sync::once::Once::call_once::{{closure}}::hb0a1d9ef34c32d8b (wasm://wasm/027e079e:wasm-function[1901]:0x487127)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/027e079e:wasm-function[1839]:0x476f0d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7ac2449e123715e3 (wasm://wasm/027e079e:wasm-function[7164]:0x76cca4)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/027e079e:wasm-function[5081]:0x6c8d3e)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/027e079e:wasm-function[7480]:0x77bba2)
    at core::panicking::panic::h27b5eefa3e4ff738 (wasm://wasm/027e079e:wasm-function[6860]:0x747bcb)
    at ruffle_core::display_object::container::ChildContainer::replace_at_depth::h753e679bdfaea519 (wasm://wasm/027e079e:wasm-function[1602]:0x41715e)
    at ruffle_core::display_object::container::TDisplayObjectContainer::replace_at_depth::h68099f75302da9af (wasm://wasm/027e079e:wasm-function[4755]:0x6acbaa)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hffdc1c2e9c6c6b60 (wasm://wasm/027e079e:wasm-function[717]:0x23c871)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://blogofsex.com/files/games.php?swf=rope-bondage-rebirth.swf
SWF URL: https://blogofsex.com/files/games/rope-bondage-rebirth.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; CPH2179) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36
Platform: Linux armv8l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-11
Channel: nightly
Built: 2023-02-11T00:18:56.442Z
Commit: a2cd3ee06edcb889e8adc70a221eabb80ad342e5
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 2628780

**Comment by Lord-McSweeney** [comment] 2023-02-20 21:36
Duplicate of #9554.

**Closed by Lord-McSweeney** 2023-02-20 21:36 UTC
Labels: nsfw, error-report
