### ISSUE TITLE
Error on https://www.gameflare.com/embed/jacksmith/

### ISSUE THREAD

**Issue by Ahylinet** [ruffle-rs/ruffle#14122] opened 2023-11-23 04:46 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096


    at N.n.wbg.__wbg_new_ab87fd305ed9004b (https://www.gameflare.com/emulators/ruffle/core.ruffle.2bed241913628c449d76.js:1:58763)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h878d7563074f0d48 (<anonymous>:wasm-function[9824]:0x9fe16a)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (<anonymous>:wasm-function[6351]:0x8dcbd1)
    at core::panicking::panic_fmt::h7a368385936888dc (<anonymous>:wasm-function[9636]:0x9f9066)
    at core::ops::function::Fn::call::h17b686c150d53841 (<anonymous>:wasm-function[6326]:0x8db5d5)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::hb300bc584d49798d (<anonymous>:wasm-function[5034]:0x83a6f4)
    at wgpu::backend::direct::Context::handle_error::hc685e116ef8cc2a5 (<anonymous>:wasm-function[2297]:0x622922)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h709030e560456ed1 (<anonymous>:wasm-function[9096]:0x9c358a)
    at wgpu::CommandEncoder::copy_texture_to_buffer::he2ad44f5cab26c99 (<anonymous>:wasm-function[8584]:0x99b37b)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h2f2d8dfd19728753 (<anonymous>:wasm-function[1780]:0x541059)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mali-G52 MC2"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 16383, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; arm_64; Android 13; RMX3430) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 YaBrowser/20.11.1.100.00 SA/3 Mobile Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-21
Channel: nightly
Built: 2023-11-21T00:14:48.522Z
Commit: 1ce772befae148f2f6260dcb82e7a224e3d09d6b
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by evilpie** [comment] 2024-04-09 15:05
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:05 UTC
Labels: error-report
