### ISSUE TITLE
Error on https://archive.org/details/flash_bigwave

### ISSUE THREAD

**Issue by Bubu** [ruffle-rs/ruffle#1598] opened 2020-11-19 23:19 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\gc_cell.rs:54:21
Error stack:
```
Y@https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.a8f0d0fd0a0f0ab41246.js:1:20278
__wbg_new_df6e6ab7a65c4c4d@https://cors.archive.org/cors/emularity_engine_v1/ruffle.js:1:31106
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1208]:0x227539
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1363]:0x242e78
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3581]:0x2eccfd
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2807]:0x2cf748
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3878]:0x2f1969
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3906]:0x2f1e53
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3781]:0x2f04e6
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3908]:0x2f1eb7
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3308]:0x2e62e3
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2014]:0x29485a
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1641]:0x26b6ac
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1313]:0x23a77c
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1203]:0x2267b9
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1280]:0x234a7c
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3035]:0x2db925
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2837]:0x2d10fd
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1329]:0x23d433
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[350]:0xd6b0e
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[635]:0x188549
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1475]:0x25458e
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[899]:0x1e0b51
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3151]:0x2e0b86
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[761]:0x1b6dd6
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3808]:0x2f0ab8
@https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[4068]:0x2f3a0c
k@https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.a8f0d0fd0a0f0ab41246.js:1:18423
f@https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.a8f0d0fd0a0f0ab41246.js:1:17378

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/flash_bigwave

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
OS: Linux x86_64

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by Toad06** [comment] 2020-11-20 10:20
The issue was related to text fields (see bug report #1580 and commit #1602).
I'm going to close this as the issue is now fixed in current master (hopefully archive.org will update their builds!).

Thanks for reporting!

**Closed by Toad06** 2020-11-20 10:20 UTC
