### ISSUE TITLE
Error on https://flasharch.com/en/archive/play/aab6e08b9317818fc89491db9fcaa102

### ISSUE THREAD

**Issue by Pre-dictablNinja** [ruffle-rs/ruffle#5649] opened 2021-11-12 15:33 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://cdn.flasharch.com/js/ruffle/2021-11-07/ruffle.js:1:7036)
    at std::sync::once::Once::call_once::{{closure}}::h5387044f596cf17b (wasm://wasm/018b815a:wasm-function[1003]:0x2f5687)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (wasm://wasm/018b815a:wasm-function[1322]:0x363092)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h4461033b8c8249d8 (wasm://wasm/018b815a:wasm-function[4587]:0x4ebe27)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (wasm://wasm/018b815a:wasm-function[3245]:0x4a7005)
    at rust_begin_unwind (wasm://wasm/018b815a:wasm-function[4647]:0x4ee093)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (wasm://wasm/018b815a:wasm-function[4844]:0x4f8ac2)
    at core::panicking::panic::hceae0c79b0247f98 (wasm://wasm/018b815a:wasm-function[4583]:0x4eb658)
    at core::ops::function::FnOnce::call_once::hf99a08a7a8d58165 (wasm://wasm/018b815a:wasm-function[1045]:0x310c9e)
    at ruffle_core::avm1::function::Executable::exec::hc98df77004cccb4f (wasm://wasm/018b815a:wasm-function[425]:0x168b95)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://flasharch.com/en/archive/play/aab6e08b9317818fc89491db9fcaa102
SWF URL: https://cdn.flasharch.com/uploads/archived/2020/12/23/b9cfeda65484def38dee6dceeac0bde4_20201223013134.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14150.74.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-07
Channel: nightly
Built: 2021-11-07T00:14:35.663Z
Commit: 9308513ae884345128506f68731ade9890f4e3ec
Is extension: false

**Comment by n0samu** [comment] 2023-04-14 01:42
Duplicate of #4932

**Closed by n0samu** 2023-04-14 01:42 UTC
Labels: duplicate, error-report
