### ISSUE TITLE
Error on https://www.gameflare.com/embed/jacksmith/

### ISSUE THREAD

**Issue by enxshi69** [ruffle-rs/ruffle#10477] opened 2023-03-31 12:31 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    not enough memory left

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.15.1/src/backend/direct.rs:3024:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    not enough memory left

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.15.1/src/backend/direct.rs:3024:5
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://www.gameflare.com/emulators/ruffle/core.ruffle.19a71c44e6349610d35b.js:1:47895)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb025c08ea6ea4a5 (wasm://wasm/02ac91b6:wasm-function[8130]:0x801cff)
    at std::panicking::rust_panic_with_hook::hc53aea0352e77326 (wasm://wasm/02ac91b6:wasm-function[5419]:0x735c1b)
    at core::panicking::panic_fmt::hf4a9df75710ece83 (wasm://wasm/02ac91b6:wasm-function[8014]:0x7fcf3e)
    at core::ops::function::Fn::call::h327d0f48f5b775ec (wasm://wasm/02ac91b6:wasm-function[5675]:0x746fc0)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h9bd6927ceaaace68 (wasm://wasm/02ac91b6:wasm-function[4234]:0x6cd9c3)
    at <T as wgpu::context::DynContext>::device_create_buffer::ha89dcec6a69c2165 (wasm://wasm/02ac91b6:wasm-function[6173]:0x772699)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h83d0ee6b2975fb84 (wasm://wasm/02ac91b6:wasm-function[1354]:0x3e6fb4)
    at ruffle_render_wgpu::surface::target::CommandTarget::new::hb011fd5b7456c598 (wasm://wasm/02ac91b6:wasm-function[671]:0x229400)
    at ruffle_render_wgpu::surface::Surface::draw_commands::h1d2a73b7fc6bf72f (wasm://wasm/02ac91b6:wasm-function[635]:0x1fd4ab)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at swordGame.models::Soldier/spriteSheetBlit()
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.35
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-31
Channel: nightly
Built: 2023-03-31T00:21:30.510Z
Commit: ad2e60adcc0eadd6927143fb97d3e6bf5e52f5d7
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by Dinnerbone** [comment] 2024-07-12 22:00
Duplicate of #10432

**Closed by Dinnerbone** 2024-07-12 22:00 UTC
Labels: duplicate, render-wgpu, error-report
