### ISSUE TITLE
In the Motorcross FMX, the player is tied without the wheel.

### ISSUE THREAD

**Issue by jooy0224** [ruffle-rs/ruffle#4120] opened 2021-04-25 12:10 UTC
**Describe the bug**
![fmx](https://user-images.githubusercontent.com/75052171/115992703-ffb68400-a609-11eb-8069-83760a7e32c1.gif)
(It is explained in the attached gif at the top.)

If you press the up arrow key after the game starts, only the wheel moves, and the player and the screen are stuck, so the game cannot be played.

[Motorcross FMX.zip](https://github.com/ruffle-rs/ruffle/files/6371879/Motorcross.FMX.zip)

**Expected behavior**
The motorcycle should be able to move forward.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Checked in self-hosted version.

**What platform are you using?**
 - Windows 10 20H1 x64
 - Google Chrome (latest)
 - Ruffle Nightly 2021-04-25

**Comment by relrelb** [comment] 2021-04-25 17:03
Duplicate of #3314.

**Closed by relrelb** 2021-04-25 17:03 UTC
Labels: bug
