### ISSUE TITLE
Error on https://shsgames.github.io/g/6f2e0289/electric-man-2

### ISSUE THREAD

**Issue by NoDripJud** [ruffle-rs/ruffle#6509] opened 2022-03-22 20:08 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.88cd1234f57f1c8b9bd5.js:1:7441)
    at std::sync::once::Once::call_once::{{closure}}::hd22b02eba3e9e551 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.21/cefa048afff4fe14624e.wasm:wasm-function[1026]:0x2c36ab)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.21/cefa048afff4fe14624e.wasm:wasm-function[1454]:0x3300d6)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdfc5065ab5dd32a2 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.21/cefa048afff4fe14624e.wasm:wasm-function[4906]:0x47fa70)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.21/cefa048afff4fe14624e.wasm:wasm-function[3230]:0x423a22)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.21/cefa048afff4fe14624e.wasm:wasm-function[5194]:0x48beee)
    at core::panicking::panic::h5d6906e2c1099660 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.21/cefa048afff4fe14624e.wasm:wasm-function[4903]:0x47f597)
    at core::ops::function::FnOnce::call_once::h806223057a5cffd8 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.21/cefa048afff4fe14624e.wasm:wasm-function[1110]:0x2d9114)
    at ruffle_core::avm1::function::Executable::exec::hffc9f2817cba146d (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.21/cefa048afff4fe14624e.wasm:wasm-function[392]:0x11de1b)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h8f91ddac7dedb596 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.3.21/cefa048afff4fe14624e.wasm:wasm-function[432]:0x157a42)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://shsgames.github.io/g/6f2e0289/electric-man-2
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14268.67.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.111 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-21
Channel: nightly
Built: 2022-03-21T00:15:09.351Z
Commit: b7a60384cfbd8e81b5d4126ca3c3894a1954bb2e
Is extension: false

**Comment by relrelb** [comment] 2022-03-22 20:33
Duplicate of #4932.

**Closed by relrelb** 2022-03-22 20:33 UTC
Labels: error-report
