### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by kdean4227** [ruffle-rs/ruffle#7401] opened 2022-07-12 05:13 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:831:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:831:18
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.fa6f70bf774b5debbe61.js:1:6065)
    at std::sync::once::Once::call_once::{{closure}}::h0555ef98a007fd4c (https://uploads.ungrounded.net/ruffle_wrapper/lib/7d199d7a4979f610d722.wasm:wasm-function[1200]:0x2afd6a)
    at std::sync::once::Once::call_inner::hecc7c66a7de7e98e (https://uploads.ungrounded.net/ruffle_wrapper/lib/7d199d7a4979f610d722.wasm:wasm-function[1381]:0x2e7fad)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h41cceef5ab38a800 (https://uploads.ungrounded.net/ruffle_wrapper/lib/7d199d7a4979f610d722.wasm:wasm-function[4684]:0x4260b0)
    at std::panicking::rust_panic_with_hook::h8888bbc201384d7b (https://uploads.ungrounded.net/ruffle_wrapper/lib/7d199d7a4979f610d722.wasm:wasm-function[3082]:0x3d85a3)
    at core::panicking::panic_fmt::h18b15be283411c65 (https://uploads.ungrounded.net/ruffle_wrapper/lib/7d199d7a4979f610d722.wasm:wasm-function[4868]:0x42c28c)
    at core::panicking::panic::h0207b244811fef8b (https://uploads.ungrounded.net/ruffle_wrapper/lib/7d199d7a4979f610d722.wasm:wasm-function[4778]:0x428143)
    at core::ops::function::FnOnce::call_once::hc7e4d379c1ab3b19 (https://uploads.ungrounded.net/ruffle_wrapper/lib/7d199d7a4979f610d722.wasm:wasm-function[1026]:0x280b56)
    at ruffle_core::avm1::function::Executable::exec::hd79e3f5a9c034f04 (https://uploads.ungrounded.net/ruffle_wrapper/lib/7d199d7a4979f610d722.wasm:wasm-function[382]:0xf9242)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hb8f38d428cfcc2d7 (https://uploads.ungrounded.net/ruffle_wrapper/lib/7d199d7a4979f610d722.wasm:wasm-function[802]:0x221be4)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1656941607%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2284345818.2c2b1eb53fcc26d41afc6eca5ff66ada93fd8306856dcc%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2262ccf6f09ebfe%22%2C%22NewgroundsAPI_SessionID%22%3A%22rw027rIW6GYJQVqC648v30e9397401ee763d5e0816976a6dfe02c1d73d3bOGma%22%2C%22NewgroundsAPI_UserName%22%3A%22Cuddly132%22%2C%22NewgroundsAPI_UserID%22%3A8518544%2C%22ng_username%22%3A%22Cuddly132%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-04
Channel: nightly
Built: 2022-07-04T00:18:13.302Z
Commit: 49e8f4e939c6b0e388a707c33c48ea397be72109
Is extension: false

**Comment by relrelb** [comment] 2022-07-13 06:20
Duplicate of #3756.

**Closed by relrelb** 2022-07-13 06:20 UTC
Labels: error-report
