### ISSUE TITLE
Error on https://game116780.konggames.com/games/AdultSwimGames/cardboard-box-assembler/frame/9d155e69-fece-4612-b0e6-5c58e11dace2/

### ISSUE THREAD

**Issue by CalvinRansom** [ruffle-rs/ruffle#12367] opened 2023-07-28 07:34 UTC
# Error Info
Error name: Error
Error message: panicked at 'Reference still held to rc', /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:260:18
Error stack:
```
Error: panicked at 'Reference still held to rc', /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:260:18
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.7d5ca800cec09bb6160b.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0e63761b8083e365 (wasm://wasm/02fa320e:wasm-function[9185]:0x8ea5cb)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02fa320e:wasm-function[6046]:0x7fa4e9)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02fa320e:wasm-function[9029]:0x8e5fb3)
    at core::option::expect_failed::hd65acbc4e2342087 (wasm://wasm/02fa320e:wasm-function[7946]:0x8a6679)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::hab09309a6c038400 (wasm://wasm/02fa320e:wasm-function[559]:0x108f20)
    at <F as nom::internal::Parser<I,O,E>>::parse::ha6d1675991eeb271 (wasm://wasm/02fa320e:wasm-function[3794]:0x6d60e5)
    at flash_lso::read::Reader::parse::h1fd871fb5a5e6f6c (wasm://wasm/02fa320e:wasm-function[4281]:0x71dd8b)
    at ruffle_core::avm2::globals::flash::net::shared_object::get_local::h62e41f329e3d2b05 (wasm://wasm/02fa320e:wasm-function[557]:0x10244f)
    at ruffle_core::avm2::function::Executable::exec::hb539235b671154fd (wasm://wasm/02fa320e:wasm-function[833]:0x2c0342)
```
AVM2 stack:
```
    at flash.net::SharedObject/flash::net::SharedObject::getLocal()
    at Scribe()
    at Scribe$/getInstance()
    at SoundManager()
    at SoundManager$/getInstance()
    at Main/init()
    at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
    at Preloader/startup()
    at Preloader/checkFrame()
```

# Player Info
Allows script access: true
Renderer: WebGL 1.0
Adapter Vendor: WebKit
Adapter Renderer: WebKit WebGL
Adapter Version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Surface samples: 1 x 
Surface size: 300 x 150

# Page Info
Page URL: https://game116780.konggames.com/games/AdultSwimGames/cardboard-box-assembler/frame/9d155e69-fece-4612-b0e6-5c58e11dace2/?kongregate_host=www.kongregate.com
SWF URL: https://game116780.konggames.com/gamez/0011/6780/live/Cube_unlocked.swf?kongregate_game_version=1308933216

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-28
Channel: nightly
Built: 2023-07-28T00:19:35.903Z
Commit: 46d6d6724dc38a658cd9760b2e6ba799bd2028d9
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 12513965

**Comment by n0samu** [comment] 2023-07-28 07:45
Duplicate of #11911

**Closed by n0samu** 2023-07-28 07:45 UTC
Labels: duplicate, error-report
