### ISSUE TITLE
Error on https://www.officegamespot.com/freegames/electric-man-2.htm

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#5850] opened 2021-12-12 17:38 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://djmhpcephgmoapenkdjopfcnpijlobon/dist/ruffle.js?id=80498051668:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h8b88e6aa08fbb40d (chrome-extension://djmhpcephgmoapenkdjopfcnpijlobon/dist/81c96daa48c0c6086c8a.wasm:wasm-function[1024]:0x3221de)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (chrome-extension://djmhpcephgmoapenkdjopfcnpijlobon/dist/81c96daa48c0c6086c8a.wasm:wasm-function[1239]:0x3694de)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3ab0488d22755852 (chrome-extension://djmhpcephgmoapenkdjopfcnpijlobon/dist/81c96daa48c0c6086c8a.wasm:wasm-function[4741]:0x529c17)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (chrome-extension://djmhpcephgmoapenkdjopfcnpijlobon/dist/81c96daa48c0c6086c8a.wasm:wasm-function[3349]:0x4e394f)
    at rust_begin_unwind (chrome-extension://djmhpcephgmoapenkdjopfcnpijlobon/dist/81c96daa48c0c6086c8a.wasm:wasm-function[4804]:0x52b338)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (chrome-extension://djmhpcephgmoapenkdjopfcnpijlobon/dist/81c96daa48c0c6086c8a.wasm:wasm-function[5015]:0x535f4f)
    at core::panicking::panic::hec1fc057bd0baf0b (chrome-extension://djmhpcephgmoapenkdjopfcnpijlobon/dist/81c96daa48c0c6086c8a.wasm:wasm-function[4738]:0x52947d)
    at core::ops::function::FnOnce::call_once::hf2847eaac0d0b0dc (chrome-extension://djmhpcephgmoapenkdjopfcnpijlobon/dist/81c96daa48c0c6086c8a.wasm:wasm-function[1097]:0x341650)
    at ruffle_core::avm1::function::Executable::exec::hd3e79afc52b5b7a9 (chrome-extension://djmhpcephgmoapenkdjopfcnpijlobon/dist/81c96daa48c0c6086c8a.wasm:wasm-function[411]:0x16a5d3)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.officegamespot.com/freegames/electric-man-2.htm
SWF URL: https://www.officegamespot.com/freewebgames/electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-11
Channel: nightly
Built: 2021-12-11T00:11:36.855Z
Commit: e5617de4aae711c1b612a246e972d198f6c86124
Is extension: true

**Comment by relrelb** [comment] 2021-12-12 18:04
Duplicate of #4932.

**Closed by relrelb** 2021-12-12 18:04 UTC
