### ISSUE TITLE
Error on http://www.ferryhalim.com/orisinal/ Firefox extension Orion browser iOS

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#15313] opened 2024-02-25 03:57 UTC
# Error Info
Error name: TypeError
Error message: Load failed

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.ferryhalim.com/orisinal/

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-13
Channel: nightly
Built: 2024-01-13T00:14:58.057Z
Commit: 2775c917bf61254dbddf67b604d36157efdff7d5
Is extension: true

# Metadata

**Comment by Dinnerbone** [comment] 2024-07-12 22:02
Duplicate of #15312

**Closed by Dinnerbone** 2024-07-12 22:02 UTC
Labels: duplicate, error-report
