### ISSUE TITLE
Error on https://www.numuki.com/gameframe/ben-to-the-rescue

### ISSUE THREAD

**Issue by Robbie941** [ruffle-rs/ruffle#14670] opened 2024-01-09 02:40 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/display_object/container.rs:968:22:
called `Option::unwrap()` on a `None` value
Error stack:
```
339/__wbg_get_imports/imports.wbg.__wbg_new_a64e3f2afc2cf2f8@moz-extension://add13597-1f52-4b9d-8133-8f8517ed9b0c/dist/339.js:2624:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::hdcdf3f6ca94f57c3@:wasm-function[10649]:0x9f0ed5
std::panicking::rust_panic_with_hook::h62090d3fc0630473@:wasm-function[6529]:0x8dd645
core::panicking::panic_fmt::hd79411a297d06dc8@:wasm-function[10372]:0x9eac1f
core::panicking::panic::hd37d8d0a98259c88@:wasm-function[9942]:0x9d16e8
core::ops::function::FnOnce::call_once::hbc673e96a93fb4fd@:wasm-function[985]:0x354447
ruffle_core::avm1::function::Executable::exec::hbe0387bec68f66e1@:wasm-function[718]:0x204723
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::ha34915036ea3c0d4@:wasm-function[6998]:0x8fe03b
ruffle_core::avm1::activation::Activation::do_action::h73335a9f95593844@:wasm-function[1106]:0x3ad159
ruffle_core::avm1::function::Executable::exec::hbe0387bec68f66e1@:wasm-function[718]:0x204521
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::ha34915036ea3c0d4@:wasm-function[6998]:0x8fe703
ruffle_core::avm1::activation::Activation::do_action::h73335a9f95593844@:wasm-function[1106]:0x3ad159
ruffle_core::avm1::function::Executable::exec::hbe0387bec68f66e1@:wasm-function[718]:0x204521
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::ha4ee332c19256d13@:wasm-function[5003]:0x85073e
ruffle_core::avm1::activation::Activation::do_action::h73335a9f95593844@:wasm-function[1106]:0x3acbb2
ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h79714ffa2cbdb669@:wasm-function[1074]:0x396abc
ruffle_core::player::Player::run_actions::hfd24b2ad6dbad10b@:wasm-function[882]:0x2f62db
ruffle_web::Ruffle::tick::h692806f0bbbeafe3@:wasm-function[852]:0x2c633a
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h220898de7b14c659@:wasm-function[12833]:0xa3fbdd
wasm_bindgen::convert::closures::invoke1_mut::h6449723b924a2b41@:wasm-function[11579]:0xa0c191
__wbg_adapter_66@moz-extension://add13597-1f52-4b9d-8133-8f8517ed9b0c/dist/339.js:294:10
real@moz-extension://add13597-1f52-4b9d-8133-8f8517ed9b0c/dist/339.js:271:20

```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: best
Surface samples: 4
Surface size: Extent3d { width: 947, height: 631, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.numuki.com/gameframe/ben-to-the-rescue
SWF URL: https://media.numuki.com/ben-10/games/ben-to-the-rescue/preload.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-30
Channel: nightly
Built: 2023-12-30T00:15:06.603Z
Commit: 583327ff6255913bdc48ae93fb78d58016c8f763
Is extension: true

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 43
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 63469

**Comment by n0samu** [comment] 2024-01-21 10:22
Duplicate of #12698

**Closed by n0samu** 2024-01-21 10:22 UTC
Labels: duplicate, error-report
