### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Miguelvideogame** [ruffle-rs/ruffle#4328] opened 2021-05-14 17:17 UTC
# Error Info
Error name: TypeError
Error message: Could not download wasm module
Error stack:
```
TypeError: Could not download wasm module
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1620839880%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F573000%2F573102_Untitled_1.swf%3F1308861822%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22609eb09f0d00b%22%2C%22NewgroundsAPI_SessionID%22%3A%22s41A1oRYEmNord90Haif0b244258622e9b2c38db7e6b5e8316cdf85641d7Or3w%22%2C%22NewgroundsAPI_UserName%22%3A%22MiguelvideogameYT%22%2C%22NewgroundsAPI_UserID%22%3A8893954%2C%22ng_username%22%3A%22MiguelvideogameYT%22%7D%2C%22width%22%3A550%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F573000%2Fflash_573102_card.png%3Ff1610416932%22%7D

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-12
Channel: nightly
Built: 2021-05-12T00:13:11.225Z
Commit: ea4ea9922a031b49ac4cc9a593389f64b0042c9c

**Comment by torokati44** [comment] 2021-06-09 01:02
Duplicate of #4250.

**Closed by torokati44** 2021-06-09 01:02 UTC
