### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm

### ISSUE THREAD

**Issue by rbalajee** [ruffle-rs/ruffle#5960] opened 2022-01-01 13:35 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::hd7ead8121c6a35d0 (http://www.freeworldgroup.com/ruffle/638d9593afa19c0b9372.wasm:wasm-function[984]:0x3064c7)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (http://www.freeworldgroup.com/ruffle/638d9593afa19c0b9372.wasm:wasm-function[1182]:0x349de4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he4d4296fb40dce2d (http://www.freeworldgroup.com/ruffle/638d9593afa19c0b9372.wasm:wasm-function[4698]:0x4fbb2b)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (http://www.freeworldgroup.com/ruffle/638d9593afa19c0b9372.wasm:wasm-function[3230]:0x4a893d)
    at rust_begin_unwind (http://www.freeworldgroup.com/ruffle/638d9593afa19c0b9372.wasm:wasm-function[4763]:0x4fd0e5)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (http://www.freeworldgroup.com/ruffle/638d9593afa19c0b9372.wasm:wasm-function[4979]:0x508084)
    at core::panicking::panic::hec1fc057bd0baf0b (http://www.freeworldgroup.com/ruffle/638d9593afa19c0b9372.wasm:wasm-function[4695]:0x4fb391)
    at core::ops::function::FnOnce::call_once::hcd326c02f608ded7 (http://www.freeworldgroup.com/ruffle/638d9593afa19c0b9372.wasm:wasm-function[1032]:0x318088)
    at ruffle_core::avm1::function::Executable::exec::h9f4e212fa4aaf0ee (http://www.freeworldgroup.com/ruffle/638d9593afa19c0b9372.wasm:wasm-function[431]:0x181c93)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm
SWF URL: http://www.freeworldgroup.com/games6/electricman2/electricman2hs_fwg.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-01
Channel: nightly
Built: 2022-01-01T00:13:36.533Z
Commit: e477fca9e40295ff550d7709d17afa769d4c461e
Is extension: false

**Comment by Poopooracoocoo** [comment] 2022-01-01 14:03
Duplicate of #4932

**Closed by Poopooracoocoo** 2022-01-01 14:03 UTC
Labels: duplicate, error-report
