### ISSUE TITLE
When you click on URL inside the flash, it will open the site, but any other click in the flash now only opens a new tab with the site.

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2476] opened 2021-01-13 20:45 UTC
http://eye.swfchan.com/flash.asp?id=116124&n=cartoon-house-online-coloring-game.swf

Nightly 2021-01-13
Chrome 87.0.4280.141
Does not repro on Desktop, didn't test other browsers

Everything as I wrote in the title, basically. 
![image](https://user-images.githubusercontent.com/75184268/104508424-40f5cb80-55f9-11eb-9a2e-375bc0fd4662.png)

If you happen to click on URL 123PEPPY (accessible at the top right when you press PLAY), it will lead to the website, but any other mouse interaction with the flash is now constantly firing up this "go to website" thing (opening countless new browser tabs), rendering the flash unusable.

**Comment by Herschel** [comment] 2021-01-13 20:47
Duplicate of #2353

**Closed by Herschel** 2021-01-13 20:47 UTC
