### ISSUE TITLE
Firefox add-ons page is unavailable

### ISSUE THREAD

**Issue by WinLinux1028** [ruffle-rs/ruffle#9054] opened 2023-01-07 04:40 UTC
### Describe the bug

[The official site](https://ruffle.rs/) has [a link to Firefox add-ons](https://addons.mozilla.org/firefox/addon/ruffle_rs), but the linked page has disappeared.
![image](https://user-images.githubusercontent.com/68107676/211131218-fd3b9a47-2883-4950-bb33-d656bce39c1f.png)

### Expected behavior

It should be possible to install Ruffle from the Firefox add-ons page again.

### Affected platform

Browser's extension

### Operating system

All operating system

### Browser

Mozilla Firefox

**Comment by Lord-McSweeney** [comment] 2023-01-07 05:22
Mozilla's extension reviewers have been unable to build Ruffle from source, so they removed it from add-ons.

**Comment by n0samu** [comment] 2023-01-07 06:28
Please see my comment: https://github.com/ruffle-rs/ruffle/issues/8799#issuecomment-1374391215
We are working to resolve the situation as quickly as possible.

**Comment by divinity76** [comment] 2023-01-08 11:12
btw looks like someone else put an ancient (2021) version of Ruffle on addons.mozilla.org

Warning: I have no reason to trust this developer, i have no idea if it's malware-free, and i have no idea who this developer ("[ModernKit.one](https://addons.mozilla.org/en-US/firefox/user/16604800/)") is

https://addons.mozilla.org/en-US/firefox/addon/flash-player-emulator/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by torokati44** [comment] 2023-01-08 17:06
I wonder if @mozilla subjects this (and other) "shady looking" Ruffle-ish extension(s) to the same scrutiny during review as they have done to our "official" one, multiple times now... :)

**Comment by n0samu** [comment] 2023-01-09 04:46
@divinity76 That is the company that is deceptively charging users for features that Ruffle already has implemented: `https://modernkit.one/flash-emulator/upgrade/`

So yeah, I'm not a fan! What a bad situation 😦

**Comment by ousia** [comment] 2023-01-13 13:57
I wonder whether this issue may be considered a duplicate of #8799 (as per https://github.com/ruffle-rs/ruffle/issues/8799#issuecomment-1368047327)).

If it isn’t, I don’t mind closing my report.

Many thanks for your help and for the awesome work.

**Comment by n0samu** [comment] 2023-01-14 07:59
Let's keep both issues open for now.

**Comment by ousia** [comment] 2023-01-15 21:09
Fine for me.

**Comment by n0samu** [comment] 2023-02-20 23:50
See https://github.com/ruffle-rs/ruffle/issues/8799#issuecomment-1437674625 as well for updated information on the situation

**Closed** 2023-02-23 16:33 UTC
Labels: firefox

**Comment by n0samu** [comment] 2023-02-24 01:15
Mozilla has approved our new build! 🎉
