### ISSUE TITLE
Error on https://f.kbhgames.com/RS/game.php

### ISSUE THREAD

**Issue by bulbekk** [ruffle-rs/ruffle#8609] opened 2022-11-24 02:54 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/array.rs:61:10
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/array.rs:61:10
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.5c3b38c9836d2d0d4a78.js:1:6899)
    at std::sync::once::Once::call_once::{{closure}}::h6dceed65b46ff778 (wasm://wasm/01868cf2:wasm-function[1057]:0x29f964)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/01868cf2:wasm-function[1351]:0x306795)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5488990682f4686e (wasm://wasm/01868cf2:wasm-function[4917]:0x498ea2)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/01868cf2:wasm-function[3662]:0x4597b5)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/01868cf2:wasm-function[5151]:0x49daba)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/01868cf2:wasm-function[4971]:0x499dc8)
    at <ruffle_core::avm2::object::array_object::ArrayObject as ruffle_core::avm2::object::TObject>::set_property_local::h220cfaad5ff4795f (wasm://wasm/01868cf2:wasm-function[1316]:0x2fde47)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::h02f16337589bd1cf (wasm://wasm/01868cf2:wasm-function[696]:0x206859)
    at ruffle_core::avm2::activation::Activation::run_actions::h31e1cc954784f5cb (wasm://wasm/01868cf2:wasm-function[303]:0x14e96)
```
AVM2 stack:
```
    at scaryama.transitions::FlashingBtn/onChange()
    at flash.events::EventDispatcher/dispatchEvent()
    at fl.transitions::Tween/setPosition()
    at fl.transitions::Tween/update()
    at fl.transitions::Tween/set time()
    at fl.transitions::Tween/nextFrame()
    at fl.transitions::Tween/onEnterFrame()
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://f.kbhgames.com/RS/game.php?r=//f.kbhgames.com/2015/03/can-your-pet.swf&w=640&h=480
SWF URL: https://f.kbhgames.com/2015/03/can-your-pet.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-24
Channel: nightly
Built: 2022-11-24T00:18:37.581Z
Commit: c10244b0a4a0f0d03df82eecdd8a354d052aa76f
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 45
numFrames: 1734
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 1867130

**Comment by n0samu** [comment] 2022-11-24 06:35
Duplicate of #7865

**Closed by n0samu** 2022-11-24 06:35 UTC
Labels: duplicate, avm2, error-report
