### ISSUE TITLE
Error on https://www.decoral3ab.com/game24.html

### ISSUE THREAD

**Issue by Za22ki** [ruffle-rs/ruffle#6437] opened 2022-03-11 09:44 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.decoral3ab.com/ruffle/ruffle.js:1:6799)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (wasm://wasm/0124c3ea:wasm-function[1327]:0x26ba91)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (wasm://wasm/0124c3ea:wasm-function[1604]:0x29efac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (wasm://wasm/0124c3ea:wasm-function[4639]:0x382410)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (wasm://wasm/0124c3ea:wasm-function[3509]:0x357ce4)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (wasm://wasm/0124c3ea:wasm-function[4146]:0x37597c)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (wasm://wasm/0124c3ea:wasm-function[4985]:0x387ae1)
    at rust_begin_unwind (wasm://wasm/0124c3ea:wasm-function[4870]:0x3863de)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (wasm://wasm/0124c3ea:wasm-function[4986]:0x387b17)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (wasm://wasm/0124c3ea:wasm-function[4244]:0x378a55)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.decoral3ab.com/game24.html
SWF URL: https://www.decoral3ab.com/files/file/1316972540.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-16
Channel: nightly
Built: 2021-02-16T00:17:10.309Z
Commit: 85069f6ccf3fbbe88de6d40094aa9e9dba616e2a

**Comment by Dinnerbone** [comment] 2024-07-12 22:09
Duplicate of #6226

**Closed by Dinnerbone** 2024-07-12 22:09 UTC
Labels: duplicate, error-report
