### ISSUE TITLE
Error on https://extrememath.me/swf.html

### ISSUE THREAD

**Issue by imarandomdude** [ruffle-rs/ruffle#8516] opened 2022-11-10 15:23 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:810:33
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:810:33
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.4c033d4c3be5515ab021.js:1:6432)
    at std::sync::once::Once::call_once::{{closure}}::hade171d180e8c1b3 (wasm://wasm/01847da2:wasm-function[837]:0x25df96)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/01847da2:wasm-function[1354]:0x311f20)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b5ff8f72074c3e7 (wasm://wasm/01847da2:wasm-function[4883]:0x497c2d)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/01847da2:wasm-function[3622]:0x4584a2)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/01847da2:wasm-function[5106]:0x49c5b3)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/01847da2:wasm-function[4935]:0x498ad7)
    at core::ops::function::FnOnce::call_once::h30d1d284d5fd9535 (wasm://wasm/01847da2:wasm-function[1249]:0x2f4ed4)
    at ruffle_core::avm1::function::Executable::exec::h21369c76f086a0ad (wasm://wasm/01847da2:wasm-function[355]:0xdd2c1)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::he8552b5e405132ad (wasm://wasm/01847da2:wasm-function[679]:0x215c07)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://extrememath.me/swf.html?notebook=electricman2
SWF URL: https://extrememath.me/swffiles/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-09
Channel: nightly
Built: 2022-11-09T00:16:25.978Z
Commit: f31f52f2daf2a26805f9994df63d293fb4a309aa
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3641749

**Comment by n0samu** [comment] 2022-11-10 20:43
Duplicate of #4932

**Closed by n0samu** 2022-11-10 20:43 UTC
Labels: duplicate, error-report
