### ISSUE TITLE
Ruffle Desktop cannot display the translation text when the System Display Language is not latin

### ISSUE THREAD

**Issue by lvyitian** [ruffle-rs/ruffle#11763] opened 2023-06-27 11:11 UTC
### Describe the bug

Steps to reproduce:
  1.Set the System Display Language to be any non-latin language
  2.Launch the ruffle desktop
Ruffle Desktop cannot display the translation text when the System Display Language is not latin.

### Expected behavior

The translation text should be displayed properly

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment] 2023-06-28 02:41
Are you sure it is an encoding issue? As far as we know, the problem is just that the font we're using doesn't support CJK characters or Arabic. See #11370

**Comment by lvyitian** [comment] 2023-06-28 04:39
> Are you sure it is an encoding issue? As far as we know, the problem is just that the font we're using doesn't support CJK characters or Arabic. See #11370

I'm not sure, it is possible to be a font issue.

**Comment by n0samu** [comment] 2023-07-07 09:57
Fixed by #11924

**Closed by n0samu** 2023-07-07 09:57 UTC
Labels: bug, desktop, localization
