### ISSUE TITLE
Ruffle has encountered a fatal error, this is a bug

### ISSUE THREAD

**Issue by CR4ZYDANI** [ruffle-rs/ruffle#18864] opened 2024-12-05 03:40 UTC
### Describe what you were doing

I just opened the app

### What does the crash message say?

panicked at desktop\src\app.rs:466:14:
GUI controller should be created: Parent device is lost

### Ruffle Version

0.1.0-nightly (44ebce3b18ea0a747331ac7748e8038a030df1a2 2024-12-04)

### Affected platform

Desktop app

### Operating system

Windows 10.0.19045 (Windows 10 Pro) [64-bit]

**Comment by evilpie** [comment] 2024-12-08 14:17
Duplicate of #18690

**Closed by evilpie** 2024-12-08 14:17 UTC
Labels: bug, panic, render-wgpu, windows
