### ISSUE TITLE
Error on https://es.y8.com/games/feed_me_moar

### ISSUE THREAD

**Issue by ghost** [ruffle-rs/ruffle#14978] opened 2024-01-28 01:22 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    Copy of X 4294967293..521 would end up overrunning the bounds of the Destination texture of X size 720

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    Copy of X 4294967293..521 would end up overrunning the bounds of the Destination texture of X size 720


    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:3476:21)
    at js_sys::Error::new::h728118aa18eebd18 (wasm://wasm/03870bbe:wasm-function[13689]:0xae237f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hfc928092015e7dff (wasm://wasm/03870bbe:wasm-function[11310]:0xa8ca65)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/03870bbe:wasm-function[6930]:0x94b092)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/03870bbe:wasm-function[11032]:0xa861dc)
    at core::ops::function::Fn::call::h15de8e8c05bfa63c (wasm://wasm/03870bbe:wasm-function[7228]:0x961e3b)
    at wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::h2f49cf1f9462116e (wasm://wasm/03870bbe:wasm-function[5749]:0x8dea31)
    at wgpu::backend::wgpu_core::ContextWgpuCore::handle_error::h48d36bf764025f8c (wasm://wasm/03870bbe:wasm-function[3103]:0x6eb9c5)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_texture::hd8417f6c1589feb9 (wasm://wasm/03870bbe:wasm-function[10281]:0xa53ad0)
    at wgpu::CommandEncoder::copy_texture_to_texture::ha6e4ab0fc734bcf7 (wasm://wasm/03870bbe:wasm-function[9591]:0xa2c438)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::applyFilter()
    at game.display.render::WaterRenderer/renderWater()
    at game.display.render::WaterRenderer/render()
    at engine::Screen/update()
    at engine.level::Level/update()
    at engine.level::GameLevel/update()
    at Main/update()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00009BC8) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://es.y8.com/games/feed_me_moar
SWF URL: https://img.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/44365/original/feed_me_moar.swf?1521552365

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-28
Channel: nightly
Built: 2024-01-28T00:16:24.409Z
Commit: fcb74d8fbc735f3c1f481738adec15d52d186c5e
Is extension: true

# Metadata
width: 700
height: 525
frameRate: 30
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 7429962

**Comment by n0samu** [comment] 2024-07-21 04:42
Duplicate of #14027

**Closed by n0samu** 2024-07-21 04:42 UTC
Labels: duplicate, error-report
