### ISSUE TITLE
Error on http://www.stickpage.com/electricman2gameplay.shtml

### ISSUE THREAD

**Issue by MxLunger** [ruffle-rs/ruffle#7038] opened 2022-05-20 21:20 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7022)
    at std::sync::once::Once::call_once::{{closure}}::hfcef47ecdbff91ce (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/533d00859b2aae889211.wasm:wasm-function[1207]:0x2b2c48)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/533d00859b2aae889211.wasm:wasm-function[1413]:0x2ec791)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb9fff54a76be75f (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/533d00859b2aae889211.wasm:wasm-function[4754]:0x43bb43)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/533d00859b2aae889211.wasm:wasm-function[3189]:0x3e27ef)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/533d00859b2aae889211.wasm:wasm-function[4937]:0x441a1d)
    at core::panicking::panic::hc28e7cc2aa792341 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/533d00859b2aae889211.wasm:wasm-function[4846]:0x43db58)
    at core::ops::function::FnOnce::call_once::hd48b4ba212e63ff9 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/533d00859b2aae889211.wasm:wasm-function[1053]:0x28be55)
    at ruffle_core::avm1::function::Executable::exec::heb2985dc6453fec6 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/533d00859b2aae889211.wasm:wasm-function[360]:0xd05cd)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h2542da9dd7871d71 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/533d00859b2aae889211.wasm:wasm-function[545]:0x199c6f)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: http://farm.stickpage.com/electricman2game.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: http://www.stickpage.com/electricman2gameplay.shtml
SWF URL: http://farm.stickpage.com/electricman2game.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS aarch64 13982.88.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.162 Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-20
Channel: nightly
Built: 2022-05-20T00:13:55.393Z
Commit: c503f78e13d9a595be0e315b18ce27267cdf94fc
Is extension: true

**Comment by n0samu** [comment] 2022-05-21 01:58
Duplicate of #4932.

**Closed by n0samu** 2022-05-21 01:58 UTC
Labels: duplicate, error-report
