### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by ginmatthew** [ruffle-rs/ruffle#9826] opened 2023-03-03 07:19 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:317:9
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:317:9
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2154:21)
    at std::sync::once::Once::call_once::{{closure}}::hf612d11c59f969d6 (wasm://wasm/028bd7fe:wasm-function[2008]:0x4d33e0)
    at std::sys_common::once::generic::Once::call::h6b012ac601cc39bf (wasm://wasm/028bd7fe:wasm-function[1940]:0x4c1c3c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haab85c1ab4107c96 (wasm://wasm/028bd7fe:wasm-function[7373]:0x798522)
    at std::panicking::rust_panic_with_hook::hbafe3e603d331223 (wasm://wasm/028bd7fe:wasm-function[5224]:0x6f0f86)
    at core::panicking::panic_fmt::h1d17fc068f528130 (wasm://wasm/028bd7fe:wasm-function[7692]:0x7a74fd)
    at core::panicking::panic::h27b5eefa3e4ff738 (wasm://wasm/028bd7fe:wasm-function[7092]:0x7741ba)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::hc57a77f2751817cf (wasm://wasm/028bd7fe:wasm-function[597]:0x1cec42)
    at ruffle_core::loader::Loader::preload_tick::h4459d8164e57e13f (wasm://wasm/028bd7fe:wasm-function[809]:0x2b3b65)
    at ruffle_web::Ruffle::tick::h46f99567ad695fa5 (wasm://wasm/028bd7fe:wasm-function[671]:0x237c66)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=&sp=0&questionSet=&r=125369&width=640&height=500&quality=high
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-03
Channel: nightly
Built: 2023-03-03T02:02:06.432Z
Commit: 5944bae33bbabab0f8a660d9fa82a84b2db56456
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by n0samu** [comment] 2023-04-22 07:37
Closing as duplicate of #9972

**Closed by n0samu** 2023-04-22 07:37 UTC
Labels: error-report
