### ISSUE TITLE
Error on https://h-flash.com/touch-the-girl/

### ISSUE THREAD

**Issue by qwiwee** [ruffle-rs/ruffle#11311] opened 2023-05-31 08:43 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:640:18
Error stack:
```
@https://h-flash.com/data/ruffle/core.ruffle.77b76ff8ebf10abc4963.js:1:48787
wasm-stub@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h321a9078ff9936f2]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h2a7f454a5f5da218]@[wasm code]
<?>.wasm-function[core::panicking::panic::ha3ebcac1438d9280]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::container::ChildContainer::replace_at_depth::h2de1d6a0c6867e00]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::container::TDisplayObjectContainer::replace_at_depth::h21501d2f3172dfbe]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h195a33510c0b747d]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::place_object::ha18b2972f2fca4d7]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::run_frame_internal::he8cb896a61d96162]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::run_frame_avm1::h4f543e565d34280c]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h2000682d298368c3]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h820d06e21ce20de4]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha6dba4b7bc395bcc]@[wasm code]
wasm-stub@[native code]
E@https://h-flash.com/data/ruffle/core.ruffle.77b76ff8ebf10abc4963.js:1:3044
f@https://h-flash.com/data/ruffle/core.ruffle.77b76ff8ebf10abc4963.js:1:2496
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://h-flash.com/touch-the-girl/
SWF URL: https://h-flash.com/data/swf/2020/04/touchthegirl_sv.swf

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/113.0.5672.69 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-12
Channel: nightly
Built: 2023-03-12T00:19:04.440Z
Commit: 1deebc87e869387c962f97b665d26785d0a2b52f
Is extension: false

# Metadata
width: 960
height: 600
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 2192454

**Comment by Lord-McSweeney** [comment] 2023-07-19 07:24
Duplicate of #11262.

**Closed by Lord-McSweeney** 2023-07-19 07:24 UTC
Labels: nsfw, error-report
