### ISSUE TITLE
Error on https://www.gameflare.com/embed/jacksmith/

### ISSUE THREAD

**Issue by StaleDragon** [ruffle-rs/ruffle#13499] opened 2023-10-10 15:41 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096


    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://www.gameflare.com/emulators/ruffle/core.ruffle.4f64c86b2b458fb5d643.js:1:51724)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h73a0ca99bc054b64 (wasm://wasm/0323790e:wasm-function[9651]:0x9772c7)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0323790e:wasm-function[6313]:0x87bef6)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0323790e:wasm-function[9458]:0x972224)
    at core::ops::function::Fn::call::h837acff4934dfd42 (wasm://wasm/0323790e:wasm-function[6493]:0x88715b)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::he437fba1dc018ced (wasm://wasm/0323790e:wasm-function[5229]:0x81f697)
    at wgpu::backend::direct::Context::handle_error::hb1a578a698e03e88 (wasm://wasm/0323790e:wasm-function[2645]:0x64b7fa)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::hdbdb8ed1ed0df88a (wasm://wasm/0323790e:wasm-function[8963]:0x94e3f1)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h222d6df2a928ae8b (wasm://wasm/0323790e:wasm-function[8420]:0x92e810)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::he944eba81cc7111d (wasm://wasm/0323790e:wasm-function[1847]:0x54c97f)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.models::LobbySoldier/swapToSprite()
    at swordGame.models::LobbySoldier/walkCustomer()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-10
Channel: nightly
Built: 2023-10-10T00:27:25.054Z
Commit: 7254cdeef9f9fadf86ffeaddb2735de99cf8fb3d
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by evilpie** [comment] 2024-04-09 15:07
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:07 UTC
Labels: render-wgpu, error-report
