### ISSUE TITLE
Ruffle Error on https://www.jogosde2.com.br/jogo/yuyu-hakusho-wars.html

### ISSUE THREAD

**Issue by THUNDERCATS124** [ruffle-rs/ruffle#3805] opened 2021-03-26 15:13 UTC
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.jogosde2.com.br/jogo/yuyu-hakusho-wars.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by Poopooracoocoo** [comment] 2021-03-27 07:16
This is a problem with how Ruffle was configured on Jogosde2 and not with Ruffle. Please report this to them. Duplicate of #3624

**Closed by Poopooracoocoo** 2021-03-27 07:16 UTC
