### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by CarinhaDaskinha** [ruffle-rs/ruffle#4524] opened 2021-06-06 17:37 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1622838566:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (https://uploads.ungrounded.net/ruffle_wrapper/lib/63a08affdc2e50c039c6.wasm:wasm-function[1093]:0x2871c6)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (https://uploads.ungrounded.net/ruffle_wrapper/lib/63a08affdc2e50c039c6.wasm:wasm-function[963]:0x261601)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (https://uploads.ungrounded.net/ruffle_wrapper/lib/63a08affdc2e50c039c6.wasm:wasm-function[3852]:0x411d8c)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (https://uploads.ungrounded.net/ruffle_wrapper/lib/63a08affdc2e50c039c6.wasm:wasm-function[3000]:0x3b24a2)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/63a08affdc2e50c039c6.wasm:wasm-function[4058]:0x417646)
    at core::panicking::panic_fmt::hd44f353696296fec (https://uploads.ungrounded.net/ruffle_wrapper/lib/63a08affdc2e50c039c6.wasm:wasm-function[4206]:0x41def0)
    at core::option::expect_none_failed::hf7dab2706f1a5551 (https://uploads.ungrounded.net/ruffle_wrapper/lib/63a08affdc2e50c039c6.wasm:wasm-function[3436]:0x40008e)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb988528a147b88d8 (https://uploads.ungrounded.net/ruffle_wrapper/lib/63a08affdc2e50c039c6.wasm:wasm-function[584]:0x1a5818)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hec010d7c15f8344d (https://uploads.ungrounded.net/ruffle_wrapper/lib/63a08affdc2e50c039c6.wasm:wasm-function[548]:0x18862a)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1622838566%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2260bd069354873%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36 OPR/75.0.3969.279
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-04
Channel: nightly
Built: 2021-06-04T00:32:40.590Z
Commit: 4ec31dc073596cc2a2747442ae8bb244cc235337

**Comment by torokati44** [comment] 2021-06-15 15:42
Duplicate of #4142.

**Closed by torokati44** 2021-06-15 15:42 UTC
