### ISSUE TITLE
The flash game Flight's achievements and upgrades are broken

### ISSUE THREAD

**Issue by Esortsyt** [ruffle-rs/ruffle#14775] opened 2024-01-16 02:15 UTC
### Describe the bug

It is loading one image across all achievement, upgrades and the customize icon, and just cycling through images, as well as saying upgrades are maxed, even though I did not buy any upgrades. 
![Screenshot 2024-01-15 6 00 36 PM](https://github.com/ruffle-rs/ruffle/assets/155596413/6e2a86dd-e70e-4cfe-be69-cbef35dbff1d)
![Screenshot 2024-01-15 6 00 40 PM](https://github.com/ruffle-rs/ruffle/assets/155596413/b0734e2e-77aa-4c18-b8fe-9ff5357de07a)
![Screenshot 2024-01-15 6 00 44 PM](https://github.com/ruffle-rs/ruffle/assets/155596413/ef15dec0-9808-44fd-9610-69bad766099a)
Also for some reason, when the armor games logo loads, and then when game menu loads, it'll play the armor games logo sound, but it won't show the armor games logo.

### Expected behavior

Should load a seperate image for each upgrade and achievement, as well as not loading random paper airplane images that are green in the customize icon. It should also not play the armor games logo sound after the game menu and the armor games logo already loaded.

### Content Location

https://ooooooooo.ooo/static/?09f92f27-cacd-4d23-b8fa-5784ed89ed78

^ Link to the flashpoint archive for the flash game Flight.

### Affected platform

Self-hosted version

### Operating system

Chrome Os

### Browser

Google Chrome

**Comment by n0samu** [comment] 2024-01-16 02:18
Duplicate of #10443

**Closed by n0samu** 2024-01-16 02:18 UTC
Labels: bug, duplicate
