### ISSUE TITLE
Error on https://flashstorage.games/embed/mini-dash

### ISSUE THREAD

**Issue by tmsnnmnsp0** [ruffle-rs/ruffle#11854] opened 2023-07-02 16:06 UTC
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
    at U.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.f56267020d1df1980a84.js:1:51428)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hac2de81f3b71691d (wasm://wasm/02d0bae6:wasm-function[8753]:0x86097f)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02d0bae6:wasm-function[5685]:0x76cda2)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02d0bae6:wasm-function[8615]:0x85c4cc)
    at alloc::raw_vec::capacity_overflow::h3bb4537b5f9f8404 (wasm://wasm/02d0bae6:wasm-function[8362]:0x855a39)
    at alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h2b00834c0560633a (wasm://wasm/02d0bae6:wasm-function[5547]:0x764c8c)
    at ruffle_core::avm2::globals::flash::utils::byte_array::set_length::h89ebb52afd28ebd1 (wasm://wasm/02d0bae6:wasm-function[3436]:0x65b425)
    at ruffle_core::avm2::function::Executable::exec::hf1fec3766087f421 (wasm://wasm/02d0bae6:wasm-function[822]:0x29eff5)
    at ruffle_core::avm2::object::TObject::call_method::h36118d5d09c74604 (wasm://wasm/02d0bae6:wasm-function[1953]:0x4e7120)
    at ruffle_core::avm2::object::TObject::set_property::he338bd3bc7e79cd3 (wasm://wasm/02d0bae6:wasm-function[2170]:0x531f15)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::length()
    at global/F_avm2_casRamLength()
    at global/F___sys_mmap()
    at global/F_mmap()
    at global/F_pages_map()
    at global/F_base_pages_alloc()
    at global/F_base_alloc()
    at global/F_arenas_extend()
    at global/F_malloc_init()
    at global/F_malloc()
    at global/F__Znwj()
    at global/F__Z16CreateGameObjectv()
    at global/F_main()
    at global/F__start1()
    at com.adobe.flascc::CModule$/callI()
    at com.adobe.flascc::CModule$/start()
    at com.adobe.flascc::CModule$/startAsync()
    at com.adobe.flascc::Console/enterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://flashstorage.games/embed/mini-dash
SWF URL: https://flashstorage.games/public/storage/games/November2021/QD21VEcY10LnXC2ISIAK.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-02
Channel: nightly
Built: 2023-07-02T00:20:03.951Z
Commit: bd043c09c7a4526d569da2ec5ea22695366ba7dc
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 0.1171875
numFrames: 1
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 20666034

**Comment by Lord-McSweeney** [comment] 2023-07-02 16:11
Duplicate of #10851. Note that this one has a full stack trace thanks to a recently merged PR.

**Closed by Lord-McSweeney** 2023-07-02 16:11 UTC
Labels: error-report
