### ISSUE TITLE
Error on https://www.comdotgame.com/play/kasumi-rebirth

### ISSUE THREAD

**Issue by sebin90** [ruffle-rs/ruffle#10199] opened 2023-03-18 02:29 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:640:18
Error stack:
```
@https://echo.comdotgame.com/ruffle/core.ruffle.77b76ff8ebf10abc4963.js:1:48787
wasm-stub@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h321a9078ff9936f2]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h2a7f454a5f5da218]@[wasm code]
<?>.wasm-function[core::panicking::panic::ha3ebcac1438d9280]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::container::ChildContainer::replace_at_depth::h2de1d6a0c6867e00]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::container::TDisplayObjectContainer::replace_at_depth::h21501d2f3172dfbe]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h195a33510c0b747d]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::run_goto::{{closure}}::h7bf1329a46718fc5]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::run_goto::hff866e088751f047]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::goto_frame::h13f7ed5f8308127d]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::globals::movie_clip::goto_frame::ha03b3597855b7782]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once::h1fd9f65df876b81f]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h38c958325b439c56]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7abbd9838b46d90c]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h9017a8ee32124b3e]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h38c958325b439c56]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::h1b6e751028f92ff8]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h9017a8ee32124b3e]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h38c958325b439c56]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7abbd9838b46d90c]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h9017a8ee32124b3e]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h1339aa78b7577250]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::hd36ae2ead33b20c6]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h2000682d298368c3]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h820d06e21ce20de4]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha6dba4b7bc395bcc]@[wasm code]
wasm-stub@[native code]
E@https://echo.comdotgame.com/ruffle/core.ruffle.77b76ff8ebf10abc4963.js:1:3044
f@https://echo.comdotgame.com/ruffle/core.ruffle.77b76ff8ebf10abc4963.js:1:2496
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f7313836a835b6c3191ed00ca9751a1c.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Param base: https://echo.comdotgame.com/4x90xhl3k0/games/files/kasumi-rebirth/3.30/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/kasumi-rebirth
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/f7313836a835b6c3191ed00ca9751a1c.swf

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/605.1 NAVER(inapp; search; 1010; 11.20.5; 14PROMAX)
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-12
Channel: nightly
Built: 2023-03-12T00:19:04.440Z
Commit: 1deebc87e869387c962f97b665d26785d0a2b52f
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 1
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3848978

**Comment by SN902** [comment] 2023-03-18 02:33
This game already in issues, stop posting duplicates

**Comment by n0samu** [comment] 2023-03-18 02:43
Duplicate of #10196

**Closed by n0samu** 2023-03-18 02:43 UTC
Labels: duplicate, nsfw, error-report
