### ISSUE TITLE
Error on http://www.bcae1.com/switchingpowersupplydesign/switchingpowersupplytut01.htm

### ISSUE THREAD

**Issue by drozco** [ruffle-rs/ruffle#6764] opened 2022-04-20 23:36 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:500:50
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7706)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[1012]:0x2ab733)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[1445]:0x31f9ca)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[4923]:0x479c8d)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[3241]:0x41d211)
    at core::panicking::panic_fmt::h5118e89563022e7e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[5005]:0x47db66)
    at core::result::unwrap_failed::ha62420c192a556da (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[4126]:0x4619b5)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h7525177f5af04a07 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[743]:0x22c686)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h9af7f672b83e4ef6 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[1721]:0x35edd0)
    at ruffle_core::font::Font::from_swf_tag::ha5d8a25f1f758987 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/0490f64d07f61e79720f.wasm:wasm-function[679]:0x20e1e7)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.bcae1.com/switchingpowersupplydesign/switchingpowersupplytut01.htm
SWF URL: http://www.bcae1.com/switchingpowersupplydesign/6inchpowersupplyphoto02.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-20
Channel: nightly
Built: 2022-04-20T00:19:00.226Z
Commit: 7cbba5bc8ff38a9a422664fd6b595af39b6bffe7
Is extension: true

**Comment by Herschel** [comment] 2022-04-28 23:45
Dupe of #1905.

**Closed by Herschel** 2022-04-28 23:45 UTC
Labels: error-report
