### ISSUE TITLE
Error on https://play.cprewritten.net/

### ISSUE THREAD

**Issue by Ashes1700** [ruffle-rs/ruffle#4241] opened 2021-05-05 06:16 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:847:49
Error stack:
```
https://play.cprewritten.net/:1:6924
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hf7fd718057964857]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h9d91fa0fae16500f]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h91d2023e5afe1929]@[wasm code]
<?>.wasm-function[core::option::expect_none_failed::h203584ddbc785ca2]@[wasm code]
<?>.wasm-function[std::thread::local::LocalKey<T>::with::h6d81463357c6f29a]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h0aace2737a3393e1]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hef4f765648aac733]@[wasm code]
wasm-stub@[native code]
E@https://play.cprewritten.net/:1:3088
a@https://play.cprewritten.net/:1:2841
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://play.cprewritten.net/
SWF URL: https://play.cprewritten.net/assets/flash/global/games/boot.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-28
Channel: nightly
Built: 2021-03-28T00:41:48.808Z
Commit: 0063f40af9cd6dd39038d67880db1d996176c309

**Comment by Dinnerbone** [comment] 2024-07-12 22:09
Duplicate of #4086

**Closed by Dinnerbone** 2024-07-12 22:09 UTC
Labels: duplicate, error-report
