### ISSUE TITLE
: https://www.juegosarea.com/travesia-del-puente.html

### ISSUE THREAD

**Issue by NICOLASVASQUEZ464** [ruffle-rs/ruffle#3420] opened 2021-02-25 21:54 UTC
**Describe the bug**
Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
If this is an issue with a specific SWF file, please provide a link to the SWF file, or you can attach the SWF by zipping it and dragging it onto the issue box.
If this is a visual issue, please attach a screenshot of the problem.

**Expected behavior**

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 - If you're using the web version, please list the OS, browser, and mobile device (if applicable).

**Comment by Poopooracoocoo** [comment] 2021-03-01 05:03
Duplicate of #3419

**Closed** 2021-03-02 13:28 UTC
Labels: duplicate
