### ISSUE TITLE
Error on http://dme2vtxapp01:8095/vertex-ui/

### ISSUE THREAD

**Issue by mickpeflin** [ruffle-rs/ruffle#2896] opened 2021-01-26 23:05 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32083
    at r (<anonymous>:3:32573)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://dme2vtxapp01:8095/vertex-ui/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-26
Channel: nightly
Built: 2021-01-26T00:36:48.131Z
Commit: 7856cdd3d770e406ce546bf1745d8046d7b716f8

**Comment by Poopooracoocoo** [comment] 2021-01-27 09:24
Looks like that's being hosted locally? Are you using the extension or have you added Ruffle to your website?

Well I think it's a CSP error. I remember that it has something to do with `unsafe-eval`

**Comment by relrelb** [comment] 2021-01-28 14:45
Duplicate of #2201.

**Closed** 2021-02-12 23:51 UTC
