### ISSUE TITLE
Error on http://swordandsandals.top/swords-and-sandals-2/

### ISSUE THREAD

**Issue by V4D1MECHE** [ruffle-rs/ruffle#12950] opened 2023-08-25 20:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.0865d85c7c067dcfcad7.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h68328b569f1b749d (wasm://wasm/0302832e:wasm-function[9312]:0x9035a5)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/0302832e:wasm-function[6105]:0x80fa87)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/0302832e:wasm-function[9154]:0x8ff08e)
    at core::result::unwrap_failed::h73809cc05a786e48 (wasm://wasm/0302832e:wasm-function[7253]:0x86bb90)
    at <T as wgpu::context::DynContext>::device_create_texture::h9c53417b1ed2a6a6 (wasm://wasm/0302832e:wasm-function[6778]:0x843a4b)
    at wgpu::Device::create_texture::ha8f32fe3c5d3a516 (wasm://wasm/0302832e:wasm-function[5148]:0x7bc5d3)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h353b14d12529e743 (wasm://wasm/0302832e:wasm-function[4985]:0x7abd3d)
    at ruffle_core::display_object::render_base::h5f6a979c393b4408 (wasm://wasm/0302832e:wasm-function[559]:0x105011)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h80fd400b0accc193 (wasm://wasm/0302832e:wasm-function[6672]:0x837c7a)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://swordandsandals.top/swords-and-sandals-2/
SWF URL: http://swordandsandals.top/wp-content/uploads/swords-and-sandals-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 YaBrowser/23.7.3.824 Yowser/2.5 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-24
Channel: nightly
Built: 2023-08-24T00:20:48.719Z
Commit: 1b03ce9ae668ea2b40f03f24ad38af95d1e92e80
Is extension: false

# Metadata
width: 640
height: 420
frameRate: 30
numFrames: 277
swfVersion: 8
backgroundColor: #FFCC66
isActionScript3: false
uncompressedLength: 5282134

**Comment by evilpie** [comment] 2024-02-01 20:33
Duplicate of https://github.com/ruffle-rs/ruffle/issues/11852

**Closed by evilpie** 2024-02-01 20:33 UTC
Labels: error-report
