### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by OllieZone** [ruffle-rs/ruffle#6844] opened 2022-05-01 15:33 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: c(...).createBuffer is not a function
TypeError: c(...).createBuffer is not a function
    at https://www.rekoroyun.com/ruffle/ruffle.js:1:11293
    at https://www.rekoroyun.com/ruffle/ruffle.js:1:4505
    at web_sys::features::gen_AudioContext::AudioContext::create_buffer::h1a7fd6319c2814a0 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4668]:0x382c5f)
    at ruffle_web::audio::WebAudioBackend::decompress_to_audio_buffer::h0e7af818499bbf83 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[463]:0x135957)
    at <ruffle_web::audio::WebAudioBackend as ruffle_core::backend::audio::AudioBackend>::register_sound::hd5ebba0374eb6c4c (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[2505]:0x30e7a9)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::{{closure}}::h37d3b4f539142195 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[294]:0x4cbcd)
    at ruffle_core::tag_utils::decode_tags::h75a43b5657cb21e4 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[1349]:0x270550)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h4cc85c5e3f686d46 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[782]:0x1d708b)
    at ruffle_core::player::Player::set_root_movie::h0309232cb5b1f714 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[343]:0xbe14a)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4cc20cb8fd4fc63c (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[579]:0x17da12))', web/src/audio.rs:712:14
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: c(...).createBuffer is not a function
TypeError: c(...).createBuffer is not a function
    at https://www.rekoroyun.com/ruffle/ruffle.js:1:11293
    at https://www.rekoroyun.com/ruffle/ruffle.js:1:4505
    at web_sys::features::gen_AudioContext::AudioContext::create_buffer::h1a7fd6319c2814a0 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4668]:0x382c5f)
    at ruffle_web::audio::WebAudioBackend::decompress_to_audio_buffer::h0e7af818499bbf83 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[463]:0x135957)
    at <ruffle_web::audio::WebAudioBackend as ruffle_core::backend::audio::AudioBackend>::register_sound::hd5ebba0374eb6c4c (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[2505]:0x30e7a9)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::{{closure}}::h37d3b4f539142195 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[294]:0x4cbcd)
    at ruffle_core::tag_utils::decode_tags::h75a43b5657cb21e4 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[1349]:0x270550)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h4cc85c5e3f686d46 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[782]:0x1d708b)
    at ruffle_core::player::Player::set_root_movie::h0309232cb5b1f714 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[343]:0xbe14a)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4cc20cb8fd4fc63c (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[579]:0x17da12))', web/src/audio.rs:712:14
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.rekoroyun.com/ruffle/ruffle.js:1:6799)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[1327]:0x26ba91)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[1604]:0x29efac)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4639]:0x382410)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[3509]:0x357ce4)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4146]:0x37597c)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4985]:0x387ae1)
    at rust_begin_unwind (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4870]:0x3863de)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4986]:0x387b17)
    at core::option::expect_none_failed::hbea1e2e5b59d80cc (https://www.rekoroyun.com/ruffle/90797cff9fcf5439a21889280011890d.wasm:wasm-function[4244]:0x378a55)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.rekoroyun.com/embed/flash/?id=3061
SWF URL: https://www.rekoroyun.com/swf/3061.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-16
Channel: nightly
Built: 2021-02-16T00:17:10.309Z
Commit: 85069f6ccf3fbbe88de6d40094aa9e9dba616e2a

**Comment by Poopooracoocoo** [comment] 2022-05-02 01:15
Duplicate of #4426

**Closed by Poopooracoocoo** 2022-05-02 01:15 UTC
Labels: duplicate, error-report
