### ISSUE TITLE
Error on https://formulatemath.com/archive/gfiles/flash/

### ISSUE THREAD

**Issue by hehehehawhuhuhuhuu** [ruffle-rs/ruffle#6936] opened 2022-05-10 05:14 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://formulatemath.com/archive/gfiles/flash/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::hdee01963557c8b87 (wasm://wasm/0193ea52:wasm-function[994]:0x315539)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (wasm://wasm/0193ea52:wasm-function[1194]:0x3599f7)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e75ef83c7eceddf (wasm://wasm/0193ea52:wasm-function[4706]:0x50c075)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (wasm://wasm/0193ea52:wasm-function[3246]:0x4b5e2d)
    at rust_begin_unwind (wasm://wasm/0193ea52:wasm-function[4770]:0x50d7ca)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (wasm://wasm/0193ea52:wasm-function[4982]:0x518747)
    at core::panicking::panic::hec1fc057bd0baf0b (wasm://wasm/0193ea52:wasm-function[4703]:0x50b8db)
    at core::ops::function::FnOnce::call_once::hb83ea7c2d8824069 (wasm://wasm/0193ea52:wasm-function[1044]:0x3277c0)
    at ruffle_core::avm1::function::Executable::exec::h97e3cc64039ed9c3 (wasm://wasm/0193ea52:wasm-function[436]:0x1894ab)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://formulatemath.com/archive/gfiles/flash/?swf=electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14526.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.133 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-21
Channel: nightly
Built: 2021-12-21T00:14:34.280Z
Commit: ccef61d0764c66d2f034ea07273d218b0f98e529
Is extension: false

**Comment by relrelb** [comment] 2022-05-10 05:18
Duplicate of #4932.

**Closed by relrelb** 2022-05-10 05:18 UTC
