### ISSUE TITLE
Error on https://h-flash.com/sexually-instructing-my-corner-masturbating-student/

### ISSUE THREAD

**Issue by phattawan** [ruffle-rs/ruffle#9828] opened 2023-03-03 08:33 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/cmp.rs:860:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/cmp.rs:860:9
    at V.e.wbg.__wbg_new_f9bb493369a83c12 (https://h-flash.com/data/ruffle/core.ruffle.5fc5bc0046838bc074f7.js:1:6921)
    at std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9 (wasm://wasm/01969952:wasm-function[1029]:0x2b1a43)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/01969952:wasm-function[1460]:0x33fe9d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542 (wasm://wasm/01969952:wasm-function[5046]:0x4d3a67)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/01969952:wasm-function[3779]:0x48e07d)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/01969952:wasm-function[5290]:0x4dc85e)
    at core::panicking::panic::h0859aaac783261b2 (wasm://wasm/01969952:wasm-function[5101]:0x4d49d2)
    at ruffle_core::player::Player::update_drag::h04c63746577775cf (wasm://wasm/01969952:wasm-function[1462]:0x34081e)
    at ruffle_web::Ruffle::tick::hdcb4afd54d8a568d (wasm://wasm/01969952:wasm-function[592]:0x1e19bf)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h5b63cba1bdda8f36 (wasm://wasm/01969952:wasm-function[6149]:0x4f14f9)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://h-flash.com/sexually-instructing-my-corner-masturbating-student/
SWF URL: https://h-flash.com/data/swf/data/jsk-studio/kadoona/kado.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-21
Channel: nightly
Built: 2022-12-21T00:16:40.503Z
Commit: 5cf5c8d5e5d3b37a38cf133aa587b7f925612f21
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 175
swfVersion: 41
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 44449515

**Comment by n0samu** [comment] 2023-03-03 08:34
Duplicate of #8839. This problem has already been fixed by #9108. Please contact the website owner and ask them to update their copy of Ruffle.

**Closed by n0samu** 2023-03-03 08:34 UTC
Labels: duplicate, nsfw, error-report
