### ISSUE TITLE
Attached flash movie locks up, does not work

### ISSUE THREAD

**Issue by mmastrac** [ruffle-rs/ruffle#2565] opened 2021-01-15 23:24 UTC
I've been trying to emulate this driver's exam flash from https://www.alberta.ca/drivers-knowledge-test.aspx#toc-2, and I get a hard lockup in the browser when loading it.

This works when served via localhost and viewed with the Adobe Flash Player. I have been unable to find any additional debugging info that could be useful, but I'm happy to dig in.

[quiz.zip](https://github.com/ruffle-rs/ruffle/files/5823364/quiz.zip)

**Comment by mmastrac** [comment] 2021-01-15 23:29
I was able to get a stack trace of where it locked up by killing it in the browser:

```
Script terminated by timeout at:
memcpy@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4532]:0x36d7ac
ruffle_core::drawing::Drawing::set_line_style::h325a193b612932e9@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[1375]:0x277681
ruffle_core::html::layout::LayoutContext::fixup_line::h6cdd6cc994079799@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[359]:0xde5c4
ruffle_core::html::layout::LayoutContext::newline::ha537557abaa6d9a4@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[3669]:0x355917
ruffle_core::html::layout::LayoutBox::lower_from_text_spans::h570d098820d832df@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[397]:0x1077e1
ruffle_core::display_object::edit_text::EditText::relayout::h57a656ab3fcf384b@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[1134]:0x244553
ruffle_core::display_object::edit_text::EditText::set_html_text::hffbea7edaa9470cf@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[1622]:0x2a1a8c
core::ops::function::FnOnce::call_once::h50b94d90326fd0ec@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[1381]:0x278aa8
ruffle_core::avm1::function::Executable::exec::h16da53806ea17e80@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[354]:0xd825c
ruffle_core::avm1::object::script_object::ScriptObject::internal_set::h77d187a6e36597c1@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[374]:0xefdb1
<ruffle_core::avm1::object::stage_object::StageObject as ruffle_core::avm1::object::TObject>::set::h9d76a877391d556c@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[787]:0x1dd243
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::set::h428e6bb059f64bb8@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[405]:0x10e5cc
ruffle_core::avm1::activation::Activation::do_action::h31a2058fdb7759d4@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[286]:0x18f40
ruffle_core::avm1::function::Executable::exec::h16da53806ea17e80@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[354]:0xd8341
<ruffle_core::avm1::function::FunctionObject as ruffle_core::avm1::object::TObject>::construct_on_existing::hf57baa00b9993359@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[1058]:0x231890
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::construct_on_existing::hee8d18909855c9f0@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[2815]:0x3235fa
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::post_instantiation::hf0ce416440f0beb2@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[401]:0x10b1dd
core::ops::function::FnOnce::call_once::hc68cc9b0d010030b@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[605]:0x1915f8
ruffle_core::avm1::function::Executable::exec::h16da53806ea17e80@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[354]:0xd825c
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::hb6dc392c4692ec37@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[811]:0x1e5a95
ruffle_core::avm1::activation::Activation::do_action::h31a2058fdb7759d4@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[286]:0x1dc02
ruffle_core::avm1::Avm1::run_stack_frame_for_action::he0db1a8133946859@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[875]:0x1fb65f
ruffle_core::player::Player::run_actions::h58d4185ed2c6915d@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[417]:0x118c11
ruffle_core::player::Player::run_frame::h741e6b7553f34162@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[878]:0x1fc510
ruffle_core::player::Player::tick::h2208887c9434b769@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[3329]:0x343dc2
std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[762]:0x1d3d76
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::ha6ff201f499682f2@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4560]:0x36dddf
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h38b6df632eacf5a9@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4835]:0x370ef9
k@https://ruffle.rs/demo/662.index.js:1:19145
f@https://ruffle.rs/demo/662.index.js:1:18100
FrameRequestCallback*624/Le<@https://ruffle.rs/demo/662.index.js:1:23721
G/<@https://ruffle.rs/demo/662.index.js:1:19907
__wbg_requestAnimationFrame_ef0e2294dc8b1088@https://ruffle.rs/demo/index.js:1:55047
web_sys::features::gen_Window::Window::request_animation_frame::hf2499db7f0943867@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4298]:0x36954c
std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[762]:0x1d416d
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::ha6ff201f499682f2@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4560]:0x36dddf
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h38b6df632eacf5a9@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4835]:0x370ef9
k@https://ruffle.rs/demo/662.index.js:1:19145
f@https://ruffle.rs/demo/662.index.js:1:18100
FrameRequestCallback*624/Le<@https://ruffle.rs/demo/662.index.js:1:23721
G/<@https://ruffle.rs/demo/662.index.js:1:19907
__wbg_requestAnimationFrame_ef0e2294dc8b1088@https://ruffle.rs/demo/index.js:1:55047
web_sys::features::gen_Window::Window::request_animation_frame::hf2499db7f0943867@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4298]:0x36954c
std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[762]:0x1d416d
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::ha6ff201f499682f2@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4560]:0x36dddf
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h38b6df632eacf5a9@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4835]:0x370ef9
k@https://ruffle.rs/demo/662.index.js:1:19145
f@https://ruffle.rs/demo/662.index.js:1:18100
FrameRequestCallback*624/Le<@https://ruffle.rs/demo/662.index.js:1:23721
G/<@https://ruffle.rs/demo/662.index.js:1:19907
__wbg_requestAnimationFrame_ef0e2294dc8b1088@https://ruffle.rs/demo/index.js:1:55047
web_sys::features::gen_Window::Window::request_animation_frame::hf2499db7f0943867@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4298]:0x36954c
std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[762]:0x1d416d
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::ha6ff201f499682f2@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4560]:0x36dddf
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h38b6df632eacf5a9@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4835]:0x370ef9
k@https://ruffle.rs/demo/662.index.js:1:19145
f@https://ruffle.rs/demo/662.index.js:1:18100
FrameRequestCallback*624/Le<@https://ruffle.rs/demo/662.index.js:1:23721
G/<@https://ruffle.rs/demo/662.index.js:1:19907
__wbg_requestAnimationFrame_ef0e2294dc8b1088@https://ruffle.rs/demo/index.js:1:55047
web_sys::features::gen_Window::Window::request_animation_frame::hf2499db7f0943867@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4298]:0x36954c
std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[762]:0x1d416d
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::ha6ff201f499682f2@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4560]:0x36dddf
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h38b6df632eacf5a9@https://ruffle.rs/demo/4ee107bd02685b71c22f.module.wasm:wasm-function[4835]:0x370ef9
k@https://ruffle.rs/demo/662.index.js:1:19145
f@https://ruffle.rs/demo/662.index.js:1:18100
FrameRequestCallback*624/Le<@https://ruffle.rs/demo/662.index.js:1:23721
G/<@https://ruffle.rs/demo/662.index.js:1:19907
__wbg_requestAnimationFrame_ef0e2294dc8b1088@https://ruffle.rs/demo/index.js:1:55047
```

**Comment by Aaron1011** [comment] 2021-01-16 22:49
This is caused by ruffle going into an infinite loop here: https://github.com/ruffle-rs/ruffle/blob/326a5b621214cb1696937de5e009f1fea48d5199/core/src/html/layout.rs#L700-L721

`breakpoint` is always 0, causing us to never exit the loop.

**Comment by adrian17** [comment] 2021-05-17 22:11
The hang should be fixed by https://github.com/ruffle-rs/ruffle/pull/4339 .

**Closed by adrian17** 2021-05-17 22:11 UTC
