### ISSUE TITLE
Error on https://game253127.konggames.com/games/BerzerkStudio/zombidle/frame/9df1a1aa-7a5b-4a5c-a757-d9baefb6bfff/

### ISSUE THREAD

**Issue by stridernj** [ruffle-rs/ruffle#12724] opened 2023-08-13 02:57 UTC
# Error Info
Error name: Error
Error message: panicked at 'Unable to get Object', /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:418:14
Error stack:
```
Error: panicked at 'Unable to get Object', /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:418:14
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h47c86d7a777c7d0f (wasm://wasm/02fe37e6:wasm-function[9233]:0x8f67e0)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02fe37e6:wasm-function[6049]:0x7f67f0)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02fe37e6:wasm-function[9076]:0x8f219a)
    at core::option::expect_failed::h3af12667ecd4887c (wasm://wasm/02fe37e6:wasm-function[7977]:0x8b2132)
    at flash_lso::amf3::read::AMF3Decoder::parse_element_object::h8895eb828864d1ac (wasm://wasm/02fe37e6:wasm-function[654]:0x1cf992)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h99103e191fdd08e1 (wasm://wasm/02fe37e6:wasm-function[562]:0x10e078)
    at ruffle_core::avm2::globals::flash::utils::byte_array::read_object::hac15e0d2d9f3a6ad (wasm://wasm/02fe37e6:wasm-function[885]:0x2ef1fb)
    at ruffle_core::avm2::function::Executable::exec::hc58f8eeee04eddab (wasm://wasm/02fe37e6:wasm-function[828]:0x2b6e05)
    at ruffle_core::avm2::object::TObject::call_property::h3c95b73679a76cc5 (wasm://wasm/02fe37e6:wasm-function[1114]:0x384978)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at com.berzerkstudio::ModelFla/loadFromByteArray()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadNextFla()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadBunch()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadAllFlas()
    at com.zombidle::MainGameWebStarling/loadModelFlas()
    at com.zombidle::MainGameWebStarling/loadZipFile()
    at Function/apply()
    at com.lachhh.io::Callback/call()
    at com.lachhhStarling::StarlingMain$/startGame()
    at MethodInfo-5838()
    at starling.utils::AssetManager/loadQueue()
    at com.lachhhStarling::StarlingMain$/loadAssetsDesktop()
    at MethodInfo-5836()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1686()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 620 (KBL GT2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game253127.konggames.com/games/BerzerkStudio/zombidle/frame/9df1a1aa-7a5b-4a5c-a757-d9baefb6bfff/?kongregate_host=www.kongregate.com
SWF URL: https://game253127.konggames.com/gamez/0025/3127/live/ZI_FGL.swf?kongregate_game_version=1570126011

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-13
Channel: nightly
Built: 2023-08-13T00:23:15.804Z
Commit: 3117469e20eeb1a435e678268252a4545228c030
Is extension: true

# Metadata
width: 960
height: 640
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 64218669

**Comment by n0samu** [comment] 2023-08-19 22:50
Duplicate of #10174

**Closed by n0samu** 2023-08-19 22:50 UTC
Labels: duplicate, error-report
