### ISSUE TITLE
Error on https://www.comdotgame.com/play/toilet-2

### ISSUE THREAD

**Issue by koooaki** [ruffle-rs/ruffle#7248] opened 2022-06-18 00:59 UTC
# Error Info
Error name: Error
Error message: panicked at 'Bezier without endpoint', core/src/shape_utils.rs:213:36
Error stack:
```
@https://echo.comdotgame.com/ruffle/core.ruffle.864a59d108a0384ed0a5.js:1:7581
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h8cc59a0b8a1b03e2]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h51a70f81ef530383]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::haa76f48d1b3c2435]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h12b2f0179ff84c92]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hf0d93ec1ac504cf9]@[wasm code]
<?>.wasm-function[core::option::expect_failed::h5b7c632d416440e9]@[wasm code]
<?>.wasm-function[<core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next::h261e6a572d911a5f]@[wasm code]
<?>.wasm-function[ruffle_core::shape_utils::ShapeConverter::flush_layer::hc7eaee51b32676ea]@[wasm code]
<?>.wasm-function[<ruffle_core::shape_utils::DistilledShape as core::convert::From<&swf::types::Shape>>::from::h208f213a107ed4a9]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h4f87672eb86c43c0]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h0b236411249392ae]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h4dece756de228be6]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdbfcdf3546723b4e]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2a114de6cd1073eb]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h20c4804f6d1ad0a2]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha9dd008cbd1077f3]@[wasm code]
wasm-stub@[native code]
O@https://echo.comdotgame.com/ruffle/core.ruffle.864a59d108a0384ed0a5.js:1:3997
c@https://echo.comdotgame.com/ruffle/core.ruffle.864a59d108a0384ed0a5.js:1:2522
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/69e17ec72f182f3f7646bfb27d0c021b.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/toilet-2
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/69e17ec72f182f3f7646bfb27d0c021b.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-18
Channel: nightly
Built: 2022-03-18T00:17:54.702Z
Commit: e5b6e8c8b7198cd016bb0f37a683718f30a3bcac
Is extension: false

**Comment by n0samu** [comment] 2022-06-18 01:26
Are you an iPad user? If so, you can update to iOS 15.5 to fix this issue! (And this would be a duplicate of #6608)

**Closed** 2024-06-23 23:30 UTC
Labels: nsfw, error-report
