### ISSUE TITLE
Error on http://www.frivjogosonline.com.br/jogo/electricman-2-hs.html

### ISSUE THREAD

**Issue by Adonisco** [ruffle-rs/ruffle#11350] opened 2023-06-02 17:32 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.frivjogosonline.com.br/ruffle-2/core.ruffle.42226413fcddb0ba52ab.js:1:7708)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (wasm://wasm/017414b6:wasm-function[1008]:0x2a52de)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (wasm://wasm/017414b6:wasm-function[1446]:0x31c029)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (wasm://wasm/017414b6:wasm-function[4922]:0x4742a3)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (wasm://wasm/017414b6:wasm-function[3242]:0x416be4)
    at core::panicking::panic_fmt::h5118e89563022e7e (wasm://wasm/017414b6:wasm-function[5007]:0x47822b)
    at core::panicking::panic::he88f1b1582b09c8c (wasm://wasm/017414b6:wasm-function[4920]:0x473e36)
    at core::ops::function::FnOnce::call_once::hea116a8eeeb59311 (wasm://wasm/017414b6:wasm-function[1089]:0x2be097)
    at ruffle_core::avm1::function::Executable::exec::h0a1a3c56ef393e7a (wasm://wasm/017414b6:wasm-function[391]:0x12c992)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf21230a28d8729f3 (wasm://wasm/017414b6:wasm-function[371]:0xe6836)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: 
http://www.frivjogosonline.com.br/wp-content/files/03/swf/electricman-2-hs.swf
Param allowscriptaccess: always
Param wmode: direct
Param SCALE: default
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://www.frivjogosonline.com.br/jogo/electricman-2-hs.html
SWF URL: http://www.frivjogosonline.com.br/wp-content/files/03/swf/electricman-2-hs.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-26
Channel: nightly
Built: 2022-04-26T00:19:55.366Z
Commit: 225c4a80ca9fb2d4bc70c37a9cedda538f115c8c
Is extension: false

**Comment by Lord-McSweeney** [comment] 2023-06-02 20:44
Duplicate of #4932; already fixed by https://github.com/ruffle-rs/ruffle/pull/9447.

**Closed by Lord-McSweeney** 2023-06-02 20:44 UTC
Labels: error-report
