### ISSUE TITLE
Error on http://www.freeworldgroup.com/games9/gameindex/tank2012.htm

### ISSUE THREAD

**Issue by ANDREI-FENG** [ruffle-rs/ruffle#7720] opened 2022-08-21 12:01 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:602:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:602:14
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/core.ruffle.19172fc9c32a2cbd528a.js:1:7361)
    at std::sync::once::Once::call_once::{{closure}}::he3cf99cdc4fda287 (wasm://wasm/016a0f7e:wasm-function[1401]:0x2f7796)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/016a0f7e:wasm-function[1363]:0x2efce3)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha1e2d21f5521daa9 (wasm://wasm/016a0f7e:wasm-function[4786]:0x43ebc1)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/016a0f7e:wasm-function[3509]:0x40491c)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/016a0f7e:wasm-function[4965]:0x4443ba)
    at core::option::expect_failed::h0a5cf22f891a14fb (wasm://wasm/016a0f7e:wasm-function[5613]:0x453cc5)
    at ruffle_core::display_object::stage::Stage::root_clip::h4c0afa8fd189dd10 (wasm://wasm/016a0f7e:wasm-function[3470]:0x402104)
    at ruffle_web::Ruffle::tick::h63bf722752bc2fd2 (wasm://wasm/016a0f7e:wasm-function[612]:0x1d0482)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h73dbebe29e6125ca (wasm://wasm/016a0f7e:wasm-function[5831]:0x45db73)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games9/gameindex/tank2012.htm
SWF URL: http://www.freeworldgroup.com/games9/tank2012/ENsecure.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-20
Channel: nightly
Built: 2022-08-20T00:18:05.053Z
Commit: c2354c1a303f14f110a4596535b53e765fc9e70b
Is extension: false

**Comment by n0samu** [comment] 2022-08-21 12:12
Duplicate of #5832

**Closed by n0samu** 2022-08-21 12:12 UTC
Labels: duplicate, error-report
