### ISSUE TITLE
Error on https://evilgames.eu/flashgames/quake-flash.htm

### ISSUE THREAD

**Issue by FleggyTheBunny** [ruffle-rs/ruffle#2807] opened 2021-01-24 10:18 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32083
    at r (<anonymous>:3:32573)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: ../swf/quake-flash.swf
Param wmode: direct
Param quality: high
Param allowNetworking: internal
Param AllowScriptAccess: never
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://evilgames.eu/flashgames/quake-flash.htm

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-24
Channel: nightly
Built: 2021-01-24T01:05:42.228Z
Commit: 86b4c20809d8778d498474a26601aeda4cec87c4

**Comment by relrelb** [comment] 2021-01-28 14:45
Duplicate of #2201.

**Closed** 2021-02-12 23:52 UTC
