### ISSUE TITLE
Error on https://www.addictinggames.com/action/electric-man-2

### ISSUE THREAD

**Issue by schoudhury442** [ruffle-rs/ruffle#7576] opened 2022-08-04 16:40 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:822:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:822:18
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.addictinggames.com/sites/all/themes/starkish/build/js/ruffle/core.ruffle.e0e876bcfd237f27a772.js:1:6065)
    at std::sync::once::Once::call_once::{{closure}}::h96c2b4473ff6d536 (wasm://wasm/0160c3f6:wasm-function[1205]:0x2b1618)
    at std::sync::once::Once::call_inner::h1c414562e2619117 (wasm://wasm/0160c3f6:wasm-function[1377]:0x2e6810)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h14edbfd8adf99b9a (wasm://wasm/0160c3f6:wasm-function[4677]:0x42b6f9)
    at std::panicking::rust_panic_with_hook::h1c368a27f9b0afe1 (wasm://wasm/0160c3f6:wasm-function[3067]:0x3dc417)
    at core::panicking::panic_fmt::hcdb13a4b2416cf82 (wasm://wasm/0160c3f6:wasm-function[4859]:0x4317e9)
    at core::panicking::panic::ha8ced62e366a0d64 (wasm://wasm/0160c3f6:wasm-function[4770]:0x42d744)
    at core::ops::function::FnOnce::call_once::hf34266054dcdb899 (wasm://wasm/0160c3f6:wasm-function[1021]:0x27d27c)
    at ruffle_core::avm1::function::Executable::exec::hea59bc6806b8639f (wasm://wasm/0160c3f6:wasm-function[382]:0xf85fa)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hc406089cf0ff3f73 (wasm://wasm/0160c3f6:wasm-function[800]:0x21fca5)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /sites/default/files/flash_games/electricman2_0.swf
Param menu: false
Param allowscriptaccess: always
Param allownetworking: all
Param movie: /sites/default/files/flash_games/electricman2_0.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.addictinggames.com/action/electric-man-2
SWF URL: https://www.addictinggames.com/sites/default/files/flash_games/electricman2_0.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-25
Channel: nightly
Built: 2022-07-25T00:17:23.429Z
Commit: afb9ecc4ab8a6f6b9b295ddcb029a4ca80230a9e
Is extension: false

**Comment by relrelb** [comment] 2022-08-04 17:30
Duplicate of #4932.

**Closed by relrelb** 2022-08-04 17:30 UTC
Labels: error-report
