### ISSUE TITLE
Error on https://gg-opensocial.googleusercontent.com/gadgets/ifr

### ISSUE THREAD

**Issue by mialane** [ruffle-rs/ruffle#13588] opened 2023-10-17 15:30 UTC
# Error Info i'm not sure what to do on this but when playing jacksmith, on day 10 where you unlock the weapon 'spetum', the warrior whatever you'd like to call them comes over and asks for a spetum. you can pour the metal fine and everything just when you try to click back it says there is an error. thanks :)
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu/src/backend/direct.rs:3056:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu/src/backend/direct.rs:3056:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://cdn.jsdelivr.net/npm/@ruffle-rs/ruffle@0.1.0-nightly.2023.10.2/core.ruffle.933c3b3a07ce9386f065.js:1:51844)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h70afc0e531fe7142 (wasm://wasm/03298f42:wasm-function[9712]:0x98ded7)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/03298f42:wasm-function[6347]:0x884d7c)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/03298f42:wasm-function[9545]:0x989449)
    at core::ops::function::Fn::call::h526e17b857ccf5d0 (wasm://wasm/03298f42:wasm-function[6561]:0x8916e0)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::ha261fe8a9bd45d04 (wasm://wasm/03298f42:wasm-function[5121]:0x7ec150)
    at wgpu::backend::direct::Context::handle_error::haf649c2c367e5acc (wasm://wasm/03298f42:wasm-function[2611]:0x62f78d)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h82c2118e9991606c (wasm://wasm/03298f42:wasm-function[6965]:0x8bf148)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h3a14717dc44e0f94 (wasm://wasm/03298f42:wasm-function[5957]:0x865e60)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h51279a0a098c0500 (wasm://wasm/03298f42:wasm-function[1608]:0x4bc83f)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/dadsstash/swf-files@93b7a945ccbd0b0dd9ae1028df26f13928020dfa/jacksmith.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://gg-opensocial.googleusercontent.com/gadgets/ifr?url=https://s3.amazonaws.com/production-assetsbucket-8ljvyr1xczmb/1ee20621-61bc-4ec8-a8ec-5e839c2e6edc%2Fjacksmith.xml
SWF URL: https://cdn.jsdelivr.net/gh/dadsstash/swf-files@93b7a945ccbd0b0dd9ae1028df26f13928020dfa/jacksmith.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-02
Channel: nightly
Built: 2023-10-02T00:25:18.095Z
Commit: 58b18e282b64629139ce64b4d6202f214bb8c72a
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9363111

**Comment by n0samu** [comment] 2023-10-17 20:01
Thank you for explaining what led up to the error! We have seen many reports of this error, but we haven't yet been able to reproduce it. This should help!

**Comment by evilpie** [comment] 2024-04-09 15:10
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:10 UTC
Labels: error-report
