### ISSUE TITLE
Elertric Man 2 Biggest Problem 

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#8077] opened 2022-09-24 18:09 UTC
### Describe the bug

https://www.electricman.space/ this is here

### Expected behavior

this is bigget problem it's 10000 error.... this is avm1 support

https://user-images.githubusercontent.com/80902993/192112491-2b9113d3-9206-483a-be8f-b8e81a01d786.mp4

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Edge

### Additional information

Ryzen 3 Graphics
AMD Radeon Graphics
8 RAM Memory (6 RAM)

**Comment by n0samu** [comment] 2022-09-24 18:24
Duplicate of #7460. Please visit the site using the URL https://electricman.space/ instead, or contact them and ask them to fix the problem with their website.

**Closed by n0samu** 2022-09-24 18:24 UTC
Labels: duplicate
