### ISSUE TITLE
Error on https://ja.h-flash.com/pervert-train-xioukoku/

### ISSUE THREAD

**Issue by musyoukou** [ruffle-rs/ruffle#9469] opened 2023-02-08 12:38 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/cmp.rs:860:9
Error stack:
```
@https://ja.h-flash.com/data/ruffle/core.ruffle.5fc5bc0046838bc074f7.js:1:6930
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9]@[wasm code]
<?>.wasm-function[std::sys_common::once::generic::Once::call::h62f79875d8dd2a00]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::he04cb00575f2a1e3]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h586d720a90aa8503]@[wasm code]
<?>.wasm-function[core::panicking::panic::h0859aaac783261b2]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::update_drag::h04c63746577775cf]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::hdcb4afd54d8a568d]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h5b63cba1bdda8f36]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h290fb0fdd8b6051e]@[wasm code]
wasm-stub@[native code]
F@https://ja.h-flash.com/data/ruffle/core.ruffle.5fc5bc0046838bc074f7.js:1:3057
c@https://ja.h-flash.com/data/ruffle/core.ruffle.5fc5bc0046838bc074f7.js:1:2509
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://ja.h-flash.com/pervert-train-xioukoku/
SWF URL: https://ja.h-flash.com/data/swf/2013/10/densya.swf

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-21
Channel: nightly
Built: 2022-12-21T00:16:40.503Z
Commit: 5cf5c8d5e5d3b37a38cf133aa587b7f925612f21
Is extension: false

# Metadata
width: 480
height: 640
frameRate: 24
numFrames: 3
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 897908

**Comment by Lord-McSweeney** [comment] 2023-02-08 15:03
Duplicate of #8363. The issue has already been resolved.

**Closed by Lord-McSweeney** 2023-02-08 15:03 UTC
Labels: duplicate, error-report
