### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by emulsionu87** [ruffle-rs/ruffle#13811] opened 2023-11-01 02:55 UTC
# Error Info
Error name: Error
Error message: Error loading movie: Couldn't read SWF: Invalid data: Invalid SWF
Error stack:
```
Error: Error loading movie: Couldn't read SWF: Invalid data: Invalid SWF
    at vt.load (https://ruffle.rs/demo/index.js:2:290056)
```

# Player Info
Allows script access: false
Renderer: WebGL 1.0
Adapter Vendor: WebKit
Adapter Renderer: WebKit WebGL
Adapter Version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Surface samples: 1 x 
Surface size: 300 x 150

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-01
Channel: nightly
Built: 2023-11-01T00:13:57.096Z
Commit: 432a63250b800ea39a742e6fc76cf4da8a81ecc1
Is extension: false

# Metadata

**Comment by danielhjacobs** [comment] 2023-11-17 16:17
Can you please zip and upload the SWF file that you tried to load? This generally happens if you try to play a corrupted or invalid file.

**Comment by emulsionu87** [comment] 2023-11-17 16:31
Hi Daniel, honestly, I am no flash guy. A long time ago, there was this
company selling an application for windows that did all the flash
animations for you.
It gave you many templates, and you inserted your media like: .jpg and wav
or mp3 files. It allowed you to customize font styles and colors etc.
All of this was generated into a directory, with a "template" file, and a
.bin subfolder I think containing the content.

The program was called Sellfolio, and I think they are long out of
business now.
On a whim, I tried to run it through your ruffle demo app on your site, to
see if I could salvage anything at all from my old website. Didn't expect
it to work at all, and it didn't.

Kills me that flash was obsoleted.
I had a great looking site that I got many compliments on before Google
chrome shut down support for it.

I can send you the folder in which all this stuff resides, but I'm afraid
being a non programmer, I cannot be of much help on my end of things.
Never built out complex flash stuff or websites myself.

Let me know if you still want to take a look at it, as what that company
had going was pretty darn awesome.
I can send the folder to you.

Appreciate your response!
John

**Comment by emulsionu87** [comment] 2023-11-17 16:35
PS., That old app made WAY better and more exciting looking sites than any
of the new Wix, Godaddy etc. site builders.
Saddened by the demise of Flash.
Because I am not a programmer, I have gone from this great animated site,
to a crappy godaddy site.
Static. Boring.
Thanks again,
john

**Comment by Dinnerbone** [comment] 2024-07-12 22:08
Duplicate of #11830

**Closed by Dinnerbone** 2024-07-12 22:08 UTC
Labels: duplicate, error-report
