### ISSUE TITLE
Standalone projector executables

### ISSUE THREAD

**Issue by MarcroSoft** [ruffle-rs/ruffle#19054] opened 2024-12-24 15:08 UTC
**Describe the feature**
Provide a clear and concise description of your feature request. Why would this feature be useful? Does the feature involve the desktop build, the web build, or both?

Hi.
I wish ruffle could create projectors like the old flash players. Then I could send a desktop game to someone and they could open it right away.
At the moment I use small 7z sfx to extract ruffle and the swf to temp, but then the files are stored twice, and may be left over in a 7z temp folder if it crashes.
I hope you can make it possible.
Thanks,
Marc

**Comment by Croworbit** [comment] 2024-12-24 15:15
duplicate of, see also https://github.com/ruffle-rs/ruffle/issues/4754

**Closed as duplicate** 2024-12-24 15:35 UTC
Labels: enhancement
