### ISSUE TITLE
Error on https://www.flashthemes.net/

### ISSUE THREAD

**Issue by boorchess** [ruffle-rs/ruffle#16022] opened 2024-04-17 18:29 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://pipjjbgofgieknlpefmcckdmgaaegban/dist/69.js:3393:21)
    at js_sys::Error::new::ha2f6fa40afaacb83 (wasm://wasm/03a684ce:wasm-function[13903]:0xb26e35)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7f02ae3a8308da6d (wasm://wasm/03a684ce:wasm-function[11505]:0xad1c9d)
    at std::panicking::rust_panic_with_hook::h9aabd906218897c3 (wasm://wasm/03a684ce:wasm-function[7076]:0x99aed9)
    at core::panicking::panic_fmt::h3aff855fe938c13f (wasm://wasm/03a684ce:wasm-function[11212]:0xacb59c)
    at core::panicking::assert_failed_inner::hc4f70f3da5729a72 (wasm://wasm/03a684ce:wasm-function[4925]:0x885a1d)
    at core::panicking::assert_failed::h430530a72591a2a6 (wasm://wasm/03a684ce:wasm-function[11252]:0xacc9f0)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::h16cd163585414f23 (wasm://wasm/03a684ce:wasm-function[2855]:0x6dd38d)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h633da768f994e46f (wasm://wasm/03a684ce:wasm-function[1436]:0x470995)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h196bd4dcf818a77b (wasm://wasm/03a684ce:wasm-function[4080]:0x806564)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 530 (0x00001912) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: low
Surface samples: 1
Surface size: (550, 400, 1)
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param flashvars: movieId=8h5xejB&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D46661&thumburl=%2Fmovie_thumbs%2Fthumb-8h5xejB-d45d7b92-93da-4d43-8659-5334bc7d3afb.png&v=46661&movieLid=6&pwm=0&ut=-1&apiserver=https%3A%2F%2Fflashthemes.net%2F&playcount=1&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=1&isInitFromExternal=0&isWide=0&appCode=go&is_slideshow=0&is_emessage=0&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=0&&&&isTemplate=0&showButtons=1&chain_mids=&endStyle=0&showshare=true
Param movie: /static/animationnew/414827163ad4eb60/player.swf
Param wmode: opaque
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.flashthemes.net/
SWF URL: https://www.flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-04-13
Channel: nightly
Built: 2024-04-13T00:05:31.557Z
Commit: e687d16ecb1d4e3fc1f4d3ea06183f37a29eb835
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by sleepycatcoding** [comment] 2024-05-21 13:15
Duplicate of #13974.

**Closed by sleepycatcoding** 2024-05-21 13:15 UTC
Labels: error-report
