### ISSUE TITLE
Error on https://www.icepets.com/arcade/playgame.php

### ISSUE THREAD

**Issue by karolinefranca** [ruffle-rs/ruffle#4389] opened 2021-05-22 05:32 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/loader.rs:454:42
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/loader.rs:454:42
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://ghccgidajaalgoackdokaioihobikedl/dist/ruffle.js?uniqueMessageSuffix=65649586286:1:7476)
    at std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103 (chrome-extension://ghccgidajaalgoackdokaioihobikedl/dist/7ffcd216fe492199a010.wasm:wasm-function[1074]:0x27f4c3)
    at std::sync::once::Once::call_inner::h99e47643887ee5a5 (chrome-extension://ghccgidajaalgoackdokaioihobikedl/dist/7ffcd216fe492199a010.wasm:wasm-function[948]:0x25807b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989 (chrome-extension://ghccgidajaalgoackdokaioihobikedl/dist/7ffcd216fe492199a010.wasm:wasm-function[3824]:0x406344)
    at std::panicking::rust_panic_with_hook::h03201bc01a0ed891 (chrome-extension://ghccgidajaalgoackdokaioihobikedl/dist/7ffcd216fe492199a010.wasm:wasm-function[2973]:0x3a7749)
    at rust_begin_unwind (chrome-extension://ghccgidajaalgoackdokaioihobikedl/dist/7ffcd216fe492199a010.wasm:wasm-function[4032]:0x40be47)
    at core::panicking::panic_fmt::hd44f353696296fec (chrome-extension://ghccgidajaalgoackdokaioihobikedl/dist/7ffcd216fe492199a010.wasm:wasm-function[4180]:0x4128fe)
    at core::panicking::panic::ha58827a77b951c10 (chrome-extension://ghccgidajaalgoackdokaioihobikedl/dist/7ffcd216fe492199a010.wasm:wasm-function[3975]:0x409a17)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0fff23994a794a87 (chrome-extension://ghccgidajaalgoackdokaioihobikedl/dist/7ffcd216fe492199a010.wasm:wasm-function[498]:0x1612d2)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8c469485238b2d40 (chrome-extension://ghccgidajaalgoackdokaioihobikedl/dist/7ffcd216fe492199a010.wasm:wasm-function[1474]:0x2e27cb)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.icepets.com/arcade/playgame.php?game_id=20
SWF URL: https://www.icepets.com/arcade/ice_snake.swf?&n=1621661438

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-22
Channel: nightly
Built: 2021-05-22T00:13:24.653Z
Commit: 7717b97027019f7194999cdbc6b13f6520a2dc19

**Comment by relrelb** [comment] 2021-05-28 07:36
Duplicate of #2866.

**Closed by relrelb** 2021-05-28 07:36 UTC
