### ISSUE TITLE
AVM1 domain locks always fail

### ISSUE THREAD

**Issue by Serentty** [ruffle-rs/ruffle#325] opened 2020-01-16 03:50 UTC
[Territory War](https://www.newgrounds.com/portal/view/302830/format/flash?emulate=flash) seems to be using a domain-locking system where it checks to see if it's hosted on Newgrounds. It seems that Ruffle isn't allowing it to verify its domain properly, causing it to lock up.

**Comment by Herschel** [comment] 2020-01-16 03:57
This requires `_url` to be implemented (cc #263). We should provide a user configurable way to spoof the URL, as well.

**Comment by kmeisthax** [comment] 2020-01-16 04:07
The quickest fix would be to just accept the URL as a parameter when constructing the instance, and then have `_url` pull that.

In `moviefetch` (PR #120) I'll have to do something more elaborate than that, and have it pull the URL from the `SwfMovie` it gets it's data from. Starting to think it might make sense to also have the player kick off the SWF fetch itself in that case...

**Comment by Herschel** [comment] 2020-01-16 04:41
Yes, I'd prefer to have as much as possible on the Rust side.

**Comment by DotGage** [comment] 2020-02-23 08:52
JCTLM and the Castle series are both being locked from viewing as well. 

https://www.newgrounds.com/portal/view/451137/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/414569/format/flash?emulate=flash

**Comment by Justin-CB** [comment] 2020-05-04 17:25
It looks like of the 3 flash games, only Castle Repercussion isn't working(which is strange, as it's one that always loads ruffle, even without `?emulate=flash`).

**Comment by n0samu** [comment] 2022-09-10 04:30
The reason Castle Repercussion isn't working is because it checks specifically for `http://` URLs, but Newgrounds is now using HTTPS:
```as
if(checkurl == "http://deletionquality.net/" || checkurl2 == "http://www.deletionquality.net/" || checkurl3 == "http://uploads.ungrounded.net/" || checkurl4 == "http://www.uploads.ungrounded.net/")
{
   gg.gotoAndStop(1);
}
```
I'll close this issue since Ruffle seems to be working as intended for all of the mentioned cases.

**Closed by n0samu** 2022-09-10 04:30 UTC
