### ISSUE TITLE
Error on https://kdata1.com/games/SSF22/

### ISSUE THREAD

**Issue by rukana0822** [ruffle-rs/ruffle#15471] opened 2024-03-07 07:23 UTC
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://kdata1.com/games/SSF22/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-07
Channel: nightly
Built: 2024-03-07T00:05:09.134Z
Commit: d3e12e4a240f545517c33b0c704a4fb197415154
Is extension: false

# Metadata

**Comment by Dinnerbone** [comment] 2024-07-12 22:07
Duplicate of #15444

**Closed by Dinnerbone** 2024-07-12 22:07 UTC
Labels: duplicate, error-report
