### ISSUE TITLE
Error on chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/player.html

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#5697] opened 2021-11-21 09:17 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/dist/player.js:1:8098)
    at std::sync::once::Once::call_once::{{closure}}::h5387044f596cf17b (chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/dist/2da79230c52ac9361cc6.wasm:wasm-function[1003]:0x2f13ae)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/dist/2da79230c52ac9361cc6.wasm:wasm-function[1334]:0x363d84)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h4461033b8c8249d8 (chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/dist/2da79230c52ac9361cc6.wasm:wasm-function[4690]:0x4f0908)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/dist/2da79230c52ac9361cc6.wasm:wasm-function[3314]:0x4ac005)
    at rust_begin_unwind (chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/dist/2da79230c52ac9361cc6.wasm:wasm-function[4752]:0x4f3076)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/dist/2da79230c52ac9361cc6.wasm:wasm-function[4959]:0x4fdbf8)
    at core::panicking::panic::hceae0c79b0247f98 (chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/dist/2da79230c52ac9361cc6.wasm:wasm-function[4686]:0x4f0139)
    at core::ops::function::FnOnce::call_once::hf99a08a7a8d58165 (chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/dist/2da79230c52ac9361cc6.wasm:wasm-function[1047]:0x30cf00)
    at ruffle_core::avm1::function::Executable::exec::hc98df77004cccb4f (chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/dist/2da79230c52ac9361cc6.wasm:wasm-function[416]:0x15909f)
```

# Player Info
Allows script access: false

# Page Info
Page URL: chrome-extension://bjmgjiiikomibajbpcdmphjapijphpjj/player.html?url=http://farm.stickpage.com/electricman2game.swf
SWF URL: http://farm.stickpage.com/electricman2game.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-20
Channel: nightly
Built: 2021-11-20T00:11:45.279Z
Commit: ae189c5a0ddb0fc515fe1070bf0287571e1cea97
Is extension: true

**Comment by relrelb** [comment] 2021-11-21 18:20
Duplicate of #4932.

**Closed by relrelb** 2021-11-21 18:20 UTC
