### ISSUE TITLE
Error on https://www.y8.com/games/electricman_2_hs

### ISSUE THREAD

**Issue by TheSpender2007** [ruffle-rs/ruffle#6362] opened 2022-02-27 05:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6962)
    at std::sync::once::Once::call_once::{{closure}}::h13f587f63b63b4ac (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/1e45ad06d2e185d06daf.wasm:wasm-function[1020]:0x2eeb6f)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/1e45ad06d2e185d06daf.wasm:wasm-function[1157]:0x32103e)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h33ec6d244c0c001a (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/1e45ad06d2e185d06daf.wasm:wasm-function[4695]:0x4c8fa3)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/1e45ad06d2e185d06daf.wasm:wasm-function[3182]:0x475a59)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/1e45ad06d2e185d06daf.wasm:wasm-function[4961]:0x4d4a86)
    at core::panicking::panic::h35778e3c18266c93 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/1e45ad06d2e185d06daf.wasm:wasm-function[4692]:0x4c8aca)
    at core::ops::function::FnOnce::call_once::h45f77bbd44c17208 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/1e45ad06d2e185d06daf.wasm:wasm-function[1054]:0x3044f0)
    at ruffle_core::avm1::function::Executable::exec::h091110751732661d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/1e45ad06d2e185d06daf.wasm:wasm-function[396]:0x13a244)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h64e8aedb6aa010eb (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/1e45ad06d2e185d06daf.wasm:wasm-function[459]:0x19075e)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.y8.com/games/electricman_2_hs
SWF URL: https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/794/original/electricman_2_hs.swf?1521282395

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-24
Channel: nightly
Built: 2022-02-24T00:17:59.239Z
Commit: 056eee8b46c91e2dbbb54530bb30554766a703ff
Is extension: true

**Comment by relrelb** [comment] 2022-02-27 07:06
Duplicate of #4932.

**Closed by relrelb** 2022-02-27 07:06 UTC
Labels: error-report
