### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by XtuRnaL** [ruffle-rs/ruffle#3907] opened 2021-04-05 22:08 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1617642380:1:6915)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://uploads.ungrounded.net/ruffle_wrapper/lib/2284a6b44671cdead92714936eb097eb.wasm:wasm-function[1196]:0x29061b)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://uploads.ungrounded.net/ruffle_wrapper/lib/2284a6b44671cdead92714936eb097eb.wasm:wasm-function[1803]:0x3101c6)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://uploads.ungrounded.net/ruffle_wrapper/lib/2284a6b44671cdead92714936eb097eb.wasm:wasm-function[5310]:0x41c97e)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://uploads.ungrounded.net/ruffle_wrapper/lib/2284a6b44671cdead92714936eb097eb.wasm:wasm-function[4085]:0x3ee2ec)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (https://uploads.ungrounded.net/ruffle_wrapper/lib/2284a6b44671cdead92714936eb097eb.wasm:wasm-function[4791]:0x40f241)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (https://uploads.ungrounded.net/ruffle_wrapper/lib/2284a6b44671cdead92714936eb097eb.wasm:wasm-function[5683]:0x422696)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/2284a6b44671cdead92714936eb097eb.wasm:wasm-function[5554]:0x420cda)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://uploads.ungrounded.net/ruffle_wrapper/lib/2284a6b44671cdead92714936eb097eb.wasm:wasm-function[5685]:0x4226fa)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h38b530e6d6f4189b (https://uploads.ungrounded.net/ruffle_wrapper/lib/2284a6b44671cdead92714936eb097eb.wasm:wasm-function[1710]:0x30042b)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1617642380%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2265177448.46950e5a58b6066d405b0c7ac8af5bf3af27a06d906c16%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22606b85a5e178e%22%2C%22NewgroundsAPI_SessionID%22%3A%225AaOeJjzKCDmNkbXWIBG05a64579810cbbc003e22e5c9e3bc4e217c98d3bW3iC%22%2C%22NewgroundsAPI_UserName%22%3A%22Xtutnal%22%2C%22NewgroundsAPI_UserID%22%3A7993468%2C%22ng_username%22%3A%22Xtutnal%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-04
Channel: nightly
Built: 2021-04-04T00:42:01.875Z
Commit: e2f124ee34eb27c0f6463a76534b4936e750d58a

**Comment by relrelb** [comment] 2021-04-09 09:46
Duplicate of #3889.

**Closed by relrelb** 2021-04-09 09:46 UTC
