### ISSUE TITLE
Error on https://ruffle.rs/

### ISSUE THREAD

**Issue by Leeev** [ruffle-rs/ruffle#14006] opened 2023-11-13 19:51 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Internal error in ShaderStages(VERTEX) shader: 

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Internal error in ShaderStages(VERTEX) shader: 


    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.9fec9a1b17acdaaddfc5.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b09d9124792ee2e (wasm://wasm/0340e2b2:wasm-function[9968]:0x9d3407)
    at std::panicking::rust_panic_with_hook::h3aa054d35a0817d7 (wasm://wasm/0340e2b2:wasm-function[6530]:0x8d3507)
    at core::panicking::panic_fmt::h3e1dd3d08288569e (wasm://wasm/0340e2b2:wasm-function[9765]:0x9ce16e)
    at core::ops::function::Fn::call::hab4d293b6b61afb0 (wasm://wasm/0340e2b2:wasm-function[6711]:0x8ddc03)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::ha8d57641bba5ca8c (wasm://wasm/0340e2b2:wasm-function[5404]:0x870ad5)
    at <T as wgpu::context::DynContext>::device_create_render_pipeline::h1d2f4ebd60272cdb (wasm://wasm/0340e2b2:wasm-function[8573]:0x9742ad)
    at wgpu::Device::create_render_pipeline::ha33a0a3216602da1 (wasm://wasm/0340e2b2:wasm-function[7227]:0x902614)
    at ruffle_render_wgpu::utils::run_copy_pipeline::hc3fc798e2bb6d97f (wasm://wasm/0340e2b2:wasm-function[2578]:0x661572)
    at ruffle_render_wgpu::surface::Surface::draw_commands_and_copy_to::h99c59d856ba641e8 (wasm://wasm/0340e2b2:wasm-function[1739]:0x50e4b2)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-13
Channel: nightly
Built: 2023-11-13T00:14:23.579Z
Commit: 11c5a68452e53858871a0c3567a3c8368d6596be
Is extension: false

# Metadata

**Comment by danielhjacobs** [comment] 2023-11-17 16:16
Can you please zip and upload or link to the SWF file that you tried to load?

**Comment by Dinnerbone** [comment] 2024-07-12 22:08
Duplicate of #13794

**Closed by Dinnerbone** 2024-07-12 22:08 UTC
Labels: duplicate, error-report
