### ISSUE TITLE
Error on https://f.silvergames.com/ruffle/player.php

### ISSUE THREAD

**Issue by macleod1235** [ruffle-rs/ruffle#7924] opened 2022-09-08 23:06 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 7 but the index is 7', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-1.0.1/src/fill.rs:1547:27
Error stack:
```
Error: panicked at 'index out of bounds: the len is 7 but the index is 7', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-1.0.1/src/fill.rs:1547:27
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://f.silvergames.com/ruffle/260822/core.ruffle.98b16d83d1ba83106bb9.js:1:7523)
    at std::sync::once::Once::call_once::{{closure}}::h9b662bb03984fbef (wasm://wasm/017204da:wasm-function[1451]:0x0)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/017204da:wasm-function[1405]:0x0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2bb213d101087fa9 (wasm://wasm/017204da:wasm-function[4786]:0x0)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/017204da:wasm-function[3549]:0x0)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/017204da:wasm-function[4965]:0x0)
    at core::panicking::panic_bounds_check::hba06abf6b514a1a1 (wasm://wasm/017204da:wasm-function[4314]:0x0)
    at lyon_tessellation::fill::FillTessellator::process_events::hdfec8c7907959ad3 (wasm://wasm/017204da:wasm-function[331]:0x0)
    at lyon_tessellation::fill::FillTessellator::tessellate_impl::h68bea4228d2df416 (wasm://wasm/017204da:wasm-function[544]:0x0)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h2a0f4d55ecb0af74 (wasm://wasm/017204da:wasm-function[618]:0x0)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://f.silvergames.com/ruffle/player.php?id=4103
SWF URL: https://f.silvergames.com/douchebags-chick_v2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.27
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-26
Channel: nightly
Built: 2022-08-26T00:17:38.238Z
Commit: d152cc3e6485b08937102b77434f6ec2cb1a40b9
Is extension: false

**Comment by n0samu** [comment] 2022-09-08 23:10
This problem is caused by Microsoft Edge's "Enhance your security on the web" feature. [See the FAQ for a solution to the problem](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#edge-webassembly-error).

Closing in favor of #7849 (same issue).

**Closed by n0samu** 2022-09-08 23:10 UTC
Labels: duplicate, error-report
