### ISSUE TITLE
Error on https://www.comdotgame.com/play/breeding-season

### ISSUE THREAD

**Issue by Amaroq26** [ruffle-rs/ruffle#9251] opened 2023-01-21 16:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://echo.comdotgame.com/ruffle/core.ruffle.da135b622b824b611fe9.js:1:6974)
    at std::sync::once::Once::call_once::{{closure}}::hcd46b3a2543691b9 (wasm://wasm/01919246:wasm-function[927]:0x26cae0)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/01919246:wasm-function[1403]:0x319a4c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb7a03847d0b7780a (wasm://wasm/01919246:wasm-function[4992]:0x4bd53a)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/01919246:wasm-function[3769]:0x47c2fa)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/01919246:wasm-function[5233]:0x4c2397)
    at core::option::expect_failed::h2290d18a0c9a6a24 (wasm://wasm/01919246:wasm-function[5916]:0x4d5aaf)
    at ruffle_core::display_object::stage::Stage::root_clip::he233f8c082471f13 (wasm://wasm/01919246:wasm-function[3705]:0x476499)
    at ruffle_web::Ruffle::tick::ha75571213826a268 (wasm://wasm/01919246:wasm-function[643]:0x1e9e69)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h2f891ef58527c159 (wasm://wasm/01919246:wasm-function[6160]:0x4ddff1)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/9c0d91fbb2b1623dea0c66e81930a097.swf
Param allowscriptaccess: always
Param bgcolor: 110000
Param wmode: gpu
Param base: https://echo.comdotgame.com/4x90xhl3k0/games/files/breeding-season/7.7.1/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/breeding-season?ruffle
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/9c0d91fbb2b1623dea0c66e81930a097.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.52
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-07
Channel: nightly
Built: 2022-12-07T00:18:07.185Z
Commit: 2bb4e2e549ab39d2f2cb7d8194ac21bb1ca2e682
Is extension: false

# Metadata
width: 960
height: 720
frameRate: 28
numFrames: 2
swfVersion: 28
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 26690565

**Comment by n0samu** [comment] 2023-01-22 01:31
Duplicate of #8344

**Closed by n0samu** 2023-01-22 01:31 UTC
Labels: duplicate, nsfw, error-report
