### ISSUE TITLE
Error on https://newheredigitaltoys.xyz/

### ISSUE THREAD

**Issue by starblinky** [ruffle-rs/ruffle#3513] opened 2021-03-03 00:49 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
https://newheredigitaltoys.xyz/ruffle.js?cache=2:1:6562
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hd3d269a4946f2df2]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h4f753dc70b771d8e]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hbd8a975261a5f466]@[wasm code]
<?>.wasm-function[std::thread::local::LocalKey<T>::with::hd56bd27bc5f64716]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hdc958bb80e5e8182]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hce25ab2cb9e71f54]@[wasm code]
wasm-stub@[native code]
I@https://newheredigitaltoys.xyz/ruffle.js?cache=2:1:3544
a@https://newheredigitaltoys.xyz/ruffle.js?cache=2:1:2841
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: NewhereDigitalToys_CenkuProductions.swf
Param movie: NewhereDigitalToys_CenkuProductions.swf
Param quality: high
Param bgcolor: #191919
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param salign: t
Param allowScriptAccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://newheredigitaltoys.xyz/
SWF URL: https://newheredigitaltoys.xyz/NewhereDigitalToys_CenkuProductions.swf

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-21
Channel: nightly
Built: 2021-02-21T00:20:18.629Z
Commit: eb173f06ca0918e2d2b488cd14849152db607e51

**Comment by Dinnerbone** [comment] 2024-07-12 22:00
Duplicate of #3452

**Closed by Dinnerbone** 2024-07-12 22:00 UTC
Labels: duplicate, error-report
