### ISSUE TITLE
Error on https://flashthemes.net/user/5432

### ISSUE THREAD

**Issue by SonnyGithub2022** [ruffle-rs/ruffle#15583] opened 2024-03-15 04:42 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3393:21)
    at js_sys::Error::new::ha368c9ce23eebad4 (wasm://wasm/03a1f3c6:wasm-function[13916]:0xb12ae8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9c4751e459e0dc59 (wasm://wasm/03a1f3c6:wasm-function[11520]:0xabd331)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/03a1f3c6:wasm-function[7072]:0x98340a)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/03a1f3c6:wasm-function[11231]:0xab6cc4)
    at core::panicking::assert_failed_inner::h161125ff96c9e54a (wasm://wasm/03a1f3c6:wasm-function[4931]:0x872e20)
    at core::panicking::assert_failed::hea0099895d8107cd (wasm://wasm/03a1f3c6:wasm-function[11274]:0xab81d5)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::hc3fed6c1b5a8797e (wasm://wasm/03a1f3c6:wasm-function[2874]:0x6d05aa)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h5b2dcfc9e99d5884 (wasm://wasm/03a1f3c6:wasm-function[1444]:0x4643b5)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h1d221e0e2fafc54e (wasm://wasm/03a1f3c6:wasm-function[4084]:0x7f23a7)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x000015D8) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param allowFullScreen: true
Param allowScriptAccess: always
Param scale: exactfit
Param wmode: transparent
Param flashvars: movieOwner=HenryAnimations2k10&movieOwnerId=5432&userId=5432&movieId=b9lqrVRj&movieLid=0&movieTitle=MFTLFCL%20(Appaling%20Edition)&movieDesc=&username=&uemail=&ut=-1&numContact=&apiserver=https%3A%2F%2Fflashthemes.net%2F&duration=2%3A26&playcount=0&thumbnailURL=https%3A%2F%2Fflashthemes.net%2F%2Fmovie_thumbs%2Fthumb-b9lqrVRj.png&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=0&appCode=go&is_slideshow=0&is_emessage=0&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D5432&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=%2Fstatic%2Fanimationnew%2F414827163ad4eb60&isEmbed=1&refuser=&utm_source=&uid=&isTemplate=0&showButtons=1&chain_mids=&averageRating=5&ratingCount=5&ad=0&v=5432&endStyle=0&isWide=0&pwm=1
Param movie: /static/animationnew/414827163ad4eb60/player.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/user/5432
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-14
Channel: nightly
Built: 2024-03-14T00:05:42.080Z
Commit: f472bbc701421c65603f0c2e3457ad6481948d53
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment] 2024-05-12 21:36
Duplicate of #13974

**Closed by n0samu** 2024-05-12 21:36 UTC
Labels: duplicate, error-report
