### ISSUE TITLE
Error on https://flashthemes.net/movie/6wxL88oQ

### ISSUE THREAD

**Issue by LeoKids** [ruffle-rs/ruffle#15835] opened 2024-04-01 21:48 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys/pal/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys/pal/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3393:21)
    at js_sys::Error::new::h8e593d55ccfdbc76 (wasm://wasm/03a4db42:wasm-function[13912]:0xb210a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc1495a37ebcbc9dc (wasm://wasm/03a4db42:wasm-function[11503]:0xacbc93)
    at std::panicking::rust_panic_with_hook::h5ca5fd3b2064be1b (wasm://wasm/03a4db42:wasm-function[7082]:0x99528d)
    at core::panicking::panic_fmt::h2582bddf31c1c986 (wasm://wasm/03a4db42:wasm-function[11210]:0xac558f)
    at core::panicking::assert_failed_inner::hf073d683243b665e (wasm://wasm/03a4db42:wasm-function[4918]:0x881a44)
    at core::panicking::assert_failed::ha3d8bcf705ea9fbe (wasm://wasm/03a4db42:wasm-function[11252]:0xac6a4e)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::h5ecb66d5db9bc106 (wasm://wasm/03a4db42:wasm-function[2860]:0x6d88d9)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h252089a314bc9d7a (wasm://wasm/03a4db42:wasm-function[1441]:0x4745d0)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h17b5e40182c3d9de (wasm://wasm/03a4db42:wasm-function[4070]:0x801c1e)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: WebGL 1.0
Adapter Vendor: WebKit
Adapter Renderer: WebKit WebGL
Adapter Version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Surface samples: 1 x 
Surface size: 300 x 150
Player type: Object
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param wmode: transparent
Param flashvars: movieOwner=&movieOwnerId=2328&movieId=6wxL88oQ&movieLid=6&pwm=0&movieDesc=This%2520is%2520what%2520playing%2520Naruto%253AUltimate%2520Ninja%2520is%2520like%252Cin%2520a%2520nutshell.&userId=2328&username=&uemail=&ut=-1&numContact=&apiserver=https%3A%2F%2Fflashthemes.net%2F&duration=53&playcount=1&thumbnailURL=%2Fmovie_thumbs%2Fthumb-6wxL88oQ.png&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=0&isInitFromExternal=0&isWide=1&appCode=go&is_slideshow=0&is_emessage=0&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D2328%26p%3Dtrue&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=1&&&&isTemplate=0&showButtons=1&chain_mids=&averageRating=0&ratingCount=2&endStyle=0&showshare=false
Param movie: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/movie/6wxL88oQ
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-04-01
Channel: nightly
Built: 2024-04-01T00:05:49.860Z
Commit: df7d95bf431911ef88433e5a253a36fc738af8cf
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment] 2024-05-12 21:35
Duplicate of #13974

**Closed by n0samu** 2024-05-12 21:35 UTC
Labels: duplicate, error-report
