### ISSUE TITLE
Error on https://www.minijogos.com.br/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by adrierjs** [ruffle-rs/ruffle#10881] opened 2023-04-29 22:41 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:602:51
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:602:51
    at O.n.wbg.__wbg_new_15d3966e9981a196 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.20f0e2271109bbc1687a.js:1:48745)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd28f65a61f685e47 (wasm://wasm/02b70612:wasm-function[8385]:0x80f7bb)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02b70612:wasm-function[5500]:0x7325b2)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02b70612:wasm-function[8240]:0x80a039)
    at core::panicking::panic::hea78c4e8b318407d (wasm://wasm/02b70612:wasm-function[7546]:0x7cfcfc)
    at ruffle_core::bitmap::bitmap_data::BitmapData::update_dirty_texture::h69e242bde85db84e (wasm://wasm/02b70612:wasm-function[1280]:0x3d4ed9)
    at <ruffle_core::library::MovieLibrarySource as ruffle_render::bitmap::BitmapSource>::bitmap_handle::h218cbf3363c21bf3 (wasm://wasm/02b70612:wasm-function[3251]:0x61f763)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_shape::haa5f47cd0e691a1c (wasm://wasm/02b70612:wasm-function[1120]:0x38361a)
    at ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h3ce1a0757a2ce061 (wasm://wasm/02b70612:wasm-function[3610]:0x66dcf4)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h30e5eba151b7c315 (wasm://wasm/02b70612:wasm-function[621]:0x1e2070)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.minijogos.com.br/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=21595&mp_game_uid=tu-95&mp_game_url=https%3A%2F%2Fwww.minijogos.com.br%2Fembed%2Ftu-95&mp_int=1&mp_locale=pt_BR&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvdHU5NS5zd2Y%3D&mp_site_https_url=https%3A%2F%2Fwww.minijogos.com.br%2F&mp_site_name=minijogos.com.br&mp_site_url=https%3A%2F%2Fwww.minijogos.com.br%2F&mp_timezone=America%2FRecife&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/tu95.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-29
Channel: nightly
Built: 2023-04-29T00:20:24.499Z
Commit: 1f956ffe55525657dc4748ce39861a995c2fe2a9
Is extension: false

# Metadata
width: 670
height: 450
frameRate: 24
numFrames: 31
swfVersion: 9
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3416455

**Comment by Lord-McSweeney** [comment] 2023-04-29 22:57
Duplicate of #10833.

**Closed by Lord-McSweeney** 2023-04-29 22:57 UTC
Labels: error-report
