### ISSUE TITLE
Error on https://game52567.konggames.com/games/raitendo/you-only-live-once/frame/2a33e8cc-9749-4c4e-9e79-04bc7a65fcb3/

### ISSUE THREAD

**Issue by memmam** [ruffle-rs/ruffle#13716] opened 2023-10-26 07:46 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/avm1/activation.rs:404:18:
No script object for display object
Error stack:
```
339/U/n.wbg.__wbg_new_d258248ed531ff54@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.fa55cd8e4a345c6a0df5.js:1:53228
core::ops::function::FnOnce::call_once{{vtable.shim}}::hee68611ee8147044@:wasm-function[9747]:0x995320
std::panicking::rust_panic_with_hook::h3aa054d35a0817d7@:wasm-function[6416]:0x8981dd
core::panicking::panic_fmt::h3e1dd3d08288569e@:wasm-function[9549]:0x99016b
ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hc5563bfda4df9212@:wasm-function[3378]:0x6f57ba
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h95b81965e7dbf74c@:wasm-function[4013]:0x763e9c
ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::ha261dc09a28ba0ca@:wasm-function[1099]:0x3b1692
ruffle_core::display_object::movie_clip::MovieClip::place_object::ha4fa33f8ba1ca753@:wasm-function[2011]:0x56e003
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h6cfe8ad1c811ca8e@:wasm-function[891]:0x31687c
ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::ha261dc09a28ba0ca@:wasm-function[1099]:0x3b16ce
ruffle_core::display_object::movie_clip::MovieClip::place_object::ha4fa33f8ba1ca753@:wasm-function[2011]:0x56e003
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h6cfe8ad1c811ca8e@:wasm-function[891]:0x31687c
<ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::ha3fc450bbce7fc57@:wasm-function[2696]:0x6531db
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h6cfe8ad1c811ca8e@:wasm-function[891]:0x315f7a
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::enter_frame::h376d917cf68d7e90@:wasm-function[4116]:0x775ef0
ruffle_web::Ruffle::tick::hc29102e9444436dd@:wasm-function[819]:0x2bf239
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h42ff82500e72e681@:wasm-function[11877]:0x9db4d0
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0afcc7fe5774140e@:wasm-function[10498]:0x9b27a9
A@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.fa55cd8e4a345c6a0df5.js:1:2834
c@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.fa55cd8e4a345c6a0df5.js:1:2511

```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game52567.konggames.com/games/raitendo/you-only-live-once/frame/2a33e8cc-9749-4c4e-9e79-04bc7a65fcb3/?kongregate_host=www.kongregate.com
SWF URL: https://game52567.konggames.com/gamez/0005/2567/live/yolo.swf?kongregate_game_version=1249158969

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-26
Channel: nightly
Built: 2023-10-26T00:21:16.921Z
Commit: 27831d78810de2db5214c298b0eb46c7cc3c6299
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 50
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 5566959

**Comment by Lord-McSweeney** [comment] 2023-11-25 02:12
Duplicate of #13614

**Closed by Lord-McSweeney** 2023-11-25 02:12 UTC
Labels: error-report, mixed-avm
