### ISSUE TITLE
Error on https://rerise.4mir.net/game/

### ISSUE THREAD

**Issue by govras** [ruffle-rs/ruffle#2797] opened 2021-01-23 14:35 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3108:14
Error stack:
```
e/a.wbg.__wbg_new_df6e6ab7a65c4c4d@https://rerise.4mir.net/ruffle/ruffle.js:1:6518
std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[1271]:0x256e6b
std::sync::once::Once::call_inner::h02eac160d339afc2@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[1537]:0x287b7f
core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[4318]:0x35dade
std::panicking::rust_panic_with_hook::h123718ba3bf480af@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[3314]:0x336baf
std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[3926]:0x3539bf
std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[4664]:0x363220
rust_begin_unwind@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[4536]:0x361836
core::panicking::panic_fmt::h285dc015a87be5a4@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[4666]:0x363284
core::panicking::panic::h0abe4e7a620ae568@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[4470]:0x3606fb
ruffle_core::display_object::movie_clip::ClipAction::from_action_and_movie::h5947c408104e25ed@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[2287]:0x2e841e
<core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next::hd27aefc78ac0e0f5@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[1212]:0x24a72f
<alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter::h3951c062be645d8f@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[1167]:0x24028f
ruffle_core::display_object::TDisplayObject::apply_place_object::hd6345e81ebcf0d57@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[826]:0x1dfb98
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::apply_place_object::h59028f5e03c925c8@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[3994]:0x355bff
ruffle_core::display_object::movie_clip::MovieClip::run_goto::{{closure}}::h94289c4103630058@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[2460]:0x2f91c5
ruffle_core::display_object::movie_clip::MovieClip::run_goto::h258cdecbe3dc0f58@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[450]:0x1286b8
ruffle_core::display_object::movie_clip::MovieClip::goto_frame::h52665f30c69ebde6@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[2749]:0x3120e6
ruffle_core::avm1::globals::movie_clip::goto_frame::hc6e17867c0bcdd39@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[1215]:0x24b341
core::ops::function::FnOnce::call_once::h1eb18f40d34cab23@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[3823]:0x34fcf0
ruffle_core::avm1::function::Executable::exec::h730c08f0eeeaf423@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[354]:0xcdbeb
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::hd9c62149769d407b@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[807]:0x1d93e3
ruffle_core::avm1::object::TObject::call_method::hbfb35770c5808609@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[1556]:0x28ac79
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h4bb72bef8c160084@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[952]:0x2086f2
ruffle_core::avm1::activation::Activation::do_action::hd598f2a9929e1825@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[286]:0x1c0f3
ruffle_core::avm1::activation::Activation::run_actions::h937245a24cf3d918@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[2785]:0x314af3
ruffle_core::avm1::Avm1::run_stack_frame_for_action::h07d1a3879bea63ef@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[1018]:0x21b11f
ruffle_core::player::Player::run_actions::hbcdf7db7936243f9@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[417]:0x10cd86
ruffle_core::player::Player::run_frame::h20f759f5a4862255@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[873]:0x1ef9a4
ruffle_core::player::Player::tick::hc63353bedee00885@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[3333]:0x337c5d
std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[759]:0x1c7f80
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hc9990c794ee9c7af@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[4568]:0x361f30
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hbc76ba63e1f5e772@https://rerise.4mir.net/ruffle/7529c74a352c7085633a156f1dc0739b.wasm:wasm-function[4845]:0x3650af
O@https://rerise.4mir.net/ruffle/ruffle.js:1:4040
a@https://rerise.4mir.net/ruffle/ruffle.js:1:2840

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://rerise.4mir.net/game/
SWF URL: https://rerise.4mir.net/game/swf/game.swf?userlogin=

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-23
Channel: nightly
Built: 2021-01-23T01:07:06.024Z
Commit: 0cf3a4abedae45a31db9764f74026dcab48cd05e

**Comment by relrelb** [comment] 2021-04-24 19:19
Duplicate of #2737.

**Closed by relrelb** 2021-04-24 19:19 UTC
