### ISSUE TITLE
Error on https://games.crazygames.com/en_US/electric-man/index.html

### ISSUE THREAD

**Issue by urmom694** [ruffle-rs/ruffle#8532] opened 2022-11-12 19:39 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://files.crazygames.com/gameframe/ruffle/2022-10-08/core.ruffle.c00b1522f61b16f6f730.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/01800756:wasm-function[1035]:0x2a7210)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01800756:wasm-function[1498]:0x32a258)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/01800756:wasm-function[4956]:0x48841a)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01800756:wasm-function[3645]:0x444624)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01800756:wasm-function[5111]:0x48b8aa)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/01800756:wasm-function[5012]:0x4893d6)
    at core::ops::function::FnOnce::call_once::h2b64b87dbbaf5054 (wasm://wasm/01800756:wasm-function[1129]:0x2c6e48)
    at ruffle_core::avm1::function::Executable::exec::h7dbb30579b1dd750 (wasm://wasm/01800756:wasm-function[369]:0x100642)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h55e375c84faa5088 (wasm://wasm/01800756:wasm-function[443]:0x16274e)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://games.crazygames.com/en_US/electric-man/index.html
SWF URL: https://files.crazygames.com/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-08
Channel: nightly
Built: 2022-10-08T00:21:16.770Z
Commit: 5c9471436371f24f1d95011d21b5cddb7fc4ee7f
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3641749

**Comment by n0samu** [comment] 2022-11-13 03:22
Duplicate of #4932

**Closed by n0samu** 2022-11-13 03:22 UTC
Labels: duplicate, error-report
