### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by MadnessCombatEnjoyer** [ruffle-rs/ruffle#5912] opened 2021-12-22 03:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/cmp.rs:816:9
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1639324228:1:7628)
    at std::sync::once::Once::call_once::{{closure}}::h8b88e6aa08fbb40d (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[986]:0x309429)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[1175]:0x34d23f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3ab0488d22755852 (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[4623]:0x4f98ff)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[3217]:0x4b37c5)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[4686]:0x4fb01d)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[4896]:0x505b86)
    at core::panicking::panic::hec1fc057bd0baf0b (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[4620]:0x4f9165)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::set_viewport_dimensions::h090030320a082c98 (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[690]:0x269dad)
    at ruffle_web::Ruffle::tick::h98d8d54201e811f2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/731179ae1716fbb60e1c.wasm:wasm-function[584]:0x21ddd2)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1639324228%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2298941460.622b23e2492c16405a99c913f9e9aa0fd5deef6057538b%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261c2942e33e10%22%2C%22NewgroundsAPI_SessionID%22%3A%22cCNAl9hZSsm2KJ5B8927b0bb5f7a1f27097b5ec556c50aa648d7a249bcb3t3z5%22%2C%22NewgroundsAPI_UserName%22%3A%22iLiekPopcorn%22%2C%22NewgroundsAPI_UserID%22%3A9901003%2C%22ng_username%22%3A%22iLiekPopcorn%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14268.67.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.111 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-12
Channel: nightly
Built: 2021-12-12T00:14:30.969Z
Commit: 1f5979f1681cd886e0e2b8245ec43190175b58ba
Is extension: false

**Comment by Poopooracoocoo** [comment] 2021-12-22 04:14
Duplicate of #4038

**Closed by Poopooracoocoo** 2021-12-22 04:14 UTC
Labels: duplicate, error-report
