### ISSUE TITLE
Error on https://ooooooooo.ooo/static/

### ISSUE THREAD

**Issue by You-mon** [ruffle-rs/ruffle#13217] opened 2023-09-17 07:40 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.17.0/src/gles/device.rs:705:52
Error stack:
```
@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.9.17/core.ruffle.9c5a7b4eda2c5ccc5fca.js:1:51852
wasm-stub@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h2e7c106a4724653e]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h7601402c0a383194]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h6dad0405f48e39e2]@[wasm code]
<?>.wasm-function[core::result::unwrap_failed::h7ed8731a69ab17a3]@[wasm code]
<?>.wasm-function[<T as wgpu::context::DynContext>::device_create_texture::hb43ba48cf478821f]@[wasm code]
<?>.wasm-function[<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_shape::h457fa8b7dd7f0339]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h98998287b12b5518]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h76424d09d27f95aa]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h5f321403e3366fec]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hebecf572e4faf52e]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h929c75f3de6624fd]@[wasm code]
wasm-stub@[wasm code]
A@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.9.17/core.ruffle.9c5a7b4eda2c5ccc5fca.js:1:2957
f@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.9.17/core.ruffle.9c5a7b4eda2c5ccc5fca.js:1:2512
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Apple GPU"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ooooooooo.ooo/static/?07921a2f-26fd-4364-9671-ee0c8d256ec1
SWF URL: http://assets.ninjakiwi.com/Games/gameswfs/btd5-dat.swf?v=20190114

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-17
Channel: nightly
Built: 2023-09-17T00:20:34.351Z
Commit: 613c21a5d2d377acca9b7e71d74c64946646042e
Is extension: false

# Metadata
width: 800
height: 620
frameRate: 30
numFrames: 1
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 23943335

**Comment by danielhjacobs** [comment] 2023-11-08 20:30
Closing as a duplicate of #11642.

**Closed by danielhjacobs** 2023-11-08 20:30 UTC
Labels: error-report
