### ISSUE TITLE
Error on https://www.megaigry.ru/embed/jacksmith/

### ISSUE THREAD

**Issue by Ars-eniy-Cheis** [ruffle-rs/ruffle#14574] opened 2024-01-01 15:15 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096


    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://www.megaigry.ru/emulators/ruffle/core.ruffle.6fc895c6fd124c5b4d63.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a9ca1d4a3bb21ab (wasm://wasm/03416582:wasm-function[9884]:0x9d1f08)
    at std::panicking::rust_panic_with_hook::hbf46ef0245cc9589 (wasm://wasm/03416582:wasm-function[6322]:0x8c0b76)
    at core::panicking::panic_fmt::h14c85a61aa3d538e (wasm://wasm/03416582:wasm-function[9675]:0x9ccb54)
    at core::ops::function::Fn::call::h4b6d6d0f7f499988 (wasm://wasm/03416582:wasm-function[6586]:0x8d48fc)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::hfb1d00ba652d38ce (wasm://wasm/03416582:wasm-function[5381]:0x86deca)
    at wgpu::backend::direct::Context::handle_error::hb280a3b1a9fb213f (wasm://wasm/03416582:wasm-function[2796]:0x69557f)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h32d05104933a20c3 (wasm://wasm/03416582:wasm-function[9117]:0x9997a7)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h5849c72639513c1c (wasm://wasm/03416582:wasm-function[8616]:0x97a1a7)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::hb496ed93607c2768 (wasm://wasm/03416582:wasm-function[1947]:0x5828a6)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Adreno (TM) 640"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.megaigry.ru/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 12; M2102J20SG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.193 Mobile Safari/537.36 OPR/79.3.4195.76674
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-27
Channel: nightly
Built: 2023-12-27T00:14:54.557Z
Commit: 28a3c7178a805ddb7027d30738b0e58acf94147e
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by evilpie** [comment] 2024-02-16 14:21
Duplicate of #11591.

**Closed by evilpie** 2024-02-16 14:21 UTC
Labels: error-report
