### ISSUE TITLE
Error on http://3dtuning.stuner.net/indexflash.html

### ISSUE THREAD

**Issue by vdreschr** [ruffle-rs/ruffle#13215] opened 2023-09-17 04:14 UTC
# Error Info
Error name: Error
Error message: panicked at 'Unimplemented opcode LogicalAnd', render/naga-pixelbender/src/lib.rs:1315:29
Error stack:
```
Error: panicked at 'Unimplemented opcode LogicalAnd', render/naga-pixelbender/src/lib.rs:1315:29
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://pipjjbgofgieknlpefmcckdmgaaegban/dist/339.js:2406:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h81b6d13caa3cc4ad (wasm://wasm/0306a596:wasm-function[9275]:0x912ca4)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/0306a596:wasm-function[6027]:0x811d71)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/0306a596:wasm-function[9115]:0x90e37d)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::he174a2837920f619 (wasm://wasm/0306a596:wasm-function[7295]:0x886a8a)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::h55508e35c9660161 (wasm://wasm/0306a596:wasm-function[1139]:0x39baea)
    at ruffle_core::avm2::function::Executable::exec::h66c199093db9deaf (wasm://wasm/0306a596:wasm-function[792]:0x296dae)
    at ruffle_core::avm2::object::TObject::call_property::h4c672bd9ae68b84e (wasm://wasm/0306a596:wasm-function[1114]:0x38ba4a)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h05fca950c22f6289 (wasm://wasm/0306a596:wasm-function[2778]:0x622c1c)
    at ruffle_core::avm2::activation::Activation::run_actions::h65f656b485b30e84 (wasm://wasm/0306a596:wasm-function[518]:0x2a0d7)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at away3d.core.pick::PBPickingCollider()
    at away3d.core.pick::PickingColliderType$cinit()
    at global$init() [TU=away3d/core/pick/PickingColliderType]
    at Builder1/init()
    at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
    at Preloader/startup()
    at Preloader/progress()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Vega 8 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: Builder.swf
Param wmode: direct
Param allowFullscreen: true
Param allowFullScreenInteractive: true
Param scale: noScale
Param allowscriptaccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://3dtuning.stuner.net/indexflash.html
SWF URL: http://3dtuning.stuner.net/Builder.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-29
Channel: nightly
Built: 2023-08-29T00:21:45.895Z
Commit: 0ed447b42877b10fdaaf913015eb2783cd9afb04
Is extension: true

# Metadata
width: 1280
height: 720
frameRate: 60
numFrames: 2
swfVersion: 15
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2689943

**Comment by Lord-McSweeney** [comment] 2023-09-17 04:19
Duplicate of #13166.

**Closed by Lord-McSweeney** 2023-09-17 04:19 UTC
Labels: error-report
