### ISSUE TITLE
Error on https://www.disney--games.com/gameframe/338

### ISSUE THREAD

**Issue by 090RARU** [ruffle-rs/ruffle#10624] opened 2023-04-09 13:44 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/display_object/movie_clip.rs:2450:24

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.disney--games.com/gameframe/338
SWF URL: https://media.numuki.com/winnie-the-pooh/games/home-run-derby/home-run-derby.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Platform: MacIntel
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-09
Channel: nightly
Built: 2023-04-09T00:19:45.197Z
Commit: 6ad5c301884be7a4c8d4d751a89bbf16a6a5915d
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 40
numFrames: 57
swfVersion: 8
backgroundColor: #7DC247
isActionScript3: false
uncompressedLength: 4038802

**Comment by n0samu** [comment] 2024-06-23 23:28
Likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:28 UTC
Labels: error-report
