### ISSUE TITLE
Super Mario 63 freezes on first frame of title screen

### ISSUE THREAD

**Issue by GTcreyon** [ruffle-rs/ruffle#4690] opened 2021-06-26 19:56 UTC
**Describe the bug**
Game freezes on the first frame of the title screen (when the cutout star first appears).
Warning "Sound.position: Unimplemented" repeated in console.
Title screen music starts, but does not loop.
https://uploads.ungrounded.net/498000/498969_Super_Mario_63__2009_.swf?123

**Expected behavior**
Title screen should load, the cutout star expanding to reveal the whole title.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Experienced both on the self-hosted and desktop versions.

**What platform are you using?**
 - Windows (Desktop)
 - Firefox (Browser)

**Comment by GTcreyon** [comment] 2021-06-26 21:38
Correction, this only applies to the 2009 version of the game.
https://drive.google.com/file/d/12VYqCEPPerS9nwUKQyIKq1uFTL06zO5D/view

**Comment by e666666** [comment] 2021-07-02 05:55
Cannot reproduce on the latest version of Ruffle, are you sure you're running the latest version?

**Comment by GTcreyon** [comment] 2021-07-13 22:21
Positive. Are you sure you're using the 2009 version of sm63? :P

**Comment by Herschel** [comment] 2021-10-19 17:05
Can confirm the issue on the linked Google drive SWF.

**Comment by Toad06** [comment] 2022-01-20 14:47
The title screen now appears as it should in nightly-2021-10-18 and the most recent releases, assume fixed by #5482.

**Closed by Toad06** 2022-01-20 14:47 UTC
Labels: bug, avm1
