### ISSUE TITLE
Error on https://www.cooljuegos.com/embed/jacksmith/

### ISSUE THREAD

**Issue by PELONCITOMIR** [ruffle-rs/ruffle#14062] opened 2023-11-18 17:35 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/49d16f7/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096


    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://www.cooljuegos.com/emulators/ruffle/core.ruffle.9319559a195fae019006.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb1c47d692dbcedf6 (wasm://wasm/0336f48a:wasm-function[9803]:0x9b0c0a)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/0336f48a:wasm-function[6278]:0x89aea5)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/0336f48a:wasm-function[9603]:0x9aba14)
    at core::ops::function::Fn::call::h17b686c150d53841 (wasm://wasm/0336f48a:wasm-function[6532]:0x8b181b)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::hb300bc584d49798d (wasm://wasm/0336f48a:wasm-function[5335]:0x84a0c2)
    at wgpu::backend::direct::Context::handle_error::hc685e116ef8cc2a5 (wasm://wasm/0336f48a:wasm-function[2739]:0x671c20)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h709030e560456ed1 (wasm://wasm/0336f48a:wasm-function[9070]:0x97a013)
    at wgpu::CommandEncoder::copy_texture_to_buffer::he2ad44f5cab26c99 (wasm://wasm/0336f48a:wasm-function[8559]:0x95aa7b)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h8d75f2b39b5f3ae0 (wasm://wasm/0336f48a:wasm-function[1914]:0x564ace)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Qualcomm, Adreno (TM) 730, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.cooljuegos.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-17
Channel: nightly
Built: 2023-11-17T00:14:46.670Z
Commit: a78a67ee24a4a172e6fae0ce03979e63864270c6
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by evilpie** [comment] 2024-04-09 15:05
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:05 UTC
Labels: error-report
