### ISSUE TITLE
Error on https://r2cdn-encs.r2games.com/bin/WebLaucher.html

### ISSUE THREAD

**Issue by rincoreiys** [ruffle-rs/ruffle#9246] opened 2023-01-21 09:17 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:594:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:593:21)
    at std::sync::once::Once::call_once::{{closure}}::h5f93984c1300ca75 (wasm://wasm/0271e1fa:wasm-function[1570]:0x406c70)
    at std::sys_common::once::generic::Once::call::h8801249ea31ccf7a (wasm://wasm/0271e1fa:wasm-function[1972]:0x496bc0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::he904c54109aabe24 (wasm://wasm/0271e1fa:wasm-function[7080]:0x741ee1)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (wasm://wasm/0271e1fa:wasm-function[5005]:0x6a3060)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (wasm://wasm/0271e1fa:wasm-function[7400]:0x750c45)
    at core::option::expect_failed::hb1beef3e49ebedf1 (wasm://wasm/0271e1fa:wasm-function[8482]:0x77a4d7)
    at ruffle_core::display_object::stage::Stage::root_clip::hee2f08cf0070ee82 (wasm://wasm/0271e1fa:wasm-function[5017]:0x6a3a91)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h44874a6ce178e2c6 (wasm://wasm/0271e1fa:wasm-function[1654]:0x41ea35)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc90f0b2d91cfd44b (wasm://wasm/0271e1fa:wasm-function[959]:0x310788)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://r2cdn-encs.r2games.com/bin/WebLaucher.html?ost=http%3A%2F%2Fcs.r2games.com&fb=1&fc=1&userid=361234368&username=361234368&time=1674292634&flag=3a66795fe140d3f112c629047f91b53e&cm=1&server_id=S87&server_name=
SWF URL: https://r2cdn-encs.r2games.com/bin/WebLaucher.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-01-21
Channel: nightly
Built: 2023-01-21T00:18:03.514Z
Commit: 6d5f6385a5af17296598cf6c5eddb177263729c0
Is extension: true

# Metadata
width: 1000
height: 600
frameRate: 24
numFrames: 1
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 26568

**Comment by n0samu** [comment] 2023-01-22 01:40
Duplicate of #8203

**Closed by n0samu** 2023-01-22 01:40 UTC
Labels: duplicate, error-report
