### ISSUE TITLE
Error on https://incredibots.com/if/game.php

### ISSUE THREAD

**Issue by Redxtorm** [ruffle-rs/ruffle#13520] opened 2023-10-11 15:31 UTC
# Error Info
Error name: Error
Error message: panicked at 'Unable to get Object', /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/3669a35/flash-lso/src/amf3/read.rs:418:14

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, Radeon HD 3200 Graphics Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1000, height: 750, depth_or_array_layers: 1 }

# Page Info
Page URL: https://incredibots.com/if/game.php
SWF URL: https://incredibots.com/if/incredibots2.swf?1604326052

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-30
Channel: nightly
Built: 2023-09-30T00:20:30.366Z
Commit: f140e7a14b379993625b07524c4453ae98592384
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 104991

**Comment by Lord-McSweeney** [comment] 2023-10-22 05:55
Duplicate of #10520

**Closed by Lord-McSweeney** 2023-10-22 05:55 UTC
Labels: avm2, error-report
