### ISSUE TITLE
Error on https://flashthemes.net/movie/UFO7varQ65

### ISSUE THREAD

**Issue by TriangleTheObjectThingy** [ruffle-rs/ruffle#15909] opened 2024-04-07 14:56 UTC
I got this error while trying to load a flashthemes video with ruffle, how can i fix this problem?

# Error Info
Error name: Error
Error message: panicked at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys/pal/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
69/__wbg_get_imports/imports.wbg.__wbg_new_28c511d9baebfa89@moz-extension://605d858a-7cfa-4285-a1fb-a3baf78a202a/dist/69.js:3393:21
js_sys::Error::new::h8e593d55ccfdbc76@:wasm-function[13912]:0xb210a0
core::ops::function::FnOnce::call_once{{vtable.shim}}::hc1495a37ebcbc9dc@:wasm-function[11503]:0xacbc93
std::panicking::rust_panic_with_hook::h5ca5fd3b2064be1b@:wasm-function[7082]:0x99528d
core::panicking::panic_fmt::h2582bddf31c1c986@:wasm-function[11210]:0xac558f
core::panicking::assert_failed_inner::hf073d683243b665e@:wasm-function[4918]:0x881a44
core::panicking::assert_failed::ha3d8bcf705ea9fbe@:wasm-function[11252]:0xac6a4e
ruffle_core::loader::Loader::load_url_loader::{{closure}}::h5ecb66d5db9bc106@:wasm-function[2860]:0x6d88d9
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h252089a314bc9d7a@:wasm-function[1441]:0x4745d0
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h17b5e40182c3d9de@:wasm-function[4070]:0x801c1e
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hbb18db729b7a1df9@:wasm-function[12521]:0xaec7fc
closure8645 externref shim@:wasm-function[12833]:0xaf85c3
__wbg_adapter_91@moz-extension://605d858a-7cfa-4285-a1fb-a3baf78a202a/dist/69.js:324:10
real@moz-extension://605d858a-7cfa-4285-a1fb-a3baf78a202a/dist/69.js:281:20

```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, Radeon HD 3200 Graphics Direct3D11 vs_5_0 ps_5_0), or similar"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: low
Surface samples: 1
Surface size: (550, 400, 1)
Player type: Object
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param wmode: transparent
Param flashvars: movieOwner=&movieOwnerId=360&movieId=UFO7varQ65&movieLid=6&pwm=0&movieDesc=NOTE%253A%2520This%2520game%2520is%2520still%2520being%2520animated%2520in%2520progress%2520so%2520what%2520you%2520will%2520have%2520for%2520now%2520is%2520this%2520title%2520screen&userId=360&username=&uemail=&ut=-1&numContact=&apiserver=https%3A%2F%2Fflashthemes.net%2F&duration=53&playcount=1&thumbnailURL=%2Fmovie_thumbs%2Fthumb-UFO7varQ65.png&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=0&isInitFromExternal=0&isWide=1&appCode=go&is_slideshow=0&is_emessage=0&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D360%26p%3Dtrue&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=1&&&&isTemplate=0&showButtons=1&chain_mids=&averageRating=0&ratingCount=2&endStyle=0&showshare=false
Param movie: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/movie/UFO7varQ65
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-30
Channel: nightly
Built: 2024-03-30T00:05:09.123Z
Commit: d0e2483bc772d25c5eb7e6774392df44cfa3b88d
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment] 2024-05-12 21:35
Duplicate of #13974

**Closed by n0samu** 2024-05-12 21:35 UTC
Labels: duplicate, error-report
