### ISSUE TITLE
Error on https://h-flash.com/restraint-and-interrogation-princess-irene-eng/

### ISSUE THREAD

**Issue by SatansPowers** [ruffle-rs/ruffle#8544] opened 2022-11-14 02:51 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: min <= max', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/cmp.rs:869:9
Error stack:
```
Error: panicked at 'assertion failed: min <= max', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/cmp.rs:869:9
    at V.e.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/662.js:1:7320)
    at std::sync::once::Once::call_once::{{closure}}::hade171d180e8c1b3 (<anonymous>:wasm-function[1000]:0x2a9838)
    at std::sync::once::Once::call_inner::h34aee843864daceb (<anonymous>:wasm-function[1405]:0x332469)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b5ff8f72074c3e7 (<anonymous>:wasm-function[4900]:0x4b42ec)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (<anonymous>:wasm-function[3651]:0x4725fe)
    at core::panicking::panic_fmt::h751be80779d42b53 (<anonymous>:wasm-function[5131]:0x4bbe4e)
    at core::panicking::panic::h8af046397a2bf65d (<anonymous>:wasm-function[4953]:0x4b51cf)
    at ruffle_core::player::Player::update_drag::h8974fc571820e60c (<anonymous>:wasm-function[2113]:0x3d2c88)
    at ruffle_web::Ruffle::tick::h888878a53ecfea0c (<anonymous>:wasm-function[584]:0x1d9719)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h4aa053802fae5111 (<anonymous>:wasm-function[5969]:0x4cfd76)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://h-flash.com/restraint-and-interrogation-princess-irene-eng/
SWF URL: https://h-flash.com/data/swf/data/jsk-studio/princess-irene-eng/irene-eng.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 13982.88.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.162 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-12
Channel: nightly
Built: 2022-11-12T00:15:57.157Z
Commit: 08270efee72ab8fe31b1448d76bcda09c8af264e
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 162
swfVersion: 10
backgroundColor: #999999
isActionScript3: true
uncompressedLength: 18870816

**Comment by n0samu** [comment] 2022-11-14 02:55
Duplicate of #8382

**Closed by n0samu** 2022-11-14 02:55 UTC
Labels: duplicate, error-report
