### ISSUE TITLE
Error on https://frivold.menu/public/files/mini-dash

### ISSUE THREAD

**Issue by Geoross** [ruffle-rs/ruffle#13017] opened 2023-08-30 20:23 UTC
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.0b7b3fa0b12148fa5c11.js:1:51650)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h81b6d13caa3cc4ad (wasm://wasm/0306a596:wasm-function[9275]:0x912ca4)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/0306a596:wasm-function[6027]:0x811d71)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/0306a596:wasm-function[9115]:0x90e34f)
    at alloc::raw_vec::capacity_overflow::h69391d2b6a90e408 (wasm://wasm/0306a596:wasm-function[9114]:0x90e25f)
    at alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h306619e1271e742a (wasm://wasm/0306a596:wasm-function[5911]:0x804aa8)
    at ruffle_core::avm2::globals::flash::utils::byte_array::set_length::h3afa9a85d2c76c19 (wasm://wasm/0306a596:wasm-function[3390]:0x6a7933)
    at ruffle_core::avm2::function::Executable::exec::h66c199093db9deaf (wasm://wasm/0306a596:wasm-function[792]:0x296dae)
    at ruffle_core::avm2::object::TObject::call_method::hef35c02509016556 (wasm://wasm/0306a596:wasm-function[1999]:0x538511)
    at ruffle_core::avm2::object::TObject::set_property::hf56cffa3ec106240 (wasm://wasm/0306a596:wasm-function[2318]:0x59ebad)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::length()
    at global/F_avm2_casRamLength()
    at global/F___sys_mmap()
    at global/F_mmap()
    at global/F_pages_map()
    at global/F_base_pages_alloc()
    at global/F_base_alloc()
    at global/F_arenas_extend()
    at global/F_malloc_init()
    at global/F_malloc()
    at global/F__Znwj()
    at global/F__Z16CreateGameObjectv()
    at global/F_main()
    at global/F__start1()
    at com.adobe.flascc::CModule$/callI()
    at com.adobe.flascc::CModule$/start()
    at com.adobe.flascc::CModule$/startAsync()
    at com.adobe.flascc::Console/enterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3050 Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://frivold.menu/public/files/mini-dash
SWF URL: https://frivold.menu/public/storage/games/November2021/QD21VEcY10LnXC2ISIAK.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-29
Channel: nightly
Built: 2023-08-29T00:21:45.895Z
Commit: 0ed447b42877b10fdaaf913015eb2783cd9afb04
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 0.1171875
numFrames: 1
swfVersion: 18
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 20666034

**Comment by n0samu** [comment] 2023-08-30 21:35
Duplicate of #10851

**Closed by n0samu** 2023-08-30 21:35 UTC
Labels: duplicate, error-report
