### ISSUE TITLE
its not working 

### ISSUE THREAD

**Issue by ghostfacegfg767** [ruffle-rs/ruffle#4382] opened 2021-05-21 13:12 UTC
**Describe the bug**
Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
If this is an issue with a specific SWF file, please provide a link to the SWF file, or you can attach the SWF by zipping it and dragging it onto the issue box.
If this is a visual issue, please attach a screenshot of the problem.

**Expected behavior**

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 - If you're using the web version, please list the OS, browser, and mobile device (if applicable).
[https://www.coolmathgames.com/0-learn-to-fly-3](url)

**Comment by danielhjacobs** [comment] 2021-05-26 00:23
https://www.coolmathgames.com/sites/cmatgame/files/games/learntofly3storefix.swf runs using AS3 and does not work. See #1368. That's why coolmathgames doesn't even bother to try to load it on https://www.coolmathgames.com/0-learn-to-fly-3.

That's why Ruffle warns you "This content is not yet supported by the Ruffle emulator and will likely not run as intended."

**Comment by n0samu** [comment] 2023-01-04 22:13
Note: the correct link as of now is https://www.coolmath-games.com/sites/cmatgame/files/games/learntofly3storefix.swf
Closing in favor of #7067 (same issue)

**Closed by n0samu** 2023-01-04 22:13 UTC
Labels: bug
