### ISSUE TITLE
Error on https://www.gameflare.com/embed/mr-vengeance-act-2/

### ISSUE THREAD

**Issue by Mihajlix09** [ruffle-rs/ruffle#14517] opened 2023-12-25 19:54 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/shader_data.rs:72:10:
Failed to compile PixelBender shader: Unimplemented("compile_pixelbender_shader")
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/shader_data.rs:72:10:
Failed to compile PixelBender shader: Unimplemented("compile_pixelbender_shader")
    at N.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://www.gameflare.com/emulators/ruffle/core.ruffle.a1043200738d35ef0737.js:1:58706)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h643031ddb85c668c (wasm://wasm/0350d03e:wasm-function[9904]:0xa1f769)
    at std::panicking::rust_panic_with_hook::hbf46ef0245cc9589 (wasm://wasm/0350d03e:wasm-function[6386]:0x8fdb1e)
    at core::panicking::panic_fmt::h14c85a61aa3d538e (wasm://wasm/0350d03e:wasm-function[9700]:0xa1a33f)
    at core::result::unwrap_failed::hc368cb5845aa399d (wasm://wasm/0350d03e:wasm-function[7693]:0x96d842)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::hc6102c680304574c (wasm://wasm/0350d03e:wasm-function[758]:0x28f3b6)
    at ruffle_core::avm2::function::Executable::exec::h256c0c4a1cfdb4cd (wasm://wasm/0350d03e:wasm-function[789]:0x2c77f7)
    at ruffle_core::avm2::object::TObject::call_property::h08476ee9d2fb298d (wasm://wasm/0350d03e:wasm-function[1334]:0x49fd63)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h177e0ec68fabedc8 (wasm://wasm/0350d03e:wasm-function[2933]:0x6f11dd)
    at ruffle_core::avm2::activation::Activation::run_actions::h3cac844649cfafe8 (wasm://wasm/0350d03e:wasm-function[569]:0x3de30)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at as_files::Filter$/outLining()
    at as_files::LevelBackground()
    at level_1_background()
    at flash.display::DisplayObject/flash.display::DisplayObject()
    at flash.display::InteractiveObject/flash.display::InteractiveObject()
    at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
    at flash.display::Sprite()
    at flash.display::MovieClip()
    at as_files::Level()
    at level_1()
    at flash.display::DisplayObject/flash.display::DisplayObject()
    at flash.display::InteractiveObject/flash.display::InteractiveObject()
    at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
    at flash.display::Sprite()
    at flash.display::MovieClip()
    at as_files::LayerLevel()
    at as_files::Game$/createLayers()
    at as_files::Game()
    at flash.display::MovieClip/flash::display::MovieClip::nextFrame()
    at as_files::Menu/nextGame()
    at as_files::Menu/update()
    at as_files::Menu/enter_frame()
```

# Player Info
Allows script access: false
Renderer: WebGL 1.0
Adapter Vendor: WebKit
Adapter Renderer: WebKit WebGL
Adapter Version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Surface samples: 1 x 
Surface size: 300 x 150

# Page Info
Page URL: https://www.gameflare.com/embed/mr-vengeance-act-2/
SWF URL: https://data.gameflare.com/games/2268/BefnvMvOrywSqR.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-21
Channel: nightly
Built: 2023-12-21T00:16:02.610Z
Commit: a5560587da4a9816a5c36cd93671f3d62550f004
Is extension: false

# Metadata
width: 800
height: 400
frameRate: 24
numFrames: 5
swfVersion: 10
backgroundColor: #CCCCCC
isActionScript3: true
uncompressedLength: 22198035

**Comment by Mihajlix09** [comment] 2023-12-25 19:55
cc

**Comment by Mihajlix09** [comment] 2023-12-25 19:55
cc

**Comment by Mihajlix09** [comment] 2023-12-25 19:55
ccc

**Comment by Mihajlix09** [comment] 2023-12-25 19:55
cccccccc

**Comment by Mihajlix09** [comment] 2023-12-25 19:55
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

**Comment by torokati44** [comment] 2023-12-25 20:00
Duplicate of https://github.com/ruffle-rs/ruffle/issues/14394.

**Closed by torokati44** 2023-12-25 20:00 UTC
Labels: error-report
