### ISSUE TITLE
Error on http://sonic.sega.jp/riders/ShootingStarStory/

### ISSUE THREAD

**Issue by BlazingRush** [ruffle-rs/ruffle#15936] opened 2024-04-09 08:11 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/string/repr.rs:43:22:
string indices out of bounds
Error stack:
```
69/__wbg_get_imports/imports.wbg.__wbg_new_28c511d9baebfa89@moz-extension://e8c1daee-2c51-4f67-b41d-37cc55d29f51/dist/69.js:3393:21
js_sys::Error::new::h8e593d55ccfdbc76@:wasm-function[13912]:0xb210a0
core::ops::function::FnOnce::call_once{{vtable.shim}}::hc1495a37ebcbc9dc@:wasm-function[11503]:0xacbc93
std::panicking::rust_panic_with_hook::h5ca5fd3b2064be1b@:wasm-function[7082]:0x99528d
core::panicking::panic_fmt::h2582bddf31c1c986@:wasm-function[11210]:0xac558f
core::option::expect_failed::h7996a6a7be71bb45@:wasm-function[9776]:0xa6a19d
ruffle_core::string::interner::AvmStringInterner::substring::h5a1df168fbb9606f@:wasm-function[6602]:0x970497
ruffle_core::avm2::globals::string::substr::hd181af8e3fddcae6@:wasm-function[2744]:0x6b3bfc
ruffle_core::avm2::function::Executable::exec::h7cd3365831833e86@:wasm-function[1047]:0x313652
ruffle_core::avm2::object::TObject::call_property::h97c1c92f643a76f9@:wasm-function[1512]:0x4950c3
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h7209d4f9339b29d2@:wasm-function[3132]:0x724c34
ruffle_core::avm2::activation::Activation::run_actions::h17d688ff337292c8@:wasm-function[736]:0x3a157
ruffle_core::avm2::function::Executable::exec::h7cd3365831833e86@:wasm-function[1047]:0x3131af
ruffle_core::avm2::object::TObject::call_property::h4ecb2a8e0dfb37ee@:wasm-function[1544]:0x4a3c43
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h7209d4f9339b29d2@:wasm-function[3132]:0x724c12
ruffle_core::avm2::activation::Activation::run_actions::h17d688ff337292c8@:wasm-function[736]:0x3a157
ruffle_core::avm2::function::Executable::exec::h7cd3365831833e86@:wasm-function[1047]:0x3131af
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h09d6182d0baa560a@:wasm-function[1220]:0x3c9e0a
ruffle_core::avm2::events::dispatch_event_to_target::h8aac957264a8ad32@:wasm-function[1247]:0x3e4a7a
ruffle_core::avm2::events::dispatch_event::h856d87540917a8f7@:wasm-function[1488]:0x48b18d
ruffle_core::avm2::Avm2::broadcast_event::hafdfe31c04be4b79@:wasm-function[939]:0x27b41e
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::enter_frame::h001257e9318413ad@:wasm-function[4612]:0x85597d
ruffle_web::Ruffle::tick::h93e4d92ee52e5adc@:wasm-function[1097]:0x3487a5
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h1443c262b0dd0aa2@:wasm-function[13838]:0xb2083c
wasm_bindgen::convert::closures::invoke1_mut::h2b56c3da3f3c25e4@:wasm-function[12463]:0xaec0c7
__wbg_adapter_63@moz-extension://e8c1daee-2c51-4f67-b41d-37cc55d29f51/dist/69.js:300:10
real@moz-extension://e8c1daee-2c51-4f67-b41d-37cc55d29f51/dist/69.js:281:20

```
AVM2 stack:
```
    at String/substr()
    at myAS::textAnimation/randomTxtFnc()
    at myAS::textAnimation/textChange()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0), or similar"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: http://sonic.sega.jp/riders/ShootingStarStory/
SWF URL: http://sonic.sega.jp/riders/ShootingStarStory/swf/top.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-30
Channel: nightly
Built: 2024-03-30T00:05:09.123Z
Commit: d0e2483bc772d25c5eb7e6774392df44cfa3b88d
Is extension: true

# Metadata
width: 800
height: 720
frameRate: 26
numFrames: 177
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 415645

**Comment by n0samu** [comment] 2024-07-11 22:17
Duplicate of #15602

**Closed by n0samu** 2024-07-11 22:17 UTC
Labels: duplicate, error-report
