### ISSUE TITLE
Error on https://www.friv.cm/electricman-2/

### ISSUE THREAD

**Issue by fifa19forever** [ruffle-rs/ruffle#6505] opened 2022-03-22 12:57 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.friv.cm/ruffle/core.ruffle.08124f6dd5c7e72ca855.js:1:6964)
    at std::sync::once::Once::call_once::{{closure}}::h4dcb78b97de78bcf (https://www.friv.cm/ruffle/f91bedccc781eba86e58.wasm:wasm-function[1019]:0x2f8ef2)
    at std::sync::once::Once::call_inner::h9279eef47cf85b81 (https://www.friv.cm/ruffle/f91bedccc781eba86e58.wasm:wasm-function[1157]:0x32aaba)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7e6cf7c840665392 (https://www.friv.cm/ruffle/f91bedccc781eba86e58.wasm:wasm-function[4721]:0x4d76d9)
    at std::panicking::rust_panic_with_hook::h47a0e203360b6c10 (https://www.friv.cm/ruffle/f91bedccc781eba86e58.wasm:wasm-function[3188]:0x482726)
    at core::panicking::panic_fmt::h4ca53049f45e3264 (https://www.friv.cm/ruffle/f91bedccc781eba86e58.wasm:wasm-function[4992]:0x4e3325)
    at core::panicking::panic::h35778e3c18266c93 (https://www.friv.cm/ruffle/f91bedccc781eba86e58.wasm:wasm-function[4718]:0x4d7200)
    at core::ops::function::FnOnce::call_once::h63635e87c343a6bd (https://www.friv.cm/ruffle/f91bedccc781eba86e58.wasm:wasm-function[1058]:0x3101d5)
    at ruffle_core::avm1::function::Executable::exec::h01bdca74588653f1 (https://www.friv.cm/ruffle/f91bedccc781eba86e58.wasm:wasm-function[395]:0x146ca3)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hd2ac2ca7aecc5e6d (https://www.friv.cm/ruffle/f91bedccc781eba86e58.wasm:wasm-function[381]:0x10c8d5)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.friv.cm/electricman-2/
SWF URL: https://www.friv.cm/wp-content/games/electricman-2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14469.41.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.57 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-26
Channel: nightly
Built: 2022-01-26T00:18:09.413Z
Commit: d5986a72947f5552b29805e3971ce58939fdd1a2
Is extension: false

**Comment by relrelb** [comment] 2022-03-22 20:34
Duplicate of #4932.

**Closed by relrelb** 2022-03-22 20:34 UTC
Labels: error-report
