### ISSUE TITLE
Error on https://s15.4399.com/4399swf/upload_swf/ftp29/haibo/suwei/y1/jifen3.htm

### ISSUE THREAD

**Issue by shenming77** [ruffle-rs/ruffle#12045] opened 2023-07-14 08:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
Error stack:
```
Error: panicked at 'No script object for display object', core/src/avm1/activation.rs:404:18
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1fb1bf8fc190c8e7 (wasm://wasm/02e582f2:wasm-function[9034]:0x8a07a6)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02e582f2:wasm-function[5991]:0x7ab2bb)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02e582f2:wasm-function[8879]:0x89bf97)
    at ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::hb81395e440233c58 (wasm://wasm/02e582f2:wasm-function[3561]:0x67db4f)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::h278bfd02dad17641 (wasm://wasm/02e582f2:wasm-function[3033]:0x61e161)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h4f165481cbbd1c45 (wasm://wasm/02e582f2:wasm-function[1013]:0x35feee)
    at ruffle_core::display_object::movie_clip::MovieClip::place_object::hcddd18755f94add0 (wasm://wasm/02e582f2:wasm-function[1727]:0x4a1667)
    at <ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h15ad50a5b15ea99b (wasm://wasm/02e582f2:wasm-function[807]:0x2c2bbf)
    at ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h4f165481cbbd1c45 (wasm://wasm/02e582f2:wasm-function[1013]:0x35ff29)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://s15.4399.com/4399swf/upload_swf/ftp29/haibo/suwei/y1/jifen3.htm
SWF URL: https://s15.4399.com/4399swf/upload_swf/ftp29/haibo/suwei/y1/main.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-13
Channel: nightly
Built: 2023-07-13T00:20:50.346Z
Commit: e0886707c5b9637c3fb6d3064a6ffd2cb28117de
Is extension: true

# Metadata
width: 600
height: 400
frameRate: 30
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 8586952

**Comment by Lord-McSweeney** [comment] 2024-01-30 20:39
Duplicate of #10936

**Closed by Lord-McSweeney** 2024-01-30 20:39 UTC
Labels: error-report
