### ISSUE TITLE
Error on https://shsgames.github.io/g/9c623170/duck-life-3

### ISSUE THREAD

**Issue by Caitythecat** [ruffle-rs/ruffle#7092] opened 2022-05-26 04:10 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 0 but the index is 0', core/src/shape_utils.rs:306:13
Error stack:
```
@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.26/core.ruffle.37f7f47076c9eae53f28.js:1:7033
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h2b3586a1c348e776]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h8a142b2dcc139875]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h0e8f59b7c29e471d]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::he2a025723e105e28]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hb02133958c1e7d35]@[wasm code]
<?>.wasm-function[core::panicking::panic_bounds_check::heb9b88ec73713bda]@[wasm code]
<?>.wasm-function[ruffle_core::shape_utils::ActivePath::flush_fill::h6288d0f4cb03f5c9]@[wasm code]
<?>.wasm-function[ruffle_core::shape_utils::ShapeConverter::flush_layer::h557ae587a67b3066]@[wasm code]
<?>.wasm-function[<ruffle_core::shape_utils::DistilledShape as core::convert::From<&swf::types::Shape>>::from::hae13b268443b0fb0]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h7cfb9c64e8cca9dd]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::hb3a1bdecfc6db20b]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::had73e26d3eec21f2]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8cc0565ce3b05513]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7f0b3da3c15b2497]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::hf6f8e75dc21a5b85]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6fb2540f55cb3894]@[wasm code]
wasm-stub@[native code]
L@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.26/core.ruffle.37f7f47076c9eae53f28.js:1:3966
c@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.26/core.ruffle.37f7f47076c9eae53f28.js:1:2491
promiseReactionJob@[native code]
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/duck-life-3.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://shsgames.github.io/g/9c623170/duck-life-3
SWF URL: https://cdn.jsdelivr.net/gh/JoshMerlino/shsg-pfile/games/duck-life-3.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-26
Channel: nightly
Built: 2022-05-26T00:18:28.438Z
Commit: 811af340c3631ebe10b319fa09a1d969848857d4
Is extension: false

**Comment by n0samu** [comment] 2022-05-26 04:14
If you're on an iPad, you should update it to iOS 15.5! It will probably fix the issue you're experiencing.

**Comment by n0samu** [comment] 2024-06-23 23:32
Closing as likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:32 UTC
Labels: error-report
