### ISSUE TITLE
Error on https://www.tokoyun.com/elektrik-adam-2.html

### ISSUE THREAD

**Issue by SavunOski** [ruffle-rs/ruffle#7294] opened 2022-06-25 10:15 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:822:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:822:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7022)
    at std::sync::once::Once::call_once::{{closure}}::h99379cdb18af2fe8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/55bd20f9a20878cbbcee.wasm:wasm-function[1185]:0x2ab59e)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/55bd20f9a20878cbbcee.wasm:wasm-function[1384]:0x2e3095)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h723fc485ccaf3ac8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/55bd20f9a20878cbbcee.wasm:wasm-function[4666]:0x4283a9)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/55bd20f9a20878cbbcee.wasm:wasm-function[3086]:0x3cd83c)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/55bd20f9a20878cbbcee.wasm:wasm-function[4848]:0x42e4de)
    at core::panicking::panic::hc28e7cc2aa792341 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/55bd20f9a20878cbbcee.wasm:wasm-function[4759]:0x42a403)
    at core::ops::function::FnOnce::call_once::h2863cd6b578a62e6 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/55bd20f9a20878cbbcee.wasm:wasm-function[1030]:0x282c86)
    at ruffle_core::avm1::function::Executable::exec::hc9d60fef35ba3746 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/55bd20f9a20878cbbcee.wasm:wasm-function[368]:0xf6d0c)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h20202ca7f9fcf4a8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/55bd20f9a20878cbbcee.wasm:wasm-function[361]:0xe7427)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.tokoyun.com/elektrik-adam-2.html?oyun=oyna
SWF URL: https://www.tokoyun.com/dosya/swf/elektrik-adam-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-25
Channel: nightly
Built: 2022-06-25T00:14:23.491Z
Commit: 53cdba96d3a741792dd0e17fa18e95f85e3ad226
Is extension: true
# Additional Notes
the game bugs out, characters dont get deleted after the tutorial and the second half of the tutorial skips itself.
loading a game file from a save code will not work.
trying to launch any fight will cause a "major issue" within 6 seconds.

**Comment by relrelb** [comment] 2022-06-25 10:38
Duplicate of #4932.

**Closed by relrelb** 2022-06-25 10:38 UTC
Labels: error-report
