### ISSUE TITLE
Error on https://gamegogo.co.kr/bbs/board.php

### ISSUE THREAD

**Issue by Kiiuoooj** [ruffle-rs/ruffle#7085] opened 2022-05-25 02:20 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/display_object/bitmap.rs:194:28
Error stack:
```
@https://gamegogo.co.kr/ruffle/core.ruffle.7ec90db4764c20d13586.js:1:6973
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::ha69306374a0d7c42]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h9279eef47cf85b81]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hd4ed35f37e0c71aa]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h47a0e203360b6c10]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h4ca53049f45e3264]@[wasm code]
<?>.wasm-function[core::result::unwrap_failed::h6d050dbd00b66340]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::set_prev_avm1_clip::h7e6ae1e4ffe9b85c]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::he9f9c79a3f561482]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h466717537c66ebc6]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h827399ce0eead02e]@[wasm code]
wasm-stub@[native code]
R@https://gamegogo.co.kr/ruffle/core.ruffle.7ec90db4764c20d13586.js:1:3079
c@https://gamegogo.co.kr/ruffle/core.ruffle.7ec90db4764c20d13586.js:1:2522
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://gamegogo.co.kr/bbs/board.php?bo_table=game_hangame&wr_id=18
SWF URL: https://gamegogo.co.kr/ruffle/%EA%B3%A0%EA%B5%B0%EB%B6%84%ED%88%AC%20-%20%EC%B6%94%EC%96%B5%EC%9D%98%20%ED%95%9C%EA%B2%8C%EC%9E%84%ED%94%8C%EB%9E%98%EC%8B%9C.swf

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/605.1 NAVER(inapp; search; 1010; 11.12.1; 13)
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-22
Channel: nightly
Built: 2022-02-22T00:17:24.523Z
Commit: ff3aadd13486f34df1303a014592c39769e15eda
Is extension: false

**Comment by n0samu** [comment] 2022-05-25 03:33
Duplicate of #6608. Updating your device to iOS 15.5 should fix the issue!

**Closed by n0samu** 2022-05-25 03:33 UTC
Labels: error-report
