### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by Siblie** [ruffle-rs/ruffle#8123] opened 2022-09-29 13:36 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:6845)
    at std::sync::once::Once::call_once::{{closure}}::h73fc39b54ec29717 (wasm://wasm/017e8b06:wasm-function[1021]:0x2a382a)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017e8b06:wasm-function[1486]:0x3273a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d648d6ec080e3d2 (wasm://wasm/017e8b06:wasm-function[4920]:0x484684)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017e8b06:wasm-function[3620]:0x4413e8)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017e8b06:wasm-function[5073]:0x487aa7)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/017e8b06:wasm-function[4976]:0x485640)
    at core::ops::function::FnOnce::call_once::hc23e58910edbda0c (wasm://wasm/017e8b06:wasm-function[1113]:0x2c2f02)
    at ruffle_core::avm1::function::Executable::exec::ha1ebff59d66588d4 (wasm://wasm/017e8b06:wasm-function[364]:0xf1f99)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h6e117415f5d8a106 (wasm://wasm/017e8b06:wasm-function[491]:0x196711)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Ffarm.maxgames.com%2Felectricman2_maxgamesMTU5.swf
SWF URL: https://farm.maxgames.com/electricman2_maxgamesMTU5.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.117 (Edition std-1)
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-29
Channel: nightly
Built: 2022-09-29T00:19:25.847Z
Commit: 8f72842b2f186c4098ff277c510af41272d14377
Is extension: true

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3641749

**Comment by n0samu** [comment] 2022-09-30 11:18
Duplicate of #4932

**Closed by n0samu** 2022-09-30 11:18 UTC
Labels: duplicate, error-report
