### ISSUE TITLE
Error on https://echoesgame.com/play.html

### ISSUE THREAD

**Issue by KarstonKellar** [ruffle-rs/ruffle#16396] opened 2024-05-21 04:02 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.0/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_texture
    Copy of X 0..252 would end up overrunning the bounds of the Destination texture of X size 250

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.0/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_texture
    Copy of X 0..252 would end up overrunning the bounds of the Destination texture of X size 250


    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3429:21)
    at ruffle_web.wasm.js_sys::Error::new::h69c04334b4f73f11 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[12748]:0x9f83e5)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::he3ea582d6a7092c3 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[10505]:0x9b1d80)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[6525]:0x8771d0)
    at ruffle_web.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[10254]:0x9aa9df)
    at ruffle_web.wasm.core::ops::function::Fn::call::h4189ec14fc51b2a7 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[7484]:0x8bb7e8)
    at ruffle_web.wasm.wgpu::backend::wgpu_core::ContextWgpuCore::handle_error::h23f6904a4975d287 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[2148]:0x55a9b5)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::queue_write_texture::h1a7c972a78ee7a5d (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[9621]:0x973710)
    at ruffle_web.wasm.wgpu::Queue::write_texture::ha04b2224fb783ed7 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[10039]:0x999f6b)
    at ruffle_web.wasm.<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::update_texture::hc832b69acf68cb79 (wasm://wasm/ruffle_web.wasm-03383efe:wasm-function[2487]:0x5d1503)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::applyFilter()
    at _-NR/_-fr()
    at _-NR/_-K4()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at _-I7/_-8A()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 970 (0x000013C2) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: dl/echoes_act1_12_secure.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://echoesgame.com/play.html
SWF URL: https://echoesgame.com/dl/echoes_act1_12_secure.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-05-21
Channel: nightly
Built: 2024-05-21T00:06:02.596Z
Commit: d8b8ffa4f3f37d266e3def3325c5a20147aa1eed
Is extension: true

# Metadata
width: 800
height: 500
frameRate: 30
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 65066008

**Comment by n0samu** [comment] 2024-09-22 07:11
Duplicate of #10549

**Closed by n0samu** 2024-09-22 07:11 UTC
Labels: duplicate, render-wgpu, error-report
