### ISSUE TITLE
Error on https://game161852.konggames.com/games/BerzerkStudio/berzerk-ball-2/frame/348e1474-55d4-4377-8d8e-fbce11496da9/

### ISSUE THREAD

**Issue by Intless** [ruffle-rs/ruffle#12241] opened 2023-07-22 22:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'Missing method for id 8', core/src/avm2/globals/flash/utils.rs:430:44
Error stack:
```
Error: panicked at 'Missing method for id 8', core/src/avm2/globals/flash/utils.rs:430:44
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.910932826a9e894fa2ba.js:1:51547)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb515a2c9ffd29eb6 (wasm://wasm/02f2fb6e:wasm-function[9095]:0x8d153a)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02f2fb6e:wasm-function[5945]:0x7d3756)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02f2fb6e:wasm-function[8939]:0x8cca49)
    at ruffle_core::avm2::globals::flash::utils::describe_internal_body::h2467e80d75c10e5c (wasm://wasm/02f2fb6e:wasm-function[583]:0x145eb0)
    at ruffle_core::avm2::globals::flash::utils::describe_type::h133663ff43554f17 (wasm://wasm/02f2fb6e:wasm-function[1017]:0x33e276)
    at ruffle_core::avm2::function::Executable::exec::h70afbd0b721055f5 (wasm://wasm/02f2fb6e:wasm-function[822]:0x2a3f53)
    at ruffle_core::avm2::object::TObject::call_property::h8b0fb9294ce532a8 (wasm://wasm/02f2fb6e:wasm-function[1116]:0x382389)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::hdd0c032051093e63 (wasm://wasm/02f2fb6e:wasm-function[2768]:0x5f58e7)
    at ruffle_core::avm2::activation::Activation::run_actions::h82da41ed664c205b (wasm://wasm/02f2fb6e:wasm-function[517]:0x2a013)
```
AVM2 stack:
```
    at global/flash.utils::describeType()
    at com.lachhhEngine.multilingual::TextFactory/BuildTextDictFromClass()
    at com.lachhhEngine.multilingual::TextFactory/BuildTextDict()
    at com.lachhhEngine.multilingual::TextFactory/Init()
    at com.berzerkball2.multilingual::BB2_TextFactory/Init()
    at com.lachhhEngine.multilingual::TextFactory$/CreateInstance()
    at com.berzerkball2::Main/CreateManagers()
    at com.lachhhEngine.games::MainGame/Init()
    at com.berzerkball2::Main/Init()
    at com.lachhhEngine.initializers::Initializer/StartMain()
    at com.lachhhEngine.initializers::Initializer/PreloaderEnded()
    at Function/apply()
    at com.lachhhEngine.io::Callback/DoCallback()
    at com.berzerkball2.init::BB2_Bubblebox_Preloader/FinishScreen()
    at com.berzerkball2.init::BB2_Bubblebox_Preloader/onEnterFrame()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game161852.konggames.com/games/BerzerkStudio/berzerk-ball-2/frame/348e1474-55d4-4377-8d8e-fbce11496da9/?kongregate_host=www.kongregate.com
SWF URL: https://game161852.konggames.com/gamez/0016/1852/live/bb2_viral.swf?kongregate_game_version=1373574552

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-22
Channel: nightly
Built: 2023-07-22T00:19:38.712Z
Commit: 77c0dac64be338500e8dbba1d8ad37d13a10cb5b
Is extension: false

# Metadata
width: 720
height: 480
frameRate: 36
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 15361611

**Comment by danielhjacobs** [comment] 2024-07-15 14:42
Duplicate of #12227

**Closed by danielhjacobs** 2024-07-15 14:42 UTC
Labels: error-report
