### ISSUE TITLE
Error on https://games.crazygames.com/en_US/electric-man/index.html

### ISSUE THREAD

**Issue by Clari-7744** [ruffle-rs/ruffle#5835] opened 2021-12-10 03:51 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://files.crazygames.com/gameframe/ruffle/2021-11-10/ruffle.js:1:7036)
    at std::sync::once::Once::call_once::{{closure}}::h5387044f596cf17b (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[1005]:0x2eb276)
    at std::sync::once::Once::call_inner::h02a6489b0ecfb269 (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[1332]:0x359e9c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h4461033b8c8249d8 (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[4621]:0x4eb4fa)
    at std::panicking::rust_panic_with_hook::h364974e717ed59ec (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[3277]:0x4a4ff4)
    at rust_begin_unwind (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[4683]:0x4ed7dc)
    at core::panicking::panic_fmt::hf69c8b08bc9d2ee5 (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[4883]:0x4f82df)
    at core::panicking::panic::hceae0c79b0247f98 (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[4617]:0x4ead2b)
    at core::ops::function::FnOnce::call_once::hf99a08a7a8d58165 (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[1045]:0x3051b4)
    at ruffle_core::avm1::function::Executable::exec::hc98df77004cccb4f (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[417]:0x15a878)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hd54e711e872a6cb0 (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[467]:0x18ce4e)
    at ruffle_core::avm1::activation::Activation::do_action::hed5e972d1d5793d1 (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[307]:0xd919)
    at ruffle_core::avm1::activation::Activation::run_actions::hbd49380c63f80bad (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[2898]:0x4833a2)
    at ruffle_core::avm1::Avm1::run_stack_frame_for_action::h12ba0701eef6f7ca (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[1148]:0x323b42)
    at ruffle_core::player::Player::run_actions::h3145541b8433fcd8 (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[449]:0x17afc3)
    at ruffle_web::Ruffle::tick::hab8e68f7d94d56cd (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[589]:0x1edd3c)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h3513e9d35b376a3d (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[5427]:0x5047f7)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6de037ab70d733f6 (https://files.crazygames.com/gameframe/ruffle/2021-11-10/fbf1f4bcf4f4c884f34b.wasm:wasm-function[5024]:0x4fa2cb)
    at I (https://files.crazygames.com/gameframe/ruffle/2021-11-10/ruffle.js:1:3421)
    at a (https://files.crazygames.com/gameframe/ruffle/2021-11-10/ruffle.js:1:2531)
    at r (https://gameframe.crazygames.com/crazygames-gameframe-v1.bundle.js:2:62408)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.crazygames.com/en_US/electric-man/index.html
SWF URL: https://files.crazygames.com/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-10
Channel: nightly
Built: 2021-11-10T00:14:29.631Z
Commit: 51af0f708f2db85188ffcf7b744eb7f7cb76fd79
Is extension: false

**Comment by relrelb** [comment] 2021-12-10 08:12
Duplicate of #4932.

**Closed by relrelb** 2021-12-10 08:12 UTC
Labels: duplicate, error-report
