### ISSUE TITLE
Error on https://www.bcae1.com/switchingpowersupplydesign/switchingpowersupplytut01.htm

### ISSUE THREAD

**Issue by wekxller** [ruffle-rs/ruffle#9524] opened 2023-02-11 23:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://gcmgaphlohnhdgfbefpphkhnaijglnci/dist/ruffle.js?id=42994842112:1:6803)
    at std::sync::once::Once::call_once::{{closure}}::hf7c73d58e4b9dc97 (chrome-extension://gcmgaphlohnhdgfbefpphkhnaijglnci/dist/0cd49685d80f76e20307.wasm:wasm-function[1026]:0x2c1bab)
    at std::sync::once::Once::call_inner::hc44ad7f626385660 (chrome-extension://gcmgaphlohnhdgfbefpphkhnaijglnci/dist/0cd49685d80f76e20307.wasm:wasm-function[1290]:0x31f53e)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h16a4fefa008aae53 (chrome-extension://gcmgaphlohnhdgfbefpphkhnaijglnci/dist/0cd49685d80f76e20307.wasm:wasm-function[4376]:0x4b32f7)
    at std::panicking::rust_panic_with_hook::he9bfe03219d715ba (chrome-extension://gcmgaphlohnhdgfbefpphkhnaijglnci/dist/0cd49685d80f76e20307.wasm:wasm-function[3218]:0x44ca23)
    at rust_begin_unwind (chrome-extension://gcmgaphlohnhdgfbefpphkhnaijglnci/dist/0cd49685d80f76e20307.wasm:wasm-function[4605]:0x4b9317)
    at core::panicking::panic_fmt::hbf21a3d4bbb82bf8 (chrome-extension://gcmgaphlohnhdgfbefpphkhnaijglnci/dist/0cd49685d80f76e20307.wasm:wasm-function[4795]:0x4c092d)
    at core::result::unwrap_failed::h27f43d993c3864a1 (chrome-extension://gcmgaphlohnhdgfbefpphkhnaijglnci/dist/0cd49685d80f76e20307.wasm:wasm-function[3901]:0x4a1a50)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hac2cf32645130353 (chrome-extension://gcmgaphlohnhdgfbefpphkhnaijglnci/dist/0cd49685d80f76e20307.wasm:wasm-function[730]:0x229df4)
    at <ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::hea2d6ac358ab2d06 (chrome-extension://gcmgaphlohnhdgfbefpphkhnaijglnci/dist/0cd49685d80f76e20307.wasm:wasm-function[2509]:0x4048c1)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.bcae1.com/switchingpowersupplydesign/switchingpowersupplytut01.htm
SWF URL: https://www.bcae1.com/switchingpowersupplydesign/6inchpowersupplyphoto02.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-10-11
Channel: nightly
Built: 2021-10-11T00:11:53.318Z
Commit: 279834a499b61671ca3b7517123960e6299b60f2
Is extension: true

**Comment by Lord-McSweeney** [comment] 2023-02-11 23:17
Duplicate of #2598.

**Closed by Lord-McSweeney** 2023-02-11 23:17 UTC
