### ISSUE TITLE
Please help me to rename the issue, don't know how to describe this.

### ISSUE THREAD

**Issue by BracerJack** [ruffle-rs/ruffle#980] opened 2020-08-06 21:16 UTC
Step 1: Open a *.swf with getURL button with the Windows Binary version of Ruffles.
Step 2: Click on that button, a browser may or may not be loaded, but what is definitely going to happen is the Windows Binary version of Ruffles is going to hang/crash/die/no longer respond.

**Comment by kmeisthax** [comment] 2020-08-06 21:22
The behavior of `getURL` when you hand it a regular webpage is to navigate the browser to that page. We emulate that in Ruffle desktop by opening a browser using another Rust library. I'm not sure why that's causing problems, but we'd need to investigate.

Do you know exactly how `ActionGetURL` is being invoked? Usually, if the target of the action is a valid layer or movieclip, then it'll load it as a SWF rather than navigate to the URL. However, we already handle all of those cases, so presumably this movie expects to be able to `getURL` without a valid target and get a child movie loaded anyway.

**Comment by Herschel** [comment] 2020-08-06 21:30
Sounds like #757 caused by winit. This is fixed in winit master but hasn't been published in a new version yet. I may just rollback winit to the previous version in the meantime.

**Comment by Herschel** [comment] 2020-08-06 21:46
Closing in favor of #757.

**Closed by Herschel** 2020-08-06 21:46 UTC

**Comment by BracerJack** [comment] 2020-08-06 22:10
Thank you Herschel and thank kmeisthax for the explanation of the inner workings of ruffles :D
