### ISSUE TITLE
stopDrag not working

### ISSUE THREAD

**Issue by mitja759** [ruffle-rs/ruffle#18493] opened 2024-11-06 07:58 UTC
### Describe the bug

Function stopDrag (As2) is working properly in Desktop application, however no in online player.![Image](https://github.com/user-attachments/assets/1696c1cc-62b2-466c-a827-c0306f436995)

### Expected behavior

Please, fix it.

### Content Location

[zigman.zip](https://github.com/user-attachments/files/17643589/zigman.zip)

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

MozillaFirefox 131.0.3 (64), Chrome

**Comment by kjarosh** [comment] 2024-11-06 11:53
Hi, thank you for your report.

Can you describe what does not work properly, how to reproduce it, and what behavior you expect? It's difficult and very time-consuming to guess what you mean by "stopDrag is not working properly".

**Comment by kjarosh** [comment] 2024-11-06 15:42
Thank you for the description, I really appreciate it! Matter of fact, I do like chess and I find it very interesting :)

Unfortunately, I cannot reproduce the issue, the queen works properly for me both on the desktop version and on web. See the following video (Firefox 131.0.3).

https://github.com/user-attachments/assets/7d11b496-acf3-4cf1-bfdd-2459ab8ea887

Am I trying to reproduce it correctly? Could you share the website where it doesn't work?

**Comment by mitja759** [comment] 2024-11-06 16:38
Hi Kamil!

I saw the video. I dont know what I am missing. I send you my page where is not working. Try to move a piece. What I did wrong? Can you figure it out?
Bottom clic Matjaž Žigman.

https://www.gravitacija.net/album.html

Best regards, Mitja Ukmar

Poslano iz programa Pošta za Windows

Od: Kamil Jarosz
Poslano: sreda, 06. november 2024 16:42
Za: ruffle-rs/ruffle
Kp: mitja759; Author
Zadeva: Re: [ruffle-rs/ruffle] stopDrag not working (Issue #18493)

Thank you for the description, I really appreciate it! Matter of fact, I do like chess and I find it very interesting :)
Unfortunately, I cannot reproduce the issue, the queen works properly for me both on the desktop version and on web. See the following video (Firefox 131.0.3).
https://github.com/user-attachments/assets/7d11b496-acf3-4cf1-bfdd-2459ab8ea887
Am I trying to reproduce it correctly? Could you share the website where it doesn't work?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>



– 
Protivirusna programska oprema Avast je pregledala to e-poštno sporočilo, ali vsebuje viruse.
www.avast.com

**Comment by mitja759** [comment] 2024-11-06 16:45
Another thing
Hi Kamil!
Doesent work properly also with Demo player in your webpage.

Mitja
Poslano iz programa Pošta za Windows

Od: Kamil Jarosz
Poslano: sreda, 06. november 2024 16:42
Za: ruffle-rs/ruffle
Kp: mitja759; Author
Zadeva: Re: [ruffle-rs/ruffle] stopDrag not working (Issue #18493)

Thank you for the description, I really appreciate it! Matter of fact, I do like chess and I find it very interesting :)
Unfortunately, I cannot reproduce the issue, the queen works properly for me both on the desktop version and on web. See the following video (Firefox 131.0.3).
https://github.com/user-attachments/assets/7d11b496-acf3-4cf1-bfdd-2459ab8ea887
Am I trying to reproduce it correctly? Could you share the website where it doesn't work?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>



– 
Protivirusna programska oprema Avast je pregledala to e-poštno sporočilo, ali vsebuje viruse.
www.avast.com

**Comment by mitja759** [comment] 2024-11-06 17:04
Another tip
Hi Kamil!
Maybe the resaon is that file isnt the same size as Player?
Mitja
Poslano iz programa Pošta za Windows

Od: Kamil Jarosz
Poslano: sreda, 06. november 2024 16:42
Za: ruffle-rs/ruffle
Kp: mitja759; Author
Zadeva: Re: [ruffle-rs/ruffle] stopDrag not working (Issue #18493)

Thank you for the description, I really appreciate it! Matter of fact, I do like chess and I find it very interesting :)
Unfortunately, I cannot reproduce the issue, the queen works properly for me both on the desktop version and on web. See the following video (Firefox 131.0.3).
https://github.com/user-attachments/assets/7d11b496-acf3-4cf1-bfdd-2459ab8ea887
Am I trying to reproduce it correctly? Could you share the website where it doesn't work?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>



– 
Protivirusna programska oprema Avast je pregledala to e-poštno sporočilo, ali vsebuje viruse.
www.avast.com

**Comment by kjarosh** [comment] 2024-11-06 17:27
Thanks for your quick response Mitja!

I've tried reproducing the issue on your webpage, but it works here too for me (both Firefox and Chromium). See the video below.

https://github.com/user-attachments/assets/4230b619-31b5-4f78-bb17-22b0100912e5

I suspect this might be either a bug in the browser or a browser/OS-specific bug in Ruffle. Can you verify whether this works on different browsers and/or devices? Firefox vs Chrome-based browsers, maybe your phone, a different computer, etc. That will give us a better idea about what causes this issue. Please let me know the specific browser and the OS where this works and where it doesn't.

**Comment by mitja759** [comment] 2024-11-06 17:54
Ok, Kamil!
I will create another Ruffle page with chess files (many of them), which size is different. I suspect the size. The place of moving the figure strongly depend on pixels. I let you know. Give me few days.
I already try Chrome, is the same. I will try same others.
For now, many thanks for your support and quick response.
Best regards, Mitja


Poslano iz programa Pošta za Windows

Od: Kamil Jarosz
Poslano: sreda, 06. november 2024 18:28
Za: ruffle-rs/ruffle
Kp: mitja759; Author
Zadeva: Re: [ruffle-rs/ruffle] stopDrag not working (Issue #18493)

Thanks for your quick response Mitja!
I've tried reproducing the issue on your webpage, but it works here too for me (both Firefox and Chromium). See the video below.
https://github.com/user-attachments/assets/4230b619-31b5-4f78-bb17-22b0100912e5
I suspect this might be either a bug in the browser or a browser/OS-specific bug in Ruffle. Can you verify whether this works on different browsers and/or devices? Firefox vs Chrome-based browsers, maybe your phone, a different computer, etc. That will give us a better idea about what causes this issue. Please let me know the specific browser and the OS where this works and where it doesn't.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>



– 
Protivirusna programska oprema Avast je pregledala to e-poštno sporočilo, ali vsebuje viruse.
www.avast.com

**Comment by mitja759** [comment] 2024-11-07 09:13
Hi, Kamil!

My instinct was right. The field on which you drop the figure is precisely determinated by coordinates. A different size of swf compromised it.

https://www.gravitacija.net/uganke.html

Sorry for reporting this as a bug. I myself turned out as a bug. Please delete my post, or as  Author give the explanation why the problem is solved.

Many thanks for your support!

P.S.
From your name i conclude that your homeland is Poland. You share your name with great ski jumper pan Stoch. But now our Slovenian ski jumpers are little better than Polish (ha, ha)

Best regards, Mitja


Poslano iz programa Pošta za Windows

Od: Kamil Jarosz
Poslano: sreda, 06. november 2024 18:28
Za: ruffle-rs/ruffle
Kp: mitja759; Author
Zadeva: Re: [ruffle-rs/ruffle] stopDrag not working (Issue #18493)

Thanks for your quick response Mitja!
I've tried reproducing the issue on your webpage, but it works here too for me (both Firefox and Chromium). See the video below.
https://github.com/user-attachments/assets/4230b619-31b5-4f78-bb17-22b0100912e5
I suspect this might be either a bug in the browser or a browser/OS-specific bug in Ruffle. Can you verify whether this works on different browsers and/or devices? Firefox vs Chrome-based browsers, maybe your phone, a different computer, etc. That will give us a better idea about what causes this issue. Please let me know the specific browser and the OS where this works and where it doesn't.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>



– 
Protivirusna programska oprema Avast je pregledala to e-poštno sporočilo, ali vsebuje viruse.
www.avast.com

**Comment by kjarosh** [comment] 2024-11-09 14:28
Hi Mitja, I'm glad you found the problem! I'll go ahead and close the issue then.

I didn't quite understand the solution, but I assume that it wasn't an error on Ruffle's side. Our goal is to match Flash's behavior in every way possible, so if there's anything that diverges here (even if you can fix it in some other way) please let me know and I'll reopen the issue.

Best wishes, Kamil

**Closed by kjarosh** 2024-11-09 14:28 UTC
Labels: bug, A-web, A-avm1

**Comment by mitja759** [comment] 2024-11-09 19:14
Hi, Kamil!

Yes, close the issue. It isn't a bug. 
I apologize another time for my ignorance. I should remembered sonner that my target (for example; field h2 _x = 381,_y = 247), is no there, when I drop a figure, if my movie don't match the size of Ruffle player!

Best regards, Mitja Ukmar˙˙

Poslano iz programa Pošta za Windows

Od: Kamil Jarosz
Poslano: sobota, 09. november 2024 15:28
Za: ruffle-rs/ruffle
Kp: mitja759; Author
Zadeva: Re: [ruffle-rs/ruffle] stopDrag not working (Issue #18493)

Hi Mitja, I'm glad you found the problem! I'll go ahead and close the issue then.
I didn't quite understand the solution, but I assume that it wasn't an error on Ruffle's side. Our goal is to match Flash's behavior in every way possible, so if there's anything that diverges here (even if you can fix it in some other way) please let me know and I'll reopen the issue.
Best wishes, Kamil
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>



– 
Protivirusna programska oprema Avast je pregledala to e-poštno sporočilo, ali vsebuje viruse.
www.avast.com
