### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by TheTruePerson** [ruffle-rs/ruffle#11697] opened 2023-06-23 13:45 UTC
#Web Page

cdn.scratch.mit.edu/scratchr2/static/__e71d264c6d10cd3e8bf248a7f0ccfbd4__/Scratch.swf

# Error Info
Error name: Error
Error message: panicked at 'not implemented: Unimplemented opcode Pow', render/naga-pixelbender/src/lib.rs:725:29
Error stack:
```
Error: panicked at 'not implemented: Unimplemented opcode Pow', render/naga-pixelbender/src/lib.rs:725:29
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2396:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb6f72ebd1a9c8bd (wasm://wasm/02c6c64a:wasm-function[8635]:0x83e821)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c6c64a:wasm-function[5602]:0x76674c)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c6c64a:wasm-function[8499]:0x83a459)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::compile_pixelbender_shader::h32721b91b5483ef8 (wasm://wasm/02c6c64a:wasm-function[7142]:0x7d4a6f)
    at ruffle_core::avm2::globals::flash::display::shader_data::init::hff8e040f78a1b1ba (wasm://wasm/02c6c64a:wasm-function[960]:0x33480d)
    at ruffle_core::avm2::function::Executable::exec::h3325d83591e2f464 (wasm://wasm/02c6c64a:wasm-function[810]:0x2ad775)
    at ruffle_core::avm2::object::TObject::call_property::h4741aae4da6be41a (wasm://wasm/02c6c64a:wasm-function[1125]:0x3977e7)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h0d99b33f9b54fbc7 (wasm://wasm/02c6c64a:wasm-function[2691]:0x5ca5d0)
    at ruffle_core::avm2::activation::Activation::run_actions::h207061ade6afadd9 (wasm://wasm/02c6c64a:wasm-function[516]:0x28fca)
```
AVM2 stack:
```
    at flash.display::ShaderData/flash::display::ShaderData::init()
    at flash.display::ShaderData()
    at flash.display::Shader/set byteCode()
    at flash.display::Shader()
    at filters::FilterPack()
    at scratch::ScratchStage()
    at scratch::ScratchStageOnline()
    at ScratchOnline/getScratchStage()
    at Scratch/initialize()
    at ScratchOnline/initialize()
    at Scratch/jsAccessDetermined()
    at Scratch/determineJSAccess()
    at Scratch()
    at ScratchOnline()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, Apple M2, OpenGL 4.1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fcdn.scratch.mit.edu%2Fscratchr2%2Fstatic%2F__e71d264c6d10cd3e8bf248a7f0ccfbd4__%2FScratch.swf
SWF URL: https://cdn.scratch.mit.edu/scratchr2/static/__e71d264c6d10cd3e8bf248a7f0ccfbd4__/Scratch.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-23
Channel: nightly
Built: 2023-06-23T00:25:27.882Z
Commit: e0cc7f1e544044ba78568df1152366631bc86153
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 24
numFrames: 1
swfVersion: 19
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6750878

**Comment by Lord-McSweeney** [comment] 2023-06-23 15:47
Duplicate of #11580

**Closed by Lord-McSweeney** 2023-06-23 15:47 UTC
Labels: error-report

**Comment by TheTruePerson** [comment] 2023-06-23 20:07
ok thx
