### ISSUE TITLE
Ruffle Error on https://learn.genetics.utah.edu/content/cloning/clickandclone/

### ISSUE THREAD

**Issue by anaorozco010579** [ruffle-rs/ruffle#4885] opened 2021-07-18 18:26 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:283:46
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:283:46
    at Object.Y (https://learn.genetics.utah.edu/ruffle/core.ruffle.efe183f76847e3a3efc0.js:1:20617)
    at __wbg_new_df6e6ab7a65c4c4d (https://learn.genetics.utah.edu/ruffle/ruffle.js:1:36567)
    at https://learn.genetics.utah.edu/ruffle/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[1109]:0x225944
    at https://learn.genetics.utah.edu/ruffle/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[1460]:0x269bae
    at https://learn.genetics.utah.edu/ruffle/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[3955]:0x3293e2
    at https://learn.genetics.utah.edu/ruffle/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[3096]:0x308595
    at https://learn.genetics.utah.edu/ruffle/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[4259]:0x32e27f
    at https://learn.genetics.utah.edu/ruffle/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[4289]:0x32e7e2
    at https://learn.genetics.utah.edu/ruffle/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[4163]:0x32ce0e
    at https://learn.genetics.utah.edu/ruffle/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[4290]:0x32e818
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://learn.genetics.utah.edu/content/cloning/clickandclone/
SWF URL: https://learn.genetics.utah.edu/content/cloning/clickandclone/clickandclone.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 11; M2101K7AG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-22
Channel: nightly
Built: 2020-12-22T00:39:03.522Z
Commit: f7797f85d6a2c340b0dfb97c42a3cc04be32b997

**Comment by jhwgh1968** [comment] 2021-08-29 03:37
This seems to work on ruffle desktop commit 3982f3af9811cfc32c6f7eaf06aa3c8c81b91226. Perhaps if the site owner updated their Ruffle version, it would solve the problem.

**Comment by n0samu** [comment] 2022-06-06 19:41
Duplicate of #4583

**Closed by n0samu** 2022-06-06 19:41 UTC
Labels: error-report
