### ISSUE TITLE
Error on T3quila Zombies 3

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#14594] opened 2024-01-03 08:50 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f976fb/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f976fb/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
    at imports.wbg.__wbg_new_a64e3f2afc2cf2f8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2624:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hdcdf3f6ca94f57c3 (wasm://wasm/0356ae8e:wasm-function[10652]:0x9f0775)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/0356ae8e:wasm-function[6542]:0x8e10c3)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/0356ae8e:wasm-function[10376]:0x9ea52b)
    at core::option::expect_failed::h0edfdc49383f4b56 (wasm://wasm/0356ae8e:wasm-function[9052]:0x998945)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h923574a4a90817ee (wasm://wasm/0356ae8e:wasm-function[612]:0x117325)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h923574a4a90817ee (wasm://wasm/0356ae8e:wasm-function[612]:0x114884)
    at flash_lso::amf3::read::AMF3Decoder::parse_object_static::h5207f13d311bad2c (wasm://wasm/0356ae8e:wasm-function[4321]:0x7c4b1c)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::h923574a4a90817ee (wasm://wasm/0356ae8e:wasm-function[612]:0x117199)
    at flash_lso::amf3::read::AMF3Decoder::parse_object_static::h5207f13d311bad2c (wasm://wasm/0356ae8e:wasm-function[4321]:0x7c4b1c)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at BinaryData$/getMovieClipManager()
    at Game/onLoadComplete()
    at Game()
    at Main/createGame()
    at Main/onRootCreated()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1837()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti (0x00001C82) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.spiele-umsonst.de/tequila-zombies-3-t5523.html
SWF URL: https://www.spiele-umsonst.de/azad/downloads/flashgames/tequilazombies3ad.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-01
Channel: nightly
Built: 2024-01-01T00:16:22.173Z
Commit: eac68a0647f78cb3dedc5c0a2d2899b29c7a9965
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 2
swfVersion: 21
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 38081696

**Comment by n0samu** [comment] 2024-01-03 10:10
Duplicate of #13748

**Closed by n0samu** 2024-01-03 10:10 UTC
Labels: duplicate, avm2, error-report, amf
