### ISSUE TITLE
Error on https://www.twoplayergames.org/gameframe/gun-mayhem-redux

### ISSUE THREAD

**Issue by Lucasgitub1** [ruffle-rs/ruffle#7927] opened 2022-09-09 01:17 UTC
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 8 but the index is 8', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.17.10/src/fill.rs:1504:27
Error stack:
```
Error: panicked at 'index out of bounds: the len is 8 but the index is 8', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.17.10/src/fill.rs:1504:27
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.twoplayergames.org/dist/build/ruffle/core.ruffle.efc79ceefe020ac2b4b7.js:1:7708)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (https://www.twoplayergames.org/dist/build/ruffle/35aab1ffc1d2cdb458be.wasm:wasm-function[982]:0x0)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://www.twoplayergames.org/dist/build/ruffle/35aab1ffc1d2cdb458be.wasm:wasm-function[1483]:0x0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (https://www.twoplayergames.org/dist/build/ruffle/35aab1ffc1d2cdb458be.wasm:wasm-function[4931]:0x0)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://www.twoplayergames.org/dist/build/ruffle/35aab1ffc1d2cdb458be.wasm:wasm-function[3261]:0x0)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://www.twoplayergames.org/dist/build/ruffle/35aab1ffc1d2cdb458be.wasm:wasm-function[5017]:0x0)
    at core::panicking::panic_bounds_check::he4f030d1ec9ef522 (https://www.twoplayergames.org/dist/build/ruffle/35aab1ffc1d2cdb458be.wasm:wasm-function[4337]:0x0)
    at lyon_tessellation::fill::FillTessellator::process_events::h6fc7564ca6d8ea40 (https://www.twoplayergames.org/dist/build/ruffle/35aab1ffc1d2cdb458be.wasm:wasm-function[359]:0x0)
    at lyon_tessellation::fill::FillTessellator::tessellate_impl::h00bb35d0c7b9325f (https://www.twoplayergames.org/dist/build/ruffle/35aab1ffc1d2cdb458be.wasm:wasm-function[581]:0x0)
    at ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h7525177f5af04a07 (https://www.twoplayergames.org/dist/build/ruffle/35aab1ffc1d2cdb458be.wasm:wasm-function[668]:0x0)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.twoplayergames.org/gameframe/gun-mayhem-redux
SWF URL: https://files.twoplayergames.org/files/games/o4/Gun_Mayhem_Redux.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.27
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-27
Channel: nightly
Built: 2022-04-27T00:15:21.542Z
Commit: 4a9d6867baf98483ef886119808d4762a606fdfa
Is extension: false

**Comment by n0samu** [comment] 2022-09-09 01:30
This problem is caused by Microsoft Edge's "Enhance your security on the web" feature. [See the FAQ for a solution to the problem](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#edge-webassembly-error).

Closing in favor of #7849 (same issue)

**Closed by n0samu** 2022-09-09 01:30 UTC
Labels: duplicate, error-report
