### ISSUE TITLE
Error on https://game253127.konggames.com/games/BerzerkStudio/zombidle/frame/b6df6f7f-50c8-4d8d-81c7-c7efd4b07a1a/

### ISSUE THREAD

**Issue by themongoose** [ruffle-rs/ruffle#14337] opened 2023-12-07 18:23 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f976fb/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/2f976fb/flash-lso/src/amf3/read.rs:417:14:
Unable to get Object
    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.62a8f0c82d1a76601817.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2c4885bc68fd7d6d (wasm://wasm/03399e2a:wasm-function[9815]:0x9bac4c)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/03399e2a:wasm-function[6301]:0x8acafe)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/03399e2a:wasm-function[9620]:0x9b5b68)
    at core::option::expect_failed::h6f4ce1bb06a99e85 (wasm://wasm/03399e2a:wasm-function[8594]:0x966786)
    at flash_lso::amf3::read::AMF3Decoder::parse_single_element::hbb144d6dc4f3dce7 (wasm://wasm/03399e2a:wasm-function[616]:0x12a26a)
    at ruffle_core::avm2::globals::flash::utils::byte_array::read_object::h4d368df9c9b4435f (wasm://wasm/03399e2a:wasm-function[910]:0x32c6ad)
    at ruffle_core::avm2::function::Executable::exec::h9257959af56803e4 (wasm://wasm/03399e2a:wasm-function[871]:0x307857)
    at ruffle_core::avm2::object::TObject::call_property::h65819b4e528a287c (wasm://wasm/03399e2a:wasm-function[1326]:0x448227)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h938ff7c627ec52e2 (wasm://wasm/03399e2a:wasm-function[2828]:0x689f81)
```
AVM2 stack:
```
    at flash.utils::ByteArray/flash::utils::ByteArray::readObject()
    at com.berzerkstudio::ModelFla/loadFromByteArray()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadNextFla()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadBunch()
    at com.lachhhStarling.berzerk::BerzerkZipModelFlaLoader/loadAllFlas()
    at com.zombidle::MainGameWebStarling/loadModelFlas()
    at com.zombidle::MainGameWebStarling/loadZipFile()
    at Function/apply()
    at com.lachhh.io::Callback/call()
    at com.lachhhStarling::StarlingMain$/startGame()
    at MethodInfo-5838()
    at starling.utils::AssetManager/loadQueue()
    at com.lachhhStarling::StarlingMain$/loadAssetsDesktop()
    at MethodInfo-5836()
    at starling.events::EventDispatcher/invokeEvent()
    at starling.events::EventDispatcher/dispatchEvent()
    at starling.events::EventDispatcher/dispatchEventWith()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1825()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 630 (0x0000591B) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game253127.konggames.com/games/BerzerkStudio/zombidle/frame/b6df6f7f-50c8-4d8d-81c7-c7efd4b07a1a/?kongregate_host=www.kongregate.com
SWF URL: https://game253127.konggames.com/gamez/0025/3127/live/ZI_FGL.swf?kongregate_game_version=1570126011

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 OPR/104.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-07
Channel: nightly
Built: 2023-12-07T00:15:04.300Z
Commit: 41ddb316a2b0a91c0d32e8f54eb0f020be42831f
Is extension: false

# Metadata
width: 960
height: 640
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 64218669

**Comment by n0samu** [comment] 2023-12-13 03:38
Duplicate of #10174

**Closed by n0samu** 2023-12-13 03:38 UTC
Labels: avm2, error-report, amf
