### ISSUE TITLE
The Skullkid - Can't chainsaw through first desk

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#2002] opened 2020-12-17 13:14 UTC
https://www.newgrounds.com/portal/view/63747

I am pretty sure this was working in Ruffle before so something may have regressed. Walk up to the first table and hold the spacebar to chainsaw through it - part way through the cutting animation, something stops your progress and you can't complete the cutting.

**Comment by Toad06** [comment] 2020-12-17 13:38
You're right about the regression, there was no issue in nightly builds <= 2020-11-29.
However, this appears to have been fixed in the nightly 2020-12-10 or newer.

**Comment by Herschel** [comment] 2020-12-18 02:01
Looks like this is working on master.

**Closed by Herschel** 2020-12-18 02:01 UTC
