### ISSUE TITLE
Error on https://games.crazygames.com/en_US/electric-man/index.html

### ISSUE THREAD

**Issue by mattw59** [ruffle-rs/ruffle#7503] opened 2022-07-29 14:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
https://files.crazygames.com/gameframe/ruffle/2022-05-17/core.ruffle.aee25967978e8aeb04e0.js:1:7496
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::ha242d4d2b43703ce]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h07d0245bef259c27]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h88636dd63977a123]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h623ac32ff431b114]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h5118e89563022e7e]@[wasm code]
<?>.wasm-function[core::panicking::panic::he88f1b1582b09c8c]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once::h35b3566b432bc806]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h58e873f674ec15e2]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7ae2f1fde5347ee6]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h71d6799f99277bcc]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::Avm1::run_stack_frame_for_action::hcb874025f49c1323]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::h6f2e92196fb67f1c]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h72c32e382ff7c3dc]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h83f84c4202dfeef8]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9b5cf45bc3df0eb9]@[wasm code]
wasm-stub@[native code]
F@https://files.crazygames.com/gameframe/ruffle/2022-05-17/core.ruffle.aee25967978e8aeb04e0.js:1:3406
c@https://files.crazygames.com/gameframe/ruffle/2022-05-17/core.ruffle.aee25967978e8aeb04e0.js:1:2393
i@https://gameframe.crazygames.com/crazygames-gameframe-v1.bundle.js:2:307248
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.crazygames.com/en_US/electric-man/index.html

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-17
Channel: nightly
Built: 2022-05-17T00:16:53.792Z
Commit: ede81be4279e0af289ebc5057ebcdb12d5f99a38
Is extension: false

**Comment by n0samu** [comment] 2022-07-29 22:11
Duplicate of #4932

**Closed by n0samu** 2022-07-29 22:11 UTC
Labels: error-report
