### ISSUE TITLE
Error on https://www.twoplayergames.org/gameframe/electricman-2

### ISSUE THREAD

**Issue by Imtiaz48** [ruffle-rs/ruffle#8407] opened 2022-10-28 23:32 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
@https://www.twoplayergames.org/dist/ruffle/core.ruffle.25dad036ec86ae2f17cd.js:1:7458
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::he3cf99cdc4fda287]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h00971925aa1adad3]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::ha1e2d21f5521daa9]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h84feca33bd4bd229]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hc171d095bc4a492d]@[wasm code]
<?>.wasm-function[core::panicking::panic::h3b7a8a1eaf47fc0f]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once::h5d896e6757363123]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::h617d7843d3858b48]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hddfd162220c32fa4]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::h397e6220157df695]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::Avm1::run_stack_frame_for_action::h6225398bc1980b44]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::h24039589d82cc373]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h63bf722752bc2fd2]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h73dbebe29e6125ca]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h8576657be332cb20]@[wasm code]
wasm-stub@[native code]
E@https://www.twoplayergames.org/dist/ruffle/core.ruffle.25dad036ec86ae2f17cd.js:1:3029
c@https://www.twoplayergames.org/dist/ruffle/core.ruffle.25dad036ec86ae2f17cd.js:1:2481
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.twoplayergames.org/gameframe/electricman-2

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6,2 Safari/605.1.15
Platform: MacIntel
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-21
Channel: nightly
Built: 2022-08-21T00:17:09.470Z
Commit: b18329c8feb06d4b2feaba64687abbf580599952
Is extension: false

**Comment by Imtiaz48** [comment] 2022-10-28 23:33
FIX YOUR STUPID FUCKING GAME FOR FUCK SAKES!!!

**Comment by Imtiaz48** [comment] 2022-10-28 23:33
OMG JUST FUCKING FIX YOUR ABOMINATION

**Comment by Imtiaz48** [comment] 2022-10-28 23:34
FOR FUCK SAKES

**Comment by Imtiaz48** [comment] 2022-10-28 23:34
OR DONT I WILL REPORT YOU

**Comment by p0008874** [comment] 2022-10-29 07:16
![image](https://user-images.githubusercontent.com/75534590/198819122-7610c1bb-d0c1-43da-a6ac-393e12548409.png)

**Comment by n0samu** [comment] 2022-10-29 15:53
Duplicate of #4932

**Closed by n0samu** 2022-10-29 15:53 UTC
Labels: duplicate, error-report
