### ISSUE TITLE
Error on https://chemistry.learningstudies.me/game/electric-man

### ISSUE THREAD

**Issue by ZestyChickenthe1st** [ruffle-rs/ruffle#8107] opened 2022-09-27 03:47 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.bca1371f982df7946ed0.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h73fc39b54ec29717 (wasm://wasm/017e80ce:wasm-function[1021]:0x2a382a)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017e80ce:wasm-function[1485]:0x32709b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d648d6ec080e3d2 (wasm://wasm/017e80ce:wasm-function[4920]:0x484625)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017e80ce:wasm-function[3620]:0x441389)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017e80ce:wasm-function[5073]:0x487a48)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/017e80ce:wasm-function[4976]:0x4855e1)
    at core::ops::function::FnOnce::call_once::hc23e58910edbda0c (wasm://wasm/017e80ce:wasm-function[1113]:0x2c2f02)
    at ruffle_core::avm1::function::Executable::exec::ha1ebff59d66588d4 (wasm://wasm/017e80ce:wasm-function[364]:0xf1f99)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h6e117415f5d8a106 (wasm://wasm/017e80ce:wasm-function[491]:0x196711)
    at ruffle_core::avm1::activation::Activation::run_actions::hdebc2c5fe73d0130 (wasm://wasm/017e80ce:wasm-function[299]:0x1ba78)
    at ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h1cd5d8b6421fbd27 (wasm://wasm/017e80ce:wasm-function[912]:0x283168)
    at ruffle_core::player::Player::run_actions::hd7afab17e4eeb759 (wasm://wasm/017e80ce:wasm-function[455]:0x1712c1)
    at ruffle_web::Ruffle::tick::h6af632469979f791 (wasm://wasm/017e80ce:wasm-function[663]:0x213a8d)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h60d726a424d28b1d (wasm://wasm/017e80ce:wasm-function[5953]:0x4a1478)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h970c39b503fdbae6 (wasm://wasm/017e80ce:wasm-function[5431]:0x491f1e)
    at A (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.bca1371f982df7946ed0.js:1:2554)
    at c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.bca1371f982df7946ed0.js:1:2231)
    at sentryWrapped (https://browser.sentry-cdn.com/6.2.2/bundle.min.js:2:53837)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://chemistry.learningstudies.me/game/electric-man
SWF URL: https://chemistry.learningstudies.me/cdn/swf/ElectricMan.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-27
Channel: nightly
Built: 2022-09-27T00:19:30.237Z
Commit: 66fa67cdcc6d802664e63cf2a5f8c6264d54fa31
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment] 2022-09-27 03:49
Duplicate of #4932

**Closed by n0samu** 2022-09-27 03:49 UTC
Labels: duplicate, error-report
