### ISSUE TITLE
Ruffle Error on https://www.electricman.space/

### ISSUE THREAD

**Issue by d0ma1nn** [ruffle-rs/ruffle#7595] opened 2022-08-08 01:54 UTC
# Error Info
Error name: TypeError
Error message: NetworkError when attempting to fetch resource.

# Player Info
Allows script access: true
Player type: Object
SWF URL: electricman.swf
Param game: electricman.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.electricman.space/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-02
Channel: nightly
Built: 2021-01-02T00:44:12.942Z
Commit: 83c32e8693ec7d585713d457599b87b81e2057c3

**Comment by n0samu** [comment] 2022-08-08 02:08
Duplicate of #7460. Please visit the site using the URL https://electricman.space/ instead, or contact them and ask them to fix the problem with their website.

**Closed by n0samu** 2022-08-08 02:08 UTC
Labels: duplicate, error-report
