### ISSUE TITLE
Error on https://www.thesbcommunity.com/games/sb_ship/

### ISSUE THREAD

**Issue by Esreever** [ruffle-rs/ruffle#11237] opened 2023-05-27 16:50 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:629:28

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.thesbcommunity.com/games/sb_ship/
SWF URL: https://www.thesbcommunity.com/games/sb_ship/ship_o_ghouls.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-07
Channel: nightly
Built: 2023-02-07T00:21:37.543Z
Commit: 48f4df51a51cc1e2e009b2212eaa14459488a1e4
Is extension: false

# Metadata
width: 600
height: 300
frameRate: 35
numFrames: 56
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 1696607

**Comment by n0samu** [comment] 2023-05-27 22:59
Hi, can you tell us what led up to this error? Did it happen at a specific point in the game?

**Comment by relrelb** [comment] 2023-05-28 04:58
Likely duplicate of #10060.

**Comment by n0samu** [comment] 2023-05-28 05:37
I managed to reproduce the error, I'll add details as a comment on the original issue

**Closed** 2023-05-28 05:37 UTC
Labels: duplicate, avm1, error-report

**Comment by n0samu** [comment] 2023-05-28 05:43
Oh, this is actually the same bug as #10314, and was already fixed by #10362.
