### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm

### ISSUE THREAD

**Issue by didemgulhan** [ruffle-rs/ruffle#6670] opened 2022-04-10 10:41 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/core.ruffle.f278ea4a450805461cf1.js:1:7441)
    at std::sync::once::Once::call_once::{{closure}}::h6bc0eae8713deb80 (http://www.freeworldgroup.com/ruffle/9499b1bd3439add91006.wasm:wasm-function[1015]:0x2ad562)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (http://www.freeworldgroup.com/ruffle/9499b1bd3439add91006.wasm:wasm-function[1468]:0x32b11c)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h4e9c305d26dd965f (http://www.freeworldgroup.com/ruffle/9499b1bd3439add91006.wasm:wasm-function[4961]:0x484024)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (http://www.freeworldgroup.com/ruffle/9499b1bd3439add91006.wasm:wasm-function[3327]:0x4295cf)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (http://www.freeworldgroup.com/ruffle/9499b1bd3439add91006.wasm:wasm-function[5248]:0x49038a)
    at core::panicking::panic::h5d6906e2c1099660 (http://www.freeworldgroup.com/ruffle/9499b1bd3439add91006.wasm:wasm-function[4958]:0x483b4b)
    at core::ops::function::FnOnce::call_once::hcc3ad9269afaef99 (http://www.freeworldgroup.com/ruffle/9499b1bd3439add91006.wasm:wasm-function[1104]:0x2c6017)
    at ruffle_core::avm1::function::Executable::exec::h3e84333d6cad5fb9 (http://www.freeworldgroup.com/ruffle/9499b1bd3439add91006.wasm:wasm-function[392]:0x1321c3)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::ha674c0d0afe093f8 (http://www.freeworldgroup.com/ruffle/9499b1bd3439add91006.wasm:wasm-function[383]:0x123c20)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm
SWF URL: http://www.freeworldgroup.com/games6/electricman2/electricman2hs_fwg.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-05
Channel: nightly
Built: 2022-04-05T00:18:48.690Z
Commit: e456fb3ed69778e58013fb6034f52a331107829e
Is extension: false

**Comment by relrelb** [comment] 2022-04-10 16:20
Duplicate of #4932.

**Closed by relrelb** 2022-04-10 16:20 UTC
Labels: error-report
