### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/tomb-chess.htm

### ISSUE THREAD

**Issue by dandridge-cole** [ruffle-rs/ruffle#4451] opened 2021-05-30 18:21 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5
Error stack:
```
e/a.wbg.__wbg_new_df6e6ab7a65c4c4d@http://www.freeworldgroup.com/ruffle/ruffle.js:1:7026
std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[1094]:0x2882fe
std::sync::once::Once::call_inner::h99e47643887ee5a5@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[966]:0x263090
core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[3852]:0x411d3c
std::panicking::rust_panic_with_hook::h03201bc01a0ed891@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[3002]:0x3b2516
rust_begin_unwind@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[4059]:0x417820
core::panicking::panic_fmt::hd44f353696296fec@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[4208]:0x41e0c6
core::option::expect_none_failed::hf7dab2706f1a5551@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[3435]:0x3ffecf
ruffle_core::avm2::object::TObject::install_foreign_trait::h89495d177c90065d@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[324]:0x9d2f0
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::hd912f4aa5c99aa11@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[383]:0xe94f6
ruffle_core::avm2::activation::Activation::do_next_opcode::hc2ee7bcd956e62eb@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[292]:0x29e4a
ruffle_core::avm2::activation::Activation::run_actions::h308fecbe0461a4ff@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[2421]:0x3888ae
ruffle_core::avm2::function::Executable::exec::h96c090c3e37e57c8@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[1268]:0x2b7686
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h2dc12215ee97be8b@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[1622]:0x30f59c
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::hd1f09ffbde438b28@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[366]:0xd3542
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::construct_frame::h09adc76d50f3bce6@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[3707]:0x40ce8f
ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::h685a15fe62ad57a2@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[588]:0x1a9134
ruffle_core::display_object::movie_clip::MovieClip::place_object::hef578ff737ebaa42@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[1159]:0x2a059b
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::hd1f09ffbde438b28@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[366]:0xd2de6
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::construct_frame::h09adc76d50f3bce6@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[3707]:0x40ce8f
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::construct_frame::hf5cdbff4580e2719@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[2664]:0x39b47b
ruffle_web::Ruffle::tick::hc604dbf87d9ee220@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[520]:0x17709f
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hbdfa88d67697aa05@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[4725]:0x427503
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6efd42d85e0a3205@http://www.freeworldgroup.com/ruffle/1757430cca34c73492f3.wasm:wasm-function[4338]:0x420356
A@http://www.freeworldgroup.com/ruffle/ruffle.js:1:3232
a@http://www.freeworldgroup.com/ruffle/ruffle.js:1:2798

```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/tomb-chess.htm
SWF URL: http://www.freeworldgroup.com/games6/tomb-chess/chess.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-26
Channel: nightly
Built: 2021-05-26T00:18:12.940Z
Commit: b4dd64a568c321ce96a8bb959c92341331a0e829

**Comment by relrelb** [comment] 2021-07-22 16:47
Duplicate of #3824.

**Closed by relrelb** 2021-07-22 16:47 UTC
