### ISSUE TITLE
Error on https://flashthemes.net/

### ISSUE THREAD

**Issue by joseangelqr43** [ruffle-rs/ruffle#14934] opened 2024-01-25 02:07 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:3175:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h61e7c84c3ecc6317 (wasm://wasm/0380b3f2:wasm-function[11293]:0xa76188)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/0380b3f2:wasm-function[6894]:0x936193)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/0380b3f2:wasm-function[11007]:0xa6f78a)
    at core::panicking::assert_failed_inner::h003d4b5b03930769 (wasm://wasm/0380b3f2:wasm-function[4791]:0x826cfa)
    at core::panicking::assert_failed::h562f5818fb5dcef9 (wasm://wasm/0380b3f2:wasm-function[11049]:0xa70dee)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::hc092c3261e524ab1 (wasm://wasm/0380b3f2:wasm-function[2597]:0x65715e)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h780e14a2797d204b (wasm://wasm/0380b3f2:wasm-function[1437]:0x44e054)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hb2787988f9230ff5 (wasm://wasm/0380b3f2:wasm-function[3937]:0x7a93c6)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h8f9281141bc1db13 (wasm://wasm/0380b3f2:wasm-function[12277]:0xa94542)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: Canvas
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param scale: exactfit
Param quality: low
Param allowScriptAccess: always
Param allowFullScreen: true
Param flashvars: movieId=Dq7Cslf&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D72&thumburl=%2Fmovie_thumbs%2Fthumb-Dq7Cslf.png&v=72&movieLid=6&pwm=0&ut=-1&apiserver=https%3A%2F%2Fflashthemes.net%2F&playcount=1&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=1&isInitFromExternal=0&isWide=0&appCode=go&is_slideshow=0&is_emessage=0&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=&isEmbed=0&&&&isTemplate=0&showButtons=1&chain_mids=&endStyle=0&showshare=true
Param movie: /static/animationnew/414827163ad4eb60/player.swf
Param wmode: opaque
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-24
Channel: nightly
Built: 2024-01-24T00:16:08.770Z
Commit: a916f6e7a2b76fc211c568aa6b63bb9d8dc76a01
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment] 2024-05-12 21:38
Duplicate of #13974

**Closed by n0samu** 2024-05-12 21:38 UTC
Labels: duplicate, error-report
