### ISSUE TITLE
Error on http://chippi.md.biu.ac.il/bin/fusnet.pl

### ISSUE THREAD

**Issue by akar315** [ruffle-rs/ruffle#3914] opened 2021-04-07 08:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:11028)
    at wasm-function[1265]:169
    at wasm-function[1528]:675
    at wasm-function[4309]:67
    at wasm-function[3299]:224
    at wasm-function[3916]:159
    at wasm-function[4655]:40
    at wasm-function[4526]:89
    at wasm-function[4657]:48
    at wasm-function[3996]:123
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://chippi.md.biu.ac.il/bin/fusnet.pl
SWF URL: http://chippi.md.biu.ac.il/swf/CytoscapeWeb.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by adrian17** [comment] 2021-05-17 22:07
It's very likely this was already fixed in newer version of Ruffle.
In fact, it's possible that this was already fixed by the time you posted this report - the issue is that the extension you used didn't use an up to date version of Ruffle. In fact, not only that extension isn't endorsed by us, it was recently removed from Chrome for being malware. With that in mind, I'd recommend trying a newer official version of Ruffle instead.

**Closed by adrian17** 2021-05-17 22:07 UTC
