### ISSUE TITLE
Error on https://archive.org/details/pacxon_swf

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#7575] opened 2022-08-04 16:08 UTC
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/pacxon_swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36 Edg/103.0.1264.44
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-16
Channel: nightly
Built: 2021-12-16T00:12:02.888Z
Commit: 07c533045604f42610bb3ca5480d9443b78f7fb7
Is extension: false

**Comment by n0samu** [comment] 2022-08-05 03:53
Duplicate of #7574

**Closed by n0samu** 2022-08-05 03:53 UTC
Labels: duplicate, error-report
