### ISSUE TITLE
https://www.x-oo.com/flash-online-games/brettspiele/world-wars-2.html

### ISSUE THREAD

**Issue by ooozooo** [ruffle-rs/ruffle#2921] opened 2021-01-28 09:06 UTC
One of the most addicting games is still running but has a problem with the background colour and i think the padding from the fields. This should be done with the background colours. Same issue in Fancy Pants 2 and lot of other games. Thanks

**Comment by relrelb** [comment] 2021-08-07 16:21
Duplicate of #4646.

**Closed by relrelb** 2021-08-07 16:21 UTC
