### ISSUE TITLE
Error on https://www.cooljuegos.com/embed/jacksmith/

### ISSUE THREAD

**Issue by mariano10k** [ruffle-rs/ruffle#13413] opened 2023-10-03 13:14 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu/src/backend/direct.rs:3056:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu/src/backend/direct.rs:3056:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://www.cooljuegos.com/emulators/ruffle/core.ruffle.364e94dce6ff4a5c7330.js:1:51844)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h70afc0e531fe7142 (wasm://wasm/0329e45a:wasm-function[9722]:0x98e5a3)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/0329e45a:wasm-function[6340]:0x884221)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/0329e45a:wasm-function[9555]:0x989b12)
    at core::ops::function::Fn::call::h526e17b857ccf5d0 (wasm://wasm/0329e45a:wasm-function[6551]:0x89093a)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::ha261fe8a9bd45d04 (wasm://wasm/0329e45a:wasm-function[5117]:0x7e708a)
    at wgpu::backend::direct::Context::handle_error::haf649c2c367e5acc (wasm://wasm/0329e45a:wasm-function[2604]:0x62065c)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h82c2118e9991606c (wasm://wasm/0329e45a:wasm-function[6950]:0x8bd329)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h3a14717dc44e0f94 (wasm://wasm/0329e45a:wasm-function[5959]:0x8655d2)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h51279a0a098c0500 (wasm://wasm/0329e45a:wasm-function[1603]:0x4ad136)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.managers::SoldierManager/updateManager()
    at swordGame.events::GameControls/gameCycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (Geminilake 2x6) , OpenGL 4.5)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.cooljuegos.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-01
Channel: nightly
Built: 2023-10-01T00:24:45.828Z
Commit: d2f0787c2ca02d649cb1e0d4946cd3cce4c9a3ed
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by evilpie** [comment] 2024-04-09 15:08
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:08 UTC
Labels: render-wgpu, error-report
