### ISSUE TITLE
Error on http://www.novalight.net/NOVALIGHT.html

### ISSUE THREAD

**Issue by felipebueno** [ruffle-rs/ruffle#3105] opened 2021-02-05 13:07 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
Error stack:
```
e/a.wbg.__wbg_new_df6e6ab7a65c4c4d@http://www.novalight.net/ruffle.js:1:6349
std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[1267]:0x24ef2a
std::sync::once::Once::call_inner::h02eac160d339afc2@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[1528]:0x27ed9a
core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[4308]:0x353f1a
std::panicking::rust_panic_with_hook::h123718ba3bf480af@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[3299]:0x32cc21
std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[3916]:0x349dfc
std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[4654]:0x359654
rust_begin_unwind@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[4525]:0x357c32
core::panicking::panic_fmt::h285dc015a87be5a4@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[4656]:0x3596b8
core::option::expect_none_failed::hb95d2b1dc5448c17@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[3995]:0x34c594
std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[758]:0x1c16af
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h0a34359a02988563@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[4558]:0x358364
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hba6c29b5a6d30e50@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[4837]:0x35b537
A@http://www.novalight.net/ruffle.js:1:3265
a@http://www.novalight.net/ruffle.js:1:2840
e/a.wbg.__wbg_open_f355af0fd051a9d8<@http://www.novalight.net/ruffle.js:1:10348
D/<@http://www.novalight.net/ruffle.js:1:4647
web_sys::features::gen_Window::Window::open_with_url_and_target::hf38a0c3c4991dce6@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[4079]:0x34ea43
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::navigate_to_url::h21d286f5254b49dc@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[463]:0x12cf3b
ruffle_core::avm1::activation::Activation::do_action::h46f0557145bb0014@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[286]:0x1a652
ruffle_core::avm1::activation::Activation::run_actions::hb2dbfba055a19184@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[2773]:0x30aec1
ruffle_core::avm1::Avm1::run_stack_frame_for_action::he6c05ed35208ac10@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[1118]:0x22df8e
ruffle_core::player::Player::run_actions::hb881f505051afe9c@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[429]:0x111c6e
ruffle_core::player::Player::handle_event::haa9ee1f3f54fb5a1@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[329]:0xa811a
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h6ba7f4eeead8ad91@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[1287]:0x2531fa
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6b0d014216238f67@http://www.novalight.net/ruffle.js line 1 > WebAssembly.instantiate:wasm-function[4836]:0x35b517
R@http://www.novalight.net/ruffle.js:1:3882
a@http://www.novalight.net/ruffle.js:1:2840

```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.novalight.net/NOVALIGHT.html
SWF URL: http://www.novalight.net/NOVALIGHTY.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-26
Channel: nightly
Built: 2021-01-26T00:36:48.131Z
Commit: 7856cdd3d770e406ce546bf1745d8046d7b716f8

**Comment by Poopooracoocoo** [comment] 2021-02-06 03:05
Can you also reproduce on the latest version of Firefox or on Chromium? Do you encounter the crash immediately? I was able to go through everything on Chrome 88 and Firefox 85 my Windows 10 laptop. 

And damn, that is incredible.

**Comment by ousia** [comment] 2021-02-06 23:28
On the first frame, click _Skip intro_:

![1st](https://user-images.githubusercontent.com/203767/107131920-38807000-68db-11eb-82b0-eac953bc46c3.png)

On the second frame, click _Résumé_:

![2nd](https://user-images.githubusercontent.com/203767/107131926-4504c880-68db-11eb-9667-2b63916e320f.png)

Ruffle seems to have problems to follow links (as I have already reported in #3126).

@Poopooracoocoo, could you confirm the bug?

**Comment by Poopooracoocoo** [comment] 2021-02-07 01:38
No I cannot reproduce the bug on both Firefox or Chrome. His resume downloads properly.

**Comment by ousia** [comment] 2021-02-07 02:09
Download is fine, but I get this and the following error:

![wrlksfa](https://user-images.githubusercontent.com/203767/107134381-d54e0800-68f1-11eb-933f-afd8873169b9.png)

# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:838:49
Error stack:
```
r/c.wbg.__wbg_new_df6e6ab7a65c4c4d@http://www.novalight.net/NOVALIGHT.html:3:6695
std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[1330]:0x26c6d3
std::sync::once::Once::call_inner::h02eac160d339afc2@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[1610]:0x2a0323
core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[4648]:0x382e65
std::panicking::rust_panic_with_hook::h123718ba3bf480af@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[3485]:0x356dd4
std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[4150]:0x376218
std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[5002]:0x3886b4
rust_begin_unwind@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[4878]:0x386df5
core::panicking::panic_fmt::h285dc015a87be5a4@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[5004]:0x388718
core::option::expect_none_failed::hb95d2b1dc5448c17@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[4246]:0x379271
std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[787]:0x1d7b84
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hc579618b4ad6cfcd@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[4910]:0x3874f1
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hfc6d3990177bfa48@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[5162]:0x38a10a
S@http://www.novalight.net/NOVALIGHT.html:3:3478
a@http://www.novalight.net/NOVALIGHT.html:3:2736
r/c.wbg.__wbg_open_f355af0fd051a9d8<@http://www.novalight.net/NOVALIGHT.html:3:10574
T/<@http://www.novalight.net/NOVALIGHT.html:3:4399
web_sys::features::gen_Window::Window::open_with_url_and_target::ha8f9d5e54bb59ef1@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[4354]:0x37c1c8
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::navigate_to_url::h6e6c37886d45b246@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[472]:0x13997a
ruffle_core::avm1::activation::Activation::do_action::h91f8e76c35c12cd0@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[289]:0x1d687
ruffle_core::avm1::activation::Activation::run_actions::h6fe40107a3b95052@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[2954]:0x3350a0
ruffle_core::avm1::Avm1::run_stack_frame_for_action::h7740d5d1ac3c1f75@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[827]:0x1e601f
ruffle_core::player::Player::run_actions::hc5831a17624673fb@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[412]:0x108282
ruffle_core::player::Player::handle_event::h3505f23c0feeeb5d@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[350]:0xc52e3
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hd73879f7e0e20300@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[1355]:0x271bcd
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h291ef6601ee543a9@http://www.novalight.net/NOVALIGHT.html line 3 > WebAssembly.instantiate:wasm-function[5161]:0x38a0ea
C@http://www.novalight.net/NOVALIGHT.html:3:3168
a@http://www.novalight.net/NOVALIGHT.html:3:2736

```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.novalight.net/NOVALIGHT.html
SWF URL: http://www.novalight.net/NOVALIGHTY.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-06
Channel: nightly
Built: 2021-02-06T00:17:26.623Z
Commit: 60f29719d36432e305a1b568035f7b97ffc08cbb

**Comment by n0samu** [comment] 2022-10-30 04:51
@felipebueno or @ousia - is this problem still occurring for you?

**Comment by ousia** [comment] 2022-10-30 07:22
@n0samu,

I can confirm the issue reported at https://github.com/ruffle-rs/ruffle/issues/3105#issuecomment-774576874 is gone.

The site seems to work as (what I think it was) expected.

Many thanks for your help.

**Comment by n0samu** [comment] 2022-10-31 00:32
Glad to hear it! I'll close the issue.

**Closed by n0samu** 2022-10-31 00:32 UTC
Labels: error-report
