### ISSUE TITLE
https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html 오류

### ISSUE THREAD

**Issue by FLAMEEEEE** [ruffle-rs/ruffle#3864] opened 2021-03-31 00:54 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1617020560:1:6915)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b9283866b5421dcf2a4c83c71a9a838f.wasm:wasm-function[1187]:0x283764)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b9283866b5421dcf2a4c83c71a9a838f.wasm:wasm-function[1773]:0x2fe727)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b9283866b5421dcf2a4c83c71a9a838f.wasm:wasm-function[5273]:0x40ad6b)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://uploads.ungrounded.net/ruffle_wrapper/lib/b9283866b5421dcf2a4c83c71a9a838f.wasm:wasm-function[4049]:0x3dc8da)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (https://uploads.ungrounded.net/ruffle_wrapper/lib/b9283866b5421dcf2a4c83c71a9a838f.wasm:wasm-function[4752]:0x3fd50a)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (https://uploads.ungrounded.net/ruffle_wrapper/lib/b9283866b5421dcf2a4c83c71a9a838f.wasm:wasm-function[5646]:0x410a83)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/b9283866b5421dcf2a4c83c71a9a838f.wasm:wasm-function[5517]:0x40f0c7)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b9283866b5421dcf2a4c83c71a9a838f.wasm:wasm-function[5648]:0x410ae7)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h8353afd96b6901d4 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b9283866b5421dcf2a4c83c71a9a838f.wasm:wasm-function[1715]:0x2f4b2a)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1617020560%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F512000%2F512407_hank2009.swf%3F1605221180%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2243538823.7c7abe332c360603baa785823533bd417a897404f0b64e%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226063c806ca969%22%2C%22NewgroundsAPI_SessionID%22%3A%2223xK9FPeqPjG8KaVmE0T652c6bb57740f996f63974f207ecd9df4bc69f48Eq29%22%2C%22NewgroundsAPI_UserName%22%3A%22hyunmin9547%22%2C%22NewgroundsAPI_UserID%22%3A8430553%2C%22ng_username%22%3A%22hyunmin9547%22%7D%2C%22width%22%3A720%2C%22height%22%3A405%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F512000%2Fflash_512407_card.png%3Ff1605218420%22%7D
SWF URL: https://uploads.ungrounded.net/512000/512407_hank2009.swf?1605221180

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.63
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-28
Channel: nightly
Built: 2021-03-28T00:41:48.808Z
Commit: 0063f40af9cd6dd39038d67880db1d996176c309

**Comment by relrelb** [comment] 2021-04-03 18:32
Duplicate of #3694.

**Closed by relrelb** 2021-04-03 18:32 UTC
