### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html fic plsss i want to play this game

### ISSUE THREAD

**Issue by NDRAZs** [ruffle-rs/ruffle#4652] opened 2021-06-23 11:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1624369749:1:7026)
    at std::sync::once::Once::call_once::{{closure}}::h5a73b3c37f29875c (https://uploads.ungrounded.net/ruffle_wrapper/lib/ed8fb1278950d8015875.wasm:wasm-function[1006]:0x2823c1)
    at std::sync::once::Once::call_inner::h79faa41f4d270a0b (https://uploads.ungrounded.net/ruffle_wrapper/lib/ed8fb1278950d8015875.wasm:wasm-function[974]:0x2785fb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h265fbb84ca9e6c29 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ed8fb1278950d8015875.wasm:wasm-function[3858]:0x41fac3)
    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ed8fb1278950d8015875.wasm:wasm-function[2986]:0x3bf2dc)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/ed8fb1278950d8015875.wasm:wasm-function[4067]:0x4253cc)
    at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://uploads.ungrounded.net/ruffle_wrapper/lib/ed8fb1278950d8015875.wasm:wasm-function[4216]:0x42c145)
    at core::result::unwrap_failed::h9bf99bca88ba05dc (https://uploads.ungrounded.net/ruffle_wrapper/lib/ed8fb1278950d8015875.wasm:wasm-function[3432]:0x40d521)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h99b84a46942446fa (https://uploads.ungrounded.net/ruffle_wrapper/lib/ed8fb1278950d8015875.wasm:wasm-function[593]:0x1be119)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8ad24761b1cacab3 (https://uploads.ungrounded.net/ruffle_wrapper/lib/ed8fb1278950d8015875.wasm:wasm-function[540]:0x199ad0)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1624369749%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2260d32011de1df%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-22
Channel: nightly
Built: 2021-06-22T00:10:37.922Z
Commit: e0107750996b5b3724680ead1acda0124002baea

**Comment by jhwgh1968** [comment] 2021-06-26 03:45
Just tested this with commit 6146502b1a427bd83b8073f26662abb5959da2b2 on desktop. It seems to work. Could it be the ruffle loader on the website?

**Comment by Poopooracoocoo** [comment] 2021-11-29 10:20
Link to Madness: Project Nexus (Classic) on Newgrounds:
https://www.newgrounds.com/portal/view/592473

**Comment by Poopooracoocoo** [comment] 2021-11-29 10:39
Duplicate of #4374

**Closed** 2021-11-29 10:46 UTC
Labels: duplicate, error-report
