### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by RandomKidNow89** [ruffle-rs/ruffle#8197] opened 2022-10-04 19:31 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
    at W.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.e93de3a0733afa72eadd.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::hdb3bd0839bea5e56 (wasm://wasm/017ec8f2:wasm-function[1022]:0x2a461f)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/017ec8f2:wasm-function[1486]:0x327ab0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h4e07f09da3a792ce (wasm://wasm/017ec8f2:wasm-function[4925]:0x485382)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/017ec8f2:wasm-function[3624]:0x4420c7)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/017ec8f2:wasm-function[5080]:0x488838)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/017ec8f2:wasm-function[4221]:0x46c2d2)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::h91e39f9fc515b92d (wasm://wasm/017ec8f2:wasm-function[2551]:0x3deb0e)
    at ruffle_core::display_object::render_base::h2f6e805f87e14fd0 (wasm://wasm/017ec8f2:wasm-function[1202]:0x2e4249)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hdfa161f893c1796b (wasm://wasm/017ec8f2:wasm-function[3846]:0x457f94)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1664892186%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2254484111.9275365578c3365091ca1c7903bbe4638bdd3592a9d5a2%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22633c875564539%22%2C%22NewgroundsAPI_SessionID%22%3A%22XV1fAOx8FArjAdj8Nf0sa6be7ac81c83c0eb9ce8835f1afa6d4a901ff48bYLXT%22%2C%22NewgroundsAPI_UserName%22%3A%22RandomKidNow89%22%2C%22NewgroundsAPI_UserID%22%3A10027482%2C%22ng_username%22%3A%22RandomKidNow89%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-04
Channel: nightly
Built: 2022-10-04T01:06:57.442Z
Commit: fbba7744e79c2c9b68a44ff5f480090acaec21dc
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by n0samu** [comment] 2022-10-04 19:32
Duplicate of #7978

**Closed by n0samu** 2022-10-04 19:32 UTC
Labels: duplicate, error-report
