### ISSUE TITLE
Error on Flashthemes

### ISSUE THREAD

**Issue by Legozilla** [ruffle-rs/ruffle#14987] opened 2024-01-29 01:55 UTC
# Error Info
Error name: Error
Error message: panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
Error: panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:3476:21)
    at js_sys::Error::new::h728118aa18eebd18 (wasm://wasm/038693c6:wasm-function[13695]:0xae0564)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hfc928092015e7dff (wasm://wasm/038693c6:wasm-function[11318]:0xa8b041)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/038693c6:wasm-function[6936]:0x949573)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/038693c6:wasm-function[11040]:0xa847b8)
    at core::panicking::assert_failed_inner::h003d4b5b03930769 (wasm://wasm/038693c6:wasm-function[4804]:0x83927d)
    at core::panicking::assert_failed::hc44aefcb1994ac4b (wasm://wasm/038693c6:wasm-function[11080]:0xa85dab)
    at ruffle_core::loader::Loader::load_url_loader::{{closure}}::h0a4838a1da7c6307 (wasm://wasm/038693c6:wasm-function[2876]:0x6ab240)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hb998537b6146e62e (wasm://wasm/038693c6:wasm-function[1416]:0x4430d0)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hb2787988f9230ff5 (wasm://wasm/038693c6:wasm-function[3974]:0x7ba0a2)
```
AVM2 stack:
```
    at flash.external::ExternalInterface/flash::external::ExternalInterface::addCallback()
    at anifire.player.components::PreviewPlayer/initAPI()
    at anifire.player.components::PreviewPlayer/onCreationCompleted()
    at anifire.player.components::PreviewPlayer/___PreviewPlayer_Group1_creationComplete()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at mx.core::UIComponent/dispatchEvent()
    at mx.core::UIComponent/set initialized()
    at mx.managers::LayoutManager/doPhasedInstantiation()
    at mx.managers::LayoutManager/doPhasedInstantiationCallback()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | PUSH_CONSTANTS | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: /static/animationnew/414827163ad4eb60/player.swf
Param bgcolor: #000000
Param allowFullScreen: true
Param allowScriptAccess: always
Param scale: exactfit
Param wmode: transparent
Param flashvars: movieOwner=SoomTheSponge&movieOwnerId=46536&userId=46536&movieId=jZgYETB&movieLid=0&movieTitle=Squidward%20R*pes%20SpongeBob%26%23x2F%3BGets%20Caught%26%23x2F%3BGrounded&movieDesc=&username=&uemail=&ut=-1&numContact=&apiserver=https%3A%2F%2Fflashthemes.net%2F&duration=0%3A52&playcount=4&thumbnailURL=https%3A%2F%2Fflashthemes.net%2F%2Fmovie_thumbs%2Fthumb-jZgYETB.png&copyable=0&isPublished=1&ctc=go&tlang=en_US&is_private_shared=0&autostart=1&appCode=go&is_slideshow=0&is_emessage=0&storePath=%2Fstatic%2Fstore%2F%3Cstore%3E%3Fv%3D46536&clientThemePath=%2Fstatic%2Fct%2Fad44370a650793d9%2F%3Cclient_theme%3E&animationPath=%2Fstatic%2Fanimationnew%2F414827163ad4eb60&isEmbed=1&refuser=&utm_source=&uid=&isTemplate=0&showButtons=1&chain_mids=&averageRating=5&ratingCount=5&ad=0&v=46536&endStyle=0&isWide=1&pwm=1
Param movie: /static/animationnew/414827163ad4eb60/player.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://flashthemes.net/user/46536
SWF URL: https://flashthemes.net/static/animationnew/414827163ad4eb60/player.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-29
Channel: nightly
Built: 2024-01-29T00:15:42.399Z
Commit: f2880975ba9cb16fa3a96c5c0d529cbeac81fe78
Is extension: true

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1799596

**Comment by n0samu** [comment] 2024-05-12 21:38
Duplicate of #13974

**Closed by n0samu** 2024-05-12 21:38 UTC
Labels: duplicate, error-report
