### ISSUE TITLE
Error on https://www.gameflare.com/embed/can-your-pet/

### ISSUE THREAD

**Issue by TamiadivaChoco** [ruffle-rs/ruffle#16852] opened 2024-06-23 23:14 UTC
# Error Info
Error name: Error
Error message: panicked at /rust/deps/dlmalloc-0.2.6/src/dlmalloc.rs:1192:9:
assertion failed: psize >= size + min_overhead
Error stack:
```
@https://www.gameflare.com/emulators/ruffle/core.ruffle.af73357f9eb1d07aec50.js:1:82986
wasm-stub@[wasm code]
ruffle_web.wasm.wasm-function[js_sys::Error::new::hf68801b1208761e0]@[wasm code]
ruffle_web.wasm.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h34e38fc10c81aa2e]@[wasm code]
ruffle_web.wasm.wasm-function[std::panicking::rust_panic_with_hook::h6731baa78621a747]@[wasm code]
ruffle_web.wasm.wasm-function[core::panicking::panic_fmt::h5c7ce52813e94bcd]@[wasm code]
ruffle_web.wasm.wasm-function[core::panicking::panic::h3b99507adb69386a]@[wasm code]
ruffle_web.wasm.wasm-function[__rust_realloc]@[wasm code]
ruffle_web.wasm.wasm-function[alloc::raw_vec::finish_grow::h0d4f476001a000f2]@[wasm code]
ruffle_web.wasm.wasm-function[alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h643061906cd5843c]@[wasm code]
ruffle_web.wasm.wasm-function[ruffle_web::audio::Buffer::play::h21a9526796780459]@[wasm code]
ruffle_web.wasm.wasm-function[ruffle_web::audio::Buffer::new::{{closure}}::ha0362f7ddd03b070]@[wasm code]
ruffle_web.wasm.wasm-function[<dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h05d444a68d77abe1]@[wasm code]
wasm-stub@[native code]
D@https://www.gameflare.com/emulators/ruffle/core.ruffle.af73357f9eb1d07aec50.js:1:4060
c@https://www.gameflare.com/emulators/ruffle/core.ruffle.af73357f9eb1d07aec50.js:1:3474
```

# Player Info
Allows script access: false
Renderer: WebGL 1.0
Adapter Vendor: WebKit
Adapter Renderer: WebKit WebGL
Adapter Version: WebGL 1.0
Surface samples: 1 x 
Surface size: 300 x 150

# Page Info
Page URL: https://www.gameflare.com/embed/can-your-pet/
SWF URL: https://data.gameflare.com/games/5432/VxPNmWeHcVV2uK.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Platform: MacIntel
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-06-21
Channel: nightly
Built: 2024-06-21T00:05:40.000Z
Commit: 1164dd747a544efd10b088209a85f634eb202a0c
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 45
numFrames: 1734
swfVersion: 27
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 867184

**Comment by n0samu** [comment] 2024-06-23 23:25
Duplicate of #6608. If you are an iPad user, please update your iPad to the latest OS version to fix this problem!

**Closed by n0samu** 2024-06-23 23:25 UTC
Labels: error-report
