### ISSUE TITLE
Error on https://flashmuseum.org/pre-civilization-marble-age/

### ISSUE THREAD

**Issue by darin-holloway** [ruffle-rs/ruffle#14525] opened 2023-12-26 15:42 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/daedf03/wgpu/src/backend/direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at H.n.wbg.__wbg_new_a64e3f2afc2cf2f8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.ce0adc01ed7927e33566.js:1:56204)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h391824662ddffbdc (wasm://wasm/03418dde:wasm-function[9876]:0x9d2bab)
    at std::panicking::rust_panic_with_hook::hbf46ef0245cc9589 (wasm://wasm/03418dde:wasm-function[6323]:0x8c1756)
    at core::panicking::panic_fmt::h14c85a61aa3d538e (wasm://wasm/03418dde:wasm-function[9673]:0x9cd918)
    at core::ops::function::Fn::call::hbd7fb88899a1ffb4 (wasm://wasm/03418dde:wasm-function[6587]:0x8d56a2)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h7b7e89b53525ad06 (wasm://wasm/03418dde:wasm-function[5388]:0x86ce8d)
    at <T as wgpu::context::DynContext>::device_create_texture::h407e88964b241820 (wasm://wasm/03418dde:wasm-function[7123]:0x90515c)
    at wgpu::Device::create_texture::hf25dad34262a5bc1 (wasm://wasm/03418dde:wasm-function[5513]:0x8773a2)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::hf7a0a1ac97e2d3cd (wasm://wasm/03418dde:wasm-function[2036]:0x5a28b7)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::h905709c875aec27c (wasm://wasm/03418dde:wasm-function[1504]:0x4d4c07)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1835()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Apple, ANGLE Metal Renderer: Apple M2 Pro, Unspecified Version)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://flashmuseum.org/pre-civilization-marble-age/
SWF URL: http://kongregate.com/Precivilization/bb330f71-09e8-4fec-8aa6-99f37016f009.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-26
Channel: nightly
Built: 2023-12-26T00:14:57.951Z
Commit: f60ba002402776146676d9b6e6e5d91f462f65ae
Is extension: false

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9716767

**Comment by darin-holloway** [comment] 2023-12-26 15:43
Just to note, the autogenerated report said I'm on intel mac, but I'm on an M2 mac

**Comment by n0samu** [comment] 2024-01-03 07:59
Duplicate of #13946

**Closed by n0samu** 2024-01-03 07:59 UTC
Labels: duplicate, error-report
