### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by tetraja** [ruffle-rs/ruffle#13236] opened 2023-09-18 14:35 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
339/V/n.wbg.__wbg_new_d258248ed531ff54@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.8.10/core.ruffle.3e5549e66b78cebab52b.js:1:51553
core::ops::function::FnOnce::call_once{{vtable.shim}}::h47c86d7a777c7d0f@:wasm-function[9224]:0x8f2109
std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8@:wasm-function[6059]:0x8006e9
core::panicking::panic_fmt::h2d3c5586175098d9@:wasm-function[9067]:0x8eda95
core::panicking::panic::h04b2835ef9b41d19@:wasm-function[8706]:0x8deab2
ruffle_core::display_object::movie_clip::MovieClip::preload::hce260bb4de8d08b9@:wasm-function[665]:0x1eccd9
ruffle_core::loader::Loader::preload_tick::h50f20d544766d07c@:wasm-function[1650]:0x48fa44
ruffle_web::Ruffle::tick::h968e8360581307dd@:wasm-function[793]:0x280aa7
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0909598910466b05@:wasm-function[11033]:0x9313cc
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h496e7bd9f54461c0@:wasm-function[9881]:0x90ef90
S@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.8.10/core.ruffle.3e5549e66b78cebab52b.js:1:2687
f@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.8.10/core.ruffle.3e5549e66b78cebab52b.js:1:2511

```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=&sp=0&questionSet=&r=784540&width=640&height=500&quality=high
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-10
Channel: nightly
Built: 2023-08-10T00:23:43.496Z
Commit: fb01473bb3a096d9afca4e464ce6961a45b09045
Is extension: false

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by Lord-McSweeney** [comment] 2023-09-19 02:17
Duplicate of #9972.

**Closed by Lord-McSweeney** 2023-09-19 02:17 UTC
Labels: error-report
