### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by OxnardFleaLaser** [ruffle-rs/ruffle#13746] opened 2023-10-27 20:57 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
339/V/n.wbg.__wbg_new_d258248ed531ff54@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.8.10/core.ruffle.3e5549e66b78cebab52b.js:1:51553
core::ops::function::FnOnce::call_once{{vtable.shim}}::h47c86d7a777c7d0f@:wasm-function[9224]:0x8f2109
std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8@:wasm-function[6059]:0x8006e9
core::panicking::panic_fmt::h2d3c5586175098d9@:wasm-function[9067]:0x8eda95
core::panicking::panic::h04b2835ef9b41d19@:wasm-function[8706]:0x8deab2
ruffle_core::display_object::movie_clip::MovieClip::preload::hce260bb4de8d08b9@:wasm-function[665]:0x1eccd9
ruffle_core::loader::Loader::preload_tick::h50f20d544766d07c@:wasm-function[1650]:0x48fa44
ruffle_web::Ruffle::tick::h968e8360581307dd@:wasm-function[793]:0x280aa7
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0909598910466b05@:wasm-function[11033]:0x9313cc
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h496e7bd9f54461c0@:wasm-function[9881]:0x90ef90
S@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.8.10/core.ruffle.3e5549e66b78cebab52b.js:1:2687
f@https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2023.8.10/core.ruffle.3e5549e66b78cebab52b.js:1:2511

```

# Player Info
Allows script access: true
Renderer: WebGL 2.0
Adapter Vendor: Mozilla
Adapter Renderer: Intel(R) HD Graphics 400
Adapter Version: WebGL 2.0
Surface samples: 4 x 
Surface size: 300 x 150

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=&sp=0&questionSet=&r=4789145&&width=640&height=500&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-10
Channel: nightly
Built: 2023-08-10T00:23:43.496Z
Commit: fb01473bb3a096d9afca4e464ce6961a45b09045
Is extension: false

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by Lord-McSweeney** [comment] 2023-10-27 22:07
Duplicate of #9972

**Closed by Lord-McSweeney** 2023-10-27 22:07 UTC
Labels: error-report
