### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html (Chibi Knight)

### ISSUE THREAD

**Issue by ChristianHein** [ruffle-rs/ruffle#5932] opened 2021-12-27 18:36 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1639324228%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2257630974.0a2dcb9a20ac16e214c21c43c4ba3bc2e547541ea7dd5c%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261ca02a9be000%22%2C%22NewgroundsAPI_SessionID%22%3A%22w6RM8LhDdEyg9kIX3M2N1d77a18d91e923424692f66018eb82ad60145262Ydc2%22%2C%22NewgroundsAPI_UserName%22%3A%22KillianPalmer%22%2C%22NewgroundsAPI_UserID%22%3A5433731%2C%22ng_username%22%3A%22KillianPalmer%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-12
Channel: nightly
Built: 2021-12-12T00:14:30.969Z
Commit: 1f5979f1681cd886e0e2b8245ec43190175b58ba
Is extension: false

**Comment by Poopooracoocoo** [comment] 2021-12-28 02:00
Duplicate of #3756

**Closed by Poopooracoocoo** 2021-12-28 02:00 UTC
Labels: duplicate, error-report
