### ISSUE TITLE
Error on https://skoolpermanent.herokuapp.com/5.html

### ISSUE THREAD

**Issue by Prodzof** [ruffle-rs/ruffle#8882] opened 2022-12-21 20:12 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at U.n.wbg.__wbg_new_f9bb493369a83c12 (https://skoolpermanent.herokuapp.com/ruffle/core.ruffle.adaebfa82029b93d2f23.js:1:6805)
    at std::sync::once::Once::call_once::{{closure}}::hfe7eb802e4d6ae27 (wasm://wasm/0180e3c2:wasm-function[1216]:0x2c259b)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0180e3c2:wasm-function[1492]:0x3116a3)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h3a8d5809fdb8bfde (wasm://wasm/0180e3c2:wasm-function[4898]:0x488d34)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0180e3c2:wasm-function[3600]:0x4467ba)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0180e3c2:wasm-function[5117]:0x48d438)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/0180e3c2:wasm-function[4953]:0x489ca6)
    at core::ops::function::FnOnce::call_once::h4279d884d2309c1e (wasm://wasm/0180e3c2:wasm-function[1121]:0x29e23c)
    at ruffle_core::avm1::function::Executable::exec::h9daf60fa7255aaed (wasm://wasm/0180e3c2:wasm-function[363]:0xdbb48)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h44d9f586785880a7 (wasm://wasm/0180e3c2:wasm-function[1067]:0x28a6c4)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://skoolpermanent.herokuapp.com/5.html#U2FsdGVkX18TmAIHmRhWC1OL/OdY6VqvFXQF/b+XLFB9OxMkJAoXy/ZO6/yDnri7wxlYPd1POveixWdgloOMCdfeDKP9aRUZDt+MlIwsvAc=
SWF URL: https://skoolpermanent.herokuapp.com/cdn/flash/electricman2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15183.69.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-23
Channel: nightly
Built: 2022-10-23T00:19:24.608Z
Commit: 919b38f20b0b15c5a10c704edb264797e69501da
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3275243

**Comment by n0samu** [comment] 2022-12-22 08:28
Duplicate of #4932

**Closed by n0samu** 2022-12-22 08:28 UTC
Labels: duplicate, error-report
