### ISSUE TITLE
Error on https://games.crazygames.com/en_US/electric-man/index.html

### ISSUE THREAD

**Issue by WarzeEgg** [ruffle-rs/ruffle#7216] opened 2022-06-13 14:35 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
966/n/c.wbg.__wbg_new_df6e6ab7a65c4c4d@https://files.crazygames.com/gameframe/ruffle/2022-05-17/core.ruffle.1d691580347605e7089e.js:1:7487
std::sync::once::Once::call_once::{{closure}}::ha242d4d2b43703ce@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[978]:0x290403
std::sync::once::Once::call_inner::h07d0245bef259c27@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[1431]:0x30c1c8
core::ops::function::FnOnce::call_once{{vtable.shim}}::h88636dd63977a123@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[4913]:0x462e84
std::panicking::rust_panic_with_hook::h623ac32ff431b114@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[3250]:0x408a9a
core::panicking::panic_fmt::h5118e89563022e7e@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[4994]:0x466ae2
core::panicking::panic::he88f1b1582b09c8c@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[4911]:0x462a1d
core::ops::function::FnOnce::call_once::h35b3566b432bc806@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[1069]:0x2aaf92
ruffle_core::avm1::function::Executable::exec::h58e873f674ec15e2@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[375]:0xfe9b9
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7ae2f1fde5347ee6@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[549]:0x1ac13d
ruffle_core::avm1::activation::Activation::run_actions::h71d6799f99277bcc@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[312]:0x1c316
ruffle_core::avm1::Avm1::run_stack_frame_for_action::hcb874025f49c1323@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[967]:0x28cfbf
ruffle_core::player::Player::run_actions::h6f2e92196fb67f1c@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[468]:0x16ef29
ruffle_web::Ruffle::tick::h72c32e382ff7c3dc@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[535]:0x1a2f3e
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h83f84c4202dfeef8@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[5792]:0x47ca5a
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9b5cf45bc3df0eb9@https://files.crazygames.com/gameframe/ruffle/2022-05-17/3ca577b52db5bd6a3fb0.wasm:wasm-function[5361]:0x471822
F@https://files.crazygames.com/gameframe/ruffle/2022-05-17/core.ruffle.1d691580347605e7089e.js:1:3282
c@https://files.crazygames.com/gameframe/ruffle/2022-05-17/core.ruffle.1d691580347605e7089e.js:1:2392
r@https://gameframe.crazygames.com/crazygames-gameframe-v1.bundle.js:2:324664

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.crazygames.com/en_US/electric-man/index.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-17
Channel: nightly
Built: 2022-05-17T00:16:53.792Z
Commit: ede81be4279e0af289ebc5057ebcdb12d5f99a38
Is extension: false

**Comment by n0samu** [comment] 2022-06-13 20:09
Duplicate of #4932. (This game doesn't work yet, sorry!)

**Closed by n0samu** 2022-06-13 20:09 UTC
Labels: duplicate, error-report
