### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by holaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa** [ruffle-rs/ruffle#8008] opened 2022-09-17 19:35 UTC
# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', core/src/display_object/bitmap.rs:300:44
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.09fe6dcc2dfeac6adb0c.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::ha360d592741a73b3 (wasm://wasm/017c80d6:wasm-function[1138]:0x2c087a)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/017c80d6:wasm-function[1446]:0x31ff37)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h613b00154d20bc2b (wasm://wasm/017c80d6:wasm-function[4879]:0x478cb6)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/017c80d6:wasm-function[3629]:0x4414cc)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/017c80d6:wasm-function[5069]:0x47f49b)
    at core::result::unwrap_failed::h68ab818eb89182b6 (wasm://wasm/017c80d6:wasm-function[4231]:0x464dca)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render_self::ha218e368eb1b9341 (wasm://wasm/017c80d6:wasm-function[2529]:0x3e2942)
    at ruffle_core::display_object::render_base::hc7954d410b384b2c (wasm://wasm/017c80d6:wasm-function[1157]:0x2c5c2f)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::h4a7b29cc39190024 (wasm://wasm/017c80d6:wasm-function[3852]:0x44f582)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1663418926%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226326210daf559%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-17
Channel: nightly
Built: 2022-09-17T00:14:56.303Z
Commit: 6f1509d4cdf4f1076fc7554995bc55c7016d828d
Is extension: false

# Metadata
width: 850
height: 530
frameRate: 30
numFrames: 30
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20491352

**Comment by holaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa** [comment] 2022-09-17 19:36
delete this bug and i will play please

**Comment by holaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa** [comment] 2022-09-17 19:36
delete it NOW

**Comment by holaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa** [comment] 2022-09-17 19:36
DELETE IT N O W

**Comment by n0samu** [comment] 2022-09-18 05:19
Duplicate of #7978

**Closed by n0samu** 2022-09-18 05:19 UTC
Labels: duplicate, error-report

**Comment by p0008874** [comment] 2022-09-18 06:32
> DELETE IT N O W

![20220908_101101](https://user-images.githubusercontent.com/75534590/190889033-216f3728-ddc5-46f3-9e32-9411ba7fad64.jpg)
