### ISSUE TITLE
cursor is stuck with the slider

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#7903] opened 2022-09-07 00:46 UTC
### Describe the bug

![GIF3](https://user-images.githubusercontent.com/98996990/188764207-821ee540-df4e-4c2d-ac56-c6e1bc3ddae1.gif)
[blackbody.zip](https://github.com/ruffle-rs/ruffle/files/9501723/blackbody.zip)

### Expected behavior

![GIF4](https://user-images.githubusercontent.com/98996990/188764425-328c31ea-ecbe-4afe-82c1-4cf52382d2ba.gif)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

![image](https://user-images.githubusercontent.com/98996990/188763937-2f94d18a-7580-460f-b1ee-7831a1959612.png)

**Comment by n0samu** [comment] 2022-09-07 03:04
Seems like the `EndDrag` action attached to the button is somehow not taking effect. I'm not sure why.

**Comment by hatal175** [comment] 2022-09-19 12:16
OK, so the issue is that the button being dragged keeps getting loaded and unloaded (id 32) constantly. After it gets unloaded the mouse update process removes the mouse_down_object since it is removed and then the release event has nothing to callback to.

You can actually make it work if you click fast enough so the button doesn't manage to unload.

Unfortunately, I'm not familiar enough with flash internals and frame behaviors to say what exactly is wrong in ruffle's implementation.

**Comment by hatal175** [comment] 2022-09-19 16:59
Maybe related to  #1108

**Comment by n0samu** [comment] 2023-07-14 23:51
Fixed by #10862

**Closed by n0samu** 2023-07-14 23:51 UTC
Labels: bug, avm1
