### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by Omega498** [ruffle-rs/ruffle#12964] opened 2023-08-26 21:04 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:348:26
    at imports.wbg.__wbg_new_d258248ed531ff54 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2403:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf23a54a5332a422a (wasm://wasm/030380a6:wasm-function[9262]:0x906ba1)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (wasm://wasm/030380a6:wasm-function[6028]:0x807f1a)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (wasm://wasm/030380a6:wasm-function[9103]:0x902288)
    at core::panicking::panic::hfd6e422134ee8ce5 (wasm://wasm/030380a6:wasm-function[8730]:0x8f29a3)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h6b273528e0463608 (wasm://wasm/030380a6:wasm-function[666]:0x1f334b)
    at ruffle_core::loader::Loader::preload_tick::h7662cc9427f379d4 (wasm://wasm/030380a6:wasm-function[1641]:0x48c3f6)
    at ruffle_web::Ruffle::tick::ha0c8b98648b0bafa (wasm://wasm/030380a6:wasm-function[757]:0x2694d5)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h7571557482383641 (wasm://wasm/030380a6:wasm-function[11213]:0x948ff5)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hdc8c70efb7f87d1c (wasm://wasm/030380a6:wasm-function[9913]:0x923b3d)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1034&nc_referer=&age=1&hiscore=&sp=0&questionSet=&r=9803218&&width=640&height=500&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_18.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-26
Channel: nightly
Built: 2023-08-26T00:22:29.980Z
Commit: b456296769e3232ca41e0da369c11e2181404733
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 18
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by Lord-McSweeney** [comment] 2023-08-27 00:34
Duplicate of #9972.

**Closed by Lord-McSweeney** 2023-08-27 00:34 UTC
Labels: error-report
