### ISSUE TITLE
Error on http://www.stickmanjuegos.com/jugar/electricman/

### ISSUE THREAD

**Issue by vjp-AlanSdlt** [ruffle-rs/ruffle#6408] opened 2022-03-06 21:43 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:1:7570)
    at std::sync::once::Once::call_once::{{closure}}::h04c6018a30aae0b2 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/37414a2c1295e4921309.wasm:wasm-function[1023]:0x2c1985)
    at std::sync::once::Once::call_inner::h51a70f81ef530383 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/37414a2c1295e4921309.wasm:wasm-function[1459]:0x32fd41)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h629785d4908f37da (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/37414a2c1295e4921309.wasm:wasm-function[4922]:0x482981)
    at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/37414a2c1295e4921309.wasm:wasm-function[3239]:0x4256ab)
    at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/37414a2c1295e4921309.wasm:wasm-function[5209]:0x48ea8a)
    at core::panicking::panic::h5d6906e2c1099660 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/37414a2c1295e4921309.wasm:wasm-function[4919]:0x4824a8)
    at core::ops::function::FnOnce::call_once::hccd13e3d375a8a6e (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/37414a2c1295e4921309.wasm:wasm-function[1106]:0x2d6f05)
    at ruffle_core::avm1::function::Executable::exec::h79701af978203eb9 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/37414a2c1295e4921309.wasm:wasm-function[384]:0x10bb19)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hcdf54ba60d7772d4 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/37414a2c1295e4921309.wasm:wasm-function[433]:0x158949)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.stickmanjuegos.com/jugar/electricman/
SWF URL: http://www.stickmanjuegos.com/games/electricman.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-03-04
Channel: nightly
Built: 2022-03-04T00:15:35.142Z
Commit: 31446785f9804fcd8090da4670a9f4038a558e6e
Is extension: true

**Comment by relrelb** [comment] 2022-03-06 22:05
Duplicate of #4932.

**Closed by relrelb** 2022-03-06 22:05 UTC
Labels: error-report
