### ISSUE TITLE
Type gradients broken, Super Mario 63 Game crashes, plays incorrectly

### ISSUE THREAD

**Issue by BrynnEvans** [ruffle-rs/ruffle#2448] opened 2021-01-13 06:08 UTC
This is the game:
https://www.newgrounds.com/portal/view/498969

Here is a video walkthrough, what the game SHOULD look and play like.
https://www.youtube.com/watch?v=UcMTA-3zhuw

Issues:
- At the beginning of the game, original gradients for text like "Runouw.com" and "Start" are not gradients like they used to be, just flat color.
- The tutorial level crashed before I could even make it to the second tutorial level screen. Twice.
- The third time I played, when about [here](https://youtu.be/UcMTA-3zhuw?t=176), I could not ground pound (Z key) and destroy the boxes. Then I realized, Mario was losing health and could swim in the air - it was like he was underwater! The level of the invisible water does not quite reach the top of the hill.
- The game lags and causes my fan to kick on. I have a newly refurbished laptop with an i7 6th gen graphics card and 16GB of RAM; I also have Office and Adobe programs open, but they haven't caused the fan to kick in like this game did. I checked my Task Manager. I was running the game in Chrome with the browser extension. As I type, TM says Chrome takes up 1,666 MB of memory. When the game was running, it got over 4,600 MB of memory.
- I'm worried Ruffle might not save my levels. I'm not sure, I haven't got that far.

Thank you for your wonderful efforts to keep Flash alive, thousands of people like me appreciate your work. :)

**Comment by Futurama39** [comment] 2021-01-14 14:55
The tutorial level freezing is a part of #1347

**Comment by poudink** [comment] 2022-04-16 20:43
In regards to the gradient stuff, I felt like creating comparison screenshots since the affected elements could actually look fine at first glance to those who haven't seen the game in Flash Player. I picked the file select for the comparison due to its particularly large amount of buttons.
This is how Ruffle displays the menu elements:
![SM63 Ruffle](https://user-images.githubusercontent.com/29778535/163690660-585dea6d-27b5-4821-8e7f-a07bb41c89be.png)
This how how it's supposed to look:
![SM63 Projector](https://user-images.githubusercontent.com/29778535/163690666-d4a923ad-bf7c-46fb-a5e7-3221787bc456.png)
Lightspark's closer getting them right, but it adds a ton of blur:
![SM63 Lightspark](https://user-images.githubusercontent.com/29778535/163690683-7039c7c2-fc0e-479e-a054-d4d6343f28f0.png)

**Comment by n0samu** [comment] 2023-04-01 00:55
Gameplay issues have been fixed by #10330. Rendering issues are caused by unimplemented filter effects. Let's track that in #5567.

**Closed by n0samu** 2023-04-01 00:55 UTC
Labels: bug, rendering
