### ISSUE TITLE
Error on http://swordandsandals.top/swords-and-sandals-2-full-version/

### ISSUE THREAD

**Issue by marcio-gomes-neto-p2f** [ruffle-rs/ruffle#15220] opened 2024-02-14 20:56 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left.


    at N.n.wbg.__wbg_new_3a66822ed076951c (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d7a66e39a50acd53556d.js:1:72830)
    at js_sys::Error::new::he329e38f5ae64355 (wasm://wasm/03914afa:wasm-function[13733]:0xb05b81)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9929706439805e04 (wasm://wasm/03914afa:wasm-function[11349]:0xaaffa7)
    at std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b (wasm://wasm/03914afa:wasm-function[6918]:0x96ef85)
    at core::panicking::panic_fmt::h87755523850ece9e (wasm://wasm/03914afa:wasm-function[11065]:0xaa95b2)
    at core::ops::function::Fn::call::h5add11a6d19ea2d0 (wasm://wasm/03914afa:wasm-function[7245]:0x9873c5)
    at wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::hecd8fc46229ee706 (wasm://wasm/03914afa:wasm-function[5737]:0x902e2a)
    at <T as wgpu::context::DynContext>::device_create_buffer::hc11cd6ece83a304a (wasm://wasm/03914afa:wasm-function[7990]:0x9cfc75)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h3c59895a60e850b0 (wasm://wasm/03914afa:wasm-function[2024]:0x57fe0d)
    at ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::h9ad6bf87be24e831 (wasm://wasm/03914afa:wasm-function[7961]:0x9c7e08)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Mesa Intel(R) Graphics (ADL GT2), OpenGL 4.6)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: http://swordandsandals.top/swords-and-sandals-2-full-version/
SWF URL: http://swordandsandals.top/wp-content/uploads/swords-and-sandals-2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-02-13
Channel: nightly
Built: 2024-02-13T00:15:35.468Z
Commit: 555fcfa9c42ecf180a838bf2c9aca0d97ec45496
Is extension: false

# Metadata
width: 640
height: 420
frameRate: 30
numFrames: 277
swfVersion: 8
backgroundColor: #FFCC66
isActionScript3: false
uncompressedLength: 5282134

**Comment by evilpie** [comment] 2024-02-14 21:05
Duplicate of #15082.

**Closed by evilpie** 2024-02-14 21:05 UTC
Labels: error-report, wgpu-oom
