### ISSUE TITLE
Error on http://www.digyourowngrave.com/rebuild/

### ISSUE THREAD

**Issue by ButtNumz** [ruffle-rs/ruffle#2544] opened 2021-01-15 09:35 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
    at Object.X (chrome-extension://gbpdgjjlhjfmncnnjcpmfheplegflcfh/dist/core.ruffle.js:1:21334)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:38348)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://gbpdgjjlhjfmncnnjcpmfheplegflcfh/dist/1153537a96484f518eaf.module.wasm:wasm-function[1279]:0x2649fb)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://gbpdgjjlhjfmncnnjcpmfheplegflcfh/dist/1153537a96484f518eaf.module.wasm:wasm-function[1547]:0x295a73)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://gbpdgjjlhjfmncnnjcpmfheplegflcfh/dist/1153537a96484f518eaf.module.wasm:wasm-function[4311]:0x3699c8)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://gbpdgjjlhjfmncnnjcpmfheplegflcfh/dist/1153537a96484f518eaf.module.wasm:wasm-function[3309]:0x342c41)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://gbpdgjjlhjfmncnnjcpmfheplegflcfh/dist/1153537a96484f518eaf.module.wasm:wasm-function[3918]:0x35f7ca)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://gbpdgjjlhjfmncnnjcpmfheplegflcfh/dist/1153537a96484f518eaf.module.wasm:wasm-function[4654]:0x36f065)
    at rust_begin_unwind (chrome-extension://gbpdgjjlhjfmncnnjcpmfheplegflcfh/dist/1153537a96484f518eaf.module.wasm:wasm-function[4528]:0x36d6e5)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://gbpdgjjlhjfmncnnjcpmfheplegflcfh/dist/1153537a96484f518eaf.module.wasm:wasm-function[4656]:0x36f0c9)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.digyourowngrave.com/rebuild/
SWF URL: http://www.digyourowngrave.com/content/swfs/rebuild.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-15
Channel: nightly
Built: 2021-01-15T01:03:45.335Z
Commit: 09a48a71d8608803fd5dba4343c5f10c928f9652

**Comment by n0samu** [comment] 2022-10-04 04:20
Duplicate of #2444

**Closed by n0samu** 2022-10-04 04:20 UTC
Labels: duplicate, error-report
