### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by NitroGAM3R-476** [ruffle-rs/ruffle#4655] opened 2021-06-23 18:23 UTC
# Error Info
Error name: TypeError
Error message: Could not download wasm module
Error stack:
```
TypeError: Could not download wasm module
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1624369749%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2271493191.7ffa6e6ba73d067ad8d432132eb64c202984bed304e371%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2260d37bbc89068%22%2C%22NewgroundsAPI_SessionID%22%3A%22XVIp1OYB0jue58FEc0Rof8e3cd73514bbf6f68812c8720d7bef595108d7fICtB%22%2C%22NewgroundsAPI_UserName%22%3A%22NitroGAM3R476%22%2C%22NewgroundsAPI_UserID%22%3A9187423%2C%22ng_username%22%3A%22NitroGAM3R476%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13904.55.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.102 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-22
Channel: nightly
Built: 2021-06-22T00:10:37.922Z
Commit: e0107750996b5b3724680ead1acda0124002baea

**Comment by relrelb** [comment] 2021-07-16 10:34
Duplicate of #4250.

**Closed by relrelb** 2021-07-16 10:34 UTC
