### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by ChristianBeninca** [ruffle-rs/ruffle#6982] opened 2022-05-14 21:56 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:862:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.22cc36667e255414ec44.js:1:7487)
    at std::sync::once::Once::call_once::{{closure}}::hc3464e04dbb9beda (https://uploads.ungrounded.net/ruffle_wrapper/lib/b8d28947a2b0a8f19725.wasm:wasm-function[978]:0x290346)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b8d28947a2b0a8f19725.wasm:wasm-function[1431]:0x30c0fd)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h44f701de063d4daa (https://uploads.ungrounded.net/ruffle_wrapper/lib/b8d28947a2b0a8f19725.wasm:wasm-function[4913]:0x462de0)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b8d28947a2b0a8f19725.wasm:wasm-function[3250]:0x40896f)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://uploads.ungrounded.net/ruffle_wrapper/lib/b8d28947a2b0a8f19725.wasm:wasm-function[4994]:0x466a3e)
    at core::panicking::panic::he88f1b1582b09c8c (https://uploads.ungrounded.net/ruffle_wrapper/lib/b8d28947a2b0a8f19725.wasm:wasm-function[4911]:0x462979)
    at core::ops::function::FnOnce::call_once::h0e85a184fa37f64b (https://uploads.ungrounded.net/ruffle_wrapper/lib/b8d28947a2b0a8f19725.wasm:wasm-function[1069]:0x2ab021)
    at ruffle_core::avm1::function::Executable::exec::h114e6421d0b212e0 (https://uploads.ungrounded.net/ruffle_wrapper/lib/b8d28947a2b0a8f19725.wasm:wasm-function[378]:0x102b13)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h39023dca8cfb590d (https://uploads.ungrounded.net/ruffle_wrapper/lib/b8d28947a2b0a8f19725.wasm:wasm-function[558]:0x1b4546)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1652537349%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2262801f837c2e6%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36 OPR/85.0.4341.79
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-14
Channel: nightly
Built: 2022-05-14T00:17:29.589Z
Commit: a453aa73afbd8d8ab509bd7cbd2366a024ca8649
Is extension: false

**Comment by relrelb** [comment] 2022-05-17 06:33
Duplicate of #3756.

**Closed by relrelb** 2022-05-17 06:33 UTC
Labels: error-report
