### ISSUE TITLE
Error on https://www.neopets.com/games/play_flash.phtml

### ISSUE THREAD

**Issue by eleanor-collier** [ruffle-rs/ruffle#10894] opened 2023-04-30 22:25 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:350:26
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/library.rs:350:26
    at imports.wbg.__wbg_new_15d3966e9981a196 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2258:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hd28f65a61f685e47 (wasm://wasm/02b73dd6:wasm-function[8393]:0x8100f7)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02b73dd6:wasm-function[5501]:0x7320ed)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02b73dd6:wasm-function[8248]:0x80a975)
    at core::panicking::panic::hea78c4e8b318407d (wasm://wasm/02b73dd6:wasm-function[7555]:0x7d0677)
    at ruffle_core::display_object::movie_clip::MovieClip::preload::h30e5eba151b7c315 (wasm://wasm/02b73dd6:wasm-function[621]:0x1ed892)
    at ruffle_core::loader::Loader::preload_tick::h7e906a83ab247c31 (wasm://wasm/02b73dd6:wasm-function[726]:0x280e95)
    at ruffle_web::Ruffle::tick::h3ce578a805835bf7 (wasm://wasm/02b73dd6:wasm-function[720]:0x275dab)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hf213caa0e24967b5 (wasm://wasm/02b73dd6:wasm-function[10111]:0x851467)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hbde675465be1b1f1 (wasm://wasm/02b73dd6:wasm-function[8985]:0x827c39)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=1031&nc_referer=&age=1&hiscore=&sp=0&questionSet=&r=7553563&&width=600&height=600&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np8_loader_v3_24.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-30
Channel: nightly
Built: 2023-04-30T00:18:39.359Z
Commit: 69134d7d8d4a4c29a71e4f15f99c40fb7c6e6967
Is extension: true

# Metadata
width: 1000
height: 1000
frameRate: 24
numFrames: 21
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 9994

**Comment by n0samu** [comment] 2023-04-30 22:28
Duplicate of #10614

**Closed by n0samu** 2023-04-30 22:28 UTC
Labels: duplicate, error-report
