### ISSUE TITLE
Error on http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm

### ISSUE THREAD

**Issue by dan-fodorean** [ruffle-rs/ruffle#5157] opened 2021-08-27 22:56 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:849:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (http://www.freeworldgroup.com/ruffle/ruffle.js:1:7576)
    at std::sync::once::Once::call_once::{{closure}}::hdc00d7da63128799 (http://www.freeworldgroup.com/ruffle/5c07dd6ff5768c700aa3.wasm:wasm-function[916]:0x24529f)
    at std::sync::once::Once::call_inner::h96e3a490169c6c27 (http://www.freeworldgroup.com/ruffle/5c07dd6ff5768c700aa3.wasm:wasm-function[1171]:0x2a2cd1)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h34a21969c4579926 (http://www.freeworldgroup.com/ruffle/5c07dd6ff5768c700aa3.wasm:wasm-function[4040]:0x42f705)
    at std::panicking::rust_panic_with_hook::h2d9079427a2d996a (http://www.freeworldgroup.com/ruffle/5c07dd6ff5768c700aa3.wasm:wasm-function[2906]:0x3c434e)
    at rust_begin_unwind (http://www.freeworldgroup.com/ruffle/5c07dd6ff5768c700aa3.wasm:wasm-function[4254]:0x4353c8)
    at core::panicking::panic_fmt::h1fea623755fffed7 (http://www.freeworldgroup.com/ruffle/5c07dd6ff5768c700aa3.wasm:wasm-function[4410]:0x43c175)
    at core::panicking::panic::h38cac710b5048ca0 (http://www.freeworldgroup.com/ruffle/5c07dd6ff5768c700aa3.wasm:wasm-function[4189]:0x432922)
    at core::ops::function::FnOnce::call_once::ha40e6113ced28e4c (http://www.freeworldgroup.com/ruffle/5c07dd6ff5768c700aa3.wasm:wasm-function[892]:0x23ae85)
    at ruffle_core::avm1::function::Executable::exec::h6321fa6c8b3e93cb (http://www.freeworldgroup.com/ruffle/5c07dd6ff5768c700aa3.wasm:wasm-function[384]:0xe5e58)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm
SWF URL: http://www.freeworldgroup.com/games6/electricman2/electricman2hs_fwg.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-27
Channel: nightly
Built: 2021-08-27T00:10:47.557Z
Commit: b5ee94aff1ea6c036a174456680733e2709e91d0
Is extension: false

**Comment by relrelb** [comment] 2021-08-28 15:22
Duplicate of #5156.

**Closed by relrelb** 2021-08-28 15:22 UTC
