### ISSUE TITLE
Error on https://www.ridesims.com/ride-simulators/Sky-Scream

### ISSUE THREAD

**Issue by ajohnr98** [ruffle-rs/ruffle#2956] opened 2021-01-29 14:53 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://ridesims.com/ruffle/ruffle.js?a=2021-01-29-02-52:1:6227)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://www.ridesims.com/ruffle/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[1278]:0x257ab0)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://www.ridesims.com/ruffle/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[1534]:0x28698b)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://www.ridesims.com/ruffle/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[4361]:0x35d1a6)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://www.ridesims.com/ruffle/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[3307]:0x334ced)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://www.ridesims.com/ruffle/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[3919]:0x351ba6)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://www.ridesims.com/ruffle/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[4693]:0x3624d7)
    at rust_begin_unwind (https://www.ridesims.com/ruffle/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[4572]:0x360ca9)
    at std::panicking::begin_panic_fmt::h96153d9dc0e882ed (https://www.ridesims.com/ruffle/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[4662]:0x361f52)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hfb809fa44aef3c83 (https://www.ridesims.com/ruffle/c2b443b5d3c1e95c719f5c7fa8f05fa4.wasm:wasm-function[1474]:0x27cb5a)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.ridesims.com/ride-simulators/Sky-Scream
SWF URL: https://www.ridesims.com/sites/default/files/2021-01/SkyScreamv1.5.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; SM-T500) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-28
Channel: nightly
Built: 2021-01-28T00:36:59.079Z
Commit: 5e0527c59944d5888128c63f37d23880fdb0c6ff

**Comment by relrelb** [comment] 2021-08-24 15:27
Duplicate of #2894.

**Closed by relrelb** 2021-08-24 15:27 UTC
