### ISSUE TITLE
Error on https://g.vseigru.net/dasha1/igry-strelyalki/igra-bezumie-proekt-neksus/

### ISSUE THREAD

**Issue by MaxXROBLOX** [ruffle-rs/ruffle#4943] opened 2021-07-28 16:43 UTC
Error info:
#----------#
I just played madness: project nexus want to play arena combat i press "New game" and i got error!

Error name: Arena combat bug

**Comment by relrelb** [comment] 2021-09-05 21:05
Duplicate of #3791.

**Closed by relrelb** 2021-09-05 21:05 UTC
