### ISSUE TITLE
(Learn to fly 2) floating penguin

### ISSUE THREAD

**Issue by SuperCrafter015** [ruffle-rs/ruffle#7785] opened 2022-08-28 15:42 UTC
### Describe the bug

Whenever you start the game everything seems fine until the game starts. After you get through the introduction the penguin that's supposed to slide down the ramp instead slowly ascends from the ground
![Screenshot (185)](https://user-images.githubusercontent.com/112334148/187082432-4be304d0-e69f-4c35-ab10-1a2f1ac05edb.png)
![Screenshot (184)](https://user-images.githubusercontent.com/112334148/187082434-e22efc79-aa34-417e-9bfa-46227eb4be53.png)
 

### Expected behavior

The penguin would slide down the ramp and begin day 1

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Google Chrome Version 104.0.5112.102 (Official Build) (64-bit)

### Additional information

I believe this game uses AVM1 and AVM2 since everything else seems fine and it was released in 2012

**Comment by n0samu** [comment] 2022-08-28 21:50
Duplicate of #1839

**Closed by n0samu** 2022-08-28 21:50 UTC
Labels: bug, duplicate
