### ISSUE TITLE
Unexpected behaviour on https://www.experimonkey.com/ruffle/learn-to-fly-2

### ISSUE THREAD

**Issue by GiovanniLoureiro** [ruffle-rs/ruffle#4592] opened 2021-06-16 15:15 UTC
**Describe the bug**
Issue faced when running the game  (no error message), title screen and cutscenes work fine, but when starting an actual level penguin just slowly floats upwards instead of moving. Is completely unresponsive to keyboard/mouse input

**Expected behaviour**
Penguin goes down the hill and you fly him around (i.e. playing the game)

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Chrome Extension, Flash Player 2021 version 2.0.1

**What platform are you using?**
macOS Big Sur 11.4, Google Chrome Version 91.0.4472.101 (Official Build) (arm64)

**Comment by relrelb** [comment] 2021-06-19 10:03
Duplicate of #1839.

**Closed by relrelb** 2021-06-19 10:03 UTC
Labels: bug
