### ISSUE TITLE
Error on https://extrememath.net/swf.html

### ISSUE THREAD

**Issue by SAVAGENOCHILL06** [ruffle-rs/ruffle#6884] opened 2022-05-04 18:06 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.d9ac1083cc51964a91e9.js:1:6879)
    at std::sync::once::Once::call_once::{{closure}}::h34724c5a615dd91e (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.4/be50d821cdf1f4d4809f.wasm:wasm-function[1004]:0x29ef2c)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.4/be50d821cdf1f4d4809f.wasm:wasm-function[1455]:0x317ed5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h1cc7f1c9e77acd09 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.4/be50d821cdf1f4d4809f.wasm:wasm-function[4941]:0x46f5d0)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.4/be50d821cdf1f4d4809f.wasm:wasm-function[3268]:0x413e09)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.4/be50d821cdf1f4d4809f.wasm:wasm-function[5026]:0x47373d)
    at core::panicking::panic::he88f1b1582b09c8c (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.4/be50d821cdf1f4d4809f.wasm:wasm-function[4939]:0x46f169)
    at core::ops::function::FnOnce::call_once::h772193ecfce46049 (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.4/be50d821cdf1f4d4809f.wasm:wasm-function[1089]:0x2b77f1)
    at ruffle_core::avm1::function::Executable::exec::h522b8fe3a8dee5fb (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.4/be50d821cdf1f4d4809f.wasm:wasm-function[390]:0x129049)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf8e7067c9dc9700a (https://unpkg.com/@ruffle-rs/ruffle@0.1.0-nightly.2022.5.4/be50d821cdf1f4d4809f.wasm:wasm-function[370]:0x10c970)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://extrememath.net/swf.html?notebook=electricman2
SWF URL: https://extrememath.net/swffiles/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14526.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.133 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-04
Channel: nightly
Built: 2022-05-04T00:18:20.135Z
Commit: d1d6b56615ef701794c2b642ffb8a5b986f874e8
Is extension: false

**Comment by relrelb** [comment] 2022-05-06 14:25
Duplicate of #4932.

**Closed by relrelb** 2022-05-06 14:25 UTC
Labels: error-report
