### ISSUE TITLE
Fault Line From Nitrome is Impossible to Play

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [ruffle-rs/ruffle#3794] opened 2021-03-25 13:30 UTC
**Describe the bug**
It Keeps Looping the animation

**Expected behavior**
A Nice Game

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

**What platform are you using?**
Windows Embedded 8.1 Industry Pro, Chrome 89.0.4389.90

**Comment by llacb47** [comment] 2021-03-25 14:45
There is no useful information here.

**Comment by danielhjacobs** [comment] 2021-03-25 21:59
Assuming http://www.nitrome.com/games/faultline/, the game won't load initially due to CORS see #2201. If you download http://cdn.nitrome.com/games/the-unit-v2.swf directly and load it into the Ruffle demo, you see the warning "This SWF contains ActionScript 3 which is not yet supported by Ruffle. The movie may not work as intended.", and the errors: "AVM2 error: TypeError: undefined is not an Object" and "Got TypeError: undefined is not an Object when constructing AVM2 side of display object". AS3 is unsupported. See #1368.

**Comment by mero09-99** [comment] 2022-10-01 14:26
The unit v2 swf isn't the game.
its a dummy swf, the game loads later.

**Comment by n0samu** [comment] 2022-10-03 08:26
Interestingly, this version of the game boots to the menu: http://www.notdoppler.com/faultline.php
But the levels on the level select screen are unselectable.

**Comment by mero09-99** [comment] 2022-10-08 01:20
this is because faultline, like a few other nitrome games, relies on external level data, with usually hashed names, in xml

**Comment by n0samu** [comment] 2022-10-08 01:58
> this website must have waited for nitrome's site to load the real swf, hacked past the sitelock and saw the title, and assumed the rest would work

No, the game works in Flash Player, so it's a Ruffle issue

**Comment by mero09-99** [comment] 2022-10-08 02:20
interesting
is Ruffle imcompatable with loading levels (xml files)?

**Comment by n0samu** [comment] 2022-10-08 03:07
The version of the game that I linked doesn't load levels via XML files, so it's not that.

**Comment by Lord-McSweeney** [comment] 2023-01-03 06:03
http://cdn.nitrome.com/games/the-unit-v2.swf directly now works a little better, but requires `encodeURIComponent`.

**Comment by Lord-McSweeney** [comment] 2023-02-25 23:55
As #9647 has been merged, the game can be played. There are some performance issues, though, and an error:
```
ERROR ruffle_core::avm2::activation: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: ::length)
	at com.nitrome.folding::Level/getFoldedPoint()
	at com.nitrome.folding::HintProjectorTile/advance()
	at com.nitrome.folding::HintProjectorTile/create()
	at com.nitrome.folding::Level/create()
	at com.nitrome.folding::Controller$/onLoadComplete()
	at com.nitrome.folding::Controller$/startLevel()
	at Faultline_fla::MainTimeline/frame72()
	at flash.display::MovieClip/flash::display::MovieClip::gotoAndStop()
	at MethodInfo-1156()
	at com.nitrome.game::Transition/doNextFrame()
	at com.nitrome.game::Transition/frame21()
```

**Comment by n0samu** [comment] 2023-02-26 03:12
Closing since the original issue is fixed

**Closed by n0samu** 2023-02-26 03:12 UTC
Labels: bug, avm2, xml
