### ISSUE TITLE
Error on https://sz-games.github.io/games/Flash.html

### ISSUE THREAD

**Issue by G1A1B1E** [ruffle-rs/ruffle#13257] opened 2023-09-20 15:06 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 0..12 would end up overrunning the bounds of the Source texture of X size 11

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 0..12 would end up overrunning the bounds of the Source texture of X size 11

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.48203a5f2ed037c39122.js:1:51844)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h57def9a78408b97f (wasm://wasm/030b6f12:wasm-function[9328]:0x92377c)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/030b6f12:wasm-function[6097]:0x8249b4)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/030b6f12:wasm-function[9164]:0x91ed93)
    at core::ops::function::Fn::call::h9c7f5d1e973a4a59 (wasm://wasm/030b6f12:wasm-function[6305]:0x830bab)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h09222b538ec8307d (wasm://wasm/030b6f12:wasm-function[4932]:0x78fa32)
    at wgpu::backend::direct::Context::handle_error::hf547d7fa4fc41168 (wasm://wasm/030b6f12:wasm-function[2530]:0x5df832)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h8036b8dcb3f54166 (wasm://wasm/030b6f12:wasm-function[6684]:0x85cbb2)
    at wgpu::CommandEncoder::copy_texture_to_buffer::h52173ae4f44f48b2 (wasm://wasm/030b6f12:wasm-function[5718]:0x80608c)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h644e2d11edbcc2b0 (wasm://wasm/030b6f12:wasm-function[1573]:0x485a0d)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://sz-games.github.io/games/Flash.html?game=https://sz-games.github.io/FlashGames/learntofly2.swf
SWF URL: https://sz-games.github.io/FlashGames/learntofly2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-20
Channel: nightly
Built: 2023-09-20T00:23:27.918Z
Commit: 5b9806bdb3b9e6eee5331553ff3003a718229be1
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 33
numFrames: 46
swfVersion: 10
backgroundColor: #2379B1
isActionScript3: false
uncompressedLength: 7048724

**Comment by torokati44** [comment] 2023-11-10 23:40
Basically a duplicate of #13164.

**Closed by torokati44** 2023-11-10 23:40 UTC
Labels: error-report
