### ISSUE TITLE
Error on https://www.gameflare.com/embed/jacksmith/

### ISSUE THREAD

**Issue by pop21cul** [ruffle-rs/ruffle#13381] opened 2023-09-30 21:12 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 2..5519 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:3056:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://www.gameflare.com/emulators/ruffle/core.ruffle.36e0ad93a02e9b11458f.js:1:51844)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haba14e1739cb566b (wasm://wasm/032984fe:wasm-function[9703]:0x98da3b)
    at std::panicking::rust_panic_with_hook::he017c20114c82dea (wasm://wasm/032984fe:wasm-function[6330]:0x883478)
    at core::panicking::panic_fmt::h7859ddfa497c0e61 (wasm://wasm/032984fe:wasm-function[9536]:0x988faa)
    at core::ops::function::Fn::call::hb22928db381f2032 (wasm://wasm/032984fe:wasm-function[6546]:0x88ffcb)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h2e9011c163e8e180 (wasm://wasm/032984fe:wasm-function[5117]:0x7e7939)
    at wgpu::backend::direct::Context::handle_error::hef02f17debce92eb (wasm://wasm/032984fe:wasm-function[2609]:0x623cc6)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h79c33bd606b17a79 (wasm://wasm/032984fe:wasm-function[6944]:0x8bd07d)
    at wgpu::CommandEncoder::copy_texture_to_buffer::hef05d2fd822d2f6b (wasm://wasm/032984fe:wasm-function[5945]:0x8648c2)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h9560ef27bbc1e536 (wasm://wasm/032984fe:wasm-function[1606]:0x4b069c)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at swordGame.models::LobbySoldier/blitSoldier()
    at swordGame.models::LobbySoldier/swapToSprite()
    at swordGame.models::LobbySoldier/walkCustomer()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.gameflare.com/embed/jacksmith/
SWF URL: https://data.gameflare.com/games/3054/iOdVF4I6Kwnblp.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-29
Channel: nightly
Built: 2023-09-29T00:21:45.562Z
Commit: ec7a8ac6453cbc48d12aaffc125dd4de79340f5b
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 6578963

**Comment by evilpie** [comment] 2024-04-09 15:23
Duplicate of #13085.

**Closed by evilpie** 2024-04-09 15:23 UTC
Labels: error-report
