### ISSUE TITLE
Error on https://www.giercownia.pl/gra/36/electricman_2_the_tournament_of_voltagen/

### ISSUE THREAD

**Issue by Sp4c3DucK** [ruffle-rs/ruffle#6115] opened 2022-01-23 19:45 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.giercownia.pl/public/js/ruffle/ruffle.js:1:6703)
    at std::sync::once::Once::call_once::{{closure}}::h2a5914e357df5b02 (https://www.giercownia.pl/public/js/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[990]:0x30f0ab)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://www.giercownia.pl/public/js/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[1195]:0x354b94)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b08ffde388f7cc2 (https://www.giercownia.pl/public/js/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[4712]:0x505beb)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://www.giercownia.pl/public/js/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[3248]:0x4b1c8a)
    at rust_begin_unwind (https://www.giercownia.pl/public/js/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[4776]:0x507340)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://www.giercownia.pl/public/js/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[4991]:0x512348)
    at core::panicking::panic::hec1fc057bd0baf0b (https://www.giercownia.pl/public/js/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[4709]:0x505451)
    at core::ops::function::FnOnce::call_once::h36ed99506270436a (https://www.giercownia.pl/public/js/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[1041]:0x32179e)
    at ruffle_core::avm1::function::Executable::exec::h724e0789f6eb133c (https://www.giercownia.pl/public/js/ruffle/c5c02c4e65c1c4423a97.wasm:wasm-function[434]:0x184fa3)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.giercownia.pl/gra/36/electricman_2_the_tournament_of_voltagen/
SWF URL: https://gry.giercownia.pl/gry/e/1170876158_electric-man-2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 OPR/82.0.4227.50
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-22
Channel: nightly
Built: 2021-12-22T00:14:15.814Z
Commit: 74ab24c0c3345025a1b7297c526c37783ecc9990
Is extension: false

**Comment by Poopooracoocoo** [comment] 2022-01-24 09:43
Duplicate of #4932

**Closed by Poopooracoocoo** 2022-01-24 09:43 UTC
Labels: duplicate, error-report
