### ISSUE TITLE
Error on https://game192194.konggames.com/games/player_03/run-3/frame/664630cf-b45f-4d40-b07e-1c5da5e91679/

### ISSUE THREAD

**Issue by scratcherevancats** [ruffle-rs/ruffle#11116] opened 2023-05-18 22:27 UTC
# Error Info
Error name: Error
Error message: panicked at 'Vertex shader failed to compile: Unimplemented("Unsupported conversion from Float1 to float4")', render/wgpu/src/context3d/current_pipeline.rs:437:10
Error stack:
```
Error: panicked at 'Vertex shader failed to compile: Unimplemented("Unsupported conversion from Float1 to float4")', render/wgpu/src/context3d/current_pipeline.rs:437:10
    at n.wbg.__wbg_new_87297f22973157c8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.1fc91d767a0a749b6126.js:1:52783)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9058a63962169328 (<anonymous>:wasm-function[8598]:0x87acfa)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (<anonymous>:wasm-function[5655]:0x798859)
    at core::panicking::panic_fmt::he4489d678d6570d5 (<anonymous>:wasm-function[8452]:0x8765eb)
    at core::result::unwrap_failed::h9c69c0d7a98df92b (<anonymous>:wasm-function[6517]:0x7d6805)
    at <ruffle_render_wgpu::context3d::WgpuContext3D as ruffle_render::backend::Context3D>::process_command::hfdb8633ee1f1f93d (<anonymous>:wasm-function[527]:0xc7653)
    at ruffle_core::avm2::globals::flash::display3D::context_3d::draw_triangles::h0e8e01306f8b09e0 (<anonymous>:wasm-function[2128]:0x53eb36)
    at ruffle_core::avm2::function::Executable::exec::h10814a1cf08c0132 (<anonymous>:wasm-function[722]:0x28148a)
    at ruffle_core::avm2::object::TObject::call_property::h8b9ff4f70faa587d (<anonymous>:wasm-function[1151]:0x3ba413)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::ha3ca638659429fa2 (<anonymous>:wasm-function[2772]:0x6099ee)
```
AVM2 stack:
```
    at flash.display3D::Context3D/flash::display3D::Context3D::drawTriangles()
    at nme3D.model::ModelGroup/render()
    at nme3D.model::ModelCollection/render()
    at nme3D::Context3DUtils$/render()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mesa DRI Intel(R) HD Graphics (BDW GT1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game192194.konggames.com/games/player_03/run-3/frame/664630cf-b45f-4d40-b07e-1c5da5e91679/?kongregate_host=www.kongregate.com
SWF URL: https://game192194.konggames.com/gamez/0019/2194/live/Run3.swf?kongregate_game_version=1669305919

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 13904.97.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.167 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-18
Channel: nightly
Built: 2023-05-18T00:22:15.330Z
Commit: 8cd5414c5dc5ad7149e7369f9513dd08ebeee614
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 60
numFrames: 2
swfVersion: 17
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 14964692

**Comment by n0samu** [comment] 2023-05-19 01:04
Duplicate of #11092. This problem is now fixed by #11109.

**Closed by n0samu** 2023-05-19 01:04 UTC
Labels: duplicate, error-report
