### ISSUE TITLE
Error on chrome-extension://dmiccnlhefjhhbpgnmleakgjljecgpib/player.html

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#8810] opened 2022-12-16 17:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://dmiccnlhefjhhbpgnmleakgjljecgpib/dist/966.js:645:21)
    at std::sync::once::Once::call_once::{{closure}}::ha7687e41144ec39a (wasm://wasm/01912dba:wasm-function[1095]:0x2a377c)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/01912dba:wasm-function[1404]:0x31a16a)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb259f62dc432889a (wasm://wasm/01912dba:wasm-function[5027]:0x4bb576)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/01912dba:wasm-function[3730]:0x475899)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/01912dba:wasm-function[5268]:0x4c039d)
    at core::panicking::panic::h0859aaac783261b2 (wasm://wasm/01912dba:wasm-function[5082]:0x4bc4f1)
    at core::ops::function::FnOnce::call_once::h53d1a0b846a1703d (wasm://wasm/01912dba:wasm-function[1288]:0x2f8739)
    at ruffle_core::avm1::function::Executable::exec::hbf4a5915999e2c85 (wasm://wasm/01912dba:wasm-function[371]:0xf591d)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h4ebaaecf22923376 (wasm://wasm/01912dba:wasm-function[1446]:0x32544a)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: chrome-extension://dmiccnlhefjhhbpgnmleakgjljecgpib/player.html?url=http%3A%2F%2Ffarm.stickpage.com%2Felectricman2game.swf
SWF URL: http://farm.stickpage.com/electricman2game.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.42
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-16
Channel: nightly
Built: 2022-12-16T00:16:00.140Z
Commit: d26b5ab0188c86c4ee73e32a6400eb7902473148
Is extension: true

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3518459

**Comment by n0samu** [comment] 2022-12-17 04:38
Duplicate of #4932

**Closed by n0samu** 2022-12-17 04:38 UTC
Labels: duplicate, error-report
