### ISSUE TITLE
Visual issue in Submachine 10

### ISSUE THREAD

**Issue by Zakru** [ruffle-rs/ruffle#5193] opened 2021-09-01 12:12 UTC
**Describe the bug**
In Submachine 10, after starting the game, the world is covered by an almost fully opaque red color or some red filter. The SWF can be downloaded from this archive: http://web.archive.org/web/20210102002841mp_/https://www.mateuszskutnik.com/submachine/swf/submachine_10.swf
Alternatively it can be played in a browser here: https://web.archive.org/web/20210102002010/https://www.mateuszskutnik.com/submachine/index.php?id=submachine_10

Steps to reproduce:
* Load the SWF
* Click "new game"
* Click the center of the circle and wait for the short intro
* The world is now red. It is worth noting that the red color is very slightly transparent, and the game is barely visible, which would indicate that otherwise everything seems to be rendering correctly. From some testing, the game seems to be working fine mechanically.

![screenshot](https://user-images.githubusercontent.com/23387227/131665768-071fb0a1-3629-465a-907f-5cf4d8a0262f.png)

**Expected behavior**
The red area should look more like the following (as shown in [this comment](https://github.com/ruffle-rs/ruffle/issues/3457#issuecomment-850997899), note that my screenshot of Ruffle above is from a different location in-game):
![screenshot of expected appearance](https://user-images.githubusercontent.com/68330228/120105404-64ad4e80-c161-11eb-9660-f50351cb0c0e.png)

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Confirmed on extension and desktop app

**What platform are you using?**
 - Desktop confirmed on Windows 10
 - Extension confirmed on Firefox 91.0.2 64-bit, Windows 10 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0)

**Comment by Zakru** [comment] 2021-09-01 12:51
A couple things I'd like to point out:

I don't know if it is significant, but the original has a vignette effect, which is not visible in any way in Ruffle.

Wherever there should be black on the screen, there is the color ED0000 instead. Using this, we can use some image editing to edit a screenshot of Ruffle (from the same location as the expected behavior screenshot) to look fairly close to the original (excluding the surrounding framing of course):
![kuva](https://user-images.githubusercontent.com/23387227/131673498-cd4a454e-2db6-4b38-996d-0f2b095cde51.png)
The way I edited the image reverses the effects of there being a pure red rectangle with an alpha of 237 (out of 255) over the image, which to me says that there is something being rendered in front of it all.

**Comment by adrian17** [comment] 2021-09-02 16:49
I'm gonna assume this is related to either blend modes (#58) or filtering (#15), both of which are not close to being implemented currently :(

**Comment by waspennator** [comment] 2023-07-09 21:16
![Screenshot 2023-07-09 151527](https://github.com/ruffle-rs/ruffle/assets/78768499/50063728-605e-4fa4-a179-30a0c936760c)
Should be fixed by #11878

**Closed** 2023-07-24 22:00 UTC
Labels: bug

**Comment by TommyDangerously** [comment] 2023-07-28 22:35
> ![Screenshot 2023-07-09 151527](https://user-images.githubusercontent.com/78768499/252169730-50063728-605e-4fa4-a179-30a0c936760c.png) Should be fixed by #11878

As of today all attempt at starting the game have given the same result as the original Poster. I would not call it closed unfortunately. Could have been Ruffle updated on their end and revived the problem.

**Comment by TommyDangerously** [comment] 2023-07-28 22:37
![image](https://github.com/ruffle-rs/ruffle/assets/96324892/3a084a39-4647-4ef5-9497-e801697ba91c)

unfortunately as of today all attempts at starting this game has reproduced the OP's issue. I wouldn't call this closed. Could be that Ruffle updated on their end and revived the original problem.

**Comment by waspennator** [comment] 2023-07-28 22:51
> ![image](https://user-images.githubusercontent.com/96324892/256944760-3a084a39-4647-4ef5-9497-e801697ba91c.png)
> 
> unfortunately as of today all attempts at starting this game has reproduced the OP's issue. I wouldn't call this closed. Could be that Ruffle updated on their end and revived the original problem.

Are you using the latest nightly build of ruffle? I quickly checked again on my end using the ruffle web demo site with the swf and the screen isn't fully colored red on my end.

**Comment by TommyDangerously** [comment] 2023-07-28 23:07
really? I use 64 bit and just to be sure downloaded the last 2 nightly builds including the newest nightly and they are all red still. checked it a few times just to make sure I wasn't messing up.

**Comment by waspennator** [comment] 2023-07-28 23:10
> really? I use 64 bit and just to be sure downloaded the last 2 nightly builds including the newest nightly and they are all red still. checked it a few times just to make sure I wasn't messing up.

Please open up the context menu on web, click on "copy debug info", then paste the resulting debug log here.

**Comment by TommyDangerously** [comment] 2023-07-28 23:17
Apologies. Where do you mean to right click? I do not get any such options on the Ruffle Player with a right click on screen. and Debut Tools do not have similar options.

**Comment by waspennator** [comment] 2023-07-28 23:20
> Apologies. Where do you mean to right click? I do not get any such options on the Ruffle Player with a right click on screen. and Debug Tools do not have similar options.

If you right click the area where the swf is playing, the context menu should pop up.

**Comment by TommyDangerously** [comment] 2023-07-28 23:22
nada. right clicking anywhere on the screen even when full size gets me nothing. Guessing that's a red flag.

**Comment by TommyDangerously** [comment] 2023-07-29 04:13
using the web demo this is the debug log. I was using the downloadable nightly before and you couldn't right click anything. --
# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-29
Channel: nightly
Built: 2023-07-29T00:25:41.578Z
Commit: 82b88ebff59f7992eeb4d10a18dec28d8714d338
Is extension: false

# Metadata
width: 400
height: 500
frameRate: 30
numFrames: 116
swfVersion: 9
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 32002267

**Comment by TommyDangerously** [comment] 2023-07-29 04:32
![image](https://github.com/ruffle-rs/ruffle/assets/96324892/2121abab-d92e-4cc9-aea6-0a78cf722473)

this is the 27th 28th and 29th nightly downloadable builds. I just wanna play Submachine 10 lol I'm going to buy the steam release of legacy when it drops anyway. But hopefully whatever ails this game on ruffle gets sorted so it doesn't happen on other games/animations.

**Comment by n0samu** [comment] 2023-07-29 04:35
Is this problem also happening for you in the Ruffle Web Demo? Or only in the desktop app?

**Comment by TommyDangerously** [comment] 2023-07-29 04:37
> Is this problem also happening for you in the Ruffle Web Demo? Or only in the desktop app?

All of the above. The debug I posted was from the web demo. the screenshots after that were of the aforementioned dated nightly desktop builds.

**Comment by n0samu** [comment] 2023-07-29 04:47
I can't reproduce the problem, and I've never seen anyone with your graphics card have this type of issue, so I'm very confused. You can try running Ruffle from the command line using the `-g dx12` or `-g vulkan` options, to see if a different renderer helps. But if this is also occurring on the Web Demo, that's less likely to make any difference.

If you just want to play the game, you can use the official standalone Adobe Flash projector to open the SWF file: http://web.archive.org/web/20220401020702/https://www.adobe.com/support/flashplayer/debug_downloads.html

**Comment by TommyDangerously** [comment] 2023-07-29 04:50
I really appreciate it. Even the browser extension didn't work. I also downloaded Flashpoint a minute ago to try that as another option. Did any other game in the series have this issue? I know one of them had invisible wisdom gems but that was ages ago according to another thread. Hopefully patched out.

**Comment by thomassth** [comment] 2023-07-29 20:42
On Firefox, the red screen issue is not fixed, but the performance is great
On Edge. the performance from loading to control is very slow, but the red screen issue is fixed

Both games are ran on same nightly build, but firefox is using WebGL and Edge using wgpu.

-- Firefox debug info --

# Player Info
Allows script access: false
Renderer: WebGL 1.0
Adapter Vendor: Mozilla
Adapter Renderer: ANGLE (Microsoft, Microsoft Basic Render Driver Direct3D11 vs_5_0 ps_5_0)
Adapter Version: WebGL 1.0
Surface samples: 1 x 
Surface size: 300 x 150

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1788.0
Platform: Windows
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-29
Channel: nightly
Built: 2023-07-29T00:25:41.578Z
Commit: 82b88ebff59f7992eeb4d10a18dec28d8714d338
Is extension: false

# Metadata
width: 400
height: 500
frameRate: 30
numFrames: 116
swfVersion: 9
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 32002267

-- Edge debug info --


# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon RX 6650 XT Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-29
Channel: nightly
Built: 2023-07-29T00:25:41.578Z
Commit: 82b88ebff59f7992eeb4d10a18dec28d8714d338
Is extension: false

# Metadata
width: 400
height: 500
frameRate: 30
numFrames: 116
swfVersion: 9
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 32002267

**Comment by thomassth** [comment] 2023-07-29 22:35
Another issue: while the game is playable till the end, all text in the "terminals" aren't populated correctly

![image](https://github.com/ruffle-rs/ruffle/assets/8331853/9b713803-71cb-4a11-8aff-62229f0e10df)

same on Firefox (image gone through extreme de-tinting):
![image](https://github.com/ruffle-rs/ruffle/assets/8331853/da5431fe-9f0a-4584-85b4-2bac6e13a523)

**Comment by TommyDangerously** [comment] 2023-07-29 22:41
I have been using Chrome with the web results. But I've opted to use Flashpoint to play the game.
