### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by ploki360** [ruffle-rs/ruffle#7815] opened 2022-08-30 16:19 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:821:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:821:18
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.dc6a4efed31836d31c04.js:1:5745)
    at std::sync::once::Once::call_once::{{closure}}::h2b0dd13dece8b2bd (wasm://wasm/016ae5c6:wasm-function[934]:0x26ac3f)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/016ae5c6:wasm-function[1370]:0x2f96e0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hcedf29f658f02358 (wasm://wasm/016ae5c6:wasm-function[4798]:0x441c82)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/016ae5c6:wasm-function[3519]:0x408f9d)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/016ae5c6:wasm-function[4975]:0x447541)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/016ae5c6:wasm-function[4885]:0x443499)
    at core::ops::function::FnOnce::call_once::h0cdce7b429eb3eab (wasm://wasm/016ae5c6:wasm-function[1022]:0x28a339)
    at ruffle_core::avm1::function::Executable::exec::h2ed8e7d0d011c683 (wasm://wasm/016ae5c6:wasm-function[352]:0xd4ff0)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h7619e00c3744f2f9 (wasm://wasm/016ae5c6:wasm-function[786]:0x22655f)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1661868203%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F526000%2F526470_beastgame_ng.swf%3F1381183836%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22630e2bd3bc40e%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F526000%2Fflash_526470_card.png%3Ff1610478129%22%7D
SWF URL: https://uploads.ungrounded.net/526000/526470_beastgame_ng.swf?1381183836

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-30
Channel: nightly
Built: 2022-08-30T00:18:51.591Z
Commit: 36450619109b6ed510991b311f4888c0784eba8e
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 25
numFrames: 1
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 7807601

**Comment by n0samu** [comment] 2022-08-31 14:05
Duplicate of #3756

**Closed by n0samu** 2022-08-31 14:05 UTC
Labels: duplicate, error-report
