### ISSUE TITLE
Learn to Fly 2 not working correctly 

### ISSUE THREAD

**Issue by bigfloppa234** [ruffle-rs/ruffle#6941] opened 2022-05-10 18:09 UTC
### Describe the bug

Learn to Fly 2 will start up correctly, but whenever you try to play, the penguin will just stay at the top of the mountain and do nothing else.

SWF: https://github.com/flash-games/games/blob/main/learn-to-fly-2.swf

### Expected behavior

I expected the penguin to start going down the cliff and then be able to control it using the proper keys

### Affected platform

Online demo

### Operating system

ChromeOS

### Browser

Chrome 100

**Comment by relrelb** [comment] 2022-05-14 11:59
Duplicate of #1839.

**Closed by relrelb** 2022-05-14 11:59 UTC
Labels: bug
