### ISSUE TITLE
Error on https://h-flash.com/cunning-little-girl-in-a-tight-spot/

### ISSUE THREAD

**Issue by haato5123** [ruffle-rs/ruffle#9405] opened 2023-02-04 10:27 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/event_object.rs:169:33
Error stack:
```
@https://h-flash.com/data/ruffle/core.ruffle.5fc5bc0046838bc074f7.js:1:6930
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9]@[wasm code]
<?>.wasm-function[std::sys_common::once::generic::Once::call::h62f79875d8dd2a00]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::he04cb00575f2a1e3]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h586d720a90aa8503]@[wasm code]
<?>.wasm-function[core::result::unwrap_failed::h1d03d3774c363770]@[wasm code]
<?>.wasm-function[ruffle_core::avm2::events::dispatch_event_to_target::h8cea46a4e02529a3]@[wasm code]
<?>.wasm-function[ruffle_core::avm2::events::dispatch_event::h7979c9083c29244e]@[wasm code]
<?>.wasm-function[ruffle_core::avm2::Avm2::dispatch_event::hf7cd5cac9caa13c2]@[wasm code]
<?>.wasm-function[<ruffle_core::display_object::interactive::InteractiveObject as ruffle_core::display_object::interactive::TInteractiveObject>::handle_clip_event::h34ad8b2cd710d18d]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::update_mouse_state::hda2527b35a7f0a0c]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::handle_event::h5d73f62bdb9313b3]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h32aedbe0603e1ccb]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1b8e63492585667c]@[wasm code]
wasm-stub@[native code]
E@https://h-flash.com/data/ruffle/core.ruffle.5fc5bc0046838bc074f7.js:1:2902
c@https://h-flash.com/data/ruffle/core.ruffle.5fc5bc0046838bc074f7.js:1:2509
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://h-flash.com/cunning-little-girl-in-a-tight-spot/
SWF URL: https://h-flash.com/data/swf/2014/05/jsk-clgts-hack.swf

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-21
Channel: nightly
Built: 2022-12-21T00:16:40.503Z
Commit: 5cf5c8d5e5d3b37a38cf133aa587b7f925612f21
Is extension: false

# Metadata
width: 600
height: 600
frameRate: 24
numFrames: 317
swfVersion: 10
backgroundColor: #999999
isActionScript3: true
uncompressedLength: 7026997

**Comment by n0samu** [comment] 2024-06-23 23:27
Duplicate of #6608

**Closed by n0samu** 2024-06-23 23:27 UTC
Labels: duplicate, nsfw, error-report
