### ISSUE TITLE
Error on http://dme2vtxapp01:8095/vertex-ui/

### ISSUE THREAD

**Issue by mickpeflin** [ruffle-rs/ruffle#3047] opened 2021-02-02 21:55 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at http://dme2vtxapp01:8095/vertex-ui/ruffle.js:1:32437
    at e (http://dme2vtxapp01:8095/vertex-ui/ruffle.js:1:32927)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://dme2vtxapp01:8095/vertex-ui/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-02
Channel: nightly
Built: 2021-02-02T00:21:23.909Z
Commit: 5783021d99477357a1d291d47fc0fd16082fbd98

**Comment by Poopooracoocoo** [comment] 2021-02-03 04:18
Hi, could you please provide some more details?

**Comment by relrelb** [comment] 2021-02-12 23:50
Duplicate of #2201.

**Closed by relrelb** 2021-02-12 23:50 UTC
