### ISSUE TITLE
mouse wheel scrolling speed is slow

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#17153] opened 2024-07-17 03:34 UTC
### Describe the bug

https://github.com/user-attachments/assets/0e934c13-c6da-4429-be47-17ada2b0e5ba

### Expected behavior

https://github.com/user-attachments/assets/9e299d67-876a-4448-a5c7-e740a68474e2

### Content Location

https://www.cs.usfca.edu/~galles/visualization/FlashTest.swf

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

to expand the combobox correctly in ruffle, the cursor should be at the right edge or outside it when releasing the mouse
this is another bug

**Comment by Lord-McSweeney** [comment] 2024-07-17 04:20
Duplicate of #14795

**Closed by Lord-McSweeney** 2024-07-17 04:20 UTC
Labels: bug
