### ISSUE TITLE
Flash Games on DollDivine

### ISSUE THREAD

**Issue by LumiKat117** [ruffle-rs/ruffle#2531] opened 2021-01-15 00:35 UTC
I use character makers on this site to help me visualize my own art but most of them aren't supported yet or don't work properly such as this one: [](http://www.dolldivine.com/dragon-maker.php) where the colors at the least don't work at all. I wanted to make this issue known but there is no hurry.

**Comment by ousia** [comment] 2021-01-15 18:36
@LumiKat117, many thanks for having joined GitHub to report the issue.

I’m only an average computer user that reports issues here from time to time.

Sorry, if the following is obvious to you. I apologize if that were the case.

I wonder whether these considerations might help to fix your issues faster.

Developers can fix problems they can reproduce themselves. It is important to describe individual issues with examples.

Sorry, but I don’t do computer games of any kind. Is the address https://www.dolldivine.com?

The best way to report issues is to provide the full address to the game or page that contains the problematic animation and a concise description of the individual problem.

 Otherwise, it might take forever, since first someone would have to do the research and report which issues are affecting the animations you use.

I hope it might help. Please, feel free to correct me in case I got something wrong.

**Comment by n0samu** [comment] 2022-10-05 03:29
Glad I double-checked this one with the GitHub API: https://api.github.com/repos/ruffle-rs/ruffle/issues/2531
With the API response, I see now that the original issue does have a link, but it's invisible because it's missing a label. @LumiKat117, I see that the specific game you were trying to mention is Dragon Maker: https://www.dolldivine.com/dragon-maker.php

This game uses BitmapData.Draw to draw the colors. So it's working fine on the Ruffle desktop app thanks to #7254. And it should work in Ruffle web builds once #6629 is finalized and merged.

**Comment by Lord-McSweeney** [comment] 2023-01-18 04:10
Fixed by #9134

**Closed** 2023-01-18 04:11 UTC
Labels: unimplemented
