### ISSUE TITLE
Error on https://radon.games/game/electric-man

### ISSUE THREAD

**Issue by dirtboy156** [ruffle-rs/ruffle#8045] opened 2022-09-22 16:03 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.e1b4c26055260cecdb25.js:1:5314)
    at std::sync::once::Once::call_once::{{closure}}::h28fa05460bbcf5b3 (wasm://wasm/01814f52:wasm-function[1179]:0x2e329b)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/01814f52:wasm-function[1480]:0x337afb)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0020dcf09a90a4c0 (wasm://wasm/01814f52:wasm-function[4944]:0x48c08f)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/01814f52:wasm-function[3640]:0x4535e5)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/01814f52:wasm-function[5133]:0x492816)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/01814f52:wasm-function[5032]:0x48d8fa)
    at core::ops::function::FnOnce::call_once::h4fe1802dd462eccf (wasm://wasm/01814f52:wasm-function[1108]:0x2c77af)
    at ruffle_core::avm1::function::Executable::exec::h599999e13621c410 (wasm://wasm/01814f52:wasm-function[359]:0xf449b)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h3344baf56a6d9b7c (wasm://wasm/01814f52:wasm-function[884]:0x2719b2)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://radon.games/game/electric-man
SWF URL: https://radon.games/cdn/swf/ElectricMan.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15054.50.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-22
Channel: nightly
Built: 2022-09-22T00:19:18.228Z
Commit: c31e9e2b1199494597399fe3fdf9d09663b7bbe2
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment] 2022-09-22 22:34
Duplicate of #4932

**Closed by n0samu** 2022-09-22 22:34 UTC
Labels: duplicate, error-report
