### ISSUE TITLE
Error on https://game81398.konggames.com/games/likwidgames/castaway/frame/003fb48e-9c78-4147-ad6b-60bac90d1160/

### ISSUE THREAD

**Issue by Benson0407** [ruffle-rs/ruffle#8244] opened 2022-10-09 01:06 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:1010:22
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:1010:22
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.c00b1522f61b16f6f730.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::h6ba3ee80d6ca129f (wasm://wasm/01800756:wasm-function[1035]:0x2a7210)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01800756:wasm-function[1498]:0x32a258)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::ha5bfda863bee82e7 (wasm://wasm/01800756:wasm-function[4956]:0x48841a)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01800756:wasm-function[3645]:0x444624)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01800756:wasm-function[5111]:0x48b8d0)
    at core::result::unwrap_failed::h5da0ab182d2c24a1 (wasm://wasm/01800756:wasm-function[4250]:0x46f245)
    at ruffle_core::bitmap::bitmap_data::BitmapData::draw::ha5472e54a47658c9 (wasm://wasm/01800756:wasm-function[757]:0x242c7a)
    at ruffle_core::avm1::globals::bitmap_data::draw::h304f9dce76567b49 (wasm://wasm/01800756:wasm-function[638]:0x204ae3)
    at ruffle_core::avm1::function::Executable::exec::h7dbb30579b1dd750 (wasm://wasm/01800756:wasm-function[369]:0x100642)
```

# Player Info
Allows script access: true
Renderer: Canvas

# Page Info
Page URL: https://game81398.konggames.com/games/likwidgames/castaway/frame/003fb48e-9c78-4147-ad6b-60bac90d1160/?kongregate_host=www.kongregate.com
SWF URL: https://game81398.konggames.com/gamez/0008/1398/live/castawayKon.swf?kongregate_game_version=1292015336

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-08
Channel: nightly
Built: 2022-10-08T00:21:16.770Z
Commit: 5c9471436371f24f1d95011d21b5cddb7fc4ee7f
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 5
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 7988051

**Comment by n0samu** [comment] 2022-10-09 01:19
Duplicate of #8016

**Closed by n0samu** 2022-10-09 01:19 UTC
Labels: duplicate, error-report
