### ISSUE TITLE
Error on https://www.play-games.com/embed/24956.html

### ISSUE THREAD

**Issue by Tinky124** [ruffle-rs/ruffle#7588] opened 2022-08-06 11:49 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at V.e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.play-games.com/js/frontend/vendor/ruffle/core.ruffle.e75954ac555a11560cab.js:1:5540)
    at std::sync::once::Once::call_once::{{closure}}::hc005efe66820567d (wasm://wasm/0169be0a:wasm-function[1190]:0x2c1327)
    at std::sync::once::Once::call_inner::h1c414562e2619117 (wasm://wasm/0169be0a:wasm-function[1373]:0x2f6f90)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h333199a3a4749bb8 (wasm://wasm/0169be0a:wasm-function[4743]:0x4402e6)
    at std::panicking::rust_panic_with_hook::h1c368a27f9b0afe1 (wasm://wasm/0169be0a:wasm-function[3096]:0x3ed9a3)
    at core::panicking::panic_fmt::hcdb13a4b2416cf82 (wasm://wasm/0169be0a:wasm-function[4930]:0x445e31)
    at core::panicking::panic::ha8ced62e366a0d64 (wasm://wasm/0169be0a:wasm-function[4839]:0x441d73)
    at core::ops::function::FnOnce::call_once::he6b960eb0e7a3615 (wasm://wasm/0169be0a:wasm-function[1010]:0x286056)
    at ruffle_core::avm1::function::Executable::exec::hd1a31b7b31ac1395 (wasm://wasm/0169be0a:wasm-function[354]:0xf7406)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h812a9e6cbb0cb2b4 (wasm://wasm/0169be0a:wasm-function[787]:0x22851f)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.play-games.com/embed/24956.html
SWF URL: https://www.play-games.com/files/swf/electric-man-1611670590.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-02
Channel: nightly
Built: 2022-08-02T00:19:12.167Z
Commit: 2ba82c92bc2f295d2a0269fa39feb574fc1fb183
Is extension: false

**Comment by n0samu** [comment] 2022-08-06 21:10
Duplicate of #4932

**Closed by n0samu** 2022-08-06 21:10 UTC
Labels: duplicate, error-report
