### ISSUE TITLE
Error on https://game253127.konggames.com/games/BerzerkStudio/zombidle/frame/3fa25b61-bbff-40ea-810b-3e68b5451093/

### ISSUE THREAD

**Issue by KaiPond** [ruffle-rs/ruffle#10488] opened 2023-04-01 00:59 UTC
# Error Info
Error name: Error
Error message: panicked at 'Unable to get Object', /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/8376453/flash-lso/src/amf3/read.rs:418:14

# Player Info
Allows script access: true

# Page Info
Page URL: https://game253127.konggames.com/games/BerzerkStudio/zombidle/frame/3fa25b61-bbff-40ea-810b-3e68b5451093/?kongregate_host=www.kongregate.com
SWF URL: https://game253127.konggames.com/gamez/0025/3127/live/ZI_FGL.swf?kongregate_game_version=1570126011

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-01
Channel: nightly
Built: 2023-04-01T00:23:12.618Z
Commit: 6fda813f0c329200cb6ca345c3f3debf35423f40
Is extension: false

# Metadata
width: 960
height: 640
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 64218669

**Comment by n0samu** [comment] 2023-08-19 22:49
Duplicate of #10174

**Closed by n0samu** 2023-08-19 22:49 UTC
Labels: duplicate, avm2, error-report
