### ISSUE TITLE
Error on https://flashstorage.games/embed/electric-man

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#7161] opened 2022-06-05 06:22 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://flashstorage.games/public/js/ruffle/core.ruffle.9e689016c043c49772e0.js:1:7024)
    at std::sync::once::Once::call_once::{{closure}}::h2b3586a1c348e776 (https://flashstorage.games/public/js/ruffle/9e191fa1a0f6723ebc13.wasm:wasm-function[1196]:0x2b4e83)
    at std::sync::once::Once::call_inner::h8a142b2dcc139875 (https://flashstorage.games/public/js/ruffle/9e191fa1a0f6723ebc13.wasm:wasm-function[1424]:0x2f1130)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0e8f59b7c29e471d (https://flashstorage.games/public/js/ruffle/9e191fa1a0f6723ebc13.wasm:wasm-function[4754]:0x440e9a)
    at std::panicking::rust_panic_with_hook::he2a025723e105e28 (https://flashstorage.games/public/js/ruffle/9e191fa1a0f6723ebc13.wasm:wasm-function[3202]:0x3e87dd)
    at core::panicking::panic_fmt::hb02133958c1e7d35 (https://flashstorage.games/public/js/ruffle/9e191fa1a0f6723ebc13.wasm:wasm-function[4937]:0x446dc1)
    at core::panicking::panic::hc28e7cc2aa792341 (https://flashstorage.games/public/js/ruffle/9e191fa1a0f6723ebc13.wasm:wasm-function[4847]:0x442ef4)
    at core::ops::function::FnOnce::call_once::h590cc274d810cad1 (https://flashstorage.games/public/js/ruffle/9e191fa1a0f6723ebc13.wasm:wasm-function[1062]:0x28f327)
    at ruffle_core::avm1::function::Executable::exec::hb7f77c6ff1c4ab01 (https://flashstorage.games/public/js/ruffle/9e191fa1a0f6723ebc13.wasm:wasm-function[358]:0xcbdaa)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hfe3077a0315fbbfe (https://flashstorage.games/public/js/ruffle/9e191fa1a0f6723ebc13.wasm:wasm-function[541]:0x196ce9)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://flashstorage.games/embed/electric-man
SWF URL: https://flashstorage.games/public/storage/games/FLASHJanuary2022/electric-man.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.30
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-26
Channel: nightly
Built: 2022-05-26T00:18:28.438Z
Commit: 811af340c3631ebe10b319fa09a1d969848857d4
Is extension: false

**Comment by n0samu** [comment] 2022-06-05 06:52
Duplicate of #4932. (This game doesn't work yet, sorry!)

**Closed by n0samu** 2022-06-05 06:52 UTC
Labels: duplicate, error-report
