### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by kevinorsomething** [ruffle-rs/ruffle#4142] opened 2021-04-26 18:25 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:189:18
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1619354746:1:6924)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://uploads.ungrounded.net/ruffle_wrapper/lib/73d78e96b2eab18414cb.wasm:wasm-function[838]:0x228302)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://uploads.ungrounded.net/ruffle_wrapper/lib/73d78e96b2eab18414cb.wasm:wasm-function[1230]:0x2aac4f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://uploads.ungrounded.net/ruffle_wrapper/lib/73d78e96b2eab18414cb.wasm:wasm-function[3690]:0x4328c0)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://uploads.ungrounded.net/ruffle_wrapper/lib/73d78e96b2eab18414cb.wasm:wasm-function[2689]:0x39a30c)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/73d78e96b2eab18414cb.wasm:wasm-function[3892]:0x438005)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://uploads.ungrounded.net/ruffle_wrapper/lib/73d78e96b2eab18414cb.wasm:wasm-function[4004]:0x43b8fa)
    at core::option::expect_none_failed::h203584ddbc785ca2 (https://uploads.ungrounded.net/ruffle_wrapper/lib/73d78e96b2eab18414cb.wasm:wasm-function[3321]:0x422e9d)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd23d4d416357cb6f (https://uploads.ungrounded.net/ruffle_wrapper/lib/73d78e96b2eab18414cb.wasm:wasm-function[564]:0x187428)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1c32e3591d6b8162 (https://uploads.ungrounded.net/ruffle_wrapper/lib/73d78e96b2eab18414cb.wasm:wasm-function[483]:0x150002)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1619354746%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2259379498.9be5d65050780629931932d6a69ad9a07a263411970bef%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226087054f5ed6a%22%2C%22NewgroundsAPI_SessionID%22%3A%22OydYM4pTBSouU2JQPJbl4ce6d344ee964edea35227137974eea2bcd377efTn8F%22%2C%22NewgroundsAPI_UserName%22%3A%22Polymer-productions%22%2C%22NewgroundsAPI_UserID%22%3A7669961%2C%22ng_username%22%3A%22Polymer-productions%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-25
Channel: nightly
Built: 2021-04-25T00:14:45.259Z
Commit: d43b033caa98ed201f37558c25f9ce5f2da189d0

**Comment by Poopooracoocoo** [comment] 2021-11-29 11:05
Duplicate of #5477

**Closed by Poopooracoocoo** 2021-11-29 11:05 UTC
Labels: duplicate, error-report
