### ISSUE TITLE
I was playing madness combat,i activated guntrick and the error appeared.

### ISSUE THREAD

**Issue by JeroOwhoo** [ruffle-rs/ruffle#4017] opened 2021-04-15 21:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1618322710:1:6915)
    at std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407 (https://uploads.ungrounded.net/ruffle_wrapper/lib/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[1222]:0x2abc22)
    at std::sync::once::Once::call_inner::hf7fd718057964857 (https://uploads.ungrounded.net/ruffle_wrapper/lib/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[1841]:0x32e1d3)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32 (https://uploads.ungrounded.net/ruffle_wrapper/lib/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[5350]:0x43c24d)
    at std::panicking::rust_panic_with_hook::h9d91fa0fae16500f (https://uploads.ungrounded.net/ruffle_wrapper/lib/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[4141]:0x40e6da)
    at std::panicking::begin_panic_handler::{{closure}}::h2d82b5b2db976f3f (https://uploads.ungrounded.net/ruffle_wrapper/lib/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[4826]:0x42e87b)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h24539600b7e2452c (https://uploads.ungrounded.net/ruffle_wrapper/lib/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[5733]:0x4421f6)
    at rust_begin_unwind (https://uploads.ungrounded.net/ruffle_wrapper/lib/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[5601]:0x44079a)
    at core::panicking::panic_fmt::h91d2023e5afe1929 (https://uploads.ungrounded.net/ruffle_wrapper/lib/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[5735]:0x44225a)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::he1007bd855d73485 (https://uploads.ungrounded.net/ruffle_wrapper/lib/56ce8e9cbf30a8f737e3556d0c544316.wasm:wasm-function[1770]:0x321e31)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1618322710%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2229438383.301c5b4e1a8706b8bdd634a154fe42b3614314014d6c24%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226078a2dcd2b73%22%2C%22NewgroundsAPI_SessionID%22%3A%22oGyY8hKMqtPnVGwMaVtm4fa1a7679e23f7cfe93e69483c44d1fdf8230de7EWCE%22%2C%22NewgroundsAPI_UserName%22%3A%22JeroOwHoo%22%2C%22NewgroundsAPI_UserID%22%3A8457306%2C%22ng_username%22%3A%22JeroOwHoo%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D
SWF URL: https://uploads.ungrounded.net/592000/592473_MadnessGame_ULTIMATE.swf?1507662264

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-13
Channel: nightly
Built: 2021-04-13T00:43:43.545Z
Commit: ae9be9882160c4fead586570d0d15376cf965f64

**Comment by EmperorBale** [comment] 2021-04-16 03:58
Does this happen everytime?

**Comment by Poopooracoocoo** [comment] 2021-11-29 10:50
Duplicate of #4038

**Closed by Poopooracoocoo** 2021-11-29 10:50 UTC
Labels: duplicate, error-report
