### ISSUE TITLE
Error on https://www.minijogos.com.br/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=6257&mp_game_uid=animator-vs-animation&mp_game_url=https%3A%2F%2Fwww.minijogos.com.br%2Fembed%2Fanimator-vs-animation&mp_int=1&mp_locale=pt_BR&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvYW5pdnNhbmkuc3dm&mp_site_https_url=https%3A%2F%2Fwww.minijogos.com.br%2F&mp_site_name=minijogos.com.br&mp_site_url=https%3A%2F%2Fwww.minijogos.com.br%2F&mp_timezone=America%2FFortaleza&mp_view_type=

### ISSUE THREAD

**Issue by arthursimao** [ruffle-rs/ruffle#7644] opened 2022-08-11 15:22 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
    at Object.U (https://ext.minijuegosgratis.com/ruffle/core.ruffle.ab9406d542303de5ee9b.js:1:21277)
    at __wbg_new_df6e6ab7a65c4c4d (https://ext.minijuegosgratis.com/ruffle/ruffle.js:1:38987)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (https://ext.minijuegosgratis.com/ruffle/b87c51083c0394ec85e9.module.wasm:wasm-function[1273]:0x2610c0)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (https://ext.minijuegosgratis.com/ruffle/b87c51083c0394ec85e9.module.wasm:wasm-function[1519]:0x28e96f)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (https://ext.minijuegosgratis.com/ruffle/b87c51083c0394ec85e9.module.wasm:wasm-function[4297]:0x364a21)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (https://ext.minijuegosgratis.com/ruffle/b87c51083c0394ec85e9.module.wasm:wasm-function[3306]:0x33e5d5)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (https://ext.minijuegosgratis.com/ruffle/b87c51083c0394ec85e9.module.wasm:wasm-function[3906]:0x35aa17)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (https://ext.minijuegosgratis.com/ruffle/b87c51083c0394ec85e9.module.wasm:wasm-function[4643]:0x36a175)
    at rust_begin_unwind (https://ext.minijuegosgratis.com/ruffle/b87c51083c0394ec85e9.module.wasm:wasm-function[4516]:0x3687b2)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (https://ext.minijuegosgratis.com/ruffle/b87c51083c0394ec85e9.module.wasm:wasm-function[4645]:0x36a1d9)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/anivsani.swf
Param quality: high
Param allowscriptaccess: always
Param allowfullscreen: false
Param wmode: direct
Param flashvars: mp_log_level=4&mp_game_id=6257&mp_game_url=https%3A%2F%2Fwww.minijogos.com.br%2Fembed%2Fanimator-vs-animation&mp_site_name=minijogos.com.br&mp_site_url=https%3A%2F%2Fwww.minijogos.com.br%2F&mp_api_id=&mp_api_as3_url=&mp_api_as3_url_bck=&mp_api_user_id=&mp_api_user_token=&mp_locale=pt_BR&mp_timezone=America%2FFortaleza&mp_embed=false&mp_base_path=https%3A%2F%2Fwww.minijuegosgratis.com%2Fflash1234%2Fno_hotlink%2F
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.minijogos.com.br/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=6257&mp_game_uid=animator-vs-animation&mp_game_url=https%3A%2F%2Fwww.minijogos.com.br%2Fembed%2Fanimator-vs-animation&mp_int=1&mp_locale=pt_BR&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvYW5pdnNhbmkuc3dm&mp_site_https_url=https%3A%2F%2Fwww.minijogos.com.br%2F&mp_site_name=minijogos.com.br&mp_site_url=https%3A%2F%2Fwww.minijogos.com.br%2F&mp_timezone=America%2FFortaleza&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/anivsani.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-13
Channel: nightly
Built: 2021-01-13T01:01:47.998Z
Commit: 63f2b4f02f8fa4fa69ce61a5f6710bb07fcd2f33

**Comment by relrelb** [comment] 2022-08-11 18:58
Duplicate of #7643.

**Closed by relrelb** 2022-08-11 18:58 UTC
Labels: duplicate
