### ISSUE TITLE
Error on https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.html?f=graviteevfinal15cm.swf&w=700&h=500

### ISSUE THREAD

**Issue by Jimmykuehnle** [ruffle-rs/ruffle#3669] opened 2021-03-15 16:09 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.js:1:6808
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h02eac160d339afc2]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h123718ba3bf480af]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_fmt::h96153d9dc0e882ed]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hbe0592654beca31b]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h291ef6601ee543a9]@[wasm code]
wasm-stub@[native code]
A@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.js:1:3398
a@https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.js:1:2841
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.coolmath-games.com/sites/cmatgame/files/games/graviteevfinal15cm.swf
Param allowScriptAccess: always
Param movie: graviteevfinal15cm.swf
Param menu: false
Param quality: high
Param wmode: direct
Param scale: exactfit
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.coolmath-games.com/sites/cmatgame/files/ruffle1/ruffle.html?f=graviteevfinal15cm.swf&w=700&h=500
SWF URL: https://www.coolmath-games.com/sites/cmatgame/files/games/graviteevfinal15cm.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-11
Channel: nightly
Built: 2021-02-11T00:18:16.959Z
Commit: 09c6def7f0df64f3868631be6b2c188c6b61ae75

**Comment by relrelb** [comment] 2021-03-15 18:05
Duplicate of #3642.

**Closed by relrelb** 2021-03-15 18:05 UTC
