### ISSUE TITLE
Audio streaming doesn't work on mobile

### ISSUE THREAD

**Issue by starblinky** [ruffle-rs/ruffle#6326] opened 2022-02-21 12:30 UTC
### Describe the bug

I found out what broke my game Cat Burglar
Its the main song.
Works on desktop.  But on mobile it stops all animations until the audio stream is finished, then allows a few frames to play.. then starts to jank out.

its like a minute long song but I shortened it to play over like 20 frames in this example file
I tested it in a separate file as seen here (issue is only on mobile, ios tested)

Tested with different songs on different frames. If a sound is streaming, it simply will not allow animations to play

### Expected behavior

animation should play while the song is playing

LINK TO FLA EXAMPLE.  It wouldn't let me upload it here, maybe file size too big 30 MB

https://www.dropbox.com/s/xojayeuf62oa4uu/TEST%20FILE.zip?dl=0

### Affected platform

Online demo

### Operating system

ios 15.3.1

### Browser

Safari

### Additional information

Tested on Newgrounds

**Comment by Toad06** [comment] 2022-02-22 22:17
Thanks for the report. I used the link that you posted on Discord (https://www.newgrounds.com/projects/games/1612154/preview/filetype/0).

This appears to be a regression introduced in nightly-2022-01-08, so it must be one of the following commits: https://github.com/ruffle-rs/ruffle/compare/nightly-2022-01-04...nightly-2022-01-08

Worth to mention that the issue also happens on desktop browsers (at least on my end) though it's much, much less noticeable (this only happens for a couple of frames right after the sound ends and before it starts playing again). On desktop _builds_, there is no issue at all.

I know that the web builds have a few specific issues that don't affect the desktop builds:
- Sounds that play at unexpected moments (cc. https://github.com/ruffle-rs/ruffle/issues/1673#issuecomment-736355688).
- Sounds that end too early (eg. when entering the ship's hold in [Steppenwolf 1-1](https://img-hws.pog.com/cloud/y8-flash-game/contents/item_versions/flash_games/485/original/steppenwolf_chapter_1_episode_1.swf).

These pre-existing issues _may_ have become more visible because of the recent changes.

@Herschel, I think you may want to take a look at this.

**Comment by Toad06** [comment] 2022-03-22 18:17
Fixed by #6493.

**Closed by Toad06** 2022-03-22 18:17 UTC
Labels: bug, audio, regression
