### ISSUE TITLE
Error on https://www.friv.cm/electricman-2/fullscreen/

### ISSUE THREAD

**Issue by sozdar100** [ruffle-rs/ruffle#8327] opened 2022-10-18 19:04 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:814:18
    at U.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.693681cdd011a3528fc6.js:1:6805)
    at std::sync::once::Once::call_once::{{closure}}::hc0104d6321319ac0 (wasm://wasm/0180b6da:wasm-function[1216]:0x2c247f)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/0180b6da:wasm-function[1491]:0x3112a5)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6143650320584ffd (wasm://wasm/0180b6da:wasm-function[4895]:0x4883bd)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/0180b6da:wasm-function[3599]:0x4461be)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/0180b6da:wasm-function[5114]:0x48cac1)
    at core::panicking::panic::h6f5024a57ca8da86 (wasm://wasm/0180b6da:wasm-function[4950]:0x48932f)
    at core::ops::function::FnOnce::call_once::h51f055153b20f1df (wasm://wasm/0180b6da:wasm-function[1121]:0x29e120)
    at ruffle_core::avm1::function::Executable::exec::h622ba75f47a2bb8d (wasm://wasm/0180b6da:wasm-function[363]:0xdba08)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h2dda4c833e4d3598 (wasm://wasm/0180b6da:wasm-function[1067]:0x28a5a8)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.friv.cm/electricman-2/fullscreen/
SWF URL: https://www.friv.cm/wp-content/games/electricman-2.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-18
Channel: nightly
Built: 2022-10-18T00:18:04.871Z
Commit: bdc041677a2c6a04e02a65cbb2b53911dd7467f6
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by n0samu** [comment] 2022-10-18 19:05
Duplicate of #4932

**Closed by n0samu** 2022-10-18 19:05 UTC
Labels: duplicate, error-report
