### ISSUE TITLE
Ruffle Error on https://play.cprewritten.net/2020/

### ISSUE THREAD

**Issue by Jarizard22** [ruffle-rs/ruffle#2221] opened 2021-01-02 05:18 UTC
# Error Info
Error name: Error
Error message: panicked at 'cannot recursively acquire mutex', C:\Users\Gravix\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src/libstd/macros.rs:13:23
Error stack:
```
Error: panicked at 'cannot recursively acquire mutex', C:\Users\Gravix\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src/libstd/macros.rs:13:23
    at Object.X (https://play.cprewritten.net/2020/assets/lib/ruffle/core.ruffle.76384a7c00f1a9593662.js:1:20834)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:1:37870)
    at wasm-function[1269]:0x24c7b7
    at wasm-function[1519]:0x2790fe
    at wasm-function[4024]:0x335b89
    at wasm-function[3167]:0x314d3a
    at wasm-function[4337]:0x33ad29
    at wasm-function[1455]:0x26e93d
    at wasm-function[4528]:0x33ccc2
    at k (https://play.cprewritten.net/2020/assets/lib/ruffle/core.ruffle.76384a7c00f1a9593662.js:1:18914)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://play.cprewritten.net/2020/
SWF URL: https://play.cprewritten.net/2020/assets/flash/global/games/boot.swf

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 9; LGL555DL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
OS: Linux armv7l

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-27
Channel: nightly
Built: 2020-12-27T03:29:29.906Z
Commit: c3811b30f5bf27e1c33939e76f0c4b01ff93c1ef

(Was playing pizzatron 3000 in candy mode and it lagged when I put on the toppings and sauce until the crash.)

**Comment by Poopooracoocoo** [comment] 2021-01-02 06:40
Is there an SWF for Pizzatron 3000? 

and oh my god i loved club penguin. the songs, the community. the twitter community was really something. it was great to see people my age, and cpr was full of people my age but i took it all for granted. people moved on. flash died. etc.

**Comment by Poopooracoocoo** [comment] 2021-01-02 08:23
possibly related to #1806

**Comment by Poopooracoocoo** [comment] 2021-02-21 03:18
#2124

**Comment by p0008874** [comment] 2023-01-14 07:40
Oh yeah Club Penguin Rewritten was gone.
It will be harder without private server
https://www.youtube.com/watch?v=zwogIaH-HHA

**Comment by Dinnerbone** [comment] 2024-07-12 22:07
Duplicate of #2124

**Closed by Dinnerbone** 2024-07-12 22:07 UTC
Labels: duplicate, error-report
