### ISSUE TITLE
Error on https://game239558.konggames.com/games/DivineGames/realm-grinder/frame/633df4ae-7f2a-47ea-b472-c7c573fbe82c/

### ISSUE THREAD

**Issue by junjun3o** [ruffle-rs/ruffle#12732] opened 2023-08-13 08:56 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Sample count 8 is not supported by format Rgba8Unorm on this device. It may be supported by your adapter through the TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES feature.

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Sample count 8 is not supported by format Rgba8Unorm on this device. It may be supported by your adapter through the TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES feature.

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
    at V.n.wbg.__wbg_new_d258248ed531ff54 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.b8e8d3700219a22fa58f.js:1:51553)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h47c86d7a777c7d0f (wasm://wasm/02fe37e6:wasm-function[9233]:0x8f67e0)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/02fe37e6:wasm-function[6049]:0x7f67f0)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/02fe37e6:wasm-function[9076]:0x8f219a)
    at core::ops::function::Fn::call::h02c044f30db86e49 (wasm://wasm/02fe37e6:wasm-function[6747]:0x83a4e5)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h400c9dc3b8bd0ad1 (wasm://wasm/02fe37e6:wasm-function[4830]:0x75b015)
    at <T as wgpu::context::DynContext>::device_create_texture::h211f9c30c290b2ba (wasm://wasm/02fe37e6:wasm-function[6721]:0x83894b)
    at wgpu::Device::create_texture::ha07bd6d502155ca8 (wasm://wasm/02fe37e6:wasm-function[5101]:0x7a0c97)
    at <ruffle_render_wgpu::context3d::WgpuContext3D as ruffle_render::backend::Context3D>::process_command::{{closure}}::h41ccdce3c482a4b5 (wasm://wasm/02fe37e6:wasm-function[2298]:0x580076)
    at <ruffle_render_wgpu::context3d::WgpuContext3D as ruffle_render::backend::Context3D>::process_command::h0ebeb1b54bff5b9c (wasm://wasm/02fe37e6:wasm-function[534]:0x9b882)
```
AVM2 stack:
```
    at flash.display3D::Context3D/flash::display3D::Context3D::configureBackBuffer()
    at Function/apply()
    at starling.core::Starling/configureBackBuffer()
    at starling.core::Starling/updateViewPort()
    at starling.core::Starling/initializeGraphicsAPI()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1686()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)"
Adapter Device Type: Cpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game239558.konggames.com/games/DivineGames/realm-grinder/frame/633df4ae-7f2a-47ea-b472-c7c573fbe82c/?kongregate_host=www.kongregate.com
SWF URL: https://game239558.konggames.com/gamez/0023/9558/live/secure_RealmGrinder.swf?kongregate_game_version=1690802124

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 OPR/100.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-13
Channel: nightly
Built: 2023-08-13T00:23:15.804Z
Commit: 3117469e20eeb1a435e678268252a4545228c030
Is extension: false

# Metadata
width: 976
height: 640
frameRate: 30
numFrames: 2
swfVersion: 23
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 21703001

**Comment by n0samu** [comment] 2023-08-13 10:07
Duplicate of #10587

**Closed by n0samu** 2023-08-13 10:07 UTC
Labels: duplicate, error-report
