### ISSUE TITLE
Error on https://www.vap.co.jp/elfenlied/staff.html

### ISSUE THREAD

**Issue by nano4153** [ruffle-rs/ruffle#8965] opened 2022-12-30 06:54 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/activation.rs:1229:38
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/activation.rs:1229:38
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:640:21)
    at std::sync::once::Once::call_once::{{closure}}::h07c839951d6d0b0f (wasm://wasm/018ff46a:wasm-function[1095]:0x2bb1e7)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018ff46a:wasm-function[1400]:0x3215a4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a01fde47a9be61a (wasm://wasm/018ff46a:wasm-function[5064]:0x4b50d3)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018ff46a:wasm-function[3744]:0x47655c)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018ff46a:wasm-function[5305]:0x4b9edc)
    at core::panicking::panic::h0859aaac783261b2 (wasm://wasm/018ff46a:wasm-function[5118]:0x4b6005)
    at ruffle_core::avm1::activation::Activation::run_actions::hcaff0750a7b9ae72 (wasm://wasm/018ff46a:wasm-function[302]:0x38d46)
    at ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::hd286c56e7ee8a556 (wasm://wasm/018ff46a:wasm-function[942]:0x280edf)
    at ruffle_core::player::Player::run_actions::haea6be853321b01e (wasm://wasm/018ff46a:wasm-function[461]:0x15fc6e)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.vap.co.jp/elfenlied/staff.html
SWF URL: https://www.vap.co.jp/elfenlied/staff.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-30
Channel: nightly
Built: 2022-12-30T00:18:10.336Z
Commit: 89e01b55981efd22e5398de31d741d87dac8d75e
Is extension: true

# Metadata
width: 750
height: 450
frameRate: 24
numFrames: 89
swfVersion: 6
backgroundColor: #FFE5EE
isActionScript3: false
uncompressedLength: 68249

**Comment by n0samu** [comment] 2022-12-30 06:55
Duplicate of #8912

**Closed by n0samu** 2022-12-30 06:55 UTC
Labels: duplicate, error-report
