### ISSUE TITLE
Error on https://www.quickflashgames.com/games/black-navy-war/

### ISSUE THREAD

**Issue by so6228** [ruffle-rs/ruffle#17562] opened 2024-08-19 10:13 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer
    Not enough memory left.


    at n.wbg.__wbg_new_28c511d9baebfa89 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.653cd9a7fca13552fc31.js:1:83178)
    at ruffle_web.wasm.js_sys::Error::new::hde54db82809eb734 (wasm://wasm/ruffle_web.wasm-031e2676:wasm-function[12709]:0x97e4a5)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h74ee4ac9b05ab19d (wasm://wasm/ruffle_web.wasm-031e2676:wasm-function[9783]:0x90b87a)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h47bd3d747ed79dc3 (wasm://wasm/ruffle_web.wasm-031e2676:wasm-function[6258]:0x7eb735)
    at ruffle_web.wasm.core::panicking::panic_fmt::hb859252f4b513814 (wasm://wasm/ruffle_web.wasm-031e2676:wasm-function[10192]:0x9273ff)
    at ruffle_web.wasm.core::ops::function::Fn::call::hc7414046003d97cc (wasm://wasm/ruffle_web.wasm-031e2676:wasm-function[6567]:0x80dd17)
    at ruffle_web.wasm.<T as wgpu::context::DynContext>::device_create_buffer::hceb34717d51400d4 (wasm://wasm/ruffle_web.wasm-031e2676:wasm-function[7484]:0x860eb3)
    at ruffle_web.wasm.<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::he8e48be358c30604 (wasm://wasm/ruffle_web.wasm-031e2676:wasm-function[1842]:0x4b3275)
    at ruffle_web.wasm.ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::h1a7776a9b08476f0 (wasm://wasm/ruffle_web.wasm-031e2676:wasm-function[7634]:0x8686c9)
    at ruffle_web.wasm.ruffle_render_wgpu::backend::WgpuRenderBackend<T>::register_shape_internal::h4bc75471b846f4b1 (wasm://wasm/ruffle_web.wasm-031e2676:wasm-function[1377]:0x3b6455)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00009BC5) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: "WebGL 2.0 (OpenGL ES 3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://www.quickflashgames.com/games/black-navy-war/
SWF URL: https://www.quickflashgames.com/static/swfs/black-navy-war/navalBattle.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-08-19
Channel: nightly
Built: 2024-08-19T00:05:58.171Z
Commit: cde0ef593c06dce85921f4e3ea590205f9ed464b
Is extension: false

# Metadata
width: 900
height: 550
frameRate: 25
numFrames: 2
swfVersion: 10
backgroundColor: #006600
isActionScript3: true
uncompressedLength: 2628412

**Comment by torokati44** [comment] 2024-08-23 11:46
Duplicate of https://github.com/ruffle-rs/ruffle/issues/14125.

**Closed by torokati44** 2024-08-23 11:46 UTC
Labels: error-report
