### ISSUE TITLE
Error on https://gamcore.com/games/breeding_season_6

### ISSUE THREAD

**Issue by ident2134** [ruffle-rs/ruffle#8738] opened 2022-12-11 14:40 UTC
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
    at W.n.wbg.__wbg_new_df6e6ab7a65c4c4d (https://fgn.cdn.serverable.com/common/flashes/js/ruffle221013/core.ruffle.c6fbe1d7464df286fdfb.js:1:6847)
    at std::sync::once::Once::call_once::{{closure}}::hf9ee3cf8881ab9cc (wasm://wasm/01803f76:wasm-function[1029]:0x2a2c96)
    at std::sync::once::Once::call_inner::hb30cfbde5209eed0 (wasm://wasm/01803f76:wasm-function[1493]:0x3285d3)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e53a26a8ce616de (wasm://wasm/01803f76:wasm-function[4921]:0x4875eb)
    at std::panicking::rust_panic_with_hook::hb09154fa23e06c37 (wasm://wasm/01803f76:wasm-function[3619]:0x4454f1)
    at core::panicking::panic_fmt::h9e229748e3ae9f9d (wasm://wasm/01803f76:wasm-function[5112]:0x48b363)
    at core::option::expect_failed::ha758e0d1c5165b94 (wasm://wasm/01803f76:wasm-function[5785]:0x49dc89)
    at ruffle_core::display_object::stage::Stage::root_clip::h29a98492982dd160 (wasm://wasm/01803f76:wasm-function[2795]:0x400780)
    at ruffle_core::display_object::movie_clip::MovieClip::is_button_mode::h7244e3f8087862dd (wasm://wasm/01803f76:wasm-function[899]:0x27be51)
    at ruffle_core::player::Player::update_mouse_state::h8c0c58581d5c0796 (wasm://wasm/01803f76:wasm-function[347]:0xdbc15)
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://gamcore.com/games/breeding_season_6
SWF URL: https://fgn.cdn.serverable.com/common/flashes/ff/b/breeding_season_6.swf?d=20150417204835

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 YaBrowser/22.11.0.2500 Yowser/2.5 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-13
Channel: nightly
Built: 2022-10-13T00:21:23.904Z
Commit: feda41d6c1e22027dbebfc157087050adc4a9acb
Is extension: false

# Metadata
width: 960
height: 720
frameRate: 28
numFrames: 2
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 18878952

**Comment by n0samu** [comment] 2023-01-22 01:31
Duplicate of #8344

**Closed by n0samu** 2023-01-22 01:31 UTC
Labels: duplicate, avm2, nsfw, error-report
