### ISSUE TITLE
Ruffle Error on https://freetennis.org/

### ISSUE THREAD

**Issue by ntua-el19089** [ruffle-rs/ruffle#16662] opened 2024-06-09 22:48 UTC
# Error Info
Error name: TypeError
Error message: NetworkError when attempting to fetch resource.

# Player Info
Allows script access: false

# Page Info
Page URL: https://freetennis.org/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by Croworbit** [comment] 2024-06-22 17:36
This website uses a version of ruffle from 2020, thats 4 years out of date!

they broke CORS, and they need to update their site and Ruffle. let them know!

**Comment by evilpie** [comment] 2024-06-22 20:32
Duplicate of #16705.

**Closed by evilpie** 2024-06-22 20:32 UTC
