### ISSUE TITLE
Error on https://game70421.konggames.com/games/BoMToons/chibi-knight/frame/1b2e1f76-f02a-4b5d-8292-f7c962b111c5/

### ISSUE THREAD

**Issue by zaepfe2** [ruffle-rs/ruffle#8883] opened 2022-12-21 20:32 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:760:32
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:760:32
    at D.n.wbg.__wbg_new_f9bb493369a83c12 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.b5d6ce968050f90fdce9.js:1:6507)
    at std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9 (wasm://wasm/018fcb8a:wasm-function[1102]:0x2aa466)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018fcb8a:wasm-function[1415]:0x31b27d)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542 (wasm://wasm/018fcb8a:wasm-function[5033]:0x4b585e)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018fcb8a:wasm-function[3756]:0x471db6)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018fcb8a:wasm-function[5275]:0x4ba6a9)
    at core::panicking::panic::h0859aaac783261b2 (wasm://wasm/018fcb8a:wasm-function[5087]:0x4b6790)
    at core::ops::function::FnOnce::call_once::h7337c1ac486f5426 (wasm://wasm/018fcb8a:wasm-function[1120]:0x2b005b)
    at ruffle_core::avm1::function::Executable::exec::h0481198b4eba6fc1 (wasm://wasm/018fcb8a:wasm-function[366]:0xeda9c)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h4be3085cc114bb53 (wasm://wasm/018fcb8a:wasm-function[1455]:0x323d14)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://game70421.konggames.com/games/BoMToons/chibi-knight/frame/1b2e1f76-f02a-4b5d-8292-f7c962b111c5/?kongregate_host=www.kongregate.com
SWF URL: https://game70421.konggames.com/gamez/0007/0421/live/beastgame_kong.swf?kongregate_game_version=1265086391

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-21
Channel: nightly
Built: 2022-12-21T00:16:40.503Z
Commit: 5cf5c8d5e5d3b37a38cf133aa587b7f925612f21
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 25
numFrames: 7
swfVersion: 9
backgroundColor: #666666
isActionScript3: false
uncompressedLength: 7891171

**Comment by n0samu** [comment] 2022-12-22 08:30
Duplicate of #3756

**Closed by n0samu** 2022-12-22 08:30 UTC
Labels: duplicate, error-report
