### ISSUE TITLE
Error on https://dethi.violet.vn/present/de-thi-hoc-ki-1-13307873.html

### ISSUE THREAD

**Issue by CatTuong06** [ruffle-rs/ruffle#5915] opened 2021-12-23 13:17 UTC
# Error Info
Error name: TypeError
Error message: Failed to construct 'Request': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
Error stack:
```
TypeError: Failed to construct 'Request': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new <anonymous> (https://dethi.violet.vn/opcode/dc299c9acef9f9bb317dcf1c3cc0f020_1636377889.js:18:907)
    at clsNew (https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=ER38S-PSpe1aUB2q9gXbjtv6t0fOK7khA9ffCeJUV6dFGWi5-Y4a8vwkFyE-iqTkKqUar4qHggpuR3vau6hFjASqg5lTh17vhup8BzBuZNY:2773:48)
    at window.fetch (https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=ER38S-PSpe1aUB2q9gXbjtv6t0fOK7khA9ffCeJUV6dFGWi5-Y4a8vwkFyE-iqTkKqUar4qHggpuR3vau6hFjASqg5lTh17vhup8BzBuZNY:2776:34)
    at r (<anonymous>:3:32212)
    at i (<anonymous>:3:34497)
    at i.next (<anonymous>)
    at a (<anonymous>:3:34625)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://dethi.violet.vn/present/de-thi-hoc-ki-1-13307873.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-13
Channel: nightly
Built: 2021-02-13T00:18:58.887Z
Commit: bb89391f3a86c0ef0fee43a57e3905dfbcf76c49

**Comment by Poopooracoocoo** [comment] 2021-12-23 14:06
Thanks for the report! It looks like you're using an outdated version of the Chrome extension. You can install the extension from the Chrome Web Store for automatic updates here: https://chrome.google.com/webstore/detail/ruffle/donbcfbmhbcapadipfkeojnmajbakjdc

When did you see this error?

**Comment by Poopooracoocoo** [comment] 2021-12-29 08:30
As I couldn't reproduce the error in the report on the latest version of the Ruffle extension and you have not provided further information, I'm closing this issue.

**Closed by Poopooracoocoo** 2021-12-29 08:30 UTC
Labels: error-report

**Comment by n0samu** [comment] 2022-10-04 06:58
Duplicate of #3337
