### ISSUE TITLE
Error on https://monkey3three.github.io/unblocked88.github.io/flash/flash%20pages/Electric%20Man%202.html

### ISSUE THREAD

**Issue by Eli-M0DS** [ruffle-rs/ruffle#8924] opened 2022-12-26 06:26 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:810:33
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:810:33
    at W.n.wbg.__wbg_new_f9bb493369a83c12 (https://monkey3three.github.io/unblocked88.github.io/ruffle/ruffle-nightly-2022_11_08-web-selfhosted/core.ruffle.15d3cd80be6c5f7a0ae1.js:1:6507)
    at std::sync::once::Once::call_once::{{closure}}::h92d611163c02d6f2 (wasm://wasm/01847dda:wasm-function[837]:0x25e04e)
    at std::sync::once::Once::call_inner::h34aee843864daceb (wasm://wasm/01847dda:wasm-function[1354]:0x311fd8)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf882ed1c291d5cd1 (wasm://wasm/01847dda:wasm-function[4883]:0x497ce5)
    at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/01847dda:wasm-function[3622]:0x45855a)
    at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/01847dda:wasm-function[5106]:0x49c66b)
    at core::panicking::panic::h8af046397a2bf65d (wasm://wasm/01847dda:wasm-function[4935]:0x498b8f)
    at core::ops::function::FnOnce::call_once::hab129c8e1797f5bb (wasm://wasm/01847dda:wasm-function[1249]:0x2f4f8c)
    at ruffle_core::avm1::function::Executable::exec::h0bc1a98722b42bc5 (wasm://wasm/01847dda:wasm-function[355]:0xdd379)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h2e98fbe01f5c448d (wasm://wasm/01847dda:wasm-function[679]:0x215cbf)
```

# Player Info
Allows script access: true
Renderer: WebGL
Player type: Object
SWF URL: https://monkey3three.github.io/unblocked88.github.io/flash/flash game files/ElectricMan_2.swf
Param movie: https://monkey3three.github.io/unblocked88.github.io/flash/flash game files/ElectricMan_2.swf
Attribute 0: undefined
Attribute 1: undefined

# Page Info
Page URL: https://monkey3three.github.io/unblocked88.github.io/flash/flash%20pages/Electric%20Man%202.html
SWF URL: https://monkey3three.github.io/unblocked88.github.io/flash/flash%20game%20files/ElectricMan_2.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-08
Channel: nightly
Built: 2022-11-08T00:21:52.123Z
Commit: 9303304e3b239ce7eda9c7ac83bc9be5e30095a7
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3518459

**Comment by n0samu** [comment] 2022-12-26 06:45
Duplicate of #4932

**Closed by n0samu** 2022-12-26 06:45 UTC
Labels: duplicate, error-report
