### ISSUE TITLE
Error on https://www.twoplayergames.org/gameframe/electricman-2

### ISSUE THREAD

**Issue by Tetor14** [ruffle-rs/ruffle#10870] opened 2023-04-28 18:23 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:751:33
Error stack:
```
966/W/n.wbg.__wbg_new_f9bb493369a83c12@https://www.twoplayergames.org/dist/ruffle/core.ruffle.fe07824c1b902e12cdf0.js:1:6899
std::sync::once::Once::call_once::{{closure}}::hade171d180e8c1b3@:wasm-function[1059]:0x2a63ca
std::sync::once::Once::call_inner::h34aee843864daceb@:wasm-function[1352]:0x30d4c4
core::ops::function::FnOnce::call_once{{vtable.shim}}::h2b5ff8f72074c3e7@:wasm-function[4886]:0x497380
std::panicking::rust_panic_with_hook::h70a0e195f4db2a29@:wasm-function[3635]:0x458938
core::panicking::panic_fmt::h751be80779d42b53@:wasm-function[5116]:0x49beba
core::panicking::panic::h8af046397a2bf65d@:wasm-function[4938]:0x49822a
core::ops::function::FnOnce::call_once::h30d1d284d5fd9535@:wasm-function[1244]:0x2e495a
ruffle_core::avm1::function::Executable::exec::h21369c76f086a0ad@:wasm-function[355]:0xdc743
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::he8552b5e405132ad@:wasm-function[900]:0x26fed8
ruffle_core::avm1::activation::Activation::run_actions::h45eca0b81352d31f@:wasm-function[304]:0x289bd
ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::haa980951d8d738e5@:wasm-function[969]:0x289756
ruffle_core::player::Player::run_actions::h954ab84db9d5d27d@:wasm-function[442]:0x152838
ruffle_web::Ruffle::tick::h888878a53ecfea0c@:wasm-function[636]:0x1eaa47
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h4aa053802fae5111@:wasm-function[6015]:0x4b5af1
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h78c8747089155c4a@:wasm-function[5472]:0x4a570a
S@https://www.twoplayergames.org/dist/ruffle/core.ruffle.fe07824c1b902e12cdf0.js:1:2578
c@https://www.twoplayergames.org/dist/ruffle/core.ruffle.fe07824c1b902e12cdf0.js:1:2255

```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://www.twoplayergames.org/gameframe/electricman-2

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-12
Channel: nightly
Built: 2022-11-12T00:15:57.157Z
Commit: 08270efee72ab8fe31b1448d76bcda09c8af264e
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3609377

**Comment by danielhjacobs** [comment] 2023-04-28 18:44
Duplicate of #4932. Panic fixed by #9447. Remaining issues tracked in #9594. The website owner needs to upgrade to a more recent version of Ruffle, though the issues from #9594 will still affect this game.

**Closed** 2023-04-28 21:44 UTC
Labels: error-report
