### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by JasimAlrawie** [ruffle-rs/ruffle#17081] opened 2024-07-11 10:14 UTC
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/shader_job.rs:76:26:
Shader property is not an object
Error stack:
```
Error: panicked at core/src/avm2/globals/flash/display/shader_job.rs:76:26:
Shader property is not an object
    at imports.wbg.__wbg_new_28c511d9baebfa89 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/69.js:3701:21)
    at ruffle_web.wasm.js_sys::Error::new::hda2cb16801956d39 (wasm://wasm/ruffle_web.wasm-0335562e:wasm-function[12817]:0x9d9c81)
    at ruffle_web.wasm.core::ops::function::FnOnce::call_once{{vtable.shim}}::h4efee46b7e0e8825 (wasm://wasm/ruffle_web.wasm-0335562e:wasm-function[9848]:0x970aee)
    at ruffle_web.wasm.std::panicking::rust_panic_with_hook::h6731baa78621a747 (wasm://wasm/ruffle_web.wasm-0335562e:wasm-function[6498]:0x8642f5)
    at ruffle_web.wasm.core::panicking::panic_fmt::h5c7ce52813e94bcd (wasm://wasm/ruffle_web.wasm-0335562e:wasm-function[10248]:0x99acb4)
    at ruffle_web.wasm.core::panicking::panic_display::hbd841ae85eb3dff4 (wasm://wasm/ruffle_web.wasm-0335562e:wasm-function[9781]:0x968cdb)
    at ruffle_web.wasm.core::option::expect_failed::h637b3c5bf9792ea8 (wasm://wasm/ruffle_web.wasm-0335562e:wasm-function[10828]:0x9a55da)
    at ruffle_web.wasm.core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hf573e928ca688193 (wasm://wasm/ruffle_web.wasm-0335562e:wasm-function[1242]:0x397007)
    at ruffle_web.wasm.ruffle_core::avm2::globals::flash::display::shader_job::get_shader_args::h7ec2db93a2ccda91 (wasm://wasm/ruffle_web.wasm-0335562e:wasm-function[3418]:0x6b9c43)
    at ruffle_web.wasm.<ruffle_render::filters::Filter as ruffle_core::avm2::filters::FilterAvm2Ext>::from_avm2_object::hdecc3a564ecf5e46 (wasm://wasm/ruffle_web.wasm-0335562e:wasm-function[1661]:0x49c3be)
```
AVM2 stack:
```
    at flash.display::DisplayObject/flash::display::DisplayObject::filters()
    at Main/loadLevelBitmap()
    at Main/openMapArea()
    at Main/handleTownClick()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 Laptop GPU (0x000028E0) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: "WebGL 2.0 (OpenGL ES"
Adapter Driver Info: "3.0 Chromium)"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-07-11
Channel: nightly
Built: 2024-07-11T00:05:52.246Z
Commit: ac9b39a652dad703638a8e55507b6db9b2b7136f
Is extension: true

# Metadata
width: 700
height: 600
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 3366039

**Comment by n0samu** [comment] 2024-07-11 22:15
Hi @JasimAlrawie, what SWF were you trying to play when the error occurred?

**Comment by JasimAlrawie** [comment] 2024-07-12 00:00
this file
[boom boom.zip](https://github.com/user-attachments/files/16185044/boom.boom.zip)

**Comment by n0samu** [comment] 2024-07-12 00:08
Thank you! We will take a look. 👍

**Comment by n0samu** [comment] 2024-07-12 00:11
Looks like this is a duplicate of #14540

**Closed by n0samu** 2024-07-12 00:11 UTC
Labels: duplicate, avm2, error-report, pixelbender
