### ISSUE TITLE
Firefox on Mac OS 10.15 (probably webGL related)

### ISSUE THREAD

**Issue by m-pr** [ruffle-rs/ruffle#3602] opened 2021-03-10 16:08 UTC
Ruffle works fantastically well with the swf on other browsers (including Safari and Edge) however not on Firefox which has the panic below.
On the browser console there are also these errors and warnings before the Error:

Failed to create WebGL context: WebGL creation failed: 
\* GL error 0x500 occurred during WebGL context initialization! ruffle_web.js:1227:34
WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
ruffle_web.js:1163:16
WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
ruffle_web.js:1163:16
WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
ruffle_web.js:1163:16
WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
ruffle_web.js:1163:16
WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
ruffle_web.js:1163:16
New Ruffle instance created. ruffle-player.js:242:20
Loading SWF file lady_vanexxa.swf ruffle-player.js:353:28
WebGL warning: <Present>: Swap chain surface creation failed.
WebGL context was lost.
createVertexArrayOES: Extension is `invalidated`. ruffle_web.js:846:34
panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50

# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:490:50
Error stack:
```
e/a.wbg.__wbg_new_df6e6ab7a65c4c4d@http://ladyvanexxa.com/ruffle/ruffle.js:1:6553
std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[1470]:0x2bf922
std::sync::once::Once::call_inner::hd3d269a4946f2df2@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[1736]:0x2f13b0
core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5191]:0x3f85fe
std::panicking::rust_panic_with_hook::h4f753dc70b771d8e@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3951]:0x3c919f
std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[4672]:0x3eaf24
std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5563]:0x3fe337
rust_begin_unwind@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5434]:0x3fc944
core::panicking::panic_fmt::hbd8a975261a5f466@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5564]:0x3fe36d
core::option::expect_none_failed::hbea1e2e5b59d80cc@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[4786]:0x3ee7ae
ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::h069f458942a6718e@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[488]:0x1598cd
<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h353e2a55e38cb839@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[2239]:0x3393aa
ruffle_core::font::Font::from_swf_tag::h8607e7c852fc6430@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[1335]:0x2a1da1
ruffle_core::player::Player::load_device_font::h50d87852f4fd9d0f@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[1611]:0x2dbab4
ruffle_core::player::Player::set_root_movie::h0ed11f781c1e99ba@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[358]:0xda1a1
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbb975094f05fd263@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[630]:0x1b43af
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h53ea19816a78cf78@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[2003]:0x31a3bb
wasm_bindgen_futures::task::singlethread::Task::run::h2d2600d6417d225b@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3717]:0x3bb7ee
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h055a2f38412827c2@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3288]:0x39e25f
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb300b74b2a6d03b3@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5710]:0x3ffb43
T@http://ladyvanexxa.com/ruffle/ruffle.js:1:4192
a@http://ladyvanexxa.com/ruffle/ruffle.js:1:2840
promise callback*e/a.wbg.__wbg_then_dd3785597974798a@http://ladyvanexxa.com/ruffle/ruffle.js:1:29370
wasm_bindgen_futures::queue::Queue::push_task::hee840234ecae5330@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3856]:0x3c3d69
wasm_bindgen_futures::task::singlethread::Task::into_raw_waker::raw_wake::h1dde88f577dd6dec@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3632]:0x3b65d9
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::finish::hbcc173fe689f205a@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3219]:0x3990cd
<T as wasm_bindgen::closure::WasmClosureFnOnce<A,R>>::into_fn_mut::{{closure}}::h358c2899f996b95f@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5194]:0x3f86e0
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb300b74b2a6d03b3@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5710]:0x3ffb43
T@http://ladyvanexxa.com/ruffle/ruffle.js:1:4192
a@http://ladyvanexxa.com/ruffle/ruffle.js:1:2840
promise callback*e/a.wbg.__wbg_then_0f957e0f4c3e537a@http://ladyvanexxa.com/ruffle/ruffle.js:1:29447
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::h5df89263bb12263a@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[1883]:0x308936
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h5dc3d69d9861395a@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[784]:0x1fb913
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbb975094f05fd263@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[630]:0x1b3fd1
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h53ea19816a78cf78@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[2003]:0x31a3bb
wasm_bindgen_futures::task::singlethread::Task::run::h2d2600d6417d225b@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3717]:0x3bb7ee
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h055a2f38412827c2@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3288]:0x39e25f
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb300b74b2a6d03b3@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5710]:0x3ffb43
T@http://ladyvanexxa.com/ruffle/ruffle.js:1:4192
a@http://ladyvanexxa.com/ruffle/ruffle.js:1:2840
promise callback*e/a.wbg.__wbg_then_dd3785597974798a@http://ladyvanexxa.com/ruffle/ruffle.js:1:29370
wasm_bindgen_futures::queue::Queue::push_task::hee840234ecae5330@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3856]:0x3c3d69
wasm_bindgen_futures::task::singlethread::Task::into_raw_waker::raw_wake::h1dde88f577dd6dec@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3632]:0x3b65d9
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::finish::hbcc173fe689f205a@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3219]:0x3990cd
<T as wasm_bindgen::closure::WasmClosureFnOnce<A,R>>::into_fn_mut::{{closure}}::h358c2899f996b95f@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5194]:0x3f86e0
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb300b74b2a6d03b3@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5710]:0x3ffb43
T@http://ladyvanexxa.com/ruffle/ruffle.js:1:4192
a@http://ladyvanexxa.com/ruffle/ruffle.js:1:2840
promise callback*e/a.wbg.__wbg_then_0f957e0f4c3e537a@http://ladyvanexxa.com/ruffle/ruffle.js:1:29447
<wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::h5df89263bb12263a@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[1883]:0x308936
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h5dc3d69d9861395a@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[784]:0x1fb88d
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbb975094f05fd263@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[630]:0x1b3fd1
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h53ea19816a78cf78@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[2003]:0x31a3bb
wasm_bindgen_futures::task::singlethread::Task::run::h2d2600d6417d225b@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3717]:0x3bb7ee
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h055a2f38412827c2@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3288]:0x39e25f
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb300b74b2a6d03b3@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5710]:0x3ffb43
T@http://ladyvanexxa.com/ruffle/ruffle.js:1:4192
a@http://ladyvanexxa.com/ruffle/ruffle.js:1:2840
promise callback*e/a.wbg.__wbg_then_dd3785597974798a@http://ladyvanexxa.com/ruffle/ruffle.js:1:29370
wasm_bindgen_futures::queue::Queue::push_task::hee840234ecae5330@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3856]:0x3c3d69
wasm_bindgen_futures::task::singlethread::Task::spawn::h7b57cb3c3ccadcbe@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[3161]:0x394874
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::h82a36280ad4fe05d@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[5038]:0x3f4fa9
ruffle_core::player::Player::fetch_root_movie::h8010bcccfd85d5db@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[1424]:0x2b5c6c
ruffle_web::Ruffle::stream_from::h1fdd89fccb30fbaa@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[1189]:0x27ec37
ruffle_stream_from@http://ladyvanexxa.com/ruffle/dd4deafe3e1a001cabaa1ec665f4d103.wasm:wasm-function[4898]:0x3f1934
stream_from@http://ladyvanexxa.com/ruffle/ruffle.js:1:5023
load/<@http://ladyvanexxa.com/ruffle/ruffle.js:1:51076
a@http://ladyvanexxa.com/ruffle/ruffle.js:1:45147
promise callback*c@http://ladyvanexxa.com/ruffle/ruffle.js:1:45312
oe/<@http://ladyvanexxa.com/ruffle/ruffle.js:1:45323
oe@http://ladyvanexxa.com/ruffle/ruffle.js:1:45090
load@http://ladyvanexxa.com/ruffle/ruffle.js:1:49952
connectedCallback@http://ladyvanexxa.com/ruffle/ruffle.js:1:62325
Oe@http://ladyvanexxa.com/ruffle/ruffle.js:1:67165
Le@http://ladyvanexxa.com/ruffle/ruffle.js:1:68644
polyfill@http://ladyvanexxa.com/ruffle/ruffle.js:1:73239
init@http://ladyvanexxa.com/ruffle/ruffle.js:1:72392
EventListener.handleEvent*Be@http://ladyvanexxa.com/ruffle/ruffle.js:1:71783
negotiate@http://ladyvanexxa.com/ruffle/ruffle.js:1:73056
@http://ladyvanexxa.com/ruffle/ruffle.js:1:74028
@http://ladyvanexxa.com/ruffle/ruffle.js:1:74125
@http://ladyvanexxa.com/ruffle/ruffle.js:1:74129

```

# Player Info
Allows script access: true

# Page Info
Page URL: http://ladyvanexxa.com/
SWF URL: http://ladyvanexxa.com/lady_vanexxa.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-10
Channel: nightly
Built: 2021-03-10T00:18:18.876Z
Commit: 934f95cd52838387ea1281fbf72be81ffb8e7903

**Comment by relrelb** [comment] 2021-03-10 22:35
Duplicate of #1905?

**Closed** 2021-03-12 07:12 UTC
Labels: bug, duplicate
