### ISSUE TITLE
Error on https://dagobah.net/flash/zombie_kicker.swf

### ISSUE THREAD

**Issue by Holagrimola** [ruffle-rs/ruffle#6923] opened 2022-05-09 03:16 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create VAO"', render/webgl/src/lib.rs:494:50
Error stack:
```
r/c.wbg.__wbg_new_df6e6ab7a65c4c4d@https://dagobah.net/js/ruffle.js line 123 > srcScript:1:7036
std::sync::once::Once::call_once::{{closure}}::h5387044f596cf17b@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[1003]:0x2f5687
std::sync::once::Once::call_inner::h02a6489b0ecfb269@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[1322]:0x363092
core::ops::function::FnOnce::call_once{{vtable.shim}}::h4461033b8c8249d8@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[4587]:0x4ebe27
std::panicking::rust_panic_with_hook::h364974e717ed59ec@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[3245]:0x4a7005
rust_begin_unwind@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[4647]:0x4ee0b4
core::panicking::panic_fmt::hf69c8b08bc9d2ee5@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[4844]:0x4f8ac2
core::result::unwrap_failed::h694db13a45aa6740@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[3920]:0x4d48c5
ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::ha4c5197dc5c7413f@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[719]:0x25e12c
<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_glyph_shape::h0bbcf7ecf7272765@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[1831]:0x3f1fb1
ruffle_core::font::Font::from_swf_tag::h8d6a724c80233dae@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[895]:0x2c84b4
ruffle_core::player::Player::set_root_movie::h95892081fd34907e@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[354]:0xdfe79
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha7e4e54d8e438e0a@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[570]:0x1f4362
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbbd98f43e4e9d36c@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[1706]:0x3cab14
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h7205236d067cc311@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[1989]:0x40cdab
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hd152dc341c383afa@https://dagobah.net/js/ruffle.js line 123 > srcScript line 1 > WebAssembly.instantiate:wasm-function[4989]:0x4fab23
F@https://dagobah.net/js/ruffle.js line 123 > srcScript:1:3883
a@https://dagobah.net/js/ruffle.js line 123 > srcScript:1:2531

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://dagobah.net/flash/zombie_kicker.swf
SWF URL: https://dagobah.net/flashswf/zombie_kicker.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-03
Channel: nightly
Built: 2021-11-03T00:13:12.329Z
Commit: 6c7d10e4d49ef0e155bc8027b6371c1217031796
Is extension: false

**Comment by Herschel** [comment] 2022-05-09 03:47
Dupe of #1905

**Closed by Herschel** 2022-05-09 03:47 UTC
