### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by T1nKurStinkR** [ruffle-rs/ruffle#12575] opened 2023-08-05 10:53 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:3019:5
Error stack:
```
@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.18e89839c4257ed9f1ae.js:1:51458
wasm-stub@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hd045a4c294d004d3]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h2d3c5586175098d9]@[wasm code]
<?>.wasm-function[core::ops::function::Fn::call::hd443b09cf48d1745]@[wasm code]
<?>.wasm-function[wgpu::backend::direct::ErrorSinkRaw::handle_error::hdd0bde40b656d7fb]@[wasm code]
<?>.wasm-function[<T as wgpu::context::DynContext>::device_create_buffer::h1efd7709d3deb773]@[wasm code]
<?>.wasm-function[<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::h6b3c857dbc35ec52]@[wasm code]
<?>.wasm-function[ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::ha275f95e97b4938c]@[wasm code]
<?>.wasm-function[<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_shape::ha6a0d21292358942]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::hdef1f0ab15debc66]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h216aec2620bf1294]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h8fba5a4973e43f72]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::he098d3773fee7c4f]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hf15465a0b3b9a061]@[wasm code]
wasm-stub@[wasm code]
v@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.18e89839c4257ed9f1ae.js:1:2759
f@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.18e89839c4257ed9f1ae.js:1:2512
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Apple GPU"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1691154295%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F695000%2F695785_final.swf%3F1498880771%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2264ce2984ec5d5%22%2C%22NewgroundsAPI_SessionID%22%3A%22Uky4bMNm18PDzaMZ2DrPf0f0f1399685d429debb843abb7242d8692327d5UqKC%22%2C%22NewgroundsAPI_UserName%22%3A%22IzaMehMax%22%2C%22NewgroundsAPI_UserID%22%3A8502234%2C%22ng_username%22%3A%22IzaMehMax%22%7D%2C%22width%22%3A720%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fimg.ngfiles.com%2Fdefaults%2Ficon-portal-xl-a.gif%3Ff1601395813%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/695000/695785_final.swf?1498880771

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15
Platform: MacIntel
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-04
Channel: nightly
Built: 2023-08-04T00:19:39.973Z
Commit: 5f200dc2a9fd992575c4bb5c49973f203cccf43a
Is extension: false

# Metadata
width: 720
height: 480
frameRate: 12
numFrames: 3386
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 30806799

**Comment by Lord-McSweeney** [comment] 2023-08-05 10:53
Duplicate of #12574.

**Closed by Lord-McSweeney** 2023-08-05 10:53 UTC
Labels: error-report
