### ISSUE TITLE
Games - 8 Planet - Arantius.com https://games.arantius.com/game.86.8+planet.html

### ISSUE THREAD

**Issue by cmlad26** [ruffle-rs/ruffle#3271] opened 2021-02-15 11:56 UTC
![image](https://user-images.githubusercontent.com/76111979/107943516-7fcec680-6f95-11eb-8aaa-7ef81b69122e.png)
After the first level games does not pass to the next one.

**Comment by n0samu** [comment] 2023-06-21 06:56
Duplicate of #2840

**Closed by n0samu** 2023-06-21 06:56 UTC
Labels: duplicate
