### ISSUE TITLE
Error on https://games.crazygames.com/en_US/electric-man/index.html

### ISSUE THREAD

**Issue by VlassicFreak** [ruffle-rs/ruffle#6309] opened 2022-02-17 15:50 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (https://files.crazygames.com/gameframe/ruffle/2022-01-11/ruffle.js:1:7158)
    at std::sync::once::Once::call_once::{{closure}}::hd1b4f64c6a058fdf (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[995]:0x2f58da)
    at std::sync::once::Once::call_inner::hf9144d66ddc67dec (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[1189]:0x33b8db)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h7c91d9e8737f5a50 (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[4699]:0x505559)
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[3242]:0x4b1ba1)
    at rust_begin_unwind (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[4766]:0x506d72)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[4978]:0x511c44)
    at core::panicking::panic::hec1fc057bd0baf0b (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[4696]:0x504dbf)
    at core::ops::function::FnOnce::call_once::h83f26a94bb6d39f3 (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[1047]:0x312862)
    at ruffle_core::avm1::function::Executable::exec::h00e69fc62e0063bd (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[432]:0x15c34e)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hb9b7718bdaa24753 (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[916]:0x2c9342)
    at ruffle_core::avm1::activation::Activation::do_action::hd77286bc08b0c311 (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[312]:0x21bee)
    at ruffle_core::avm1::activation::Activation::run_actions::h6609057211ea0f83 (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[2849]:0x48e34f)
    at ruffle_core::avm1::Avm1::run_stack_frame_for_action::hb499ce5ef9c78c8e (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[1158]:0x33367f)
    at ruffle_core::player::Player::run_actions::h5eea8b3801b1d5ae (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[463]:0x1802c5)
    at ruffle_web::Ruffle::tick::h8820f05fbb36117f (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[591]:0x1ef8d0)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h0fd3c78b3db543bb (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[5563]:0x51e4e7)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h546afa1d1f99eb9c (https://files.crazygames.com/gameframe/ruffle/2022-01-11/42ef41f25116839c8e75.wasm:wasm-function[5122]:0x513d54)
    at x (https://files.crazygames.com/gameframe/ruffle/2022-01-11/ruffle.js:1:2659)
    at a (https://files.crazygames.com/gameframe/ruffle/2022-01-11/ruffle.js:1:2535)
    at r (https://gameframe.crazygames.com/crazygames-gameframe-v1.bundle.js:2:74144)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://games.crazygames.com/en_US/electric-man/index.html
SWF URL: https://files.crazygames.com/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-11
Channel: nightly
Built: 2022-01-11T00:13:04.329Z
Commit: b39ab9034c5bff008a6cff32d0890e5d4cc0942b
Is extension: false

**Comment by relrelb** [comment] 2022-02-17 17:39
Duplicate of #4932.

**Closed by relrelb** 2022-02-17 17:39 UTC
Labels: error-report
