### ISSUE TITLE
Error on https://www.anafolie.net/anafolie.php?action=espacedemo

### ISSUE THREAD

**Issue by robertdu86** [ruffle-rs/ruffle#2808] opened 2021-01-24 11:01 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.anafolie.net/anafolie.php?action=espacedemo
SWF URL: https://www.anafolie.net/30tir_preload.swf?alea=1611486077

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-24
Channel: nightly
Built: 2021-01-24T01:05:42.228Z
Commit: 86b4c20809d8778d498474a26601aeda4cec87c4

**Comment by n0samu** [comment] 2022-10-23 22:44
Duplicate of #2495

**Closed by n0samu** 2022-10-23 22:44 UTC
Labels: duplicate, error-report
