### ISSUE TITLE
Error on https://www.flashgames.it/sexy.maid.nude.html

### ISSUE THREAD

**Issue by Furia2022** [ruffle-rs/ruffle#6770] opened 2022-04-21 12:29 UTC
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
@https://www.flashgames.it/js/ruffle/ruffle.js:1:6808
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h02eac160d339afc2]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h123718ba3bf480af]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_fmt::h96153d9dc0e882ed]@[wasm code]
<?>.wasm-function[std::thread::local::LocalKey<T>::with::ha706aae5b9bcb9bd]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::hc579618b4ad6cfcd]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hfc6d3990177bfa48]@[wasm code]
wasm-stub@[native code]
F@https://www.flashgames.it/js/ruffle/ruffle.js:1:3708
a@https://www.flashgames.it/js/ruffle/ruffle.js:1:2841
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.flashgames.it/sexy.maid.nude.html
SWF URL: https://www.flashgames.it/giochi/sexy/sexy.maid.nude/game.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-11
Channel: nightly
Built: 2021-02-11T00:18:16.959Z
Commit: 09c6def7f0df64f3868631be6b2c188c6b61ae75

**Comment by n0samu** [comment] 2024-06-23 23:36
Likely duplicate of #6608

**Closed by n0samu** 2024-06-23 23:36 UTC
Labels: nsfw, error-report
