### ISSUE TITLE
Error on https://evilgames.eu/flashgames/hedgehog-launch-2.htm

### ISSUE THREAD

**Issue by trenton-telge** [ruffle-rs/ruffle#2474] opened 2021-01-13 20:10 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:67736
    at Array.forEach (<anonymous>)
    at Object.yi.f.wasm (<anonymous>:3:67344)
    at <anonymous>:3:35282
    at Array.reduce (<anonymous>)
    at Function.yi.e (<anonymous>:3:35259)
    at i (<anonymous>:3:6444)
    at i.next (<anonymous>)
    at <anonymous>:3:6744
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: ../swf/hedgehog-launch-2.swf
Param wmode: direct
Param quality: high
Param allowNetworking: internal
Param AllowScriptAccess: never
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://evilgames.eu/flashgames/hedgehog-launch-2.htm

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by Futurama39** [comment] 2021-01-13 20:17
Here's a full dump at least running Chrome 2020-01-12, firefox wouldn't load it at all.

`Some messages have been moved to the Issues panel.
VM41:3 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-G1BR0wU4PZyN/xje5UjmpZbkO0q6sDomFK2DT81svxA='), or a nonce ('nonce-...') is required to enable inline execution.

773 @ VM41:3
yi @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ lv0.js:1
VM41:3 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-LFa4MDXJh14vo1T5I97V1Q+E6rVyAjSRq0iwsfD/v0M='), or a nonce ('nonce-...') is required to enable inline execution.

773 @ VM41:3
yi @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ lv0.js:1
VM41:3 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-BNbTB+U4kp+dbS5xzn5xKnJ6dkwb7jCMKLNYurECToc='), or a nonce ('nonce-...') is required to enable inline execution.

773 @ VM41:3
yi @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ lv0.js:1
VM41:3 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-ZdHxw9eWtnxUb3mk6tBS+gIiVUPE3pGM470keHPDFlE='), or a nonce ('nonce-...') is required to enable inline execution.

773 @ VM41:3
yi @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ lv0.js:1
VM41:3 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-q1iyMH6QLH5mE7/qInp59V8OYLknVfky+ZimhyvRDuw='), or a nonce ('nonce-...') is required to enable inline execution.

W @ VM41:3
(anonymous) @ VM41:3
polyfill @ VM41:3
init @ VM41:3
VM41:3 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.

W @ VM41:3
(anonymous) @ VM41:3
polyfill @ VM41:3
init @ VM41:3
VM41:3 Serious error loading Ruffle: CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
(anonymous) @ VM41:3
Promise.catch (async)
(anonymous) @ VM41:3
(anonymous) @ VM41:3
p @ VM41:3
ensureFreshInstance @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
p @ VM41:3
load @ VM41:3
connectedCallback @ VM41:3
W @ VM41:3
(anonymous) @ VM41:3
polyfill @ VM41:3
init @ VM41:3
setTimeout (async)
o @ VM41:3
negotiate @ VM41:3
773 @ VM41:3
yi @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ lv0.js:1
async function (async)
(anonymous) @ lv0.js:1
(anonymous) @ lv0.js:1
s @ lv0.js:1
VM41:3 Serious error occurred loading SWF file: CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
(anonymous) @ VM41:3
s @ VM41:3
Promise.then (async)
a @ VM41:3
(anonymous) @ VM41:3
p @ VM41:3
load @ VM41:3
connectedCallback @ VM41:3
W @ VM41:3
(anonymous) @ VM41:3
polyfill @ VM41:3
init @ VM41:3
setTimeout (async)
o @ VM41:3
negotiate @ VM41:3
773 @ VM41:3
yi @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ lv0.js:1
async function (async)
(anonymous) @ lv0.js:1
(anonymous) @ lv0.js:1
s @ lv0.js:1
VM41:3 Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:67736
    at Array.forEach (<anonymous>)
    at Object.yi.f.wasm (<anonymous>:3:67344)
    at <anonymous>:3:35282
    at Array.reduce (<anonymous>)
    at Function.yi.e (<anonymous>:3:35259)
    at i (<anonymous>:3:6444)
    at i.next (<anonymous>)
    at <anonymous>:3:6744
    at new Promise (<anonymous>)
(anonymous) @ VM41:3
yi.f.wasm @ VM41:3
(anonymous) @ VM41:3
yi.e @ VM41:3
i @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
a @ VM41:3
k @ VM41:3
P @ VM41:3
fromNativeObjectElement @ VM41:3
W @ VM41:3
(anonymous) @ VM41:3
polyfill @ VM41:3
init @ VM41:3
Promise.then (async)
a @ VM41:3
(anonymous) @ VM41:3
p @ VM41:3
load @ VM41:3
connectedCallback @ VM41:3
W @ VM41:3
(anonymous) @ VM41:3
polyfill @ VM41:3
init @ VM41:3
setTimeout (async)
o @ VM41:3
negotiate @ VM41:3
773 @ VM41:3
yi @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ VM41:3
(anonymous) @ lv0.js:1
async function (async)
(anonymous) @ lv0.js:1
(anonymous) @ lv0.js:1
s @ lv0.js:1
`

From the error name probably realted with #2201 ?

**Comment by relrelb** [comment] 2021-02-12 23:52
Duplicate of #2201.

**Closed by relrelb** 2021-02-12 23:52 UTC
