### ISSUE TITLE
Error on https://www.gameflare.com/embed/castaway/

### ISSUE THREAD

**Issue by littlerook04** [ruffle-rs/ruffle#8641] opened 2022-11-30 01:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/bitmap/bitmap_data.rs:1014:22
Error stack:
```
@https://www.gameflare.com/emulators/ruffle/core.ruffle.73cd4b2216766003e577.js:1:7398
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h73fc39b54ec29717]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hb30cfbde5209eed0]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d648d6ec080e3d2]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::hb09154fa23e06c37]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h9e229748e3ae9f9d]@[wasm code]
<?>.wasm-function[core::result::unwrap_failed::h5da0ab182d2c24a1]@[wasm code]
<?>.wasm-function[ruffle_core::bitmap::bitmap_data::BitmapData::draw::h73fe75191fcb268e]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::globals::bitmap_data::draw::h3741067adbf98faa]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::ha1ebff59d66588d4]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h6e117415f5d8a106]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::hdebc2c5fe73d0130]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::ha1ebff59d66588d4]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h6e117415f5d8a106]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::hdebc2c5fe73d0130]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::function::Executable::exec::ha1ebff59d66588d4]@[wasm code]
<?>.wasm-function[<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h6e117415f5d8a106]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::activation::Activation::run_actions::hdebc2c5fe73d0130]@[wasm code]
<?>.wasm-function[ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h1cd5d8b6421fbd27]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::run_actions::hd7afab17e4eeb759]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h6af632469979f791]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h60d726a424d28b1d]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h970c39b503fdbae6]@[wasm code]
wasm-stub@[native code]
T@https://www.gameflare.com/emulators/ruffle/core.ruffle.73cd4b2216766003e577.js:1:3033
c@https://www.gameflare.com/emulators/ruffle/core.ruffle.73cd4b2216766003e577.js:1:2485
```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://www.gameflare.com/embed/castaway/
SWF URL: https://data.gameflare.com/games/687/NvhdQfTou1kTn8.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-28
Channel: nightly
Built: 2022-09-28T00:21:21.396Z
Commit: 5ac4f4358d01724da72d46ab29014b9a51a411cb
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 5
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 7975889

**Comment by n0samu** [comment] 2022-11-30 05:58
Duplicate of #8016. This problem has already been fixed by #8317. Please contact the website owner and ask them to update their copy of Ruffle.

**Closed by n0samu** 2022-11-30 05:58 UTC
Labels: duplicate, error-report
