### ISSUE TITLE
Error on https://gamesofdesired.com/2bfc24dc841a2647ae624d955c3eff4b-meet-and-pummel-lesbian-rail

### ISSUE THREAD

**Issue by BroIdkShutUp** [ruffle-rs/ruffle#6776] opened 2022-04-22 01:33 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.17.5/src/fill.rs:1924:56
Error stack:
```
@https://gamesofdesired.com/assets/ruffle/ruffle.js:1:7035
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h99e47643887ee5a5]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h03201bc01a0ed891]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hd44f353696296fec]@[wasm code]
<?>.wasm-function[core::panicking::panic::ha58827a77b951c10]@[wasm code]
<?>.wasm-function[core::slice::sort::shift_tail::h7506548c59681df0]@[wasm code]
<?>.wasm-function[core::slice::sort::recurse::h7e84012ff4121f8a]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::process_events::he93534a3cdb14d7a]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_impl::h79202e374f2fe70d]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_path::hf43baaeab0553f2a]@[wasm code]
<?>.wasm-function[ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::he06901c88d3868a1]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h127c2f4965b540b0]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h7cda84583092b1b3]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::hc1aa22a23a3780b3]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h5cc1cee597baa183]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h120ccdeae3267ee4]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h72d7af3bf06f1fd6]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4014bfc4ca727422]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h69dd9711782f1b19]@[wasm code]
wasm-stub@[native code]
T@https://gamesofdesired.com/assets/ruffle/ruffle.js:1:4274
a@https://gamesofdesired.com/assets/ruffle/ruffle.js:1:2799
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/3/1/7/31790f17171b24172575e9f64fa00dd6/31790f17171b24172575e9f64fa00dd6.swf
Param movie: https://v8p5i7f9.ssl.hwcdn.net/games/swf/3/1/7/31790f17171b24172575e9f64fa00dd6/31790f17171b24172575e9f64fa00dd6.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Param SCALE: default
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://gamesofdesired.com/2bfc24dc841a2647ae624d955c3eff4b-meet-and-pummel-lesbian-rail
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/3/1/7/31790f17171b24172575e9f64fa00dd6/31790f17171b24172575e9f64fa00dd6.swf

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-17
Channel: nightly
Built: 2021-06-17T00:11:56.220Z
Commit: 622f35eb713c224a980ab67eb251a4b6880e1834

**Comment by torokati44** [comment] 2022-04-29 08:30
#6608 can be related.

**Comment by n0samu** [comment] 2022-05-20 16:49
Duplicate of #6608. Updating your device to iOS 15.5 should fix the issue!

**Closed by n0samu** 2022-05-20 16:49 UTC
Labels: nsfw, error-report
