### ISSUE TITLE
Error on https://www.crazymonkeygames.com/Boxhead-the-Nightmare.html

### ISSUE THREAD

**Issue by LesleyGrossman** [ruffle-rs/ruffle#11270] opened 2023-05-29 14:21 UTC
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
    at W.n.wbg.__wbg_new_87297f22973157c8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.6392c618460af42080b4.js:1:51142)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf586b8fd5967b71f (wasm://wasm/02c3fd4a:wasm-function[8634]:0x83080c)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c3fd4a:wasm-function[5629]:0x753fa3)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c3fd4a:wasm-function[8483]:0x82bb79)
    at alloc::raw_vec::capacity_overflow::h743526e95bf6b28b (wasm://wasm/02c3fd4a:wasm-function[8247]:0x825974)
    at alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h82b668b8e2729ec1 (wasm://wasm/02c3fd4a:wasm-function[5288]:0x73b51c)
    at <ruffle_core::avm2::object::array_object::ArrayObject as ruffle_core::avm2::object::TObject>::set_property_local::h62b7cad3a4b50c3a (wasm://wasm/02c3fd4a:wasm-function[2349]:0x547a6c)
    at ruffle_core::avm2::object::TObject::set_property::he55646085e773106 (wasm://wasm/02c3fd4a:wasm-function[2215]:0x5257d9)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::set_property::h0bd3d093556f77b9 (wasm://wasm/02c3fd4a:wasm-function[1826]:0x4a5a0c)
    at ruffle_core::avm2::activation::Activation::run_actions::h5b8a2740576f32f0 (wasm://wasm/02c3fd4a:wasm-function[512]:0x3c3c1)
```
AVM2 stack:
```
    at frontend.data::DataConnector/storeData()
    at frontend.data::FData$/firstTimeUnlocks()
    at frontend.data::FData/e_USER_DATA_LOADED()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at frontend.data::DataConnector/loadData()
    at frontend.data::DataConnector/getUserData()
    at frontend.data::FData/e_FILE_COMPLETE()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at frontend.data::FMedia/e_SWF_LOADED()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (ATI Technologies Inc., AMD Radeon RX 6900 XT OpenGL Engine, OpenGL 4.1)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 16384, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.crazymonkeygames.com/Boxhead-the-Nightmare.html
SWF URL: https://www.crazymonkeygames.com/swf-nr2kjn-jekb/secure_bxhnm.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-29
Channel: nightly
Built: 2023-05-29T00:19:07.550Z
Commit: 0955ab40e67d4668f3ebd5fbdf3602750e35abb8
Is extension: false

# Metadata
width: 760
height: 576
frameRate: 60
numFrames: 3
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 5592133

**Comment by n0samu** [comment] 2023-05-29 19:43
Duplicate of #11181

**Closed by n0samu** 2023-05-29 19:43 UTC
Labels: duplicate, error-report
