### ISSUE TITLE
Ruffle Error on https://e621.net/posts/361950?q=parent%3A349966

### ISSUE THREAD

**Issue by MasterBowser64** [ruffle-rs/ruffle#2542] opened 2021-01-15 08:48 UTC
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:64924
    at Array.forEach (<anonymous>)
    at Object.hi.f.wasm (<anonymous>:3:64532)
    at <anonymous>:3:33090
    at Array.reduce (<anonymous>)
    at Function.hi.e (<anonymous>:3:33067)
    at i (<anonymous>:3:6063)
    at i.next (<anonymous>)
    at <anonymous>:3:6363
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/361950?q=parent%3A349966

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-22
Channel: nightly
Built: 2020-12-22T00:39:03.522Z
Commit: f7797f85d6a2c340b0dfb97c42a3cc04be32b997

**Comment by Futurama39** [comment] 2021-01-15 08:52
Most probably a duplicate of #2201

**Comment by Toad06** [comment] 2021-01-15 08:58
Closing as per above comment. Thanks for reporting.

**Closed by Toad06** 2021-01-15 08:58 UTC

**Comment by SpaceWallaby936** [comment] 2024-10-24 00:24
no shame is crazy
