### ISSUE TITLE
Error on https://game115608.konggames.com/games/light_bringer777/learn-to-fly-2/frame/fa3a6e74-10d5-4973-b89c-0c9c533cb493/

### ISSUE THREAD

**Issue by code424arch** [ruffle-rs/ruffle#11173] opened 2023-05-22 17:47 UTC
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 0..5500 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.0/src/backend/direct.rs:3019:5
Error stack:
```
Error: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_buffer
    Copy error
    Copy of X 0..5500 would end up overrunning the bounds of the Source texture of X size 4096

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.0/src/backend/direct.rs:3019:5
    at W.n.wbg.__wbg_new_87297f22973157c8 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.5414b0614180f4f61fb1.js:1:50966)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hee170dc26e4169dd (wasm://wasm/02c1df5a:wasm-function[8612]:0x82a42c)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c1df5a:wasm-function[5567]:0x74b6b6)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c1df5a:wasm-function[8461]:0x8257c7)
    at core::ops::function::Fn::call::h83da12931ee08b01 (wasm://wasm/02c1df5a:wasm-function[5900]:0x760d12)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h27ddee42d4a7dd38 (wasm://wasm/02c1df5a:wasm-function[4402]:0x6e8b29)
    at wgpu::backend::direct::Context::handle_error_nolabel::h340dcc110411ef09 (wasm://wasm/02c1df5a:wasm-function[2821]:0x5d93a7)
    at <T as wgpu::context::DynContext>::command_encoder_copy_texture_to_buffer::h23c1f4950ae72b71 (wasm://wasm/02c1df5a:wasm-function[6100]:0x773498)
    at wgpu::CommandEncoder::copy_texture_to_buffer::hb39fde4264404deb (wasm://wasm/02c1df5a:wasm-function[5345]:0x739acf)
    at <ruffle_render_wgpu::QueueSyncHandle as ruffle_render::bitmap::SyncHandle>::retrieve_offscreen_texture::h166d8240a2024a79 (wasm://wasm/02c1df5a:wasm-function[1591]:0x45c353)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) HD Graphics 520 (SKL GT2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 1024, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game115608.konggames.com/games/light_bringer777/learn-to-fly-2/frame/fa3a6e74-10d5-4973-b89c-0c9c533cb493/?kongregate_host=www.kongregate.com
SWF URL: https://game115608.konggames.com/gamez/0011/5608/live/secure_Learn2Fly.swf?kongregate_game_version=1541118719

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-22
Channel: nightly
Built: 2023-05-22T00:19:58.859Z
Commit: 6ac4e5256da25d462f88bd85b23d6619ff70b2f0
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 33
numFrames: 46
swfVersion: 10
backgroundColor: #2379B1
isActionScript3: false
uncompressedLength: 7042769

**Comment by n0samu** [comment] 2023-05-22 20:56
Duplicate of #11171

**Closed by n0samu** 2023-05-22 20:56 UTC
Labels: duplicate, error-report
