### ISSUE TITLE
Error on https://hutao.biz/3/3.html

### ISSUE THREAD

**Issue by EmptySpace1** [ruffle-rs/ruffle#7128] opened 2022-06-01 15:11 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:853:18
    at c.wbg.__wbg_new_df6e6ab7a65c4c4d (https://hutao.biz/ruffle/core.ruffle.690378fd369af3b23308.js:1:7708)
    at std::sync::once::Once::call_once::{{closure}}::h802bfeb6f8bb5638 (https://hutao.biz/ruffle/b2f5e37372ebd0a36c16.wasm:wasm-function[1013]:0x2ac0f8)
    at std::sync::once::Once::call_inner::h07d0245bef259c27 (https://hutao.biz/ruffle/b2f5e37372ebd0a36c16.wasm:wasm-function[1443]:0x31f0a6)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h9ecdeaaea35085f8 (https://hutao.biz/ruffle/b2f5e37372ebd0a36c16.wasm:wasm-function[4918]:0x478da7)
    at std::panicking::rust_panic_with_hook::h623ac32ff431b114 (https://hutao.biz/ruffle/b2f5e37372ebd0a36c16.wasm:wasm-function[3238]:0x41b9ed)
    at core::panicking::panic_fmt::h5118e89563022e7e (https://hutao.biz/ruffle/b2f5e37372ebd0a36c16.wasm:wasm-function[5000]:0x47cc5a)
    at core::panicking::panic::he88f1b1582b09c8c (https://hutao.biz/ruffle/b2f5e37372ebd0a36c16.wasm:wasm-function[4916]:0x47893a)
    at core::ops::function::FnOnce::call_once::hea116a8eeeb59311 (https://hutao.biz/ruffle/b2f5e37372ebd0a36c16.wasm:wasm-function[1093]:0x2c28a4)
    at ruffle_core::avm1::function::Executable::exec::h0a1a3c56ef393e7a (https://hutao.biz/ruffle/b2f5e37372ebd0a36c16.wasm:wasm-function[394]:0x134514)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf21230a28d8729f3 (https://hutao.biz/ruffle/b2f5e37372ebd0a36c16.wasm:wasm-function[381]:0x11a4a3)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://hutao.biz/3/3.html#https://hutao.biz/theatre/flash/electricman2.swf
SWF URL: https://hutao.biz/theatre/flash/electricman2.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14588.123.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.72 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-04-19
Channel: nightly
Built: 2022-04-19T00:15:10.342Z
Commit: c1b74f1b01ed88d67df34359f07e7aab3dd49209
Is extension: false

**Comment by relrelb** [comment] 2022-06-01 18:56
Duplicate of #4932.

**Closed by relrelb** 2022-06-01 18:56 UTC
Labels: error-report
