### ISSUE TITLE
Error on https://radzo73.github.io/fparchive/Legacy%20Branch/FPAW2.html

### ISSUE THREAD

**Issue by kikenspeedruns** [ruffle-rs/ruffle#4906] opened 2021-07-21 11:18 UTC
**Describe the bug**
The backgrounds and most objects for the game are broken and appear either black or grey (for backgrounds, the objects are non existent). and if I load a level enough times, the page crashes with error code: SBOX_FATAL_RAM_EXCEEDED.

**Expected behavior**
The level loads normally and the other sprites are viewable. This happens on the self hosted and extension version.

**What platform are you using?**
Windows 10, Google Chrome Version 91.0.4472.164 (Official Build) (64-bit), I wasn't using mobiile

**Comment by relrelb** [comment] 2021-08-07 16:18
Duplicate of #4646.

**Closed by relrelb** 2021-08-07 16:18 UTC
Labels: bug
