### ISSUE TITLE
onSoundComplete doesn't fire when a sound completes

### ISSUE THREAD

**Issue by PastoTreering** [ruffle-rs/ruffle#2604] opened 2021-01-18 03:14 UTC
To reproduce: Have a dynamically played sound triggered via sound.start() also have an onSoundComplete callback from the same sound. Anything in the onSoundComplete callback will not fire.

Sample code to reproduce:
```
s = new Sound();
s.attachSound("splode");

s.start();
s.onSoundComplete = function() {
	trace("done!");
	clipper._x = 0;
	clipper._y = 0;
}
```

Demo File: https://www.newgrounds.com/projects/games/1580899/preview
In flash, the red square shows up in the upper left when the sound completes. In Ruffle, nothing happens (not even an error log in the console).

**Comment by relrelb** [comment] 2021-01-18 05:32
Duplicate of #396.

**Comment by Herschel** [comment] 2021-01-19 03:35
Closing in favor of #396

**Closed by Herschel** 2021-01-19 03:35 UTC
Labels: duplicate
