### ISSUE TITLE
Error on https://www.gamezhero.com/get-game-code/4c40792e5998965f300247b4b43a879b

### ISSUE THREAD

**Issue by 4kh00** [ruffle-rs/ruffle#15048] opened 2024-02-01 00:19 UTC
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero

Error stack:
```
Error: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero


    at imports.wbg.__wbg_new_3a66822ed076951c (chrome-extension://pipjjbgofgieknlpefmcckdmgaaegban/dist/339.js:3175:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h61e7c84c3ecc6317 (wasm://wasm/0380b3f2:wasm-function[11293]:0xa76188)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (wasm://wasm/0380b3f2:wasm-function[6894]:0x936193)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (wasm://wasm/0380b3f2:wasm-function[11007]:0xa6f78a)
    at core::ops::function::Fn::call::h06a8cd986a8df014 (wasm://wasm/0380b3f2:wasm-function[7193]:0x94c39e)
    at wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error::h022f3325cf226bbf (wasm://wasm/0380b3f2:wasm-function[5724]:0x8c9aee)
    at <T as wgpu::context::DynContext>::device_create_texture::h26deafbb6f273bc6 (wasm://wasm/0380b3f2:wasm-function[7561]:0x968119)
    at wgpu::Device::create_texture::he5698963b98551be (wasm://wasm/0380b3f2:wasm-function[6066]:0x8e7ab1)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_bitmap::h54292bc35922c6d5 (wasm://wasm/0380b3f2:wasm-function[2384]:0x617fb8)
    at ruffle_core::bitmap::bitmap_data::BitmapData::bitmap_handle::h866a005597b20e00 (wasm://wasm/0380b3f2:wasm-function[1780]:0x4f74b1)
```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::draw()
    at com.emibap.textureAtlas::DynamicAtlas$/drawItem()
    at com.emibap.textureAtlas::DynamicAtlas$/fromMovieClipContainer()
    at Asset$/loadAtlas()
    at Asset$/init()
    at Classes$/init()
    at MainMenu()
    at starling.core::Starling/initializeRoot()
    at starling.core::Starling/initialize()
    at starling.core::Starling/onContextCreated()
    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
    at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
    at MethodInfo-1885()
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 Laptop GPU (0x000028E0) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(FLOAT32_FILTERABLE | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)
Player type: Object
SWF URL: //files.gamezhero.com/game/d54/4cb/d544cb609cf940f8/data/precivilizationmarbleagegreeceedition.swf
Param allowfullscreen: true
Param swliveconnect: true
Param allowscriptaccess: always
Param wmode: direct
Param base: //files.gamezhero.com/game/d54/4cb/d544cb609cf940f8/data/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.gamezhero.com/get-game-code/4c40792e5998965f300247b4b43a879b
SWF URL: https://files.gamezhero.com/game/d54/4cb/d544cb609cf940f8/data/precivilizationmarbleagegreeceedition.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-24
Channel: nightly
Built: 2024-01-24T00:16:08.770Z
Commit: a916f6e7a2b76fc211c568aa6b63bb9d8dc76a01
Is extension: true

# Metadata
width: 800
height: 533
frameRate: 30
numFrames: 2
swfVersion: 34
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 9733381

**Comment by evilpie** [comment] 2024-02-01 20:37
Duplicate of #13946.

**Closed as not planned by evilpie** 2024-02-01 20:37 UTC
Labels: bug, render-wgpu, error-report
