### ISSUE TITLE
Error on https://flashstorage.games/embed/electric-man-2

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#8075] opened 2022-09-24 17:55 UTC
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:818:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:818:18
    at e.wbg.__wbg_new_df6e6ab7a65c4c4d (https://flashstorage.games/public/js/ruffle/core.ruffle.3beacba57a0d16850cf5.js:1:7523)
    at std::sync::once::Once::call_once::{{closure}}::h9b662bb03984fbef (wasm://wasm/016b6b7e:wasm-function[1432]:0x30a9bf)
    at std::sync::once::Once::call_inner::h00971925aa1adad3 (wasm://wasm/016b6b7e:wasm-function[1385]:0x2fdee0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h2bb213d101087fa9 (wasm://wasm/016b6b7e:wasm-function[4794]:0x444714)
    at std::panicking::rust_panic_with_hook::h84feca33bd4bd229 (wasm://wasm/016b6b7e:wasm-function[3524]:0x40b2e0)
    at core::panicking::panic_fmt::hc171d095bc4a492d (wasm://wasm/016b6b7e:wasm-function[4972]:0x449fce)
    at core::panicking::panic::h3b7a8a1eaf47fc0f (wasm://wasm/016b6b7e:wasm-function[4881]:0x445f2b)
    at core::ops::function::FnOnce::call_once::h70b0977f78d3492f (wasm://wasm/016b6b7e:wasm-function[1028]:0x28c482)
    at ruffle_core::avm1::function::Executable::exec::h7a348dfa734176a3 (wasm://wasm/016b6b7e:wasm-function[352]:0xd5997)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h571f4d23a417479a (wasm://wasm/016b6b7e:wasm-function[793]:0x229b56)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://flashstorage.games/embed/electric-man-2
SWF URL: https://flashstorage.games/public/storage/games/November2021/iKueKPLrtlE2EsRtE6AZ.swf?at=2022-09-24%2009:40:59

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.42
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-08-27
Channel: nightly
Built: 2022-08-27T00:18:46.959Z
Commit: c008cc4dea87aade184466fce5b44f613cda94d9
Is extension: false

# Metadata
width: 640
height: 400
frameRate: 18
numFrames: 36
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 3575587

**Comment by n0samu** [comment] 2022-09-24 18:52
Duplicate of #4932

**Closed by n0samu** 2022-09-24 18:52 UTC
Labels: duplicate, error-report
